### PR TITLE
[Merged by Bors] - Fix material alpha_mode in example global_vs_local_translation

### PR DESCRIPTION
**Pull request by holyfight6**
# Objective

The global_vs_local_translation example tries to use transparency to identify static cubes, but the materials of those cubes aren't transparent.

## Solution

Change material alpha_mode to  `AlphaMode::Blend` for those cubes.

### CODE REVIEW

**Comment by nicopap** [comment]
`global_vs_local_translation` does not use transparency in any way? I'm not sure where you got this idea. I'm running the example on `main` and on your branch and I see no difference.

Could you explain better why you think adding `AlphaMode::Blend` is needed?

**Review by nicopap — APPROVED** [review]
Thank for the update, it makes the example much clearer!

**Comment by holyfight6** [comment]
@nicopap See the comments in `toggle_movement` system, it uses transparency to indicate which cubes can be moved

**Comment by nicopap** [comment]
@holyfight6 It was my bad, I totally see the interest of this PR now. Thanks.

**Review by james7132 — APPROVED** [review]

**Comment by holyfight6** [comment]
The ci build failed at some PPA error, has it been fixed now?

**Comment by alice-i-cecile** [comment]
Yep, looks fixed.

bors r+

**Pull request closed without merging**
