### PR TITLE
Simple Implementation to address #1327 by adding a focused field to the window and related system

### PR DESCRIPTION
**Pull request by huhlig**

### CODE REVIEW

**Comment by cart** [comment]
For window state like this, we generally try to set it directly in the window backend to ensure state is updated immediately. Can you set window.focused here instead?
 (see some of the other events for examples)
https://github.com/bevyengine/bevy/blob/c87d4c110f60fc0a92c2b37d999e1787a303f1c5/crates/bevy_winit/src/lib.rs#L410

**Comment by huhlig** [comment]
> For window state like this, we generally try to set it directly in the window backend to ensure state is updated immediately. Can you set window.focused here instead?
> (see some of the other events for examples)
> https://github.com/bevyengine/bevy/blob/c87d4c110f60fc0a92c2b37d999e1787a303f1c5/crates/bevy_winit/src/lib.rs#L410

Changed to more match the existing updates. I was attempting to minimize the impact of the change but this way makes more sense.

**Comment by cart** [comment]
Remove the unused imports reported by clippy and we're good to go!

**Comment by huhlig** [comment]
Let me know if there are any other changes I should make to the PR.

**Comment by cart** [comment]
Haha automated rebase failed for some reason (it doesn't like that its on the master branch?)

I'll just do it manually.

**Comment by algrn1406** [comment]
Y

**Pull request merged**
