### PR TITLE
[Merged by Bors] - Remove markdown dead link check

### LINKED ISSUE #4575: check-markdown-links is painfully flaky
This step of the CI is *incredibly* flaky (see https://github.com/bevyengine/bevy/pull/4469 for an example). Blocking merges is pointless friction, and confuses new contributors.

There are several options here:

1. Make sure the check doesn't block CI.
2. Use an alternative strategy for testing for dead links that is more reliable.
3. Somehow scope the check to only make sure it checks newly added or modified links.
4. Move dead linking to an action that is run once a day, with some form of alerting.

These are not mutually exclusive by any means. @mockersf, do you have preferences?

### PR DESCRIPTION
**Pull request by cart**
# Objective

This fails constantly and causes more pain than it is worth.

## Solution

Remove dead link checks.

Alternative to #4837, which is more granular but ironically still fails to build. I'm in favor of the nuclear option.

Fixes #4575

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Can you note that this fixes #4575?

**Review by james7132 — APPROVED** [review]
Probably should delete the config for the check as well. Under `.github/linters/markdown-link-check.json`

**Comment by cart** [comment]
Good call. I also removed the relevant bors line (which i totally missed).

**Pull request closed without merging**
