### PR TITLE
Update 2d examples: Bundle -> Components

### PR DESCRIPTION
**Pull request by skairunner**
Simple syntax fix. Bundles were renamed to components.

### CODE REVIEW

**Comment by mockersf** [comment]
hello 👋 

It's actually the other way around, `*Components` were renamed to `*Bundle`, and examples are updated for latest git version.

If you want to check examples for version 0.3, you should look at the `0.3.0` tag, for example https://github.com/bevyengine/bevy/blob/v0.3.0/examples/2d/sprite_sheet.rs

**Comment by memoryruins** [comment]
`*Bundle` is the current naming convention, not `*Components`.
 
https://github.com/bevyengine/bevy/blob/704a11677881e762415b15e384c1b7a05fee7c1e/crates/bevy_sprite/src/entity.rs#L16

If you’re using 0.3, make sure to use the examples under the [0.3 git tag](https://github.com/bevyengine/bevy/tree/v0.3.0/examples). A note about [here](https://github.com/bevyengine/bevy/tree/master/examples#%EF%B8%8F-note-for-users-of-releases-on-cratesio).

**Comment by skairunner** [comment]
👌

**Comment by memoryruins** [comment]
Ah looks like I was slower to respond :)

**Pull request closed without merging**
