### PR TITLE
[Merged by Bors] - Text pipeline benchmark

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Simple text pipeline benchmark. It's quite expensive but current examples don't capture the performance of `queue_text` as it only runs on changes to the text.

### CODE REVIEW

**Comment by ickshonpe** [comment]
Doesn't work, text isn't recomputed on changes to `Text2dBounds`.
Just working on the fix.

**Review by alice-i-cecile — APPROVED** [review]
Definitely pretty artificial, but it's nice to be able to isolate these things.

**Comment by ickshonpe** [comment]
> Definitely pretty artificial, but it's nice to be able to isolate these things.

It's weird I was worried I was being silly PRing this as it is really trivial, but it actually seems to cover some important edge cases that were hiding bugs.

**Review by superdump — APPROVED** [review]
bors r+

**Pull request closed without merging**
