### PR TITLE
Fix mouse behavior in scale_factor_override example

### LINKED ISSUE #7377: Mouse movement is sluggish in scale_factor_override example
## Bevy version

main

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

- `cargo run --example scale_factor_override` or
    `cargo run --example scale_factor_override --release`
- move mouse around in window

## What went wrong

Movement is super janky

## Additional information

This is happening because the window title is being updated every frame.

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

Fixes #7377

## Solution

Add an intermediate resource for the override state so that we can update the title only when it has been changed.

## Other potential options:

1. [Just revert the non-essential changes](https://github.com/rparrett/bevy/commit/07cc143de91591296544baf6fa7f659a1f74444b) made to this example in #5589.
2. Consolidate the toggle and change systems and display systems into one, and keep track of "changedness" there
3. Make the display system a normal function and call it from the toggle and change systems
4. Display the current setting in the `Text` instead, checking to see if the formatted text differs from the current value

### CODE REVIEW

**Comment by devil-ira** [comment]
Bevy shouldn't be messing with the cursor position just because some property of the window was changed.
Looks like `.bypass_change_detection()` is being abused to avoid this problem internally. I don't like that at all :\

**Comment by mockersf** [comment]
The complete fix would be to have different api to update the cursor position from Winit, and to expose to the user. Then add a flag to it, so we know when it comes from the user. This is closer to how it was done before the window as entity PR. I hoped change detection would be enough to avoid the issue, but as it keeps popping up we need to go back to the difference between internal/user demanded updates.

**Comment by devil-ira** [comment]
The fix is pretty simple. A clone of the `Window` struct to compare against to see what properties the user has changed, but this clone needs to be updated when we receive new info about the window from winit so we don't see them as user changes, which would cause a feedback loop.

**Comment by rparrett** [comment]
Even if this is "properly fixed," it's probably not good practice to update the window title every frame.

**Pull request closed without merging**
