### PR TITLE
Dim point and spot lights by the same factor as directional lights

### LINKED ISSUE #8369: Directional lights are 4800x dimmer than point lights and spot lights
## Bevy version

2ec38d146 (but also happens on 0.10.x and probably others).

## What you did

Delete the environment map lighting from the PBR example, then compare point light and directional light strengths.

The point light is `sqrt(50^2 + 50^2 + 50^2) ≈ 86 meters` from the origin and has a strength of 600K lumens. Which means `600,000 / (4 * PI * 86^2) ≈ 6.5 lux` reaching the origin.

### Point light
image

### Same strength directional light
```rust
commands.spawn(DirectionalLightBundle {
    transform: Transform::from_xyz(50.0, 50.0, 50.0).looking_at(Vec3::ZERO, Vec3::Y),
    directional_light: DirectionalLight {
        illuminance: 6.5,
        ..default()
    },
    ..default()
});
```
image

### 4800x scaled directional light
```rust
commands.spawn(DirectionalLightBundle {
    transform: Transform::from_xyz(50.0, 50.0, 50.0).looking_at(Vec3::ZERO, Vec3::Y),
    directional_light: DirectionalLight {
        illuminance: 6.5 * 4800.0,
        ..default()
    },
    ..default()
});
```
image

## Additional information

The bug is caused by this code which dims the strengths of directional lights by 4800x, but leaves point lights and spotlights unchanged:
https://github.com/bevyengine/bevy/blob/2ec38d1467c0f5f6de70fc28120dd6302806dfa0/crates/bevy_pbr/src/render/light.rs#L857-L867

### PR DESCRIPTION
**Pull request by benny-n**
# Objective

- Fixes #8369 
- The objective of this PR is to fix the issue where the directional lights are being dimmed by 4800x, while point and spot lights are not (as can be seen in the PBR example in the linked issue).

## Solution

- Apply the 4800x dimming factor to point and spot lights as well.

---

## Changelog

- Point and spot lights are now 4800x dimmer.

## Migration Guide

- Users who have used point and spot lights in their projects may need to increase the strength of these lights by a factor of 4800.

### Results

The PBR example _without_ environment map lighting, before the change:
image
After the change:
image
Directional light with the same strength for comparison (copied from the issue):
image

### CODE REVIEW

**Comment by mockersf** [comment]
You should fix the example so that it still displays the same.

In this case, that would mean setting the point light to an intensity of 600_000 * 4_800 = 2_880_000_000 lumens which feels very wrong...

**Comment by fintelia** [comment]
The problem is that Bevy lacks automatic exposure. Right now scenes with only directional lights have a manual exposure set to EV=12 while scenes with only point and spot light have an EV=0. That produces a "fake automatic exposure". But if you start mixing directional lights and point lights then you discover that their using different scales and no single EV value describes what you see.

This PR changes everything to use an EV=12 which is [appropriate for an overcast outdoor scene](https://en.wikipedia.org/wiki/Exposure_value#Tabulated_exposure_values), but is immediately going to cause issues for any indoor scene. It isn't particularly surprising that you need an outrageously strong light bulb to seem as bright as the sun, especially in this case where you've got only a single light and it is 86 meters away from the subjects being illuminated!

**Comment by benny-n** [comment]
So should I proceed with fixing the PBR example (by increasing the point light's strength) or are we seeking a different solution?

**Comment by mockersf** [comment]
All examples with a (point|spot)light will need to be fixed, not just the pbr one...

And the fix is probably not going to be "just multiply the light intensity", but checking what's the purpose of the light... For example, in the pbr example it may make more sense to replace it with a directional light.

Sorry, no definitive answer for you, I don't know about light enough so I'll trust @fintelia or other rendering people about that, but all the examples should display more or less the same, and without ridiculously high values.

**Comment by alice-i-cecile** [comment]
Closing in favor of a more complete fix in #8407.

**Pull request closed without merging**
