### PR TITLE
[Merged by Bors] - Cleanup some things which shouldn't be components

### PR DESCRIPTION
**Pull request by DJMcNab**
# Objective

- Using `Stopwatch` and `Timer` as raw components is a footgun.

## Solution

- Stop them from being components

### CODE REVIEW

**Comment by DJMcNab** [comment]
`Timer` shouldn't be a component because using it as a component has a high likelihood of colliding with another crate using it. That is, imagine module 1 uses a `Timer` component to mean 'when this entity should explode', but then module 2 uses a `Timer` component to mean 'when this entity's attack cooldown has finished'.

Using both module 1 and module 2 together would lead to your players exploding when they finish every attach, which would not be ideal.

**Comment by wilk10** [comment]
> `Timer` shouldn't be a component because using it as a component has a high likelihood of colliding with another crate using it. That is, imagine module 1 uses a `Timer` component to mean 'when this entity should explode', but then module 2 uses a `Timer` component to mean 'when this entity's attack cooldown has finished'.
> 
> 
> 
> Using both module 1 and module 2 together would lead to your players exploding when they finish every attach, which would not be ideal.

Ok, thanks for the explanation

**Comment by cart** [comment]
I'm fine with making Timer a "non component" for the time being, as it is generally better to wrap it (for ease of querying). We might ultimately want to add some form of "generic timer component" that auto ticks / can be added to scenes in the Bevy Editor, as I've found that useful in Godot in the past. Thats why I initially made `Timer` an auto-ticking component. But yeah, we should build things as the need arises, not before.

**Pull request closed without merging**
