### PR TITLE
Merge New Renderer

### PR DESCRIPTION
**Pull request by cart**
This merges the `pipelined-rendering` branch into `main`, which adds the new Bevy renderer as an opt-in alternative to the current renderer. This can be tested by adding `PipelinedDefaultPlugins` instead of `DefaultPlugins` (and using the types from the crates in the `pipelined` folder).

The many changes here are not intended to be reviewed in this PR. They have already been through the normal review process, just on the `pipelined-rendering` branch. Generally if you do find an issue, open a bug and we can resolve it in a follow up PR prior to making the new renderer the default. If you find a change that you believe shouldn't be merged now (especially if it affects the user experience in DefaultPlugins), feel free to call it out and we can adjust if we need to. 

Also note that there is still plenty of work to merge before release and the new render isn't _quite_ ready for all scenarios yet. The point of this PR is to move all development on to `main` and start preparing for the Bevy 0.6 release.

For more context on the new renderer, the discussions / prs that brought us here, and the remaining work to be done check out this tracking issue: #2535.

This is irregular, but this PR will not be merged with bors (or squash merged). I want to preserve the history to properly credit the people involved and to more accurately capture the history of the renderer's development.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
So the plan for now is to let them both operate in parallel, then fully remove the old renderer in time for the release?

What are we missing for feature parity? Just UI?

**Comment by cart** [comment]
> So the plan for now is to let them both operate in parallel, then fully remove the old renderer in time for the release?

Yup! I'd like to remove the current renderer ASAP though. As soon as we have feature parity.

> What are we missing for feature parity? Just UI?

Yup UI is the last piece!

**Comment by kirawi** [comment]
:O I can't wait to try this soon!

**Comment by parasyte** [comment]
@cart If I'm not mistaken, I think this PR is missing #3165 (which I accidentally pulled into one of my rebases). So that PR is currently not merged into the `main` branch.

**Comment by cart** [comment]
Oof very nice catch. @DJMcNab I can create a new pr on your behalf (with your commit intact) or you can create a new one targeting `main`. Your call!

**Comment by cart** [comment]
Looks like thats the only missing commit (because I merged that after creating the branch in this pr).

**Comment by DJMcNab** [comment]
I'm not bothered either way

I won't be able to make a new PR until much later today, if I can do so today.

**Pull request merged**
