### PR TITLE
Use -D warnings in all relevant CI

### LINKED ISSUE #17009: Build warnings with certain feature combinations
In CI, we don't use warnings as errors in all relevant places, so warnings are found, but don't block merging. These warnings should be fixed and the CI should fail on warnings.

https://github.com/bevyengine/bevy/actions/runs/12519981025/job/34925080257#step:5:25

https://doc.rust-lang.org/stable/clippy/continuous_integration/index.html

### PR DESCRIPTION
**Pull request by BenjaminBrienen**
# Objective

Fixes #17009

See: https://doc.rust-lang.org/stable/clippy/continuous_integration/index.html

## Solution

Add the env

## Testing

CI should start to fail, then I'll fix it.

## Showcase

image

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I broadly agree with this: deny warnings is the standard practice for Rust + Bevy, and blocking CI is the best way to ensure that these are fixed and stay fixed.

**Comment by BenjaminBrienen** [comment]
An alternative direction that we could take is to deny warnings in CI *except* for unused imports, variables, and muts. This might help keep verbosity down while still catching important lints. If we do that though, I would expect all the cfg stuff to be removed in all existing places we already do do that.

**Review by BD103 — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
> I don't like this though because I don't want irrelevant warnings when developing locally and there isn't enough granularity with allowing warnings in unchanged code.

Agreed. Half of the reason why these lints exist are to provide a better local development experience.

**Comment by mockersf** [comment]
OK to add `-D warnings` to CI, but I would prefer the warnings in task pool creating to be solved in a way that keep their builder for wasm and not wasm common

**Comment by BenjaminBrienen** [comment]
I can do that

**Review by alice-i-cecile — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Pull request merged**
