### PR TITLE
New Resources API

### PR DESCRIPTION
**Pull request by JonahPlusPlus**
# Objective

With 0.10, I really enjoyed merging `add_system` calls into `add_systems`. So I wanted to see if that can be done for calls like `insert_resource` and `init_resource`.

## Solution

This PR deprecates `<App/Commands/World>::insert_resource` and `<App/Commands/World>::init_resource` in favor of `<App/Commands/World>::insert_resources` and `<App/Commands/World>::init_resources`.

It introduces new traits: `InitResources` and `InsertResources` (separate because of different constraints). `InitResources` has an associated type for whether `ComponentId` or `[ComponentId; _]` should be returned from `World::init_resources`.

## Examples
```rust
// Before
App::new()
  .insert_resource(A::new())
  .insert_resource(B::new())
  .init_resource::<C>()
  .init_resource::<D>()
  .init_resource::<E>()
  .run();

// After
App::new()
  .insert_resources((A::new(), B::new()))
  .init_resources::<(C, D, E)>()
  .run();
```

---

### Added
- Added `<App/Commands/World>::init_resources`
- Added `InitResources`
- Added `InitResourceCommand`
- Added `<App/Commands/World>::insert_resources`
- Added `InsertResources`
- Added `InsertResourcesCommand`

### Changed
- Changed `Command` implementers to have `-Command` suffix
- Changed invocations of `<App/Commands/World>::init_resource` to `<App/Commands/World>::init_resources`
- Changed invocations of `<App/Commands/World>::insert_resource` to `<App/Commands/World>::insert_resources`

### Removed
- Removed `<App/Commands/World>::init_resource`
- Removed `<App/Commands/World>::insert_resources`

## Migration Guide

- Calls to `<App/Commands/World>::init_resource` should be changed to `<App/Commands/World>::init_resources`.
- Calls to `<App/Commands/World>::insert_resource` should be changed to `<App/Commands/World>::insert_resource`

### CODE REVIEW

**Comment by JonahPlusPlus** [comment]
Currently, this uses `Vec<ComponentId>` to return a list of the component IDs produced in `World::init_resources`. I tried using `[ComponentId; Self::SIZE]`, but this type of const generics isn't stabilized, so the vector will have to do for now. (Another option, `&'static [ComponentId]` is unsound because `World::init_resource` isn't deterministic (multiple instances of `World` may return different IDs)).

**Comment by JonahPlusPlus** [comment]
Decided against adding `init_non_send_resources` since the trait bounds (`'static + FromWorld`) can't be properly constrained due to orphan rules (if `Default` was added upstream to a tuple like `(A, B, C)`, it would conflict with `A`'s implementation). If this is desired, in order to be consistent with the rest of the API, it would require creating a new trait.

**Comment by JonahPlusPlus** [comment]
Okay, I feel this is ready now.

I eliminated the use of `Vec<ComponentId>` by using an associated type (I really got to stop shooting myself in the foot by over constraining my traits). This allows for `World::init_resource` and `World::insert_resource` to be deprecated safely, as `InitResources` and `InsertResources` now carry all the functionality needed.

The traits `InitResources` and `InsertResources` needed corresponding commands, so I created `InitResourcesCommand` and `InsertResourceCommand`, then renamed all the other commands to have a `-Command` suffix for consistency. Maybe a bit overkill, but I figured it just makes the names more explicit.

**Comment by iiYese** [comment]
I think the issue people might have with this initially is that the semantics aren't completely parallel with bundles/systems. In those APIs the elements are related/coupled in some way. For resources it is less often the case (even on a plugin basis) that multiple resources are related in some way.

However there's nothing stopping people from just using multiple calls for unrelated resources. I'm in favor of this anyway. I think it's fine to not be opinionated on this matter and let it come down to a choice of style for each author.

**Comment by JonahPlusPlus** [comment]
@james7132 Yes, the main goal of this PR is usability when inserting or initializing many resources.

However, with `World::init_resources`, there is also the option of getting a `[ComponentId; _]`, which might be useful in cases where you want to initialize many resources and then iterate on them with some common function or destructure it (`let [a, b, c] = world.init_resources::<(A, B, C)>();`).

As for order of operations, it works in the order of the tuple. So, for your example, the final value would be `A::new(2)`. That one call would have looked like:
```rust
app.insert_resource(A::new(0));
app.insert_resource(A::new(1));
app.insert_resource(A::new(2));
```
If this needs to be documented, I will gladly do so.

As for any increase in mental burden, as @iiYese pointed out, nothing is stopping users from writing it out like before.
In fact, when migrating pieces of code to this new interface in Bevy, there were times where it was better to make separate calls, for the sake of organization.
On that note, this isn't forcing users to add resources all together, rather it gives them more options for organization.

On compile times: I don't think there is an issue. Sure, it isn't lowering times, but it isn't calling macros on every invocation and with incremental compilation the compile time cost will really only be seen on fresh builds.

**Comment by iiYese** [comment]
> it works in the order of the tuple
Would be nice if we could just disallow this at a type level. If not I think adding a warning for tuples that contain more than one of the same resource should be considered.

**Comment by JonahPlusPlus** [comment]
@iiYese AFAIK there's no way to currently do that. It would require specialization or negative bounds/impls.

With negative bounds, you would create and implement a trait for checking equality and then use it as a negative bound. Ex:
```rust
trait EqTrait {}

impl<T> EqTrait for (T, T) {}

impl<A, B> MyTrait for (A, B) where (A, B): !EqTrait {}
```

This technique could also be used with specialization, but would only result in a panic, not a compile error.

However, one problem is expanding this to larger tuples, as checks between each type would grow exponentially (Ex: `(A, B, C) => (A && B) || (A && C) || (B && C)`).
It's not a big deal with compile time checks, but if I were to add runtime checks, they would get pretty expensive. They could be disabled in release builds though.

One solution was to move the checks to compile time, but that can only be done on nightly:
```rust
#![feature(const_trait_impl)]
#![feature(const_type_id)]
use std::any::TypeId;

trait MyTrait {
    const EQ: bool;

    fn foo(self);
}

impl<A: 'static, B: 'static> MyTrait for (A, B) {
    const EQ: bool = TypeId::of::<A>() == TypeId::of::<B>();

    fn foo(self) {
        if Self::EQ {
            println!("Error");
        } else {
            println!("Works");
        }
    }
}

fn main() {
    (2, 3).foo();
}
```

Though, I'm not sure how I feel about runtime warnings. If the call is from a system, it would be repeated ad nauseam.

**Comment by JonahPlusPlus** [comment]
@cart I went ahead and did some benchmarks with this PR branch and a branch based off the base commit (20101647c114e59e8c95dd0514f316a67c307e2d). I ran `cargo build` inside of "bevy_ecs" (it's where the macros are, and by focusing on a smaller piece of code there is less variance) and ran `cargo clean` before each test.

Device specs: Ryzen 5 2600 CPU, 16GB DDR4 RAM

The first 5 trials were with other programs running (Firefox, Spotify, etc.). For the last 5, I closed those programs (keeping some up for noting the times). I switched branches between each test. Afterwards, I calculated the confidence interval using a t-score.

| | Time (in sec) |
|--------|--------|
| Base # 01 | 30.80 |
| PR # 01 | 31.02 |
| Base # 02 | 29.50 |
| PR # 02 | 29.26 |
| Base # 03 | 29.67 |
| PR # 03 | 29.15 |
| Base # 04 | 28.78 |
| PR # 04 | 29.18 |
| Base # 05 | 30.13 |
| PR # 05 | 30.75 |
| Base # 06 | 29.82 |
| PR # 06 | 29.62 |
| Base # 07 | 29.58 |
| PR # 07 | 29.47 |
| Base # 08 | 30.66 |
| PR # 08 | 31.13 |
| Base # 09 | 28.69 |
| PR # 09 | 30.27 |
| Base # 10 | 29.43 |
| PR # 10 | 30.81 |
| Base Avg | 29.706 |
| PR Avg | 30.0666 |
| Base Std Dev | 0.69324 |
| PR Std Dev | 0.811928|
| Base Std Err | 0.219222 |
| PR Std Err | 0.256754 |
| Base 95% Confidence Interval | 29.706 +/- 0.49588 |
| PR 95% Confidence Interval | 30.0666 +/- 0.580778 |

From all this, we can say that in the worst reality, the difference between the true means (with 95% confidence) would be 1.44sec (In the best reality, it would be -0.72sec). But on average, we should see a 0.36sec difference. That's a 1.21% increase from before. Frankly, that's pretty significant for a relatively small change, even if it's not very noticeable. Mind you, these are on clean builds, so most of the time, users won't deal with these costs.

Despite these costs, I still think it's worth it. We already have similar interfaces, so this one should be no big deal. I think consistency and usability are more important than 0.36sec on clean builds.

**Comment by cart** [comment]
@bevyengine/ecs-team

**Comment by JoJoJet** [comment]
Nice writeup on the benchmarks, that does alleviate my concerns about codegen. My only objection at this point is that this will add slightly more friction when switching between `insert_resource` and `init_resource` -- not a very strong objection though.

Overall I'd say that I'm not really opposed to this PR, but I don't think it wins us too much either.

**Comment by hymm** [comment]
On the plus side things get a little more consistent with the add_systems api. On the minus side, code is a little harder to understand as things are put behind a macro. Overall I'm pretty neutral on the change.

Taking a bit from my jam game
```rust
        // before
        app.insert_resource(RapierConfiguration {
            timestep_mode: TimestepMode::Fixed {
                dt: 1. / 60.,
                substeps: 1,
            },
            ..Default::default()
        })
        .add_plugin(RapierPhysicsPlugin::<NoUserData>::pixels_per_meter(100.))
        .insert_resource(FixedTime::new_from_secs(1.0 / 60.0))
        .insert_resource(PhysicsSettings {
            initial_jump_speed: 400.0,
            gravity_pressed: 40.0,
            gravity_unpressed: 200.0,
            horizontal_speed: 200.0,
            max_speed: 700.0,
        });

        // after
        app.insert_resources(RapierConfiguration {
            timestep_mode: TimestepMode::Fixed {
                dt: 1. / 60.,
                substeps: 1,
            },
            ..Default::default()
        })
        .add_plugin(RapierPhysicsPlugin::<NoUserData>::pixels_per_meter(100.))
        .insert_resources((
            FixedTime::new_from_secs(1.0 / 60.0),
            PhysicsSettings {
                initial_jump_speed: 400.0,
                gravity_pressed: 40.0,
                gravity_unpressed: 200.0,
                horizontal_speed: 200.0,
                max_speed: 700.0,
            }
        ));
```
Looks slightly cleaner.

**Comment by cart** [comment]
Alrighty I think we should move forward with this. Marginal legibility/ergo increase in some cases and consistency with the direction other apis are going in. This would be a hard thing to justify in a "stable bevy" world, so its now or never.

**Comment by alice-i-cecile** [comment]
@JonahPlusPlus can you please rebase or otherwise fix the merge conflicts then?

**Comment by JonahPlusPlus** [comment]
@alice-i-cecile Sure, I'll get on it.

**Comment by JonahPlusPlus** [comment]
That should do it, but let me know if there are more merge conflicts. By the time I finished fixing these merge conflicts, there was already another one.

**Review by alice-i-cecile — APPROVED** [review]
I'm neutral on the syntax change but this appears correct now.

**Comment by alice-i-cecile** [comment]
@cart can you do a quick skim and merge this? I'd like to avoid leaving this longer because of the merge conflicts it generates.

**Comment by mockersf** [comment]
Not a fan of grouping resources together... in my opinion it's not the same as systems where you often want to be able to schedule several systems at the same time, resources each have their own meaning

**Comment by alice-i-cecile** [comment]
Looking at the compile time increases, the messiness of init_resources and the added complexity in our code, I've shifted from "neutral" to opposed.

**Comment by james7132** [comment]
> @james7132 As for what happens if the user specifies the same resource type multiple times, we should look at how we handle bundles/components, where the same issue occurs. What happens when you put the same component/bundle type multiple times in a tuple in a single spawn call? If our insert_resources behavior is consistent with that, I don't see a problem.

This would indeed address the ambiguity issues with duplicated resources being inserted. For bundle insertion/removal, deduplication currently has the global allocator and panics included (increasing codegen even more), but is only done at bundle registration time. We could duplicate this infrastructure and track every possible `InitResources`/`InsertResources` implementation the same way we track `Bundle` implementors to avoid the deduplication cost, or we can eat the allocation/performance cost on every insert/initialization. Whether or not we should do that is dependent on whether we think the usability wins outweighs the associated costs here.

**Comment by B-Reif** [comment]
We don't currently add any behavior to, or implement any traits on, tuples-of-resources. For that reason, I don't think this syntax is appropriate for resources (or plugins for that matter). I'm in favor of leaving this API as it is.

> Bevy has been steadily moving in the direction of "add multiple things with a single call, with tuple syntax" for a while now.

This syntax enables us to share some properties across the members of the given tuple, and to reason about the members within as a _single_ thing. For systems, this enables useful patterns around scheduling and run conditions. Resources (and plugins) don't have these added 'decorators' and don't benefit from coupling the way that systems do. 

Even after the schedule-first API, users won't configure the entire app with a single call. Systems will still be added with multiple calls on the app builder. The 'multiple things' in a single call are grouped together for specific, observable reasons.

> I feel like API consistency is good to strive for.

The existing API _is_ consistent: add behavior to the app by invoking methods of the app builder. These methods have different signatures because they each add different constructs. 

In the case of plugins, grouping might even mislead users into believing that the member plugins are ordered or coupled somehow. The API would be _less_ consistent because the plugin tuple wouldn't add or specify any behavior the way that system tuples do. In the case of resources, a new user might wonder what the tuple grouping does.

The only reason I would be in favor: this change could leave us the space to do implement traits on resource tuples in the future. I don't know what the purpose of that would be. Even after a post-Bevy-1.0 world, though, it wouldn't be the end of the world to extend the API with pluralized methods.

**Comment by JonahPlusPlus** [comment]
How about I create a prototype crate that adds this functionality for now? That way users can opt into this right now and see whether or not it should be an official part of Bevy.

**Comment by JonahPlusPlus** [comment]
Here, published a [crate](https://crates.io/crates/bevy_proto_resource_tuples). There are some limitations (can't implement the trait for the base case due to orphan rules), but it otherwise works. Give it a try and see how it works.

**Pull request closed without merging**
