### PR TITLE
[Merged by Bors] - Use default serde impls for Entity

### LINKED ISSUE #6143: Fully serialize entities
## What problem does this solve or what need does it fill?

Currently for entities we serialize only `id`:
https://github.com/bevyengine/bevy/blob/b995b4662a9481e8d6fd984b2d2fd02e1c2d1a5d/crates/bevy_ecs/src/entity/serde.rs#L9
But this is not very expected behavior. For example, if you serialize an entity, send it over the network, and map it to an entity on another machine, this will not work correctly, because [generation](https://docs.rs/bevy/latest/bevy/ecs/entity/struct.Entity.html#method.generation) is skipped for serialization.

## What solution would you like?

Fully serialize entities. It may only be redundant for scenes, but Bevy use [DynamicEntity](https://docs.rs/bevy/latest/bevy/scene/struct.DynamicEntity.html) for them anyway.

### PR DESCRIPTION
**Pull request by Shatur**
# Objective

Currently for entities we serialize only `id`. But this is not very expected behavior. For example, in networking, when the server sends its state, it contains entities and components. On the client, I create new objects and map them (using `EntityMap`) to those received from the server (to know which one matches which). And if `generation` field is missing, this mapping can be broken. Example:

1. Server sends an entity `Entity{ id: 2, generation: 1}` with components.
2. Client puts the received entity in a map and create a new entity that maps to this received entity. The new entity have different `id` and `generation`. Let's call it `Entity{ id: 12, generation: 4}`.
3. Client sends a command for `Entity{ id: 12, generation: 4}`. To do so, it maps local entity to the one from server. But `generation` field is 0 because it was omitted for serialization on the server. So it maps to `Entity{ id: 2, generation: 0}`.
4. Server receives `Entity{ id: 2, generation: 0}` which is invalid.

In my game I worked around it by [writing custom serialization](https://github.com/dollisgame/dollis/blob/master/src/core/network/entity_serde.rs) and using `serde(with = "...")`. But it feels like a bad default to me.

Using `Entity` over a custom `NetworkId` also have the following advantages:

1. Re-use `MapEntities` trait to map `Entity`s in replicated components.
2. Instead of server `Entity <-> NetworkId ` and `Entity <-> NetworkId`, we map entities only on client.
3. No need to handling uniqueness. It's a rare case, but makes things simpler. For example, I don't need to query for a resource to create an unique ID.

Closes #6143.

## Solution

Use default serde impls. If anyone want to avoid wasting memory on `generation`, they can create a new type that holds `u32`. This is what Bevy do for [DynamicEntity](https://docs.rs/bevy/latest/bevy/scene/struct.DynamicEntity.html) to serialize scenes. And I don't see any use case to serialize an entity id expect this one.

---

### Changed

- Entity now serializes / deserializes `generation` field.

## Migration Guide

- Entity now fully serialized. If you want to serialze only `id`, as it was before, you can create a new type that wraps `u32`.

### CODE REVIEW

**Review by inodentry — APPROVED** [review]
I like this. Simpler, more predictable behavior.

**Review by afonsolage — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
For the record: both @mockersf and I are opposed to this, as discussed in the linked issue. This violates one of our most important privacy guarantees, and is not adequately motivated IMO.

**Comment by maniwani** [comment]
This change makes sense to me. I don't really understand what *not* serializing generation does. You already can't do anything with an `Entity` that doesn't exist, nor can you spawn an entity with a specific ID and generation.

I see no harm in allowing an `Entity` value from one `World` to be used in a mapping in another.

Presumably, if we were loading a scene, we'd be spawning entirely new entities and just using the serialized values to correctly map the saved `Entity` values to the new ones.

In that case, not including the generation can actually create invalid aliasing. If you had serialized a component that was holding onto a stale `Entity` value, now we can't distinguish it from another value with the same ID but "living" generation.

**Comment by alice-i-cecile** [comment]
I've been convinced, and I agree with @maniwani's position. There's no value in serializing Entity in the current strategy, and simply not serializing `Entity` will result in a pretty rough UX with no real increase in safety.

`EntityMap` badly needs better docs and examples, but that's not this PR's problem.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
Entity's generation only make sense in a given world. Outside of their originating world, the only thing that makes sense is the "relations" between different entities when a component refer to another entity. The ID is enough to capture that information.

For me, relying on the generation to keep entities in sync means that entities are not actually synced, as spawn/despawn are not synced otherwise there would be no risk of targeting a wrong entity just by its ID. It also means that the synchronised world will only despawn entities when it notice a synced component is targeting an entity with a same ID/different generation, so that means your synchronised world is actually never in sync as entities are not despawned by themselves

**Comment by Shatur** [comment]
> For me, relying on the generation to keep entities in sync means that entities are not actually synced, as spawn/despawn are not synced otherwise there would be no risk of targeting a wrong entity just by its ID.

We probably misunderstood each other. This PR is not about spawning an entity with the same ID. This is necessary to map the server entity to the local client entity. And without `generation` this mapping won't be correct. I updated the description and provided an example of why. I mean if server receives a command "Move `Entity { id: 10, generation: 0}` it won't be able to easily map it to `Entity { id: 10, generation: 2}`

**Review by maniwani — APPROVED** [review]

**Review by devil-ira — APPROVED** [review]

**Comment by maniwani** [comment]
Thinking about it more, maybe we should return an error if we find an invalid `Entity` reference when saving a scene.

Then it would be OK to only serialize an index (purpose being smaller size, not "safety"). 

But dropping the generation while components can store invalid `Entity` values and we don't check is bad imo. If an invalid `Entity` value is serialized, it seems like either the value will alias or the scene load will error/panic. Both of those are undesirable.

Once `Option<Entity>` has the niche optimization, we could make that a convention. Then if the scene serializer sees a component holding an unmapped/stale `Entity` value, it can replace it with `None` instead of erroring like it would in the unwrapped case.

**Review by cart — APPROVED** [review]
Ok I'm on board for this. The initial impl was intended to be used for scene formats, but I agree that it is a separate concern.

`Entity` _is_ a generation + id, which represents a runtime-only id for a specific world. Serializing that _should_ include the generation.

However this should never be used to represent anything other than the current runtime state of a specific World. We should actively discourage using this impl for scenarios like scenes or keeping multiple worlds in sync on the same `Entity` value. (But @Shatur's `ServerEntity -> ClientEntity` mapping scenario does seem valid).

**Pull request closed without merging**
