### PR TITLE
[Merged by Bors] - Made Time::time_since_startup return from last tick.

### LINKED ISSUE #3259: Time::time_since_startup is inconsistent
## Bevy version

master@2021-12-05, or 4423a2fa2dc82fad71525ed3f44e16b8481a4902

## The issue

Time.seconds_since_startup() ([source](https://github.com/bevyengine/bevy/blob/4423a2fa2dc82fad71525ed3f44e16b8481a4902/crates/bevy_core/src/time/time.rs#L65-L68)) and Time.time_since_startup() ([source](https://github.com/bevyengine/bevy/blob/4423a2fa2dc82fad71525ed3f44e16b8481a4902/crates/bevy_core/src/time/time.rs#L82-L84)) are inconsistent, which is unexpected.

The former returns the time from startup to the last update(), the latter returns the time from startup to Instant::now().

## What you expected to happen

I think Time.time_since_startup() should return the time from startup to the last update(), because that is consistent with the rest of the struct and a similarly named method.

If users truly want to compare to Insant::now they can do so with `Instant::now - time.startup()`.

This would be a breaking change; if that is undesirable then at least the discrepancy can be documented to try and avoid surprising users.

### PR DESCRIPTION
**Pull request by fluffysquirrels**
Also added unit tests for it.

# Objective

- Fixes #3259 

## Solution

- As discussed in #3259

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Looks great, thanks for the first contribution!

**Review by mockersf — CHANGES_REQUESTED** [review]
The value for `seconds_since_startup` is computed at update time:
https://github.com/bevyengine/bevy/blob/4423a2fa2dc82fad71525ed3f44e16b8481a4902/crates/bevy_core/src/time/time.rs#L34-L44
In that function, `duration_since_startup` is also computed. Could we save it in that struct instead of recalculating it when calling `time_since_startup`?

**Comment by fluffysquirrels** [comment]
@mockersf good idea! I'll work on that now.

**Comment by fluffysquirrels** [comment]
I made that change @mockersf

**Comment by fluffysquirrels** [comment]
I don't think that CI error in bevy_render is anything to do with my code.

**Comment by mockersf** [comment]
CI error should be fixed (#3269) if you rebase on main

**Comment by fluffysquirrels** [comment]
I rebased and pushed.

**Review by mockersf — APPROVED** [review]

**Comment by cart** [comment]
Good call! Way more useful this way. I agree that pre-computing seconds-since-startup is a good call. There are enough ops in the Duration -> "float seconds" conversion that the extra internal complexity seems worth it when this function might get called hundreds or thousands of times per frame.

**Pull request closed without merging**
