### PR TITLE
Improve render asset

### PR DESCRIPTION
**Pull request by vallrand**
# Objective

- Remove duplicated implementation of asset extraction/preparation in material/material2d
- Allow to have multiple GPU representations for the same "main world" asset.

## Solution

Remove one to one correlation between "main world" asset and GPU asset, by swapping base type that implements `RenderAsset` to be the GPU asset type. That would make `RenderAssetPlugin` more flexible, being able to prepare different data based on same source asset *(example: effect plugin could preprocess mesh buffer data for specialized rendering, without affecting main render flow)*.
That also makes `RenderAssets<GPUType>` more explicit.

#### Changed
- `RenderAsset` trait definition
- `Material` and `Material2d` now use `RenderAssetPlugin`
- `RenderMaterials` and `RenderMaterials2d` were replaced with more generic `RenderAssets`

## Migration Guide

- `RenderMaterials<M>` can now be accesed as `RenderAssets<PreparedMaterial<M>>`
- `RenderMaterials2d<M>` can now be accesed as `RenderAssets<PreparedMaterial2d<M>>`
- `RenderAssets<Image>` is now `RenderAssets<GpuImage>`
- `RenderAssets<Mesh>` is now `RenderAssets<GpuMesh>`
- `RenderAsset` trait should now be implemented on prev `RenderAsset::PreparedAsset` type, while source asset type is defined as `RenderAsset::SourceAsset`

#### Before
```rust
impl RenderAsset for Image {
    type ExtractedAsset = Image;
    type PreparedAsset = GpuImage;

    fn extract_asset(&self) -> Self::ExtractedAsset {
        self.clone()
    }
}
```
#### After
```rust
impl RenderAsset for GpuImage {
    type SourceAsset = Image;
    type ExtractedAsset = Image;

    fn extract_asset(source_asset: &Self::SourceAsset) -> Self::ExtractedAsset {
        source_asset.clone()
    }
}
```

### CODE REVIEW

**Comment by vallrand** [comment]
@JMS55 

That `multiple representations` was perhpaps a bit misleading.
From the perspective of decoupling generic "main world" types
from specific rendering implementation, as example if one would want to swap to renderer implementation where mesh assets are all kept in one large buffer, but keep using `Handle<Mesh>`.

One could always just duplicate the original asset, if it needs to be uploaded to the gpu twice.

Wrote some feedback if you'll find it useful [8132](https://github.com/bevyengine/bevy/pull/8132#issuecomment-1479081654)

**Comment by JMS55** [comment]
After some further experimentation with meshlets and ray tracing, I'm in favor of something like this PR.

**Comment by superdump** [comment]
@vallrand - could you update this PR? I have long disliked the split between RenderAssets and RenderMaterials and wanted materials to be just another asset.

**Comment by superdump** [comment]
I've adopted this in #12827 as it was a great idea, ahead of its time. :)

**Pull request closed without merging**
