### PR TITLE
[Merged by Bors] - Correctly use as_hsla_f32 in Add<Color> and AddAssign<Color>, fixes #5543

### LINKED ISSUE #5543: Color's Add and AddAssign impls add RGBA values to HSLA
https://github.com/bevyengine/bevy/blob/f3b5bf029c54a1abfb39014104a14dde24a4c2ce/crates/bevy_render/src/color/mod.rs#L662
https://github.com/bevyengine/bevy/blob/f3b5bf029c54a1abfb39014104a14dde24a4c2ce/crates/bevy_render/src/color/mod.rs#L711

These lines should probably be `let rhs = rhs.as_hsla_f32()` instead.

### PR DESCRIPTION
**Pull request by vertesians**
Probably a copy-paste error, but `Add<Color>` and `AddAssign<Color>` should use `rhs.as_hlsa_f32()` instead of `rhs.as_linear_rgba_f32()` when the LHS is a `Color::Hsla`. Fixes #5543.

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@mockersf, bors appears to be stuck.

**Comment by cart** [comment]
Looks like this is stalled out because of the following bors error message:

```json
  {:error, :create_commit,
   "{\"message\":\"Validation Failed\",\"errors\":[{\"resource\":\"author\",\"code\":\"missing_field\",\"field\":\"email\"}],\"documentation_url\":\"https://docs.github.com/rest/reference/git#create-a-commit\"}",
```

**Comment by cart** [comment]
Note that the commit doesn't link to the author's github account / you can't click on the author like you normally could.
@vertesians: make sure you've configured git to link to your github account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git.

**Comment by cart** [comment]
@vertesians try setting the author of this commit using the instructions here: https://www.git-tower.com/learn/git/faq/change-author-name-email.
Then force push to this branch.

**Comment by cart** [comment]
I was hoping now that the commit has my authorship attached to it that it would stop failing. Sadly that did not play out.

**Comment by vertesians** [comment]
Really really sorry for the trouble — I didn't even think that it could be an issue. :( 

Hopefully it'll work now.

**Pull request closed without merging**
