### PR TITLE
Add `Without<Parent>` filter to `sync_simple_transforms`' orphaned entities query

### LINKED ISSUE #9517: `sync_simple_transforms` only checks for removed parents and doesn't filter for `Without<Parent>`
## Bevy version

Bevy main 3aad5c6b994f

## What you did

```
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, remove_and_set_parent)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn(SpriteBundle {
        sprite: Sprite {
            color: Color::WHITE,
            custom_size: Some(Vec2::splat(100.)),
            ..Default::default()
        },
        transform: Transform::from_translation(50. * Vec3::ONE),
        ..Default::default()
    })
    .with_children(|commands| {
        commands.spawn(SpriteBundle { 
            sprite: Sprite {
                color: Color::RED,
                custom_size: Some(Vec2::splat(110.)),
                ..Default::default()
            },
            transform: Transform::from_translation(50. * Vec3::ONE),
            ..Default::default()
        });
    });
}

fn remove_and_set_parent(
    input: Res<Input<KeyCode>>,
    mut commands: Commands,
    query: Query<(Entity, &Parent), With<Sprite>>,
) { 
    if input.just_pressed(KeyCode::Space) {
        for (e, p) in query.iter() {
            commands.entity(e).remove_parent();
            commands.entity(e).set_parent(p.get());
        }
    }
}
```
run it and you get:

transform_bug_1

after pressing space:

transform_bug_2

## What went wrong

`sync_simple_transforms` only checks for removed parents and doesn't filter for `Without<Parent>`, so it overwrites the `GlobalTransform` of non-orphan entities that removed and then added a parent since the last update.

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

`sync_simple_transforms` only checks for removed parents and doesn't filter for `Without<Parent>`, so it overwrites the `GlobalTransform` of non-orphan entities that were orphaned and then reparented since the last update.

Introduced by #7264

## Solution

Filter for `Without<Parent>`.

Fixes #9517, #9492

## Changelog

`sync_simple_transforms`:
* Added a `Without<Parent>` filter to the orphaned entities query.

### CODE REVIEW

**Comment by JoJoJet** [comment]
Can you add some regression tests to make sure that this fixes the issues?

**Comment by alice-i-cecile** [comment]
Definitely a reasonable fix, but I'd also like to see a test or three.

**Comment by ickshonpe** [comment]
> Can you add some regression tests to make sure that this fixes the issues?

Will do.

I'd like to get @Nicopap to review as well. I think my understanding of the problem is correct, but want to make sure that there wasn't a good reason for not filtering by `Without<Parent>`.

**Review by nicopap — APPROVED** [review]
I didn't think of entities which `Parent` component was removed and later added back. I was thinking "if the `Parent` component is removed, then why check for `Without<Parent>`, glossing over situations where it is removed and later added back.

**Review by devil-ira — APPROVED** [review]

**Review by JoJoJet — APPROVED** [review]

**Pull request merged**
