### PR TITLE
Auto add default UI camera

### PR DESCRIPTION
**Pull request by Wcubed**
Adds a system to PostStartup that spawns a default UI camera if it finds UI nodes but no camera to render them.

Partial solution to #1432.

## Open question
When there are no UI elements present during startup, the system won't trigger. Elements added later on in the game won't therefore be visible.

One solution to this would be to move the new check from startup to some stage that runs every frame. Would this be overkill? And is there a possibility that a user might have UI nodes, but doesn't want them to be rendered at the moment?

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
This is a neat idea, thanks for the contribution! Code quality and tests are excellent.

I'm of two minds about this idea. In favor:

- this is a frustrating and mysterious error for new beginners
- UI cameras are rarely customized
- this significantly reduces boilerplate of quick examples, and makes adding debug text / elements to games much lower friction.
- users can just despawn this camera if they really care

Against:
- this is implicit, and somewhat surprising
- it obscures the fact that UI cameras exists and can be configured

If we don't do this, I think we should print a warning instead, using the same schedule position as you have here. Overall, I think I've convinced myself that this is worth it.

@Wcubed could you add a resource that controls whether or not this is done, defaulting to true? That will make it simpler to opt-out of this if users really care.

**Comment by alice-i-cecile** [comment]
One more note: I think this should be blocked on #1854 / #3635. Users almost always want to add a marker component to each of their cameras right now, and fetching just the UI camera without a marker is currently a nuisance.

**Comment by Wcubed** [comment]
Good points.

- The option to print a warning was considered earlier, with cart mentioning that his ideal solution would be to auto-add the UI camera: https://github.com/bevyengine/bevy/pull/1440#issuecomment-778661990.

- When I add a resource, I could instead make it so it always adds the default UI camera, unless the user specifies it shouldn't. This way it will work regardless of whether there are UI elements at startup. Which removes that gotcha, and makes the situation: "the UI camera is just there, unless you don't want it".
Or would that incur too much unnecessary overhead for those not using it, and not aware it spawns one by default?

- I agree that this should be blocked on the camera marker components. I now see I don't actually distinguish between a 2d Ortographic camera, and the UI camera. So it should either check the camera name, or the new marker components.

**Comment by mockersf** [comment]
I would rather have the UI renderer work without a camera by assuming one with the default value rather than spawn one that could conflict with the user

**Comment by Wcubed** [comment]
If I understand you correctly, you propose that if the ecs world does not contain a ui camera, the render system would assume in the background it has one with the default settings?

That would have less edge-cases or gotcha's, I think. Interestingly, it would make the UI camera a bit of a "config object". If it's not there, defaults are assumed, so it's existence would then serve to override those defaults. Not sure if that is the desired direction.

For the implementation I think this `if let` could be turned into a `match`, with the `None` case spawning a default camera into the comands. This _would_ create a new default camera every frame, so maybe the default camera could be kept somewhere, so it doesn't have to be re-created?
https://github.com/bevyengine/bevy/blob/e30199f7a9cf6429aed6c0b6f66fe76b791e90aa/crates/bevy_ui/src/render/camera.rs#L9

**Comment by Weibye** [comment]
> I would rather have the UI renderer work without a camera by assuming one with the default value rather than spawn one that could conflict with the user

I agree with @mockersf here that this problem might be better solved by improving the design of other systems.

**Comment by mockersf** [comment]
Since Bevy 0.8, there isn't a need for a UI camera anymore, and 2D/3D camera will display UI by default
https://bevyengine.org/news/bevy-0-8/#no-more-camerauibundle

**Pull request closed without merging**
