### PR TITLE
Explain Camera2dBundle.projection needs to be set carefully

### PR DESCRIPTION
**Pull request by stepancheg**
Encountered it while implementing https://github.com/bevyengine/bevy/pull/11109.

### CODE REVIEW

**Review by matiqo15 — COMMENTED** [review]
What if we add this comment to `OrthographicProjection`? I would likely look there if I encountered any issue with this.

**Comment by stepancheg** [comment]
@matiqo15 I added comment in `OrthographicProjection` initially, but then decided it is more appropriate on `Camera2dBundle`, because `OrthographicProjection` can be used not only with 2D camera.

**Comment by matiqo15** [comment]
Makes sense, but I still think we should at least mention it in `OrthographicProjection` so that we can point users in the right direction. Would like to get someone else's opinion on this.

**Review by rodolphito — APPROVED** [review]
Is there any chance we could instead change the culling behavior to cull stuff strictly behind the near plane and not also things on the near plane?

**Comment by stepancheg** [comment]
@rodolphito I suspect that might be
- fragile to minor changes the project
- may result in visual artefacts due to float rounding

But I don't really know.

**Review by TrialDragon — APPROVED** [review]

**Comment by TrialDragon** [comment]
I believe this needs to have main merged in; it's try to run CI checks that aren't available it seems.

**Pull request merged**
