### PR TITLE
Add into_ methods for EntityMut and EntityWorldMut that consume self.

### LINKED ISSUE #12417: Missing EntityWorldMut::into_mut(self)
## What problem does this solve or what need does it fill?

For my plugin I'd like to have closures that takes `Entity` and `&' mut World` and returns `Mut<'w, T>`:

```rust
fn translation<'w>(id: Entity, world: &'w mut World) -> Mut<'w, Vec3> {
    world
        .entity_mut(id)
        .get_mut::<Transform>()
        .unwrap()
        .map_unchanged(|t| &mut t.translation)
}
```

This code won't compile:
```
cannot return value referencing temporary value
returns a value referencing data owned by the current function
```

It happens because `EntityWorldMut<'w>::get_mut(&mut self)` returns `Mut` with lifetime of `&mut self` instead of `'w`. 

## What solution would you like?

It would be nice to have some method on `EntityWorldMut` like `get_mut` but that consumes self and returns `Mut<'w, T>`:

```rust
// bevy_ecs/world/entity_ref.rs
impl<'w> EntityWorldMut<'w> {
  pub fn into_mut<T: Component>(self) -> Option<Mut<'w, T>> {
    unsafe { self.into_unsafe_entity_cell().get_mut() }
  }
}
```

It is possible to implement the translation function for now:
```rust
fn translation<'w>(id: Entity, world: &'w mut World) -> Mut<'w, Vec3> {
  world
    .entity_mut(id)
    .into_mut::<Transform>()
    .unwrap()
    .map_unchanged(|t| &mut t.translation)
}
```

## What alternative(s) have you considered?

I didn't find a way to bypass proper lifetime within my `transform` function without making changes to engine.

### PR DESCRIPTION
**Pull request by jkb0o**
# Objective

Provide component access  to `&'w T`, `Ref<'w, T>`, `Mut<'w, T>`, `Ptr<'w>` and `MutUntyped<'w>` from `EntityMut<'w>`/`EntityWorldMut<'w>` with the world `'w` lifetime instead of `'_`.

Fixes #12417

## Solution

Add `into_` prefixed methods for `EntityMut<'w>`/`EntityWorldMut<'w>` that consume `self` and returns component access with the world `'w` lifetime unlike the `get_` prefixed methods that takes `&'a self` and returns component access with `'a` lifetime.

Methods implemented:
- EntityMut::into_borrow
- EntityMut::into_ref
- EntityMut::into_mut
- EntityMut::into_borrow_by_id
- EntityMut::into_mut_by_id
- EntityWorldMut::into_borrow
- EntityWorldMut::into_ref
- EntityWorldMut::into_mut
- EntityWorldMut::into_borrow_by_id
- EntityWorldMut::into_mut_by_id

### CODE REVIEW

**Comment by jkb0o** [comment]
@james7132 I'd like to follow issue [discussion](https://github.com/bevyengine/bevy/issues/12417#issuecomment-1987999508) and method naming here if possible. 

The `take_` prefix fits better for my taste, but there is already `EntityWorldMut::take` that drops all components, and I'm not sure it is good idea to change that API. The `into_` prefix  doesn't fit well with `get` and `get_by_id` methods.

**Comment by jkb0o** [comment]
If `into_` stuff fits better the purpose, I can change the naming:
- EntityMut::into_borrow
- EntityMut::into_ref
- EntityMut::into_mut
- EntityMut::into_ref_by_id
- EntityMut::into_mut_by_id
- EntityWorldMut::into_borrow
- EntityWorldMut::into_ref
- EntityWorldMut::into_mut
- EntityWorldMut::into_ref_by_id
- EntityWorldMut::into_mut_by_id

**Comment by pablo-lua** [comment]
Looks like you changed the methods name, can you change the title to reflect those changes?

**Review by james7132 — APPROVED** [review]
LGTM. Thanks for covering the untyped APIs too.

**Review by pablo-lua — APPROVED** [review]

**Pull request merged**
