### PR TITLE
[Merged by Bors] - Update `glam` to `0.23`

### PR DESCRIPTION
**Pull request by geieredgar**
# Objective

- Update `glam` to the latest version.

## Solution

- Update `glam` to version `0.23`.

Since the breaking change in `glam` only affects the `scalar-math` feature, this should cause no issues.

### CODE REVIEW

**Comment by OptimisticPeach** [comment]
Bumped & published hexasphere to 8.1.0 :)

**Comment by teoxoy** [comment]
encase v0.5 is up on crates.io (with updated glam dep)

**Review by james7132 — APPROVED** [review]
LGTM if CI passes.

**Review by mockersf — APPROVED** [review]

**Comment by CGMossa** [comment]
Great job on this!

**Pull request closed without merging**
