### PR TITLE
[Merged by Bors] - Update glam to 0.13.0.

### PR DESCRIPTION
**Pull request by bitshifter**
See https://github.com/bitshifter/glam-rs/blob/master/CHANGELOG.md for details on changes.

### CODE REVIEW

**Comment by Ratysz** [comment]
Don't forget to `cargo fmt`.

**Comment by Ratysz** [comment]
Looks like there were more deprecations in this update:
```
error: use of deprecated associated function `bevy_math::Mat4::identity`: use Mat4::IDENTITY instead
   --> crates/bevy_core/src/bytes.rs:234:25
    |
234 |         test_round_trip(Mat4::identity());
    |                         ^^^^^^^^^^^^^^
    |
    = note: `-D deprecated` implied by `-D warnings`
```

**Comment by mockersf** [comment]
what do you think about replacing `VecN::default()` with `VecN::ZERO` to benefit there also from the new consts?

**Comment by bitshifter** [comment]
@mockersf  I agree, I think `VecN::ZERO` would be a bit clearer intent wise than `VecN::default()`. Other than that, it might remove a function call in unoptimised builds but I think it's probably much of a muchness otherwise.

**Comment by Ratysz** [comment]
Please resolve [warnings](https://github.com/bevyengine/bevy/pull/1550/checks?check_run_id=2030260708#step:5:823) locally first?

**Comment by bitshifter** [comment]
@Ratysz I did build locally but I did not see these warnings. They appear to be from iOS examples, perhaps they aren't part of the standard build?

**Comment by Ratysz** [comment]
The one I linked runs `cargo clippy --workspace --all-targets --all-features -- -D warnings -A clippy::type_complexity -A clippy::manual-strip` on Linux, and the warning comes from an example.

**Comment by bitshifter** [comment]
Does that require nightly? failed to build for me at all on Rust stable 1.50 on Windows:

```
error: use of a blacklisted/placeholder name `foo`
   --> crates\bevy_tasks\src\task_pool.rs:283:13
    |
283 |         let foo = Box::new(42);
    |             ^^^
    |
    = note: `-D clippy::blacklisted-name` implied by `-D warnings`
```

etc.

**Comment by bitshifter** [comment]
The file that is failing now was added at some point after I made this PR, which is why I didn't see it. I need to rebase with main.

**Comment by Ratysz** [comment]
That's odd. I know this sounds silly, but it works on my machine 😄

**Comment by bitshifter** [comment]
It worked after rebasing.

**Review by alec-deason — APPROVED** [review]
I'm excited to see this one land.

**Comment by cart** [comment]
Thanks for keeping us up to date! Looks good to me.

**Comment by cart** [comment]
We will need to update hexasphere before merging to avoid duplicate deps: https://github.com/OptimisticPeach/hexasphere
@OptimisticPeach down to do an update?

**Comment by OptimisticPeach** [comment]
Of course! I'll have it ready in an hour or so.

**Comment by OptimisticPeach** [comment]
Half an hour, actually, `hexasphere` 3.2.0 is up.

Related: how would you feel if I were to rewrite/refactor `hexasphere` to be generic over the vector used in a separate crate (and then use that in bevy), so updating glam is seamless?

**Comment by cart** [comment]
That sounds good to me!

**Pull request closed without merging**
