### PR TITLE
[Merged by Bors] - Improve many sprites example

### PR DESCRIPTION
**Pull request by willolisp**
# Objective

My attempt at fixing #2075 .

This is my very first contribution to this repo. Also, I'm very new to both Rust and bevy, so any feedback is *deeply* appreciated.

## Solution
- Changed `move_camera_system` so it only targets the camera entity. My approach here differs from the one used in the [cheatbook](https://bevy-cheatbook.github.io/cookbook/cursor2world.html?highlight=maincamera#2d-games) (in which a marker component is used to track the camera), so please, let me know which of them is more idiomatic.
- `move_camera_system` does not require both `Position` and `Transform` anymore (I used `rotate` for rotating the `Transform` in place, but couldn't find an equivalent `translate` method).
- Changed `tick_system` so it only targets the timer entity.
- Sprites are now spawned via a single `spawn_batch` instead of multiple `spawn`s.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I think we should merge this over #2075; be sure to credit @neosam in the appropriate places too however.

**Comment by Sheepyhead** [comment]
I disagree with the addition of the _system prefix, but other than that it looks good

**Review by Sheepyhead — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]
While I'm not opposed to anything here, I would prefer not using unwrap() in example code, but it's still good without.

**Comment by alice-i-cecile** [comment]
bors retry

**Pull request closed without merging**
