### PR TITLE
Add bloom postprocessing based on #2876

### PR DESCRIPTION
**Pull request by jakobhellermann**
on top of #3425

The work for the `BloomNode` was done by @ChangeCaps in #2876, I just updated it to the newest `main` on #3425.

### CODE REVIEW

**Comment by superdump** [comment]
Just noting that @CptPotato and @cart had some feedback on the previous PR that may or may not still be relevant / need to be addressed.

**Comment by mtsr** [comment]
I think some examples need to have their lighting adapted. Particularly the `lighting` example. I'll give the other examples a quick review.

**Comment by jakobhellermann** [comment]
The 2d examples are broken because https://github.com/bevyengine/bevy/pull/3425 doesn't handle 2d yet.
The 3d examples definitely need some tweaking, probably both the example itself and the bloom threshold.

**Comment by mtsr** [comment]
#3425 does double tonemapping, fixing that improves the bloom results significantly.

**Comment by alice-i-cecile** [comment]
Continued in #6397.

**Pull request closed without merging**
