### PR TITLE
remove `DeterministicRenderingConfig`

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Since #12453, `DeterministicRenderingConfig` doesn't do anything

## Solution

- Remove it

---

## Migration Guide

- Removed `DeterministicRenderingConfig`. There shouldn't be any z fighting anymore in the rendering even without setting `stable_sort_z_fighting`

### CODE REVIEW

**Comment by james7132** [comment]
Doesn't this still affect the sorted render phases?

**Comment by re0312** [comment]
looks like it is still required for transparent material,  but example regarding the `deterministic `option should be updated. for long-term consideration, im not in favor of keeping it. the `determinismis` configured by `DeterministicRenderingConfig  `more of an issue with Bevy's parallelizer rather than a rendering related,Could we track the order when splitting tasks in `par_for_each `instead of sorting all `visible_entities `after iteration?

**Comment by mockersf** [comment]
If I introduce a little shift in the transforms of the deterministic example, it looks like 
Screenshot 2024-04-01 at 09 27 59


and... it's not deterministic anymore, how it looks will change every time it's run

> looks like it is still required for transparent material

Right, with a transparent material it works as expected

We already have a tool against z fighting it's [`depth_bias`](https://docs.rs/bevy/latest/bevy/pbr/trait.Material.html#method.depth_bias)

**Review by james7132 — APPROVED** [review]
Ah right momentarily forgot about that, thanks. LGTM.

**Pull request merged**
