### PR TITLE
document, test, and refactor AtomicBorrow

### PR DESCRIPTION
**Pull request by multun**

### CODE REVIEW

**Comment by cart** [comment]
this seems like a welcome change. @Ralith might also be interested in a hecs pr.

**Comment by multun** [comment]
Can you rebase this on master? Format checking was enabled, and the CI doesn't yet check for it at the commit you're at

**Comment by cart** [comment]
Closing this as Bevy is now lock free in most cases / the current impl works for the few remaining cases / the changes weren't made in upstream hecs.

**Comment by Ralith** [comment]
I went ahead and merged changes based on this to hecs. Thanks!

**Pull request closed without merging**
