### PR TITLE
`UiRect` axes constructor

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

We don't have a constructor function for `UiRect` that sets uniform horizontal and vertical values, even though it is a common pattern.

## Solution

Add a constructor function to `UiRect` called `axes`, that sets both `left` and `right` to the same given horizontal value,
and sets both `top` and `bottom` to same given vertical value.

## Changelog

* Added a constructor function `axes` to `UiRect`.

### CODE REVIEW

**Comment by ickshonpe** [comment]
Part of the problem is like its called `UiRect` but isn't even used to represent rectangles, but renaming it to `RetangularAnnulus` is never going to fly.

**Comment by SDesya74** [comment]
> `RectRing` perhaps?

I also recently thought that the the name does not describe what the `UiRect` is. Perhaps the word `Borders` is appropriate?

**Comment by ickshonpe** [comment]
I really hate the name `axis`, axis is singular not plural :disappointed:

Maybe `axes` is a good enough compromise? It at least isn't likely to get confused with anything else.

**Comment by SDesya74** [comment]
I like "axes", word has the same length, but I'm not so familiar with English to speak with confidence

**Comment by ickshonpe** [comment]
> > `RectRing` perhaps?
> 
> I also recently thought that the the name does not describe what the `UiRect` is. Perhaps the word `Borders` is appropriate?

I thought about the name `Frame` as well. `UiRect` is used for a lot of different things though. It would be really weird to have the type we are using to represent positions called `Borders` or `Frame` or `RectRing`. 

Another option is to have separate types `Margin`, `Border`, `Padding`, `Position`, etc and use macros or cut and paste to implement `UiRect`'s functions for each one.

**Comment by alice-i-cecile** [comment]
I like `axes` as well for the name of this constructor method.

As for the type question, I like `Frame` quite a bit, and would support a PR renaming `UiRect` to that. Splitting the types is also very appealing.

**Comment by ickshonpe** [comment]
Definitely `axes`.

**Comment by ickshonpe** [comment]
This is ready to be merged I think.

**Review by james7132 — APPROVED** [review]

**Pull request merged**
