### PR TITLE
Updated fox model

### LINKED ISSUE #8099: Fox.glb has incorrectly scaled normals
## Bevy version

35e107ca

## What went wrong

The `Fox.glb` model has incorrect scaling of the vertex normals.

e.g. for the first vertex, the normals are:

```
0.176476 -0.507666 -0.242626
```

correctly scaled would be:

```
0.299268 -0.860901 -0.411446
```

This has led to issues such as  #6528. That has been fixed, but it would be good to fix this at the source anyway.

### PR DESCRIPTION
**Pull request by JohnTheCoolingFan**
# Objective

Partially fixes #8099, only updating the model itself, the issue discusses other additional slutions for problems found because of this model.

## Solution

Use Blender3d to recalculate normals

### CODE REVIEW

**Comment by JohnTheCoolingFan** [comment]
Only a draft because foxes are still black on https://github.com/bevyengine/bevy/commit/1914a3f288a812667f735ee9e7806cf1560dacc0 even with new model

**Comment by JohnTheCoolingFan** [comment]
And also tested on 681c9c6dc859be52565609e56ce9dc7f6f1c1f12, still black

**Comment by JohnTheCoolingFan** [comment]
The upstream model is completely fine on my setup (RX 6700 XT)

**Comment by mockersf** [comment]
Our fox model should come straight from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Fox and not be modified

**Pull request closed without merging**
