### PR TITLE
[Merged by Bors] - Mark `Task` as `#[must_use]`

### PR DESCRIPTION
**Pull request by devil-ira**
The `async_executor::Task` that it wraps is also `#[must_use]` with the same message.

### CODE REVIEW

**Review by IceSentry — APPROVED** [review]
Since this would be a breaking change could you write a migration guide?

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Comment by IceSentry** [comment]
Well, our CI broke because of a new lint 😉, but yeah, technically the code would still compile so I guess it doesn't count.

**Comment by devil-ira** [comment]
Not sure what I'd write in the guide.
If I understand it correctly, any code that would trigger this lint wasn't working/doing anything, since the task would be dropped and canceled immediately.
I guess I could write "Hey, your code is broken.", but the muse_use message kinda already does that.

**Comment by alice-i-cecile** [comment]
> I guess I could write "Hey, your code is broken.", but the muse_use message kinda already does that.

Point taken. Don't worry about it.

**Comment by IceSentry** [comment]
Yeah, at first I thought it was a compile error which is why I asked for a migration guide, but since it's just a lint for something that was simply not working before it's less of an issue.

**Pull request closed without merging**
