### PR TITLE
Overflow clip margin

### LINKED ISSUE #15468: More flexible UI overflow API
## What problem does this solve or what need does it fill?

At the moment if you set `OverflowAxis::Clip`/`Hidden`/`Scroll` the node's clipping rect will be set to the node's bounds.
This isn't very natural since if you have a UI Node set to `Overflow::Clip` any overflowing content of its children's will spill over the node's border.

There is a PR in review #15442 that changes the clipping rect to the node's content-box (The innermost part of the node excluding the padding and border).

It's not difficult to implement support for other clipping options, so we should.

## What solution would you like?

I'm not sure we can match all the CSS options anytime soon, so I suggest a simplified API:

```rust
pub enum OverflowAxis {
    /// Show overflowing items.
    Visible,
    /// Hide overflowing items by clipping.
    Clip(OverflowClipMargin),
    /// Hide overflowing items by influencing layout and then clipping.
    Hidden(OverflowClipMargin),
    /// Scroll overflowing items.
    Scroll(OverflowClipMargin),
}

pub struct OverClipMargin {
    /// Visible area
    box: OverflowClipBox,
    /// Insets the chosen `box` on all edges, can be negative
    offset: Val,
}

pub enum OverflowClipBox {
    /// Clip overflow outside the margin
    MarginBox,
    /// Clip overflow outside the border
    BorderBox,
    /// Clip overflow outside the padding
    PaddingBox,
    /// Clip any overflow outside the content box
    ContentBox,
}
```

`MarginBox` might be tricky to support as `Taffy`'s `Layout` doesn't return margin values and could be left out initially.

Doesn't seem worth thinking about `clip-path` until we have some sort of compositing.

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Limited implementation of the CSS property `overflow-clip-margin`
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-clip-margin

Allows you to control the visible area for clipped content when using overfllow-clip, -hidden, or -scroll and expand it with a margin.

Based on #15442

Fixes #15468

## Solution

Adds a new field to Style: `overflow_clip_margin: OverflowClipMargin`.
The field is ignored unless overflow-clip, -hidden or -scroll is set on at least one axis.

`OverflowClipMargin` has these associated constructor functions:
```
pub const fn content_box() -> Self;
pub const fn padding_box() -> Self;
pub const fn border_box() -> Self;
```
You can also use the method `with_margin` to increases the size of the visible area:
```
commands
  .spawn(NodeBundle {
      style: Style {
          width: Val::Px(100.),
          height: Val::Px(100.),
          padding: UiRect::all(Val::Px(20.)),
          border: UiRect::all(Val::Px(5.)),
          overflow: Overflow::clip(),
          overflow_clip_margin: OverflowClipMargin::border_box().with_margin(25.),
          ..Default::default()
      },
      border_color: Color::BLACK.into(),
      background_color: GRAY.into(),
      ..Default::default()
  })
```
`with_margin` expects a length in logical pixels, negative values are clamped to zero.

## Notes
* To keep this PR as simple as possible I omitted responsive margin values support. This could be added in a follow up if we want it.
* CSS also supports a `margin-box` option but we don't have access to the margin values in `Node` so it's probably not feasible to implement atm.

## Testing

```cargo run --example overflow_clip_margin```

overflow-clip-margin

## Migration Guide

Style has a new field `OverflowClipMargin`.  It allows users to set the visible area for clipped content when using overflow-clip, -hidden, or -scroll and expand it with a margin.

There are three associated constructor functions `content_box`, `padding_box` and `border_box`:
* `content_box`: elements painted outside of the content box area (the innermost part of the node excluding the padding and border) of the node are clipped. This is the new default behaviour.
* `padding_box`: elements painted outside outside of the padding area of the node are clipped. 
* `border_box`:  elements painted outside of the bounds of the node are clipped. This matches the behaviour from Bevy 0.14.

There is also a `with_margin` method that increases the size of the visible area by the given number in logical pixels, negative margin values are clamped to zero.

`OverflowClipMargin` is ignored unless overflow-clip, -hidden or -scroll is also set on at least one axis of the UI node.

### CODE REVIEW

**Review by nicoburns — APPROVED** [review]
Looks good to me. Web only implements this for `overflow:clip` (not hidden or scroll). Not sure what the reasons for that is.

**Review by BenjaminBrienen — APPROVED** [review]

**Comment by BenjaminBrienen** [comment]
Really nice showcase

**Review by UkoeHB — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
This going to have merge conflicts with its sibling PR, but ping me tomorrow and I'll get this in.

**Comment by ickshonpe** [comment]
> This going to have merge conflicts with its sibling PR, but ping me tomorrow and I'll get this in.

Weren't too bad, should be ready now.

**Pull request merged**
