### PR TITLE
[Merged by Bors] - Adds docs deadlinks check on CI

### PR DESCRIPTION
**Pull request by mnmaita**
Closes https://github.com/bevyengine/bevy/issues/1579

This is my first contribution to this repository, feel free to correct anything that I'm missing and I'll address feedback as soon as possible!

### CODE REVIEW

**Comment by CleanCut** [comment]
Since you're running the CI job on Linux, you'll need to add a step to install the Linux build dependencies. 😄 

https://github.com/bevyengine/bevy/blob/f61e44db2824c0cc4b4815748c4d3f051002ada7/.github/workflows/ci.yml#L32-L33

**Comment by mnmaita** [comment]
> 
> 
> Since you're running the CI job on Linux, you'll need to add a step to install the Linux build dependencies. 😄
> 
> https://github.com/bevyengine/bevy/blob/f61e44db2824c0cc4b4815748c4d3f051002ada7/.github/workflows/ci.yml#L32-L33

Thanks! I just figured that out. 😅 

Will be fixing it in a few. ;) 

BTW, should I use `ubuntu-latest` for this job or is it easier to run it on other platform? Any preferences on that?

**Comment by CleanCut** [comment]
> BTW, should I use `ubuntu-latest` for this job or is it easier to run it on other platform? Any preferences on that?

 `ubuntu-latest` is probably fine.  We've generally leaned that way since it has been fastest (or near fastest) while also having very predictable behavior.

**Comment by CleanCut** [comment]
The dead links have to be fixed as well!  Otherwise this PR won't pass CI. 😆

**Comment by mockersf** [comment]
I... think there are too many dead links to ask it as part of this PR. Around 7500?

We could:
- make it ignore failures for now, as a mean to track
- or open a tracking issue with the dead links split in logical groups to share the effort

**Comment by CleanCut** [comment]
> I... think there are too many dead links to ask it as part of this PR. Around 7500?

That number is high enough to make me suspicious that it's not functioning as intended.

**Comment by mockersf** [comment]
I checked a few, it seems they all come from methods from the crate [`downcast-rs`](https://crates.io/crates/downcast-rs)

**Comment by mnmaita** [comment]
I changed this so the deadlinks check doesn't fail, is this acceptable?

I'm not 100% sure on how these are fixed to be honest, any tips?

**Comment by CleanCut** [comment]
> I checked a few, it seems they all come from methods from the crate [`downcast-rs`](https://crates.io/crates/downcast-rs)

Hmm...links from documentation of _dependencies_ of Bevy is probably not helpful.

**Comment by mockersf** [comment]
ok, after digging more : 
- errors from [`downcast-rs`](https://crates.io/crates/downcast-rs) can be "fixed" by running `cargo doc --all-features && cargo deadlinks --dir target/doc/bevy` instead of `cargo deadlinks`
- errors from [`tracing`](https://crates.io/crates/tracing) should be fixed on their next release (0.2 with some breaking changes)
- an issue in rustdoc that added an anchor to a section that didn't exist (when implementing `Deref` for a target that didn't have methods, probably fixed by https://github.com/rust-lang/rust/commit/61c8aae0a9222b7d2481704094f85a0d8f6b333e, should be ok in next stable)
- some issues with rust doc itself

so... I think this is not worth it right now, maybe take a look after `tracing` release 0.2

**Comment by cart** [comment]
Thanks for looking into it!

**Comment by mockersf** [comment]
fixed a few dead links from rust std: https://github.com/rust-lang/rust/pull/82950, that will be available in two versions so... 2021/05/06

**Comment by MinerSebas** [comment]
What happens if you `--no-deps` to `cargo doc` command?
I suspect it will supress the dependencies errors, but the question is whether it bevy documention will now show errors.

**Comment by CleanCut** [comment]
@MinerSebas makes a good point that there's no need to check dependencies' documentation links. 👍🏼

**Comment by mnmaita** [comment]
> 
> 
> What happens if you `--no-deps` to `cargo doc` command?
> I suspect it will supress the dependencies errors, but the question is whether it bevy documention will now show errors, due to missing them.

So should I add `--no-deps` or replace `--all-features`?. I did some changes [here](fb79f46) based on a suggestion, please check that too since I'm kinda playing by ear here 😅.

BTW, I've read that `cargo-deadlinks` ["runs cargo doc for you"](https://github.com/deadlinks/cargo-deadlinks#usage) so I'm wondering if there's a way to pass down args to that...

**Comment by mockersf** [comment]
> I'm wondering if there's a way to pass down args to that...

Yup, you run `cargo doc` yourself, with the args you want, then `cargo deadlinks --dir path/to/the/doc/you/built`

**Comment by CleanCut** [comment]
To answer your first question: Add `--no-deps` to your `cargo doc` you run separately.

**Comment by mnmaita** [comment]
> 
> 
> To answer your first question: Add `--no-deps` to your `cargo doc` you run separately.

It's done. I've also updated the branch.

**Review by CleanCut — APPROVED** [review]
Looks great, thanks!

**Comment by cart** [comment]
Looks good to me. Lets merge this! Anyone want to volunteer to create a tracking issue / lead the effort for resolving deadlinks so we can make this job fail on deadlink detection?

**Comment by mockersf** [comment]
#1983 for tracking known dead link sources

**Pull request closed without merging**
