### PR TITLE
Implement rotation for Text2d (2nd pass)

### PR DESCRIPTION
**Pull request by CleanCut**
This is based off of @nside's excellent pull request [here](https://github.com/bevyengine/bevy/pull/2084). I wanted to help add the scaling functionality, but I couldn't figure out how to open a pull request to merge into that pull request since we're both in different forks of the `bevy` repository (I know how to do it if we're in the _same_ repository).

@nside If you would like to accept this change to be combined with yours, there's a couple options for going forward:
1. Give me collaborator access to your `nside/bevy` fork, and I can push a commit to [the pull request you already have open](https://github.com/bevyengine/bevy/pull/2084), and then I can close this pull request, or...
2. Close your pull request, and we can merge this one instead.

If you'd rather leave your changes standalone, then I'll close this PR and open a separate one later after yours is merged. (But if you do that, you should still incorporate the alignment offset fix I made!).

Changes in this PR:
- Fix the vertical and horizontal alignment _offset_ handling (the _offset_ for top/bottom and left/right alignments were reversed)
- Move `scale_factor` handling for alignment offsets entirely into `DrawableText::draw` so that the call sites don't need to know to do the calculation
- Handle scaling based off of `Transform.scale`
  - I chose the approach to scale the entire quad, resulting in pixellated text when you scale it up. This may be a desirable effect for retro 2D games. For "smooth scaling", change the font size instead.
- Updated the `text2d` example to demonstrate translation, rotation, and scale separately (combining all three was difficult to understand what was going on, plus it was making me motion-sick 😝)
  - I used a `QuerySet` to handle all the queries in a single system. Would it be simpler for the user to understand if we used three separate systems instead?

text2d-trs

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
>  but I couldn't figure out how to open a pull request to merge into that pull request since we're both in different forks of the bevy repository (I know how to do it if we're in the same repository).

For future reference, I've found that the way to do this is to create multiple local clones of the same repo by putting them in different directories, then work from that directory and create a pull request like that <3

**Comment by mockersf** [comment]
> but I couldn't figure out how to open a pull request to merge into that pull request since we're both in different forks of the `bevy` repository (I know how to do it if we're in the _same_ repository).

You can add many remotes to your local fork. You probably have `origin` that points to your fork on GitHub, and `upstream` that points to official Bevy repo.
You can `git remote add nside-fork git@github.com:nside/bevy.git` locally, then you'll be able to rebase on their branch by using `nside-fork` instead of `upstream`

**Comment by CleanCut** [comment]
@alice-i-cecile I'm not following how either of those approaches allows me to _open the pull request_. What am I missing? I'm already using multiple remotes on my local repository.  I wasn't able to find a way in the GitHub UI to open a pull request with nside's fork as a base.  In fact, that was the weirdest part: other forks showed up in the base list, but not nside's.

**Comment by mockersf** [comment]
oh if it's GitHub UI it can be strange at times... you can force its hand by going to https://github.com/nside/bevy/compare/text2d-rotation...your_branch_name_here?expand=1

**Comment by CleanCut** [comment]
> oh if it's GitHub UI it can be strange at times... you can force its hand by going to https://github.com/nside/bevy/compare/text2d-rotation...CleanCut:text2d-rotation?expand=1

That URL did get nside's fork into the base list! 🎉  Odd that it wasn't showing up otherwise--I even tried navigating to his fork's pull request page and clicking "new pull request"--no luck there.  Oh well.

Closing this PR in favor of a PR against @nside's PR here: https://github.com/nside/bevy/pull/1

**Pull request closed without merging**
