### PR TITLE
Fix Mesh allocator bug and reduce Mesh data copies by two

### PR DESCRIPTION
**Pull request by atlv24**
# Objective

- First step towards #15558

## Solution

- Rename `get_vertex_buffer_data` to `create_packed_vertex_buffer_data` to make it clear that it is not "free" and actually allocates
- Compute length analytically for preallocation instead of creating the buffer to get its length and immediately discard it
- Use existing vertex attribute size calculation method to reduce code duplication
- Fix a bug where mesh index data was being replaced by unnecessarily newly created mesh vertex data in some cases
- Overall reduces mesh copies by two. We still have plenty to go, but these were the easy ones.

## Testing

- I ran 3d_scene, lighting, and many_cubes, they look fine.
- Benchmarks would be nice, but this is very obviously a win in perf and correctness.

---

## Migration Guide

- `Mesh::create_packed_vertex_buffer_data` has been renamed `Mesh::create_packed_vertex_buffer_data` to reflect the fact that it copies data and allocates.

## Showcase

- look mom, less copies

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by kristoff3r — APPROVED** [review]
Wow, it's pretty misleading that a function called `get_vertex_buffer_data` does a copy of the mesh. Nice find!

**Comment by greytdepression** [comment]
@alice-i-cecile In the migration guide it should be "`Mesh::get_vertex_buffer_data` has been renamed..." :)

**Comment by alice-i-cecile** [comment]
Fixed, thanks @greytdepression.

**Comment by greytdepression** [comment]
@alice-i-cecile Sorry to ping again, but I think you forgot to add a backtick after `Mesh::get_vertex_buffer_data`

**Pull request merged**
