### PR TITLE
Add example for bounding volumes and intersection tests

### PR DESCRIPTION
**Pull request by NiseVoid**
# Objective

- Create an example for bounding volumes and intersection tests

## Solution

- Add an example with a few bounding volumes, created from primitives
- Allow the user to cycle trough the different intersection tests

### CODE REVIEW

**Comment by NiseVoid** [comment]
https://github.com/bevyengine/bevy/assets/3254486/77426a89-67eb-4481-be63-02cff88a1af3

This is what the example looks like.

**Comment by alice-i-cecile** [comment]
That example video is a fantastic candidate for the blog post.

**Review by alice-i-cecile — APPROVED** [review]
LGTM in its current form. Would you like me to merge https://github.com/bevyengine/bevy/pull/11072 now so you can use the gizmos?

**Comment by NiseVoid** [comment]
I filled up the duplicate circle spots with other shapes now:

image

**Review by Jondolf — APPROVED** [review]
LGTM!

**Comment by alice-i-cecile** [comment]
Ran this locally: looks awesome. Great stuff!

**Pull request merged**
