### PR TITLE
[Merged by Bors] - Remove spirv-reflect from readme

### PR DESCRIPTION
**Pull request by IceSentry**
# Objective

- The libraries used section of the README is outdated and is missing a lot of libraries
- The README isn't really the place for that anyway

## Solution

- Remove the section

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Agreed. This made a lot more sense on initial release, but isn't actionable / useful information for beginners or contributors.

**Review by Nilirad — APPROVED** [review]

**Comment by Nilirad** [comment]
I agree on that, but should it be blocked on cart since it's a very historical piece of the readme?

**Comment by alice-i-cecile** [comment]
I don't think it should be blocked on him here. This is a straightforward docs change that improves UX, and the simple fact that it's old (or in the README) shouldn't impact this. That said, ping @cart for clarity?

**Comment by mockersf** [comment]
This isn't just doc, it's also a shoutout to foundational libraries for Bevy.
While spirv-reflect isn't used anymore, it's very unlikely that we will stop using the others. Naga could be added as it's one of the big bricks that allows cross platform

**Comment by cart** [comment]
I do like that we shout out foundational libraries. Things like wgpu / naga / winit / glam are central to bevy's success and the devs of those projects deserve high visibility recognition. I think in the short term we shouldn't remove the section, but instead just remove spirv-reflect.

We can discuss alternative ways to boost projects in this category, but I don't want to remove this until we have some other form of recognition in place.

**Comment by alice-i-cecile** [comment]
Sounds good. My preference would be on the Bevy website, ideally in the same sort of place we talk about sponsors.

**Comment by IceSentry** [comment]
>  just remove spirv-reflect.

Done!

**Review by mockersf — APPROVED** [review]

**Pull request closed without merging**
