### PR TITLE
[Merged by Bors] - `transparency_3d` example tweaks

### PR DESCRIPTION
**Pull request by MiniaczQ**
Fixed a typo, removed unused component, normalized comments added a touch more detail.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Good eye :)

**Comment by MiniaczQ** [comment]
Actually, before merging, I'd like to add a possible use case of `Mask(f32)`, but I'm not sure myself what it'd be.
It works like a poor's man `alpha` driven `is_visible`, because it still renders the shadow. :/

**Comment by MiniaczQ** [comment]
Okay, so Mask isn't supposed to leave a shadow, guess it's fine to merge then, I'll make an issue for that

**Pull request closed without merging**
