### PR TITLE
Add bevy_core as a dev dependency to bevy_ecs

### PR DESCRIPTION
**Pull request by Nilirad**
# Objective

As I'm working on #2365, I'm noticing that adding dev dependencies between bevy crates could be very helpful for writing good documentation examples.

## Example

I'll use as an example the documentation I'm writing for `Query::iter_mut`.

### Without dev dependency

I have to replicate a dummy `Time` resource. In case of edits to the real `Time`, this example will fall out of sync and become potentially misleading.

```
# use bevy_ecs::prelude::*;
#
# struct Velocity { x: f32, y: f32, z: f32 }
# struct Time;
# impl Time {
#     fn delta_seconds(&self) -> f32 { 1.0 / 60.0 }
# }
#
fn gravity_system(mut query: Query<&mut Velocity>, time: Res<Time> ) {
    for mut velocity in query.iter_mut() {
        velocity.y -= 9.8 * time.delta_seconds();
    }
}
# gravity_system.system();
```

### With dev dependency

No more dummy. Test suite will raise an error if `Time` changes.

```
# use bevy_ecs::prelude::*;
# use bevy_core::prelude::*;
#
# struct Velocity { x: f32, y: f32, z: f32 }
#
fn gravity_system(mut query: Query<&mut Velocity>, time: Res<Time> ) {
    for mut velocity in query.iter_mut() {
        velocity.y -= 9.8 * time.delta_seconds();
    }
}
# gravity_system.system();
```

# Solution

- Change `Cargo.toml` file of `bevy_ecs` to include `bevy_core` to the `dev-dependencies`.

### CODE REVIEW

**Comment by mockersf** [comment]
`bevy_ecs` should avoid depending on additional parts of Bevy, even for docs, as it can be used independently

**Comment by alice-i-cecile** [comment]
> bevy_ecs should avoid depending on additional parts of Bevy, even for docs, as it can be used independently

Hmm. I agree that this *should generally* be the case, but many `bevy_ecs` examples end up a bit artificial without any useful primitives to work with. Maybe that's a worthwhile sacrifice though.

**Comment by cart** [comment]
> Hmm. I agree that this should generally be the case, but many bevy_ecs examples end up a bit artificial without any useful primitives to work with. Maybe that's a worthwhile sacrifice though.

Imo its better to inline code here than to couple bevy_ecs to other parts of bevy.

**Comment by Nilirad** [comment]
Ok, I'm closing it in favor of a simpler approach. I realized that for the example above, removing altogether the resource fetch will make it easier to read. I'll just put a `1.0 / 60.0` instead of delta time. After all, the important thing is not making a production quality example, but a didactically correct example (from the API perspective)

**Pull request closed without merging**
