### PR TITLE
One-shot systems as `Command`s -- allow commands to use `SystemParam`s

### LINKED ISSUE #2192: One-shot systems via Commands for scripting-like logic
## What problem does this solve or what need does it fill?

Some operations are only done very rarely:  scripting-like game logic that modifies levels, unlocks achievements or handles a boss's special attack come to mind.

These systems clutter the schedule, waste resources as they constantly spin, and are harder to extend.

## What solution would you like?

There are two parts to my proposed solution:

1. Add  `Commands::run_system(system: impl Into<SystemDescriptor>)`. This runs the specified system on the `World` the next time commands are processed.
2. Create a pattern where we store references to system functions on components, and dynamically run those systems when the appropriate trigger is met, allowing for scripting-like flexibility with low-overhead and seamless ergonomic Bevy syntax. 

## What alternative(s) have you considered?

Writing custom commands types each time will be onerous and have much increased boilerplate, and because they take exclusive access to `World`, force the users to learn a new syntax and reduce our ability to parallelize commands of this sort in the future.

This same functionality could also be framed as "dynamically inserting systems", but that may complicate the API somewhat when you often don't end up caring a lot about overhead.

Other approaches to reactivity may be able to fill this niche in some form instead.

## Additional context

Making sure the ordering on this is correct enough is going to be one of the larger challenges. May be better to wait until after #1375. Chaining also needs some careful thought.

Brought up in response to the following [user request](https://discord.com/channels/691052431525675048/742884593551802431/843675331131080704):

>  Is it possible / practical / good practice to pass a function around inside an event? My thought process is an NPC could have an interaction with a very specific procedure following it like opening a secret door across the map or unlocking a new dialogue option with another NPC so much so that having a system that contains every one of these niche interactions inside a match would be rather hideous.

Depending on the efficiency and ergonomics of this, could also be used to support push data-flow for UI (see #254).

Related to #1273.

### PR DESCRIPTION
**Pull request by JoJoJet**
# Objective

Fixes #2192.

Currently, anonymous one-shot commands can be defined as a closure accepting `&mut World`. Working with exclusive world access is quite cumbersome, and is usually only necessary if a command makes changes to a world's archetypes. In cases where a command simply needs to access and mutate world data, it is much more ergonomic to do so via `SystemParam`s such as `ResMut<>` or `Query`.

## Solution

* Add the trait `CommandSystemParam`, which is a subset of `SystemParam` that excludes types that don't make sense for one-shot systems, such as `Local<>` or `Commands`.
* Any systems consisting of `CommandSystemParam`s may be used as a command.

### Example

```rust
// One-shot systems are run by calling `Commands::add`.
commands.add(|main_character: Res<MainCharacter>,
              mut characters: Query<&mut Character>| {
    let main_character = characters.get_mut(main_character.id()).unwrap();
    main_character.do_thing();
});
```

---

TODO: Docs. I'd like to see the response to this PR before putting in the effort to write full documentation.

TODO: Look into storing "command systems" in a registry resource, to avoid duplicate initialization code. This will require benchmarking.

## Changelog

TODO

## Migration Guide

TODO

### CODE REVIEW

**Comment by JoJoJet** [comment]
@alice-i-cecile I don't need a full review or approval yet, but I'd like to get your opinion on this PR before I move forward with it.

**Comment by alice-i-cecile** [comment]
I agree that we want a commands-powered API for one-shot systems :) Concerns with this approach though:

1. This doesn't cache state, which means a) serious efficiency cost b) no change detection. This was a dealbreaker for Cart in my early experiments, which is what led to the design in #4090.
2. I think you really want a dedicated collection for systems that are supposed to run at the next command flush, in order to unlock future parallelism.
3. I don't like the addition of yet another trait with `CommandSystemParam`. With 1 resolved, I don't think it's needed.

Excited to see work towards one-shot systems in one form or another, but I'm not sold on this approach.

**Comment by JoJoJet** [comment]
1. I think that the efficiency cost is overstated -- this approach has no overhead compared to using `SystemState` manually inside of a `|&mut World|` command. Also, I don't think change detection even makes sense within a one-shot system, so this isn't a loss IMO.
2. This is probably a cleaner solution.

**Comment by alice-i-cecile** [comment]
> I think that the efficiency cost is overstated

Generally agreed, but not my requirement :p

> Also, I don't think change detection even makes sense within a one-shot system, so this isn't a loss IMO.

Once you start looking at using one shot systems for UI callbacks this makes a lot of sense to me :)

**Pull request closed without merging**
