### PR TITLE
smoother loops in repeating animations

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- When looping animations, there are some cases with a small difference between the last frame and the first. This can result in a small jump. It is very hard to unsee

https://user-images.githubusercontent.com/8672791/224546509-6f3950d0-93fe-4983-9e3e-9b52d0a61e7c.mp4

Here the animation has keyframes at 30 FPS, when played at 120 FPS the jump is 4 frames long

## Solution

- lerp between the last frame and the first when the first doesn't start at timestamp 0

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by CooCooCaCha** [comment]
I strongly believe that bevy should avoid little bits of implicit behavior like this. If someone’s animation is messed up they should fix it themselves or this could be a setting that’s turned off by default. Or it could be a plug-in used during the asset processing step when bevy gets a revamped asset system.

I know it’s tempting to put up guardrails but it’s incredibly annoying to hunt down and fix guardrails that conflict with your project. What if I want to make a game with low frame rate animations like stop motion?

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
I no longer think we should do this: implicit behavior is bad.

**Comment by torsteingrindvik** [comment]
I recently wanted something like this.

My use case is that I bought an asset from an asset website and it contained animations. I am happy with the animations, but they have ugly jumps when repeating.
I'd prefer not to edit the animations in Blender- I would be very happy if Bevy could do what this PR does.

Could we consider making this explicit/opt-in via some setting?

**Comment by alice-i-cecile** [comment]
For an opt-in behavior, perhaps this actually makes sense as an asset preprocesser? The asset is fundamentally broken: rather than fixing it live every time, shouldn't we actually just change it?

**Comment by torsteingrindvik** [comment]
> For an opt-in behavior, perhaps this actually makes sense as an asset preprocesser? The asset is fundamentally broken: rather than fixing it live every time, shouldn't we actually just change it?

I think that could work.
I'd love for that to be customizable such that the interpolation variant and how long the transition back to start is via some processing settings.

**Comment by CooCooCaCha** [comment]
A self-contained asset processor that you can add to your pipeline like a plugin sounds like a good idea.

Adding it to the default processor as an option is likely to result in the default processor becoming a dumping ground for options which IMO is confusing and intimidating for users.

**Pull request closed without merging**
