### PR TITLE
Fix button bug on iOS

### PR DESCRIPTION
**Pull request by rustui**
# Objective

On a real iOS device, buttons are sometimes unresponsive when tapped for the first time.

`ui_focus_system` needs to obtain the touch position through `Touches`'s `pressed`, but `pressed` is sometimes cleared because both `TouchPhase::Started` and `TouchPhase::Ended` are triggered in the same frame. The deeper reason may be that `InputSystem` is in `CoreSet::PreUpdate`, and native touch events are sent faster than the screen's refresh rate.

## Solution

If it detects that `TouchPhase::Started` and `TouchPhase::Ended` with the same `id` are in the same frame, defer `TouchPhase::Ended`'s `process_touch_event` to the next frame.

---

### Changed
`touch_screen_input_system`'s method signature changes from
```rust
pub fn touch_screen_input_system(
    mut touch_state: ResMut<Touches>,
    mut touch_input_events: EventReader<TouchInput>,
)
```
to
```rust
pub fn touch_screen_input_system(
    mut touch_state: ResMut<Touches>,
    mut touch_input_events: EventReader<TouchInput>,
    mut ended_events: Local<Vec<TouchInput>>,
)
```

### CODE REVIEW

**Comment by rustui** [comment]
> On a real iOS device, buttons are sometimes unresponsive when tapped for the first time.

"sometimes" is too conservative, buttons are unresponsive very often on my iPhone SE 2, although on the iOS simulator they generally work fine.
It would be nice to have a temporary solution before a new version is released.

**Comment by mockersf** [comment]
I can't reproduce on my devices, but could you check with https://github.com/mockersf/bevy/tree/touches-position-also-in-just_pressed if it fixes the issue for you?

I would prefer it to this PR has it doesn't introduce a delay for some events.

**Comment by rustui** [comment]
Yes, your fork fixes the issue on my iPhone SE 2. Without your fix, buttons still are unresponsive often on the main branch.
I agree with you, your solution is more concise. Thanks for the fix.

**Comment by mockersf** [comment]
Thanks for checking! I opened a PR in #7743

**Comment by mnmaita** [comment]
Was this finally fixed in the PR that closed https://github.com/bevyengine/bevy/issues/12442? Maybe we can close this one if someone can confirm @mockersf @alice-i-cecile.

**Pull request closed without merging**
