### PR TITLE
Enable wgpu device features and limits

### PR DESCRIPTION
**Pull request by Neo-Zhixing**
Alternative implementation to #547.
This PR also added `WgpuFeatures`, `name`, and `WgpuLimits` to `WgpuOptions`. Additionally, it also re-exported certain wgpu render resource limit constants.

This is ready for review.

### CODE REVIEW

**Comment by verzuz** [comment]
"getting stuck" is not the right way to call my PR, but I dont mind - @cart can pick which one he wants use.

**Comment by cart** [comment]
Cool I'll do a review of both in the near future.

**Comment by cart** [comment]
@Neo-Zhixing @verzuz

I was initially inclined to merge this pr as it also includes wgpu limits and the api is a closer match to Wgpu. I also like how this pr include WgpuFeatures inside of WgpuOptions. However #547 has the desirable behavior of breaking when the wgpu bitflags change (ex: a flag is renamed or removed). A list of enums is also more serialization-friendly, and there is a world where we move to "serialized" plugin configuration for the Bevy Editor.

I think I'll merge #547 (with DeviceFeatures merged into WgpuOptions), but it would be awesome if this pr could be adapted to account for #547 so we can get the nice WgpuLimits config too.

**Comment by Neo-Zhixing** [comment]
@cart I've added #1544 for WgpuLimits.

**Pull request closed without merging**
