### PR TITLE
[Merged by Bors] - Fix typo in Xtask CI

### PR DESCRIPTION
**Pull request by lambdagolem**
I think there was a typo here. If this is not a typo and I misunderstood the comment please just ignore this PR.

### CODE REVIEW

**Comment by bjorn3** [comment]
Thanks for the PR. Seems to be a typo to me too.

**Comment by mockersf** [comment]
👋 it is an error indeed!

It should be fixed as part of #1508 , but this may go faster if discussion is still ongoing there

**Review by CleanCut — APPROVED** [review]
Yep, also fixed in #1508.  This PR can be merged or closed. Either way works.

**Pull request closed without merging**
