### PR TITLE
[Merged by Bors] - Update linux_dependencies.md

### PR DESCRIPTION
**Pull request by godsmith99x**
Thanks for making Bevy. Recommend adding rust-libudev-devel as an additional dependence for Fedora.

# Objective

- Describe the objective or issue this PR addresses.
- If you're fixing a specific issue, say "Fixes #X".

## Solution

- Describe the solution used to achieve the objective above.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Awesome thanks! Once we can get someone else to verify this (I'm not a Linux expert, and don't have a Fedora install to play with), I'll be happy to merge it in.

**Comment by rparrett** [comment]
Also not a linux expert, but it seems like folks using `rustup` to manage their rust install might not want to install this package?

**Comment by alice-i-cecile** [comment]
@godsmith99x, do you have any thoughts on why Fedora might need this dep, but other distros don't seem to?

**Comment by godsmith99x** [comment]
Sorry, I wouldn't call myself an expert either. I'm new to rust. I used rustup to install my tool chain, but the bevy breakout example didn't compile, at first. I just followed the compiler errors to locate the missing packages until it worked. Just wanted to share my experience. Hope it is helpful.

**Comment by alice-i-cecile** [comment]
Sounds good. I'll ask around in the broader community and see if I can find any answers. Thanks for letting us know!

**Comment by alice-i-cecile** [comment]
So, summary of my investigation:
- [rust-libudev-devel](https://src.fedoraproject.org/rpms/rust-libudev-sys) enables FFI bindings for the Rust crate `libudev-sys`.
- [libudev-sys](https://crates.io/crates/libudev-sys) enables an API to access the `libudev` C library
- [libudev](https://www.freedesktop.org/software/systemd/man/libudev.html) lists and enumerates connected devices

So this is probable getting pulled in by either `winit` or `gilrs`. Looks like [`gilrs`](https://github.com/Arvamer/gilrs/blob/master/gilrs-core/Cargo.toml#L24).

We need an equivalent crate for `Ubuntu`: `sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev`, which makes this much less mysterious.

Okay, this makes sense to me now! Thanks for the troubleshooting, I'll merge it in :)

**Comment by KirmesBude** [comment]
Hi @alice-i-cecile,

As @rparrett mentions this conflicts with rust that was installed using rustup.
Rustup is probably the preferred installation method, rather than using the package manager.

For me (rustup installation inside a toolbox with the Fedora35 base image), I ran into the following build error:
```
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit status: 1\nerror: could not find system library 'libudev' required by the 'libudev-sys' crate\n\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'libudev', required by 'virtual:world', not found\n"', /var/home/bude/._toolbox/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/libudev-sys-0.1.4/build.rs:38:41
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Which was resolved with just `sudo dnf install systemd-devel`.

Blindly following the dependencies and installing `rust-libudev-devel` will install rust via the package manager,
Took me a few hours to understand why rust-analyzer was no longer finding rust-src, because it now attempts to search for it in /usr/lib instead of ~/.rustup/lib.

If you do get rust from your package manager, maybe `rust-libudev-devel` is actually necessary.
But I dont think suggesting this by default is a good idea.

We should probably ask the user to install rust via rustup and optionally provide additional packages if you do decide to install rust via the package manager.

**Pull request closed without merging**
