### PR TITLE
Implement Clone for VisibilityBundle and SpatialBundle

### PR DESCRIPTION
**Pull request by doonv**
# Objective

Had an issue where I had `VisibilityBundle`  inside a bundle that implements `Clone`, but since `VisibilityBundle` doesn't implement `Clone` that wasn't possible. This PR fixes that.

## Solution

Implement `Clone` for `VisibilityBundle` by deriving it. And also `SpatialBundle` too because why not.

---

## Changelog

- Added implementation for `Clone` on `VisibilityBundle` and `SpatialBundle`.

### CODE REVIEW

**Review by alice-i-cecile — COMMENTED** [review]
Can you check if SpatialBundle (and ideally our other premade bundle types) need this treatment too?

**Comment by doonv** [comment]
Good call, I Implemented `Clone` for `SpatialBundle` too. I checked and I don't think theres a common bundle that also requires this treatment.

**Review by alice-i-cecile — APPROVED** [review]

**Review by JoJoJet — APPROVED** [review]

**Review by JMS55 — APPROVED** [review]

**Comment by doonv** [comment]
Huh, why did it fail building wasm?

**Comment by alice-i-cecile** [comment]
Looks like a semver violating change / new bug in one of our dependencies :( 

We may need to pin async_executor: https://github.com/smol-rs/async-executor/issues/72 (thanks @Bluefinger).

**Review by james7132 — APPROVED** [review]

**Pull request merged**
