### PR TITLE
[Merged by Bors] - Add a separate ClearPass

### LINKED ISSUE #3190: Support for RenderPass that renders to WindowSwapChain before MainPass
## What problem does this solve or what need does it fill?

I want to add a RenderPassthat renders to WindowSwapChain before MainPass. 
This currently does not seem possible because of the Operation defined in the PassDescriptor of MainPass, that clears the color attachment.
https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/render_graph/base.rs#L141

## What solution would you like?

Clearing the color_attachment should be its own pass before MainPass, so users can add their own passes before MainPass.

## What alternative(s) have you considered?

Alternatively there could be a way to change the Operation/PassDescriptor of MainPass at runtime or during initial creation (by way of parameter to RenderPlugin)

## Additional context

You can fínd my attempt at adding a RenderPass before MainPass here: https://github.com/KirmesBude/bevy_background
Minimal example including a RenderGraph svg dump.

Edit: The issue exsits on 0.6, but the proposed solutions are different.

### PR DESCRIPTION
**Pull request by KirmesBude**
# Objective

- Rendering before MainPass should be possible, so clearing needs to happen in an earlier pass.
- Fixes #3190.

## Solution

- I added a "Clear" SubGraph, a "ClearPassNode" Node, that clears the color and depth attachments of all views and a "ClearNodeDriver" Node, that schedules the "ClearPassNode" before MainPass.
- Make sure that the 2d and 3d draw passes do not clear their attachments anymore.

### Notes

- It works in the way, that with the current pipeline examples nothing should have changed in their behaviour
- I would like to add an example that adds a pass inbetween ClearPass and MainPass, but I do not understand enough about the new render architecture to do that yet
- Clears all attachment for all views: I do not know enough about rendering in general to say, whether there is a use case for not clearing
- Does not solve #3043 as we still need Cameras/ViewTargets to clear.

### CODE REVIEW

**Comment by jakobhellermann** [comment]
The way this is implemented right now won't quite fix #3190 yet because `ViewTarget`s are only extracted for cameras in the scene. Are you in the [bevy discord](https://discord.com/invite/bevy)? I opened a thread today discussing possible solutions: https://discord.com/channels/691052431525675048/743663924229963868/914117453150322718

**Comment by KirmesBude** [comment]
Yes, I do occasionally lurk on the discord :D. Came across the thread after I had already done my initial changes. 
If I understood the thread correctly its specifically about the case where no cameras are used? (the MSAA discussion did not seem very relevant)

I feel like this would theoretically fix #3190, but I if there is more to it as was discussed in the thread, maybe it makes sense to have a complete solution from the beginning. 
I will try to understand the proposed solutions and see if I am able to implement any of them.

**Comment by jakobhellermann** [comment]
Oh, I mixed up #3190 and #3043. I guess I had the other issue on my mind and didn't read the PR description properly 😃

**Review by StarArawn — APPROVED** [review]
This looks good to me! It allows rendering of both 2d and 3d at the same time. I think in the future we might want to make the views configurable so you can specify which ones get cleared, but I don't think that's required yet. Can we get main merged in or this branch rebased to get rid of the merge conflicts?

**Comment by cart** [comment]
Yeah I agree that ultimately we'll want "per view" clear behaviors / graphs, but those changes seem like they will go hand in hand with the addition of "multiple render targets". This implementation seems like a perfectly reasonable interim solution.

**Comment by cart** [comment]
I believe CI should be working now. Lets give it a go!

**Pull request closed without merging**
