### PR TITLE
[Merged by Bors] - Add `Windows::get_focused(_mut)`

### LINKED ISSUE #5646: `close_on_esc` does nothing if window was immediately focused on creation
https://github.com/bevyengine/bevy/blob/55957330351828e84bfc63cf8e151e2805e9d278/crates/bevy_window/src/system.rs#L46

On Linux with i3 WM, sometimes the app window will be focused on creation with no initial `WindowFocused` event. When this happens, `close_on_esc` does nothing until you unfocus and refocus the window to send a `WindowFocused` event.

### PR DESCRIPTION
**Pull request by devil-ira**
Add a method to get the focused window.

Use this instead of `WindowFocused` events in `close_on_esc`.
Seems that the OS/window manager might not always send focused events on application startup.

Sadly, not a fix for #5646.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Comment by DJMcNab** [comment]
I'd not looked into this before. Surely assuming that every window is focused on creation also doesn't make sense.

E.g. on systems where new windows don't get focus automatically

Something else needs to change here, I think. We need winit to provide some guidance here.

**Comment by ryrony123** [comment]
Crop vdftt4gr tv d

**Comment by devil-ira** [comment]
Thanks for pointing that out. I had thought that `focused` would get its initial state from winit, but it simply defaults to `true`.
Looked through the winit docs and focus events is all the info we have on the window's focused state, leading me to believe the linked issue is a bug in the i3 window manage.

I've changed `focused` to be `false` on window creation as `true` causes the following system to print '2' for a single frame when added to the `multiple_windows` example.
```rust
.add_system(|windows: Res<Windows>| {
    println!("{}", windows.iter().filter(|w| w.is_focused()).count())
})
```

**Comment by DJMcNab** [comment]
There is the possibility that a rogue Window 'unfocused' event is getting in there (e.g. `1: true, 2: false` is sent in that order), which this would handle correctly but `close_on_esc` currently does not.

**Comment by devil-ira** [comment]
> There is the possibility that a rogue Window 'unfocused' event is getting in there (e.g. 1: true, 2: false is sent in that order)

Surely that would be considered a bug in the window manager?

**Review by DJMcNab — APPROVED** [review]
I'm happy with this now

**Pull request closed without merging**
