### PR TITLE
Added `add_group` to `PluginGroupBuilder`

### LINKED ISSUE #751: Enable subgroups for PluginGroups
The primary place I see this being used is for DefaultPlugins.
Would allow bevies' default plugins to to take advantage of PluginGroups with only a PluginGroup instead of a Plugin + PluginGroup.

Example API:
```rust
// Implements Plugin
pub struct FooPlugin;
// Implements Plugin
pub struct BarPlugin;
// Implements PluginGroup
pub struct CowPlugins;

// Example plugin group
pub struct ExamplePlugins;

impl PluginGroup for ExamplePlugins {
    fn build(&mut self, group: &mut PluginGroupBuilder) {
        group
            .add(FooPlugin)
            .add_group(CowPlugins)
            .add(BarPlugin);
    }
}
```

### PR DESCRIPTION
**Pull request by bushrat011899**
# Objective

- Fixes #751

## Solution

- Added `PluginGroupBuilder::add_group`, which accepts an owned `impl PluginGroup` and adds those plugins to self, following `PluginGroupBuilder::add`'s replacement rules.
- Split `PluginGroupBuilder::upsert_plugin_state` into two functions, one of the same name, and `PluginGroupBuilder::upsert_plugin_entry_state` which takes a `PluginEntry` and `TypeId` directly. This allows for shared behaviour between `add` and `add_group`.
- Added 2 unit tests documenting the replacement behaviour in `PluginGroupBuilder::add_group`.

### CODE REVIEW

**Comment by ActuallyHappening** [comment]
This is a feature I would benefit from, what's holding this back from merging?

**Comment by bushrat011899** [comment]
> This is a feature I would benefit from, what's holding this back from merging?

Glad to hear it! I've rebased this onto the current main branch just to make sure there aren't any issues. Perhaps you could leave a review if you feel comfortable doing so to spur on the adoption process?

**Review by ActuallyHappening — APPROVED** [review]
Looks good, the tests are correct and properly test ordering plugins in plugin groups.
The signatures of the old public API don't change so this isn't a breaking change.

**Comment by ActuallyHappening** [comment]
Maybe for future consideration, its not possible to order plugin *groups* relative to other plugin *groups*, but I don't need this functionality

**Comment by AustinHellerRepo** [comment]
I would love this feature to get merged in. What are the next steps?

**Comment by ActuallyHappening** [comment]
Yes, I would also love for this to merged!

**Review by alice-i-cecile — APPROVED** [review]
This seems like a reasonable extension of the `PluginGroup` API. My apps tend to be pretty simple flat collections of plugins, so I would definitely be curious to hear more about what users are using this abstraction for in practice

Thanks for the great docs and tests :)

**Comment by ActuallyHappening** [comment]
I'm authoring a library where I depend on `bevy_xpbd`s plugins to be initialised. `bevy_xpbd` exports a *bunch* of plugins, which they organise into a single plugin group. I want to be able to export a single plugin group which contains all of their plugins and my own. This seems the best way of doing that, without requiring users to (read my docs and) initialise `bevy_xpbd` themselves, although that really isn't a bad solution currently.

**Comment by AustinHellerRepo** [comment]
I'm also writing a library that itself is a plugin bundle that utilizes another plugin bundle. Thanks for merging this!

**Comment by ActuallyHappening** [comment]
I'm pretty sure this made it into 0.13 so yay!

**Comment by simbleau** [comment]
> I'm pretty sure this made it into 0.13 so yay!

It didn't... At least I don't see it? What happened to this?

**Comment by simbleau** [comment]
Yeah. Confirmed, it's not in 0.13 - Should be in 0.14?

**Comment by bushrat011899** [comment]
> Yeah. Confirmed, it's not in 0.13 - Should be in 0.14?

Correct! This was merged about a week after 0.13 came out so this should be on track to be included in 0.14 (you can currently see it on [`main`](https://github.com/bevyengine/bevy/blob/b0409f63d5488b209d80f75aa332b6515c8b80d3/crates/bevy_app/src/plugin_group.rs#L135-L151)

**Comment by ActuallyHappening** [comment]
Oh well, guess I'll hold off using bevy until 0.14 ;)

**Pull request merged**
