### PR TITLE
bevy_dynamic_plugin: fix doc typo

### PR DESCRIPTION
**Pull request by globin**
# Objective

- Fixes minor documentation typo

## Solution

- Using the correct word

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Are you sure this isn't deliberate? Dynamically loading and dynamically linking are both real things, and there's a chance that @cart meant the former here.

**Comment by globin** [comment]
From looking at the code and function name I'm pretty sure dynamic loading is the intention.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by BD103** [comment]
I don't think this is a typo. The function in question does dynamically link to the given path, where it then resolves the `_bevy_create_plugin` symbol and calls it.

`libloading`, the library used in question, is just a wrapper over `libc::dlopen`.

image

This change may help abstract over the dynamic linking process, but the original wording was not a mistake.

**Comment by alice-i-cecile** [comment]
Going to close this out then: while debatable, I don't think this is a typo.

**Pull request closed without merging**
