### PR TITLE
attempt work around rustc regression

### PR DESCRIPTION
**Pull request by BoxyUwU**
# Objective

CI is failing because of a rustc bug

## Solution

Explicitly write out `'_` instead of eliding it

---

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Giving this P-Critical, because otherwise CI will fail on everything and we won't be able to merge anything.

The regression in question: https://github.com/rust-lang/rust/issues/96540

**Comment by mockersf** [comment]
I would rather wait for rust to fix the issue than work around it in Bevy.
If we want a quick fix we can use a nightly from before the issue.

On the rust PR that introduces the issue it was mentioned they either want a quick fix or a revert soon

**Comment by alice-i-cecile** [comment]
Regression appears to be addressed! https://github.com/rust-lang/rust/pull/96559

Going to test this out on another PR, and see if that's fixed it for us.

**Comment by alice-i-cecile** [comment]
Still failing: https://github.com/bevyengine/bevy/runs/6237109995?check_suite_focus=true. We should try again after the next nightly release.

**Pull request closed without merging**
