### PR TITLE
Fix typos in `config_fast_builds.toml`

### PR DESCRIPTION
**Pull request by benfrankel**
From https://github.com/TheBevyFlock/bevy_new_2d/pull/317 plus a few other changes.

### CODE REVIEW

**Review by MiniaczQ — APPROVED** [review]

**Comment by mockersf** [comment]
do you know why this file isn't checked by the typo CI?

**Review by mockersf — APPROVED** [review]

**Comment by benfrankel** [comment]
CI uses the `crate-ci/typos` action, which has info on this in its FAQ: https://github.com/crate-ci/typos?tab=readme-ov-file#why-was--not-corrected

**Comment by mockersf** [comment]
> EDIT: Following this, it seems we have `ignore-hidden` set to `true` (which is the default value) so `typos` skips the `.cargo/` directory.

Thanks!

I think it could be worth a try to check if disabling that doesn't raise too many issues

**Comment by benfrankel** [comment]
> I think it could be worth a try to check if disabling that doesn't raise too many issues

The output seems good to me if we also explicitly exclude `.git`. I can make a separate PR for this.

**Pull request merged**
