### PR TITLE
Optional batch size for bevy_render

### PR DESCRIPTION
**Pull request by ManevilleF**
# Objective

Following #4489 by @aevyrie I think we can improve the batching:
- [x] Making it optional* but enabled by default
- [x] Making the batch size customizable
- [ ] Propagating the batching to other `bevy_render` systems

## Solution

I'm opening this *Draft* showing how I think we can apply the target improvements:

- The batch size can be enabled or disabled directly through the `RenderPlugin` where I added an optional field, set by default to `1024` like in #4489 .
- The systems retrieve the batch size through an **optional** resource, meaning we can **add**, **edit** or **remove** this resource at any time, making it customizable and dynamic.

## Notes
  
- The code is not very pretty but I think there are ways to improve it or maybe make the whole conditional parallelization *generic* and therefore easily appliable to other systems in `bevy_render` or maybe other crates.
- I didn't test or benchmark the new code yet, since I don't think this MR should be merged before the design is discussed

### CODE REVIEW

**Comment by ManevilleF** [comment]
An other design choice could be that `RenderBatchSize` is always present and set through a `App::init_resource()` but storing an `Option<usize>` for the `batch_size`.
this would mean that it could be retrieved through `Res<>` instead of `Option<Res<>>` and maybe add clarity

**Comment by james7132** [comment]
Wouldn't #4777 largely remove the need for this?

**Comment by ManevilleF** [comment]
> Wouldn't #4777 largely remove the need for this?

Absolutely, I didn't know it existed but if the batch size can be dynamically estimated I don't think there is need for a config resource

**Comment by ManevilleF** [comment]
#4777 and #4663 make this obsolete

**Pull request closed without merging**
