### PR TITLE
Fix frustum culling w/ sprite transform scaling

### LINKED ISSUE #1760: Frustum culling problem
## Bevy version
https://github.com/bevyengine/bevy?branch=main#1d7196da4fff00bbc15fe75a04849de915f587d5

## Operating system & version
Windows 10

## What you did
tried to use frustum culling

I spawn a camera like this:
```Rust
let mut orth_camera = OrthographicCameraBundle::new_2d();
    orth_camera.transform.scale = Vec2::new(2.0, 2.0).extend(1.0);
commands
    .spawn()
    .insert_bundle(orth_camera)
    .insert(MainCamera);
```
I spawn the sprites like this: 
```Rust
local_commands.spawn().insert_bundle(HarvestableResouce {
    pickable: PickableBundle::default(),
    sprite: SpriteSheetBundle{
        texture_atlas:game_sprites.atlas_handle.clone(),
        sprite:TextureAtlasSprite { index: map[&texture_names[1].to_string()].index_in_atlas as u32,..Default::default()},
                                        transform:Transform::from_translation(
                                            area_cells[j].as_f32().mul(UNIT_TO_WORLD).extend(0.0)
                                                + Vec2::new(
                                                    thread_rng.gen_range(-15.0..15.0),
                                                    thread_rng.gen_range(-15.0..15.0),
                                                )
                                                .extend(0.0),
                                        ),
                                        ..Default::default()
                                    } 
                                });
```

## What you expected to happen
expected

## What actually happened
problem

## Additional information
not really..

### PR DESCRIPTION
**Pull request by fuzzbuck**
# Objective

- Frustum culling now takes in account the Transform scale of the sprite
- Also added a demo example (from https://github.com/rparrett/bevy-test/tree/culling)

## Solution

- Take sprite's Transform.scale into account when measuring whether camera_rect & sprite_rect intersect each other

### CODE REVIEW

**Comment by rparrett** [comment]
Just want to point out that my test case and the one from the author of that issue seem to be showcasing two separate issues.

In my test case, sprite scaling is unaccounted for.

In that issue, it seems that camera scale is unaccounted for.

**Comment by fuzzbuck** [comment]
> 
> 
> Just want to point out that my test case and the one from the author of that issue seem to be showcasing two separate issues.
> 
> In my test case, sprite scaling is unaccounted for.
> 
> In that issue, it seems that camera scale is unaccounted for.



> 
> 
> Just want to point out that my test case and the one from the author of that issue seem to be showcasing two separate issues.
> 
> In my test case, sprite scaling is unaccounted for.
> 
> In that issue, it seems that camera scale is unaccounted for.

That issue happens because sprites outside of camera bounds are not drawn, regardless of window size
I'm not sure whether this is expected behavior or not

**Comment by fuzzbuck** [comment]
Actually, #1760 is not even related to frustum culling, as when I disable the feature completely, it is still reproducible by scaling the camera Transform to any amount below 1.0

https://user-images.githubusercontent.com/54221024/131414148-ab37287e-7e04-4902-b8cb-c2f2ec02a3df.mp4

**Comment by fuzzbuck** [comment]
Ok, in summary:
 - This PR fixes frustum culling on sprites scaled by Transform
 - It adds an example that showcases frustum culling

There are plethora of other issues but I think that can be resolved in other PRs (or v0.6)

**Comment by rparrett** [comment]
Yeah it is possible that #1760 is actually describing some separate issue related to sprite sheets or something.

Just want to make sure #1760 doesn't get closed if this is merged, because I'm pretty sure my repro is not the bug originally described.

**Comment by alice-i-cecile** [comment]
#2861 looks like it will obsolete this; is that correct?

**Comment by superdump** [comment]
> #2861 looks like it will obsolete this; is that correct?

I suppose that practically anything against the 'old' renderer is obsoleted by the new renderer. That said, I didn't actually implement culling for 2D, just visibility propagation.

@cart and I were on the fence about whether culling would bring benefits over just culling on the GPU and opted to leave it for later as batched sprite rendering already has great performance on pipelined-rendering anyway and it may not be a clear win. That said, if someone wanted to add sprite rect vs view rect intersection testing for 2D on top of #2861 and check whether it improves performance, I'm sure no one would complain. :)

**Comment by alice-i-cecile** [comment]
Closing as no longer relevant <3

**Pull request closed without merging**
