### PR TITLE
[Merged by Bors] - Use `SpatialBundle`/`TransformBundle` in examples

### PR DESCRIPTION
**Pull request by devil-ira**
Does what it do

### CODE REVIEW

**Review by afonsolage — APPROVED** [review]

**Comment by mockersf** [comment]
I think I would prefer examples to avoid chaining insert commands on the same entity, as that's currently not a great pattern in Bevy

**Comment by devil-ira** [comment]
#2975 just got merged :)
Am I correct in thinking that will solve your issue with this @mockersf?

**Comment by mockersf** [comment]
yup, once this PR is update to only issue one command each time 👍

**Comment by devil-ira** [comment]
This has been rebased on top of the recent changes to spawning/inserting

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Comment by alice-i-cecile** [comment]
@devil-ira can you fix up these merge conflicts?

**Pull request closed without merging**
