### PR TITLE
[Merged by Bors] - single parent set for transform propagate

### PR DESCRIPTION
**Pull request by jakobhellermann**
# Objective

- have no system belonging to multiple sets

go from
before
to
after

## Solution

- `propagate_transforms in PropagateTransformSets in TransformSystem::TransformPropagate` instead of
```
propagate_transforms in PropagateTransformSets
propagate_transforms in TransformSystem::TransformPropagate
PropagateTransformsSet is free
```

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Sure I can see the value here :)

**Review by devil-ira — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Looks like it needs formatting.

**Comment by james7132** [comment]
bors retry

**Pull request closed without merging**
