### PR TITLE
Pass camera position to shader

### PR DESCRIPTION
**Pull request by andreasterrius**
Pass camera position to shader to calculate fragment to camera direction.
Will be useful for specular/fresnel calculation later on

### CODE REVIEW

**Comment by lachlansneff** [comment]
Can we pass more to the camera here? A particular usecase of mine requires the world matrix, the projection matrix, and an inverted view matrix.

**Comment by andreasterrius** [comment]
I could try, I'll look into it after I get off work today.

What's a world matrix btw ?

**Comment by lachlansneff** [comment]
Actually, I spoke too soon, those aren't appropriate to pass here.

**Comment by cart** [comment]
The "world matrix" would probably be useful in some cases and the world position can be extracted from it. That might be the more "general purpose" solution. We could also consider making this an "optional" binding that is separate from the ViewProj. I honestly don't know the best choice here. Maybe we should look at what other engines do for this.

**Comment by andreasterrius** [comment]
I'm closing this PR, I think this is better if this is done alongside shader implementations (such as #261 ), since we would know better what to pass to the shaders

**Pull request closed without merging**
