### PR TITLE
[Merged by Bors] - Flip UI image

### LINKED ISSUE #3225: Allow for flippable UI Images
## What problem does this solve or what need does it fill?

General UI functionality. In my case, some of the textures that appear in the world also need to be shown into the UI (in a Minecraft-esque tile picker that includes flipped tiles), using `ImageBundle`. I imagine others may run into similar issues.

## What solution would you like?

Allow `Sprite` components (which include `flip_x` and `flip_y` fields) to affect UI images created from `ImageBundle`. The `resize_mode` field will perhaps also be useful, if that functionality is not already covered for UI. I don't imagine the `size` field will be as relevant in UI though, but I may be wrong.

## What alternative(s) have you considered?

Allow sprites to be flipped with negative `Transform` scale values. Currently, they scale properly for positive values, but disappear for negative values. This is less intuitive for developers newer to gamedev, but will make particular scenarios easier to code, such as lerping to a flipped state from an un-flipped one through scaling. I don't think it should be the blessed way, though, unless they specifically need scaling and flipping to be closely related.

Thank you!

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective
Fixes  #3225, Allow for flippable UI Images

## Solution
Add flip_x and flip_y fields to UiImage, and swap the UV coordinates accordingly in ui_prepare_nodes.

## Changelog
* Changes UiImage to a struct with texture, flip_x, and flip_y fields.
* Adds flip_x and flip_y fields to ExtractedUiNode.
* Changes extract_uinodes to extract the flip_x and flip_y values from UiImage.
* Changes prepare_uinodes to swap the UV coordinates as required.
* Changes UiImage derefs to texture field accesses.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I'm on board; this is a clean implementation of a useful feature.

I'd probably prefer a singular `Flip` component, which is reused across sprites and UI images, but I won't block on that.

**Comment by ickshonpe** [comment]
> I'd probably prefer a singular `Flip` component, which is reused across sprites and UI images, but I won't block on that.

Yes, I'm trying to keep things as close to sprites as possible with the least breaking changes.  I chose `FlipImage` rather than `Flip` because a lot of people already find the UI confusing, so I wanted to be extra clear about what it's flipping. Most of the ambiguity is in the `Style` component though so maybe `Flip` is fine. Or it could be `FlipTexture`.

**Comment by mockersf** [comment]
I don't think it should be a separate component. What happens if I add the `FlipImage` component to a `PbrBundle`? Is the image file used for texture flipped?

I would prefer to have two fields `flip_x` and `flip_y` in an existing UI component, maybe `Style` or `UiImage`

**Comment by ickshonpe** [comment]
> I don't think it should be a separate component. What happens if I add the `FlipImage` component to a `PbrBundle`? Is the image file used for texture flipped?
> 
> I would prefer to have two fields `flip_x` and `flip_y` in an existing UI component, maybe `UiImage`

I agree that would be better, it's just that I was worried it'd break a lot of existing code that expects `UiImage` to be a newtype. 

`ImageMode` is only used as a marker component for the image widget at the moment, the flip_x/y fields could be added to it as an alternative? Or would it be better to just have the changes to ExtractedUiNode and ui_prepare_nodes in this PR, and put in a separate one for the interface?

**Comment by alice-i-cecile** [comment]
> I agree that would be better, it's just that I was worried it'd break a lot of existing code that expects UiImage to be a newtype.

Yep, no worries about breaking existing code here :) This sort of migration is very easy. Not immediately sure about your other question though.

**Review by alice-i-cecile — APPROVED** [review]

**Review by Weibye — APPROVED** [review]
Clean and straightforward!

**Pull request closed without merging**
