### PR TITLE
Add inverse model matrix to Mesh uniform buffer

### PR DESCRIPTION
**Pull request by pbaja**
# Objective

- Enable users to convert positions from world to object local space in shaders. This is often useful when f.eg. ray marching.
- Match `unity_WorldToObject` functionality from Unity

## Solution

- Add `model_inverse` field to Mesh and Mesh2d structs
- Compute and assign the variable to MeshUniform and Mesh2dUniform. This is free because we are already computing the inverse model matrix for the `inverse_transpose_model` field.
- Additional change was to rename the field from `transform` to `model` in the MeshUniform and Mesh2dUniform structs, to match structs in shaders and reduce confusion. I can revert it if this is unwanted.

### CODE REVIEW

**Comment by james7132** [comment]
I'd like to see some performance numbers here. `MeshUniform`'s size in memory is notorious for impacting end-to-end rendering performance.

**Comment by pbaja** [comment]
I have run many_cubes test with `cargo run --example many_cubes --release sphere`.
```
AdapterInfo { name: "NVIDIA GeForce RTX 3060 Laptop GPU", vendor: 4318, device: 9504, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "517.48", backend: Vulkan }
```

|Diagnostic| Before change | After Change |
|------------|-----------------|----------------|
|Frametime|23 - 26 ms|24 - 27 ms|
|Framerate|38 - 42 FPS|34 - 40 FPS|

Not great.

I did some googling, and found out that inversing a matrix even on the modern GPUs is expensive (But that would have to be confirmed by testing). Also, WGSL does not provide any matrix inverse methods.

**Comment by james7132** [comment]
It may have worth to move the transpose explicitly to the GPU. If it's "free" on the GPU and has a cost on the CPU, makes more sense to just provide the inverse and transpose it in the shader.

**Comment by james7132** [comment]
@pbaja do you mind trying the alternative I proposed above? If it shows that it's as performant, we can probably merge the change.

**Comment by atlv24** [comment]
Now that #12773 is merged, this can be closed. The model inverse transpose is computed on the GPU anyways due to bandwidth savings. Getting inverse model is just a different unpacking of it and should be pretty cheap.

**Comment by superdump** [comment]
I wouldn't say that it can be closed only because of #12773 because that is only addresses platforms with compute. That said, the inverse transpose is available and can be transposed back and reconstructed into the full inverse model matrix on all platforms, and various performance optimisations have and continue to be done to make performance as good as it reasonably can be.

**Pull request closed without merging**
