### PR TITLE
Fix text2d view-visibility

### LINKED ISSUE #9676: Text2d is broken
## Bevy version

main, since #9236

## What you did

`cargo run --example text2d`

## What went wrong

No text shows up.

## Additional information

This is a known issue, but not yet documented here on GitHub. I'm posting here so there's a place for discussion and to point to in other issues/PRs and so that it's not forgotten.

From discord:

> the queue_sprites is checking against visible_entities in order to determine whether it renders each sprite and since we are using a sparseset for sprites the text2d individual glyphs get assigned new entity ids that don't match the original Text2dBundle so they are considered not visible. Ideally we have a better way of storing text glyphs for both ui and 2d (and eventually 3d) so we don't have to spawn a bunch of empty entities. 

> (this doesn't currently affect UI text as it is clipped later rather than using visible_entities)

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

Fixes #9676
Possible alternative to #9708

`Text2dBundles` are not currently drawn because the render-world-only entities for glyphs that are created in `extract_text2d_sprite` are not tracked by the per-view `VisibleEntities`.

## Solution

Add an `Option<Entity>` to `ExtractedSprite` that keeps track of the original entity that caused a "glyph entity" to be created.

Use that in `queue_sprites` if it exists when checking view visibility.

## Benchmarks

Quick benchmarks. Average FPS over 1500 frames.

| bench | before fps | after fps | diff |
|-|-|-|-|
|many_sprites|884.93|879.00|🟡 -0.7%|
|bevymark -- --benchmark --waves 100 --per-wave 1000 --mode sprite|75.99|75.93|🟡 -0.1%|
|bevymark -- --benchmark --waves 50 --per-wave 1000 --mode mesh2d|32.85|32.58|🟡 -0.8%|

### CODE REVIEW

**Review by superdump — APPROVED** [review]
Assuming this works, I prefer this PR to the other one.

**Comment by robtfm** [comment]
Don’t want to muddy the waters but since the new sprites are only created for visible entities could we just have a force_visible bool that gets set to true on the new ones? Not sure if there’s other value to tracking the original entity

**Comment by rparrett** [comment]
> Don’t want to muddy the waters but since the new sprites are only created for visible entities could we just have a force_visible bool that gets set to true on the new ones? Not sure if there’s other value to tracking the original entity

My understanding is that entities that are definitely not visible in any view are not extracted, but the visibility check in `queue_sprites` is per-view / based on `RenderLayers`.

**Comment by rparrett** [comment]
I re-did the benchmarks on power / without a sneaky bevy ant simulator running in the background / actually averaging all 1500 framerate samples (oops).

**Review by robtfm — APPROVED** [review]

**Pull request merged**
