### PR TITLE
bevy_ecs: Add doc example for par_iter_mut (#11311)

### LINKED ISSUE #11311: Missing docs in `Query::par_iter` and `Query::par_iter_mut`
## How can Bevy's documentation be improved?

http://dev-docs.bevyengine.org/bevy/ecs/system/struct.Query.html#method.par_iter

I'd like an example for usage of `par_iter` and `par_iter_mut` in the docs.

Several times I have reached for these APIs I keep trying to use it like so:

```rust
for transform in transforms_query.par_iter_mut()  {
    ...
});
```

but you have to use it like:

```rust
transforms_query.par_iter_mut().for_each(|mut t| {
    ...
});
```

### PR DESCRIPTION
**Pull request by lkolbly**
# Objective

Fixes #11311 

## Solution

Adds an example to the documentation for `par_iter_mut`. I didn't add any examples to `par_iter`, because I couldn't think of a good example and I figure users can infer that `par_iter` and `par_iter_mut` are similar.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Really solid, thanks :)

**Review by hymm — APPROVED** [review]
Would be nice to have this on `Query::par_iter_mut`, but that could be a follow up pr.

**Comment by alice-i-cecile** [comment]
Waiting until Monday: add the docs there too if you get a chance. Otherwise I'll make a follow-up issue.

**Comment by lkolbly** [comment]
> Would be nice to have this on `Query::par_iter_mut`, but that could be a follow up pr.

Is that a different `Query` than the one in [crates/bevy_ecs/src/system/query.rs](https://github.com/bevyengine/bevy/pull/11499/files#diff-a99b568e881ec4857371e2adb49edbacdb422f1edef522f00e2335805c02c244R817)?

**Comment by hymm** [comment]
> Is that a different Query than the one in [crates/bevy_ecs/src/system/query.rs](https://github.com/bevyengine/bevy/pull/11499/files#diff-a99b568e881ec4857371e2adb49edbacdb422f1edef522f00e2335805c02c244R817)?

Oops, not sure what I was thinking with that comment. Might have been to add them to `par_iter` instead and was thinking about something else at the same time.

**Comment by lkolbly** [comment]
Fair 'nuff. I can't think of any good examples for a succinct `par_iter` use case, they all involve atomics or locks or channels or some sort of synchronization. But, I added a note:
```
    /// Note that you must use the `for_each` method to iterate over the
    /// results, see [`par_iter_mut`] for an example.
```
which hopefully should point users in the right direction?

**Pull request merged**
