### PR TITLE
Label conflicting PRs

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- PRs can get conflicts due to other PRs merged
- It's painful to manually check for conflicts on each PR

## Solution

- Add an action to label conflicting PR on every push

@cart if you agree with this action, you would need to add the label `S-Conflicts` and add a GitHub token for the secret. I reviewed the action, I won't guarantee it's bug free but it doesn't do anything nefarious with the token. I've set it up with the version I reviewed

### CODE REVIEW

**Review by DJMcNab — APPROVED** [review]
The version being used is:

https://github.com/mschilde/auto-label-merge-conflicts/tree/8c6faa8a252e35ba5e15703b3d747bf726cdb95c

This gets the token here:
https://github.com/mschilde/auto-label-merge-conflicts/blob/8c6faa8a252e35ba5e15703b3d747bf726cdb95c/lib/main.ts#L16
and uses it only for reading in `queries.ts`, and then only uses it below:
https://github.com/mschilde/auto-label-merge-conflicts/blob/8c6faa8a252e35ba5e15703b3d747bf726cdb95c/lib/queries.ts#L120

which looks correct to me

**Comment by cart** [comment]
A bit hesitant to give a secret to a non-github-developed action without a ton of eyes on it. Is "enumerating all prs with conflicts" worth the risk? Generally my review approach wouldn't have a need for that information. I look at prs individually based on their activity and my own priorities. And when focused on a specific pr I can see that it has conflicts by scrolling down.

**Comment by DJMcNab** [comment]
My reasoning for wanting this is for my own bookkeeping. It's much easier to look at a list of prs labelled with whether they are updated, than go to each one, scroll down, wait for it to update, move to the next.

I want to keep all my PRs 'ship shape' ~~because I'm still optimistic they might land~~; it seems disrespectful of your time to 'make' you rebase them. Shrinking the time cost of that would be appreciated.

**Comment by mockersf** [comment]
don't want to use a token for that

**Pull request closed without merging**
