### PR TITLE
`plugin_group!` macro (adopted)

### LINKED ISSUE #7332: Documented list of `DefaultPlugins` is out-of-date.
## How can Bevy's documentation be improved?

The list of default plugins at [`DefaultPlugins` docs](https://docs.rs/bevy/0.9.1/bevy/struct.DefaultPlugins.html) appears to be out of date. In particular, it does not list:

* `ImagePlugin` with feature `bevy_render`
* `CorePipelinePlugin` with feature `bevy_core_pipeline`
* `AnimationPlugin` with feature `bevy_animation`

as can be seen from the [source code](https://docs.rs/bevy_internal/0.9.1/src/bevy_internal/default_plugins.rs.html#25) (I might have missed one or two).

### PR DESCRIPTION
**Pull request by BD103**
# Objective

- Adopted from #11460.
- Closes #7332.
- The documentation for `DefaultPlugins` and `MinimalPlugins` frequently goes out of date because it is not .

## Solution

- Create a macro, `plugin_group!`, to automatically create `PluginGroup`s and document them.

## Testing

- Run `cargo-expand` on the generated code for `DefaultPlugins` and `MinimalPlugins`.
- Try creating a custom plugin group with the macro.

---

## Showcase

- You can now define custom `PluginGroup`s using the `plugin_group!` macro.

```rust
plugin_group! {
    /// My really cool plugic group!
    pub struct MyPluginGroup {
        physics:::PhysicsPlugin,
        rendering:::RenderingPlugin,
        ui:::UiPlugin,
    }
}
```

<details>
  <summary>Expanded output</summary>

```rust
/// My really cool plugic group!
///
/// - [`PhysicsPlugin`](physics::PhysicsPlugin)
/// - [`RenderingPlugin`](rendering::RenderingPlugin)
/// - [`UiPlugin`](ui::UiPlugin)
pub struct MyPluginGroup;
impl ::bevy_app::PluginGroup for MyPluginGroup {
    fn build(self) -> ::bevy_app::PluginGroupBuilder {
        let mut group = ::bevy_app::PluginGroupBuilder::start::<Self>();
        {
            const _: () = {
                const fn check_default<T: Default>() {}
                check_default::<physics::PhysicsPlugin>();
            };
            group = group.add(<physics::PhysicsPlugin>::default());
        }
        {
            const _: () = {
                const fn check_default<T: Default>() {}
                check_default::<rendering::RenderingPlugin>();
            };
            group = group.add(<rendering::RenderingPlugin>::default());
        }
        {
            const _: () = {
                const fn check_default<T: Default>() {}
                check_default::<ui::UiPlugin>();
            };
            group = group.add(<ui::UiPlugin>::default());
        }
        group
    }
}
```

</details>

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
CI failures are real :)

**Comment by MrGVSV** [comment]
If you have time, could you also include a simplified sample of the expanded macro in Solution? Or maybe a sample of the auto-generated docs in Showcase?

**Comment by stevehello166** [comment]
The CI tests fail when the macro is trying to include the 'CiTestingPlugin'(the irony). Not sure what is causing it though, because the error says that it doesn't implement `std::default::Default` but none of the other plugins need it. You could include the CiTestingPlugin using the normal way, but that would kind of defeat the purpose of including the feature. Or you could implement std::default::Default for the CiTestingPlugin. Which ever floats your boat/fixes the issue.

**Comment by BD103** [comment]
> The CI tests fail when the macro is trying to include the 'CiTestingPlugin'(the irony). Not sure what is causing it though, because the error says that it doesn't implement `std::default::Default` but none of the other plugins need it. You could include the CiTestingPlugin using the normal way, but that would kind of defeat the purpose of including the feature. Or you could implement std::default::Default for the CiTestingPlugin. Which ever floats your boat/fixes the issue.

Part of this change actually requires plugins added in `plugin_group!` to implement `Default`. Fix pushed, let me update the docs.

**Comment by BD103** [comment]
> If you have time, could you also include a simplified sample of the expanded macro in Solution? Or maybe a sample of the auto-generated docs in Showcase?

Done! Macro outputs aren't the prettiest, but I tried to improve `plugin_group!` enough that it is at least passable.

**Review by stevehello166 — APPROVED** [review]

**Review by alice-i-cecile — COMMENTED** [review]
One last small thing I though of: can you link this from the `PluginGroup` trait docs? Once that's done (or if you don't want to bother) I'll merge this in.

**Pull request merged**
