### PR TITLE
Feature gate use_shortnames

### PR DESCRIPTION
**Pull request by BenjaminBrienen**
# Objective

- use_shortnames only does anything if bevy_reflect feature is enabled, so it makes sense to put it behind a feature.

## Solution

- #[cfg] on the if block and the field declaration

## Testing

- CI

## Migration Guide

- If you've disabled bevy_reflect feature of bevy_ecs, remove references to that field.

## Context

See: #15340

### CODE REVIEW

**Comment by BenjaminBrienen** [comment]
Might want to merge https://github.com/bevyengine/bevy/pull/15340 first, as this is branched from there

**Review by alice-i-cecile — APPROVED** [review]

**Comment by hymm** [comment]
Send weird to me that short names in the schedule would be feature gated to bevy reflect. As it doesn't have anything to do with that feature. Feels more like an argument against #15340

**Comment by BenjaminBrienen** [comment]
> Send weird to me that short names in the schedule would be feature gated to bevy reflect. As it doesn't have anything to do with that feature. Feels more like an argument against #15340

#15340 doesn't change any functionality. It just moves the existing code from bevy_utils into bevy_reflect.

**Comment by BenjaminBrienen** [comment]
I'm just gonna merge this into the other branch, actually.

**Comment by hymm** [comment]
The fact that you had to feature gate use_short_name for schedules says to me that there was a change in functionality.

**Comment by BenjaminBrienen** [comment]
> The fact that you had to feature gate use_short_name for schedules says to me that there was a change in functionality.

I didn't have to. That was an enhancement on top of the simple refactor.

**Comment by hymm** [comment]
So the use_shortnames flag still worked without the `bevy_reflect` feature enabled? I find that hard to believe.

**Comment by BenjaminBrienen** [comment]
> So the use_shortnames flag still worked without the `bevy_reflect` feature enabled? I find that hard to believe.

Sorry, you're right. I was drawing a distinction between "have to feature gate use_shortname" and "have to feature gate the place where its used". I guess the PR can be reverted if the maintainers decide this is unwanted.

**Pull request closed without merging**
