### PR TITLE
Possible fix for #1056

### PR DESCRIPTION
**Pull request by rparrett**
I don't want to pretend to be able to explain what's going on here.

This is definitely a hackjob, but it might be the case that it's a hackjob that's well aligned with another recent hack (#1208) around the same code. It's entirely possible that I'm just accidentally fixing this by oversizing the staging buffer or something.

I'm tossing this here so that cart or someone else with experience with this code might determine whether or not it's doing anything useful. I'm happy to just keep my fork patched locally so that I can write game code again for a while if it's no good.

This information is also buried in #1056 but I'll summarize here:

This fixes a panic that occurs in both of these cases:

https://github.com/rparrett/taipo/tree/spritesheet-panic-two (game will play itself until it panics when the crabs start dying)
https://github.com/rparrett/bevy-test/tree/render-panic (just displays a chunk of text one letter at a time)

This seems to be related to font atlases and tweaking font sizes affects time-to-panic. I'm on macOS with a high DPI display. So YMMV.

### CODE REVIEW

**Comment by rparrett** [comment]
Sadly, this PR doesn't seem to completely fix the problem. However I am only seeing the panic very intermittently now and can't reliably reproduce it yet.

**Comment by rmsc** [comment]
> Sadly, this PR doesn't seem to completely fix the problem. However I am only seeing the panic very intermittently now and can't reliably reproduce it yet.

I was able to reliably reproduce this using your `render-panic` example, and got curious enough to poke around. What I found is interesting. Just before a crash happens, for example:

* `prepare_uniform_buffers()` reports a required size of 17656
* `write_uniform_buffers()` panics while trying to write to 17656, while the slice length is only 17632

To me this tells me that the buffer isn't being properly resized. Will investigate further.

**Comment by rmsc** [comment]
I'm definitely nacking this.

The problem is that `set_required_staging_buffer_size_to_max()` is destroying the computed `required_staging_buffer_size`, and so preventing `resize_staging_buffer()` from resizing the buffer.

**Comment by rparrett** [comment]
Closing in favor of #1509

**Pull request closed without merging**
