### PR TITLE
[Merged by Bors] - fix scene_viewer example on wasm

### PR DESCRIPTION
**Pull request by jakobhellermann**
The scene viewer example doesn't run on wasm because it sets the asset folder to `std::env::var("CARGO_MANIFEST_DIR").unwrap()`, which isn't supported on the web.

Solution: set the asset folder to `"."` instead.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
I've had a similar issue with this `unwrap` could you instead have it `unwrap_or_else(|| ".".to_string())`?

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
Much cleaner. Good suggestion :)

**Comment by alice-i-cecile** [comment]
bors retry

**Pull request closed without merging**
