### PR TITLE
Mesh insert indices

### LINKED ISSUE #11740: Turn `Mesh::set_indices` into `Mesh::insert_indices`
## What problem does this solve or what need does it fill?

We have [`Mesh::insert_attribute`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.insert_attribute) and [`Mesh::remove_attribute`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.remove_attribute).

But for indices we have `Mesh::remove_indices` (added in #11733) and [`Mesh::set_indices`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.set_indices) which accepts `Option`. It's inconsistent with the attributes API.

## What solution would you like?

I would suggest to make [`Mesh::set_indices`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.set_indices) similar to [`Mesh::insert_attribute`](https://docs.rs/bevy/latest/bevy/prelude/struct.Mesh.html#method.insert_attribute), i.e. pass the value instead of `Option`.

Ping @solis-lumine-vorago since he may be interested in it.

### PR DESCRIPTION
**Pull request by solis-lumine-vorago**
# Objective

- Fixes #11740 

## Solution

- Turned `Mesh::set_indices` into `Mesh::insert_indices` and added related methods for completeness.

---

## Changelog

- Replaced `Mesh::set_indices(indices: Option<Indices>)` with `Mesh::insert_indices(indices: Indices)`
- Replaced `Mesh::with_indices(indices: Option<Indices>)` with `Mesh::with_inserted_indices(indices: Indices)` and `Mesh::with_removed_indices()` mirroring the API for inserting / removing attributes.
- Updated the examples and internal uses of the APIs described above.

## Migration Guide

- Use  `Mesh::insert_indices` or `Mesh::with_inserted_indices` instead of  `Mesh::set_indices` / `Mesh::with_indices`.
- If you have passed `None` to `Mesh::set_indices` or `Mesh::with_indices` you should use `Mesh::remove_indices` or `Mesh::with_removed_indices` instead.

### CODE REVIEW

**Comment by solis-lumine-vorago** [comment]
I'm not sure about the naming of `Mesh::with_removed_indices`. Would `Mesh::without_indices` be better?

**Comment by IceSentry** [comment]
I personally prefer `without_indices`, but also, I'd prefer having `with_indices` and `with_attribute`. The `_inserted_` part seems redundant to me.

But that's just personal preference, the current state of the PR LGTM

**Review by IceSentry — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Looks like this needs a bit of clean up: CI errors look real.

**Comment by mockersf** [comment]
new users of the renamed apis have been added to main, they need to be updated too

**Pull request merged**
