### PR TITLE
Fix wasm builds with file_watcher enabled

### PR DESCRIPTION
**Pull request by Leinnan**
# Objective

- Currently, in 0.12 there is an issue that it is not possible to build bevy for Wasm with feature "file_watcher" enabled. It still would not compile, but now with proper explanation.
- Fixes https://github.com/bevyengine/bevy/issues/10507

## Solution

- Remove `notify-debouncer-full` dependency on WASM platform entirely.
- Compile with "file_watcher" feature now on platform `wasm32` gives meaningful compile error. 

---

### Fixed

- Compile with "file_watcher" feature now on platform `wasm32` gives meaningful compile error.

### CODE REVIEW

**Comment by Leinnan** [comment]
Repro steps:

**Comment by nicopap** [comment]
Add "Fixes #10507" to the PR description please.

Now the difficult question. Is this what we want? What's the problem with failing to compile invalid code?

The proposed solution of having hot-reloading silently become broken on WASM targets seems far from ideal. When a user compiles their game with the `file_watcher` feature, they expect hot-reloading to work. Nothing else. With this change, it sure compiles, but it won't work, breaking user expectation.

Here is a suggestion:

```rust
#[cfg(all(feature = "file_watcher", target_arch = "wasm32"))]
compile_error!(
    "The \"file_watcher\" feature for hot reloading does not work \
    on WASM.\nDisable \"file_watcher\" (or \"embedded_watcher\") \
    when compiling to WASM"
);
```

Question: does this print the error message when trying to compile with the setup you describe? If so I think it might be preferable.

-----

What's the issue with the failing compilation? That it is unclear how to fix it? If so, the `compile_error!` trick should fix the problem.

**Comment by Leinnan** [comment]
@nicopap I did not about this macro, it's great! So I did remove most of the changes and added the macro. One thing that I left is I still disabled notify-debouncer-full dependency, so it is not compiled on wasm. I did it because without that change, it does not even get to the macro compilation and error is not obvious:
```
   Compiling notify-debouncer-full v0.3.1
error[E0432]: unresolved import `file_id::get_file_id`
   --> C:\Users\rybop\.cargo\registry\src\index.crates.io-6f17d22bba15001f\notify-debouncer-full-0.3.1\src\cache.rs:6:15
    |
6   | use file_id::{get_file_id, FileId};
    |               ^^^^^^^^^^^ no `get_file_id` in the root
    |
note: found an item that was configured out
   --> C:\Users\rybop\.cargo\registry\src\index.crates.io-6f17d22bba15001f\file-id-0.2.1\src\lib.rs:111:8
    |
111 | pub fn get_file_id(path: impl AsRef<Path>) -> io::Result<FileId> {
    |        ^^^^^^^^^^^
    = note: the item is gated behind the `unix` feature
note: found an item that was configured out
   --> C:\Users\rybop\.cargo\registry\src\index.crates.io-6f17d22bba15001f\file-id-0.2.1\src\lib.rs:121:8
    |
121 | pub fn get_file_id(path: impl AsRef<Path>) -> io::Result<FileId> {
    |        ^^^^^^^^^^^
    = note: the item is gated behind the `windows` feature

For more information about this error, try `rustc --explain E0432`.
error: could not compile `notify-debouncer-full` (lib) due to previous error
```

And now on my branch it fails nicely:
```
   Compiling bevy_asset v0.12.0 (C:\PROJECTS\bevy\crates\bevy_asset)
error: The "file_watcher" feature for hot reloading does not work on WASM.
       Disable "file_watcher" when compiling to WASM
 --> C:\PROJECTS\bevy\crates\bevy_asset\src\io\mod.rs:2:1
  |
2 | / compile_error!(
3 | |     "The \"file_watcher\" feature for hot reloading does not work \
4 | |     on WASM.\nDisable \"file_watcher\" \
5 | |     when compiling to WASM"
6 | | );
  | |_^

error: could not compile `bevy_asset` (lib) due to previous error
```

You guessed the point of the change, right- I just want to make clear what build is failing if it has to fail.

**Review by nicopap — APPROVED** [review]

**Comment by nicopap** [comment]
Add "Fixes #10507" to the PR description please. So that the issue gets automatically closed.

You can click on the … on the top left of your PR description, and there should be an "Edit" option.

**Comment by nicopap** [comment]
This seems completely non-breaking, as we still have the same behavior, just a different compilation error message. So I think it's a candidate for 0.12.1

**Comment by Leinnan** [comment]
> Add "Fixes #10507" to the PR description please. So that the issue gets automatically closed.
> 
> You can click on the … on the top left of your PR description, and there should be an "Edit" option.

Description updated

**Review by cart — APPROVED** [review]

**Pull request merged**
