### PR TITLE
Simple tree-structure print of Scheduler

### PR DESCRIPTION
**Pull request by Telzhaak**
### Implemented a way to print out the current Scheduler

Extends the [`Stage`](https://docs.rs/bevy/0.4.0/bevy/ecs/struct.State.html)-Trait by a `system_names()` function, that returns a `Vec<String>`, in a very very basic way.

EDIT: Systems are printed in relation to the `Stage`/`Scheduler` they belong to, **BUT NOT** in the order they are executed in! No checking for serial or parallel execution happens

 The current implementation **does some formatting**, which may not be ideal for every use-case. So maybe i should add a 
`(..., recursion_depth: usize)` parameter and `-> (Vec<recur_depth: usize, stage_type: String, stage_name: String>` return, which would allow non-formatted ouput, such that formatting can be done depending on the usecase after the fact. It could then _maybe_ also be used for displaying in an editor with hot-linking to source-code, which I think is impossible with this implementation?

To use this, call for example:
```rust
println!(format!("{}", appbuilder.app.print_stage_schedule());
```
on the `AppBuilder` after adding systems, but before `app.run()`.

--- 

Output example: https://gist.github.com/Telzhaak/2a19de3337e25ccde729b1f5437c29da

### CODE REVIEW

**Review by alice-i-cecile — COMMENTED** [review]
Good, this is a nice little debugging tool and a good basis to start building on for an eventual schedule visualizer :)

This is relevant to #1144. It should be extended to work with system labels once that lands.

Does this make more sense to implement using the `Display` trait?

**Comment by Telzhaak** [comment]
It is possible to extend this using the `Display` trait, such that not only the names, but also current state of each System/SystemStage/Scheduler/... gets exposed recursively. 

Either by making the `Display`-implementation itself recursive, or writing a recursive function (like currently done), that uses Display to format each instance. Taking for example:
https://github.com/bevyengine/bevy/blob/b6485ccf29e23f24c972d2f9a57c0c2da1f1a1df/crates/bevy_ecs/src/schedule/stage.rs#L27-L35
1. Display could itself loop over all `systems`, and integrate their respective Display-outputs to its own output. 
2. Or the `systems` field is omitted, and a seperate function uses both the "slimmed down" Display of `SystemStage` and loops over all `systems`, handling the high-level formatting, while each Display-implementation only cares about its own low-level formatting


Looking at the massive ecs changes in 0.5, I would, however, probably push this back until those changes are done.

**Comment by Telzhaak** [comment]
ADDENDUM:

After thinking about the current implementation, which is a static printout of all registered systems and stages outside the app-loop in a wall-of-text, there is no way this approach can be used in a dynamic context (not necessarily an Editor, but also in console or ingame UI).

For that, a completely different approach is needed, requiring a complete rewrite. UI-integration necessitates that each "object" (in a loss of better word for the amalgamation of system+scheduler+systemStage+ everything else of the scheduler) is returned separately for use in UI-elements, lest the wall-of-text needs parsing again to deconstruct the structure just constructed (not desireable).
- Some objects should also return their current value (e.g. ShouldRun, is it Parallel/SerialExecture?, ...) allowing to highlight currently active systems (when in debug-mode and paused execution) and their ordering 
- Others only a as rough outline or implicitely (there can be 100+ of the same system running in parallel, each working on an entity, thus only the name, query-compositions and resource-names used should be returned, in a static manner, not the components' current values, which is a whole different subject)

Because of this, i would not use the recursive 1) `Display`-implementation (previous two comments), but the second approach. Since I cannot predict the UI-development that is set to happen for 0.6, and I am not keen on doing it twice, I definitely am going to push this back until UI-development starts. This way, it also adds a relevant, often-used feature to test UI-approaches and on. 

The current implementation is, however, a useful debugging tool, and simple enough to easily remove later on. So I would still merge it for the time being.

**Comment by cart** [comment]
This does look useful!

General thoughts:

* I think the formatting here is too opinionated to be a debug or display impl. "embedding it" in other text wouldn't look very good. I can also see it eventually taking in configuration to control the outputs. For now I think it makes sense to leave it as a separate function.
* I'm not a huge fan of adding `system_names` to the stage api at this point. We might eventually build an abstraction to enumerate systems per-stage (maybe for the editor), but I'd prefer to table that conversation until later when the need is more pressing and we have more requirements for the api. For now I think it makes more sense to downcast stages in the "schedule print" function and handle each type manually. This also gives us the freedom to print each stage type differently / with more information.

**Comment by Telzhaak** [comment]
Sounds reasonable,

I'm closing this PR for now, and re-do this once UI has progressed a little in 0.6 and the basic API requirements become somewhat clear

**Pull request closed without merging**
