### PR TITLE
Don't Panic

### PR DESCRIPTION
**Pull request by CleanCut**
Same as #649 for `despawn_recursive` too.

### CODE REVIEW

**Comment by CleanCut** [comment]
Weird, I wonder why the first two commits show up again even though they've already been merged into master in #649? Maybe it's because I re-used the same branch?

**Comment by CleanCut** [comment]
Hmm. After the changelog the diff part from the first two commits disappeared. At least that's sane.

**Comment by cart** [comment]
yeah i think its because the squash resulted in a new commit, which means you're adding "new" commits to the history.

**Comment by cart** [comment]
In this case its harmless because I'm going to squash this pr too :)

**Comment by CleanCut** [comment]
Ah, squash-n-merges, that makes sense.

**Pull request merged**
