### PR TITLE
add `ExtractEventPlugin` for extracting events to the render world

### PR DESCRIPTION
**Pull request by atornity**
# Objective

Sometimes I'd like to render/compute something in response to something happening in the main world. Using events seemed like a good way of doing this. 

Currently (as far as I know) you have to use a resource or component to do this sort of thing.

## Solution

I added an `ExtractEvent` trait along with a plugin and system which is all almost identical to the `ExtractResource` counterparts except it "clones" the individual events rather than the whole resource. 

Just like `ExtractResource` it can be automatically derived for any event type that implements `Clone` by using the macro.

---

## Changelog

- added `ExtractEvent` trait, `ExtractEventPlugin` and `extract_event` system.
- added `ExtractEvent` derive macro.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
What are the tradeoffs of using this vs extracting the whole resource? That should be made clear in the docs, and `ExtractResource` should link to this.

**Comment by atornity** [comment]
> What are the tradeoffs of using this vs extracting the whole resource? That should be made clear in the docs, and `ExtractResource` should link to this.

`ExtractResource` is not currently implemented for `Events` but I guess it maybe could be? That would require cloning the whole thing every time there's a new event which *feels* wrong to me. Not sure if `Events` are even clone-able though. idk, I mostly did it this way because it was convenient and I couldn't think of anything better 🤷‍♀️

I'll take a look at the docs 👍

**Comment by JMS55** [comment]
What e.g. Materials do is the extraction function checks for new events, and then extracts changed materials. I feel like that's generally a better pattern.

**Comment by atornity** [comment]
> What e.g. Materials do is the extraction function checks for new events, and then extracts changed materials. I feel like that's generally a better pattern.

ooo yeah, I think I agree. closing

**Pull request closed without merging**
