### PR TITLE
Fix CAS toggle broken by retained render world

### LINKED ISSUE #16531: Toggling sharpening on then off results in a massively oversharpened image despite sharpening being disabled.
## Bevy version

2a66bf0909992b280420442ecda42a38d37de326 with https://github.com/bevyengine/bevy/pull/16530 so sharpening actually works

## What you did

Run the `anti_aliasing` example, then toggle sharpening on and off. Wait a bit and it starts glitching out.

## What went wrong

Image ends up being oversharpened to the point of looking broken, with the oversharpening artifacts changing over time as well despite sharpening being disabled.

Image

### PR DESCRIPTION
**Pull request by kristoff3r**
# Objective

Fixes #16531

I also added change detection when creating the pipeline, which technically isn't needed but it felt weird leaving it as is.

## Solution

Remove the pipeline if CAS is disabled. The uniform was already being removed, which caused flickering / weirdness.

## Testing

Tested the anti_alias example by toggling CAS a bunch on/off.

### CODE REVIEW

**Review by Elabajaba — APPROVED** [review]
Tested it and it works.

**Comment by mockersf** [comment]
Would that work correctly if the `CasUniform` component is removed and re-added in the same frame?

**Comment by kristoff3r** [comment]
> Would that work correctly if the `CasUniform` component is removed and re-added in the same frame?

No, that would break. But that can't happen with `ExtractComponentPlugin` afaik, so you'd have to add a custom extraction or render system just to break it.

I think it just works if we run removals first, because in the "added then removed" case the query would be empty.

**Review by alice-i-cecile — APPROVED** [review]
Oh hey, this is a situation where @cart's "required components work on removal" would have solved that bug. Anyways, this is fine, merging.

**Pull request merged**
