### PR TITLE
Implement Debug for SpriteBundle and SpriteSheetBundle

### PR DESCRIPTION
**Pull request by NixyJuppie**
# Objective
Implement Debug trait for SpriteBundle and SpriteSheetBundle
It's helpful and other basic bundles like TransformBundle and VisibilityBundle already implement this trait

### CODE REVIEW

**Review by Selene-Amanita — APPROVED** [review]

**Comment by afonsolage** [comment]
What are the benefits or use case of implementing `Debug` for `Bundle`s? I ask this even for those who already are implement `Debug`, like `TransformBundle` and `VisibilityBundle`

**Comment by NixyJuppie** [comment]
> What are the benefits or use case of implementing `Debug` for `Bundle`s? I ask this even for those who already implement `Debug`, like `TransformBundle` and `VisibilityBundle`

Helpful when you include one of these bundles in your own which have Debug derive.
I use it for debug logging all components before spawning entity from bundle

**Comment by alice-i-cecile** [comment]
@mockersf, opinions?

**Review by afonsolage — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
For the record, I don't feel strongly about whether or not this should be included.

**Pull request merged**
