### PR TITLE
Mirko/error docs

### PR DESCRIPTION
**Pull request by mirkoRainer**
# Objective

Slight improvement to structure of error docs so the template can be followed moving forward.

## Solution

Create a list of errors with links and summary for quick reference.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
As this grows in size, it may be nice to have a CI action for this that works like our "check all examples have links" action.

**Comment by mockersf** [comment]
I'm not sure having another list to keep in sync manually is a good idea.

The list of errors will be automatically built on Bevy website once they are released.

**Comment by alice-i-cecile** [comment]
> I'm not sure having another list to keep in sync manually is a good idea.

Hmm, this is fair. On reflection, I think I'm opposed to merging this without CI, and probably prefer the automatic list approach.

**Comment by mirkoRainer** [comment]
Moved into Draft state as I work on automated Table of Contents.

Where does this list get generated for the website? It may be a good point of reference.

**Comment by mockersf** [comment]
it was done in https://github.com/bevyengine/bevy-website/pull/216 on the website.

I don't think it's a good idea to do something similar on this repo, as it would mean an action adding commits to a PR, which usually leads to conflict for the person opening the PR

**Pull request closed without merging**
