### PR TITLE
[Merged by Bors] - ECS benchmarks organization

### PR DESCRIPTION
**Pull request by ShadowCurse**
## Objective

Fixes: #5110

## Solution

- Moved benches into separate modules according to the part of ECS they are testing.
- Made so all ECS benches are included in one `benches.rs` so they don’t need to be added separately in `Cargo.toml`.
- Renamed a bunch of files to have more coherent names.
- Merged `schedule.rs` and `system_schedule.rs` into one file.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I got too frustrated trying to do this 😅 Thanks a ton!

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Bikeshedding for you.

1. The `stages` folder should be renamed to `scheduling`, and `schedule.rs` belongs in there
2. `world_get.rs` belongs beside `get_component.rs`.
3. `iteratations` -> `iteration`
4. The `world` folder doesn't make a lot of sense to me, but I'm not sure where else to put `commands.rs`.

**Comment by ShadowCurse** [comment]
Made some more changes according to @[alice-i-cecile](https://github.com/alice-i-cecile) suggestions:
- Merged `systems` and `stages` into `scheduling`. This means `heavy_complute.rs` is also there now and I am not sure if it should be like that. Maybe it should be just a separate module. 
- Moved benches from `get_component` and `get_component_system` into `world_get`
- Renamed `iteratations` -> `iteration`

**Comment by alice-i-cecile** [comment]
> This means heavy_complute.rs is also there now and I am not sure if it should be like that. Maybe it should be just a separate module.

Agreed. I'd say stick it in `iteration` for now, as it's effectively a counterpoint to those tests.

**Review by alice-i-cecile — APPROVED** [review]

**Review by PROMETHIA-27 — APPROVED** [review]

**Pull request closed without merging**
