### PR TITLE
add `monitor_selection` to window

### PR DESCRIPTION
**Pull request by jakobhellermann**
# Objective

make
```rust
    commands.spawn(Window {
        monitor_selection: MonitorSelection::Index(1),
        mode: WindowMode::BorderlessFullscreen,
        ..default()
    });
```
work

## Solution

- add `monitor_selection` field to `Window`
- respect that solution for non-`Windowed` modes

## Open questions
- should `WindowPosition::Centered(MonitorSelection)` change? we could
  1. remove the `MonitorSelection` and always use the `MonitorSelection` from the window itself
  2. keep `MonitorSelection` so that you can spawn on `Primary`, then later move to `Centered(MonitorSelection::At(1))`.
- should we try to make changing the selection work after the window is spawned by moving it to another monitor? I don't know how to do this with winit.

## Changelog

- add `monitor_selection` to `Window`. Windows can now specify which monitor they want to be spawned on.

## Migration Guide

- nnothing if we keep `WindowPosition::Centered(MonitorSelection)`

### CODE REVIEW

**Review by paul-hansen — COMMENTED** [review]
I think I would prefer putting MonitorSelection on the WindowMode variants that it applies to instead of having it be top level. 

E.g.
```rust
pub enum WindowMode {
    Windowed,
    BorderlessFullscreen(MonitorSelection),
    SizedFullscreen(MonitorSelection),
    Fullscreen(MonitorSelection),
}
```

This makes it more clear what it affects. For example, if the monitor selection is a top level field, does it affect `WindowPosition::at` too?  What about `WindowPosition::Automatic` ? It seems like it would make sense that automatic would automatically position the window on the selected window, but currently in this PR it still positions it on the main monitor, and `WindowPosition::at` is also relative to the primary monitor.

I also think we really need to support being able to change which monitor fullscreen is using at runtime, this is something we need the user to be able to configure, we have no idea which monitor they want to use if they don't want to use the primary. Could do this in a PR later if that's easier though.

**Comment by devil-ira** [comment]
This was added before, but was yoten by windows-as-entities. For reference: #5878
<sup><s>Monitor selection 2: electric boogaloo

**Comment by paul-hansen** [comment]
Ah yeah that PR has more changes that would make this more of a complete solution. E.g. `WindowPosition::at` becomes relative to the monitor. I could be okay with that. I still think setting it on variants like WindowMode::Fullscreen(monitor) makes it more clear what it applies to and when though.

**Comment by janhohenheim** [comment]
Closing this as @paul-hansen's proposal is now on `main` :) 
http://dev-docs.bevyengine.org/bevy/window/enum.WindowMode.html

**Pull request closed without merging**
