### PR TITLE
[Merged by Bors] - Fix some more typos

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

I managed to dig up some more typos with a combination of the "[code spell checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)" and "[open folder](https://marketplace.visualstudio.com/items?itemName=rwu823.open-folder)" vscode extensions.

## Solution

Fix em

### CODE REVIEW

**Comment by IceSentry** [comment]
What do you mean by the "open folder" extension?

**Comment by rparrett** [comment]
"code spell checker" seems to only spell check open files. "open folder" is an extension in the marketplace that lets you open all files contained in a folder.

**Comment by IceSentry** [comment]
🤦‍♂️ I should have just searched for the extension in vscode directly. Makes sense. That must have been a _lot_  of opened files.

**Comment by rparrett** [comment]
It was manageable going crate by crate.

**Review by IceSentry — APPROVED** [review]

**Comment by rparrett** [comment]
I was previously occasionally checking [cargo-spellcheck](https://crates.io/crates/cargo-spellcheck) on the whole codebase or on files modified by large PRs, but it's extremely user-unfriendly and noisy.

**Review by alice-i-cecile — APPROVED** [review]

**Pull request closed without merging**
