### PR TITLE
Improve bevy simpleicon for smaller sizes

### PR DESCRIPTION
**Pull request by Weasy666**
# Objective
Improve the Bevy simpleicons for smaller sizes. This change makes it look like this:
bevy_simpleicons_webpage_grey

It is still not perfect at the smallest size. I don't think using just one bird is a good idea, because one bird is not a community and with only one bird it would look too similar to the twitter logo, which could result in some legal worries.

If you have different ideas, please voice them here. If you want to test and view them yourselves, just copy the path out of your SVG file and paste it here https://petershaggynoble.github.io/SI-Sandbox/preview/.

PS: The upstream (simpleicons.org) PR is this one https://github.com/simple-icons/simple-icons/pull/7076. I will update it as soon as this PR is merged.

EDIT: Updated the simpleicon to the improved version from #4050.

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Comment by ickk** [comment]
Given that the small badge size is likely to be one of if not the most common use of this, I think we need to improve the legibility at lot. At the moment it is very difficult to tell that it's even meant to be a bird, let alone three.

If removing paths & complexity is off-the-table, I don't know what the solution is beyond further expanding the gaps and/or trying to use the vertical space more effectively (could try rotating the image or something); it looks we're only using about 70% of the available vertical space, so there's free real-estate if we can figure out how to best utilise it.

**Comment by Weasy666** [comment]
I didn't mean that a single bird is off the table, i just wanted to voice my concerns. I can't say if Twitter will have a problem with it, or if it they could even realistically take some legal action against it. I just wanted to mention it, so that we can keep something like that in mind.
Still, i would prefer a solution that keeps the idea of community, but...yeah...i agree that the birds are hard to discern at the small size. I don't really have a good solution, except widen the gap (but that is imo not really a good solution). That is why i wanted to discuss our options here.

**Comment by Weasy666** [comment]
After noticing https://github.com/bevyengine/bevy/pull/4050, i'd like to bump this PR a bit.
@cart (sorry for pinging) Could you please share your opinion on this matter? Should we stay with the bevy of birds and try to separate the birds further with a bigger gap, or should we use a single bird, or even something else we haven't thought about. I'd really like to finish this up and do something with the open PR in the simpleicons repo 😅

**Comment by cart** [comment]
Oops sorry for letting this fester. We should stay with the bevy of birds and give them a larger gap. I like what you did here:
image

If you apply the gap change to the new logo version from #4050, I'm on board!

**Comment by cart** [comment]
In fact, I think we should consider increasing the gap size in the other logo variants too. Better to make the logo "scalable" everywhere rather than having two versions.

**Comment by cart** [comment]
(but im happy to defer that decision until later if you just want to sort out the simpleicons situation first)

**Comment by Weasy666** [comment]
I think, in this PR i will just update the simpleicon with the new logo from #4050. And open a new PR for the other icons. Will do that tomorrow, need to go to bed now. 😴

**Comment by Weasy666** [comment]
Ok done. Follow up PR is #4061.

**Comment by ickk** [comment]
Just so we're all on the same page, this is how the (likely?) most commonly used icon size will render on regular (non-HiDPI) displays:

image image

image
Personally I find it quite hard to discern, but it seems like there's not a lot of good options to improve the situation.

**Review by alice-i-cecile — APPROVED** [review]

**Review by ickk — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Blocking this on #4061, and then we can merge these all at once.

**Comment by richchurcher** [comment]
Closed (backlog cleanup), tracked in #15584 .

**Pull request closed without merging**
