### PR TITLE
[Merged by Bors] - Update linux_dependencies.md

### PR DESCRIPTION
**Pull request by aktaboot**
fixes alsalib dependency for NixOS

### CODE REVIEW

**Comment by nicopap** [comment]
I'll admit I'm impressed. That particular line of the docs was modified about 5 times in the last 2 years by supposedly nix users and none noticed it was wrong? Or was it correct and nix recently changed the package name?

**Review by rparrett — APPROVED** [review]
It looks like it was deprecated / renamed mid-2021, but an alias was added at the same time.
https://github.com/NixOS/nixpkgs/pull/126440

That alias was removed in september of this year:
https://github.com/NixOS/nixpkgs/pull/192681

**Comment by alice-i-cecile** [comment]
Can you change the PR title to be a bit more descriptive? It turns into our commit messages :)

**Review by alice-i-cecile — APPROVED** [review]

**Pull request closed without merging**
