### PR TITLE
Fix text measurement when multiple font sizes are present

### PR DESCRIPTION
**Pull request by UkoeHB**
# Objective

- Fixes https://github.com/bevyengine/bevy/issues/15659

## Solution

- Add up line heights to get text block height instead of using `Metrics`, which only records the largest line height.

## Testing

- [x] Fixed issue shown in https://github.com/bevyengine/bevy/pull/15622

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by viridia** [comment]
This looks great, however I have one minor comment which I am not certain applies for Bevy.

Usually when fonts are laid out on a line, they are aligned on the font baseline, and each font has an ascent-height and a descent height. So the actual line height is calculated as max(all_ascents) + max(all_descents). So for example, if one font has a very large ascent height, and another font has a very larger descent height, you might end up with a line-height that is taller than either font is individually.

**Review by viridia — APPROVED** [review]

**Comment by UkoeHB** [comment]
@viridia [These](https://docs.rs/cosmic-text/0.12.1/cosmic_text/struct.LayoutRun.html) are the docs for the layout info provided by `cosmic-text`. Do you think we need to incorporate `line_y` and `line_top`? The `line_height` claims to be distance to next line so my assumption is it encompasses all complexities.

**Comment by viridia** [comment]
In any case, this PR is "strictly no worse" than what came before, so I'd commit it regardless.

**Review by ickshonpe — COMMENTED** [review]
Looks good.

**Comment by ickshonpe** [comment]
> If we had some fonts with large ascent and descent then it would be easy to test it.

I constructed a few naive examples like this and there didn't seem to be any problems.

**Pull request merged**
