### PR TITLE
bevy_reflect: Update `EulerRot` to match `glam` 0.29

### PR DESCRIPTION
**Pull request by MrGVSV**
# Objective

#15349 added an `impl_reflect!` for `glam::EulerRot`. This was done by copying and pasting the enum definition from `glam` into `bevy_reflect` so that the macro could interpret the variants.

However, as mentioned in the description for that PR, this would need to be updated for `glam` 0.29, as it had not been updated yet.

#15249 came and updated `glam` to 0.29, but did not change these impls. This is understandable as failing to do so doesn't cause any compile errors.

This PR updates the definition and aims to make this silent breakage a little less silent.

## Solution

Firstly, I updated the definition for `EulerRot` to match the one from `glam`.

Secondly, I added the `assert_type_match` crate, which I created specifically to solve this problem. By using this crate, we'll get a compile time error if `glam` ever decides to change `EulerRot` again.

In the future we can consider using it for other types with this problem, including in other crates (I'm pretty sure `bevy_window` and/or `bevy_winit` also copy+paste some types). I made sure to use as few dependencies as possible so everything should already be in-tree (it's just `quote`, `proc-macro2`, and `syn` with default features).

## Testing

No tests added. CI should pass.

---

## Migration Guide

The reflection implementation for `EulerRot` has been updated to align with `glam` 0.29. Please update any reflection-based usages accordingly.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@aecsocket @targrub could I get your reviews here?

**Comment by MrGVSV** [comment]
Also, if we don't want to add the extra dependency, let me know. I can revert that commit!

**Comment by alice-i-cecile** [comment]
No, I really like the dependency!

**Review by pablo-lua — APPROVED** [review]
Looks useful if we get to reflect more enums in the future.

**Pull request merged**
