### PR TITLE
Add example for text with the default font

### PR DESCRIPTION
**Pull request by juliohq**
# Objective

This PR adds a new example for drawing text with Bevy's default font (based on the text example).

### CODE REVIEW

**Comment by nicopap** [comment]
Every example with text uses the default font right? I don't think this is necessary.

**Comment by juliohq** [comment]
Actually no, they load a font with `AssetServer::load` instead of using `default_font`.

**Comment by nicopap** [comment]
Right, the UI examples do explicitly load the font, which is reasonable since they are supposed to illustrate how to make an UI, and you usually want a custom font.

But other examples like the ones in 3d do use the default font.

The main difficulty with default font is not the rust code to use it. The whole point of the default font is that you don't have to write any code for it! But rather the `Cargo.toml` configuration (add the `default_font` feature)

I'm still not convinced such an example is any good. We run the risk of confusing the users, because an explicit example would imply that you need some special manipulation to use default fonts, which is not the case.

**Comment by nicopap** [comment]
If the issue this is trying to solve is discoverability (legitimately difficult to find out there is a default font!) I'd suggest adding a one line comment to the text example. Still not optimal, I think it improves discoverability as much as making a copy/pasted version of the text example with the explicit font removed.

**Comment by mockersf** [comment]
I would also prefer to update the existing text example, for example by removing the font loaded here: https://github.com/bevyengine/bevy/blob/main/examples/ui/text.rs#L65 and adding a comment explaining that if no font is specified, it will use the default font

**Comment by alice-i-cecile** [comment]
Going to close this out: let's make a new PR with the course of action laid out in @mockersf's comment.

**Pull request closed without merging**
