### PR TITLE
Add (de)serialization reflection support for PrimitiveTopology enum.

### LINKED ISSUE #1528: 'bevy_render::pipeline::state_descriptors::PrimitiveTopology\' does not support ReflectValue serialization
## Bevy version

bc4fe9b186db3f32eef38fc4241289df480fa949

## Operating system & version

Windows 10

## What you did

spawn a PbrBundle and try to serialize it like in the example (https://github.com/bevyengine/bevy/blob/main/examples/scene/scene.rs)

## What you expected to happen

get a serialized RON string of my scene

## What actually happened

My game crashed and produced the following error message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Message("Type \'bevy_render::pipeline::state_descriptors::PrimitiveTopology\' does not support ReflectValue serialization"), position: Position { line: 0, col: 0 } }', src\shared\gameplay\scene_loading.rs:9:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Additional information

Discord user Bd#4705 on Bevy discord server said:

> It's missing #[reflect_value(Serialize, Deserialize, PartialEq, Hash)], all reflected enums should have it. There are a few places where the reflection of bevy types is not complete, you should probably open a broader issue for that.

### PR DESCRIPTION
**Pull request by CleanCut**
Resolves #1528 - If anyone knows of a straightforward way to identify which other enums need this treatment, please let me know. 

/cc @Dmajster - can you test this and see if it fixes your problem?  UPDATE: I did a more comprehensive fix in #1536 -- try that instead!

### CODE REVIEW

**Comment by bjorn3** [comment]
> If anyone knows of a straightforward way to identify which other enums need this treatment, please let me know.

Probably something like `rg -A2 "#\[.*Reflect" crates/" | rg -A2 "Deserialize|Serialize" | rg -v "#\[reflect_value"`.

**Comment by CleanCut** [comment]
@bjorn3 Nice! I infer that the enums to look at are the ones that are deriving `Reflect`, `Serialize` and `Deserialize`.

Is it correct that the general approach is that any of the values { `Serialize`, `Deserialize`, `PartialEq`, `Hash` } that are present in the `#[derive(..)]` should be correspondingly added to a `#[reflect_value(...)]`?  That is to say, the `#[reflect_value(...)]` doesn't need to include ones not present in the derive?

**Comment by bjorn3** [comment]
As far as I am aware that is correct.

**Comment by CleanCut** [comment]
Closed in favor of #1536

**Pull request closed without merging**
