### PR TITLE
Minor docs correction for `EntityCommands::insert`

### PR DESCRIPTION
**Pull request by Seldom-SE**
# Objective

The docs on `EntityCommands::insert` refers to the function as `with` instead of `insert` once

## Solution

I corrected the doc

Thanks!

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
I think this case shouldn't even need to be mentioned anymore, as it's not possible anymore unless a struct derives `Bundle` and `Component` at the same time... which seems like not a good idea

**Comment by alice-i-cecile** [comment]
> I think this case shouldn't even need to be mentioned anymore

I agree, can you just remove this sentence entirely in this PR?

**Comment by Seldom-SE** [comment]
> I think this case shouldn't even need to be mentioned anymore

Done, thanks!

**Review by james7132 — APPROVED** [review]

**Comment by Seldom-SE** [comment]
This appears to be resolved in `main`

Thanks!

**Pull request closed without merging**
