### PR TITLE
Provide shell.nix for easier compiling with nix-shell

### PR DESCRIPTION
**Pull request by figsoda**
Created shell.nix under root, as mentioned in #481 

Dependencies are the same as the ones in [docs/linux_dependencies.md](https://github.com/bevyengine/bevy/blob/master/docs/linux_dependencies.md#nixos)
> `nix-shell -p pkgconfig x11 xorg.libXcursor xorg.libXrandr xorg.libXi vulkan-tools lutris vulkan-headers vulkan-loader vulkan-validation-layers alsaLib`

### CODE REVIEW

**Comment by cart** [comment]
I would prefer it if we moved this to docs/linux_dependencies.md under the NixOS section. I want to keep the root as flat / legible as possible and Nix config only applies to a small subset of the population.

**Comment by figsoda** [comment]
> I would prefer it if we moved this to docs/linux_dependencies.md under the NixOS section. I want to keep the root as flat / legible as possible and Nix config only applies to a small subset of the population.

Would you like to keep it embedded in `docs/linux_dependencies.md` or in a separate file under `docs/`?

**Comment by cart** [comment]
Lets keep it embedded in linux_depedencies.md (with instructions on how/where to create the file)

**Comment by cart** [comment]
Looks good to me!

**Pull request merged**
