### PR TITLE
[Merged by Bors] - impl more traits for bevy_core::Name

### PR DESCRIPTION
**Pull request by JoJoJet**
# Objective

- `Name` component is missing some useful trait impls.

## Solution

- Implement the missing traits. `Display`, `AsRef<str>`, and several other conversions to and from strings.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Looks handy and correct, thanks!

**Comment by mockersf** [comment]
The point of using the `Name` component instead of a new typed string is it's hash, and to encourage users to compare them through the has rather than the string as it's faster.

Most of the times, `Name` should not be used as a string. I worry that implementing those conversions would make it too easy to use it as a string.

**Comment by JoJoJet** [comment]
> The point of using the `Name` component instead of a new typed string is its hash, and to encourage users to compare them through the hash rather than the string as it's faster.
> 
> Most of the times, `Name` should not be used as a string. I worry that implementing those conversions would make it too easy to use it as a string.

It seems odd to say that `Name` shouldn't be used as a string. The way I see, storing the hash it just an optimization for a common use-case of this component. It seems backwards that this optimization would prescribe the allowed use cases.

**Comment by mockersf** [comment]
I will disagree, to me it seems forward to use the type system to guide towards the best way to use a value.

**Pull request closed without merging**
