### PR TITLE
Promote `Aabb` to `bevy_math`

### LINKED ISSUE #7395: Consider promoting `bevy::render::primitives::Aabb` to `bevy_math` for interop
## What problem does this solve or what need does it fill?

This is similar to #5575 which was already merged, but this time for the 3D counterpart. There is no common `Aabb` type that can be easily reused and shared among crates, like `Vec3` or other math types. The current `bevy::render::primitives::Aabb` is in the render module, but it's generic enough to be used elsewhere.

## What solution would you like?

Either or all of, in order of priority:

1. "Promote" `bevy::render::primitives::Aabb`, which is a center-half-extent AABB with SIMD support (`Vec3A`) so is fairly general, to the `bevy_math` crate for sharing and reuse, without having to depend on an optional part of Bevy.

2. Add useful methods similar to what was done for `Rect` on #5575.

3. Evaluate if the center-half-extent is the best option. Min-max is an alternative with other nice properties. See for example https://fgiesen.wordpress.com/2013/01/14/min-max-under-negation-and-an-aabb-trick/ -- note that if changing the representation, we _might_ have to keep a render-only copy if the render library requires the current representation for optimization purpose.

## What alternative(s) have you considered?

Roll my own :'( -- see also #5575, same concerns.

### PR DESCRIPTION
**Pull request by djeedai**
# Objective

Promote the `Aabb` type to a generic math type for broader use.

Fixes #7395 partially

## Solution

- Promote the `Aabb` type to `bevy_math` as a generic AABB math type, dropping the `Component` derive.
- Add a newtype component `CullingAabb(Aabb)` in `bevy_render` to replace the previous AABB component used for visibility culling.
- Move the reflection of `Aabb` into the `bevy_reflect` crate, same as its 2D counterpart (`Rect`).

---

### Changed

- Renamed `bevy::render::Aabb` into `CullingAabb`.

### Added

- Added a new `bevy::math::Aabb` type representing a generic axis aligned bounding box.

## Migration Guide

-  `bevy::render::Aabb` has been renamed to `CullingAabb`. A new `bevy::math::Aabb` type has also been added, which is more generic and does not derive `Component`. Simply rename any `Aabb` use into `CullingAabb` to migrate.

### CODE REVIEW

**Comment by djeedai** [comment]
Opened as Draft following discussion on Discord about the question of how to name that new component. Went for `CullingAabb` after a quick discussion with Cart, but please chime in if you have any other suggestion. The PR is probably ready otherwise, if there's no other objection.

**Comment by superdump** [comment]
I think maybe CullingAabb is not the right name. The Aabb could be used for multiple things potentially. Whether it can be directly used for a particular purpose depends perhaps on the space and axes within which the values exist. So for example, these Aabbs as used for culling are in the local space of the Mesh asset. Perhaps LocalAabb or so?

**Comment by djeedai** [comment]
> I think maybe CullingAabb is not the right name. The Aabb could be used for multiple things potentially. Whether it can be directly used for a particular purpose depends perhaps on the space and axes within which the values exist. So for example, these Aabbs as used for culling are in the local space of the Mesh asset. Perhaps LocalAabb or so?

I agree that it could be used for other things, but let's not forget that adding that component enables visibility culling, so it's more than just an AABB it's also an implicit `bool` flag. I'm worried that if we just say "this is a generic local AABB used for many things" then we lock all those things together in an all or nothing pattern. Unless we add a separate `EnableCulling` component in addition of `LocalAabb`, in which case that would be fine.

**Comment by DanielJin21** [comment]
> I'm worried that if we just say "this is a generic local AABB used for many things" then we lock all those things together in an all or nothing pattern. Unless we add a separate `EnableCulling` component in addition of `LocalAabb`, in which case that would be fine.

Does the existing `NoFrustumCulling` component fulfill what you are looking for? I see that this component is checked in `check_visibility`; and fustrum culling is only performed for entities without this component.

**Comment by NthTensor** [comment]
Whats the status on this PR? Seems stale, but still useful. I agree with using `LocalAabb`.

**Comment by djeedai** [comment]
> Whats the status on this PR? Seems stale, but still useful. I agree with using `LocalAabb`.

I never got consensus on naming unfortunately, so it's stuck.

**Comment by superdump** [comment]
@djeedai does the `NoFrustumCulling` comment from @DanielJin21 address your concern about the implicit `bool`? `NoFrustumCulling` makes it explicit - present means frustum culling using the aabb is disabled, not present means frustum culling is enabled, for that entity.

If so, then I still think that the data itself is perhaps most appropriately named based on the coordinate space to which the axes are aligned. So `LocalAabb` as we have previously decided that we should call the coordinate space of mesh vertices 'local'.

**Comment by NthTensor** [comment]
Consensus on discord seems to prefer switching the renderer to `bevy_math::Aabb3d` instead. This seems effectively blocked until that avenue is investigated.

**Comment by NthTensor** [comment]
This has been open for quite some time, and the consensus is now that this PR is obsolete following the changes to bounding boxes and the growth of `bevy_math`. Feel free to re-open if you disagree.

**Pull request closed without merging**
