### PR TITLE
feature input map

### PR DESCRIPTION
**Pull request by PradeepKumarRajamanickam**
Features
- new* Input Map Example
- new* Keyboard Key Mapping
- new* Mouse Button Mapping
- new* Mouse Axis Mapping
- new* Action Strength
- pending* Deadzone implementation

Note* I am very new to rust (less than a week to be precise), bevy and ecs. I am learning If things can be done better please do let me know.

### CODE REVIEW

**Comment by PradeepKumarRajamanickam** [comment]
Look like there is some code format issue. Let me check.

**Comment by cart** [comment]
Anything merged into the bevy repo is by definition no longer a "prototype" crate. This does seem pretty workable, but I think it might make sense to publish this as a 3rd party "prototype" crate first, add it to the awesome-bevy list, and request feedback on the bevy discord.

Then once we're confident with the design, we can add this to the repo (either directly in `bevy_input` or in `bevy_input_map`

**Comment by PradeepKumarRajamanickam** [comment]
Alright shall we close this pr

**Comment by cart** [comment]
Yeah let's close this for now. Definitely (if you want to) publish that crate though. This is a feature that many people want / is basically a "must have" for serious games. I just want to make sure we give it the time it needs to find the "right" API.

**Pull request closed without merging**
