### PR TITLE
Add ImageFormatSetting::Guess to image loader

### PR DESCRIPTION
**Pull request by Azorlogh**
# Objective

- Allow using image assets that don't have an extensions and whose format is unknown. This is useful for loading images from arbitrary HTTP URLs.

## Solution

- This PR adds a new variant to `ImageFormatSetting` called `Guess`. The loader will use `image::guess_format` to deduce the format based on the content of the file.

## Testing

- I locally removed the extension of bevy_bird_dark, and ran a modified version of the `sprite` example:
```rust
//! Displays a single [`Sprite`], created from an image.

use bevy::{
    prelude::*,
    render::texture::{ImageFormatSetting, ImageLoaderSettings},
};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn(SpriteBundle {
        texture: asset_server
            .load_with_settings("branding/bevy_bird_dark", |s: &mut ImageLoaderSettings| {
                s.format = ImageFormatSetting::Guess
            }),
        ..default()
    });
}

```

### Added

`ImageFormatSetting::Guess` to automatically guess the format of an image asset from its content.

### CODE REVIEW

**Comment by Azorlogh** [comment]
Note: when loading images without extension, a warning gets logged to the console:
`Multiple AssetLoaders found for Asset: Some(TypeId { t: (6046691006513703432, 8515571476300803229) }); Path: Some(branding/bevy_bird_dark); Extension: None`
However this warning was already present on main when using `ImageFormatSetting::Format`. I believe it's because of `HdrTextureLoader`. `ImageLoader` is always registered after `HdrTextureLoader`, so it should take precedence over it.

**Review by alice-i-cecile — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
random ci failure, trying to retrigger it

**Comment by alice-i-cecile** [comment]
The first commit from this PR was taken from https://github.com/bevyengine/bevy/pull/11998/commits/6b3ffac85c25cfdf0313448122884e35d8f9b4a4 by @robtfm. @Azorlogh, in the future, either add `Co-authored by:` to your Git commit message or base your branch directly on old work to make sure credit is preserved properly.

**Comment by alice-i-cecile** [comment]
No worries! This change was pretty mechanical: very reasonable that the first step looked extremely similar <3

**Pull request merged**
