### PR TITLE
Update `glam`, `encase` and `hexasphere`

### PR DESCRIPTION
**Pull request by irate-devil**
Update to `glam` 0.25, `encase` 0.7 and `hexasphere` to 10.0

## Changelog
Added the `FloatExt` trait to the `bevy_math` prelude which adds `lerp`, `inverse_lerp` and `remap` methods to the `f32` and `f64` types.

### CODE REVIEW

**Review by rodolphito — APPROVED** [review]
there's also a lerp in bevy_animation/src/lib.rs::728
```
.map(|(a, b)| *a + lerp * (*b - *a));
```
could be
```
.map(|(a, b)| a.lerp(b, lerp));
```

**Review by hymm — APPROVED** [review]
This needs the merge conflicts to fixed.

**Review by laundmo — APPROVED** [review]
Only replacing manual lerp formulas with calls to the FloatExt trait, and all of them look good.

**Comment by irate-devil** [comment]
Fixed the merged conflict.
Check the latest commit for one more switch to the `lerp` method and an `inverse_lerp` I noticed.
I checked that the animated_fox example still behaves as it did.

**Review by laundmo — APPROVED** [review]

**Comment by mockersf** [comment]
https://github.com/OptimisticPeach/hexasphere dependency on glam need to be updated first

**Comment by irate-devil** [comment]
https://github.com/OptimisticPeach/hexasphere/pull/18

**Comment by irate-devil** [comment]
@mockersf, hexasphere has been updated

**Pull request merged**
