### PR TITLE
`LayoutTree` implementation for `UiSurface`

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Implement `LayoutTree` for `UiSurface` instead of using Taffy's `Taffy` built-in implementation.

## Solution

Implement `LayoutTree` for `UiSurface` with minimal changes to existing bevy systems and types.

cargo run --profile stress-test --features trace_tracy --example many_buttons no-text
uisurface-layouttree-impl_tracey

---

## Changelog
 * implemented `LayoutTree` for `UiSurface`
  * added slotmap dependency
  * moved `UiSurface` to separate `ui_surface` module

## Migration Guide

`UiSurface` has been moved to a separate `ui_surface` module.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Technically breaking as we moved a public type.

**Review by alice-i-cecile — APPROVED** [review]
Heavy on boilerplate, but this is precisely why `taffy` exposes this trait now. We already have our own tree: no need to duplicate its storage.

**Comment by alice-i-cecile** [comment]
I take it the trace results are showing a small but measurable performance improvement?

**Comment by ickshonpe** [comment]
> I take it the trace results are showing a small but measurable performance improvement?

It's a small performance regression, I'm not sure why. This is a very basic implementation of the `LayoutTree` trait that hardly changes anything. 

I've tried a couple of different designs on other branches. I think a good approach might be to get rid of `UiSurface` entirely, split up all the fields into resources and queries and implement `LayoutTree` on a `SystemParam`. That should make it easy to split up the other UI update and clean up tasks into separate systems that can run in parallel.

**Comment by alice-i-cecile** [comment]
Are you compiling these benchmarks with LTO enabled? The lack of cross-crate inlining are a plausible source of performance loss.

**Comment by nicoburns** [comment]
> Heavy on boilerplate, but this is precisely why `taffy` exposes this trait now. We already have our own tree: no need to duplicate its storage.

As far as I can tell this is still duplicating the storage. It's just doing so by reimplementing Taffy's storage in Bevy rather than using Taffy's implementation. Not duplicating the storage would mean pulling data directly from the bevy `Style` component during layout. Which I think would be a good thing to do if we can make it work without impacting performance too much, but does not seem to be what this PR does...

**Comment by nicoburns** [comment]
I think we probably ought to hold off on this until Taffy 0.4 is released (or any PR's implementing this should work off of Taffy `main` until it is released), as it makes quite significant changes to the [`LayoutTree` trait](https://github.com/DioxusLabs/taffy/blob/main/src/tree/mod.rs#L25). I also think this is only beneficial if it uses bevy_ecs components for storage. As far as I can see, this is duplicating the Taffy storage code into Bevy without actually changing the way in which data is stored.

**Comment by alice-i-cecile** [comment]
Closing this out then: we should redo this work then.

**Pull request closed without merging**
