### PR TITLE
[Merged by Bors] - Add getter for RenderGraph Node uuid

### PR DESCRIPTION
**Pull request by mtsr**
`RenderGraph` errors only give the `Uuid` of the node. So for my graphviz dot based visualization of the `RenderGraph` I really wanted to show it to the user. I think it makes sense to have it accessible for at least debugging purposes.

### CODE REVIEW

**Comment by Ratysz** [comment]
Don't forget about `cargo fmt`.

Unrelated note, wasn't there a fix ti reduce the noise in CI?.. It's pretty hard to dig [stuff](https://github.com/bevyengine/bevy/pull/1499/checks?check_run_id=1950282111#step:5:66) out.

**Comment by mtsr** [comment]
Thanks. I've been toggling formatting on and off in my editor, because I ran into some projects without `rustfmt.toml` that were nonetheless completed reformatted by my default config.

**Review by Ratysz — APPROVED** [review]

**Comment by CleanCut** [comment]
> Unrelated note, wasn't there a fix to reduce the noise in CI?.. It's pretty hard to dig [stuff](https://github.com/bevyengine/bevy/pull/1499/checks?check_run_id=1950282111#step:5:66) out.

@Ratysz I know I noticed it and planned to reduce the noise, but I don't think I did...[until now](https://github.com/bevyengine/bevy/pull/1508). 😉

**Pull request closed without merging**
