### PR TITLE
Added an illustration to the compass direction docs (issue 13664)

### LINKED ISSUE #13664: Add an illustration to the compass direction docs
> These docs would benefit from an illustration.

_Originally posted by @NthTensor in https://github.com/bevyengine/bevy/issues/13636#issuecomment-2146434371_

Maybe ASCII art?

### PR DESCRIPTION
**Pull request by Wuketuke**
i based the design on @mgi388 in the discussion about the issue.
i added the illustration in such a way that it shows up when you hover your mouse over the type, i hope this is what was meant by the issue
no unit tests were added bc obviously

Fixes #13664

### CODE REVIEW

**Comment by Wuketuke** [comment]
i forgot to add "ignore" to the documentation (bc rust unit tests documentation like a chad)

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
FYI only "fixes" and "closes" work as magic keywords: I edited your post from "solves" to link the issue properly :)

**Comment by alice-i-cecile** [comment]
Wait, why did you close this? This was good stuff and I was about to merge it :)

**Comment by Wuketuke** [comment]
@alice-i-cecile  what no i didnt close it on purpose

**Comment by alice-i-cecile** [comment]
Yep, it looks like it closed this out automatically when the branch was deleted :) I've reopened this now, merging!

**Comment by Wuketuke** [comment]
i feel so silly everytime the tests fail

**Pull request merged**
