### PR TITLE
fix the disorder issue of texture atlas

### PR DESCRIPTION
**Pull request by gaxxx**
# Objective
fix the disorder of SpriteSheetBundle built with TextureAtlasBuilder
When TextureAtlasBuilder builds the final TextureAtlas, it uses the handleId to draw layers, but the handleId is created in a random manner, So the SpriteSheetBundle would display in a disordered way. 

## Solution
use a Vec to store the textures info to make sure the sprite index is as the order as the adding textures.
and since TextureAtlasBuilder is usually temp, the overhead of the Vec is nothing, but the output TextureAtlas would be steady.

### CODE REVIEW

**Review by rparrett — COMMENTED** [review]
This seems to change the behavior somewhat when a user attempts to add the same image multiple times.

I can't really say if the new behavior is better or worse and I doubt that anybody is relying on the old behavior, so probably not a big deal.

I like the idea though.

**Comment by gaxxx** [comment]
> This seems to change the behavior somewhat when a user attempts to add the same image multiple times.
I've not considered this, but I think it's the client's choice.
Maybe someone want to do that to have the same frames in animation :)

**Comment by mockersf** [comment]
> I've not considered this, but I think it's the client's choice.

This PR would actually introduce inconsistencies. images with the same handles will be written at the same place in the atlas, but would have several records in the `atlas.texture` pointing to them, but only one entry in the `atlas.texture_handles` pointing to those rects.

Could you change the `order` to something that would guarantee uniqueness like an `HashSet` to keep the same behaviour?

**Comment by alice-i-cecile** [comment]
Fixed in https://github.com/bevyengine/bevy/pull/11474

**Pull request closed without merging**
