### PR TITLE
fix some post-processing issues

### LINKED ISSUE #5721: UI only shows if in last pass
## Bevy version

f1be89d45809c71c7d3f9f341f99e80780d69b20

## Relevant system information

Tested on MacOS and iOS, with 4x MSAA

## What you did

I used `UiCameraConfig` to enable `show_ui` on only one pass that was not the last pass (using camera priority.)

## What went wrong

The UI did not show, but I could see it was being rendered using the Metal debugger.

## Additional information

I suspected that the wrong color attachment was being used, so that the rendered UI was accidentally discarded.

So I made the following changes:

```diff
diff --git a/crates/bevy_ui/src/render/pipeline.rs b/crates/bevy_ui/src/render/pipeline.rs
index e199cef52..7914d3b8f 100644
--- a/crates/bevy_ui/src/render/pipeline.rs
+++ b/crates/bevy_ui/src/render/pipeline.rs
@@ -105,7 +105,7 @@ impl SpecializedRenderPipeline for UiPipeline {
             },
             depth_stencil: None,
             multisample: MultisampleState {
-                count: 1,
+                count: 4,
                 mask: !0,
                 alpha_to_coverage_enabled: false,
             },
diff --git a/crates/bevy_ui/src/render/render_pass.rs b/crates/bevy_ui/src/render/render_pass.rs
index 66445c92a..9308b7a26 100644
--- a/crates/bevy_ui/src/render/render_pass.rs
+++ b/crates/bevy_ui/src/render/render_pass.rs
@@ -81,14 +81,10 @@ impl Node for UiPassNode {
         };
         let pass_descriptor = RenderPassDescriptor {
             label: Some("ui_pass"),
-            color_attachments: &[Some(RenderPassColorAttachment {
-                view: &target.view,
-                resolve_target: None,
-                ops: Operations {
-                    load: LoadOp::Load,
-                    store: true,
-                },
-            })],
+            color_attachments: &[Some(target.get_color_attachment(Operations {
+                load: LoadOp::Load,
+                store: true,
+            }))],
             depth_stencil_attachment: None,
         };
```

and it works as expected now, but it's probably not necessary to use MSAA for the UI, so I'm not sure what the correct way to do this is. Obviously hardcoding the multisample count is a bad idea; it would have to be passed through the key if this is actually the correct solution.

### LINKED ISSUE #7361: Bloom not restricted to cameras with BloomSettings?
## Bevy version

- latest main
- bevy 0.9
- PR #6677 as of 1/27

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

I want bloom to be applied only to a subset of my scene, so I added a separate camera with `BloomSettings`.

```rust
use bevy::{
    core_pipeline::{bloom::BloomSettings, clear_color::ClearColorConfig},
    prelude::*,
    render::view::RenderLayers,
    sprite::MaterialMesh2dBundle,
};

fn main() {
    App::new()
        .insert_resource(ClearColor(Color::rgb(0.1, 0.1, 0.1)))
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    let no_bloom_layer = RenderLayers::layer(0);
    let bloom_layer = RenderLayers::layer(1);

    commands.spawn((
        Camera2dBundle {
            camera: Camera {
                hdr: true,
                ..default()
            },
            ..default()
        },
        no_bloom_layer,
    ));

    commands.spawn((
        Camera2dBundle {
            camera_2d: Camera2d {
                clear_color: ClearColorConfig::None,
                ..default()
            },
            camera: Camera {
                hdr: true,
                order: 1,
                ..default()
            },
            ..default()
        },
        bloom_layer,
        BloomSettings {
            threshold: 0.5,
            ..default()
        },
    ));

    let (saturation, lightness, alpha) = (0.8, 0.7, 1.0);

    // Circle
    commands.spawn((
        MaterialMesh2dBundle {
            mesh: meshes.add(shape::Circle::new(100.).into()).into(),
            material: materials.add(ColorMaterial::from(Color::Hsla {
                hue: 180.,
                saturation,
                lightness,
                alpha,
            })),
            transform: Transform::from_translation(Vec3::new(-125., 0., 0.)),
            ..default()
        },
        no_bloom_layer,
    ));

    // Hexagon
    commands.spawn((
        MaterialMesh2dBundle {
            mesh: meshes
                .add(shape::RegularPolygon::new(100., 6).into())
                .into(),
            material: materials.add(ColorMaterial::from(Color::Hsla {
                hue: 120.,
                saturation,
                lightness,
                alpha,
            })),
            transform: Transform::from_translation(Vec3::new(125., 0., 0.)),
            ..default()
        },
        bloom_layer,
    ));
}
```

## What went wrong

`BloomSettings` is only on the camera that renders the hexagon, so I expected only the hexagon to get bloom.

Instead, both shapes get bloom.

image

## Additional information

It's not clear if this is user error, a known limitation, or a bug.

### LINKED ISSUE #7435: Post processing doesn't work correctly when using multiple viewports
## Bevy version

0.9 and main

## What you did

In the split_screen example: 
- Enable hdr on both cameras (enabling hdr only on one also breaks bevy, but this is a separate issue).
- Add `BloomSettings::default()` to the left camera
- Use an emissive color for the plane

image

I would have expected the left viewport to have bloom applied to it.

## What went wrong

The bloom effect does not appear in the left viewport.

As you can see here, the bloom effect is indeed computed and generated correctly, but once it gets to the final upscaling pass, the texture modified by the post process is not used as an input.
image

image

I haven't investigated more than that, but it seems like the upscaling node is using the wrong texture when using multiple viewports combined with post processing.

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

fix some post-processing issues

## Solution

- make upscaling load existing color, and use `Some(BlendState::ALPHA_BLENDING)` when writing each camera's result to the output texture instead of just overwriting
- also fix a minor issue with bloom where the output image's alpha was just the bloom alpha. this now needs to be maxed since we blend the output

todo:
- [ ] maybe add a `CameraBlendMode(Option<Wgpu::BlendState>)` component to allow controlling the blend mode
- [ ] maybe clear instead of loading on first upscale for a given target (wgpu docs say you must clear before loading, but it seems to work for me without ... but my ci seems to be crashing on linux examples)
- [ ] check for performance impact

fix #7435 
fix #7361
hopefully fix #5721 (again i haven't tested that)

---

## Migration Guide

- Using a clear color with alpha != 1 will lead to ghosting. make sure your clear color alpha is 1 on the first camera for a given target.
- Previously where you would use `ClearColor::None` on secondary cameras, you will now probably want `ClearColorConfig::Custom(Color::NONE)`, which will clear the texture to transparent
- this may change the apparent sensitivity of bloom on secondary cameras. this is because previously the bloom was using the clear color from previous cameras, which will now not be present in the camera's texture. you can work around this by changing the sensitivity (i found turning up the knee to 4.0 seemed to be the same as a clear color of 0.1, ymmv) or re-ordering the cameras.

### CODE REVIEW

**Comment by Keelar** [comment]
Just tested #5721 again and unlike #7460 this PR does not fix it in its current state.

**Comment by robtfm** [comment]
> Just tested #5721 again and unlike #7460 this PR does not fix it in its current state.

thanks for checking it. do you have a small reproduction?

**Comment by Keelar** [comment]
Sure, this is what I've been testing it with:

```rust
use bevy::{core_pipeline::clear_color::ClearColorConfig, prelude::*, render::view::RenderLayers};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(startup)
        .run();
}

fn startup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle {
        camera_2d: Camera2d {
            clear_color: ClearColorConfig::Custom(Color::WHITE),
        },
        ..Default::default()
    });
    commands.spawn((
        UiCameraConfig { show_ui: false },
        Camera2dBundle {
            camera_2d: Camera2d {
                clear_color: ClearColorConfig::None,
            },
            camera: Camera {
                order: 1,
                ..Default::default()
            },
            ..Default::default()
        },
        RenderLayers::layer(1),
    ));

    commands.spawn(NodeBundle {
        style: Style {
            size: Size::new(Val::Percent(100.0), Val::Percent(50.0)),
            ..Default::default()
        },
        background_color: BackgroundColor(Color::rgba(0.0, 0.0, 0.0, 0.5)),
        ..Default::default()
    });

    commands.spawn((
        SpriteBundle {
            texture: asset_server.load("branding/icon.png"),
            ..Default::default()
        },
        RenderLayers::layer(1),
    ));
}
```

**Comment by robtfm** [comment]
if you change the second camera's clear color to `clear_color: ClearColorConfig::Custom(Color::NONE),` then i think it looks like you're describing. the top half is a bit darker, but only behind the sprite.

i mentioned that in the migration guide, but i think if we decide this is the right approach it might be worth changing the behaviour of `ClearColorConfig::None` so that it does a transparent clear (which is what `Custom(NONE)` does) instead of no clear, then this would work without change.

**Comment by Keelar** [comment]
Ah, you're right. That does fix it. I do agree about maybe changing `ClearColorConfig::None`. Using `ClearColorConfig::Custom(Color::NONE)` when `ClearColorConfig::None` exists is very counter intuitive.

**Comment by robtfm** [comment]
closing too for #7490

**Pull request closed without merging**
