### PR TITLE
add optional viewport to camera

### PR DESCRIPTION
**Pull request by jakobhellermann**
# Objective

Sometimes it is useful to render only to a subregion in the camera's render target, for example when rendering two split view cameras for a local multiplayer game.

## Solution

Add a `Option<Viewport>` to the camera, with a definition of
```rust
struct Viewport {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
    pub min_depth: f32,
    pub max_depth: f32,
    pub scaling_mode: ViewportScalingMode,
}
enum ViewportScalingMode {
    /// `x`, `y`, `w` and `h` are in `0..=1`
    Normalized,
    /// Pixel units
    Pixels,
}
```

The scaling mode is introduced, so that when rendering to fractions of the screen like `x: 0.0, y: 0.0, w: 1.0, h: 1.0` you don't need additional setup to set the values on window resize, and the pixel unit mode is still allowed for maximum flexibilty.

### Open questions

Should the depth be scaled as well according to the camera projection?

**Note: MSAA is currently disabled in the example because only one view would be displayed, possibly due to https://github.com/bevyengine/bevy/issues/3499**

grafik

### CODE REVIEW

**Comment by thebracket** [comment]
I just gave this a spin locally, and it's *exactly* what I need for [Pyrite Box](https://github.com/thebracket/pyrite_box). The UI hasn't been updated to benefit from it, but constraining the 3D viewport to part of the screen is working perfectly (I didn't try anti-aliasing):
image

**Comment by thebracket** [comment]
I am running into one interesting issue with this PR. Not sure if I'm doing something wrong, or if its a problem. If I create the camera as follows:

```rust
let camera = Camera {
            name: Some("camera_3d".to_string()),
            near: perspective.near,
            far: perspective.far,
            viewport: Some(bevy::render::camera::Viewport {
                x: 0.0,
                w: 0.75,
                h: 0.75,
                ..Default::default()
            }),
            ..Default::default()
        };
```

I get an odd black bar at the left of the 3D viewport. The bar isn't there if I move the viewport to the center, and appears on the right if I move the viewport all the way to the right of the screen. 
image

I played around with using pixel or relative coordinates, and the near/far values - but the issue persisted. I'm pretty sure I missed something!

**Comment by blaind** [comment]
This looks interesting. A few questions:
- any thoughts on the expected performance? Is it possible to have e.g. 10x 256pxx256px additional cameras, or would that become infeasible?
- would it be possible to mark render visibility per object on the scene (per render graph?)
- I wonder if the `SecondaryCamPlugin` can be extracted away from the example into bevy itself?

**Comment by jakobhellermann** [comment]
1. I'm not sure. Every view will still have to render the entire scene (or at least what is visible) but at least the resolution would be pretty small so it is cheaper. You'll have to experiment to see where the limits are.
2. you can use the `RenderLayers` component for that
3. that would be useful, although in another PR. https://github.com/bevyengine/bevy/issues/1854 proposes having marker components replacing the current string-based camera API, which https://github.com/bevyengine/bevy/pull/3635 attempts to implement

**Comment by cart** [comment]
I dig this, but I think Viewports should be tied to RenderTargets (as [defined in this comment](https://github.com/bevyengine/bevy/pull/3412#issuecomment-1048383949)) rather than Cameras. I'll be working on the proposed render target changes this week, and I think adapting this pr to those changes should be relatively straightforward.

**Comment by cart** [comment]
Closing in favor of #4898

**Comment by cart** [comment]
Turns out Cameras _were_ the right call in the end :)
(see #4745 for details)

**Pull request closed without merging**
