### PR TITLE
Remove States::variants and remove enum-only restriction its derive

### PR DESCRIPTION
**Pull request by ItsDoot**
# Objective

The `States::variants` method was once used to construct `OnExit` and `OnEnter` schedules for every possible value of a given `States` type. [Since the switch to lazily initialized schedules](https://github.com/bevyengine/bevy/pull/8028/files#diff-b2fba3a0c86e496085ce7f0e3f1de5960cb754c7d215ed0f087aa556e529f97f), we no longer need to track every possible value.

This also opens the door to `States` types that aren't enums.

## Solution

- Remove the unused `States::variants` method and its associated type.
- Remove the enum-only restriction on derived States types.

---

## Changelog

- Removed `States::variants` and its associated type.
- Derived `States` can now be datatypes other than enums.

## Migration Guide

- `States::variants` no longer exists. If you relied on this function, consider using a library that provides enum iterators.

### CODE REVIEW

**Comment by ItsDoot** [comment]
Something to consider is whether to remove the derive macro entirely, and blanket implement `States`.

**Comment by alice-i-cecile** [comment]
> Something to consider is whether to remove the derive macro entirely, and blanket implement `States`.

I don't think we should, at least not in this PR. The explicitness of the trait has its upsides and this PR is not currently controversial.

**Comment by jnhyatt** [comment]
I agree we keep the `derive` macro, at least for now. I suppose there's no real reason anymore since `States` impl is empty.

**Review by jnhyatt — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by jnhyatt** [comment]
I'm going to link #9942 here because it's something we'll want to look into merging once this is in -- it adds the ability to match on state patterns in run conditions and transition schedules. Definitely something we want if we're allowing "anything can be a state"

**Comment by lee-orr** [comment]
I do want to add that I think having the derive is very useful - for a couple of reasons:

a) even with all the changes here and in my PR, states still need to be `Eq` and discreet in some way. Even if theres infinite* options, you have to be able to say "were in the same state we were in last time".
b) the convention across bevy is to have a derive for different categories of types that we support - components, resources, etc. removing that for states will feel arbitrary in a way, and make it harder to tell when something can or cannot be considered a state

**Review by lee-orr — APPROVED** [review]

**Pull request merged**
