### PR TITLE
Providing expanded imports to 2d examples 

### PR DESCRIPTION
**Pull request by lkadalski**
Hello ! :wave: 
I followed the [issue #1721 ](https://github.com/bevyengine/bevy/issues/1721).
Those are changes for just 2d examples. If you approve them I can provide others. 

Signed-off-by: lkadalski <kadalski.lukasz@gmail.com>

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I'm in favor of this and this batch of changes is good but this is ultimately a matter of style.

@cart, how do you feel about expanded imports in the non-game examples for more clarity?

**Comment by MinerSebas** [comment]
I personally don't like this importing style.
If had the choice between wildcard import (1.), specified imports in the prelude (2.), or specified imports without a prelude (3.), then I would choose 1. or 3. over 2.

1.
```rust
use bevy::prelude::*;
```
2.
```rust
use bevy::prelude::{
    AlignSelf, App, AssetServer, Assets, Color, ColorMaterial, Commands, DefaultPlugins, Entity,
    Handle, IntoSystem, OrthographicCameraBundle, Quat, Query, Res, ResMut, Sprite, SpriteBundle,
    SpriteResizeMode, Style, Text, TextBundle, TextSection, TextStyle, Time, Timer, Transform,
    UiCameraBundle, Vec2, Vec3, Windows, With,
};
```
3.
```rust
use bevy::{
    app::App,
    asset::{AssetServer, Assets, Handle},
    core::{Time, Timer},
    ecs::{
        entity::Entity,
        query::With,
        system::{Commands, IntoSystem, Query, Res, ResMut},
    },
    math::{Quat, Vec2, Vec3},
    render::{color::Color, entity::OrthographicCameraBundle},
    sprite::{entity::SpriteBundle, ColorMaterial, Sprite, SpriteResizeMode},
    text::{Text, TextSection, TextStyle},
    transform::components::Transform,
    ui::{
        entity::{TextBundle, UiCameraBundle},
        AlignSelf, Style,
    },
    window::Windows,
    DefaultPlugins,
};
```

**Comment by mockersf** [comment]
with above examples, my order of preference is 1 >> 3 > mixed > 2

**Comment by alice-i-cecile** [comment]
3 > 1 > mixed > 2 for me.

Honestly, #1721 may no longer be needed now that we've merged #1985. Much of the pain was in finding "where the heck is this actually defined", which is fixed now that you only get the canonical location on docs.rs.

If others agree, I think we should close out #1721 and this PR.

**Comment by NathanSWard** [comment]
> If others agree, I think we should close out #1721 and this PR.

Yes I concur with the opinions above. Either use the wildcard match.
```rust
use bevy::prelude::*
```

Or use the fully qualified names.
```rust
use bevy::{
    app::App,
    asset::{/*stuff*/},
    // ...
} 
```

**Comment by cart** [comment]
I agree with the either/or "prelude wildcard" or "fully qualified".

Something to consider now that rust-analyzer is a de-facto standard:  anything with a prelude gets prioritized for import suggestions (and sometimes i don't get non-prelude suggestions at all). This creates a weird situation where fully qualified imports need to be manually specified.

One "solution" to that problem is to just minimize the prelude to the absolute bare minimum to cut down on import noise (basically just the bevy_ecs prelude). Then everything else would need fully qualified names.

This would be a major departure from what we have today and would definitely increase "import noise". But that _is_ what we have tooling for. I'd want us to do a draft pr where we remove preludes from everything but bevy_ecs, then update the examples (using rust-analyzer to pull in whatever the "default" ends up being).

**Comment by alice-i-cecile** [comment]
I'll defer to Cart's judgement here :)

**Comment by cart** [comment]
I think we should experiment with `bevy_internal::prelude::*` being "only" the bevy_ecs prelude, encourage a glob import for that, and let everything else be fully qualified.

However I won't have a solid opinion on this until I can see what it looks like / play around with the code personally. Thats just how my brain works :)

**Comment by anarelion** [comment]
wildcard imports and prelude make finding where something is implemented a bit harder, as ctrl/cmd-click leads you to the prelude module, not the real implementing module.

**Comment by cart** [comment]
At least in vscode + rust analyzer, ctrl/cmd+click navigates to the symbol definition, which has nothing to do with the prelude.

**Comment by lkadalski** [comment]
I'm working in Intellij and ctrl+click also directs to symbol definition (not prelude).

I might experiment with `bevy_internal::prelude` but it is not directly related to this issue. :D 
@alice-i-cecile could you create issue for that(or update existing accordingly?) 
Should we close this PR?

**Comment by cart** [comment]
Yeah I think this discussion has evolved past the initial request. I do think we should consider an even slimmer prelude (probably just bevy_ecs), but that should be a separate issue. And I'm not yet convinced that its a good idea :)

**Pull request closed without merging**
