### PR TITLE
[Merged by Bors] - Fix KTX2 R8_SRGB, R8_UNORM, R8G8_SRGB, R8G8_UNORM, R8G8B8_SRGB, R8G8B8_UNORM support

### LINKED ISSUE #4592: KTX2: unsupported pixel formats R/RG/RGB linear/srgb
Bevy version: Current main: `989fb8a7`

## What you did

Created some KTX2 files from source png files (grayscale, grayscale+alpha, RGB) using the `toktx` tool. No gpu/block texture compression, data is uncompressed (just zstd, but that's irrelevant). Tried to load them in Bevy.

I created a little test project for reproducing the issue: https://github.com/inodentry/bevy_ktx2_test

It contains KTX2 files in a variety of formats. I also created linear versions in addition to sRGB, for good measure.

## What you expected to happen

The textures can load and be used for rendering. The spawned sprites appear on-screen.

## What actually happened

```
WARN bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file logo_bevy.ktx2: unsupported texture format: R8_SRGB, this is an error in `bevy_render`.
WARN bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file logo_bevy_linear.ktx2: unsupported texture format: R8_UNORM, this is an error in `bevy_render`.
WARN bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file logo_rust_grey.ktx2: unsupported texture format: R8G8_SRGB, this is an error in `bevy_render`.
WARN bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file logo_rust_grey_linear.ktx2: unsupported texture format: R8G8_UNORM, this is an error in `bevy_render`.
WARN bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file logo_rust_linear.ktx2: unsupported texture format: R8G8B8_UNORM, this is an error in `bevy_render`.
WARN bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file logo_rust.ktx2: unsupported texture format: R8G8B8_SRGB, this is an error in `bevy_render`.
```

### PR DESCRIPTION
**Pull request by superdump**
# Objective

- Fixes #4592

## Solution

- Implement `SrgbColorSpace` for `u8` via `f32`
- Convert KTX2 R8 and R8G8 non-linear sRGB to wgpu `R8Unorm` and `Rg8Unorm` as non-linear sRGB are not supported by wgpu for these formats
- Convert KTX2 R8G8B8 formats to `Rgba8Unorm` and `Rgba8UnormSrgb` by adding an alpha channel as the Rgb variants don't exist in wgpu

---

## Changelog

- Added: Support for KTX2 `R8_SRGB`, `R8_UNORM`, `R8G8_SRGB`, `R8G8_UNORM`, `R8G8B8_SRGB`, `R8G8B8_UNORM` formats by converting to supported wgpu formats as appropriate

### CODE REVIEW

**Review by mockersf — APPROVED** [review]
change looks OK but I can't test it

**Comment by alice-i-cecile** [comment]
@superdump how does this PR relate to #5325? (And this needs rebasing)

**Review by rodolphito — APPROVED** [review]
transcoding is lossy (unsurprisingly), supporting this is good though. if it ever results in banding near deep dark colors, dithering at the transcode step could be investigated

**Comment by superdump** [comment]
@alice-i-cecile it isn’t directly related. This is about supporting some uncompressed data formats. That other PR was rather about how to interpret the pieces of data (layers in array textures, faces in cubemap textures, both in cubemap array textures, and mip levels and whatever) to get them to wgpu buffers in the correct order without really caring about the format of the data itself.

**Review by alice-i-cecile — APPROVED** [review]

**Pull request closed without merging**
