### PR TITLE
[Merged by Bors] - Remove the early exit to make sure the prepass textures are cleared

### LINKED ISSUE #7888: prepass should run even when phases are empty
## Bevy version

cb0db07c

## What you did

- add a prepass component to a camera
- add a mesh with a `prepass_enabled: false` material

## What went wrong

depth texture is never cleared. the main pass `Load`s depth because of the prepass component on the camera, but the prepass node early exits because no phase items are found, so doesn't clear the depth texture

### PR DESCRIPTION
**Pull request by geieredgar**
# Objective

- Fixes #7888.

## Solution

- Remove the early exit to make sure the prepass textures are cleared.

### CODE REVIEW

**Comment by JMS55** [comment]
The fix seems to work. I'm somewhat confused on the concept though. Say you have a camera with DepthPrepass, but don't have any meshes with prepass_enabled. What happens both in terms of what depth textures get generated, and how the main pass uses it?

**Comment by geieredgar** [comment]
With this we always begin a RenderPass, which will clear the specified color and depth attachments (the prepass textures). If there are no meshes, there are no draw calls so the textures will stay in their cleared state. Previously, because we exited early, no render pass was started so the textures stayed in their old state from the previous frame.

**Comment by JMS55** [comment]
That much makes sense to me. What confuses me is, what happens in the main pass then? Presumably it has an empty depth texture, which seems like it would cause problems?

**Comment by geieredgar** [comment]
The depth texture is cleared with the value `0.0`, which i assume is the depth value at the far plane. So fragments inside the frustum should always pass the depth test, assuming the depth test is set to greater or equal (if the depth of the near plane is positive). If that is the case, it should not cause any issues.

**Review by JMS55 — APPROVED** [review]
After reading up on how depth testing works, this lgtm now :)

**Review by IceSentry — APPROVED** [review]
I originally had the if there to avoid unnecessary work, but I guess it's not that much code that ends up running when these are empty anyway.

**Comment by JMS55** [comment]
The alternative to this would be to set a flag so that the main pass clears the depth texture itself. I don't think that's worth it, this is an unlikely situation to come up anyways.

**Review by robtfm — APPROVED** [review]
i think this is fine. the node won't get this far if no prepass_enabled materials are used as the query above will not match (no RenderPhase would be added), so there won't be a perf impact for no-prepass use cases.

**Comment by robtfm** [comment]
> set a flag so that the main pass clears the depth texture itself

yes updating the camera's depth load op would be better so we don't need to check for all possible prepass markers in the core_3d node. something to bear in mind for if we move the rendergraph to a pure schedule.

**Review by superdump — APPROVED** [review]
bors r+

**Pull request closed without merging**
