### PR TITLE
[Merged by Bors] - Added Opensuse Tumbleweed

### PR DESCRIPTION
**Pull request by dintho**
# Objective

- Describe the objective or issue this PR addresses.
- added openSUSE Tumbleweed deps that i needed to install today 2021-06-22

## Solution

- Describe the solution used to achieve the objective above.
- added info to doc

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by NathanSWard** [comment]
I'm curious, what is this what is `openSUSE` used/required for?

**Comment by dintho** [comment]
> I'm curious, what is `openSUSE` used/required for?

i may not be the best spokesman for suse but the short answer would be a enterprise focused distro that is used more in Europe then here in the usa

a slightly longer answer would be a non-redhat  RPM based distro that originated in germany i think has been around 25+ years. opensuse leap is also used in alot of cash registers here in the states that need a stable gui front end. umm it also i think there is a WSL version

i have been using it as a daily driver OS since Febuary of this year on a thinkpad P50 and yes its slightly bloated as a os... but things just work and it has let me focus on supporting other peoples machines/servers and not my own 

i dont know if that helped answer your question.. below is comparison chart of use scope based on redhat distros  
 
suse = redhat
opensuse leap = cemtos or rocky 
opensuse tumbleweed = arch linux in the sense that its a rolling release distro with 50+ updates a day but i find it more stable then fedora

as a side note: suse linux is where i learned to understand linux from 1996 - 2005 so when i was having issues with the wifi drivers on this machine with debian based distros... installing tumbleweed back in Febuary i was really happy to see that they kept such a seamless hardware support for what is a enterprise workstation laptop that i just happen to get  2nd hand

**Comment by NathanSWard** [comment]
> i may not be the best spokesman for suse but the short answer would be a enterprise focused distro that is used more in Europe then here in the usa

Wow, thank you for the thorough explanation 🙂🙂!!
Afaik, this looks ok to me, but I'm not super familiar, so I'll leave this to another reviewer to approve.

**Comment by ZaMaZaN4iK** [comment]
As an ex-opensuse user, I like mentioning this distro. The instruction is valid.

**Review by ZaMaZaN4iK — APPROVED** [review]

**Comment by mockersf** [comment]
could you mention in #2373 if you're ok with changing the license for your contribution?

**Comment by dintho** [comment]
done

**Pull request closed without merging**
