### PR TITLE
Make `SystemIdMarker` reflect-able

### PR DESCRIPTION
**Pull request by LiamGallagher737**
Make `SystemIdMarker` reflect-able.

### CODE REVIEW

**Review by pablo-lua — APPROVED** [review]

**Comment by notmd** [comment]
You need to register the type as well. Automatic registering types is not landing yet iirc

**Comment by pablo-lua** [comment]
Thats true, there is almost automatic registering based on recursive registering, but thats that

**Comment by LiamGallagher737** [comment]
> You need to register the type as well. Automatic registering types is not landing yet iirc

I had a [discussion about this on the discord](https://discord.com/channels/691052431525675048/749335865876021248/1290425292703137902) and the conclusion seemed to be to dynamically register it when needed.

If I were to register it manually where would that be?

**Comment by pablo-lua** [comment]
Normally, the plugins register all the types they need to use. 
but with bevy_ecs thats another subject, you should probably leave it as it is and register it yourself. bevy_ecs doesn't seem to register directly any of its types

**Review by bushrat011899 — APPROVED** [review]

**Pull request merged**
