### PR TITLE
Rewrite part of Commands rustdoc

### PR DESCRIPTION
**Pull request by stepancheg**
- Explain it is flushed in the same schedule run (was not obvious to me)
- Point to `apply_deferred` example
- Remove mentions of `System::apply_deferred` and `Schedule::apply_deferred` which are probably too low level for the most users

### CODE REVIEW

**Comment by hymm** [comment]
With https://github.com/bevyengine/bevy/pull/9822 merged the story here is a little more complex now.

**Comment by stepancheg** [comment]
Suggestions how to rephrase it?

I submit PRs to rustdoc comments, when I'm trying to understand something, and apparently I don't always understand it correctly.

Also that PR says:

> This PR auto inserts sync points if there are deferred buffers on a system and there are dependents on that system (systems with after relationships).

Doesn't it mean that `apply_deferred` example is outdated — `apply_deferred` call is no longer needed here?

https://github.com/bevyengine/bevy/blob/8067e46049f222d37ac394745805bad98979980f/examples/ecs/apply_deferred.rs#L22-L29

**Comment by hymm** [comment]
> Doesn't it mean that apply_deferred example is outdated — apply_deferred call is no longer needed here?

Yeah probably. You can still add apply_deferred manually and the algorithm will respect it, but the algo doesn't merge manually added sync points together only the auto added ones. For that reason I would not recommend not adding sync points in manually. For the example it might make sense to make a new schedule that disables auto inserted sync points. That or just delete it. That should be done in a separate PR of course.

**Comment by hymm** [comment]
> Suggestions how to rephrase it?

I think the main point of emphasis should be that it's enough to add a before/after relationship between the systems for them to see the effect of commands.

**Comment by stepancheg** [comment]
Changed the docs — updated with new knowledge for me, and moved it to `apply_deferred`.

**Review by doonv — APPROVED** [review]

**Review by TrialDragon — APPROVED** [review]

**Review by james7132 — APPROVED** [review]

**Pull request merged**
