### PR TITLE
run skinned shadow wireframe example in ci

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Avoid regressions on skinned mesh with shadow and wireframe

## Solution

- Run an example in CI

### CODE REVIEW

**Comment by cart** [comment]
This feels like its adding "noise" to our examples. We already have examples that illustrate these features individually, and I don't think we should treat examples as "regression tests", especially given that this will only protect us against future crashes (not actual "correctness" of these features working together).

**Comment by alice-i-cecile** [comment]
I agree with Cart; I don't think this is a useful learning example, and it's not very useful as a test either.

I do like the organizational change though, and I'd be in favor of merging that in a separate PR.

**Comment by cart** [comment]
Closing this out. Feel free to continue the discussion and I'll re-open if needed.

**Comment by cart** [comment]
We always knew we'd want "real" end-to-end tests eventually (and that examples weren't for that). I'm down to re-open that conversation.

**Pull request closed without merging**
