### PR TITLE
Non-breaking change* from UK spellings to US

### PR DESCRIPTION
**Pull request by BlackPhlox**
Fixes issue mentioned in PR #8285.

_Note: By mistake, this is currently dependent on #8285_
# Objective

Ensure consistency in the spelling of the documentation.

Exceptions:
`crates/bevy_mikktspace/src/generated.rs` - Has not been changed from licence to license as it is part of a licensing agreement.

Maybe for further consistency, https://github.com/bevyengine/bevy-website should also be given a look.

### Changed the spelling of the current words (UK/CN/AU -> US) :
cancelled -> canceled (Breaking API changes in #8285)
behaviour -> behavior (Breaking API changes in #8285)
neighbour -> neighbor
grey -> gray
recognise -> recognize
centre -> center
metres -> meters
colour -> color

### ~~Update [`engine_style_guide.md`]~~ Moved to #8324 

---

## Changelog

Changed UK spellings in documentation to US

## Migration Guide

Non-breaking changes*

\* If merged after #8285

### CODE REVIEW

**Review by JoJoJet — APPROVED** [review]

**Review by james7132 — APPROVED** [review]

**Comment by james7132** [comment]
Marking this as controversial due to updating project guidelines. To make sure this is a direction we want to go in.

**Comment by alice-i-cecile** [comment]
I'm opposed to enforcing this without an automated way to check this.

**Comment by BlackPhlox** [comment]
> I'm opposed to enforcing this without an automated way to check this.

@alice-i-cecile Working on it! [#https://github.com/BlackPhlox/bevy/pull/1](https://github.com/BlackPhlox/bevy/pull/1)

**Comment by alice-i-cecile** [comment]
If we can get this in CI without massive false positives I'm on board with it for consistency :) Ideally we're also checking type and method names too?

I think that rather than using a generic spellchecker, we should probably consider a blacklist approach? Software dev always has a ton of "unusual" words, and game dev is even worse for that.

**Comment by BlackPhlox** [comment]
@alice-i-cecile Agreed! I think it might create too much friction for everyone involved if it is a whitelist. So I think we should wait until blacklist functionality has been developed for check-spelling, see [check-spelling - Feature : Dictionary deltas](https://github.com/check-spelling/check-spelling/wiki/Feature%3A-Dictionary-deltas). So currently I'm just testing by compiling my own whitelist just to see if it would work from a CI standpoint.

**Comment by BlackPhlox** [comment]
@alice-i-cecile I've updated my opinion on this and reflected my concerns in #8324. I think we should continue the discussion to that pr instead. Maybe then I should remove [engine_style_guide.md](https://github.com/BlackPhlox/bevy/blob/us_spelling_only/.github/contributing/engine_style_guide.md?rgh-link-date=2023-04-02T07%3A37%3A38Z#spelling-guidelines) changes from this pr, so this pr is trivial instead of marked controversial and do the changes in #8324 instead?

**Comment by alice-i-cecile** [comment]
Agreed on moving that, and removing the style guide changes :)

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Canadian spelling are *obviously* the superior option, but I definitely think we should standardize, even if informally.

Merging now; we can continue the discussion on automated tools to enforce this.

**Comment by JoJoJet** [comment]
I don't agree that style guide changes *need* to be accompanied by automated enforcement. They're just guidelines, and I think that suggesting a standard style is better than being silent on it. Plus, international spellings will most likely slip past code review in the future, so having this in the style guide would make it easier for contributors to write a PR to fix them.

That said, the style guide changes should probably be in a separate PR.

**Pull request merged**
