### PR TITLE
change return type of `World::resource_ref` to `Ref`

### LINKED ISSUE #11825: `World::resource_ref` should return `Ref<T>`
## What problem does this solve or what need does it fill?

`World::resource_ref` currently returns `Res<T>`, which does not make sense as `Res<T>` doesn't provide any functionality over `Ref<T>`. The only reason that `Res<T>` and `ResMut<T>` exist is that system params need to use the type to distinguish resources from other data. Otherwise, `Res{Mut}<T>` do not need to exist, and thus we have always treated `Ref<T>` and `Mut<T>` and as the change detection primitives. `ResMut::map_unchanged` and `ResMut::reborrow` have always returned `Mut<T>` to reflect this.

I disagree with returning `Res<T>` here, as it encourages more use of this type. We should use types like `Res<T>` and `ResMut<T>` and little as possible, so we won't need to duplicate all change detection APIs for these types.

## What solution would you like?

`World::resource_ref` should return `Ref<T>`.

## What alternative(s) have you considered?

None

## Additional context

https://github.com/bevyengine/bevy/issues/9926
https://github.com/bevyengine/bevy/pull/11776
https://github.com/bevyengine/bevy/pull/11776
https://github.com/bevyengine/bevy/pull/9940

### PR DESCRIPTION
**Pull request by atornity**
# Objective

Closes #11825

## Solution

Change return type of `get_resource_ref` and `resource_ref` from `Res` to `Ref` and implement `From Res<T> for Ref<T>`.

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
We should only allow conversions to `Ref` from `Res`, not the other way around. Ditto for `ResMut` and `Mut`. Otherwise, it's possible to get a `Ref` or `Mut` from a `Query` and then treat it as a resource, which is very confusing.

**Comment by atornity** [comment]
> We should only allow conversions to `Ref` from `Res`, not the other way around. Ditto for `ResMut` and `Mut`. Otherwise, it's possible to get a `Ref` or `Mut` from a `Query` and then treat it as a resource, which is very confusing.

You would only be able to convert Ref to Res if the inner value is a resource. Although I would like to replace `From<Ref>` to a new constructor `from_ref`. 

I'm okay with removing it altogether though, but I do remember needing to get a Res from a world (this was my motivation for adding 'get_resource_ref') forever ago, and if there is no conversion then it will no longer be possible once 'get_resource_ref' returns a 'Ref'. 

Anyways, I don't see a problem with potentially getting Res from a Ref in a query since the component need to also be a resource for that to be possible, and you cant really so anything weird/funky with it anyways. 

What do you think? (Sorry for the ramble, I'm on my phone)

**Comment by atornity** [comment]
Alternatively, I could add a 'into_raw' or similar to get the value and ticks from a 'Ref' which can then be used to construct a 'Res' with the 'new' method

**Comment by alice-i-cecile** [comment]
> You would only be able to convert Ref to Res if the inner value is a resource

Ah, I see: the trait bound on the From impl will enforce that. Hmm. Okay, I don't hate exposing this then.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by atornity** [comment]
> Ah, I see: the trait bound on the From impl will enforce that. Hmm. Okay, I don't hate exposing this then.
> 
> 

Great, thoughts on `From` impl vs a new `from_ref` constructor? 

A new constructor would mean you can't do `let my_res = my_ref.into()`, but you can still do `let my_res = Res::from_ref(my_ref)`

**Comment by alice-i-cecile** [comment]
No strong feelings. IMO let's stick with the From impls for consistency.

**Comment by maniwani** [comment]
This seems like the opposite of what was requested in the linked issue?

> The only reason that `Res<T>` and `ResMut<T>` exist is that system params need to use the type to distinguish resources from other data.

This is true. Functions that aren't systems should only be taking `Ref<T>` and `Mut<T>` as parameters, not `Res<T>` and `ResMut<T>`.

I don't think we should encourage using them interchangeably even if `Res<T>` and `ResMut<T>` transparently wrap `Ref<T>` and `Mut<T>`.

**Comment by atornity** [comment]
> I don't think we should encourage using them interchangeably even if `Res<T>` and `ResMut<T>` transparently wrap `Ref<T>` and `Mut<T>`. I think it should be one-way conversions from `Res<T>` to `Ref<T>` and from `ResMut<T>` to `Mut<T>`.

Yeah, I once needed to get a `Res` from a `World` and I wanted to make sure that's still possible once I change the `resource_ref` to return a `Ref`. But I'm realizing that my use case was way to niche and I abandoned that project forever ago anyways, so I don't need it anymore. Once I have time, I'll fix up the pr to remove some of the conversions as well as change the return type of the `resource_ref` methods.

**Comment by atornity** [comment]
@alice-i-cecile are you sure this is controversial now? I removed the conversion from `Ref/Mut -> Res/ResMut` which is the only part that got pushback afaik.

**Review by alice-i-cecile — APPROVED** [review]

**Review by pablo-lua — APPROVED** [review]
No reason why not expose this method, can reduce confusion over the types Res and Ref.

**Comment by ethereumdegen** [comment]
This broke my code and there is nothing in the migration guide... what do i do. now im blocked on my game project and nobody can help me 

https://github.com/bevyengine/bevy/issues/16831

**Pull request merged**
