### PR TITLE
[Merged by Bors] - Implement `From<bool>` for `ShouldRun`.

### PR DESCRIPTION
**Pull request by devil-ira**
Make writing simple yes/no run criteria easier.

### CODE REVIEW

**Review by CGMossa — APPROVED** [review]
LGTM

**Review by mockersf — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]
The implementation is good, but now it makes me wonder why we use `ShouldRun` instead of bool in the first place. If the intention was to eventually extend it, this will break the impl if that ever happens.

**Comment by IceSentry** [comment]
Oh, you're right, sorry, it was a bit too early in the morning for me to do a review 😅

**Comment by alice-i-cecile** [comment]
This is a good stopgap. I intend to remove the `ShouldRun` type completely in favor of a `bool` by 0.9, but that's easy to do regardless.

**Comment by alice-i-cecile** [comment]
bors retry

**Pull request closed without merging**
