### PR TITLE
[Merged by Bors] - use ogg by default instead of mp3

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- mp3 feature of rodio has dependencies that are not maintained with security issues
- mp3 feature of rodio doesn't build in wasm
- mp3 feature of rodio uses internal memory allocation that cause rejection from Apple appstore

## Solution

- Use vorbis instead of mp3 by default

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I think this is an important stopgap solution. We can at least reduce the pain here.

**Review by Ixentus — APPROVED** [review]
Looks good to me. This brings us closer to being able to build for wasm without disabling default features.

Although a lot of people use mp3, they really shouldn't. It's easy to mass convert mp3 to ogg.

**Comment by mockersf** [comment]
Yup, with this change Bevy builds in wasm with the default features

**Comment by cart** [comment]
I agree that this is the best short term move, especially given that there are already long term solutions in the works (Symphonia backends and/or minimp3 dependency fixes). Bevy should work everywhere by default and people that _really_ want mp3 support can just enable the feature.

**Pull request closed without merging**
