### PR TITLE
examples: fix movements for audio 2d/3d

### PR DESCRIPTION
**Pull request by yjhmelody**
# Objective

The directions are wrong, need to reverse them.

## Solution

- Describe the solution used to achieve the objective above.

### CODE REVIEW

**Comment by IceSentry** [comment]
Can you explain what you mean by wrong? When I hit left the listener moves to the left. It all seems correct to me.

**Comment by yjhmelody** [comment]
I'm on a Mac and the direction is reversed. It's very strange

**Comment by mockersf** [comment]
also on a Mac, the directions are right for me

**Comment by yjhmelody** [comment]
Ok. I misunderstood the code

**Pull request closed without merging**
