### PR TITLE
Make `feature(doc_auto_cfg)` work

### PR DESCRIPTION
**Pull request by ameknite**
# Objective

- In #12366 `![cfg_attr(docsrs, feature(doc_auto_cfg))] `was added. But to apply it it needs `--cfg=docsrs` in rustdoc-args.

## Solution

- Apply `--cfg=docsrs` to all crates and CI.

I also added `[package.metadata.docs.rs]` to all crates to avoid adding code behind a feature and forget adding the metadata.

Before:

Screenshot 2024-03-22 at 00 51 57

After:
Screenshot 2024-03-22 at 00 51 32

### CODE REVIEW

**Comment by ameknite** [comment]
I found that even enabling `all-features=true`. It can't not enable "deep features"

Example:
This is how the docs looks in the `bevy` crate:
Screenshot 2024-03-22 at 01 42 08

and this is how it looks in the `bevy_render` crate:
Screenshot 2024-03-22 at 01 42 02


I don't know if exists a solution for this 🤔

**Review by james7132 — APPROVED** [review]
Looks good to me! Definitely wanted something like this for quite some time due to how many compile time features we're accumulating. 

The CI failure looks like a false positive, what could be triggering an allowed lint?

**Review by alice-i-cecile — APPROVED** [review]
I'm happy to merge this once you can appease CI.

**Comment by yrns** [comment]
@alice-i-cecile  It's my understanding that docs.rs already adds the "docsrs" attribute since (https://github.com/rust-lang/docs.rs/pull/2390) so the metadata is unnecessary (which it why I didn't add it), but it doesn't hurt to have.

**Pull request merged**
