### PR TITLE
Remove `ZIndex::Global`

### LINKED ISSUE #9875: Remove `ZIndex::Global`
## What problem does this solve or what need does it fill?

* It doesn't seem very useful, particularly since #9637 was merged.

* Almost no one seems to use it. I can't think of anything it allows you to do, that you can't do without it. CSS only has a local ZIndex.

* It's quite expensive for something no one uses. `ui_stack_system` constructs a new tree of `StackingContext`s each update. Without `ZIndex::Global`, we could update the UI stack in a single walk of the layout tree.

## What solution would you like?

Remove it.

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Remove `ZIndex::Global`

Fixes #9875

## Solution

Change the `ZIndex` enum into a tuple struct wrapping an `i32`. This value represents the local z index, replacing what was `ZIndex::Local`.

`ui_stack_system` updates `UiStack` in a single walk of the layout tree.

`ui_stack_system` benchmark (Yellow is this PR):

```
cargo run --release --features trace_tracy --example many_buttons -- --no-text --no-borders
```

stack_system_walk

---

## Changelog

* `ZIndex::Global` is removed.
* `ZIndex` is now a tuple struct wrapping an `i32`. This value represents the local z index, replacing what was `ZIndex::Local`.
`ui_stack_system` updates `UiStack` in a single walk of the layout tree.

## Migration Guide

`ZIndex` is now an 'i32` tuple struct. This value represents the local z index, replacing what was `ZIndex::Local`.
`ZIndex::Global` has been removed.

### CODE REVIEW

**Comment by james7132** [comment]
This partially reverts #5877. Does #9637 address the issues @oceantume was running into so that this PR doesn't become a regression?

**Comment by oceantume** [comment]
> This partially reverts #5877. Does #9637 address the issues @oceantume was running into so that this PR doesn't become a regression?

I went over the PR text quickly and didn't see a mention for explicitly defining the order in which root node render relative to each other. Since ECS doesn't guarantee ordering for nodes that aren't hierarchically related, wouldn't that still be an issue? 

Regardless of above, this is a regression in the sense that global zindex allows a node anywhere in a tree to "escape" the tree and render above everything else in the app for example. 

Whether this really is a desired feature is debatable though.

**Comment by ickshonpe** [comment]
Local zindex can still be used to sort the root nodes. 

> Regardless of above, this is a regression in the sense that global zindex allows a node anywhere in a tree to "escape" the tree and render above everything else in the app for example.
> 
> Whether this really is a desired feature is debatable though. On simple UIs it's generally not needed, but on the Web, this is often used for rendering deeply nested dropdowns and modals on top of everything else without having to add them to the root (body), and keeping the hierarchy which has effects other than just positioning and ordering (e.g. style inheritence, selectors, etc)

I hadn't really considered style inheritance. I can see there might be some advantages to keeping the hierarchy, though I'm not really sure. There's no need to rush into this I guess anyway.

**Comment by ickshonpe** [comment]
Closed in favour of #9889

**Pull request closed without merging**
