### PR TITLE
Improved Axis API

### PR DESCRIPTION
**Pull request by simpuid**
Added functions to get _current_ value, _previous_ value and _delta_ value of `Axis<T>`
_previous_ value means the value before calling `Axis<T>::update` and _current_ value means the value after calling `Axis<T>::update`. _delta_ value is the difference between _current_ and _previous_ values and it can be `0.0f32`. _delta_ would be `None` when axis' value is not set after calling `Axis<T>::update`
This will help to detect actual changes to axis value by the caller system easily, like in the updated `gamepad_input` example.
The other way is to approx compare  _delta_ with `0.0f32` but that's tiring (see the first commit)

### CODE REVIEW

**Comment by cart** [comment]
I'm a little hesitant about this one. If there are multiple "axis input events" in the same update, that would result in some of the delta being missed.

I also think most axis use cases use absolute values / don't require deltas (ex: "how fast should I move this thing" and "is this axis past a certain threshold"), so I think I'm fine letting the user track this themselves. For use cases that need to track "did something happen since the last time we ran", I think exposing the axis events in an Events<T> queue is a more generic approach.

**Comment by simpuid** [comment]
> I'm a little hesitant about this one. If there are multiple "axis input events" in the same update, that would result in some of the delta being missed.

Actually the delta would be the sum of all the deltas

> I also think most axis use cases use absolute values / don't require deltas (ex: "how fast should I move this thing" and "is this axis past a certain threshold"), so I think I'm fine letting the user track this themselves. For use cases that need to track "did something happen since the last time we ran", I think exposing the axis events in an Events queue is a more generic approach.

Events seems like a good approach to solve this problem. I shall open a new PR with `AxisChange(GamepadAxisType, f32)` and `ButtonChange(GamepadButtonType, f32)` variants of `GamepadEventType`. This would allow users to apply custom deadzones for axis and buttons which was discussed in #681 

Closing because it's redundant

**Comment by cart** [comment]
> Actually the delta would be the sum of all the deltas

I don't thats true. If there are two EventType::AxisChanged events processed in the same frame (lets say with original value 0, new1 == 0.5, new2 == 0.75), this is what I'm pretty sure happens:

1. new1 is processed, set is called. previous = 0, current = 0.5
  * if we called delta() now, we would get a value of `0.5` 
2. new2 is procesed, set is called. previous = 0.5, current = 0.75
  * if we called delta() now, we would get a value of `0.25`
3. some user system runs in update and calls .delta(), we get `0.25` despite the fact that it actually should be `0.75`

**Comment by simpuid** [comment]
> new2 is procesed, set is called. previous = 0.5, current = 0.75

it would be previous() = 0, current() = 0.75 and delta() = 0.75
If you look closely in the `Axis<T>::set` function, the previous values are _inserted_ when they are absent (vacant entry), they are never _updated_ .

`Axis<T>::update` clears the previous values so the previous value is _inserted_ only at the first call of `Axis<T>::set` after `Axis<T>::update`

Whatever the case, the event approach looks better

**Comment by cart** [comment]
Oops yeah you're right. Thanks for bearing with me :smile:

**Pull request closed without merging**
