### PR TITLE
[Merged by Bors] - Add move sprite example. 

### PR DESCRIPTION
**Pull request by jak6jak**
## Objective
There is no bevy example that shows how to transform a sprite. At least as its singular purpose. This creates an example of how to use transform.translate to move a sprite up and down. The last pull request had issues that I couldn't fix so I created a new one

### Solution
I created move_sprite example.

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by jak6jak** [comment]
how do I get check-bans to pass?

**Comment by jak6jak** [comment]
how do I get check-bans to pass?

**Comment by mockersf** [comment]
it has been fixed on main in https://github.com/bevyengine/bevy/pull/2415, you can rebase on main and it should be fixed

**Comment by mockersf** [comment]
I think #2441 (opened for #2400) covers the same ground as this example and then some. Would you mind taking a look at it?

**Comment by jak6jak** [comment]
How would I focus on showing the difference?

**Comment by alice-i-cecile** [comment]
bors try

**Comment by alice-i-cecile** [comment]
@jak6jak, could you rebase this so I can merge it in (finally)? :) https://bevyengine.org/learn/book/migration-guides/0.5-0.6/ will help you translate to the new API.

**Pull request closed without merging**
