### PR TITLE
Use let else

### PR DESCRIPTION
**Pull request by B-Reif**
# Objective

Now that `let...else` is stable, we can improve legibility and reduce indentation in code that currently uses `if let`, followed by large blocks of code.

## Solution

Replace instances of `if let` or `match...return` to use `let...else`.

The first commit in this PR fixes instances of `clippy::manual_let_else`, which detects basic instances of `match` that we can replace easily. The second commit in this PR additionally changes large function and loop blocks to return or continue early when a value is not matched. This unfortunately causes a lot of changed lines in the PR.

We can just cherry pick the first commit if we don't want to change beyond the pedantic clippy lint, or break these changes up into multiple PRs.

EDIT: For any potential reviewers, you might consider viewing the changes in your local editor or somewhere else that ignores indentation changes when highlighting lines.

### CODE REVIEW

**Comment by B-Reif** [comment]
I probably should have checked for that before working on this.

**Comment by IceSentry** [comment]
With that said, your PR is much more recent, so if it gets support soon at least your PR is more up to date

**Comment by IceSentry** [comment]
For the tracking issue in the rustfmt side https://github.com/rust-lang/rustfmt/issues/4914

**Comment by B-Reif** [comment]
It looks like rustfmt's implementation work is more-or-less there also. Apparently held up by 'release/communication work'.
https://github.com/rust-lang/rustfmt/pull/5690

**Comment by B-Reif** [comment]
`let...else` has been blocked on rustfmt for nearly four months now. Would we consider using a fork of rustfmt to get this unblocked until they can get this thing merged? This release gap is starting to seem unreasonable.

**Comment by mockersf** [comment]
> EDIT: For any potential reviewers, you might consider viewing the changes in your local editor or somewhere else that ignores indentation changes when highlighting lines.

You can do that in GitHub UI for reviews:

Screenshot 2023-04-14 at 19 14 19

> Would we consider using a fork of rustfmt to get this unblocked until they can get this thing merged?

I don't think `let ... else` is an improvement big enough for that... so no for me

**Comment by alice-i-cecile** [comment]
This is no longer blocked, but it's going to be easier to just remake this than to fix the merge conflicts :) Please feel free to do so: this is generally a really nice change to make!

**Pull request closed without merging**
