### PR TITLE
Conditions to check for any state

### PR DESCRIPTION
**Pull request by gabriel-gheorghe**
# Objective

Sometimes we need to run the same system within different states, but not in all of them.
For example a background animation should run on both Playing and Paused states but never in GameOver state.
Currently we can do the following:

```rust
enum GameState {
    #[default]
    Playing,
    Paused,
    GameOver,
}

background_animation.run_if(in_state(GameState::Playing).or_else(in_state(GameState::Paused)))
```

Consider having multiple checks, it becomes spaghetti.
This code can be reduce to:

```rust
background_animation.run_if(in_any_state([GameState::LevelPlaying, GameState::Editor]))
```

## Solution

Implementing ```in_any_state``` and ```state_exists_and_equals_any``` conditions.

## Use Cases

I've used this pattern a lot in my game so I put here some examples.

Consider having a game that contains these states: LevelPlaying, Editor, EditorSimulating + others.
And a CameraPlugin which have some system.
A camera can be rotated 90 degrees only when you are in LevelPlaying, Editor and EditorSimulating.
You can manually move a camera only when you are in Editor or EditorSimulating.

```rust
pub struct CameraPlugin;

.add_systems(
    PreUpdate,
    camera_rotate_90
        .run_if(in_any_state([
            GameState::LevelPlaying,
            GameState::Editor,
            GameState::EditorSimulating,
        ])),
).add_systems(
    Update,
    camera_manual_movement
        .run_if(in_any_state([
            GameState::Editor,
            GameState::EditorSimulating,
        ])),
);
```

Another example is a return to main menu functionality. You can do that when you are only in some states.
This way you force that if the event ReturnToMainMenu is send from another state, nothing happens, and you make sure
another devs on your team won't create behaviour that is not intended.

```rust
pub struct MainMenuPlugin;

.add_systems(
    Update,
    return_to_main_menu
        .run_if(on_event::<ReturnToMainMenu>())
        .run_if(in_any_state([
            GameState::LevelPlaying,
            GameState::LevelPaused,
            GameState::LevelCleared,
            GameState::GameOver,
            GameState::Editor,
        ])),
);
```

The third example is similar to the first one, I want to run my player_logic only when I am inside LevelPlaying and EditorSimulating states.

```rust
pub struct PlayerPlugin;

.add_systems(
    PreUpdate,
    player_logic
        .run_if(in_any_state([
            GameState::LevelPlaying,
            GameState::EditorSimulating,
        ])),
)
```

### CODE REVIEW

**Comment by lee-orr** [comment]
I just want to point out that if https://github.com/bevyengine/bevy/pull/9957 is merged first, this will need some implementation adjustments (and vice versa). While there aren't really code-line conflicts here, there are conceptual changes around States that make the two PR's incompatible without some modification.

**Comment by thirdq** [comment]
I agree.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
This is well made, but feels like a pretty heavy tool without a lot of flexibility. Is this really easier than writing your own run condition?

I'd happily approve an example demonstrating this pattern though.

**Comment by thirdq** [comment]
> This is well made, but feels like a pretty heavy tool without a lot of flexibility. Is this really easier than writing your own run condition?
> 
> I'd happily approve an example demonstrating this pattern though.

I added some examples from my game in the description.

**Comment by alice-i-cecile** [comment]
Hmm okay, that's helping me understand why this might be a natural fit. Could we use the `matches!` machinery somehow? Then do `run_if(state_matches!(GameState::LevelPlaying | GameState::Editor))`, which exposes the full power of enum pattern matching in this API.

**Comment by jnhyatt** [comment]
I think that's a really good point. Being able to pattern match on states would allow us to do most of what's demonstrated here, and we really want pattern matching anyway now that we can make states out of structs, nested enums, etc.

**Comment by thirdq** [comment]
> Hmm okay, that's helping me understand why this might be a natural fit. Could we use the `matches!` machinery somehow? Then do `run_if(state_matches!(GameState::LevelPlaying | GameState::Editor))`, which exposes the full power of enum pattern matching in this API.

After #9957 gets merged I can use the same pattern like there. As I saw, in that PR there it is:
`in_state!(GameState, LevelPlaying { .. })`
and then I can implement:
`state_matches!(GameState, LevelPlaying | Editor)`.

**Comment by alice-i-cecile** [comment]
Superseded by https://github.com/bevyengine/bevy/pull/10088 <3

**Pull request closed without merging**
