### PR TITLE
Disable lint that interferes with rust beta CI compatibility

### LINKED ISSUE #15116: Main branch fails to compile on Rust beta.
## Weekly CI run has failed.
[The offending run.](https://github.com/bevyengine/bevy/actions/runs/10772729527)

### PR DESCRIPTION
**Pull request by BenjaminBrienen**
# Objective

Fix our CI with rust beta

## Solution

Disable new lint. Fixes #15116.

## Testing

Ran `cargo +nightly clippy`.

### CODE REVIEW

**Comment by BenjaminBrienen** [comment]
Made this because I don't want my shenanigans in #16141 to be a headache or a blocker.

**Comment by BenjaminBrienen** [comment]
> could you add a todo to re-enable the lint after it's fixed? with a link to a relevant issue/pr

The decision to disable the lint has to do with the fact that bevy chooses not to elide lifetimes which clippy suggests can be elided. In fact, I have an open PR to unelide many currently elided lifetimes to make that decision more consistent. It isn't a bug with the lint, if that's what you meant by you comment. I'll link my PR in a second.

**Comment by BenjaminBrienen** [comment]
https://github.com/bevyengine/bevy/pull/16141

**Comment by mockersf** [comment]
I was more thinking of a link to your PR, but I haven't caught up completely yet so not sure if it will be enough to re-enable the lint

**Comment by BenjaminBrienen** [comment]
> Made this because I don't want my shenanigans in #16141 to be a headache or a blocker.

The PR is here

**Comment by alice-i-cecile** [comment]
> could you add a todo to re-enable the lint after it's fixed? with a link to a relevant issue/pr

I don't think we should ever re-enable this lint. The diff is really unpleasant.

**Pull request merged**
