### PR TITLE
[Merged by Bors] - Fix mouse_clicked check for touches.

### PR DESCRIPTION
**Pull request by nihohit**
This seems like a copy-paste from line 72 that was only partially modified.

I don't know how to test this, so please verify me :)

### CODE REVIEW

**Comment by cart** [comment]
Yup this looks correct to me, but we'll want someone with a touch screen to validate. I'd run this on my android phone, but currently android builds are broken :)

**Comment by alice-i-cecile** [comment]
@nihohit, can you comment in #2373? We've since relicensed to MIT + Apache, and I'd like to either ensure that this can be picked up or close it out.

**Comment by nihohit** [comment]
@alice-i-cecile done

**Comment by alice-i-cecile** [comment]
This is a trivial fix: we were triggering on button presses on touch releases, rather than touch presses. This is obviously incorrect.

**Pull request closed without merging**
