### PR TITLE
[Merged by Bors] - Update minimal version requirements for dependencies

### PR DESCRIPTION
**Pull request by bjorn3**
This was tested using cargo generate-lockfile -Zminimal-versions.
The following indirect dependencies also have minimal version
dependencies. For at least num, rustc-serialize and rand this is
necessary to compile on rustc versions that are not older than 1.0.

* num = "0.1.27"
* rustc-serialize = "0.3.20"
* termcolor = "1.0.4"
* libudev-sys = "0.1.1"
* rand = "0.3.14"
* ab_glyph = "0.2.7

Based on https://github.com/bevyengine/bevy/pull/2455

### CODE REVIEW

**Comment by mockersf** [comment]
for easy change comparison: https://github.com/bjorn3/bevy/compare/remove_unused_deps...bjorn3:minimal_versions

why do you want to add minimal patch versions?

**Comment by bjorn3** [comment]
To ensure that adding or updating bevy without a full `cargo update` will always work without problems. Currently if you already have say anyhow 1.0.0 in your `Cargo.lock` you will get a compilation error when adding bevy as new dependency. In the future it could happen that a fresh `Cargo.lock` generated at the time of the release of a certain bevy version will cause compilation to fail when bevy is updated to a new version in the future if the minimal version requirements in bevy are not updated to match reality.

**Comment by mockersf** [comment]
Oh they broke backward compatibility between patch version... though that's a hard guarantee to make

**Review by mockersf — APPROVED** [review]

**Comment by bjorn3** [comment]
Anyhow only uses patch releases it seems. The current version is 1.0.42.

**Review by NiklasEi — APPROVED** [review]

**Comment by bjorn3** [comment]
Rebased

**Pull request closed without merging**
