### PR TITLE
[Merged by Bors] - Implement AnyOf queries

### PR DESCRIPTION
**Pull request by TheRawMeatball**
Implements a new Queryable called AnyOf, which will return an item as long as at least one of it's requested Queryables returns something. For example, a `Query<AnyOf<(&A, &B, &C)>>` will return items with type `(Option<&A>, Option<&B>, Option<&C>)`, and will guarantee that for every element at least one of the option s is Some. This is a shorthand for queries like `Query<(Option<&A>, Option<&B>, Option<&C>), Or<(With<A>, With<B>, With&C>)>>`.

### CODE REVIEW

**Comment by mockersf** [comment]
I think it won't be part of the prelude, is it willingly?

**Comment by alice-i-cecile** [comment]
I would like this to be part of the prelude; all of the query and system parameters feel particularly annoying and confusing to repeatedly manually import.

**Review by cart — COMMENTED** [review]
Looks good to me. The `all_tuples` derive is a pretty "big" one. Probably worth measuring how much it affects compile times (but I won't block on that).

Just needs to be updated to main (i resolved conflicts, but this needs `WorldQuery::ReadOnlyFetch` support). I'll leave the ball in @TheRawMeatball's court for now and pick this up myself if needed.

**Comment by MinerSebas** [comment]
Should there be also a `Query<ExclusiveAnyOf<(&A, &B, &C)>>` that is basically sugar for

`Query<(Option<&A>, Option<&B>, Option<&C>), Or<((With<A>, Without<B>, Without<C>), (Without<A>, With<B>, Without<C>), (Without<A>, Without<B>, With<C>))>>`
?

**Comment by alice-i-cecile** [comment]
> Should there be also a Query<ExclusiveAnyOf<(&A, &B, &C)>>

`ExactlyOneOf` explains the idea better :) IMO this isn't super useful: really what you want to enforce here should be encoded by #1481, rather than in queries.

**Pull request closed without merging**
