### PR TITLE
add `Update` to `add_systems` in `state_changed` docs

### LINKED ISSUE #10866: Function `state_changed` docs does add system without a schedule
http://dev-docs.bevyengine.org/bevy/prelude/fn.state_changed.html#example

This example does 

```rust
app.add_systems(
    // `state_changed` will only return true if the
    // given states value has just been updated or
    // the state has just been added
    my_system.run_if(state_changed::<GameState>()),
);
```

should likely include a schedule such as `Update` as a first arg

### PR DESCRIPTION
**Pull request by Cyborus04**
# Objective

Fixes #10866

## Solution

Added the argument to the method call.

### CODE REVIEW

**Comment by Cyborus04** [comment]
wait what

**Review by alice-i-cecile — COMMENTED** [review]
I think this is *probably* going to fail to compile, because of the dumb thing we're doing above with pretending that a `Schedule` is an `App`. We might be able to use `Schedules` instead.

Ultimately caused by the split between crates that I want to eliminate in #3786.

**Comment by Cyborus04** [comment]
Ah, makes sense. Locally running the doc check with `Schedules` instead didn't seem to work (hope I did that right), so I'll follow that issue and try this again when that's concluded.

**Comment by alice-i-cecile** [comment]
This has been changed quite a bit; closing <3

**Comment by Cyborus04** [comment]
makes sense

**Pull request closed without merging**
