### PR TITLE
[Merged by Bors] - Remove auto-margin properties from the examples

### LINKED ISSUE #6498: Stop using auto-margin to centering UI elements in our examples
## Bevy version

Current main

## Description

At several locations throughout our examples we use the old css-hack of setting `margin: auto` on an element that should be centered in order to make it center on the screen. This is incorrect and can lead to hard-to-understand behaviour with sibling-nodes. 
The correct way to center elements on the page is to set the following properties on the parent node:
- `AlignItems::Center`
- `JustifyContent::Center`

See https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container#properties_that_control_alignment

We should correct this so that new users of Bevy to learn our tools correctly.

Ref: https://github.com/bevyengine/bevy/pull/5513#discussion_r1014839272

## Suggested fix

1. Look through all examples for nodes with auto-margin
2. Determine if they have auto margin in order to achieve centering
3. If yes, replace it with the correct setup of the parent node (`AlignItems::Center`, `JustifyContent::Center`)

### PR DESCRIPTION
**Pull request by garychia**
# Objective

Fixes #6498.

## Solution

Adding a parent node with properties AlignItems::Center and JustifyContent::Center to centered child nodes and removing their auto-margin properties.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Awesome, thank you very much!

**Review by TimJentzsch — APPROVED** [review]
Definitely a bit more verbose, but this should be the correct way to do this.

Maybe we can introduce some helper methods in the future that make common stuff like this easier.

**Review by Weibye — APPROVED** [review]
Ran all relevant examples and verified that they look the same 👍

**Pull request closed without merging**
