### PR TITLE
Added actual type to Property::set panic message & reduced impl_property_std size to 300 lines

### PR DESCRIPTION
**Pull request by dbartussek**
The error now reads `prop value is not f32, but u64` instead of `prop value is not f32`.
I've also reduced the size of impl_property_std.rs by using the same impl for all integers and floats respectively via a macro, but I can undo that if you prefer the old way.
And lastly, is it intentional that integers cannot be assigned to floats? The integer assigns are also lossy, so it wouldn't really change semantics. If not, I'd add `set_integer!` to the float impl.

### CODE REVIEW

**Comment by cart** [comment]
Thanks for the interest! Im definitely cool with macros provided they are simple and they significantly cut down code. in this case they seem  to fall into that category.

However its important to note that in this case, each block is slightly different, so theres actually a bug in the new implementation. (the non-isize impls will be missing isize conversion). The current impls contain checks for Self and then convert to every type that isn't Self.

In regard to floats, i think i would prefer to not do implicit conversions. Medium term I actually want to completely remove the Property casting behavior we currently have. The main reason its there today is that the RON file format is lossy on type (theres only one int type), so we need to support casting to the "real" type when we load from ron. The new scene format will ideally fully preserve integer and float types. Then we can regain some type safety.

For now, this change is definitely welcome, but we'll need to resolve the slightly broken behavior that the macro introduces.

**Comment by dbartussek** [comment]
Ah, yes, missed that line. That's why it's always good to have someone else check your copy-paste 😅. I've removed the downcast to self, it now always goes through the list of integer types.

I've also run fmt on the changes.

**Comment by dbartussek** [comment]
So I've looked into how a downcast_ref chain is compiled and [it looks like it just calls the virtual type_id() function each time and compares in sequence](https://godbolt.org/z/cEE9Gn).
This means that my version performs worse for the best/desired case of assigning Self because the check is no longer in front.

I see 3 options to deal with this:
- We go back to the old version where each type has its own implementation
- We keep it as is. If you plan on removing the behavior in the future anyways, it may not matter too much
- We put a check for Self in the front and just check the Self type twice

[I've also written a macro that reimplements downcast_ref for variadic arguments](https://godbolt.org/z/vEvdTh). It only calls type_id() once and compiles the type check down to a comparison tree. I'm not sure if you will like it because it's a non-trivial macro and uses unsafe, but with a downcast_ref<Self> in front it should make solution 3 just as good as the current version in the best case and better in the worst/average case.

If you tell me which one is your preferred option, I will implement it.

**Comment by cart** [comment]
I'm closing this. Feel free to open a new pr for the improved panic message (but no pressure).

**Pull request closed without merging**
