### PR TITLE
drop info locks in single threaded

### LINKED ISSUE #15508: regression in GLTF Scene loading
## Bevy version

0.15.0-dev

## What you did

Migrated code base with a SceneView example to 0.15.0-dev.

## What went wrong

`let scene: Handle<Scene> = asset_server.load(asset);` causes Bevy to hang and never load the asset. This is in a regular system with `asset_server: Res<AssetServer>`.
On the previous version (0.14.2), the asset loaded correctly. There is no error message.

## Additional information

Asset in question: https://github.com/UmbraLuminosa/sickle_ui/blob/main/assets/examples/Low_poly_scene.gltf#Scene0

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

addresses half of issue #15508
avoid asset server deadlock when `multi_threaded` feature is not enabled.

## Solution

drop the locks in the single-threaded case.

the lock is still held with the `multi-threaded` feature enabled to avoid re-locking to insert the load task. i guess this might possibly cause issues on single-core machines ... is that something we should worry about?

### CODE REVIEW

**Comment by eidloi** [comment]
Please note that this will only _partially_ fix #15508 as there is still a 50/50 chance it will not render (to be verified once this is merged).

> is that something we should worry about?
We probably should, since the `multi-threaded` feature would not exist otherwise :)

**Comment by robtfm** [comment]
> > is that something we should worry about?
> 
> We probably should, since the `multi-threaded` feature would not exist otherwise :)

so if a user has a single-threaded cpu and runs an app with the multi-threaded feature, i suspect this may still hang (i'm not sure though - perhaps in that case the tasks are still deferred until after the lock is dropped on the spawning thread).

my question is, should we lock/release/lock again on the `AssetInfo`s to avoid this case (which will be slower), or is it reasonable to assume that apps targetting single-threaded machines will not use the multi-threaded feature?

**Review by BenjaminBrienen — APPROVED** [review]

**Review by bushrat011899 — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@robtfm this is failing on web.

**Comment by robtfm** [comment]
i trashed the history (vscode push after merge doesn't squash apparently). i can start over if you like, the diff is still clearly contained though

**Comment by alice-i-cecile** [comment]
Yeah the diff is good so I'm going to merge anyway.

**Pull request merged**
