### PR TITLE
[Merged by Bors] - fix `Quat` type name in scene example scene file

### LINKED ISSUE #5790: Unable to Load Quat Type for Scene Example
## Bevy version

I just pulled down main right now. 

## What you did

I ran the scene example with `cargo run --example scene`

## What went wrong

I get this warning... 

` WARN bevy_asset::asset_server: encountered an error while loading an asset: No registration found for glam::f32::scalar::quat::Quat`

If I delete the transform component from the ron file, it seems to work fine and I get

```
2022-08-24T22:28:06.755070Z  INFO scene:   Entity(3)
2022-08-24T22:28:06.755115Z  INFO scene:     ComponentA: { x: 1 y: 2 }

2022-08-24T22:28:06.816769Z  INFO scene:   Entity(4)
2022-08-24T22:28:06.816809Z  INFO scene:     ComponentA: { x: 3 y: 4 }
```

### PR DESCRIPTION
**Pull request by tguichaoua**
# Objective

fix #5790 

## Solution

Change type name in the scene file by its new name `glam::f32::sse2::quat::Quat`.

### CODE REVIEW

**Comment by djeedai** [comment]
As noted by @DJMcNab in #5790 (as I understand) this is the wrong fix.

**Comment by tguichaoua** [comment]
https://github.com/bevyengine/bevy/pull/5805 is a more generic fix to this kind of problem.

**Review by cart — APPROVED** [review]
Yeah we really need something like #5805. While we wait, I think its better to bet on sse2 existing than not existing, so im inclined to merge this.

**Pull request closed without merging**
