### PR TITLE
[Merged by Bors] - log spans on panic when trace is enabled

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Help debug panics

## Solution

- Insert a custom panic hook when trace is enabled that will log spans

example when running a command on a despawned entity

before:
```
thread 'main' panicked at 'Could not add a component (of type `panic::Marker`) to entity 1v0 because it doesn't exist in this World.
If this command was added to a newly spawned entity, ensure that you have not despawned that entity within the same stage.
This may have occurred due to system order ambiguity, or if the spawning system has multiple command buffers', /bevy/crates/bevy_ecs/src/system/commands/mod.rs:664:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

after:
```
   0: bevy_ecs::schedule::stage::system_commands
           with name="panic::my_bad_system"
             at crates/bevy_ecs/src/schedule/stage.rs:871
   1: bevy_ecs::schedule::stage
           with name=Update
             at crates/bevy_ecs/src/schedule/mod.rs:340
   2: bevy_app::app::frame
             at crates/bevy_app/src/app.rs:111
   3: bevy_app::app::bevy_app
             at crates/bevy_app/src/app.rs:126
thread 'main' panicked at 'Could not add a component (of type `panic::Marker`) to entity 1v0 because it doesn't exist in this World.
If this command was added to a newly spawned entity, ensure that you have not despawned that entity within the same stage.
This may have occurred due to system order ambiguity, or if the spawning system has multiple command buffers', /bevy/crates/bevy_ecs/src/system/commands/mod.rs:664:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Excellent! This helps a fair bit immediately, and should be a useful building block.

**Comment by alice-i-cecile** [comment]
IMO this is important / useful enough that I would like `trace` to be a default `bevy` feature. It doesn't [appear to be](https://github.com/bevyengine/bevy/blob/main/Cargo.toml#L19), but our feature structure is rather elaborate.

**Review by IceSentry — APPROVED** [review]

**Comment by cart** [comment]
Lovely! _Lots_ of value here.

> IMO this is important / useful enough that I would like trace to be a default bevy feature. It doesn't [appear to be](https://github.com/bevyengine/bevy/blob/main/Cargo.toml#L19), but our feature structure is rather elaborate.

`trace` adds a level of instrumentation that could register perf-wise in released apps. I'm not comfortable enabling it by default until we've shown that it doesn't meaningfully regress perf in any "real world" high-complexity apps.

**Comment by superdump** [comment]
Just want to say that I love this. :)

**Pull request closed without merging**
