### PR TITLE
Fix dim emissive values in `lighting` example

### LINKED ISSUE #12330: `lighting` example emissive values need to be adjusted
## Bevy version

0.13 / main / after #11868

## What you did

`cargo run --example lighting`

## What went wrong

The sphere and capsules representing the red and green lights are dark and sad. They used to be bright.

The sphere representing the blue light doesn't seem to be visible in the scene at all, but it also has an emissive value that probably needs adjusting.

It seems like values in the ballpark of 100x the old values might work.

### PR DESCRIPTION
**Pull request by andristarr**
# Objective

- Fixes #12330 

## Solution

- Increasing the emissive of the objects representing the lights.

### CODE REVIEW

**Comment by rparrett** [comment]
@BD103 do the values in this PR look good? They are a bit dimmer than what I came up with based the output of `0.12.1` but I don't know what we should prefer, artistically.

**Review by BD103 — CHANGES_REQUESTED** [review]
I agree with @rparrett, I think the emission needs to be increased a little bit more.

Could you also remove the unused `bevy::pbr::light_consts` import?

https://github.com/bevyengine/bevy/blob/b26f20a563286e18c7e1f07f5925d9cc94fb4891/examples/3d/lighting.rs#L8

**Comment by andristarr** [comment]
Done! Perfectly increased by a magnitude of 100x.

**Review by rparrett — APPROVED** [review]
Looks good to me. Thanks!

Could you (or a maintainer) adjust the PR title to something like

~~~
Fix dim emissive values in `lighting` example
~~~

?

The PR title is what ends up in the commit log / changelog, so it's good if it looks nice and pretty.

**Comment by andristarr** [comment]
Done!

**Review by mockersf — APPROVED** [review]

**Pull request merged**
