### PR TITLE
Fix action.yml syntax

### LINKED ISSUE #15429: action.yml is not valid (schema)
[metadata-syntax-for-github-actions](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions)

image

.github\actions\install-linux-deps\action.yml
image

Should we have CI for our CI? 😆

Schema: https://json.schemastore.org/github-action.json

### PR DESCRIPTION
**Pull request by BenjaminBrienen**
# Objective

Fixes #15429 

## Solution

Fix type of default value

## Testing

We'll see if the CI still works I guess.

## Showcase

image

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Needs one approval before final review for trivial PRs :)

**Comment by BenjaminBrienen** [comment]
I thought that trivial only needed a final review, my bad.

**Review by richchurcher — APPROVED** [review]
Annoying as it is to have a bool in a string, LGTM!

**Comment by BenjaminBrienen** [comment]
> Annoying as it is to have a bool in a string, LGTM!

I wonder if I can submit a PR to GitHub Actions to improve their interface 🤔

**Comment by richchurcher** [comment]
> I wonder if I can submit a PR to GitHub Actions to improve their interface 🤔

I imagine they do it that way because the default value might be anything, depending on the action. People pass all kinds of weird JSON into their actions :laughing:

**Pull request merged**
