### PR TITLE
Remove `bevy_core`

### LINKED ISSUE #16892: Split up `bevy_core`
## What problem does this solve or what need does it fill?

Title. This crate is basically a utilities crate, which we would like to avoid (`bevy_utils` is slowly being split up, for example). See here for its current API surface: https://docs.rs/bevy_core/latest/bevy_core/

## What solution would you like?

We should:
- Move `FrameCount` and its plugin to `bevy_diagnostics` or `bevy_window`
- Move other plugins to `bevy_app`
- Move everything else to `bevy_ecs`

## What alternative(s) have you considered?

Leave it as-is.

## Additional context

Related to #11478 and #16877.

[Originally brought up on the Bevy Discord.](https://discord.com/channels/691052431525675048/692572690833473578/1319072745010761749)

### PR DESCRIPTION
**Pull request by bushrat011899**
# Objective

- Fixes #16892

## Solution

- Removed `TypeRegistryPlugin` (`Name` is now automatically registered with a default `App`)
- Moved `TaskPoolPlugin` to `bevy_app`
- Moved `FrameCountPlugin` to `bevy_diagnostic`
- Deleted now-empty `bevy_core`

## Testing

- CI

## Migration Guide

- `TypeRegistryPlugin` no longer exists. If you can't use a default `App` but still need `Name` registered, do so manually with `app.register_type::<Name>()`.
- References to `TaskPoolPlugin` and associated types will need to import it from `bevy_app` instead of `bevy_core`
- References to `FrameCountPlugin` and associated types will need to import it from `bevy_diagnostic` instead of `bevy_core`

## Notes

This strategy was agreed upon by Cart and several other members in [Discord](https://discord.com/channels/691052431525675048/692572690833473578/1319137218312278077).

### CODE REVIEW

**Comment by bushrat011899** [comment]
I've marked this as `X-Blessed` based on Cart's approval of my proposal, but please remove it if that's inappropriate!

**Review by aevyrie — APPROVED** [review]
Probably worth noting the path change to `Name` for people migrating their scene files.

**Comment by ItsDoot** [comment]
> Probably worth noting the path change to `Name` for people migrating their scene files.

That should be covered by the migration guide in #16894

**Comment by bushrat011899** [comment]
> Probably worth noting the path change to `Name` for people migrating their scene files.

Yeah as @ItsDoot mentioned it's covered by #16894's migration guide. I just missed this instance and it slipped through CI, so I fixed it here since it's somewhat related.

**Pull request merged**
