### PR TITLE
[Merged by Bors] - Don't bundle extra transform with camera in many sprites examples

### LINKED ISSUE #6077: many_sprites and many_animated_sprites examples are broken
## Bevy version

main, since cd15f0f5be040b95da84f99391afbb2214fea4b8

caught by https://rparrett.github.io/prototype_bevy_example_runner/

## What you did

```
cargo run --example many_sprites
cargo run --example many_animated_sprites
```

## What went wrong

A transform and a transform-containing bundle were both bundled together.

```
2022-09-23T14:40:34.889320Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, backend: Metal }
thread 'main' panicked at 'Bundle (bevy_core_pipeline::core_2d::camera_2d::Camera2dBundle, bevy_transform::components::transform::Transform) has duplicate components', crates/bevy_ecs/src/bundle.rs:723:5
```

### PR DESCRIPTION
**Pull request by Carlrs**
Fixes #6077 
# Objective

- Make many_sprites and many_animated_sprites work again

## Solution

- Removed the extra transform from the camera bundle - not sure why it was necessary, since `Camera2dBundle::default()` already contains a transform with the same parameters.

---

### CODE REVIEW

**Comment by rparrett** [comment]
Thanks for picking this up! A couple notes:

- The tuple (extra set of parens) is no longer needed
- We still want to set the z value of the camera's transform. You can do something like

```rust
Camera2dBundle {
    transform: Transform::from_xyz(0., 0., 1000.),
    ..default()
}
```

**Comment by rparrett** [comment]
Could you move the "Fixes" note to the body of the PR? I don't think the issue got linked properly.

**Comment by Carlrs** [comment]
Should be linked properly now and I removed the extra parens as well.

**Review by alice-i-cecile — APPROVED** [review]
Thanks!

**Review by rparrett — APPROVED** [review]

**Review by afonsolage — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Once merge conflicts are resolved @Carlrs I'll merge this in :)

**Review by devil-ira — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Ah, gotta fix the new deprecation notice :)

**Pull request closed without merging**
