### PR TITLE
rename Commands to DeferredCommands

### LINKED ISSUE #5913: Commands is poorly communicated to new users
## How can Bevy's documentation be improved?

I've had to tell new users that things done through Commands don't apply until the end of the stage tens of times. I'm fine with that, but it does indicate to me that there's something about the Commands documentation or API that is misleading to new users, and I'm not sure if it'd take a rethinking of how the Commands API is named, or just more obvious documentation of this, but I thought I'd bring it up because I do see it as a general communication issue with Bevy right now.

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Fix #5913

## Solution

- rename `Commands` to `DeferredCommands`

---

## Migration Guide

- rename `Commands` to `DeferredCommands`

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I think this is the right call. This is an essential part of the mental model, and one of the biggest barriers for new users learning Bevy. The verbosity is worth it.

**Comment by alice-i-cecile** [comment]
(Added the Controversial label due to the high user-facing impact)

**Comment by mockersf** [comment]
@DJMcNab could you explain what you would want from a RFC? This PR has no design at all, it's "just" changing the name to match the current design

**Comment by DJMcNab** [comment]
Hmm, perhaps an RFC doesn't quite express it.

I was just wanting to note that this needs much wider input from the community than just a controversial PR imo. It's a breaking change which breaks what, half of all systems, for what is in my opinion a fairly niche reason.

Imo, the name Commands already has an implication of being deferred, as it is an inert list of commands. If we're wanting the name to contain the word deferred, I'd advice to find another word, perhaps `WorldOperations` (since brevity is clearly not a concern)

(Also your pr description missed out that you added a deprecated type alias of `Commands` to `DeferredCommands`, which I assume you must have done. I can't verify that because this pr is too big to check that on mobile)

**Comment by djeedai** [comment]
I'm strongly against that. I agree with @DJMcNab that "the name Commands already has an implication of being deferred". That rename is just more verbose for the same thing. We can likely improve the documentation to make it plain clear _when_ those commands are executed, but renaming `Commands` will not make it less immediate than already implied. After all, why would we have a set of commands if we could just execute some code immediately? Plus, `DeferredCommands` implies the existence of some `ImmediateCommands`, which obviously cannot exist. And if users don't understand when commands are executed, even if they get they're deferred, they will likely misuse them anyway, so the problem is not limited to being deferred but to teaching user the command workflow and the ECS architecture in general.

**Comment by Nilirad** [comment]
Introducing such a big change for an issue i just heared about is not a good idea IMO. Also, renaming `Commands` would create merge conflicts in so many open PRs. I don't think that just doing a rename will fix #5913. It's more on how we communicate the big picture to the users (i.e. the book, that we don't have)

I'll try to make the API docs for `Commands` clearer by adjusting the wording here and there and adding some links.

**Comment by alice-i-cecile** [comment]
>  DeferredCommands implies the existence of some ImmediateCommands, which obviously cannot exist

This convinced me; I don't think I like this rename. I definitely agree that this is one of the most serious teaching issues though.

**Comment by mockersf** [comment]
> Plus, DeferredCommands implies the existence of some ImmediateCommands, which obviously cannot exist

Actually, all commands are immediate by default. Creating them through `Commands` is what make them to be deferred

**Comment by Nilirad** [comment]
I think the deferred nature of `Commands` is implied not by the root of the noun but by its plurality.

However, if we really want to change the name, `CommandQueue` is much more descriptive than `DeferredCommands`.

**Comment by nicopap** [comment]
I want to point out that "Deferred" may also imply "applies at the end of the function" (for example: as in Go's `defer` keyword) It's still completely implicit that the commands are only applied at the end of the stage _after_ other systems may have ran. I'm not fundamentally against a change like this (although I think it needs more community involvement) but I don't think the "Deferred" wording is enough for disambiguation.

I'd suggest "StageCommand" if stageless wasn't around the corner, so I'm out of constructive feedback :sweat_smile:

**Comment by Nilirad** [comment]
~~`PendingCommands`~~

Btw, I just like `Commands`, nice and simple once you understand where it fits in the ECS.

**Comment by mockersf** [comment]
> Btw, I just like `Commands`, nice and simple once you understand where it fits in the ECS.

I like `Commands` too, but the issue is that it's "nice and simple". People get the wrong idea from the name, and that leads to hard to debug issues. And that can't be fixed by docs, because people don't read the docs of something that is "nice and simple".

**Comment by Nilirad** [comment]
So your point seems to be that the `Commands` name is too simplistic and therefore misleading to some new users. That's a fair point.

However, I still think that the new name `DeferredCommands` doesn't help much. The only benefit it has is that it creates enough insecurity in the user to the point that they may end up consulting the documentation or asking for help before introducing a bug in their code. This may also constitute an entry barrier to new users: with `Commands` they have a partially accurate mental model of its function, while with `DeferredCommands` they have no model at all, since it's impossible to understand what “deferred” means until one knows to what point in time the commands are deferred to.

Some better names could be:

- `CommandQueue`: more descriptive than `Commands`, but it requires us to rename the homonymous struct.
- `CommandBuffer`: in-line with the `apply_buffers` stageless terminology (I didn't follow the last developments, so I'm not completely sure if the name is still that).

**Comment by djeedai** [comment]
I'd avoid overloading the term "buffer". If you _really_ want to rename I'd suggest `CommandStream` rather than `CommandBuffer`; the former also highlights the serialized nature of command execution.

**Comment by cart** [comment]
I do understand the rationale, and I appreciate that we're having this conversation. But I'm also against this change (or anything that adds an additional qualifier). My only argument is that `Commands` is shorter and simpler:

```rust
fn system(mut deferred_commands: DeferredCommands) {
}

fn system(mut commands: Commands) {
}
```

(yes I renamed the variable too, as that is generally the naming convention we encourage. if you want to argue that we should shorten it to `commands` because it takes up too much space and is harder to type, then you're already arguing against your own point)

As others have mentioned, Commands are in something like half of systems. Thats a lot of extra "space" being taken up (more typing, higher likelihood of going past the clippy line length threshold, resulting in the system params each having their own newline, consuming extra vertical space, more letters to visual read + parse, etc). Yes, autocomplete will help _sometimes_, but that hinges on the prelude already being imported, the user being willing to page through / refine the various suggestions, RA actually being primed and ready to go, etc. For _most_ types I'm willing to trade terseness for clarity, the more uncommon they are, the more willing I am. But this is a core "concept" and I've very willing to give it a simple / first class short name.

Its the same reason we use `ResMut<Time>` instead of `ResourceMut<Time>` and `Query<&T>` instead of `WorldQuery<&T>`. Yes newbies might not know what `ResMut` means or what the context of `Query` is, but the terseness is worth it for such a core concept.

**Comment by mockersf** [comment]
> I do understand the rationale, and I appreciate that we're having this conversation. But I'm also against this change (or anything that adds an additional qualifier). My only argument is that `Commands` is shorter and simpler:

So... your only constraint would be to find a word shorter than `Commands` 😄 

I didn't rename the variable name everywhere because I didn't expect to find the right name right away, but I agree that it should follow the name of the struct. I don't have a good idea for the perfect name, but then I'm not that good at naming things, even less in English. All suggestions seems to build on `Command`, so not sure a good idea will pop up for something shorter.

**Comment by cart** [comment]
> If Commands does evoke something that doesn't happen immediately for enough people, let's keep it I guess. But I feel the argument "oh it's plural, so obviously it happens at the end of the stage" may be a little weak.

I definitely wouldn't argue that the plural-ness of Commands implies end-of-stage application. I think `Commands` implies a collection of `Command` impls, nothing more. The core of my argument is that trying to express how and where the Commands are applied in the type itself inserts too much context into the boilerplate of system declaration. The clarity / extra context _is_ useful (especially for newbies), but I don't think its useful enough to offset re-establishing that context repeatedly for every system. And even qualifiers like "Deferred", "Queue", etc don't tell the whole story (when is it deferred to? When is the queue applied?).  Imo the "commands are deferred until the end of a stage" context is something you should learn once as part of learning Bevy, not something you should repeat like a mantra in every system. Its also worth nothing that in the future this context might change: with "stageless scheduling" commands will be applied at the next "flush" system (and in the future might be applied implicitly in a way that respects "hard" dependencies between systems). 

That being said, there is no "right" answer here. This type of naming is an art. Everyone will have a different opinion about how to balance all of the variables. I fully acknowledge that the `DeferredCommands` name solves real problems, I just don't personally think its the optimal solve of all constraints. I'm happy to discuss / leave this open / wait for other opinions, but my opinion is relatively fixed at this point.

**Comment by mockersf** [comment]
Closing until I find the perfect name. Feel free to help if you have ideas!

**Pull request closed without merging**
