### PR TITLE
Fixing text sizes for examples

### LINKED ISSUE #14265: Various examples need their font sizes adjusted post-`cosmic-text`
## Bevy version

main, after #10193

## Additional information

See this run from [`bevy-example-runner`](https://thebevyflock.github.io/bevy-example-runner/):
<https://pixel-eagle.com/project/b25a040a-a980-4602-b90c-d480ab84076d/run/3207/compare/3196?screenshot=UI%20(User%20Interface)/transparency_ui.png>

Bevy's default font size and a few examples were updated to compensate, but some examples where the a font size other than the default was specified now may need to be updated.

Dividing the font size by `1.2` and rounding to the nearest whole number will give rendered text roughly the same size as before.

One of the more obvious examples is `transparency_ui`, where the text no longer fits on one line:

image

We should 
- look through the Pixel Eagle report
- note examples where the font size has significantly changed
- make a judgment about whether to
  - divide the specified font size by `1.2`ish.
  - OR, modify the example to use the default text size (and possibly color) instead.
    There are various examples where we probably should be using the default values but we are not. e.g. `low_power`.

### PR DESCRIPTION
**Pull request by tjlaxs**
# Objective

- Fixes #14265

## Solution

- Go through Pixel Eagle examples (and examples all in all)
- If default size is used it is usually left there
- If size of font is touched try dividing with 1.2 and round it to nearest whole number

## Testing

- Run example before and after
- Make sure examples text are readable or like before cosmic-text change

---

## Showcase

Before:
image

After:
image

### CODE REVIEW

**Comment by tjlaxs** [comment]
Mostly tiny changes like that the text fits better in buttons, with some exceptions like `transparency_ui`. And then larger problems like the `text_debug` example.

**Comment by rparrett** [comment]
Cross-referencing a list I made, could you double-check these?

```
borders
low_power
multiple_windows
render_ui_to_texture
stepping
text
ui
ui_scaling
```

**Comment by tjlaxs** [comment]
Rechecking these:
- [ ] borders
- [ ] low_power
- [ ] multiple_windows
- [ ] render_ui_to_texture
- [ ] stepping
- [ ] text
- [ ] ui
- [ ] ui_scaling

And was so confused with the `text_debug` problems example that I had made all of the fonts the exact same size, might change these back to show better way of different font sizes in the case.

**Comment by tjlaxs** [comment]
- Borders and low_power had been fixed/touched elsewhere and were already fine
- Multiple windows and render_ui_to_texture looked fine there is a font size change but nothing drastic and default size is used
- Stepping isn't an example but is used in the breakout example but did fix the font size for it
- Had forgotten text example some how, but will fix them with text_debug
- Examples ui and ui_scaling still need changes

Will do these changes now.

Sidenote... second time around, I seem to understand better what the examples are trying to show.

**Comment by tjlaxs** [comment]
Now the text_debug font sizes don't match the Pixel-Eagle images, but the size changes were newer than the cosmic-commit. So I guessed these were the correct ones.

**Review by alice-i-cecile — APPROVED** [review]

**Review by rparrett — APPROVED** [review]

**Pull request merged**
