### PR TITLE
Keyboard modifiers

### PR DESCRIPTION
**Pull request by blunted2night**
This patch add tracking of keyboard the ctrl, alt, shift & the "logo" modifier keys. The window_settings example is updated to support toggling full screen mode with the 'alt+enter' chord.

### CODE REVIEW

**Comment by amberkowalski** [comment]
I might be missing something, but I'm not sure if I understand the purpose of this. Isn't it possible to check the current keyboard modifiers with the current input infrastructure?

**Comment by blunted2night** [comment]
I poked around in the input handling code and didn't see anything. It looks to me that bevy's keyboard input handling is a thin wrapper around winit's, and this part was unimplemented.

**Comment by amberkowalski** [comment]
Using `Input<KeyCode>` you can do
```
if input.pressed(KeyCode::LControl) && input.pressed(KeyCode::V) {}
```
Why does bevy need a dedicated system for determining modifier key presses? I'm not attacking the system, I just want a nice solid reason to believe in it.

**Comment by smokku** [comment]
It may not be plain obvious, but Bevy indeed does have this feature.

Take a look here: https://gist.github.com/smokku/c5598d32092141c65cbf53821cb1aeb0#file-megaui-rs-L218
```rust
fn process_input(
    keyboard_input: Res<Input<KeyCode>>,
) {
    let shift = keyboard_input.pressed(KeyCode::LShift) || keyboard_input.pressed(KeyCode::RShift);
    let ctrl = keyboard_input.pressed(KeyCode::LControl) || keyboard_input.pressed(KeyCode::RControl);
```

**Comment by blunted2night** [comment]
My bad, I looked for those, and some how missed them.

While looking at winit to figure this patch out there was a comment to the effect that having the separate `ModifiersChanged` event was important. This is because the tracking of press/release messages are not reliable due to the potential of keyboard focus changing. Of course that would also apply to the `Input<KeyCode>`  which I guess we are just assuming wont happen.

Given this, I agree that this PR should probably not be merged, though I will leave open a little longer to see of there are any other opinions.

**Comment by cart** [comment]
No worries! ModifiersChanged seems like a reasonable implementation, but I do think that using Input<KeyCode> is simpler (and therefore preferable). Less code is also better.

Thanks for exploring this idea!

**Pull request closed without merging**
