### PR TITLE
Additional options to mesh primitives

### PR DESCRIPTION
**Pull request by ManevilleF**
# Objective

Add new options to some primitives, like anchoring for Cones and cylinders and custom angle ranges for Torus.
I think these kind of options are useful, but I would understand that these addition feel overkill

## Solution

Add 

## Testing

- Did you test these changes? If so, how?

> I used the new options in the `3d_shapes` example with various parameters and got the expected results

## Changelog

- Added `caps` bool option to toggle cylinder circle caps
- Added `angle_range` f32 range option non full torus shapes
- Added `anchor` enum option for cylinders,  with either `Top`, `Midpoint` or `Bottom`
- Added `anchor` enum option for cones, with either `Tip`, `Midpoint` or `Base`
- **BREAKING** `TorusMeshBuilder` is no longer `Copy` due to `RangeInclusive`, we can use a `(f32, f32)` if we want it to be `Copy`

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I think these are useful. If we're letting folks build meshes out of our shapes, the API should reasonably accommodate things users might want to do.

**Review by Olle-Lukowski — APPROVED** [review]
Looks good to me, useful changes. One thing though, we might want to provide an example for the new options, but probably in another PR.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
This is well-documented and I like the overall API.

**Comment by ManevilleF** [comment]
> Looks good to me, useful changes. One thing though, we might want to provide an example for the new options, but probably in another PR.

We could add a second row of shapes with various options but I think these would fit better in a manual with some screenshots

**Pull request merged**
