### PR TITLE
KeyCode::key_char

### PR DESCRIPTION
**Pull request by stepancheg**
# Objective

To implement basic (e.g. self-debugging) text input using bevy without extensions, some code is needed to convert keys to text.

## Solution

`KeyCode::key_char` does naive conversion of keys to chars, for example for `KeyCode::Key1` without shift it returns `'1'` without shift and `'!'` with shift.

### Added

- `KeyCode::key_char` function to map from keycode to Rust `char`

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
@Vrixyz how compatible is this with the upcoming `winit` changes?

**Comment by Vrixyz** [comment]
I'd say the concept is compatible with the winit update, it's a helper function over our KeyCode, owned by bevy_input and not bevy_winit.

If this PR is accepted, winit PR will have to rewrite most of its KeyCode mappings due to their changes, but it would be a minor conversion.

**Comment by Vrixyz** [comment]
That being said, such conversions are highly "debugging level", I'm curious why provide mapping over shift modifier, and not alt/ctrl ? I'm curious of a practical use case which wouldn't be covered by Debug (or a simpler key_char mapping without shift, where the user has to combine with shift modifier by the user

**Comment by rlidwka** [comment]
> `KeyCode::key_char` does naive conversion of keys to chars

Is there a non-naive conversion? What would it look like? Do we want to have it?

*Just want to make sure we aren't introducing a bad practice here, which would break code for users with different keyboard layouts.*

**Review by rlidwka — CHANGES_REQUESTED** [review]
1. I suggest to rename `KeyCode::key_char()` to something that reflects the fact that it works in specific keyboard layout (for example, `KeyCode::in_us_layout()`).

2. Please add documentation that clarifies, for all the people who have `Res<Input<KeyCode>>` in their code and want to get actual (layout-dependent) symbol typed by the user, how to change their code to do so. Otherwise, they are going to use this method and do the wrong thing.

**Comment by stepancheg** [comment]
> KeyCode::in_us_layout()

This wouldn't be 100% correct, but OK.

> Please add documentation that clarifies, for all the people who have Res<Input<KeyCode>> in their code and want to get actual (layout-dependent) symbol typed by the user, how to change their code to do so

I can do small improvement like this PR, or I can abandon this PR if you think this is not improvement. I cannot afford to spend hours researching this topic.

> Otherwise, they are going to use this method and do the wrong thing.

In my subjective opinion, being able to do somewhat incorrect thing is better than not being able to do it at all.

**Comment by stepancheg** [comment]
Renamed.

**Comment by mockersf** [comment]
keyboard event from winit 0.29 is https://docs.rs/winit/0.29.3/winit/event/struct.KeyEvent.html
This can be updated to work on the next version of the key code, but it will be duplicated and less correct than what is provided by winit, which will give the actual text according to the keyboard layout

**Pull request closed without merging**
