### PR TITLE
Implement methods to list all components and all resources

### LINKED ISSUE #3007: Simple methods to list all components and all resources
## What problem does this solve or what need does it fill?

Having a list of all resources or all components is useful for debugging purposes.
This will be particularly valuable in the editor.

## What solution would you like?

~~Add a `Resources` system parameter.

On both the `Components` and `Resources` system parameter, implement `Iter`, returning `ComponentInfo` as the item.~~

EDIT: this has been fixed for resources by https://github.com/bevyengine/bevy/pull/12829, but an equivalent for components is still missing.

## What alternative(s) have you considered?

Right now, you can use the complex method listed in https://bevy-cheatbook.github.io/cookbook/print-resources.html for resources, but no such obvious method exists for components.

Blindly check component IDs from `Components` by trying all of the `usize` options (or hoping they're strictly contiguous and start at 0). 

[`World::inspect_entity`](https://docs.rs/bevy/latest/bevy/ecs/prelude/struct.World.html#method.inspect_entity) can be used to inspect all of the components of a *specific* entity, and was added in #5136.

## Additional context

https://github.com/bevyengine/bevy/pull/15435 improves this situation for query errors and could be helpful inspiration.

### PR DESCRIPTION
**Pull request by sseemayer**
# Objective

- Fixes #3007
- Simplify debugging by allowing iteration over all `Component`s and `Resource`s registered in a `World`.

## Solution

- [x] Rename `Components` into `WorldData` to reflect that it stores metadata both on `Component`s and `Resource`s. Also rename   `ComponentId` to `DataId`, `ComponentInfo` to `DataInfo` and `ComponentDescriptor` to `DataDescriptor`
- [x] implement `IntoIterator` for `WorldData` to iterate over all components and resources
- [x] create a new `Components` system descriptor and implement `IntoIterator` to iterate over all components
- [x] create a new `Resources` system descriptor and implement `IntoIterator` to iterate over all resources

### CODE REVIEW

**Review by inodentry — APPROVED** [review]
This all looks good to me.

I really like the "component" -> "data" rename. It makes so much more sense this way. I previously found it confusing that bevy ecs uses the term "components" to refer both to the user-facing concept and api (distinct from "resources") and the internal backing storage for all data (including resources). They are separate things and deserve distinct names.

And, being able to iterate "all components", "all resources", and "all data"/both, is obviously also very useful.

**Comment by alice-i-cecile** [comment]
@sseemayer I'm interested in merging this; can you please rebase?

**Comment by KevinKeyser** [comment]
Would it be okay with either of you if I open a PR for this rebased on main? @alice-i-cecile @inodentry 
This would be my first PR, but the work I put in already passes all the CI checks on my fork.

**Comment by alice-i-cecile** [comment]
@KevinKeyser Yes please! That's the intent behind the `Adopt-Me` label :) And I've wanted this functionality for ages.

**Pull request closed without merging**
