### PR TITLE
[Merged by Bors] - Sprites - keep color as 4 f32

### LINKED ISSUE #4356: ClearColor and Sprite same value yields different color
## Bevy version

Bevy 0.6.1

## Operating system & version

Pop!_OS 21.10 x86_64

## What you did
Set a sprite and the background to the same rgb value
```rust
use bevy::prelude::*;

const BG_COLOR: Color = Color::rgb(0.16, 0.16, 0.16);

fn main() {
    App::new()
        .insert_resource(ClearColor(BG_COLOR))
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn_bundle(OrthographicCameraBundle::new_2d());

    commands.spawn_bundle(SpriteBundle {
        sprite: Sprite {
            color: BG_COLOR,
            custom_size: Some(Vec2::new(50.0, 50.0)),
            ..Default::default()
        },
        ..Default::default()
    });
}
```

## What you expected to happen

The rectangle sprite should be indistinguishable from the background.
Only one color should be visible.

## What actually happened

The sprite (center) renders *slightly* darker than the background.

image

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Fix #4356

## Solution

- Do not reduce the color of sprites to 4 u8

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I think this is a better solution than rounding. Color consistency and accuracy is better than the very small performance win.

**Review by cart — APPROVED** [review]
Yeah I think this is the move. I'll hold off on merging just to give some space for dissenting opinions.

**Comment by alice-i-cecile** [comment]
Ping @bevyengine/rendering-team for quick opinions on this :)

**Comment by bytemuck** [comment]
This is the way to go IMO.

**Comment by rparrett** [comment]
Should `mesh2d_manual` get the same treatment?

If so are `as_rgba_u32` and `as_linear_rgba_u32` still useful to keep around?

**Review by HackerFoo — APPROVED** [review]

**Comment by HackerFoo** [comment]
This would probably be a good place to use FP16 in the future: https://github.com/gpuweb/gpuweb/issues/658

**Comment by mockersf** [comment]
> Should `mesh2d_manual` get the same treatment?

This examples needs to use a `u32` as the attribute for mesh color is marked as `Uint32`:
https://github.com/bevyengine/bevy/blob/63fee2572b017deb9edcfd110bdcedc50c5153f7/crates/bevy_render/src/mesh/mesh/mod.rs#L74-L76

It could change there too, but I don't know if there was another reason there for it to be `u32`

**Comment by CptPotato** [comment]
I prefer this fix over #4357 👍 

An alternative would be passing the color using `4 x u8` (as before) but encoded using SRGB color and then doing the transform back to linear in the shader. But I think `f32`/`f16` is the better option as this would also work with higher bit depths and unclipped colors, which allows brightening sprites and will work with HDR.

Regarding the vertex color, it makes sense to me to keep them compressed as `u32` in my opinion, since switching to `4 x f32` would increase the memory required per vertex quite a bit.
I haven't tested the vertex colors, but I think they probably have the same precision issue. Maybe doing the SRGB encoding I mentioned above makes sense for the vertex attributes in the future?

**Comment by inodentry** [comment]
I was originally one of the proponents of this idea to "compress" the color into a `u32`. In retrospect I think I am now convinced that it was over-optimizing, trading off correctness and support for some valid use cases, for a drop of performance. I agree with this PR that we should not do that anymore. :)

The current sprites renderer was designed with WebGL2 limitations in mind. If we really want performance gains for sprites rendering, we should look into having a fast path (using storage buffers and vertex pulling, or other such render techniqes) for platforms that aren't so limited, and leave the current implementation as a fallback for platforms that don't support it. That would be much more beneficial, than trying to "micro-optimize" the individual struct fields.

**Comment by cart** [comment]
Sound like we have consensus!

**Pull request closed without merging**
