### PR TITLE
[Merged by Bors] - Add writing of scene data to Scene example

### PR DESCRIPTION
**Pull request by wanderrful**
# Objective

Alice says to make this PR: https://discord.com/channels/691052431525675048/745805740274614303/1018554340841107477

- The "scene" example in the examples folder has a TODO comment about writing the serialized data to a file. This PR implements that.

## Solution

The `AssetIo` trait in the `AssetServer` only supports reading data, not writing it. So, I used `std::io::File` for the implementation. This way, every time you run the example, it will mutate the file in-place.  

I had thought about adding a UUID string to the example Component, so that every time you run the example, the file will be guaranteed to change (currently, it just writes the same numbers over and over). However, I didn't bother because it was beyond the scope of the TODO comment.

One thing to note is that the logic for serializing the scene into RON data has changed since the existing RON file was created, and so even though the data is the same, it's rendered in a different order for whatever reason.

I left the changed output to the example file, because it's presumably trivial.  I can remove it and force-push if you don't want that included in here.

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Thanks! IMO we should write the scene to a new file to avoid altering the loaded data (and gitgnore the generated file).

**Review by alice-i-cecile — APPROVED** [review]

**Review by devil-ira — APPROVED** [review]

**Comment by mockersf** [comment]
This is a bad idea, and we should really not show usage of a blocking api (file writing) in a system.

**Comment by wanderrful** [comment]
@mockersf What alternative do you suggest for this use case?

**Comment by mockersf** [comment]
ideally, the asset server should be able to write assets...

But for now, we can just wrap it in a task: #5952

**Pull request closed without merging**
