### PR TITLE
Rename `Input` to `ButtonInput`

### LINKED ISSUE #10853: `Input` name is too generic
`bevy_input` contains a struct called [`Input`][1] which refers to any kind of "pressable input". The problem is that `Input` is too generic, since there are other kinds of input like axis input, that do not fit into there, misleading users that have not yet read the documentation.
`Input` should be renamed to something more specific.

This may have the drawback of a longer name, but personally I don't mind since it's not a thing that's used everywhere, so it's worth it to be more specific IMO.

[1]: https://dev-docs.bevyengine.org/bevy/input/struct.Input.html

### PR DESCRIPTION
**Pull request by matiqo15**
# Objective

- Resolves #10853 

## Solution

- ~~Changed the name of `Input` struct to `PressableInput`.~~
- Changed the name of `Input` struct to `ButtonInput`.

## Migration Guide

- Breaking Change: Users need to rename `Input` to `ButtonInput` in their projects.

### CODE REVIEW

**Comment by ItsDoot** [comment]
What about `DigitalInput` instead? Slightly more succinct.

**Comment by Nilirad** [comment]
> What about `DigitalInput` instead? Slightly more succinct.

Would `BinaryInput` be more immediate? 🤔

**Comment by alice-i-cecile** [comment]
I like `Pressable` much better: it more clearly captures the intent and is more approachable for beginners.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
I would like a `Pressable` marker trait to go with this eventually, but that can wait until it's better motivated. See https://github.com/Leafwing-Studios/leafwing-input-manager/issues/321 for the broader context there.

**Comment by stepancheg** [comment]
Maybe `ButtonInput`. Not precisely correct, but conveys the meaning. My 2 cents.

**Comment by Nilirad** [comment]
> I would like a `Pressable` marker trait to go with this eventually, but that can wait until it's better motivated. See [Leafwing-Studios/leafwing-input-manager#321](https://github.com/Leafwing-Studios/leafwing-input-manager/issues/321) for the broader context there.

Do you mean something like #10855?

**Comment by ickshonpe** [comment]
> Maybe `ButtonInput`. Not precisely correct, but conveys the meaning. My 2 cents.

Much prefer this, `PressableInput` is a bit ugly and `DigitalInput` is too obscure.

**Comment by alice-i-cecile** [comment]
Let's go with `ButtonInput` then and get this merged :)

**Pull request merged**
