### PR TITLE
#![forbid(rustdoc::broken_intra_doc_links)]

### PR DESCRIPTION
**Pull request by stepancheg**
Safer this way.

### CODE REVIEW

**Comment by hymm** [comment]
This should probably wait for https://github.com/bevyengine/bevy/pull/10011 and then use workspace lints.

**Comment by alice-i-cecile** [comment]
On board with this, but swap it to a warn and do it at the workspace level like WrongShoe said :)

**Comment by stepancheg** [comment]
> swap it to a warn 

It is warn by default. So when I run `cargo doc`, it just prints a warning which is too easy to overlook.

**Comment by mockersf** [comment]
CI will already fail on doc warnings, no need to forbid it

**Comment by alice-i-cecile** [comment]
Let's leave it as is then.

**Pull request closed without merging**
