### PR TITLE
Compile multiple run conditions into one

### PR DESCRIPTION
**Pull request by JoJoJet**
# Objective

When multiple run conditions are attached to a system, they should be compiled together as one function.

## Solution

Add a variant of `System{Set}Config` that preserves the types of run conditions and combines them with any newly-added ones. This allows the compiler to inline them into one function.

This optimization is performed opportunistically -- run conditions that have already been boxed and type erased are not combined, as there is no benefit to doing so. This means that structs that perform type erasure such as `SystemConfig` present a barrier for this optimization. Resolving this should be possible in the future, but it would require a much higher-impact change that involves preserving the type data for all `SystemConfig` instances.

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
I don't love adding more complexity here, but the aim is valuable. Great comments!

Requests:

1. Add a matching `Either` combinator (to avoid mangling `Or` from queries).
2. Add doc tests to both `Either` and `And`.
3. Add links to both `Either` and `And` from the `Condition` docs. `not` from #7559 would be nice to mention there too.

**Comment by JoJoJet** [comment]
> 1. Add a matching `Either` combinator (to avoid mangling `Or` from queries).

I'm assuming you want this in order to satisfy #7584 -- however the `And` combinator I've added here intentionally doesn't short-circuit, so it won't resolve that issue. Instead of building on the `And` type by adding `Either`, I think it would be better to keep `And` an implementation detail and make it `#[doc(hidden)]`.

I am working on another PR that would satify #7584, though.

**Comment by alice-i-cecile** [comment]
Okay great, I'm fine to cut 1 from this PR :)

**Comment by JoJoJet** [comment]
I'm taking this off of the milestone if that's okay, since 0.10 is so close and this is just a nice-to-have optimization.

**Comment by JoJoJet** [comment]
Closing this since it's out of date, and I don't consider this to be high enough priority to get it working again.

**Pull request closed without merging**
