### PR TITLE
[Merged by Bors] - Update tracing-subscriber requirement from 0.2.22 to 0.3.1

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Fix #3058 opened by dependabot

## Solution

- A new feature need to be added to `tracing-subscriber`

### CODE REVIEW

**Comment by mockersf** [comment]
this still need to wait on `tracing-wasm` updating their dependency on `tracing-subscriber`: https://github.com/storyai/tracing-wasm/pull/18

**Comment by colelawrence** [comment]
Updated tracing-wasm to `0.2.1`. Please check.

**Comment by mockersf** [comment]
simpler fix that should get something working now: https://github.com/bevyengine/bevy/pull/3102

**Comment by mockersf** [comment]
`tracing-chrome` updated https://github.com/thoren-d/tracing-chrome/pull/4 
`tracing-tracy` waiting on https://github.com/nagisa/rust_tracy_client/pull/27

**Comment by mockersf** [comment]
CI seems to say that all dependencies using `tracing-subscriber` are now updated 🎉

**Comment by cart** [comment]
Brilliant! Lets give it a go!

**Pull request closed without merging**
