### PR TITLE
[Merged by Bors] - Remove unnecessary exceptions for wgpu

### PR DESCRIPTION
**Pull request by TheRawMeatball**

### CODE REVIEW

**Comment by mockersf** [comment]
why do you think they are unnecessary?

**Comment by TheRawMeatball** [comment]
Should've clarified :sweat_smile: : they'll soon be unnecessary, as https://github.com/gfx-rs/wgpu/pull/1516 will remove the need for it.

**Comment by TheRawMeatball** [comment]
Wgpu 0.9 has dropped with the new license!

**Comment by mockersf** [comment]
Could you also do the update to wgpu 0.9 in this PR? It would be best to remove exceptions and update in the same PR otherwise CI will be broken between the two

**Comment by mockersf** [comment]
to be done after #2371

**Review by alice-i-cecile — APPROVED** [review]
Looks like upstream got merged; we can merge this in now @mockersf.

**Review by MinerSebas — APPROVED** [review]

**Review by DJMcNab — APPROVED** [review]
🎉 
Just @Cupnfish for https://github.com/OptimisticPeach/hexasphere/issues/7 remaining

**Comment by bjorn3** [comment]
They just responded.

**Comment by mockersf** [comment]
@TheRawMeatball could you resolve the conflicts ?

**Pull request closed without merging**
