### PR TITLE
deleted redundant example sampling_primitives.rs

### LINKED ISSUE #15823: Are the `random_sampling` and `sampling_primitives` examples redundant?
## Bevy version

main

## What you did

`cargo run --example random_sampling`
Added in #13507

`cargo run --example sampling_primitives`
Added in #13519

## What went wrong

These examples appear to be extremely similar, and their docs even have identical descriptions.

```
//! This example shows how to sample random points from primitive shapes.
```

## Additional information

It appears that this isn't a mistake, so I would suggest updating the description of either or both examples to explain what each of them is accomplishing.

But they seem totally redundant to me, so removing one may be an option.

### PR DESCRIPTION
**Pull request by I-Ruiz**
# Objective

- Deleted example sampling_primitives.rs 
- Fixes #15823

## Solution

- delete sampling_primtives

## Testing

- No testing
- Alice voted redundant

---

### CODE REVIEW

**Comment by BenjaminBrienen** [comment]
You need to remove the declaration of the example from the Cargo.toml and probably regenerate the templated README.md.

**Review by BenjaminBrienen — CHANGES_REQUESTED** [review]
Missing Cargo.toml edit

**Comment by I-Ruiz** [comment]
Update: deleted sampling_primitives references in Cargo.toml

**Comment by alice-i-cecile** [comment]
Duplicated in #16453.

**Pull request closed without merging**
