### PR TITLE
Added custom node rendering example

### PR DESCRIPTION
**Pull request by Lindenk**
# Objective

Provide the fruits of my keyboard mashing as an accessible example for creating a custom rendering node.

## Solution

Provides a well commented and (hopefully) idiomatic example for creating a rendering node and adding it to a node graph.

### CODE REVIEW

**Comment by DJMcNab** [comment]
I think it would be useful to have a screenshot/video of what this example produces here.

**Comment by Lindenk** [comment]
Here you are. I went with something that uses the resolution from `ExtractedView`, a simple implementation for extracting `Time`, and the color is extracted from a custom node attached to the camera. I feel like that should provide decent coverage for what a user might want to do
custom_node

**Comment by Lindenk** [comment]
I'm also a little unsure how to fix the `check_bans` check. It seems to pass on my end

**Review by djeedai — COMMENTED** [review]
My 2c is that it's a unique occasion to explain what a render world is, the extraction process, etc. All these things that should be documented but are not. Instead, I don't really see the difference between this example and reading the internal code for e.g. sprite or UI rendering. So I'd suggest to add a lot more comment not only on what is going on but first and foremost why, and how the general process of adding a render node works.

**Comment by Nilirad** [comment]
This PR adds a new example. Adding module and item level doc comments, as described in:

- #3951 and
- #4438,

would be really useful to those who will browse examples.

**Comment by IceSentry** [comment]
Most of this is now covered by the post_processing example.

A more targeted example like this might still be useful but this PR is now very outdated to the point I believe it should just be started from scratch.

**Pull request closed without merging**
