### PR TITLE
[Merged by Bors] - remove component and resource suffixes from reflect structs

### PR DESCRIPTION
**Pull request by oliverpauffley**
# Objective

Remove suffixes from reflect component and resource methods to closer match bevy norms.

## Solution

removed suffixes and also fixed a spelling error

---

### CODE REVIEW

**Comment by oliverpauffley** [comment]
Fixes https://github.com/bevyengine/bevy/issues/5202

**Review by alice-i-cecile — APPROVED** [review]
Looks good to me :) Thanks for the contribution!

**Comment by alice-i-cecile** [comment]
Can you put the "Fixes" comment into your PR description? That will cause the issue to get linked and automatically closed.

**Review by MrGVSV — APPROVED** [review]

**Review by PROMETHIA-27 — APPROVED** [review]

**Pull request closed without merging**
