### PR TITLE
Fix `Triangle2d`/`Triangle3d` interior sampling to correctly follow triangle

### PR DESCRIPTION
**Pull request by mweatherley**
# Objective

When I wrote #12747 I neglected to translate random samples from triangles back to the point where they originated, so they would be sampled near the origin instead of at the actual triangle location.

## Solution

Translate by the first vertex location so that the samples follow the actual triangle.

### CODE REVIEW

**Comment by bushrat011899** [comment]
I agree this solves the bug, not sure how I missed it in the initial review! Just as an aside, this function can be made a lot simpler now that I'm looking at it more closely:

```rust
/// Interior sampling for triangles which doesn't depend on the ambient dimension.
fn sample_triangle_interior<P: NormedVectorSpace, R: Rng + ?Sized>(
    [a, b, c]: [P; 3],
    rng: &mut R,
) -> P {
    // Generate random points on a parallelipiped and reflect so that
    // we can use the points that lie outside the triangle
    let u = rng.gen_range(0.0..=1.0);
    let v = rng.gen_range(0.0..=1.0);

    a * (1. - u - v).abs() + b * u + c * v;
}
```

This removes 1 `P`-space vector addition and eliminates the branch, and also includes the fix you've developed. Even without this suggestion, the fix you've provided makes sense and I approve!

**Review by bushrat011899 — APPROVED** [review]

**Comment by mweatherley** [comment]
> I agree this solves the bug, not sure how I missed it in the initial review! Just as an aside, this function can be made a lot simpler now that I'm looking at it more closely:
> 
> ```rust
> /// Interior sampling for triangles which doesn't depend on the ambient dimension.
> fn sample_triangle_interior<P: NormedVectorSpace, R: Rng + ?Sized>(
>     [a, b, c]: [P; 3],
>     rng: &mut R,
> ) -> P {
>     // Generate random points on a parallelipiped and reflect so that
>     // we can use the points that lie outside the triangle
>     let u = rng.gen_range(0.0..=1.0);
>     let v = rng.gen_range(0.0..=1.0);
> 
>     a * (1. - u - v).abs() + b * u + c * v;
> }
> ```
> 
> This removes 1 `P`-space vector addition and eliminates the branch, and also includes the fix you've developed. Even without this suggestion, the fix you've provided makes sense and I approve!

I don't think this is right; when the inside of the absolute value is negative, the sum of coefficients is 2u + 2v - 1, when it should always be 1.

**Comment by bushrat011899** [comment]
Yes you're correct, I gotta stop trying to do maths at midnight. I'd neglected the change in the coefficients of `b` and `c`.

```rust
/// Interior sampling for triangles which doesn't depend on the ambient dimension.
fn sample_triangle_interior<P: NormedVectorSpace, R: Rng + ?Sized>(
    [a, b, c]: [P; 3],
    rng: &mut R,
) -> P {
    // Generate random points on a parallelipiped
    let u = rng.gen_range(0.0..=1.0);
    let v = rng.gen_range(0.0..=1.0);

    // Reflect so that we can use the points that lie outside the triangle
    let (u, v) = if u + v > 1. {
        (1. - u, 1. - v)
    } else {
        (u, v)
    };

    // Ensure coefficients sum to 1
    let t = 1. - u - v;

    a * t + b * u + c * v;
}
```

Still removes the extra vector operation, but definitely more of a style choice than anything else now.

**Review by alice-i-cecile — APPROVED** [review]
I'd like to see tests that our sampling methods always return values inside of the shapes, but I won't block on it here.

**Pull request merged**
