### PR TITLE
Add opt-in spelling-check CI

### PR DESCRIPTION
**Pull request by BlackPhlox**
# Objective

- Fixes issue [highlighted](https://github.com/bevyengine/bevy/pull/8291#issuecomment-1499423313) in #8291 by developing an automated approach that will help ensure that spelling mistakes are detected and corrected, while also enforcing the use of US spelling variant.

As this pr is dependent on #8291, for this pull request to be completed, #8291 has to be merged beforehand.

## Solution

- Using the GitHub Action: [check-spelling](https://github.com/check-spelling/check-spelling), we are able to detect any spelling mistakes by using the default corpus, and extra corpora, and providing our own, to allow for exceptions (via dictionaries, regex, and file filtering).
- The GitHub action does have a CI bot. However, it is currently not set up but can be in the future as it only requires authorization from the repository owner.
- One point of contention is how invasive this CI task can be as discussed in #8291 :
    - As game dev has a lot of obscure words and the default dictionaries provided from [cspell-dicts](https://github.com/streetsidesoftware/cspell-dicts) do not encompass the game dev vernacular. Currently, we have two possible solutions:
        - A blacklist of all other variants of English spellings apart from the US variant would be one way to solve this somewhat. However, this means that spelling mistakes still can creep into the API and documentation, which in IMO. not the correct solution. Also, as of now, check-spelling does not have a blacklist as a feature but it is [planned](https://github.com/check-spelling/check-spelling/wiki/Feature%3A-Dictionary-deltas).
        - Another solution, the one I've currently implemented, is to create a whitelist composed of 4 dictionaries: `bevy.txt`,`gamedev.txt`,`rust.txt` and `linux.txt`. I hope to upstream at least the last 3 aforementioned dictionaries. Upstreaming should allow furthering the spelling check ecosystem, as check-spelling is using a format also available for spellchecker extensions in Visual Studio Code.
- To get the ball rolling I've currently made the ci step opt-in, requiring the commit message to contain: `[spellcheck]`. This would be, IMO. the first step to test its usefulness in cases such as prior to a scheduled release. Next-step improvements could be:
    - To set up the bot and let the ci job emit warnings and let the bot notify the user, to either fix the spelling mistake or whitelist any of the words if deemed acceptable by a maintainer.
    - Get it working with the [Code Spell Checker](https://github.com/streetsidesoftware/vscode-spell-checker) vsc extension.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Upstreaming the dictionary list seems like a solid choice: it would be lovely to be able to turn on automated spell-checking in my projects and in Bevy.

**Comment by mockersf** [comment]
> The GitHub action does have a CI bot. However, it is currently not set up but can be in the future as it only requires authorization from the repository owner.

What would we gain by adding this bot? Is it an issue if we never add it?

**Comment by BlackPhlox** [comment]
@mockersf No not really, I just thought that it would be more user-friendly for newcomers who haven't experience with CI, etc.

**Comment by BlackPhlox** [comment]
Ah, the commit message check doesn't work for prs anymore, see: https://github.com/orgs/community/discussions/28474#discussioncomment-3334578

**Comment by BlackPhlox** [comment]
Looks like I can get the VSC spellcheck extension working! 🎉

image

**Comment by BlackPhlox** [comment]
As we are only using [super-linter](https://github.com/github/super-linter) for Markdown linting, I recommend switching to [mega-linter](https://github.com/oxsecurity/megalinter) since it also includes cspell ci spellcheck. I believe this is a better solution than [check-spelling](https://github.com/check-spelling/check-spelling). Currently, because of the GitHub action, this PR requires duplicated configuration files to work: `excludes.txt` and `patterns.txt` for CI, versus `cspell.json` for the VSC extension. I would prefer to consolidate everything in a single `cspell.json` file.

You can find a comparison against super-linter [here](https://megalinter.io/latest/mega-linter-vs-super-linter).

Just like we're using super-linter:slim-v4 for markdown lint, we can use a mega-linter's documentation-flavoring docker image [here](https://megalinter.io/latest/flavors/documentation).

Similar to how we're using super-linter:slim-v4 for markdown linting, we can use a documentation-flavored docker image provided by mega-linter [here](https://megalinter.io/latest/flavors/documentation).

**Comment by alice-i-cecile** [comment]
Closing in favor of #12036.

**Pull request closed without merging**
