### PR TITLE
Make RenderPlugin emit only a soft error when there's no gpu, instead of panicking

### LINKED ISSUE #5931: Plugin for testing Bevy code in CI
## What problem does this solve or what need does it fill?

Bevy (partially because it's based on ECS) is uniquely suited for writing tests. A test can just involve adding some plugins, using direct world access to spawn in some entities with componets, calling `app.update()` a few times, then checking that your components were updated as you expected.

It's very common for someone to want to run tests in CI. But it's not clear which plugins you should add for that – you don't want `WinitPlugin` because it doesn't work except from the main thread, so it's not suitable for tests (which would ideally all run on their own thread). `RenderPlugin`, which you are likely to want because bevy_rapier depends on it, complains about [being unable to find a GPU](https://github.com/anchpop/endless-sea/runs/8276649772?check_suite_focus=true) when run in a gpu-less CI server.  

## What solution would you like?

A `TestsPlugin` for use when writing tests, that adds all the plugins besides the ones that really make no sense in CI, like `WinitPlugin`. 

Ideally, plugins that require things like a gpu would have alternatives that do as much as is possible when no GPU is available, even if it's just adding resources and things like that. But, even just adding a plugin bundle that adds the ones I below would likely be a big help to new users!

Additionally, if #4934 were fixed, it would allow `LogPlugin` to be used in tests, which is required for logs to show up. 

## What alternative(s) have you considered?

Forking `bevy_rapier` to not fail when `RenderPlugin` isn't added, and adding `MinimalPlugins`, `AssetPlugin`, `ScenePlugin`, `WindowPlugin`, `GilrsPlugin`, `TransformPlugin`, `HierarchyPlugin`, `DiagnosticsPlugin`, `InputPlugin`, and `AudioPlugin` manually. But having to do that isn't very friendly to new users :D

### PR DESCRIPTION
**Pull request by anchpop**
- Depends on #5932

# Objective

- Fixes #5931

## Solution

- In initialize_renderer, I just replaced the `.expect` with a `error!`, and made the function return an `Option` 
- In [bevy_render/src/lib.rs](https://github.com/bevyengine/bevy/compare/main...anchpop:%40anchpop/soft-error-when-no-gpu?expand=1#diff-856082d916c7309cbe6c8b2a231f703c8ab0769db951591018a5f217e6c42823) I wrapped some code in an `if let`. (The diff is huge, but it's just indentation changes.)
- Now that `RenderPlugin` will work in gpu-less environments like CI, I added it to `TestPlugins`.

---

### Fixed
- `RenderPlugin` no longer panics when run on a device without a GPU.

### CODE REVIEW

**Comment by bjorn3** [comment]
What is the advantage of this? If there is no GPU but the render plugin is used, the app is in a broken state. It doesn't make sense to needlessly consume resources (it will likely saturate at least a single core due to no vsync) as opposed to exit.

**Comment by devil-ira** [comment]
@bjorn3 The rationale is explained in the linked issue.

**Comment by mockersf** [comment]
In my opinion, this would be better as a cargo feature disabling rendering when not needed.

**Comment by alice-i-cecile** [comment]
> In my opinion, this would be better as a cargo feature disabling rendering when not needed.

Can you selectively disable cargo features for specific tests? If so, how?

**Comment by bjorn3** [comment]
Alternatively we could add a method to `DefaultPlugins` which disables the render and window plugins.

**Comment by mockersf** [comment]
> Can you selectively disable cargo features for specific tests? If so, how?

You can select the tests and the features to use when running the command `cargo test`. But why would you want some tests with rendering and some without?

**Review by afonsolage — COMMENTED** [review]
I like the idea, but should we move it to a separated `bevy_tests` crate? So users would use as `[dev-dependencies]`. We may also add other useful tests utilities in the future.

I don't like the ideia of `for_testing` being available in non-testing builds.

**Comment by alice-i-cecile** [comment]
Closing this out; https://github.com/bevyengine/bevy/blob/main/examples/app/no_renderer.rs should just work.

**Pull request closed without merging**
