### PR TITLE
Extracting ambient light from light.rs, and creating light directory

### PR DESCRIPTION
**Pull request by nbielans**
# Objective
Beginning of refactoring of light.rs in bevy_pbr, as per issue #12349 
Create and move light.rs to its own directory, and extract AmbientLight struct.

## Solution

- moved light.rs to light/mod.rs
- extracted AmbientLight struct to light/ambient_light.rs

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Looks good: nice and straightforward. Once merge conflicts are resolved and we have a second approval (from anyone) I'll merge this in for you :)

**Review by JMS55 — APPROVED** [review]

**Comment by JMS55** [comment]
One more file moved out of the root module yay.

**Comment by Shute052** [comment]
also `PointLight`, `SpotLight`, and `DirectionalLight`?

**Comment by alice-i-cecile** [comment]
> also `PointLight`, `SpotLight`, and `DirectionalLight`?

Agreed this should be done, but no preference on one vs several PRs :)

**Comment by nbielans** [comment]
yup, moving those other light variants is the plan, just wanted to make sure I felt good about the process and that this looked good before doing the rest of the file!

**Review by superdump — APPROVED** [review]

**Comment by superdump** [comment]
@nbielans - it looks like there are some merge conflicts. Could you update the PR by merging in the changes from `main`? Reach out on Discord if you need any help.

**Comment by nbielans** [comment]
@superdump just merged the changes!

**Pull request merged**
