### PR TITLE
Add First/Pre/Post/Last schedules to the Fixed timestep

### PR DESCRIPTION
**Pull request by Aceeri**
Fixes https://github.com/bevyengine/bevy/issues/10974

# Objective
Duplicate the ordering logic of the `Main` schedule into the `FixedMain` schedule.

---

## Changelog
- `FixedUpdate` is no longer the main schedule ran in `RunFixedUpdateLoop`, `FixedMain` has replaced this and has a similar structure to `Main`.

## Migration Guide
- Usage of `RunFixedUpdateLoop` should be renamed to `RunFixedMainLoop`.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Companion to #10969, which does a similar transformation for startup schedules.

**Review by maniwani — APPROVED** [review]
Yeah, `FixedMain` and `Main` carve up the same timeline in different ways (fixed vs. variable-sized steps). Their separation kind of resembles threads, so it makes sense that they would have the same structure.

**Comment by rlidwka** [comment]
`Startup` has different structure, there are no equivalents for `First` and `Last` there

what's the reason for the disparity?

**Comment by maniwani** [comment]
> What's the reason for the disparity?

It seems like it'd be better to ask this in the other PR. Especially if it's a blocker for you.

**Comment by Aceeri** [comment]
> `Startup` has different structure, there are no equivalents for `First` and `Last` there
> 
> what's the reason for the disparity?

https://github.com/bevyengine/bevy/pull/10969 This would be a better place to make this change

**Comment by rlidwka** [comment]
> It seems like it'd be better to ask this in the other PR.

I can ask "why First doesn't exist for Startup", and that question belongs to other PR. I can ask "why First exists for FixedUpdate", and that question belongs here. But that's the same fundamental question. Is `Startup` very different from `Main` and `Fixed`, such that first/last don't make sense there? Or is `Main` very different from `Startup` and `Fixed`, such that first/last only make sense there?

This PR is the one that adds `FixedFirst` and `FixedLast`. It seems reasonable to ask why.

**Comment by Aceeri** [comment]
> > It seems like it'd be better to ask this in the other PR.
> 
> I can ask "why First doesn't exist for Startup", and that question belongs to other PR. I can ask "why First exists for FixedUpdate", and that question belongs here. But that's the same fundamental question. Is `Startup` very different from `Main` and `Fixed`, such that first/last don't make sense there? Or is `Main` very different from `Startup` and `Fixed`, such that first/last only make sense there?
> 
> This PR is the one that adds `FixedFirst` and `FixedLast`. It seems reasonable to ask why. _Especially if I prefer to err on the side of not adding things if in doubt, since it's much easier to add things later than to remove them._

Startup is different in some ways but I don't 

> > It seems like it'd be better to ask this in the other PR.
> 
> I can ask "why First doesn't exist for Startup", and that question belongs to other PR. I can ask "why First exists for FixedUpdate", and that question belongs here. But that's the same fundamental question. Is `Startup` very different from `Main` and `Fixed`, such that first/last don't make sense there? Or is `Main` very different from `Startup` and `Fixed`, such that first/last only make sense there?
> 
> This PR is the one that adds `FixedFirst` and `FixedLast`. It seems reasonable to ask why. _Especially if I prefer to err on the side of not adding things if in doubt, since it's much easier to add things later than to remove them._

The only difference between fixed and main is that one is variable timing vs a set tick rate. Ideally all gameplay logic is in FixedMain, while UI/rendering/input related things are in Main. Startup is different in that it is just a setup tool for spawning scenes/ui/whatever or inserting resources or something. I don't have much objection to First/Last in Startup but I don't see much motivation for it currently.

**Pull request merged**
