### PR TITLE
[Merged by Bors] - Fix CI

### PR DESCRIPTION
**Pull request by BoxyUwU**

### CODE REVIEW

**Comment by mockersf** [comment]
is it due to a regression in rust nightly, or is it something that we actually need to fix in Bevy?

**Comment by BoxyUwU** [comment]
regression but i'd be kind of surprised if it was fixed since it doesnt seem like a clear cut "bug"

**Review by superdump — APPROVED** [review]
I don't fully understand the nitty gritty details, just the high-level concept that the rust compiler has changed something in nightly that affects the way it is able to prove lifetime constraints for various types/traits that caused this regression, and that this PR changes the lifetime annotations in such a way that the rust compiler can verify their validity. Thanks to @BoxyUwU for taking the time on Discord to discuss with and explain to me what this is about.

I also think it is important to unblock CI. We discussed whether the problem should be fixed upstream (yes?) and whether it's likely to happen soon (no?). We discussed alternatives to unblock CI such as make rust nightly builds failing not block CI (would make rust nightly users sad, and miri jobs identifying undefined behaviour would have to also be made non-blocking, which is also bad) and didn't come up with anything that feels better than merging this PR.

As such, I approve this.

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
Discussion about this in the rust-lang repo: https://github.com/rust-lang/rust/issues/89352#issuecomment-1119673901
For now, waiting for a crater run to see the impact

**Pull request closed without merging**
