### PR TITLE
Remove CanvasParentResizePlugin

### PR DESCRIPTION
**Pull request by Vrixyz**
Improves #11052

# Changelog
- Remove `Window::fit_canvas_to_parent`, as its resizing on wasm now respects its CSS configuration.

## Migration Guide
- Remove uses of `Window::fit_canvas_to_parent` in favor of CSS properties, for example:
  ```css
  canvas {
    width: 100%;
    height: 100%;
  }
  ```

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
You appear to be missing an issue link :)

**Review by irate-devil — APPROVED** [review]
When the website gets updated for the 0.13 release we can revert https://github.com/bevyengine/bevy-website/pull/640.

**Comment by MeoMix** [comment]
Really excited for this! :) I think this will make it simpler to avoid a flicker due to incorrect sizing on first load of my WASM app!

**Comment by cshenton-work** [comment]
A migration guide would be appreciated. 

`fit_canvas_to_parent` provided the exact behaviour I was depending on, simply giving me a full screen canvas that scaled with the window, without the need for any external css/html other than the default generated by most wasm runners.

**Comment by frewsxcv** [comment]
The CSS replacement of `fit_canvas_to_parent` does not work for me. Doesn't seem to resize like it used to https://rgis.app

**Comment by MeoMix** [comment]
> The CSS replacement of `fit_canvas_to_parent` does not work for me. Doesn't seem to resize like it used to https://rgis.app

Your width/height 100% isn't taking precedent over other stylings set programmatically.

image

**Comment by frewsxcv** [comment]
@MeoMix To my knowledge, I am not setting them programmatically in my project

**Comment by frewsxcv** [comment]
1280 x 720 is coming from Bevy:

https://github.com/bevyengine/bevy/blob/caa7ec68d41252217068c0bd330203990a6603d7/crates/bevy_window/src/window.rs#L631-L632

**Comment by frewsxcv** [comment]
It seems like it's being set by winit:

https://github.com/rust-windowing/winit/blob/a127bd6f6684909852000cdf32469bac3b611887/src/platform_impl/web/web_sys/canvas.rs#L71-L77

**Comment by MeoMix** [comment]
Understood.

https://github.com/bevyengine/bevy/pull/11278 It sort of looks like this PR wanted to get merged in but didn't make it?

**Comment by Vrixyz** [comment]
In the meantime I believe a workaround has been to set the width/height of the container div/html

**Comment by frewsxcv** [comment]
> In the meantime I believe a workaround has been to set the width/height of the container div/html

Set it to what?

**Comment by Vrixyz** [comment]
To 100%. (Or the size you want your inner canvas to be)

**Pull request merged**
