### PR TITLE
[Merged by Bors] - Fix some nightly clippy lints

### PR DESCRIPTION
**Pull request by BoxyUwU**
on nightly these two clippy lints fail:
- [needless_borrow](https://rust-lang.github.io/rust-clippy/master/#needless_borrow)
- [unused_unit](https://rust-lang.github.io/rust-clippy/master/#unused_unit)

### CODE REVIEW

**Comment by mockersf** [comment]
I think all the `#[allow(clippy::unused_unit)]` are due to all the macro for tuple running on tuples of size 0 which... are not tuples.
What would be the impact of fixing that so the macros start at 1?

**Comment by BoxyUwU** [comment]
- `fn foo()` would not be a valid system, not sure if this is actually useful or not but it doesnt seem harmful
- `()` would not be a valid fetch making `Query<()>` invalid so we wouldnt be able to do filter only queries
- `()` would not be a bundle... which actually seems like a win :)

**Comment by mockersf** [comment]
so... I think we should stop considering unit to be a special case of tuples, have the macro start at 1, and only impl the relevant trait for unit

**Comment by alice-i-cecile** [comment]
> so... I think we should stop considering unit to be a special case of tuples, have the macros start at 1, and only impl the relevant trait for unit

I agree with this.

> fn foo() would not be a valid system, not sure if this is actually useful or not but it doesnt seem harmful to allow

I've used this for testing and debugging before, so I'd like to keep it.

> () would not be a valid fetch making Query<()> invalid so we wouldnt be able to do filter only queries

I would also like to keep this.

> () would not be a bundle... which actually seems like a win :)

Yeet this one.

**Comment by mockersf** [comment]
@TheRawMeatball mentioned that [unit are actually tuples](https://doc.rust-lang.org/reference/types/tuple.html).

**Comment by BoxyUwU** [comment]
they are, i still think it makes sense to split out these impls though as the reason for having them is different than the impls for other tuples

**Comment by TheRawMeatball** [comment]
I'd disagree - having the tuple implementing ones also impl for the unit type is rather elegant imo, and I think we should keep them. IMO, to fix the lints, we should just add `#[allow(clippy::unused_unit)]` to these macros.

**Comment by cart** [comment]
I agree with @TheRawMeatball: a separate manual impl for unit is cumbersome / redundant / error prone. We should just suppress the lint for relevant impl macros (if there is no way to phrase the code to suppress the lint implicitly).

An example of an implicit suppression:

```rust
fn foo(_bar: T) {
  // bar isn't used and _ suppresses the unused lint
}
```

**Comment by cart** [comment]
> () no longer a bundle

I'm cool with this

> () no longer a Fetch

This creates problems for both filterless queries and fetchless filters (because they both rely on () having a Fetch impl ... filters are a special case of Fetch). This should stay as-is.

> fn foo() would not be a valid system

strong disagree. users should be able to create inputless systems (for things like printing messages)

**Comment by cart** [comment]
Sorry I added a new thought in the edit of my previous message, which probably should have been a new message so yall don't miss it.

**Comment by BoxyUwU** [comment]
imo `()` being a bundle never has a use case so having it implemented can only cause silent errors but im fine to table this for a different PR

**Pull request closed without merging**
