### PR TITLE
Add zoom to orthographic example

### LINKED ISSUE #2580: Add example demonstrating how to zoom orthographic cameras
## How can Bevy's documentation be improved?

Zooming an orthographic camera is surprisingly tricky; unlike ordinary cameras moving them further away from the object doesn't cause the size of the objects displayed to change as all their projection is parallel.

@TheRawMeatball provided this initial solution in #help:

```rust
fn zoom_system(
    mut whl: EventReader<MouseWheel>,
    mut cam: Query<(&mut Transform, &mut OrthographicProjection), With<MainCamera>>,
    windows: Res<Windows>,
) {
    let delta_zoom: f32 = whl.iter().map(|e| e.y).sum();
    if delta_zoom == 0. {
        return;
    }

    let (mut pos, mut cam) = cam.single_mut().unwrap();

    let window = windows.get_primary().unwrap();
    let window_size = Vec2::new(window.width(), window.height());
    let mouse_normalized_screen_pos =
        (window.cursor_position().unwrap() / window_size) * 2. - Vec2::ONE;
    let mouse_world_pos = pos.translation.truncate()
        + mouse_normalized_screen_pos * Vec2::new(cam.right, cam.top) * cam.scale;

    cam.scale -= ZOOM_SPEED * delta_zoom * cam.scale;
    cam.scale = cam.scale.clamp(MIN_ZOOM, MAX_ZOOM);

    pos.translation = (mouse_world_pos
        - mouse_normalized_screen_pos * Vec2::new(cam.right, cam.top) * cam.scale)
        .extend(pos.translation.z);
}
```
This should be straightforward to verify and clean up. Adding panning or rotation might also be worth including in the same example.

### PR DESCRIPTION
**Pull request by B-Janson**
# Objective
Fixes #2580. Extends the orthogonal example to include zoom as suggested.

## Solution

- Describe the solution used to achieve the objective above.

### CODE REVIEW

**Comment by DJMcNab** [comment]
Should this zoom maths be added as a method on `OrthographicProjection` instead?

**Comment by alice-i-cecile** [comment]
> Should this zoom maths be added as a method on OrthographicProjection instead?

I'm definitely in agreement with this :) Looks solid though!

**Comment by B-Janson** [comment]
I'm not sure I understand exactly. In the example, zooming is performed by changing the scale of the projection and moving the camera itself. But we don't have access to the camera translation from within the projection. I can only see how it'd be possible to zoom in and out of the centre of the screen plane.

**Comment by DJMcNab** [comment]
Hmm yeah, true.

The zoom method could return the relative transform based on the Vec2 as the fraction of the screen, then you'd update the camera's transform based on that.

**Comment by B-Janson** [comment]
WDYT of the following signature
`pub fn zoom_to(&mut self, screen_center_normalized: Vec2, delta_scale: f32, from_translation: &mut Vec3)`

**Comment by alice-i-cecile** [comment]
Initial proposal:

> `pub fn zoom_to(&mut self, screen_center_normalized: Vec2, delta_scale: f32, from_translation: &mut Vec3)`

Counter-proposal:
> `pub fn zoom_to(&mut self, new_screen_center: Vec2, new_scale: f32, camera_transform: &mut Transform)`

Changes:
- `new_screen_center`: better communicates intent. Clearly specify that this is in `Transform`'s `x, y` units in the field docs.
- `delta_scale` -> `new_scale`: idempotency is nice, and users can easily reconstruct the other API out of this one.
- `camera_transform: &mut Transform` -> Somewhat more type-safe, uses the familiar `Transform` type and clearly specifies where the values are coming from.

**Comment by B-Janson** [comment]
Sorry for the delay, I have been very busy finishing up the quarter with work! Back and able to contribute with a bit more consistency.
After thinking about this a little bit, I'm back to thinking that the original commit was the best solution. Just including a specific example for how to achieve rotation and zoom for a specific example. I'm not sure it is clean enough to define a zoom function within the projection itself just yet, especially if it wouldn't be consistent amongst all other current projections. What do you think?
cc @alice-i-cecile @DJMcNab

**Comment by alice-i-cecile** [comment]
>  I'm not sure it is clean enough to define a zoom function within the projection itself just yet, especially if it wouldn't be consistent amongst all other current projections. What do you think?

Hmm. I think that the smaller, scoped demo has clear value. Then, we can tackle a proper, general solution in another PR and update the example.

**Comment by alice-i-cecile** [comment]
@B-Janson I'm going to add the `Adopt-Me` label, but feel free to pick up this work again yourself :)

**Comment by NthTensor** [comment]
I want this but it seems stale. I recommend we close this an open a tracking issue for the example.

**Comment by alice-i-cecile** [comment]
Seconding that. Please close once an issue is up.

**Comment by tychedelia** [comment]
This would conflict with #11022, we should probably just request an example there.

**Pull request closed without merging**
