### PR TITLE
Fix min and max size using size value

### LINKED ISSUE #7946: Nodes are not constrained to container
## Bevy version

0.10, main
bisected to 76058bcf3346e085c0883c892e6111e20657e4f0

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

`scale_factor` is `2.`, but the behavior is the same when overridden to `1.`

## What you did

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

pub const DIALOG_BACKGROUND: Color = Color::rgb(0.2, 0.2, 0.2);
pub const BUTTON_BACKGROUND: Color = Color::rgb(0.15, 0.15, 0.15);

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());

    // dialog
    commands
        .spawn((NodeBundle {
            style: Style {
                size: Size::new(Val::Px(320.0), Val::Px(300.0)),
                margin: UiRect::all(Val::Auto),
                padding: UiRect::all(Val::Px(20.0)),
                flex_direction: FlexDirection::Column,
                ..Default::default()
            },
            background_color: DIALOG_BACKGROUND.into(),
            ..Default::default()
        },))
        .with_children(|parent| {
            // horizontal flex container for "buttons"
            parent
                .spawn(NodeBundle {
                    style: Style {
                        size: Size::new(Val::Percent(100.0), Val::Px(70.0)),
                        flex_direction: FlexDirection::Row,
                        justify_content: JustifyContent::Center,
                        align_items: AlignItems::Center,
                        ..Default::default()
                    },
                    ..Default::default()
                })
                .with_children(|parent| {
                    // "button" 1
                    parent.spawn(NodeBundle {
                        style: Style {
                            size: Size::new(Val::Percent(100.0), Val::Percent(100.0)),
                            ..Default::default()
                        },
                        background_color: BUTTON_BACKGROUND.into(),
                        ..Default::default()
                    });

                    // "button" 2
                    parent.spawn(NodeBundle {
                        style: Style {
                            size: Size::new(Val::Percent(100.0), Val::Percent(100.0)),
                            margin: UiRect {
                                left: Val::Px(10.0),
                                ..Default::default()
                            },
                            ..Default::default()
                        },
                        background_color: BUTTON_BACKGROUND.into(),
                        ..Default::default()
                    });
                });
        });
}
```

## What went wrong

Post-Taffy-3
image

Pre-Taffy-3 and 0.9 (what I expected)
image

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

Fixes #7946

## Solution

Fixed what seems to be a copy/paste error and things started to work.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Ping @ickshonpe for review :) (Bug Cart to be added to the org so I can request reviews properly?)

**Review by alice-i-cecile — APPROVED** [review]

**Review by ickshonpe — APPROVED** [review]
yeah this was me.

**Review by mockersf — APPROVED** [review]

**Comment by nicoburns** [comment]
@cart Is there a timeline for a bevy `0.10.1` release? #8169 is the fourth report we've had of this particular issue. IMO it might be worth putting out a `0.10.1` release with just this commit cherry-picked if a full patch release isn't going to be soon. Probably wouldn't even need to bother with release notes, etc if you wanted to keep the amount of work this requires down.

For context, the bug here is a silly typo when translating Bevy UI styles into Taffy styles that sets the `min_size` and `max_size` styles in Taffy to the value of the `size` style set in Bevy (instead of the corresponding `min_size` and `max_size` styles in Bevy). This completely breaks any UIs that use min or max sizes (and I think even UIs that just use width/height where those UIs rely on flex-shrinking).

**Comment by cart** [comment]
No specific timeline (other than before [Bevy Jam #3](https://itch.io/jam/bevy-jam-3), but this does make me want to release sooner rather than later. I'll look into the state of things.

**Comment by nicoburns** [comment]
> No specific timeline (other than before [Bevy Jam #3](https://itch.io/jam/bevy-jam-3)), but this does make me want to release sooner rather than later. I'll look into the state of things.

"before Bevy Jam 3" would be in the next week or so anyway? If so, then that seems plenty soon enough to me :) Definitely be good to get this sorted before the Jam!

**Pull request merged**
