### PR TITLE
Improve bevy icons for better "scalability"

### PR DESCRIPTION
**Pull request by Weasy666**
# Objective
Follow up to #3728.

@cart mentioned that increasing the gap size of the birds in the logo should be done for all icons, to make them scale better.

Right now, i have not committed anything to this branch/PR. I wanted to first discuss how i should handle the gap between the icon and text.

### Current
bevy_logo_dark_3

### Logo with increased gap but same banner size (notice the decreased gap between logo and text)
bevy_logo_dark_2

### Logo with increased gab and increased banner size (gap between logo and text is the same as in the current banner)
bevy_logo_dark_1
(in this example, the width increased from 416 px to 422 px)

### Current
icon

### Increased gap
icon

Let me know which `Logo + Text` you prefer and i will push that variant.

PS: The changed `bevy_bird_simpleicons.svg` should vanish after #3728 gets merged, i created a branch from that PR.

### CODE REVIEW

**Comment by bjorn3** [comment]
I feel like it becomes less clear that it represents three birds and more a single bird and two weird shapes.

**Review by alice-i-cecile — APPROVED** [review]
@Weasy666 can you take this out of draft mode?

I'd like to merge this + #3728 together.

**Comment by Weasy666** [comment]
Sure, done!

**Comment by alice-i-cecile** [comment]
It's not a major difference either way; pick whichever one you like best :)

**Comment by Weasy666** [comment]
OK...i picked `ogo with increased gab and increased banner size` and modified all svgs and their respective pngs accordingly.

**Comment by TimJentzsch** [comment]
Personally I would prefer two or three versions of the logo, based on the size. I don't think we can find a gap size that fits well for the super small and super big sizes. Especially considering the size difference of the badges to the website logo.

**Comment by Weasy666** [comment]
A few month ago @cart was not a fan of having different versions of the icons, dunno if he has changed his mind in the meantime. https://github.com/bevyengine/bevy/pull/3728#issuecomment-1053703655

**Comment by alice-i-cecile** [comment]
Adding the controversial label; I think this needs a final call from @cart.

**Comment by cart** [comment]
Yeah I think I'd prefer to not have a bunch of different versions of the logo bouncing around. Too easy for someone to pick the "wrong" one. I agree that the spacing feels "too big". Its worth considering a slightly smaller gap, but I'm a bit worried that any gap increase will make the logo feel "worse".

**Comment by Weasy666** [comment]
For me, it looks kinda like we are running in circles and i am slowly loosing my motivation here 😅
Sorry if this sounds kinda harsh, that is not my intention 🙂, but now we are more or less back to where we were at #3728

**Comment by cart** [comment]
I really appreciate the work you've done so far and if you stop here I certainly won't hold it against you. But I do think this is a conversation thats worth bringing to its conclusion. We have a number of concerns to balance:

1. Logo scalability at small sizes
2. Perceived logo quality at "normal" sizes
3. Logo consistency (ideally just one version)

Finding the right balance is a matter of aesthetic taste and given that I am the arbiter of that taste atm, it will either involve a lot of back and forth with me to tweak, or me taking ownership of the work. I'm happy to take ownership of the work, but I can't say this is my highest priority atm.

**Comment by cart** [comment]
Cool cool! From my perspective, in #3728 I only expressed that (a) a single logo version has my preference and (b) it is worth exploring increasing the gap in that unified version. Then this pr gave that a whack and we've largely agreed that the gap is too big. 

> Can you point me in a direction regarding the too big gap? How big should it be, compared to the original and current gap?

Lets try splitting the difference (half way between the original and current gap) and rendering that at a variety of sizes.

**Comment by richchurcher** [comment]
Closed (backlog cleanup), tracked in #15584.

**Pull request closed without merging**
