### PR TITLE
added temporary functions to control audio volume

### PR DESCRIPTION
**Pull request by Dash-L**
This PR is in reference to #650. I should start off by saying I'm very new to GitHub, I don't really want to merge this into master, simply into a bevyengine/bevy better-audio branch so that more work can be done on the system before it actually gets used, however, I cannot find a way to do that so here we are. All I did was make it so audio can be played at specified volumes with `play_volume()` and `play_source_volume()`, this is not a breaking change as the other audio functions were, for all intents and purposes, unchanged and will work as they used to.

### CODE REVIEW

**Comment by Dash-L** [comment]
Something to note is that we should probably migrate to rodio 0.12 before we do anything more with audio, see #638 for discussion about that.

**Comment by cart** [comment]
I like this idea! I created a "better-audio" branch for you. Feel free to change the base of the pr to that.

**Comment by Dash-L** [comment]
So I migrated to rodio 0.12 using thread local resources, but I may have done something wrong as seen by that last commit "Merge branch 'master' into better-audio." I had previously updated the master branch of my local fork and that was my way of updating the better-audio branch so I could use the thread local resources, not sure if I did it correctly though. I plan to add something like an `AudioDescriptor` struct that is used to configure audio and I think it would make sense to use events to control audio playing and stopping since it will all be running on the main thread now.

**Comment by cart** [comment]
I'm starting to think that the "better-audio" branch isn't the best way to approach this. While experimenting, I think its probably better for you to maintain your own branch (and potentially a 3rd party audio plugin if you want people to be able to test it in their bevy games)

Double reviewing code (once for better-audio and once for master) doesn't sound very appealing to me and it limits your ability to experiment freely.

I also think we should do the rodio upgrade to 0.12 in a separate pr so we can merge that quickly.

**Comment by Dash-L** [comment]
Ok, Im going to close this PR and (if there isn't one already) open a PR for the rodio upgrade.

**Pull request closed without merging**
