### PR TITLE
Add Box::from_min_max method

### PR DESCRIPTION
**Pull request by rezural**
# Objective

- This adds from_min_max to the Box shape type, to make non-centred Boxes easier.
- This is helpful for creating a visual representation of an axis aligned bounding box.

## Solution

- Add the method, which recieves min: Vec3, max: Vec3

### CODE REVIEW

**Review by DJMcNab — COMMENTED** [review]
Thanks, looks useful. 

One concern I have is e.g. if you pass `(1, 0, 1), (0, 1, 0)`, then the given box would potentially be weird. I don't know if there are any troubles with this case (which can also be reached manually or when using `Box::new` with negative numbers).

I wonder if it would make more sense to either rename it, or to automatically work out the minimum for each axis. It might be worth renaming `new` to `from_side_lengths`?

To be honest, I think `Box` could easily just be defined as `min: Vec3, max: Vec3`. I'm not sure why it wasn't defined as such in https://github.com/bevyengine/bevy/pull/883.

**Comment by rezural** [comment]
Yeah, I can code to work out the minimum, or asserts perhaps. It perhaps violates principal of least surprise to swap out if the minimums. Perhaps returning an Option.

However, this kind of stuff is already in the shape primitives PR, and perhaps effort is best concentrated there..?

Cheers

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
@rezural I like this, but I'd like to see:

1. Basic doc strings.
2. Assertions that min < max in all cases.

**Comment by james7132** [comment]
I'd rather just use `Vec3::min` and `Vec3::max` instead of asserts. Both are likely faster than asserts, being branchless on all platforms.

**Comment by james7132** [comment]
Closing in favor of #6672.

**Pull request closed without merging**
