### PR TITLE
avoid realloc memory across frame in GpuArrayBuffer

### PR DESCRIPTION
**Pull request by re0312**
# Objective

- currently,bevy use GputArrayBuffer for meshUniform,however ,in GpuArrayBuffer::StorageBuffer keeps a buffer will pass to Gpu everyframe that will be drop across frame which is not necessary.

## Solution
- keep the buffer to avoid realloc 

## Peformance
Window 11 ,Intel 13400kf, NV 4070Ti
(Only the platform which support StorageBuffer will benefit from this pr)

many cubes
yellow is main   ,    red is pr 

frame meantime from 3.85ms to 3.23ms,~16% reduction 

hot-spot function : batch_and_prepare_render_phase

meantime from 1.01ms to 0.567ms,almost 100% gain

### CODE REVIEW

**Review by JMS55 — APPROVED** [review]
Good spot! Approved, but you need to remove the unused mem import to get CI to pass.

**Comment by mockersf** [comment]
will that memory still be dealloced when it's not needed?

**Comment by JMS55** [comment]
We'll want to implement a scheme that shrinks the buffer capacity by a certain percentage if a certain percentage is unused when flip flopping. I have similar logic on my meshlet PR.

**Comment by re0312** [comment]
> will that memory still be dealloced when it's not needed?

No, memory usage will remain at the peak level required to hold the maximum number of meshes rendered on screen ,but the actual memory cost is relatively small, for example , 160k meshes (a pretty large number) obly cost 36*4B*160000 =20Mb

**Comment by mockersf** [comment]
Could you add a todo comment in the code for that?

**Review by mockersf — APPROVED** [review]

**Comment by re0312** [comment]
@JMS55 any reasons why we keep two vector in GpuArrayBuff::StorageBuffer ? IMO, the second vector seems unnecessary (or I might be overlooking something important).

**Review by james7132 — APPROVED** [review]
Thanks for making this PR! We can always add a `shrink_to_fit` function for reclaiming the unused memory.

**Comment by Elabajaba** [comment]
Can't we just call `shrink_to_fit` before we clear the vec?

**Comment by JMS55** [comment]
What I've been doing is when resetting the vec, if there's more than 30% spare capacity, shrink down to 30%.

**Comment by JMS55** [comment]
> any reasons why we keep two vector in GpuArrayBuff::StorageBuffer ? IMO, the second vector seems unnecessary (or I might be overlooking something important).
I don't know. I don't see why we need the second vec instead of just using buffer.get_mut(). Feel free to remove it.

**Comment by Elabajaba** [comment]
I don't think this is still applicable after #11368, should probably be closed?

We still probably need a compaction strategy for the buffers now.

**Comment by re0312** [comment]
> I don't think this is still applicable after #11368, should probably be closed?
> 
> We still probably need a compaction strategy for the buffers now.

Yeah, I will close it. maybe we need an individual system to free(shrink) all the memory that is no longer needed for render world.

**Comment by re0312** [comment]
close in favor of #11368

**Comment by re0312** [comment]
close in favor of https://github.com/bevyengine/bevy/pull/11368

**Pull request closed without merging**
