### PR TITLE
Fix common capitalization errors in documentation

### PR DESCRIPTION
**Pull request by janhohenheim**
WASM -> Wasm
MacOS -> macOS

Nothing important, just something that annoyed me for a while :)

### CODE REVIEW

**Comment by mockersf** [comment]
I would prefer to not change the changelog, otherwise 👍

**Comment by janhohenheim** [comment]
@mockersf typos are typos, no matter when or where they are located. Although I generally agree that a changelog shouldn't be touched after the fact, I don't think there's much of a point of leaving a typo on purpose there. It's not a historical document or anything.
But if you give me some git command I can just execute to undo it, I'll do that.

**Comment by mockersf** [comment]
it's excluded from typos detection:
https://github.com/bevyengine/bevy/blob/bfcb19a871559d988f4452cd9c60898ef186bdda/typos.toml#L2-L6

For a git command, maybe `git show bfcb19a871559d988f4452cd9c60898ef186bdda -- CHANGELOG.md | git apply -R`? 
Didn't try, but it's the first google result, surely it should work

**Comment by janhohenheim** [comment]
I remembered that I could just rebase everything into one commit and then `git restore CHANGELOG.md`, so I did that :)
Should be good now.

**Review by mockersf — APPROVED** [review]

**Pull request merged**
