### PR TITLE
Equirectangular skybox

### LINKED ISSUE #12455: Equirectangular HDRI skybox
## What problem does this solve or what need does it fill?

None of the HDRIs or panoramas out there seem to be available as cube maps.
The tools for conversions mostly don't work or have errors when building.
Even with having cube maps it won't solve the issue of loading an equirectangular HDRI at runtime.

## What solution would you like?

It would be great for bevy to either have it's own way to render an equirectangular pano as a skybox
or convert the equirectangular map to cube map and then render the cube map.

## What alternative(s) have you considered?

All of them, none solve rendering equirectangular panorama at runtime.

### PR DESCRIPTION
**Pull request by solis-lumine-vorago**
# Objective

- Fixes #12455

## Solution

- Adds support for using equirectangular skybox textures.
- The `Skybox` component now lets you specify the kind of texture used as a skybox using the `skybox_texture_layout` property. 

---

## Migration Guide

When creating a `Skybox` component, you need to specify the `skybox_texture_layout`. For your existing textures you should use `SkyboxTextureLayout::Cubemap`.

## Additional information

I have added a equirectangular version of the `assets/textures/Ryfjallet_cubemap.png`. This asset has a license/readme attached to it and I am not sure how to modify the readme.

### CODE REVIEW

**Review by JMS55 — COMMENTED** [review]
I don't see the need to have the user specify the layout themselves. You can just check the image type they provide.

Also note that the inverse trigonometric functions the non-cubemap layout uses is _extremely_ expensive. If we're going to support them, we should add a doc comment explaining that you should really prefer cubemap textures for performance reasons.

**Comment by solis-lumine-vorago** [comment]
> I don't see the need to have the user specify the layout themselves. You can just check the image type they provide.

You could, but I don't think that is particularly obvious. Although it is fairly clear that a cube texture will be a cubemap, there is nothing indicating that a flat image will be an equirectangular projection; why couldn't it be a Gall stereographic or any of the Mercator projections? 

> Also note that the inverse trigonometric functions the non-cubemap layout uses is _extremely_ expensive. If we're going to support them, we should add a doc comment explaining that you should really prefer cubemap textures for performance reasons.

You are absolutely right, I will add a note.

**Comment by JMS55** [comment]
> You could, but I don't think that is particularly obvious. Although it is fairly clear that a cube texture will be a cubemap, there is nothing indicating that a flat image will be an equirectangular projection; why couldn't it be a Gall stereographic or any of the Mercator projections?

Because bevy supports only equirectangular and cubemap. We can assume it's equirectangular if it's a 2d image, and cubemap if it's a 3d image.

**Comment by pcwalton** [comment]
This is unfortunately going to be slow as `atan2` in the shader is a very slow operation. It'd be better to generate a cubemap up front. We have an asset preprocessor now, so that'd be the ideal way to tackle this I think.

**Comment by pcwalton** [comment]
To provide a more concrete proposal to move this forward: I'd like to see this instead generate a cubemap texture at asset import time. This is relatively straightforward to do. This would provide the best performance possible at runtime, at some load time cost. Bonus points if you can save the cubemap as a `.ktx2` so you can cache this, but that isn't necessary for a first implementation.

**Comment by solis-lumine-vorago** [comment]
Ok, I am not familiar enough with cubemabs or the `ktx2` format and I am not comfortable enough to do this. As such I would close this PR and leave it to someone else to do this :)

**Comment by KristijanZic** [comment]
I think this should have been accepted. Now we have nothing again...

**Pull request closed without merging**
