### PR TITLE
Fixed crash when transcoding one- or two-channel KTX2 textures

### PR DESCRIPTION
**Pull request by Hexorg**
# Objective

Fixes a crash when transcoding one- or two-channel KTX2 textures

## Solution

transcoded array has been pre-allocated up to levels.len using a macros. Rgb8 transcoding already uses that and addresses transcoded array by an index. R8UnormSrgb and Rg8UnormSrgb were pushing on top of the transcoded vec, resulting in first levels.len() vectors to stay empty, and second levels.len() levels actually being transcoded, which then resulted in out of bounds read when copying levels to gpu

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Can you add a test to avoid regressions here?

**Comment by Hexorg** [comment]
@alice-i-cecile a unit test or a test file?

**Comment by Hexorg** [comment]
@alice-i-cecile I've built in a sample ktx2 file into the unit test. it's only 312 bytes. Let me know if you want it organized differently.

**Review by alice-i-cecile — APPROVED** [review]
Awesome, thank you very much. I'm very pleased to slowly start documenting and testing more of Bevy's rendering code. Automated tests >> manual inspection and user reports that we broke something again.

**Comment by Hexorg** [comment]
@alice-i-cecile ah ok, next time I make a pull request I’ll sprinkle docs on functions I touch (if you want)

**Comment by alice-i-cecile** [comment]
I will never say no to more docs ;)

**Review by superdump — APPROVED** [review]

**Pull request merged**
