### PR TITLE
Resolve UI outlines using the correct target's viewport size

### LINKED ISSUE #14945: UI outline geometry is always resolved using the size of the `PrimaryWindow` regardless of target
## What problem does this solve or what need does it fill?

`resolve_outlines_system` wasn't updated when multi-window support was added and it always uses the size of the primary window when resolving viewport coords.

## What solution would you like?

Resolve outlines using the target's viewport size.

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective
`resolve_outlines_system` wasn't updated when multi-window support was added and it always uses the size of the primary window when resolving viewport coords, regardless of the layout's camera target.

Fixes #14945

## Solution

It's awkward to get the viewport size of the target for an individual node without walking the tree or adding extra fields to `Node`, so I removed `resolve_outlines_system` and instead the outline values are updated in `ui_layout_system`.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by ickshonpe** [comment]
Not sure why the CI is failing with all those system ordering amibiguities.

**Comment by tychedelia** [comment]
> Not sure why the CI is failing with all those system ordering amibiguities.

The CI is difficult to parse, you need to look for systems you specifically touched.

**Review by tychedelia — APPROVED** [review]
Seems simpler.

**Comment by alice-i-cecile** [comment]
Yeah, I'm not thrilled with the output, but if the net effect is a decrease in ambiguities just set the expected number to the new total.

**Pull request merged**
