### PR TITLE
[Merged by Bors] - move `get_insert_bundle_info`

### PR DESCRIPTION
**Pull request by BoxyUwU**
I had to move this out in my relations PR and its causing a large diff so I figure I could just do this separately

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by BoxyUwU** [comment]
bad bors

**Comment by mockersf** [comment]
good bors!

bors r+

**Comment by BoxyUwU** [comment]
bad bors!!!!

**Comment by BoxyUwU** [comment]
bors retry

**Pull request closed without merging**
