### PR TITLE
[Merged by Bors] - Extract monomorphic get_insert_bundle_info function

### PR DESCRIPTION
**Pull request by bjorn3**
This shrinks breakout from 316k to 310k when using `--feature dynamic`.

I haven't run the ecs benchmark to test performance as my laptop is too noisy for reliable benchmarking.

### CODE REVIEW

**Comment by jakobhellermann** [comment]
Out of curiosity, which tools do you use to find which functions contribute the most to binary size?

**Comment by bjorn3** [comment]
Nothing fancy. Just https://github.com/m4b/bingrep to look at which symbols are defined in the executable. It also lists the function size.

```
$ #                                                  remove relocations
$ #                                                  |                 only keep functions
$ #                                                  |                 |           remove imports
$ #                                                  |                 |           |               these significantly reduce whitespace
$ #                                                  v                 v           v               v           v
$ bingrep target/release/examples/breakout --color | grep -v X86_64_ | grep FUNC | grep -v " 0 " | cut -c19- | tr -s " "
```

**Comment by cart** [comment]
I'm also on a pretty noisy / unreliable laptop right now, so I'll hold off on merging this until I can run it on my tower (next week). In theory I'm sold though!

**Comment by cart** [comment]
Just ran benchmarks on my tower and there were no significant perf changes here. Lets merge this!

**Pull request closed without merging**
