### PR TITLE
split check_light_mesh_visibility

### PR DESCRIPTION
**Pull request by lamalmeida**
# Objective

- Part of #12349 
- Split check_light_mesh_visibility into check_directional_light_mesh_visibility and check_spot_point_light_mesh_visibility

## Solution

- Moved shrink_entities to outside of check_light_mesh_visibility and split function according to light type
- Updated lib.rs accordingly

## Motivation

- Part of the refactoring effort focusing on decreasing the complexity of light.rs splitting it's contents into more manageable size 
- Refactored the check_light_mesh_visibility system: Making one system for handling directional lights, and one that handles point and spot lights
- Suggested by @superdump

### CODE REVIEW

**Comment by james7132** [comment]
Is this primarily for code quality or performance? If it's the latter, splitting the system up won't allow it to parallelize due to the mutable access it needs.

**Comment by NthTensor** [comment]
Thanks! Small diff, but I think reviewers would appreciate some motivation for this change. Needs profiling too probably.

**Review by superdump — APPROVED** [review]

**Comment by superdump** [comment]
The code looks fine, but I agree that this should have benchmarks to show it doesn't regress performance.

@james7132 @NthTensor - see https://github.com/bevyengine/bevy/issues/12349 for the high-level. This code has a mix of code doing all sorts of different things in one file, and long systems with mixed responsibilities. This PR was one step I suggested to starting to split things up. The end goal is going to be a collection of plugins for clustering, for different light types (spot and point lights will probably live together, but separate from ambient, directional, etc), and for different shadow mapping techniques (spot light single projection, point light cubemaps, directional light cascaded shadow maps).

**Comment by superdump** [comment]
@lamalmeida please take a look at https://github.com/bevyengine/bevy/blob/main/docs/profiling.md#tracy-profiler to see how to do profiling. I think we need a stress test example like `many_lights` and `many_cubes`, but that allows testing `check*_light_mesh_visibilty` performance. I think it should do the following:
- Have many objects in the scene like `many_cubes`
- Have the ability to have many point lights, many spot lights, a directional light, or a mix
- Use seeded random number generators where needed to give more reproducible results

Then when you have that stress test implemented, do a profile run on `main` before the changes in this PR and another with the changes, and compare the median frame times, and median `check*_light_mesh_visibility` times. Reach out on Discord if you need any help.

**Comment by lamalmeida** [comment]
Screenshot 2024-03-30 135455

Yellow is new, red is old implementation. There is a slight performance drop when the scene contains both types of lights. If the scene only has one type of light, then there is a slight performance gain. In either cases they look almost the same.

**Comment by NthTensor** [comment]
Whats the status of this PR? Ready for another round of reviews and bench-marking?

**Comment by lamalmeida** [comment]
The changes to lib.rs and mod.rs regarding check_light_mesh_visibility were tested with the profiling results above and approved by Rob Swain. The new file shadow.rs moves any shadow related structs from mod.rs. I didn't mean to add it to this PR, I'm just not too familiar with git/github and I'm working to remove it.

**Pull request closed without merging**
