### PR TITLE
add `SystemIdMarker` `Component` to enable filtering for `SystemId` `Entity`s

### PR DESCRIPTION
**Pull request by databasedav**
# Objective

Enables writing queries like `Query<Entity, With<SystemIdMarker>>` to filter `Entity`s that are, or are not (with `Without`), `SystemId`s.

## Solution

Simple unit struct `SystemIdMarker` added during `World::register_boxed_system`; `World::remove_system` already despawns the entity, removing the marker.

## Testing

No tests, but happy to write some with direction.

### CODE REVIEW

**Comment by databasedav** [comment]
@alice-i-cecile to answer your question from discord

> And double check what observers do while you're there maybe?

I didn't dig super deep, but one shot systems and observers are similar in that they both store a boxed system, the former stores it in a component, the latter doesn't. Plus, the former is associated with an `Entity` whereas the latter isn't as far as I can tell.

This is actually semi-related to a question I asked about [stopping bubbling observer event propagation](https://discord.com/channels/691052431525675048/1236111180624297984/1263399249974919178) a couple weeks ago; one can't actually query for particular observers in systems, so modifying their state, e.g. stopping event propagation, must be done indirectly within the observer's body, e.g. with a marker component. It would be nice to be able to query for observers too, although I don't know enough to know the implications.

**Comment by DasLixou** [comment]
What about just `With<RegisteredSystem>`?

**Comment by alice-i-cecile** [comment]
Looking at the code, I think that making `RegisteredSystem` (but probably not any of its fields and methods) `pub` is my preferred solution here :)

As for observers, looks like they add a public `Observer` component, but that's generic and can't readily be queried. That can be tackled in a follow-up PR.

**Comment by ItsDoot** [comment]
RegisteredSystem is also generic:

https://github.com/bevyengine/bevy/blob/7c80ae73133f9866f2ed477ce9922c83fc3fe1cc/crates/bevy_ecs/src/system/system_registry.rs#L9-L13

**Review by chescock — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
