### PR TITLE
[Merged by Bors] - Add ControlNode for UI

### PR DESCRIPTION
**Pull request by TheRawMeatball**
This PR adds a ControlNode which marks an entity as "transparent" to the UI layout system, meaning the children of this entity will be treated as the children of this entity s parent by the layout system(s).

### CODE REVIEW

**Comment by TheRawMeatball** [comment]
Something we should consider is whether to move this into bevy_transform instead - this form of "children transparency" could be useful elsewhere, and having a common component all others base things around could be a good idea.

**Review by inodentry — APPROVED** [review]

**Comment by mockersf** [comment]
Code looks good, but could you show an example where this is useful?

**Comment by TheRawMeatball** [comment]
This increases the flexibility of the hierarchy by letting other crates store more complex information in the UI hierarchy while still having it work. I'm personally using this in ui4 to encode the control structure inside the ECS as deeper levels of nesting, and this change made things drastically simpler.

**Review by mockersf — APPROVED** [review]
I guess we'll have a new kind of issues with people adding `ControlNode` where it shouldn't, but this will be for people doing complicated things with UI so they're already torturing themselves 👍

**Pull request closed without merging**
