### PR TITLE
[Merged by Bors] - Add cart's fork of ecs_bench_suite

### LINKED ISSUE #2062: Move Bevy's fork of the ecs_bench_suite to the appropriate folder
I went looking for the latest bevy-specific `ecs_bench_suite` code and could not quickly find it.

Ideally, this should be found (or linked) in our [benches/bevy_ecs](https://github.com/bevyengine/bevy/tree/main/benches/benches/bevy_ecs) folder.

The most up-to-date version is currently found on @cart's GitHub page here: https://github.com/cart/ecs_bench_suite/tree/bevy-benches. The latest upstream code is here: https://github.com/rust-gamedev/ecs_bench_suite

Once this is done, please also update CONTRIBUTING.md (see #2040) with directions to the benchmarks and add appropriate documentation on how to run the benchmarks in the README of the benches folder.

I'm also not entirely sure why we have two layers of `benches` folders; perhaps someone else can chime in.

### PR DESCRIPTION
**Pull request by james7132**
# Objective
Better benchmarking for ECS. Fix #2062.

## Solution
Port @cart's fork of ecs_bench_suite to the official bench suite for bevy_ecs, replace cgmath with glam, update to latest bevy.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Looks good to me. We can revise these further in the future IMO.

**Comment by IceSentry** [comment]
I'm not sure if I'm doing something wrong, but if I clone this PR, go to the `/benches` folder and run `cargo bench` I get this error.

```
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
   --> C:\Users\<user>\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-epoch-0.9.8\src\atomic.rs:314:6
    |
314 | impl<T: ?Sized + Pointable> Atomic<T> {
    |      ^
...
346 |     pub const fn null() -> Atomic<T> {
    |     -------------------------------- function declared as const here
    |
    = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information
    = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable

   Compiling cast v0.2.7
For more information about this error, try `rustc --explain E0658`.
```

**Comment by hymm** [comment]
I was able to run the tests just fine. Windows 10, rust 1.59.

**Review by hymm — APPROVED** [review]

**Review by cart — APPROVED** [review]
Awesome! I agree that we might ultimately want to tweak these to meet our own needs (instead of assuming ecs_bench_suite patterns are the right call). But having these tests in-tree makes optimizing bevy_ecs much easier. This is definitely a win.

**Comment by DJMcNab** [comment]
Sorry to do this, but I think we need to revert this. We don't have a license to include the code from `ecs_bench_suite`, which is all rights reserved.

We can seperately get in touch with @tomgillen to try and get such a license, but otherwise we can't use this.

**Comment by cart** [comment]
This was the right call, as we hadn't previously discussed this. But I think generally these fall under the "trivially reproducible / not novel" category of thing. From scratch impls would look pretty much the same. Couple that with me being the one that wrote most of the code here, and I think adding these isn't risky.

That being said, its better to ask and be safe.
  
@TomGillen, can we have permission to relicense the bevy ecs_bench_suite tests under bevy's dual MIT/Apache-2.0 license?

**Comment by TomGillen** [comment]
I don't have any problem with that. It should have had such a license in the first place, but it didn't occur to me that someone would want to embed the code into another project or use it as a library.

**Comment by cart** [comment]
Thanks @TomGillen!

**Pull request closed without merging**
