### PR TITLE
[Merged by Bors] - rename bevy_ui::node module so that bevy_ui::render::node isn't shadowed

### PR DESCRIPTION
**Pull request by jakobhellermann**
Previously the `mod node` shadowed the `pub use render::node`, and `CAMERA_UI`, `NODE` and `UI_PASS` constants couldn't be used.

### CODE REVIEW

**Review by DJMcNab — APPROVED** [review]
This doesn't change the public API, since the module wasn't even exported.

**Review by DJMcNab — APPROVED** [review]
I'll try and approve again now that I've made my membership public, maybe that will make it official.

**Comment by bjorn3** [comment]
I think it will only mark it as "official" if you have write permission.

**Review by mockersf — APPROVED** [review]

**Comment by DJMcNab** [comment]
> I think it will only mark it as "official" if you have write permission.

Yeah, we discussed this on discord

**Comment by cart** [comment]
> I think it will only mark it as "official" if you have write permission.

Yeah this is a real shame. Lol maybe we can build a github workflow that adds tags when there are X approvals from members.

**Pull request closed without merging**
