### PR TITLE
Add a case-insensitive check for `Key::Character` value

### LINKED ISSUE #11689: Unexpected Logical Key Value
## Bevy version

The main Bevy (currently, commit #08654ad), but the bug actually comes from [Bevy PR #10702: Update winit to 0.29](https://github.com/bevyengine/bevy/pull/10702)

## \[Optional\] Relevant system information

This might be able to reproduce on any machine in the version.

## What you did

I am working on the [updates](https://github.com/Leafwing-Studios/leafwing-input-manager/pull/463) of `leafwing_input_manager` to Bevy 0.13, but as the title says, the logical `Key` value seems to be incorrect.

### Simple Case for Reproduction

```rust
fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Update, read_keyboard_input)
        .run()
}

fn read_keyboard_input(mut keyboard_input: EventReader<KeyboardInput>) {
    for input in keyboard_input.read() {
        dbg!(input);
    }
}
```

## What went wrong

The situation is:
- If you just press any letter keys, e.g., W key and then you will get a `KeyboardInput(logical_key: "w")`, an expected lowercase w letter.
- However, if CapsLock is activated or Shift is pressing, like normal text input, you will get a `KeyboardInput(logical_key: "W")`, **"AN UPPERCASE W LETTER"**!

### PR DESCRIPTION
**Pull request by Shute052**
# Objective

Fixes #11689 if logical letter keys should remain consistent regardless of external factors.
Reporting both lowercase and UPPERCASE logical letter keys is adding a burden on us to make shortcuts in the games.

## Solution

~~Apply the upstream [suggestion](https://github.com/rust-windowing/winit/issues/3453).~~
~~- Use `key_without_modifiers` in `convert_keyboard_input` for `convert_logical_key`.~~

~~- Use `to_uppercase` to all OSs because some of them don't support `key_without_modifiers`.~~

### Add `Key::to_uppercase_character()`.

Returns an uppercase version if `self` is a `Key::Character`.
Otherwise, returns a `Clone` of `self`.

For example:

```rust
use bevy_input::keyboard::Key;

assert_eq!(Key::Character("B".into()).to_uppercase_character(), Key::Character("B".into()));
assert_eq!(Key::Character("b".into()).to_uppercase_character(), Key::Character("B".into()));
assert_eq!(Key::ArrowUp.to_uppercase_character(), Key::ArrowUp);
```

### Expose the `SmolStr::eq_ignore_ascii_case(&str)` to `Key`.

Returns true if `self` is a `Key::Character(character_self)` and `character_self` is an ASCII case-insensitive match with the given `character`.
Otherwise, it means they are not matched or `self` is not a `Key::Character`.

For example:

```rust
use bevy_input::keyboard::Key;

assert!(Key::Character("B".into()).eq_ignore_ascii_case("B"));
assert!(Key::Character("b".into()).eq_ignore_ascii_case("B"));
assert!(!Key::ArrowUp.eq_ignore_ascii_case("B"));
```

### Before

The main Bevy after the merge of #10702 occurs the situation that all letter logical keys, for example, the 'W' key is reporting a lowercase 'w' normally and an uppercase 'W' when CapsLock is activated or Shift is pressed.

If dealing with both case, we have to repeat the following boilerplate code:

```rust
/// Binds with the logical keys rather than physical keys without this PR
fn listen_keyboard_input_events(mut events: EventReader<KeyboardInput>) {
    for event in events.read() {
        if let Key::Character(character) = event.logical_key {
            if character.eq_ignore_ascii_case("A") {
              info!("A key has been pressed!")
            }
        }
        // Other cases...
        match event.logical_key {
            Key::Character("w".into()) | Key::Character("W".into()) => {
              info!("W key has been pressed!")
            }
            Key::Character(c) if c.eq_ignore_ascii_case("S") => {
              info!("S key has been pressed!")
            }
            Key::ArrowUp => {
              info!("ArrowUp key has been pressed!")
            }
            // Other cases...
            _ => continue,
        }
        // Or via if-let
    }
}
```

### After

Now in this case, we have:

```rust
/// Binds with the logical keys rather than physical keys via current PR.
fn listen_keyboard_input_events(mut events: EventReader<KeyboardInput>) {
    for event in events.read() {
        if event.logical_key.eq_ignore_ascii_case("W") {
            info!("W key has been pressed!")
        }
        // Other cases...
        match event.logical_key.to_uppercase_character() {
            Key::Character("W".into()) => {
              info!("W key has been pressed!")
            }
            Key::ArrowUp => {
              info!("ArrowUp key has been pressed!")
            }
            // Other cases...
            _ => continue,
        }
    }
}
```

### CODE REVIEW

**Comment by rparrett** [comment]
This particular would be a bit of a bummer for me. `ReceivedCharacter` is not adequate for implementing a text input and  `logical_key` has been helpful. (Further explanation here: #11297)

**Comment by Shute052** [comment]
> This particular fix would be a bit of a bummer for me. `ReceivedCharacter` is not adequate for implementing a text input and `logical_key` has been helpful. (Further explanation here: #11297)

It seems that you need `KeyEvent::logical_key::to_text()`?

**Review by Vrixyz — APPROVED** [review]
I think this has value :+1: ; and low surprise code for users.

A user can still match like to avoid clone
```rs
match event.logical_key {
    Key::Character(c) if c.to_uppercase().to_string() == "A") =>
...
```

**Comment by Shute052** [comment]
> I think this has value 👍 ; and low surprise code for users.
> 
> A user can still match like to avoid clone
> 
> ```rust
> match event.logical_key {
>     Key::Character(c) if c.to_uppercase().to_string() == "A") =>
> ...
> ```

Added an alternative, or perhaps having both functions could be a viable option?

**Comment by Shute052** [comment]
> I think this has value 👍 ; and low surprise code for users.
> 
> A user can still match like to avoid clone
> 
> ```rust
> match event.logical_key {
>     Key::Character(c) if c.to_uppercase().to_string() == "A") =>
> ...
> ```

Is there a way to use `ButtonInput<Key>`? I tried initially, but `ButtonInput<T>` demands that `T` has the `Copy` trait. However, the `Key`s include `Key::Character`, preventing them from deriving `Copy`.

**Comment by alice-i-cecile** [comment]
We could remove the `Copy` bound on `ButtonInput`, but I'm still nervous about trying to exact match more complex data like that.

P.S. Closing this out, as the linked issue has been closed and I don't think this is the right approach to the ultimate problem.

**Comment by Vrixyz** [comment]
> Is there a way to use `ButtonInput<Key>`?

There is no such thing, it's not trivial to consistently support `released` after `pressed`  for characters, so it didn't make it in. More context there: https://github.com/Vrixyz/bevy/pull/3

**Pull request closed without merging**
