### PR TITLE
Support no_std compilation for various crates

### PR DESCRIPTION
**Pull request by james7132**
# Objective
Partially addresses #6370. Make many of the crates `no_std`.

## Solution
Replace `std` with `core` and `alloc`.

Also sprinkles a few `forbid(unsafe_code)` where it's trivial to add it to a crate.

This does not guarantee all of these crates will build for `no_std` environments. Many still have dependencies with `std` deps.

### CODE REVIEW

**Comment by james7132** [comment]
Going to assume this controversial by default due to the commitment and potential maintenance burden this may have.

**Comment by mockersf** [comment]
> This does not guarantee all of these crates will build for `no_std` environments. Many still have dependencies with `std` deps.

Are at least a few of the crates `no_std` compatibles with this? Would it makes sense to add that check to CI for those / how long would it take?

**Comment by james7132** [comment]
Quite a few of them are. The few that aren't usually require some kind of IO, since `std::fs` and `std::net` have zero core, or alloc equivalents.

**Comment by james7132** [comment]
Another major blocker I'm running into: `thiserror` has zero support for no_std. We could manually implement it, or find another no_std compatible error derive crate.

**Comment by alice-i-cecile** [comment]
I'm happy to review any smaller forms of this PR: breaking it up by chunks seems very appealing.

**Comment by james7132** [comment]
The primary things that we'd be missing are, as far as I know:

 * `std::thread` and `std::sync`. These come up for parallelization and concurrency, but we already have ways of disabling threading. We may need to drop down to `lock_api` to find alternatives for the latter.
 * `std::io` is the other big one, which precludes a large portion of the asset-dependent crates. Thankfully we haven't started adding networking capabilities to first party crates yet other than in-browser fetches.

`alloc` is probably the biggest thing we cannot get rid of, and I don't think it makes sense to be running Bevy on a platform without dynamic memory allocation of any kind.

**Comment by james7132** [comment]
Closing in favor of #15281.

**Pull request closed without merging**
