### PR TITLE
[Merged by Bors] - Cam scale cluster fix

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

fix clustering calculations for cameras with non-unit scale

## Solution

get view scale and apply to light range at various points

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
These changes make sense to me, but I'm nervous about the pervasive lack of tests for this stuff. Is there a reasonable way to add some here?

**Comment by Elabajaba** [comment]
I totally forgot about this.

It fixes the bugs I was seeing on the built-in animation in Bistro, but I don't understand how lighting works well enough to know if everything here is correct.

**Review by superdump — APPROVED** [review]

**Comment by superdump** [comment]
bors retry

**Pull request closed without merging**
