### PR TITLE
Improve many_sprites example (#2075)

### PR DESCRIPTION
**Pull request by neosam**
Hi.  The the camera movement is different now but I guess it's easier to understand.  If that's a problem, I can work on the camera movement system a little more.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Much improved! Thanks for the contribution :)

**Comment by alice-i-cecile** [comment]
Closes #2075.

**Review by alice-i-cecile — APPROVED** [review]
A solid improvement to code quality. @Byteron, would you be able to comment on whether the new camera movement will still stress-test the frustum culling system appropriately?

**Comment by alice-i-cecile** [comment]
@neosam could you please comment in #2373? Alternatively, we can just move forward with #2785 and credit you there for the effort you put into this (my bad on encouraging the duplication).

**Comment by neosam** [comment]
@alice-i-cecile No problem.  Pick the one which fits best.  I left a comment on #2373.

**Comment by alice-i-cecile** [comment]
Closing in favor of #2785 <3 Thanks a ton!

**Pull request closed without merging**
