### PR TITLE
3d game example

### PR DESCRIPTION
**Pull request by mockersf**
Eat the cakes. Eat them all, I dare you.

...

**And experience the powerful sugar rush of the alien.**

Small 3d game example that I had fun doing this afternoon.

### CODE REVIEW

**Comment by mockersf** [comment]
Controls are arrow key to move, spacebar to restart after losing.

Game shows spawning and controlling gltf scenes in various ways, changing the camera, systems with state.

Some of the thins could be nicer with more complexity, but goal was too keep it short


https://user-images.githubusercontent.com/8672791/104822079-76402a80-5840-11eb-871b-6e847902bc0e.mp4

**Comment by tigregalis** [comment]
Nice work.

The camera movement makes me uncomfortable though haha.

Here's a camera movement system I've come up with - in general it points to the mid-point between the alien and the cake:
```rust
#[derive(Default)]
struct Game {
    board: Vec<Vec<Cell>>,
    player: Player,
    bonus: Bonus,
    score: i32,
    cake_eaten: u32,
    camera_should_focus: Vec3,
    camera_is_focus: Vec3,
}

fn setup(commands: &mut Commands, asset_server: Res<AssetServer>, mut game: ResMut<Game>) {
    // reset the game state
    game.cake_eaten = 0;
    game.score = 0;
    game.player.i = BOARD_SIZE_I / 2;
    game.player.j = BOARD_SIZE_J / 2;
    game.camera_should_focus = Vec3::new(
        BOARD_SIZE_I as f32 / 2.0,
        0.0,
        BOARD_SIZE_J as f32 / 2.0 - 0.5,
    );
    game.camera_is_focus = game.camera_should_focus;
    // ...
}

// move the camera, the more cake eaten, the faster
fn move_camera(
    time: Res<Time>,
    mut game: ResMut<Game>,
    mut transforms: QuerySet<(Query<(&mut Transform, &Camera)>, Query<&Transform>)>,
) {
    const SPEED: f32 = 2.0;
    // if there is both a player and a bonus, target the mid-point of them
    if let (Some(player_entity), Some(bonus_entity)) = (game.player.entity, game.bonus.entity) {
        if let (Ok(player_transform), Ok(bonus_transform)) = (
            transforms.q1().get(player_entity),
            transforms.q1().get(bonus_entity),
        ) {
            game.camera_should_focus = player_transform
                .translation
                .lerp(bonus_transform.translation, 0.5);
        }
    // otherwise, if there is only a player, target the player
    } else if let Some(player_entity) = game.player.entity {
        if let Ok(player_transform) = transforms.q1().get(player_entity) {
            game.camera_should_focus = player_transform.translation;
        }
    // otherwise, target the middle
    } else {
        game.camera_should_focus = Vec3::new(
            BOARD_SIZE_I as f32 / 2.0,
            0.0,
            BOARD_SIZE_J as f32 / 2.0 - 0.5,
        );
    }
    // calculate the camera motion based on the difference between where the camera is looking
    // and where it should be looking; the greater the distance, the faster the motion;
    // smooth out the camera movement using the frame time
    let mut camera_motion = game.camera_should_focus - game.camera_is_focus;
    if camera_motion.length() > 0.2 {
        camera_motion *= SPEED * time.delta_seconds();
        // set the new camera's actual focus
        game.camera_is_focus += camera_motion;
    }
    // look at that new camera's actual focus
    for (mut transform, camera) in transforms.q0_mut().iter_mut() {
        if camera.name == Some(CAMERA_3D.to_string()) {
            *transform = transform.looking_at(game.camera_is_focus, Vec3::unit_y());
        }
    }
}
```

**Comment by cart** [comment]
Yeah I like everything about this except the "motion sickness as a game mechanic" aspect. Some people are very sensitive to that and I don't want to make them sick :smile:

**Comment by mockersf** [comment]
> Here's a camera movement system I've come up with

Oh I like that your camera actually does something useful and interesting to show in an example

**Comment by mockersf** [comment]
> "motion sickness as a game mechanic"

It actually came from me trying to do something useful with the camera and just failing to have controls that I liked so... heh

**Comment by cart** [comment]
Awesome. This looks good to me!

**Pull request merged**
