### PR TITLE
`IntoSystemConfigs::chain_ignore_deferred`'s return type fix

### LINKED ISSUE #13917: `IntoSystemSetConfigs::chain_ignore_deferred` has wrong return type
## Bevy version

53910e07aefc40a9f9ca089f643d731b748c699f (Bevy 0.13.2)

## What you did

```rust
#[derive(SystemSet, Debug, Hash, PartialEq, Eq, Clone)]
struct SetA;

#[derive(SystemSet, Debug, Hash, PartialEq, Eq, Clone)]
struct SetB;

fn main() {
    App::new()
        .configure_sets(Update, (SetA, SetB).chain_ignore_deferred());
}
```

## What went wrong

`IntoSystemSetConfigs::chain_ignore_deferred`'s return type is not the same as `IntoSystemSetConfigs::chain`. Because of that you can't use `chain_ignore_deferred` with system sets

Compile error:
```
error[E0277]: the trait bound `NodeConfigs<std::boxed::Box<dyn bevy::prelude::System<In = (), Out = ()>>>: IntoSystemSetConfigs` is not satisfied
   --> src/main.rs:30:33
    |
30  |         .configure_sets(Update, (SetA, SetB).chain_ignore_deferred())
    |          --------------         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `SystemSet` is not implemented for `NodeConfigs<std::boxed::Box<dyn bevy::prelude::System<In = (), Out = ()>>>`, which is required by `NodeConfigs<std::boxed::Box<dyn bevy::prelude::System<In = (), Out = ()>>>: IntoSystemSetConfigs`
    |          |
    |          required by a bound introduced by this call
    |
```

### PR DESCRIPTION
**Pull request by Jenya705**
# Objective

Fixes #13917 

## Solution

Changed `IntoSystemSetConfigs::chain_ignore_deferred`'s return type from `SystemConfigs` to `SystemSetConfigs`

## Testing

Tried to run the `ecs_guide` example, where `chain` method is replaced by `chain_ignore_deferred` method 

---

### CODE REVIEW

**Review by ItsDoot — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by urben1680** [comment]
This fix did not make it into 14.0 or 14.1 sadly. @alice-i-cecile

**Comment by alice-i-cecile** [comment]
Yep, this isn't a 0.14.x candidate because it's breaking unfortunately.

**Comment by urben1680** [comment]
Ah so missing 0.14.0 doomed it for 0.15.0.

Interesting though, I would interpret it as an *un*breaking change as right now one cannot use this method in `configure_sets`.

**Comment by alice-i-cecile** [comment]
Definitely a bug fix, but it changes the return type in a way that isn't semver compatible. Definitely an annoying limitation, but not so severe as to bend the rules IMO.

**Pull request merged**
