### PR TITLE
Add `#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]` to gamepad types.

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by cart** [comment]
This is similar to #524, but I prefer it because its simpler / doesn't require setting defaults on enums that don't _really_ have a default that makes sense.

@PradeepKumarRajamanickam: does this handle everything you need it to?

**Comment by PradeepKumarRajamanickam** [comment]
I had tried this (refer commit #ebb33c1 in #524) but this will fail at runtime with a panic when you serialize to json due to struct tuples. So I had to implement a serialize/deserialize helper manually. 

Regarding the enum default, it has been a while and I don't remember the exact reason but I think I was getting compiler errors when using them in Hashmap. But I could be wrong we can remove it if it is not really needed.

**Comment by PradeepKumarRajamanickam** [comment]
@cart I have added a custom serde helper method in input map project to do serialize/deserialize stuff. It only needs enums to be marked with derive so we can use this pr. 

However it would be nice to be able to serialize gamepad struct tuples out of the box. This will reduce duplicate effort incase someone else wants to develop plugins that needs serde.

**Comment by ndarilek** [comment]
Not sure about the referenced PR, but I created this by looking at keyboard.rs and copying the derives from there. So, if nothing else, this creates parity between keyboard and joystick serialization and should probably be merged on that alone. If something isn't correct, it's probably worth revisiting the keyboard implementation. I also haven't looked into the other PR, so maybe it brings other benefits too. If it does, those should probably be mirrored for keyboards if they aren't already.

**Comment by PradeepKumarRajamanickam** [comment]
@ndarilek Yeah may be you are right. We can revisit tuple struct serialisation panic at a later point.

**Comment by cart** [comment]
@PradeepKumarRajamanickam i'd rather not make the code more complicated to work around the limitations of specific serializers. I think I'd prefer to use the default derives.

**Comment by PradeepKumarRajamanickam** [comment]
Cool. Shall we merge this PR?

**Comment by ndarilek** [comment]
Would love to see this merged. I was using bevy_input_map, and this plus the custom serializer seems like it'd unblock its, and in turn my, migration to 0.2. Also hoping to help out a bit with input_map, but I have limited time for that, and doing so is a bit less appealing if the game I'm knocking together has to remain on 0.1.

Thanks.

**Pull request merged**
