### PR TITLE
[Merged by Bors] - Implement ReflectValue serialization for Duration

### LINKED ISSUE #3277: Type 'core::time::Duration' does not support ReflectValue serialization
## What problem does this solve or what need does it fill?

I'm building a general purpose plugin for doing rollback networking for bevy and a game using that. To support clients reconnecting after disconnect, I need to serialize relevant state and transmit it to reconnecting clients. It's common for `Timer`s to be relevant for gameplay logic, and those require serializing `Duration`s.

## What solution would you like?

Implement `ReflectValue` serialization for `Duration` and other `core` types. 

## What alternative(s) have you considered?

To unblock myself, I can reimplement `Timer` and `Duration` with a custom `MyDuration` type that derives `Reflect`. Doing that is not ideal for a myriad of reasons, but probably necessary to continue progress on my project.

### PR DESCRIPTION
**Pull request by jcornaz**
# Objective

Resolves #3277 

Currenty if we try to serialize a scene that contains a `Duration` (which is very common, since `Timer` contains one), we get an error saying:

> Type 'core::time::Duration' does not support ReflectValue serialization

## Solution

Let `Duration` implement `SerializeValue`.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Looks good to me. Could you do the same quick for `Instant` in this PR? It's not quite as immediately useful, but it's an important complement to `Duration`.

**Comment by jcornaz** [comment]
> Looks good to me. Could you do the same quick for `Instant` in this PR? It's not quite as immediately useful, but it's an important complement to `Duration`.

Mmm... that one is less straightforward. Because `serde` doesn't implement `Serialize` and `Deserialize`. And more generally, it is not that easy (or even possible?) because `Instant` is an opaque type. 

> Instants are opaque types that can only be compared to one another. There is no method to get "the number of seconds" from an instant. Instead, it only allows measuring the duration between two instants (or comparing two instants).

**Comment by alice-i-cecile** [comment]
>Mmm... that one is less straightforward. Because serde doesn't implement Serialize and Deserialize for Instant. And more generally, it is not that easy (or even possible?) because Instant is an opaque type.

Sounds good to me. I'll keep an eye out for this when designing Bevy's timers and related work: hopefully we should never need to store instants.

**Review by alice-i-cecile — APPROVED** [review]

**Pull request closed without merging**
