### PR TITLE
[Merged by Bors] - Make many_cubes example more interesting

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Make the many_cubes example more interesting (and look more like many_sprites)

## Solution

- Actually display many cubes
- Move the camera around

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I like it! Random cube colors would also be nice for consistency and interest, but I'm unsure if that will affect performance.

**Comment by mockersf** [comment]
added a light so that the cubes show their true color

https://user-images.githubusercontent.com/8672791/155239283-f8bbcabf-abe6-4809-b512-4e2768c3b62e.mp4

**Review by superdump — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@mockersf, can you rebase this when you get a chance?

**Comment by mockersf** [comment]
done!

**Comment by DJMcNab** [comment]
I hadn't seen this PR until it was merged, but I'm not sure I like this. 

I just ran it now, and it's quite uncomfortable to watch. I only had it on for 700 frames apparently (31 seconds), and my eyes are still 'sore' almost 5 minutes later.

I'm not sure why that is, but I assume it's creating some nasty moiré patterns?

**Comment by alice-i-cecile** [comment]
Fair. Perhaps we can make it less uncomfortable in a follow-up PR?

**Comment by mockersf** [comment]
Sorry for that. I did find it a little dizzying, but that was fixed for my by adding a bigger cube to act as a reference point.

Would it work to slow down the camera rotations?

**Comment by mockersf** [comment]
I tried slowing down the camera and add extra space between the cubes: https://github.com/mockersf/bevy/tree/many-calm-cubes

**Comment by DJMcNab** [comment]
So I just tried that branch, and get a similar feeling, although I think it might be less bad. 

I think it would still be better as slower though. Unfortunately, I don't have any real suggestions for making it better :(

**Comment by alice-i-cecile** [comment]
We could do very basic user-control perhaps? That would make it more useful as an example, but less useful as a quasi-benchmark.

**Comment by mockersf** [comment]
I tried a few other things in https://github.com/bevyengine/bevy/pull/4117

**Pull request closed without merging**
