### PR TITLE
Gng example

### PR DESCRIPTION
**Pull request by fabiao**
I added a sprite example based on ghouls'n ghosts main player with basic movements and animations. I had to modify CullMode::Back to CullMode::None for easily flip horizontal animations only rotating y axis.

### CODE REVIEW

**Comment by StarArawn** [comment]
I opened a PR to address sprite flipping here: #248

**Comment by cart** [comment]
Whats the license on that sprite sheet? Unless Ghouls n' Ghosts is in the public domain, I'd want to remove the "ghouls n' ghosts" naming and sprites in favor of something more generic

**Comment by fabiao** [comment]
Yes, no prob for renaming stuff, i grabbed assets from a remake called
ghouls'n ghost remake from valarsoft:
http://www.valarsoft.com/?stage=7&action=2&downloadID=84

Il giorno ven 21 ago 2020 alle ore 02:28 Carter Anderson <
notifications@github.com> ha scritto:

**Comment by cart** [comment]
I like the idea of having a "platformer" example, but I think I'd want it to be a little more complete first. Ex: some sort of game play loop, player drops back down to the floor when jumping, etc.

Mind if we transition this to a draft pr?

**Comment by fabiao** [comment]
No prob, it was an exercise for testing animations reacting to user inputs. I also wanted to add some basic physics for jump and shooting weapons, maybe in a while

**Comment by cart** [comment]
For now I think I'll close this out, but I'm happy to re-open it if you ever pick this back up.

**Pull request closed without merging**
