### PR TITLE
Fix potential deadlock in `AssetServer` on single-threaded modes.

### LINKED ISSUE #15807: Possible deadlock in AssetServer in single-threaded modes.
## Bevy version

HEAD at `bd0c74644fda1c6cbdd2524c2920e81fce063648`

## What you did

According to the docs at https://github.com/bevyengine/bevy/blob/bd0c74644fda1c6cbdd2524c2920e81fce063648/crates/bevy_asset/src/server/mod.rs#L423C1-L425C21, we're supposed to be dropping the infos guard. However this is no longer true after #15509.

We should either pass the mutex guard to this function, or drop the guard before the function call.

### PR DESCRIPTION
**Pull request by andriyDev**
# Objective

Fixes #15807 

## Solution

We move the guard into this function.

## Testing

N/A, This is just reverting to the old behavior before #15509.

### CODE REVIEW

**Comment by andriyDev** [comment]
Note an alternative is to do the dropping of the lock outside the function, but that would mean duplicating it twice.

**Review by aecsocket — APPROVED** [review]
I think this change makes sense, I don't entirely like passing the `RwLockWriteGuard` across functions but that's fine if this logic is more correct.

**Review by JMS55 — APPROVED** [review]
Didn't test, but seems fine to me.

**Comment by mockersf** [comment]
does this fix also https://github.com/bevyengine/bevy/issues/15508?

**Comment by andriyDev** [comment]
> does this fix also #15508?

Yes, this also seems to fix #15508, at least the reproduction case provided (I tested it on HEAD first to make sure it was still broken). I don't know why @alice-i-cecile reopened the issue though, so maybe there's another cause?

**Pull request merged**
