### PR TITLE
[Merged by Bors] - Add `mesa-vulkan-drivers` to Debian install

### PR DESCRIPTION
**Pull request by Psychoticpotato**
I received the `Unable to find GPU` error, but I got it to render by using this package.  Not 100% sure if a better option exists.

### CODE REVIEW

**Review by DJMcNab — COMMENTED** [review]
Thanks for the pull request - Welcome!

It might be possible that these drivers could conflict with other drivers the user already has installed. I don't have enough domain specific to knowledge to sign off on this

Maybe it would be better to comment: 
> You might also need to install vulkan support using packages such as `mesa-vulkan-drivers`.

instead.

**Comment by NiklasEi** [comment]
If I look at my history I had to install `nvidia-graphics-drivers-396 nvidia-settings vulkan vulkan-utils` to get the bevy examples to run. The difference seems to be AMD/Nvidia GPUs.

It would definitely be helpful to extend the info at https://bevyengine.org/learn/book/troubleshooting/

**Comment by cart** [comment]
Yeah drivers are device specific so we can't add this as generic advice. Given that package names are distro-specific, I think they should still live in `linux_dependencies.md`, but probably under a new "graphics drivers" section for different devices/driver preferences.

The troubleshooting page should probably link to `linux_dependencies.md` to avoid duplicating information (and avoid adding a bunch of noise to a generic "troubleshooting" page).

**Comment by Psychoticpotato** [comment]
Gotcha, so adding `mesa-vulkan-drivers` to the list of possible installs on troubleshooting page.  Should the troubleshooting page be referenced on `linux_dependencies.md`, or should I have just paid better attention, :P?

**Comment by Psychoticpotato** [comment]
Good points, everyone.  I moved it into a separate line noting the graphics info.  Do you think it should be a full section with a header, like @cart suggests?  I can see it being useful, but there also isn't a whole lot of info at the moment.

**Comment by cart** [comment]
I think what we have now is reasonable and has the benefit of being terse. I'm happy to merge this as-is.

**Pull request closed without merging**
