### PR TITLE
Split up `gamepad.rs` into smaller chunks

### PR DESCRIPTION
**Pull request by KDecay**
# Objective

- Part of the splitting process of #3692.

## Solution

- Split up `gamepad.rs` into smaller chunks.

## Reasons

- It makes navigating the file structure easier.
- It helps to find particular things faster.
- It's a good practice to not just dump everything into one huge file.
- Discussion in #3692.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Yes please; this makes this sort of file so much easier to navigate and extend.

**Comment by IceSentry** [comment]
Is it really that big? It's just 370 lines of not tests and most of it is just type declarations used in the 2 systems in the file. Personally, there's nothing about this file or the other files in the input module that feels troublesome to work with. I personally prefer having all those things in the same file, I actually find it easier to find things this way and I like not having to constantly change files. 

To be clear, I don't think it's wrong, but it just doesn't feel necessary to me and I prefer how it is currently.

I'll let cart decide on this one and related PRs because this seems to be something very subjective.

**Comment by cart** [comment]
Yeah I think this split is too aggressive. I don't buy the "one struct per file" pattern (common in languages like C#), especially for Rust (where that pattern is very uncommon). Files should be used to group by subject and roughly by module. The subject here is "gamepads".

This is definitely a matter of opinion, but I think this takes things a bit too far.

**Comment by KDecay** [comment]
I agree that this is a matter of taste. I feel like this file definitely needs some splitting, but if that is not perceived this way by others than that's good to know. 

@cart
Is your opinion similar for the other 3 PRs I made (see below)? If so then I'll close all of them so that I can continue working on the splitting process of #3692.

# Related PRs

- #4315
- #4316
- #4317

**Comment by cart** [comment]
Yeah this opinion applies to all of those PRs and my preference is to close them. Thanks for being understanding! Feel free to continue discussing this if you have strong opinions. If you garner enough support for this pattern, I'll revisit this decision.

**Comment by KDecay** [comment]
There's no need to fight about this since this is just matter of taste and if this is an unusual pattern for `Rust` then that's totally fine to me. I'm probably biased by using C# at work :D Thanks for sharing your thoughts!

**Pull request closed without merging**
