### PR TITLE
[Merged by Bors] - support all line endings in shader preprocessor

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Advance uses of shaders seems to often fail for Windows users
- Bevy split lines on `'\n'` which messes with windows line endings

## Solution

- Uses Rust built in https://doc.rust-lang.org/std/primitive.str.html#method.lines

### CODE REVIEW

**Review by superdump — APPROVED** [review]
Good call!

**Comment by superdump** [comment]
Well. Approved aside from it breaking tests. :)

**Comment by mockersf** [comment]
fixed!

**Review by IceSentry — APPROVED** [review]

**Pull request closed without merging**
