### PR TITLE
UI batching Fix

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Reimplement #8793 on top of the recent rendering changes.

## Solution

The batch creation logic is quite convoluted, but I tested it on enough examples to convince myself that it works.

The initial value of `batch_image_handle` is changed from `HandleId::Id(Uuid::nil(), u64::MAX)` to `DEFAULT_IMAGE_HANDLE.id()`, which allowed me to make the if-block simpler I think.

The default image from `DEFAULT_IMAGE_HANDLE` is always inserted into `UiImageBindGroups` even if it's not used. I tried to add a check so that it would be only inserted when there is only one batch using the default image but this crashed.

---

## Changelog
`prepare_uinodes`
* Changed the  initial value of  `batch_image_handle` to `DEFAULT_IMAGE_HANDLE.id()`.
*  The default image is added to the UI image bind groups before assembling the batches. 
* A new `UiBatch` isn't created when the next `ExtractedUiNode`s image is set to `DEFAULT_IMAGE_HANDLE` (unless it is the first item in the UI phase items list).

### CODE REVIEW

**Comment by rparrett** [comment]
Commenting to clarify that this is fixing a performance regression introduced in this cycle.

I'm assuming that this needs updating after #9685 and #9903.

**Comment by superdump** [comment]
This needs updating. And as it is addressing a performance regression, it would be great to see some benchmarks.

**Comment by JMS55** [comment]
@ickshonpe this is currently on the 0.12 milestone, and the release will be shortly. Do you have time to update and benchmark this PR? (no worries if the answer is no!)

**Comment by ickshonpe** [comment]
Updated, I'll add some benchmarks in a bit.

**Comment by ickshonpe** [comment]
yellow is this PR, red is main
```
cargo run --profile stress-test --features trace_tracy --example many_buttons
```

Frames
ui-batching-fix-frames

`prepare_uinodes`
ui-batching-prepare

`bevy_ui::render::render_pass::UiPassNode`
ui_pass_node

**Review by superdump — APPROVED** [review]

**Review by cart — APPROVED** [review]

**Pull request merged**
