### PR TITLE
[Merged by Bors] - Use `cbrt()` instead of `powf(1./3.)`

### PR DESCRIPTION
**Pull request by targrub**
# Objective

- Use cube root library function instead of handrolling.

## Solution

- Instead of `powf(1./3.)` use `cbrt()`.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Merging as trivial.

bors r+

**Comment by james7132** [comment]
This is fine in an example, but I don't think the implementation for `cbrt` is well defined in Rust stdlib, nor in the IEEE-754 spec. If we want to maintain Bevy's use for deterministic/reproducible simulation, we should avoid stepping outside of those bounds in actual engine code.

**Comment by alice-i-cecile** [comment]
Oof, that's really frustrating. Noted!

**Comment by targrub** [comment]
I understand what you're saying (and I know Alice does as well, since we're both Factorio fans), but...
Is this an explicit, documented goal of Bevy?

**Comment by alice-i-cecile** [comment]
Explicit yes, documented not really. We should probably add it to the contributing guide.

**Pull request closed without merging**
