### PR TITLE
ci able to override how example runs

### PR DESCRIPTION
**Pull request by shuoli84**
# Objective

* provide extra features to example

### CODE REVIEW

**Comment by shuoli84** [comment]
This pr is a follow up for #7825 , will merge after #7825 merged.

**Comment by alice-i-cecile** [comment]
#7825 is now merged :) This looks to test the failing `debug_asset_server` example in CI?

**Comment by shuoli84** [comment]
> #7825 is now merged :) This looks to test the failing `debug_asset_server` example in CI?

Yap, this runs the example "load_gltf" with "debug_asset_server" feature enabled in existing "run-examples" flow. Now it checks whether there is a example_name.sh file, if yes, then just launch that script, otherwise fallback to standard `cargo run`

**Comment by shuoli84** [comment]
Hmm, it seems there are multiple places with run-examples, and the running argument is kinda different...

**Comment by shuoli84** [comment]
@alice-i-cecile any idea? Is this the right way to go? I can fix the above issue by passing extra features through environment variables. hmm. Or is "adding extra feature for run-examples" a good thing?

**Comment by alice-i-cecile** [comment]
I'm not personally confident on the right design here: that's why I requested review from our CI ninja @mockersf ;)

**Comment by shuoli84** [comment]
ping

**Comment by shuoli84** [comment]
ping?

**Review by mockersf — CHANGES_REQUESTED** [review]
This code is getting complex enough that we should move it to a rust script rather than keep it as a CI script.

It could be quite a bit more complex, @shuoli84 do you think you can do it?

**Comment by shuoli84** [comment]
> This code is getting complex enough that we should move it to a rust script rather than keep it as a CI script.
> 
> It could be quite a bit more complex, @shuoli84 do you think you can do it?

Not quite sure what do you mean by "rust script". Is there an example?

**Comment by alice-i-cecile** [comment]
The CI script in the tools folder is a good example of this :)

**Comment by alice-i-cecile** [comment]
@shuoli84 are you comfortable tackling this? If not, I'm happy to add `Adopt-Me` to this PR and others can help pick up this work.

**Comment by shuoli84** [comment]
> @shuoli84 are you comfortable tackling this? If not, I'm happy to add `Adopt-Me` to this PR and others can help pick up this work.

Hi alice, I'm happy to either transfer this to other or just close it. Sorry for the late reply..

**Comment by alice-i-cecile** [comment]
No worries, thanks for the reply. Closing this out for now but we can redo it as needed.

**Pull request closed without merging**
