### PR TITLE
SimpleMeshBuilder

### PR DESCRIPTION
**Pull request by stepancheg**
Constructing `Mesh` manually is somewhat not trivial.

`SimpleMeshBuilder` is a "builder" for mesh with positions, normals, uvs.

I use it my project, so I decided to submit it to bevy project. Not sure if it is universally helpful.

### CODE REVIEW

**Comment by Robert7301201** [comment]
`TotalVec2` and `TotalVec3` should probably be `bevy::math::u32::UVec2` and `bevy::math::u32::UVec3`. Is there an advantage to using `TotalVec2` and `TotalVec3`?

**Comment by stepancheg** [comment]
`UVec2` and `UVec3` store integer coordinates. `TotalVec2` and `TotalVec3` store float coordinates by transmuting them to integers.

So `UVec2` and `UVec3` could be used, but that might be misleading.

But I can get rid of `TotalVec2` and `TotalVec3` and just replace them with tuples.

**Comment by Robert7301201** [comment]
I think I understand now. It's a workaround to hash a Vec3 since floats can't be hashed.

I found a relevant discussion for the upstream glam-rs: https://github.com/bitshifter/glam-rs/issues/123. That discussion links to https://internals.rust-lang.org/t/f32-f64-should-implement-hash/5436/33 which does offer the workaround of transmuting to u32.

I'd prefer keeping `Total2` and `Total3` since it clues the reader in that they're doing something special. Maybe consider renaming to `HashVec2` `HashVec3`. Either way it'd be a good idea to document that their intended purpose is for hashing, unless I'm glossing over some other functionality.

That being said though, I wonder if it would be better to just have duplicate vertices. Would this be intended as more of a prototyping tool and some inefficiencies are acceptable, or should this be optimized?

**Comment by stepancheg** [comment]
> Maybe consider renaming

OK, I'll try something.

> That being said though, I wonder if it would be better to just have duplicate vertices.

Might be a lot of duplication. Consider common mesh like this (e.g. when creating a sphere):

image

Here each vertex is shared by 6 triangles, and not deduplicating it may result in significant memory usage increase.

> Would this be intended as more of a prototyping tool and some inefficiencies are acceptable, or should this be optimized?

I'm not an enterprise game developer, so I don't really know how often people generate meshes programmatically rather than just loading them from GLTF.

**Comment by stepancheg** [comment]
Replaced `TotalVec2` and `TotalVec3` with simpler `SimpleVertexHashable`.

**Review by tychedelia — COMMENTED** [review]
Our mesh api is kind of annoying to work with but I feel like I'd like to better understand the pain points there and whether we can improve them rather than just adding a more normative "simple" type.

**Comment by cart** [comment]
Yup any proposal for a `SimpleX` type is an indicator that we need to improve our existing APIs, not add a new one. My gut reaction is that we should enumerate the problems being solved here and try to solve them in the core types.

**Comment by IceSentry** [comment]
I'd prefer seeing this in a crate first.

Also, this could potentially be implemented as free functions in the mesh module that take in the `&mut Mesh` and the fixed list of vertex data and append it to the end of the respective arrays.

**Comment by cart** [comment]
Yup closing this out as there appears to be rough consensus that doing this upstream isn't the move.

**Pull request closed without merging**
