### PR TITLE
Improve ci - install binaries instead of compiling

### PR DESCRIPTION
**Pull request by ameknite**
# Objective

Reduce time compiling crates in CI.

## Solution

- Install binaries using https://github.com/taiki-e/install-action/tree/v2/

install-actions uses github releases to find the binaries.
Uses [cargo-binstall](https://github.com/cargo-bins/cargo-binstall) as a fallback

### CODE REVIEW

**Review by BD103 — APPROVED** [review]
Good change, I'm going to try to rally on Discord to get this merged!

**Comment by BD103** [comment]
Also would you mind rebasing onto main? A few of the required checks have been modified after this PR was created, which is why it says some checks haven't been completed yet.

**Review by mockersf — CHANGES_REQUESTED** [review]
please put the version of the action everywhere

**Comment by BD103** [comment]
> please put the version of the action everywhere

Agreed, it would be good to target specific versions of the binaries so we don't have breaking changes.

```yml
- uses: taiki-e/install-action@v2
  with:
    tool: taplo-cli@0.9
```

I don't think we need to specify the patch version, but certainly the minor and major versions.

**Review by TimJentzsch — COMMENTED** [review]
Do you have some measurements on how much this improves the CI times?

It seems like this adds two additional security risks:

- The `install-action` action itself, which runs multiple shell scripts
- The release binaries which are being downloaded

Of course, there are always some risks involved when adding new dependencies and we can mitigate them by fixing the version of both the action (note that the commit hashes are safer than the version tags) and the installed tools.
Just wondering if it's worth it in this case

**Pull request closed without merging**
