### PR TITLE
[Merged by Bors] - Update glam 0.22, hexasphere 8.0, encase 0.4

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Update glam to 0.22, hexasphere to 8.0, encase to 0.4

## Solution

- Update glam to 0.22, hexasphere to 8.0, encase to 0.4
- ~~waiting on https://github.com/teoxoy/encase/pull/17 and https://github.com/OptimisticPeach/hexasphere/pull/13~~

### CODE REVIEW

**Review by james7132 — APPROVED** [review]
Approval contingent on the updates to encase.

**Review by superdump — APPROVED** [review]
Also approved as long as the upstream deps also get updated.

**Comment by teoxoy** [comment]
Just released encase v0.4.

**Review by devil-ira — APPROVED** [review]

**Review by rodolphito — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]

**Pull request closed without merging**
