### PR TITLE
Replace `unwrap` calls with `expect` in `bevy_sprite` crate 

### PR DESCRIPTION
**Pull request by mnmaita**
# Objective

- Addresses https://github.com/bevyengine/bevy/issues/3899 for `bevy_sprite` crate.

## Solution

- Replaced all `unwrap` calls with `expect` calls and added comprehensive error messages when these statements panic.

Feel free to review the error messages and provide suggestions on how they could be made clearer.

### CODE REVIEW

**Comment by mnmaita** [comment]
Should I use the following pattern (suggested by `clippy`) on places where I call a `format!` macro as the argument for the `expect` call?

```rust
foobar.unwrap_or_else(|_| panic!(/* ... */))
```

**Comment by mnmaita** [comment]
Also, I was trying to display `HandleId`s as part of some errors but noticed it's an enum with tuple variants and it doesn't implement `Debug`, so any suggestion on how to clarify messages on loops or places where a hint on the entity/handle/etc. could be useful is very welcome.

**Comment by james7132** [comment]
> Should I use the following pattern (suggested by `clippy`) on places where I call a `format!` macro as the argument for the `expect` call?
> 
> ```rust
> foobar.unwrap_or_else(|_| panic!(/* ... */))
> ```

Please do, otherwise there will be a String allocated even when there isn't an error.

**Comment by alice-i-cecile** [comment]
Closing per discussion in #3899 <3

**Pull request closed without merging**
