### PR TITLE
Smaller TAA fixes

### PR DESCRIPTION
**Pull request by JMS55**
Extracted the easy stuff from #8974 .

# Problem
1. Commands from `update_previous_view_projections` would crash when matching entities were despawned.
2. `TaaPipelineId` and `draw_3d_graph` module were not public.
3. When the motion vectors pointed to pixels that are now off screen, a smearing artifact could occur.

# Solution
1. Use `try_insert` command instead.
2. Make them public, renaming to `TemporalAntiAliasPipelineId`.
3. Check for this case, and ignore history for pixels that are off-screen.

### CODE REVIEW

**Review by alice-i-cecile — COMMENTED** [review]
Commit one: strongly in favor of.

Commit two: not clear on the motivation of this.

Commit three: a before/after screenshot would be really helpful.

**Comment by Diddykonga** [comment]
Nitpick, but enlarging of names should be discouraged unless it is an new/bespoke concept or term, where as TAA is an industry standard and can be found with a simple google search if someone doesn't know what it stands for.

**Review by coreh — APPROVED** [review]
If we do end up renaming things, do we also need a migration guide section? Or does this not apply because of `experimental`?

**Comment by alice-i-cecile** [comment]
> If we do end up renaming things, do we also need a migration guide section? Or does this not apply because of `experimental`?

The only renames are currently internal, so it's not a breaking change :)

**Comment by DGriffin91** [comment]
I won't have time to test this later this week so I'm testing it now given that it already has an approval and is on the milestone.

This PR does not fix the edge smearing issue:
taa_screenshot-0

**Comment by JMS55** [comment]
@DGriffin91 thanks for the test! Should be fixed now. The approach I was using before doesn't work with the way TAA is currently setup, so when I pulled out of the larger changes it wasn't working.

**Review by rodolphito — APPROVED** [review]

**Comment by rparrett** [comment]
Tested with the example from #10200 and the obvious edge blurring is no longer present. Can't really comment beyond that.

**Pull request merged**
