### PR TITLE
Migrate BuildChildren to impl IntoIterator<Item = impl Borrow<Entity>>

### PR DESCRIPTION
**Pull request by emwalker**
# Objective

Fixes https://github.com/bevyengine/bevy/issues/7229

This PR picks up where https://github.com/bevyengine/bevy/pull/7244 leaves off.  In this PR we migrate the remaining methods on the `BuildChildren` trait to use `children: impl IntoIterator<Item = Entity>` instead of `children: &[Entity]`.  In the process we change the move semantics.  (I only created this PR when I saw that the earlier one had been dormant for several weeks.)

cc @LamequeFernandes, @adam-shih, @XaurDesu

## Open Questions
- [x] Should other traits in this file should be migrated as well?
- [x] Should some of the methods use `impl Iterator<Item = &'e Entity>` instead, in order to avoid consuming the input?
- [ ] What if anything should go in the [Migration Guide](https://github.com/bevyengine/bevy/pull/7939#issuecomment-1457708983) section?

## Changelog

Changed: Methods on `BuildWorldChildren` and `BuildChildren` that accept `&[Entity]` updated to take `impl IntoIterator<Item = impl Borrow<Entity>>` instead.

## Migration Guide

TBD  (Use of `impl Iterator<Item = &'e Entity>` in place of `&[Entity]` seems backwards incompatible.)

### CODE REVIEW

**Review by james7132 — APPROVED** [review]

**Review by devil-ira — CHANGES_REQUESTED** [review]
The methods on `EntityMut` should also be changed

**Comment by emwalker** [comment]
@devil-ira sounds good.  Just so I don't go off on a tangent, can you link to an example or two of methods you want to modify?  I looked in [crates/bevy_ecs/src/world/entity_ref.rs](https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/world/entity_ref.rs), and the only function I found there with a slice argument was [sorted_remove](https://github.com/bevyengine/bevy/blob/c09a9f0c7366d0797a42f8c59724500465bb281d/crates/bevy_ecs/src/world/entity_ref.rs#L775-L788).  But perhaps you have something more general in mind.

@devil-ira, @james7132 any thoughts on the questions I added to the description?

**Comment by devil-ira** [comment]
Ah, sorry I should have been more clear. I was referring to the `BuildWorldChildren` impl for `EntityMut` in the same file (`child_builder.rs`)

**Comment by emwalker** [comment]
Seems there's some errors that are being picked up in CI that I don't see in my smoke tests when running things locally.  This evening or tomorrow I'll try to reproduce what CI is doing.

**Comment by emwalker** [comment]
I was able to mostly repro what CI is doing by updating to the latest `stable` version using `rustup` and then running this command:

```sh
$ cargo run -p ci -- lints
```

I say "mostly" because the linter wanted me to fix a linting issue in `crates/bevy_reflect/src/enums/dynamic_enum.rs`, which wasn't touched in this PR, so I suspect that my local run isn't quite the same as CI on GitHub.

**Comment by emwalker** [comment]
@devil-ira is this good to go, or is there something else that will be needed?

**Comment by devil-ira** [comment]
> Should some of the methods use impl Iterator<Item = &'e Entity> instead, in order to avoid consuming the input?

What you could use is `impl IntoIterator<Item = impl Borrow<Entity>>` which accepts both owned values and references. That should avoid this being breaking change as well. 
This does mean you have to do `SmallVec::from_iter(children.into_iter().map(|e| *e.borrow()))` instead.

**Comment by emwalker** [comment]
> What you could use is impl IntoIterator<Item = impl Borrow<Entity>> which accepts both owned values and references.

Done.

**Comment by emwalker** [comment]
Might be good to move [this function](https://github.com/emwalker/bevy/blob/8eb0440f1ed0f075ed488e7efa36ba0f8bb37cad/crates/bevy_hierarchy/src/child_builder.rs#L69) over as well.

**Comment by emwalker** [comment]
As I work through this PR, I'm beginning to wonder whether it improves upon the existing ergonomics, or whether it makes it harder to work with the `children` argument than when it was passed as a `&[Entity]` slice.

**Comment by emwalker** [comment]
Closing per this discussion: https://github.com/bevyengine/bevy/issues/7229#issuecomment-1465434249

**Pull request closed without merging**
