### PR TITLE
Change relevant methods in World and co to return ResMut

### LINKED ISSUE #11765: Get `ResMut` of a resource from `World`
> I can change it so World::resource_mut returns ResMut instead of Mut as well if that's desired, but that could also be added later in a seperate pr.

> Let's keep this split this out.

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/issues/11561#issuecomment-1913222497_
            
## What problem does this solve or what need does it fill?

There should be a way to get change-detection-enabled, mutable access to a resource from the `World`. The type that's conventionally used for that is `ResMut`

## What solution would you like?

Add a method to `World` that supports that / change the current implementation of `resource_mut` (and the like) to get `ResMut` instead of `Mut` and/or `&mut T`

## What alternative(s) have you considered?

Keep as is

### PR DESCRIPTION
**Pull request by solis-lumine-vorago**
# Objective

- Fixes #11765 

## Solution

- Changed the current implementations to use `ResMut` instead of `Mut`

---

## Changelog

- In `World`: `resource_mut`, `get_resource_mut`, `get_resource_or_insert_with` now return `ResMut` / `Option<ResMut>` and `resource_scope`now accepts a function parameter of type `impl FnOnce(&mut World, ResMut<R>) -> U`
- In `UnsafeWorldCell`: `get_resource_mut` now returns `Option<ResMut>`
- Changed internal uses of these methods to use `ResMut` aswell.
- `ResMut<R>` now implements `From<Mut<R: Resource>>`

## Migration Guide

- For most use cases this should not require any action besides changing `Mut<T>` to `ResMut<T>` since they are very similar to each other and  `Mut<T>` implements `From<ResMut<'w, T>> for Mut<'w, T>`. But you could just call `.into()` if any problems arise.

### CODE REVIEW

**Review by Adamkob12 — APPROVED** [review]
The documentation of most methods that were changed don't mention that the returned value supports change detection, I think it would be nice if they would. But that's how it was before the PR so it's not critical to add it here.

**Review by pablo-lua — APPROVED** [review]
I think this PR can greatly help the user to understand whats going on by returning what the user expects to find: I requested a resource_mut, I'm expecting a `ResMut`, so this is great for consistency.

**Review by JoJoJet — CHANGES_REQUESTED** [review]
I don't see much reason to change `Mut<>` to `ResMut<>`. They do the same thing -- the only reason that `ResMut` exists is because with `SystemParam`, you have to distinguish between components and resources via the type itself. Here, we're able to use the method's name to distinguish between components and resources, making `ResMut` unnecessary. We already treat `Mut` as the "canonical" change detection smart pointer: `ResMut::reborrow` returns `Mut`, for example.

[Originally posted here](https://github.com/bevyengine/bevy/pull/9940#issuecomment-1740243280)

**Comment by JoJoJet** [comment]
Thank you for the PR, we're likely going to move forward with the direction described in #11825

**Pull request closed without merging**
