### PR TITLE
[Merged by Bors] - Update toml_edit to 0.18

### PR DESCRIPTION
**Pull request by devil-ira**
Removes a duplicate dependency from the tree

### CODE REVIEW

**Comment by TimJentzsch** [comment]
If a duplicate dependency got removed, `deny.toml` should probably be updated to disallow that dependency again

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
it's not in the deny.toml file

**Review by TimJentzsch — APPROVED** [review]

**Review by james7132 — APPROVED** [review]
bors r+

**Comment by james7132** [comment]
bors retry

**Pull request closed without merging**
