### PR TITLE
[Merged by Bors] - Spherical area lights example

### PR DESCRIPTION
**Pull request by cart**
I was putting together the Bevy 0.6 release blog post and wanted a simple area light radius example, so here we are :)

image

### CODE REVIEW

**Review by jakobhellermann — APPROVED** [review]
Looks good!

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Code quality and clarity are great as always. LGTM!

**Comment by mockersf** [comment]
(link failure on reddit)

**Pull request closed without merging**
