### PR TITLE
[Merged by Bors] - Expose resource change detection on World

### PR DESCRIPTION
**Pull request by TheRawMeatball**

### CODE REVIEW

**Comment by Davier** [comment]
I'd prefer returning `Res<T>` instead of `&T` in `World::get_resource`, but I guess that's a small overhead. Or maybe a single method that returns `ChangeTrackers<T>` for a resource.

**Comment by alice-i-cecile** [comment]
For posterity, here was the Discord [conversation](https://discord.com/channels/691052431525675048/692572690833473578/823085264171171870) that prompted this PR.

**Comment by cart** [comment]
@Davier yeah I do think its worth considering "unifying" the SystemParam and World return types (ex: return Res, ResMut, NonSend, etc instead of `&T `and `Mut<T>`).

At least for 0.5, I'm cool with the api as written. We can just do a breaking change later if needed.

**Pull request closed without merging**
