### PR TITLE
Make `StandardMaterial` bindless.

### PR DESCRIPTION
**Pull request by pcwalton**
This commit makes `StandardMaterial` use bindless textures, as implemented in PR #16368. Non-bindless mode, as used for example in Metal and WebGL 2, remains fully supported via a plethora of `#ifdef BINDLESS` preprocessor definitions.

Unfortunately, this PR introduces quite a bit of unsightliness into the PBR shaders. This is a result of the fact that WGSL supports neither passing binding arrays to functions nor passing individual *elements* of binding arrays to functions, except directly to texture sample functions. Thus we're unable to use the `sample_texture` abstraction that helped abstract over the meshlet and non-meshlet paths. I don't think there's anything we can do to help this other than to suggest improvements to upstream Naga.

### CODE REVIEW

**Review by JMS55 — APPROVED** [review]
Oh boy, absolutely terrible code 😅. We are unlikely to get any improvements to this in naga anytime soon afaik. I think we might want to look into writing a simple macro in naga_oil or bevy for texture sampling.

**Comment by pcwalton** [comment]
Yeah, I'd love a macro in `naga_oil`. We could do a lot with macros, not just this. For example, we could abstract over bindless/non-bindless declarations.

**Review by kristoff3r — APPROVED** [review]
My eyes might have glazed over at some point, but looks correct and tested pbr example on linux+webgl2.

I agree we need macros or similar very soon, the pbr shaders weren't pretty before but they're getting borderline unreadable except for mechanical changes like this.

**Comment by alice-i-cecile** [comment]
Testing this via an [example run](https://github.com/TheBevyFlock/bevy-example-runner/actions/runs/12248580234) then merging. I'm not pleased with the reduced clarity of the shaders, but I agree that this is not the place to solve it (nor should this be blocked on that).

**Comment by pcwalton** [comment]
Example run is green.

**Comment by rparrett** [comment]
The example run completed successfully, but shows differences in `fog_volumes` and `volumetric_fog` on macOS and `meshlet` on linux which seem to be breakage.

https://pixel-eagle.com/project/B25A040A-A980-4602-B90C-D480AB84076D?filter=PR-16644

**Pull request merged**
