### PR TITLE
Expose mutable Animation Clips

### LINKED ISSUE #13052: Mutable Animation Clips
Hello, 

I am trying to write a skeletal animation edition tool using bevy. However, the animation clips used by bevy are read only. 
I understand that this is probably due to the fact that animation assets are tied to their loading files and the logic of having code modifying it can seem weird. However for a game editor I believe it would still make sense to have tools that allow animation edition within bevy ? 

Would it be possible to have mutable access to VariableCurves or expose functions that would allow the modification of animation asset inside bevy ? 

My goal is then to export this animation into a brand new animation file. 

For now the only solution I can think of is to fork bevy and force this mutable animation setup OR make a new animation plugin which would consist of a lot of duplicated code. Another way would be to create a brand new AnimationClip everytime I make an edit using the only mutable function exposed by AnimationClip (add_curve_to_target) but this would kill my performance... 

I'm failry new to Rust and Bevy so bare with me if there are obvious solutions. 
Thanks !

### PR DESCRIPTION
**Pull request by nzhao95**
# Objective

- Be able to edit animation inside the editor and save them once modified. This will allow bevy to modify animation assets with code. 
- Fixes #13052

## Solution

- Expose the previously const getters of the Animation curves

---

### CODE REVIEW

**Review by mweatherley — APPROVED** [review]
Looks pretty straightforward!

**Comment by NthTensor** [comment]
Looks good, thanks for working on this.

I want to double check that this won't cause problems for possible animation graph optimization/baking, but I'll approve once that's covered.

**Comment by nzhao95** [comment]
Thanks for the review ! 
I guess it really depends on how it's being used in the end. If we want to modify some curve values it shouldn't be much concern but it we want to modify the structure of the animation itself with path changes that are optimized through hashmaps then it wouldn't work using those getters, it would be better to rewrite the animation clip altogether. 
Finally one issue that this can lead to is when the duration is not correctly set. I think that ideally instead of offering mutable getters the better way is to have a bunch of setters exposed like an API , for instance rotate_bone_at_time, translate, add key etc.. that will allow the system to modify everything needed behind the scene. But that's a much bigger change

**Comment by nzhao95** [comment]
I am going to use those getters to write those functions and if they work well on my code and you guys are interested I could try and see how it could be setup cleanly inside bevy directly. For now it's still very early stage

**Review by NthTensor — APPROVED** [review]
Looks like we are all good! This should play very nicely with the animation graphs.

**Pull request merged**
