### PR TITLE
Example with repeated texture

### LINKED ISSUE #11136: Add an example demonstrating how to repeat textures
This is a simple adoption of https://github.com/bevyengine/bevy/issues/11109.

### PR DESCRIPTION
**Pull request by bugsweeper**
# Objective

Fixes #11136 .
Fixes https://github.com/bevyengine/bevy/pull/11161.

## Solution

- Set image sampler with repeated mode for u and v
- set uv_transform of StandardMaterial to resizing params

## Testing

Got this view on example run
image

### CODE REVIEW

**Comment by bugsweeper** [comment]
@alice-i-cecile May I ask you for a review?

**Review by alice-i-cecile — APPROVED** [review]
Perfect! Really straightforward and useful. Nice texture, and absolutely tiny.

**Review by matiqo15 — APPROVED** [review]

**Comment by matiqo15** [comment]
Could you add "Closes #11161" to the description?

**Comment by bugsweeper** [comment]
> Could you add "Closes #11161" to the description?

I don't know if this usefull after merge complete, but I changed PR description

**Pull request merged**
