### PR TITLE
Update window scale on window creation

### PR DESCRIPTION
**Pull request by StaffEngineer**
# Objective

Fixes https://github.com/bevyengine/bevy/issues/10407

I guess this is not a proper fix but more like a workaround, just sharing maybe someone will come up with better idea...

## Solution

`WindowScaleFactorChanged` is fired on window creation, allowing to refresh window scale.

### CODE REVIEW

**Comment by StaffEngineer** [comment]
> It looks like this sends an event but doesn't actually change anything in the app. Are additional changes needed to fix the text issues (follow-up PR?)?

Good question. Basically the situation is the following:
```
/// pre-PR#9826
2023-11-09T18:35:27.367530Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-11-09T18:35:27.435296Z  INFO windowbug: F0 WindowResolution { physical_width: 500, physical_height: 300, scale_factor_override: Some(1.9), scale_factor: 2.0 }
2023-11-09T18:35:27.450425Z  INFO windowbug: F1 WindowResolution { physical_width: 500, physical_height: 300, scale_factor_override: Some(1.9), scale_factor: 2.0 }

// post-PR#9826
2023-11-09T18:34:53.438184Z  INFO windowbug: F0 WindowResolution { physical_width: 500, physical_height: 300, scale_factor_override: Some(1.9), scale_factor: 1.0 }
2023-11-09T18:34:53.463914Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-11-09T18:34:53.523100Z  INFO windowbug: F1 WindowResolution { physical_width: 500, physical_height: 300, scale_factor_override: Some(1.9), scale_factor: 2.0 }
```
Window creation log may be printed after first frame (F0), so on Retina display it may be situation that

Frame 1: scale has default value 1
Frame 2: scale updated to 2

BUT `WindowScaleFactorChanged` is not fired in such scenario, the hotfix implements sending `WindowScaleFactorChanged` so userland can act on it. In my plugin I don't need to add any code since I'm already handling scale change event: https://github.com/StaffEngineer/bevy_cosmic_edit/blob/0758d43b98729a0368b0d1ea7a9412581672ac97/src/render.rs#L479

I am not sure that this is a proper fix, another option is to revert PR#9826... or maybe someone more familiar with the engine internals has better idea to tackle this issue.

**Comment by alice-i-cecile** [comment]
Can you test: is this change still required following the merging of https://github.com/bevyengine/bevy/pull/10389?

I strongly suspect that this was introduced during #9826.

**Comment by alice-i-cecile** [comment]
@devil-ira, I would appreciate your input here as well if you have opinions.

**Comment by alice-i-cecile** [comment]
These changes seem basically fine to me as a robustness improvement / workaround, but I'd like to verify that we can reproduce the problem before merging.

**Comment by StaffEngineer** [comment]
> It seems like winit events are not sent in some circumstances.

@UkoeHB in this scenario it's another situation, smt like:


```
-- bevy's frame 1 (default window scale is used (value 1)): scale = 1
-- winit window is created (window scale is 2)
-- bevy's frame 2: scale 1
```

the current fix is basically

```
-- bevy's frame 1 (default window scale is used (value 1)): scale = 1
-- winit window is created (window scale is 2)
-- propogate window scale update using bevy's `WindowScaleFactorChanged` event
-- bevy's frame 2: scale = 2
```

**Comment by StaffEngineer** [comment]
> These changes seem basically fine to me as a robustness improvement / workaround, but I'd like to verify that we can reproduce the problem before merging.

Tested just now on the latest main ([33cd59f](https://github.com/bevyengine/bevy/commit/33cd59fb0489825b9a4628f59f89fc8af774e80a)). Issue still occurs for me.

**Comment by StaffEngineer** [comment]
> My question is, where is the scale changing so that a winit event used to be emitted but now is not emitted?

As far as I understand the code (may be wrong) _before_ user could read in setup system window scale and that value was "not default one" but from winit (2 for Retina display) (because window was created before setup system run)... so in the previous version of code we don't need to fire bevy's window scale event change... because it's always 2 for a Retina user :) 

I am not sure about invariants... code changes seems work fine for me but surely more testing is appreciated.

**Comment by mockersf** [comment]
I believe this is not the right fix. with this, text will be rendered once without the proper scale, then once more with it.

With #9826 or #10389, there is still an `update` running before the window is actually created in winit, so before we have the proper scale.

I think instead we should investigate on each platform where the proper step to create windows should be, and ensure it's correctly place relative to the update

**Comment by StaffEngineer** [comment]
@mockersf yep, completely agree thar proper fix is to move window creation back as it was in 0.11 for MacOS.

**Comment by StaffEngineer** [comment]
@mockersf what do you think about running recently introduced `update` call only for iOS?

https://github.com/bevyengine/bevy/compare/main...StaffEngineer:bevy:fix-macos-scaling#diff-b2fba3a0c86e496085ce7f0e3f1de5960cb754c7d215ed0f087aa556e529f97fR317

**Pull request closed without merging**
