### PR TITLE
[Merged by Bors] - Fix a few uninlined_format_args lints

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

Prevent things from breaking tomorrow when rust 1.67 is released.

## Solution

Fix a few `uninlined_format_args` lints in recently introduced code.

### CODE REVIEW

**Review by james7132 — APPROVED** [review]

**Review by devil-ira — APPROVED** [review]
CI is currently blocked on this :p

**Comment by rparrett** [comment]
Got it

**Pull request closed without merging**
