### PR TITLE
Add `unsafe_op_in_unsafe_fn` to Clippy CI & Crates

### LINKED ISSUE #9848: Lint against (and enforce) missing unsafe blocks in unsafe functions
There is already a bunch of missing safety comments in the call sites (because it's inside `unsafe` functions and no one bothered to do the unsafe blocks within unsafe functions), so it would be difficult to justify just adding the safety comment for the mutual exclusion rule.

_Originally posted by @nicopap in https://github.com/bevyengine/bevy/issues/9836#issuecomment-1724875046_

### PR DESCRIPTION
**Pull request by bushrat011899**
# Objective

- Fixes #9848

## Solution

- Added `unsafe_op_in_unsafe_fn` to the lint options for CI `clippy` task.
- Added `#![forbid(unsafe_op_in_unsafe_fn)]` to all crates that did not already forbid `unsafe`
- Placed `unsafe { ... }` statements around specific uses of `unsafe` where lint raised warnings.

## Notes

* My safety comments are fairly generic due to the shear volume required. I would encourage people to submit change suggestions to better comments where they may have a better understanding of the specific unsafe function contract.
* I've neglected the `generated.rs` file in `bevy_mikktspace`, as something like #9050 will resolve that issue on its own.

### CODE REVIEW

**Comment by JoJoJet** [comment]
IMO it would be better to add this lint to each crate individually, rather than putting it in CI. That would provide a better development experience since contributors won't be surprised by CI failing when clippy passed locally.

It would also make it easier to fix all of the occurrences since we could do it for each crate/groups of crates separately.

**Comment by bushrat011899** [comment]
> IMO it would be better to add this lint to each crate individually

Yeah I think you're right, I'll add that but keep it in the CI as a catch for future crates.

**Comment by Kanabenki** [comment]
Once #10011 is merged, this could be rebased to integrate the `unsafe_op_in_unsafe_fn` in the `Cargo.toml` lint table :slightly_smiling_face:

**Comment by alice-i-cecile** [comment]
Yeah, IMO we should move this to the universal lint config.

**Comment by mockersf** [comment]
Could you keep the lint at the warn level rather than forbid? It gives a much better local dev experience, and will be denied by CI

**Comment by bushrat011899** [comment]
I'm going to have another crack at this now that #10011 is merged, with the goal being to `warn` on `unsafe_op_in_unsafe_fn`, and fix any violations. I'm switching this to draft just to indicate it's not ready yet.

**Comment by BD103** [comment]
There's been some recent work in this area through #11590. Can any of this PR help with that?

**Pull request closed without merging**
