### PR TITLE
Switch to default PartialEq implementation for RenderResourceBinding

### LINKED ISSUE #858: Changing a material handle doesn't affect how an entity is rendered
An example where this can be reproduced: https://github.com/mvlabat/muddle-run/blob/b2fc5d91a6b6d81ee94029924507db0acdedc42d/bins/desktop_client/src/main.rs.

This is where I define two different materials: https://github.com/mvlabat/muddle-run/blob/b2fc5d91a6b6d81ee94029924507db0acdedc42d/bins/desktop_client/src/main.rs#L55-L70

And this is the code where I swap the handles: https://github.com/mvlabat/muddle-run/blob/b2fc5d91a6b6d81ee94029924507db0acdedc42d/bins/desktop_client/src/main.rs#L328-335

I can see the logs printed, so I'm pretty certain that those branches are executed as expected. I also tried inserting debug logging of the material handles themselves, and I could see that they are changed too and no system changes them back somewhere in the middle.

@memoryruins suggested me in the Discord that I try to edit the material itself, like so:

```
if let Some((material, _)) = controllable_object {
    materials.get_mut(material.clone()).unwrap().albedo = if contacting {
        Color::rgb(0.85, 0.1, 0.1)
    } else {
        Color::rgb(0.87, 0.87, 0.87)
    };
}
```

After applying these changes, I could see the object rendered in different colours.

My guess is that Bevy's renderer doesn't detect changes in entities' material handles, so this is probably a bug.

### PR DESCRIPTION
**Pull request by mvlabat**
This should fix #858.

I'm a noob in rendering, but I assumed that changing the dynamic index of a binding should invalidate it. It works (in my example I can see materials changed), though I'm not sure about the performance implications of this. I guess excluding dynamic index from `PartialEq` implementation was done on purpose. Probably there's a better way to solve the issue.

### CODE REVIEW

**Comment by cart** [comment]
Yeah I'm pretty sure this solves #858, but I'm also worried about performance. We don't want to "rebind" the dynamic uniform buffer when there is a different uniform index / create a new bind group for each buffer/index combo.

**Comment by mvlabat** [comment]
@cart, yeah, understood. I'm trying to come up with a better fix, but my knowledge is really limiting me here. Could you give me a hint what code should I take a look at?

**Comment by cart** [comment]
Alrighty I've given this some thought and I think I found the "right" solution. Its basically:

1. Move to the default "derive" impls, just like you already did in this pr (which I just verified does solve #858)
2. Add a new function to BindGroupBuilder called "hash_binding(&mut self, binding: &RenderResourceBinding)" and copy the "old" hash implementation there.

That way the normal impl behaves as expected and we move the "special case" logic to the place that needs it.

**Comment by cart** [comment]
https://github.com/bevyengine/bevy/blob/d6eb64745176c42cd225492405df25b0e42793b3/crates/bevy_render/src/renderer/render_resource/bind_group.rs#L38

**Comment by cart** [comment]
I guess specifically we would replace this line with our new "hash_binding" function: https://github.com/bevyengine/bevy/blob/d6eb64745176c42cd225492405df25b0e42793b3/crates/bevy_render/src/renderer/render_resource/bind_group.rs#L48

**Comment by mvlabat** [comment]
Alright, this should work. I also removed the default `Hash` implementation for `RenderResourceBinding`, since doesn't seem to be used anywhere else.

**Pull request merged**
