### PR TITLE
[Merged by Bors] - bevy_render: Use RenderDevice to get limits/features and expose AdapterInfo

### PR DESCRIPTION
**Pull request by superdump**
# Objective

- `WgpuOptions` is mutated to be updated with the actual device limits and features, but this information is readily available to both the main and render worlds through the `RenderDevice` which has .limits() and .features() methods
- Information about the adapter in terms of its name, the backend in use, etc were not being exposed but have clear use cases for being used to take decisions about what rendering code to use. For example, if something works well on AMD GPUs but poorly on Intel GPUs. Or perhaps something works well in Vulkan but poorly in DX12.

## Solution

- Stop mutating `WgpuOptions `and don't insert the updated values into the main and render worlds
- Return `AdapterInfo` from `initialize_renderer` and insert it into the main and render worlds
- Use `RenderDevice` limits in the lighting code that was using `WgpuOptions.limits`.
- Renamed `WgpuOptions` to `WgpuSettings`

### CODE REVIEW

**Comment by Weasy666** [comment]
Have you seen https://github.com/bevyengine/bevy/pull/3832 ? 😅

**Comment by superdump** [comment]
Also renamed `WgpuOptions` and related to `WgpuSettings` as suggested by @cart here: https://github.com/bevyengine/bevy/pull/3832#issuecomment-1038455906

**Review by Weasy666 — COMMENTED** [review]
LGTM, but could you add module level docs, like mentioned by @alice-i-cecile https://github.com/bevyengine/bevy/pull/3832#discussion_r796716573 ? To make people aware that `AdapterInfo` is available as a resource?

**Comment by superdump** [comment]
> LGTM, but could you add module level docs, like mentioned by @alice-i-cecile [#3832 (comment)](https://github.com/bevyengine/bevy/pull/3832#discussion_r796716573) ? To make people aware that `AdapterInfo` is available as a resource?

Done, with links.

**Review by Weasy666 — APPROVED** [review]

**Pull request closed without merging**
