### PR TITLE
[Merged by Bors] - `-Csplit-debuginfo=unpacked` is default on nightly

### PR DESCRIPTION
**Pull request by gfreezy**
https://github.com/rust-lang/cargo/pull/9298

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Comment by gfreezy** [comment]
Ci reports `markdown lint` errors in README and CHANGELOG. Should i fix it?
image

**Comment by bjorn3** [comment]
#1096 will fix it.

**Comment by DJMcNab** [comment]
Yeah, the issue is fixed by #1906, so this would be safe to merge (because bors checks the version from after rebase), although if you do come back to the code then rebasing would also make CI pass here

**Review by DJMcNab — APPROVED** [review]
We already use a `-Z` flag, so it being set as default only on nightly is fine.

**Review by DJMcNab — APPROVED** [review]
The rebased code is the same change as I previously approved.

In future, if you're going to experiment with the bors commands, I'd advise you not to delete the comments, and instead perhaps edit them to explain why you tried that. In this repository, no-one other than @cart has bors permissions at the moment, and so running the commands will fail.

**Comment by gfreezy** [comment]
@DJMcNab I don’t know how to get the pr merged. After glancing other merged prs, I thought  running bors commands might be needed.

**Comment by cart** [comment]
Yup thats a reasonable guess. For now I'm the only one that can merge prs with `bors r+`

**Comment by DJMcNab** [comment]
@gfreezy please respond in #2373 for the relicense to MIT/Apache 2.0. Thanks!

**Pull request closed without merging**
