### PR TITLE
Add clippy support and fix all warnings / errors

### PR DESCRIPTION
**Pull request by multun**
Depends on #204 and #201

### CODE REVIEW

**Comment by cart** [comment]
This one will take a bit more time for me to review. I havent used clippy much in practice so I need to sort out what I want from it.

**Comment by cart** [comment]
to determine the urgency of this pr: were these changes all automated or did you need manual intervention? if its automated im fine waiting, but i dont want to throw away a bunch of manual work / make it hard to update this pr when we merge new stuff.

**Comment by multun** [comment]
clippy can't automatically fix the vast majority of suggestions by itself yet, so I had to do it by hand.
Here's my take on clippy:

 - it makes the code more readable the vast majority of the time
 - it catches bugs (dfbdeeb and e36b26c)

It isn't perfect, but it doesn't let the kind of code you write at 4am through

**Comment by cart** [comment]
I learned a few new patterns from this pr. Nice!

This looks good to go.

**Pull request merged**
