### PR TITLE
Take example screenshots in CI

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- I want to take screenshots of examples in CI to help with validation of changes

## Solution

- Can override how much time is updated per frame
- Can specify on which frame to take a screenshots
- Save screenshots in CI

I reused the `TimeUpdateStrategy::ManualDuration` to be able to set the time update strategy to a fixed duration every frame. Its previous meaning didn't make much sense to me. This change makes it possible to have screenshots that are exactly the same across runs.

If this gets merged, I'll add visual comparison of screenshots between runs to ensure nothing gets broken

## Migration Guide

* `TimeUpdateStrategy::ManualDuration` meaning has changed. Instead of setting time to `Instant::now()` plus the given duration, it sets time to last update plus the given duration.

### CODE REVIEW

**Comment by mockersf** [comment]
Example screenshots can be found in the artefacts section of https://github.com/bevyengine/bevy/actions/runs/4800302635

**Comment by JMS55** [comment]
Would be awesome to use these CI-generated images in the examples page of the website :)

**Comment by mockersf** [comment]
That will be the plan after the next release!

**Review by alice-i-cecile — APPROVED** [review]
I really like this idea in theory, and the API is good. I'm curious to see how this ends up being used and how new screenshots can be blessed, but I'm content with this as a first step.

**Review by TheRawMeatball — APPROVED** [review]
There's definitely more work to be done, but this seems like a very good first step to me.

**Pull request merged**
