### PR TITLE
[Merged by Bors] - Assert compiler errors for compile_fail tests

### PR DESCRIPTION
**Pull request by NiklasEi**
# Objective

bevy_ecs has several compile_fail tests that assert lifetime safety. In the past, these tests have been green for the wrong reasons (see e.g. #2984). This PR makes sure, that they will fail if the compiler error changes.

## Solution

Use [trybuild](https://crates.io/crates/trybuild) to assert the compiler errors.

The UI tests are in a separate crate that is not part of the Bevy workspace. This is to ensure that they do not break Bevy's crater builds. The tests get executed by the CI workflow on the stable toolchain.

### CODE REVIEW

**Comment by cart** [comment]
This is super useful and solves a very real problem. I feel so much safer now :)

**Comment by mockersf** [comment]
Nice!

It will probably add to the things we need to update on a new rust version, and also fail things like [crater](https://github.com/rust-lang/crater) builds. Would there be a way to run those kind of tests not on a simple `cargo test` but another command that we can add to our CI?

**Comment by NiklasEi** [comment]
Maybe if we move them into a seperate crate that is not part of the workspace?

**Comment by NiklasEi** [comment]
The UI tests are now moved into a separate crate that is not part of the Bevy workspace. They get executed by the `CI` workflow and should no longer be able to break Bevy's crater tests.

**Comment by mockersf** [comment]
Could you fix the warning in CI

```
warning: bevy_ecs_ui_tests-tests v0.0.0 (/home/runner/work/bevy/bevy/crates/bevy_ecs_ui_tests/target/tests/bevy_ecs_ui_tests) ignoring invalid dependency `bevy_ecs_ui_tests` which is missing a lib target
```

It could be confusing in the future in case of other errors

**Comment by NiklasEi** [comment]
> Could you fix the warning in CI

I added an empty `lib.rs` pointing to the integration tests.

**Review by mockersf — APPROVED** [review]

**Comment by NiklasEi** [comment]
bors try

The redit link is failing to resolve...

**Comment by cart** [comment]
Cool I think this is good to go, but I think the `ui_test` naming (despite being semi-standard) is a bit unintuitive / ambiguous with "UI as in GUI" tests. Maybe we should be a bit more specific and call this something like "bevy_ecs_compile_fail_tests" or "bevy_ecs_trybuild_tests".

**Pull request closed without merging**
