### PR TITLE
[Merged by Bors] - Check for NaN in `Camera::world_to_screen()`

### PR DESCRIPTION
**Pull request by aevyrie**
# Objective

- Checks for NaN in computed NDC space coordinates, fixing unexpected NaN in a fallible (`Option<T>`) function.

## Solution

- Adds a NaN check, in addition to the existing NDC bounds checks.
- This is a helper function, and should have no performance impact to the engine itself.
- This will help prevent hard-to-trace NaN propagation in user code, by returning `None` instead of `Some(NaN)`.

Depends on https://github.com/bevyengine/bevy/pull/3269 for CI error fix.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
CI error should be fixed (#3269) if you rebase on main

**Comment by mockersf** [comment]
> This will help prevent hard-to-trace NaN propagation in user code, by returning None instead of Some(NaN).

The `NaN` wasn't propagated, you'r checking for it on the `z` component which is discarded after

**Review by mockersf — CHANGES_REQUESTED** [review]
Could you also do the same fix on `pipelined/bevy_render2/src/camera/camera.rs`?

**Comment by aevyrie** [comment]
> > This will help prevent hard-to-trace NaN propagation in user code, by returning None instead of Some(NaN).
> 
> The `NaN` wasn't propagated, you'r checking for it on the `z` component which is discarded after. Do you know how it would be possible to have this case happens?

This PR is the result of a bug I found while debugging an application. The `NaN` was propagated in the `Vec2` this function returns. I found that in all cases, inputs that resulting in the `Vec2` containing `NaN`s, could be caught by checking the z value alone, which I was already using for comparison in these other checks. I don't know if this is provable for all cases.

> Could you also do the same fix on pipelined/bevy_render2/src/camera/camera.rs?

Good call, will do.

**Comment by aevyrie** [comment]
@mockersf I've added a fix to pipelined, and changed the check to use `is_nan` on the output `Vec2`.

**Review by mockersf — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]

**Pull request closed without merging**
