### PR TITLE
Bump toml_edit in build-template-pages tool

### PR DESCRIPTION
**Pull request by BD103**
# Objective

- The [`build-templated-pages`](https://github.com/bevyengine/bevy/tree/4778fbeb65d840eb39bda017fd428ebfc17a1153/tools/build-templated-pages) tool is used to render the Markdown templates in the [docs-template](https://github.com/bevyengine/bevy/tree/4778fbeb65d840eb39bda017fd428ebfc17a1153/docs-template) folder.
- It depends on out outdated version of `toml_edit`.

## Solution

- Bump `toml_edit` to 0.21, disabling all features except `parse`.

### CODE REVIEW

**Review by doonv — APPROVED** [review]

**Comment by mockersf** [comment]
I don't think taking the same complexity of slugify is worse a 3 seconds decrease

**Comment by BD103** [comment]
> I don't think taking the same complexity of slugify is worth a 3 seconds decrease

What do you mean by this? Do you think manually registering the filter is too complex, or do you think we shouldn't pull in the `slug` crate at all and just implement our own filter? All it's doing is making some text lowercase, replacing spaces with dashes, and skipping symbols.

Another idea I had was to just move the function into `example.rs`, since that's the only place it is used.

**Comment by mockersf** [comment]
That I prefer to keep depending on the default features, 3 seconds on the build time on a tool not on a critical path doesn't seem a big enough gain

**Comment by BD103** [comment]
> That I prefer to keep depending on the default features, 3 seconds on the build time on a tool not on a critical path doesn't seem a big enough gain

Ok. I'll revert the Tera commit but keep the other one.

**Review by doonv — APPROVED** [review]

**Comment by BD103** [comment]
After looking at the most recent CI run, it appears that the Tera commit was the only thing providing any sort of time gains. (Compile times are back to 26.5 seconds.) I'm going to rename the PR and rewrite the description to make it just a version bump, because that's all it is at this point.

**Comment by mockersf** [comment]
from https://github.com/bevyengine/bevy/pull/11357 it's also used in other places. would it makes sense to also remove the default features there?

**Comment by BD103** [comment]
I bumped `toml_edit` everywhere it was explicitly depended on. I appears that they only need the `parse` feature, but CI will hopefully catch it if that's not the case.

```shell
$ cargo tree -i toml_edit
error: There are multiple `toml_edit` packages in your project, and the specification `toml_edit` is ambiguous.
Please re-run this command with one of the following specifications:
  toml_edit@0.19.15
  toml_edit@0.21.0
```

It appears that `toml_edit` 0.19 is being pulled in as well. It looks like an outdated version of `proc-macro-crate` is being used, which sources itself all the way back to `bevy_audio`. There's no much to be done about this except wait for dependencies to update themselves.

```shell
$ cargo tree --target all -i toml_edit@0.19.15
toml_edit v0.19.15
└── proc-macro-crate v1.3.1
    └── num_enum_derive v0.5.11 (proc-macro)
        └── num_enum v0.5.11
            └── ndk v0.7.0
                ├── cpal v0.15.2
                │   └── rodio v0.17.3
                │       └── bevy_audio v0.12.0 (/Users/bdeep/dev/bevy/bevy/crates/bevy_audio)
                │           └── bevy_internal v0.12.0 (/Users/bdeep/dev/bevy/bevy/crates/bevy_internal)
                │               └── bevy v0.12.0 (/Users/bdeep/dev/bevy/bevy)
                └── oboe v0.5.0
                    ├── bevy_audio v0.12.0 (/Users/bdeep/dev/bevy/bevy/crates/bevy_audio) (*)
                    └── cpal v0.15.2 (*)
```

**Review by mockersf — APPROVED** [review]

**Pull request merged**
