### PR TITLE
add docs to clip_from_view

### PR DESCRIPTION
**Pull request by atlv24**
more docs

### CODE REVIEW

**Comment by JMS55** [comment]
Users can also use a custom projection

**Comment by atlv24** [comment]
im aware, i think if a user is advanced enough to do custom projections then they know what they're doing. i cant possibly document what they are doing anyways

**Comment by JMS55** [comment]
Mhm. Just thinking we should maybe leave a comment reminding people about it. Up to you, I don't feel strongly either way.

**Comment by JMS55** [comment]
The other nice thing to add would be how you check for ortho vs perspective in a shader.

**Comment by atlv24** [comment]
addressed both

**Review by aevyrie — APPROVED** [review]

**Review by JMS55 — APPROVED** [review]

**Review by BenjaminBrienen — APPROVED** [review]

**Review by JMS55 — APPROVED** [review]

**Review by aevyrie — APPROVED** [review]
Docs always good.
Is there anything we can do to avoid having 3 sets of the same docs from getting out of sync? Newtyping? Including a text document or linking to it?

**Review by pcwalton — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
> Docs always good. Is there anything we can do to avoid having 3 sets of the same docs from getting out of sync? Newtyping? Including a text document or linking to it?

You can `include_str` various bits of text in docs. In this case though module docs feel more correct.

**Pull request merged**
