### PR TITLE
Remove exit_on_esc_system

### PR DESCRIPTION
**Pull request by alice-i-cecile**
# Objective

The entire code of `exit_on_esc_system` is:
```rust
pub fn exit_on_esc_system(
    mut keyboard_input_events: EventReader<KeyboardInput>,
    mut app_exit_events: EventWriter<AppExit>,
) {
    for event in keyboard_input_events.iter() {
        if let Some(key_code) = event.key_code {
            if event.state == ElementState::Pressed && key_code == KeyCode::Escape {
                app_exit_events.send_default();
            }
        }
    }
}
```

- it is trivial for end users to write on their own
- it is the only freestanding system that Bevy exports
- it is never correct to include in nontrivial Bevy applications: simply exiting when ESC is pressed is surprising behavior
- its main value ("how do I exit the App?") is better demonstrated through the `game_menu` example
- if this system *should* be provided to users, it does not belong in `bevy_input`

## Solution

Yeet.

## Changelog

- removed `exit_on_esc_system`

## Migration Guide

`exit_on_esc_system` has been removed. Add your own `exit_on_esc_system` by copying the following code into your app:

```rust
pub fn exit_on_esc_system(
    mut keyboard_input: Res<Input<KeyCode>>,
    mut app_exit_events: EventWriter<AppExit>,
) {
  if keyboard_input.just_pressed(KeyCode::Escape){
       app_exit_events.send_default();
  }
}
```

### CODE REVIEW

**Review by DJMcNab — COMMENTED** [review]
I firmly disagree

Exiting on escape is absolutely the correct behaviour in examples, and during early prototyping it's invaluable.

In #3575, I move this to close only the current window, which is probably a nicer place for it to live.

**Comment by alice-i-cecile** [comment]
> Exiting on escape is absolutely the correct behaviour in examples, and during early prototyping it's invaluable.

During early prototyping, is this easier / better than just using Alt+F4?

**Comment by DJMcNab** [comment]
Yes, it is better than alt-f4 imo. Using alt-f4, it's very easy to kill the wrong window. e.g. your editor, or browser window.

For my mind, it's much easier to just press escape, than think 'am I sure my game window is the one selected' (or else ~every hour completely lose flow by killing the editor)

**Comment by alice-i-cecile** [comment]
Alright, I'll accept it for now. We can revisit the question of "utility systems" down the road.

Closing in favor of #4260.

**Pull request closed without merging**
