### PR TITLE
Reexport crevice in bevy_utils

### PR DESCRIPTION
**Pull request by mrk-its**
# Objective

Let's reexport bevy's version of crevice to be able to use it in apps.

### CODE REVIEW

**Comment by bjorn3** [comment]
Maybe re-export if from bevy_render instead? `crevice` has a proc-macro that depends on syn, which takes a while to build. Adding crevice to bevy_utils may make the critical path during fresh compilations longer.

**Comment by cart** [comment]
Yeah I think `bevy_render2` is a better spot for it. Do the proc_macros even work with the re-export? Often times they break in situations like this.

**Comment by mrk-its** [comment]
I've tested it locally and it seems to work (although my usage is very simple). Will move to new location)

**Comment by mrk-its** [comment]
done

**Comment by cart** [comment]
Sorry one more thing: if we're going to make `bevy_render2` the "source" of crevice, I think we should consume it from there in internal crates too. Can you update bevy_pbr2 to consume it from there?

**Comment by mrk-its** [comment]
sure, will do

**Comment by mrk-its** [comment]
@cart heh, you were right regarding possible problems with proc_macros - I just have tons of errors in `bevy_pbr2` because of that.

**Comment by cart** [comment]
Yeah we'll probably need to update the proc macros to (optionally) point to `bevy_render::crevice` (maybe with a cargo feature).

**Comment by mockersf** [comment]
I think it can't work with a cargo feature, you need to check in the macro how the crevice crate is imported (if it's in `Cargo.toml` file) and change the path based on that

**Comment by mrk-its** [comment]
Closing it now  as official crevice package works for me. Let's reopen / create new PR later if needed.

**Pull request closed without merging**
