### PR TITLE
(WIP) Refactor bevy_input crate

### PR DESCRIPTION
**Pull request by Vaelint**

### CODE REVIEW

**Comment by Vaelint** [comment]
In it's current state I think this refactor is worthy of being discussed.

Known issues: 
 - Renaming Input to Button causes a collision with bevy_ui
 - devices sub-module is very confusing and needs further investigation.

**Comment by memoryruins** [comment]
Thanks for the PR! The following is general comments about module organization and is only my two-cents.

For some of the new modules, I wonder the current organization is _too_ granular in splitting things into small files.
For example, the new state module is written as

```rust
// crates/bevy_input/src/state/mod.rs 

pub mod element;
pub mod keyboard;
pub mod mouse_button;
pub mod touch_system;

pub use element::ElementState;
pub use keyboard::KeyboardInputState;
pub use mouse_button::MouseButtonInputState;
pub use touch_system::TouchSystemState;
```

and each of those types in its child modules have very short implementations, e.g. `mouse_button.rs`

```rust
use crate::events::MouseButtonEvent;
use bevy_app::EventReader;

/// State used by the mouse button input system
#[derive(Default)]
pub struct MouseButtonInputState {
    pub(crate) mouse_button_input_event_reader: EventReader<MouseButtonEvent>,
}
```

For when the implementation in the module is so short,  we could consider placing those types directly into the state module instead.

---

Something that applies to most of the new `mod.rs`s: we can avoid making their child modules public and leave them as an implementation detail. By exposing the child modules, it adds more levels of docs for the user to grok in docs, and in this case, redundant navigation since their items are already re-exported. rustdoc also adds a not so pretty re-export section.

Currently `device_codes`'s docs in this PR looks like the following by locally running
`cargo doc -p bevy_input --no-deps --open` from bevy's root.

<details>

<summary>screenshot</summary>

screenshot 8968

</details>

and clicking the child gamepad module's docs, we see

<details>

<summary>screenshot</summary>

image

</details>

To help make the docs less nested and avoiding a messy re-export section, can do the following:

```diff
//  crates/bevy_input/src/device_codes/mod.rs
- pub mod mouse;
- pub use mouse::{MouseButtonCode, MouseScrollUnitCode};
+ mod mouse;
+ pub use mouse::*;
```

and then rustdoc will render it as the following

<details>

<summary>screenshot</summary>

image

</details>

Another thing to consider for some of the `mod.rs`s is the method mentioned in https://github.com/bevyengine/bevy/issues/633#issuecomment-704669930

---

Something that concerns me about the current reorganization is that its less obvious where to look for each category of input. Currently docs on master branch looks like the following, and if we click `gamepad`, we are met with most items essential to gamepad.

<details>

<summary>screenshots</summary>

image

image

</details>

To compare with the current state of the refactor, we see

<details>

<summary>screenshot</summary>

image

</details>

and while this does organize it more in the categories of bevy sorts (systems, events, etc), both dev and user must move between multiple modules to get an idea of all the items that relate to a certain sort of input.

Regardless, thanks for caring about this and making an effort to improve on the organization!
I hope some of the above review can helps achieve the refactor's goals :)

**Comment by Vaelint** [comment]
Reposting the goals in this thread:
 - Split current implementation into sub-modules
 - Only split when the split makes the module easier to understand.
 - Make the API between devices as similar where it doesn't cause friction

@memoryruins I like all of your suggestions and plan to implement them. Thank you! You've just made me a better rust programmer.

Before I go further with this work I need to think think through, make presentable, and gather the community / @cart 's thoughts on some of the high level design decisions that need to be made.

**Comment by enfipy** [comment]
That's huge! I also think that the input crate can be much better. Nice work!

**Comment by Vaelint** [comment]
Closing due to rebasing breaking things and it just being faster to start PR over.

**Pull request closed without merging**
