### PR TITLE
[Merged by Bors] - Enable the `doc_markdown` clippy lint

### LINKED ISSUE #3435: Check for for missing back-ticks in doc links in CI
Unfortunately, docs.rs renders [Foo] and [\`Foo\`] differently. https://cdn.discordapp.com/attachments/743559241461399582/924406539584942100/unknown.png

We want the latter, and our CI should check for this.

### PR DESCRIPTION
**Pull request by mfdorst**
# Objective

CI should check for missing backticks in doc comments.

Fixes #3435

## Solution

`clippy` has a lint for this: `doc_markdown`. This enables that lint in the CI script.

Of course, enabling this lint in CI causes a bunch of lint errors, so I've gone through and fixed all of them. This was a huge edit that touched a ton of files, so I split the PR up by crate.

When all of the following are merged, the CI should pass and this can be merged.

+ [x] #3467
+ [x] #3468
+ [x] #3470 
+ [x] #3469
+ [x] #3471 
+ [x] #3472 
+ [x] #3473 
+ [x] #3474 
+ [x] #3475 
+ [x] #3476 
+ [x] #3477 
+ [x] #3478 
+ [x] #3479 
+ [x] #3480 
+ [x] #3481 
+ [x] #3482 
+ [x] #3483 
+ [x] #3484 
+ [x] #3485 
+ [x] #3486

### CODE REVIEW

**Comment by mfdorst** [comment]
If it's working the CI should fail...

**Comment by mfdorst** [comment]
Lookin good! I guess I'll just fix up all those warnings now.

**Comment by mfdorst** [comment]
Oh jesus there's a lot...

**Comment by mfdorst** [comment]
Okay so this is irritating...
[This line] is causing a lint warning:
```
warning: you should put `sRGB` between ticks in the documentation
  --> crates/bevy_render/src/color/colorspace.rs:36:42
   |
36 |     /// converts a color in HLS space to sRGB space
   |                                          ^^^^
   |
   = note: requested on the command line with `-W clippy::doc-markdown`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
```
I'm not sure if there's a way around this.

[This line]: https://github.com/bevyengine/bevy/blob/3a9d5a63c980b4bd0d3c19d4bf2e652a1c351f1e/crates/bevy_render/src/color/colorspace.rs#L36

**Comment by mfdorst** [comment]
There is a workaround if we have a `clippy.toml`:
```
doc-valid-idents = ["sRGB"]
```

**Comment by mockersf** [comment]
Probably a good time to create the `clippy.toml` file 👍 

I don't know how big this PR will be, but if there are a lot of changes don't hesitate to open smaller PR that would fix this lint for part of Bevy, smaller PRs would be faster / easier to merge. Then after all fixing PRs would be merged this one could enable the lint.

**Comment by mfdorst** [comment]
Oh okay yeah that’s a good strategy. This will defninitely touch a lot of files so I guess that’s what I’ll do.

**Comment by mfdorst** [comment]
Okay I didn't realize there were so many crates, I probably should have grouped one of these instead of doing 20 PR's :grimacing:

**Comment by mockersf** [comment]
Could you convert the PR list in your issue to a task list? See https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists for example

I've merged the easy ones and added comments on a few others. For the remaining and before activating the lint, I would rather wait for the 0.6 to avoid slowing down merging the PRs needed for the release.

**Comment by mockersf** [comment]
all merged! let's try this one now 🙂

**Comment by mockersf** [comment]
bors try

**Comment by mockersf** [comment]
Oh the lint need to be allowed specifically to not warn in `bevy_crevice`...

Could you add it?
```diff
diff --git a/crates/bevy_crevice/src/lib.rs b/crates/bevy_crevice/src/lib.rs
index 782e85cf4..48451966b 100644
--- a/crates/bevy_crevice/src/lib.rs
+++ b/crates/bevy_crevice/src/lib.rs
@@ -3,7 +3,8 @@
     clippy::needless_update,
     clippy::len_without_is_empty,
     clippy::needless_range_loop,
-    clippy::all
+    clippy::all,
+    clippy::doc_markdown
 )]
 /*!
 [![GitHub CI Status](https://github.com/LPGhatguy/crevice/workflows/CI/badge.svg)](https://github.com/LPGhatguy/crevice/actions)
```

There are still a few other issues with the lint in Bevy's crate, if you fix them in this PR we'll get it merge soon 🙂

**Review by mockersf — APPROVED** [review]

**Pull request closed without merging**
