### PR TITLE
[Merged by Bors] - Add methods to `Query<&Children>` and `Query<&Parent>` to iterate over descendants and ancestors

### PR DESCRIPTION
**Pull request by devil-ira**
# Objective
Add methods to `Query<&Children>` and `Query<&Parent>` to iterate over descendants and ancestors, respectively.

## Changelog

* Added extension trait for `Query` in `bevy_hierarchy`, `HierarchyQueryExt`
* Added method `iter_descendants` to `Query<&Children>` via `HierarchyQueryExt` for iterating over the descendants of an entity.
* Added method `iter_ancestors` to `Query<&Parent>` via `HierarchyQueryExt` for iterating over the ancestors of an entity.

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Very useful and well made. Can you add a couple of tests for these methods and link to them from the [`Parent`] and [`Children`] docs?

**Review by alice-i-cecile — APPROVED** [review]
Excellent, thanks!

**Comment by alice-i-cecile** [comment]
Why was the last commit needed?

**Comment by devil-ira** [comment]
Just code-quality :)
The commit is named 'yuck' because I realized `EntityMut` does not have `add_child` :expressionless:

**Review by mockersf — APPROVED** [review]

**Review by james7132 — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Pull request closed without merging**
