### PR TITLE
Add "all-features = true" to docs.rs metadata for most crates

### PR DESCRIPTION
**Pull request by yrns**
# Objective

Fix missing `TextBundle` (and many others) which are present in the main crate as default features but optional in the sub-crate. See:

- https://docs.rs/bevy/0.13.0/bevy/ui/node_bundles/index.html
- https://docs.rs/bevy_ui/0.13.0/bevy_ui/node_bundles/index.html

~~There are probably other instances in other crates that I could track down, but maybe "all-features = true" should be used by default in all sub-crates? Not sure.~~ (There were many.) I only noticed this because rust-analyzer's "open docs" features takes me to the sub-crate, not the main one.

## Solution

Add "all-features = true" to docs.rs metadata for crates that use features.

### Changed

- Unified features documented on docs.rs between main crate and sub-crates

### CODE REVIEW

**Review by alice-i-cecile — COMMENTED** [review]
Oh clever. Yeah, I think we should actually just turn on all_features in the docs for all of our crates. I've been bitten by that elsewhere too (why doesn't it impl serde?!).

Can you make a PR for that?

**Comment by yrns** [comment]
> Can you make a PR for that?

Yep, I'll just push here.

**Comment by yrns** [comment]
I see people using `[workspace.metadata.docs.rs]` but it apparently [doesn't work](https://github.com/rust-lang/docs.rs/issues/2226).

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Great :) Can you update your PR description and title?

**Comment by yrns** [comment]
> Great :) Can you update your PR description and title?

Done.

**Comment by mockersf** [comment]
could you try with `doc_auto_cfg` to see if that works well to document what is behind features? https://github.com/rust-lang/rust/issues/43781

**Comment by yrns** [comment]
> could you try with `doc_auto_cfg` to see if that works well to document what is behind features? [rust-lang/rust#43781](https://github.com/rust-lang/rust/issues/43781)

So, add `#![cfg_attr(docsrs, feature(doc_auto_cfg))]` at the root of every crate? It looks good to me. It requires nightly if you want to build the docs locally with that feature enabled, like: `RUSTDOCFLAGS="-Zunstable-options --cfg=docsrs" cargo doc --all-features`.

**Review by james7132 — APPROVED** [review]

**Comment by yrns** [comment]
I added the `doc_auto_cfg` feature to the same set of crates. It highlights which items are specific to feature or target. It is [documented here](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/unstable-features.md#doc_auto_cfg-automatically-generate-doccfg), and only runs on docs.rs. Might be worth considering using https://github.com/dtolnay/cargo-docs-rs on CI.

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
