### PR TITLE
Move UI example to testbed

### LINKED ISSUE #16230: Move UI example to testbed folder
[M]ove this example into the `testbed` folder? It's really not good learning material.

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/pull/16151#pullrequestreview-2402068976_

### PR DESCRIPTION
**Pull request by richchurcher**
# Objective

UI example is quite extensive, probably not the best teaching example anymore.

Closes #16230.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by ickshonpe — COMMENTED** [review]
The diagonal text and flipped icons aren't rendered for some reason. Just going to check if they are still present on main.

**Review by ickshonpe — APPROVED** [review]

**Comment by ickshonpe** [comment]
It's the same on main, the example and these changes are fine, something else is broken.

**Review by mockersf — APPROVED** [review]

**Comment by mnmaita** [comment]
@alice-i-cecile the merge failed due to "error: no example target named `ui`" in the wasm build, FYI.

**Comment by alice-i-cecile** [comment]
Yeah, I think that we need to tweak the testing setup somehow. @mockersf or @BD103 may know the answer offhand?

**Comment by ickshonpe** [comment]
> > It's the same on main, the example and these changes are fine, something else is broken.
> 
> Seems likely that this was broken by #16088 and wasn't noticed before #16151 was merged.
> 
> That PR had some other side effects in examples: #16239, #16240. I didn't open an issue for `ui` because it hasn't actually changed since #16151 was merged, so I didn't notice the problem.

Yeah not surprised, that PR accumulated a lot of changes with different people pushing to it and it got merged before I could check its final state.

**Comment by richchurcher** [comment]
Oh whoops, let's see what's going on in the `wasm` CI :eyes:

**Comment by richchurcher** [comment]
Oh, hrm. Interesting! It mentions this particular example as a literal :laughing: 
```
       - name: First Wasm build
        run: |
          cargo build --release --example ui --target wasm32-unknown-unknown
```
I guess maybe it needs one build with the release flag done initially? Anyway, easy enough fix.

**Comment by richchurcher** [comment]
@alice-i-cecile in theory this ought to be OK to go back in the merge queue.

**Pull request merged**
