### PR TITLE
Added example of how to change sprite & texture at runtime

### PR DESCRIPTION
**Pull request by louisgjohnson**
# Objective

Fixes: https://github.com/bevyengine/bevy/issues/3130

## Solution

- Added an example on how to update sprites at runtime
- Showing an example of how to alter the color value
- Showing an example of how to swap the texture

### CODE REVIEW

**Comment by mockersf** [comment]
Thanks for adding this example! I think it would need changes to work after the pipelined rendering rework. 

The new sprite bundle will look like this:
https://github.com/bevyengine/bevy/blob/029a7c03d820107952f5f9570fcafc22d8647d58/pipelined/bevy_sprite2/src/bundle.rs#L14-L23

Could you try rewriting it for the `pipelined-rendering` branch?

**Comment by louisgjohnson** [comment]
> Thanks for adding this example! I think it would need changes to work after the pipelined rendering rework.
> 
> The new sprite bundle will look like this:
> 
> https://github.com/bevyengine/bevy/blob/029a7c03d820107952f5f9570fcafc22d8647d58/pipelined/bevy_sprite2/src/bundle.rs#L14-L23
> 
> Could you try rewriting it for the `pipelined-rendering` branch?

Yep I can do that! Would you like me to keep this one and create a new pr for the pipelined-rendering branch? Or would that create too much confusion

**Comment by cart** [comment]
Probably best to just close this and create a new pr. Make sure your example uses the new pipelined rendering plugins / imports. Check out [bevymark_pipelined](https://github.com/bevyengine/bevy/blob/pipelined-rendering/examples/tools/bevymark_pipelined.rs) for an example.

**Comment by louisgjohnson** [comment]
> Probably best to just close this and create a new pr. Make sure your example uses the new pipelined rendering plugins / imports. Check out [bevymark_pipelined](https://github.com/bevyengine/bevy/blob/pipelined-rendering/examples/tools/bevymark_pipelined.rs) for an example.

Cool, I'll open a new PR

**Pull request closed without merging**
