### PR TITLE
[Merged by Bors] - Add readme to errors crate and clean up cargo files

### PR DESCRIPTION
**Pull request by NiklasEi**
# Objective

- Document that the error codes will be rendered on the bevy website (see bevyengine/bevy-website#216)
- Some Cargo.toml files did not include the license or a description field

## Solution

- Readme for the errors crate
- Mark internal/development crates with `publish = false`
- Add missing license/descriptions to some crates

- [x] merge bevyengine/bevy-website#216

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
dead link found by CI is https://bevyengine.org/errors as it's not yet deployed

**Comment by NiklasEi** [comment]
[Now the link is no longer dead](https://bevyengine.org/learn/errors) :slightly_smiling_face:

**Comment by cart** [comment]
Haha so close!

**Pull request closed without merging**
