### PR TITLE
Custom `MeasureFunc` 

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

At the moment Bevy UI has a very basic, unmodifiable `MeasureFunc`. 

Problems:

* Text wrapping can't be implemented correctly as the `MeasureFunc` needs access to the font and text data to choose the correct size for the node.

* Images are difficult to work with. With more complicated layouts users have to set fixed size constraints using `min_size` and `max_size` to get the correct dimensions, which isn't acceptable.

* Users can't implement widgets that need to control their own size. 

* There are bugs that are hard to find and replicate without modifying the `MeasureFunc`
  #8111, #6748, and https://github.com/DioxusLabs/taffy/issues/406 are examples.

## Solution
Create a new trait `MeasureNode` and add a `Box<dyn MeasureNode>` field to `CalculatedSize`.
Have `upsert_leaf` use the boxed `MeasureNode` to create the `MeasureFunc` for the node.

## Changelog
  * Added a new trait `MeasureNode`.
  * Added new structs `ImageMeasure` and `BasicMeasure` that implement `MeasureNode`.
  * Add a field to `CalculatedSize` called `measure` that takes a boxed `MeasureNode`.
  * `upsert_leaf` uses the `measure` of `CalculatedSize` to create a `MeasureFunc` for the node.

### CODE REVIEW

**Comment by ickshonpe** [comment]
This PR is the wrong approach, the whole `flex` module has big underlying problems I didn't understand before.

**Comment by TimJentzsch** [comment]
@ickshonpe What are the underlying problems?
Did we capture them in issues already?

**Comment by ickshonpe** [comment]
> @ickshonpe What are the underlying problems? Did we capture them in issues already?

The major problem with this PR is that it clones and double-boxes the `MeasureFunc` when I think the layout algorithm should be able to access it directly from the `CalculatedSize` component. 

There are a lot of internal performance bugs that are hard to find because they only have an impact when the UI updates and not every frame. I just published #8402 which fixes another unnecessary update bug.

**Comment by nicoburns** [comment]
@ickshonpe Would it be helpful if `MeasureFunc`s were able to borrow from their environment. I've been considering adding such a feature to Taffy, although there are a couple of possible designs:

- MeasureFunc's could take an "environment" parameter. The user would would be pass the "environment" (which could be a reference) to `compute_layout`, which would just pass it in every time it called a `MeasureFunc`.
- OR Individual MeasureFunc's could be replaced by a single measure func which is passed in to `compute_layout` and get's called with the node's id as a paramter.

**Pull request closed without merging**
