### PR TITLE
[Merged by Bors] - Derive default for enums where possible

### LINKED ISSUE #5153: Use new enum default method throughout code base
We can [now use #[derive(Default)] on enum types](https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#default-enum-variants)!

This is clearer and more idiomatic, as it puts the default values directly on the struct definition.

We should migrate to this pattern throughout the code base; search for `impl Default for` to find candidates.

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

Fixes #5153

## Solution

Search for all enums and manually check if they have default impls that can use this new derive.

By my reckoning:

| enum | num |
|-|-|
| total | 159 |
| has default impl | 29 |
| default is unit variant | 23 |

### CODE REVIEW

**Review by hymm — APPROVED** [review]
Changes in the PR look good. I didn't double check if there were any enums that were missed.

**Comment by devil-ira** [comment]
Found a couple more:
https://github.com/rparrett/bevy/blob/c27a3cff6d593e1b1220886673018a508aaa785d/crates/bevy_reflect/bevy_reflect_derive/src/container_attributes.rs#L39
https://github.com/rparrett/bevy/blob/fb813a3a64cdafdd75f7590a461364bcdf34bf2e/crates/bevy_reflect/bevy_reflect_derive/src/field_attributes.rs#L37

**Review by james7132 — APPROVED** [review]
Changes look good. Less code is better code.

**Comment by rparrett** [comment]
> Found a couple that were missed: https://github.com/rparrett/bevy/blob/c27a3cff6d593e1b1220886673018a508aaa785d/crates/bevy_reflect/bevy_reflect_derive/src/container_attributes.rs#L39 https://github.com/rparrett/bevy/blob/fb813a3a64cdafdd75f7590a461364bcdf34bf2e/crates/bevy_reflect/bevy_reflect_derive/src/field_attributes.rs#L37

Thanks. Looks like I missed `pub(crate) enum`s. Will do a sweep for those.

**Comment by rparrett** [comment]
Of the 10 pub(crate) enums, only those two were relevant.

**Review by devil-ira — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Update your Rust version using rustup update :)

**Comment by adsick** [comment]
I've already done it:
```
bevy/examples/2d  main ✔                                                                   5h39m  ⍉
▶ rustup update
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: checking for self-updates

   stable-x86_64-apple-darwin unchanged - rustc 1.62.1 (e092d0b6b 2022-07-16)
  nightly-x86_64-apple-darwin unchanged - rustc 1.64.0-nightly (9a7b7d5e5 2022-07-19)

info: cleaning up downloads & tmp directories

bevy/examples/2d  main ✔
```

**Comment by adsick** [comment]
done all these steps and still(

**Comment by alice-i-cecile** [comment]
Hmm. Perhaps you're running Bevy with an old Rust version via some project specific configuration? I would try a fresh example project, where you just define a toy enum and use this feature.

Either way, I would delete your Bevy folder and clone it again from scratch.

**Comment by adsick** [comment]
sounds OK, I'll try, thanks

**Comment by mockersf** [comment]
a few commands to check your rust versions:
* `rustup show` shows everything
* `rustup toolchain list` shows all toolchains installed
* `rustup overrides list` shows if there are overrides from rustup
* `cargo rustc -- --version` shows rustc version used by cargo, but I think it needs to compile to work

**Pull request closed without merging**
