### PR TITLE
Slicing support for texture atlas

### PR DESCRIPTION
**Pull request by ManevilleF**
# Objective

Follow up to #11600 and #10588 
https://github.com/bevyengine/bevy/issues/11944 made clear that some people want to use slicing with texture atlases

## Changelog

* Added support for `TextureAtlas` slicing and tiling.
`SpriteSheetBundle` and `AtlasImageBundle` can now use `ImageScaleMode`
* Added new `ui_texture_atlas_slice` example using a texture sheet

Screenshot 2024-02-23 at 11 58 35

### CODE REVIEW

**Review by Aceeri — APPROVED** [review]
LGTM :)

**Review by pablo-lua — APPROVED** [review]
I don't really like the fact that there is a duplicate code between ui slice and sprite slice, but that can be a follow up in the future. 
Just a couple mispelling here, LGTM

**Comment by alice-i-cecile** [comment]
@ManevilleF can you format this when you get a chance?

**Comment by ManevilleF** [comment]
@alice-i-cecile Done !

**Pull request merged**
