### PR TITLE
[Merged by Bors] - Mut to immut impls

### LINKED ISSUE #2005: Create blanket impl to convert from mutable to immutable versions of ECS data
## What problem does this solve or what need does it fill?

When working with functions that accept data from the ECS, you may want to pass in the wrapped data type (e.g. Res<T> or `ResMut<T>` instead of the underlying data.

Because we don't have an easy (or automatic) way to convert between them, this causes silly avoidable errors and can force duplication of functions for both the mutable and immutable types.

## What solution would you like?

Create blanket impls casting our mutable data wrappers (resources, components, eventually relations) into their immutable forms.

## What alternative(s) have you considered?

Always unwrap the data before passing it. This is the correct solution in most user-facing code, but perhaps not for all advanced features.

## Additional context

A new user [stumbled](https://discord.com/channels/691052431525675048/742884593551802431/835633836436094986) on this in #help.

### PR DESCRIPTION
**Pull request by dbearden**
# Objective
- Provide impls for mutable types to relevant immutable types. 
- Closes #2005 

## Solution

- impl From<ResMut> for Res
- impl From<NonSendMut> for NonSend
- Mut to &/&mut already impl'd in change_detection_impl! macro

### CODE REVIEW

**Review by james7132 — APPROVED** [review]
Looks simple enough; LGTM.

**Review by alice-i-cecile — APPROVED** [review]
Looks good to me :)

**Comment by alice-i-cecile** [comment]
So, I have a few arguments in favor of supporting why we should add this functionality:
- this is trivially correct to support
- it is logically consistent with the ability to cast other pointers from mutable to immutable forms
- it makes it possible to cleanly write APIs that take in a `Res`. In most cases you're going to want to take a `&R`, like you point out, but in some edge cases you may want to verify that the type was constructed as a resource. This is particularly interesting because of the way that users can't actually manually construct a raw `Res<T>` from a `T`
- if we add more metadata to resources eventually (like which world they belong to), APIs that take a `Res` rather than a `&` become increasingly useful

**Review by mockersf — APPROVED** [review]

**Comment by cart** [comment]
I'm on board!

**Pull request closed without merging**
