### PR TITLE
Speed up fast compiles config

### PR DESCRIPTION
**Pull request by ashneverdawn**
On my late 2014 macbook, this makes my incremental builds take half as long. Mileage will vary depending on hardware and OS.

This speeds up compiles by reducing how much debug info is included to 'line tables only'
See: https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#debug

### CODE REVIEW

**Comment by cart** [comment]
This seems like a nice win, but do you know what we're losing here by dropping to level 1?

**Comment by memoryruins** [comment]
It makes a similar change as `-gline-tables-only` in [clang](https://clang.llvm.org/docs/UsersManual.html#id48)

> Generate line number tables only.
> This kind of debug info allows to obtain stack traces with function names, file names and line numbers (by such tools as gdb or addr2line). It doesn’t contain any other data (e.g. description of local variables or function parameters).

It ends up generating much less debuginfo while still being fairly useful for general panics and surface level debugging. It may be worth leaving a comment in the config that if more debugging information is required to comment the setting out (or set it back to the default [`2`](https://doc.rust-lang.org/cargo/reference/profiles.html#debug)).

**Comment by cart** [comment]
ah so this would probably make using the live-debugger experience a bit worse

**Comment by cart** [comment]
if the wins arent particularly measurable with lld, we could consider scoping this to macos only (where the difference is _significant_)

**Comment by memoryruins** [comment]
Scoping it to macos sounds reasonable. The link time differences differences has been much less significant for me on linux and windows while using `lld`. (though, I am still looking forward to split dwarf / debuginfo fission in rustc https://github.com/rust-lang/rust/issues/34651 ).

**Comment by cart** [comment]
Yeah on linux the change for me is ~0.05 seconds, which is measurable but im not sure its worth a reduced debugger experience.

**Comment by cart** [comment]
If we can scope this to macos for now that would be great.

**Comment by ashneverdawn** [comment]
Thanks for the feedback!
There doesn't appear to be a way to make that particular config mac only https://doc.rust-lang.org/cargo/reference/config.html
So, I've commented it out and added a description so it's upto the user to uncomment it if they want it.

**Comment by cart** [comment]
Awesome awesome. Thanks

**Pull request merged**
