### PR TITLE
[Merged by Bors] - Port bevy_gltf to pipelined-rendering

### PR DESCRIPTION
**Pull request by superdump**
# Objective

Port bevy_gltf to the pipelined-rendering branch.

## Solution

crates/bevy_gltf has been copied and pasted into pipelined/bevy_gltf2 and modifications were made to work with the pipelined-rendering branch. Notably vertex tangents and vertex colours are not supported.

### CODE REVIEW

**Comment by superdump** [comment]
I did diff `pipelined/bevy_gltf2` against `crates/bevy_gltf` to try to catch changes since the original branch was made. There were a few including the addition of the Apache 2.0 license.

**Comment by cart** [comment]
Haha CI demands that you add the new pipelined gltf example to the "examples" readme.

**Comment by cart** [comment]
bors retry

**Comment by cart** [comment]
Added the clippy fixes from `main` to `pipelined-rendering`. Hopefully this works now!

**Comment by cart** [comment]
This is what I get for being lazy and not just running rustup + testing locally :smile:

**Pull request closed without merging**
