### PR TITLE
[Merged by Bors] - Borrow instead of consuming in `EventReader::clear`

### PR DESCRIPTION
**Pull request by mvlabat**
The PR fixes the interface of `EventReader::clear`. Currently, the method consumes the reader, which makes it unusable.

## Changelog

- `EventReader::clear` now takes a mutable reference instead of consuming the event reader. 

## Migration Guide

`EventReader::clear` now takes a mutable reference instead of consuming the event reader. This means that `clear` now needs explicit mutable access to the reader variable, which previously could have been omitted in some cases:

```rust
// Old (0.9)
fn clear_events(reader: EventReader<SomeEvent>) {
  reader.clear();
}

// New (0.10)
fn clear_events(mut reader: EventReader<SomeEvent>) {
  reader.clear();
}
```

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by devil-ira** [comment]
Not necessarily against this change but this was done on purpose because the reader is useless after calling `clear`.

**Comment by mockersf** [comment]
> Currently, the method consumes the reader, which makes it unusable.

Could you add more details on how that's unusable? Once `clear`ed, you can't use the event reader anymore, but then there are no events in it.

You'll have to fix other things (see CI failures), I think the fact that it was consumed was useful for something but can't remember what from the top of my head.

**Comment by james7132** [comment]
This still changes a public facing API which makes it a breaking change. @mvlabat do you mind writing up a short changelog and migration guide?

**Review by JoJoJet — APPROVED** [review]

**Comment by cart** [comment]
I think this is a reasonable change. I don't think we need a migration guide as this is a relaxing of constraints. Before, calling clear() would result in EventReader being dropped / no longer available. This means no code after it could use it. After the change, that code will behave identically: clear will still be the last usage of EventReader and it will be dropped. Functionally maybe there is _some_ contrived case where that difference matters, but I can't come up with one.

**Comment by cart** [comment]
I added a changelog entry though

**Comment by cart** [comment]
Welp the build found a non-trivial breaking change, so I was wrong this does need a migration guide. I'll fix that now.

**Comment by mvlabat** [comment]
Oh, that was merged sooner than I was able to reply! Thanks! :D

Just to add to @JoJoJet's comment, consuming the event reader also makes it more difficult to use inside structs that derive `SystemParam`.

@cart thank you for adding the change log and migration guide. I thought that the patch was quite trivial and didn't imply breaking changes, so I omitted them, but you were right to note that it requires specifying mutability in the arguments.

**Pull request closed without merging**
