### PR TITLE
Make markdown link checking only check internal links

### PR DESCRIPTION
**Pull request by DJMcNab**
# Objective

- This has begun spuriously failing again

## Solution

- Make it less likely to spuriously fail.
- I've tried to test this locally, but the tool appears to just not do anything - I'm not sure what the output should be.

### CODE REVIEW

**Comment by james7132** [comment]
Probably should just remove it altogether if it's still failing on this PR.

**Comment by cart** [comment]
Yup I think we should remove it completely for now

**Comment by james7132** [comment]
Closing this as #4839 was merged.

**Comment by james7132** [comment]
Just didn't want to block other PRs until the config was fixed. If we still want those checks for the future, we can revert the removal with a more scoped config.

**Pull request closed without merging**
