### PR TITLE
Right-aligned text crash fix

### LINKED ISSUE #9395: right-aligned text panic
## Bevy version

0.11 & main

## What you did
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn(
        TextBundle::from_section(
            format!(" H\nHH"),
            TextStyle::default(),
        )
        .with_text_alignment(TextAlignment::Right)
    );
}
```

## What went wrong
```
thread 'Compute Task Pool (3)' panicked at 'min > max, or either was NaN. min = 15.000002, max = 10.000001'
```

This bug was reported before on [discord](https://discord.com/channels/691052431525675048/1135561200739041361/1135561200739041361) but without a replication

##  Additional Details

The horizontal bounds for right-aligned text containing spaces are calculated incorrectly. In the example above the space is counted twice causing the min-content-width to be larger than the max-content-width, causing a crash when the measure func attempts to clamp the available space.

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

UI text nodes have a `MeasureFunc` the layout algorithm uses to determine how much space in the layout to allot for text.
For this, the `MeasureFunc` requires the `min-content-width` and `max-content-width` values for the text. 
* `min-content-width` is where the text wraps on every soft line breakpoint (i.e. every space), which normally means its value is set to the logical pixel width of the longest word in the text.
* `max-content-width` is the width of the text if it never has to wrap at soft line breakpoints.

These values are precomputed by the `compute_text_bounds` function.

To get the `min-content-width` value we call the `calculate_glyphs` method of `glyph_brush_layout::Layout` with size bounds of zero width by infinite height. `calculate_glyphs` returns a Vec of glyphs with each glyph positioned so that the text will fit within the bounds specified. Each line of glyphs is guaranteed to have at least one word, if possible, even if that word exceeds the width bound. That is, it guarantees the glyphs are returned in a min-content-size arrangement. Then the function `compute_text_bounds` is called to find the minimum bounding Rect that contains all the glyphs. The width of the rect returned by `compute_text_bounds` is our `min-content-width`.

The problem comes with right-aligned text:
* Left-aligned text starts at the origin and then each glyph is placed to the right with increasing positive x coordinates. 
* Right-aligned text starts at a point with x equal to negative of the length of the current line and ends at x = 0.
For left- and center-aligned text `calculate_glyphs` works correctly (at least according to my tests) but for right-aligned text with lines containing leading or inbetween soft-breaks such as:
```
" H\nHH"
```
The soft break characters are positioned as though they are left-aligned instead:

text-min-content_bug

So after `compute_text_bounds`, we have widths of:
* min_content_width = 10 - (-20) = 30
* max_content_width = 0 - (-20) = 20

Then when the layout algorithm runs and calls the `MeasureFunc` for this text with a defined `AvailableSpace` value the `MeasureFunc attempts to clamp the available width here:
```rust
 let x = width.unwrap_or_else(|| match available_width {
            AvailableSpace::Definite(x) => x.clamp(
                self.info.min_width_content_size.x,
                self.info.max_width_content_size.x,
            ),
            AvailableSpace::MinContent => self.info.min_width_content_size.x,
            AvailableSpace::MaxContent => self.info.max_width_content_size.x,
        });
```
Which leads to a panic:
```
min > max, or either was NaN. min = 30, max = 20.
```

fixes #9395

## Solution
The left bound of the text is returned correctly and, for right-aligned text, the right bound will always be zero.

So we just need to check if the text is right-aligned and, if it is, set the right bound of the bounding `Rect` to zero before returning it from `compute_text_bounds`.

## Changelog

* Added a `TextAlignment` parameter to  `compute_text_bounds`.
* If the text is aligned right, `compute_text_bounds` sets the right bound of the text's bounding `Rect` to 0.

### CODE REVIEW

**Comment by ickshonpe** [comment]
I'd prefer to replicate this in glyph_brush_layout and locate exactly where the problem is (assuming it isn't something in Bevy that I missed after all) but this is a serious bug and needs to be fixed immediately.

**Comment by alice-i-cecile** [comment]
> I'd prefer to replicate this in glyph_brush_layout and locate exactly where the problem is (assuming it isn't something in Bevy that I missed after all) but this is a serious bug that needs an immediate fix.

For me, this is just more reason to migrate to cosmic_text (#7616). @tigregalis, can you do a quick review to help reassure me that we haven't missed the source of the bug in Bevy itself?

**Review by alice-i-cecile — APPROVED** [review]

**Comment by tigregalis** [comment]
> > I'd prefer to replicate this in glyph_brush_layout and locate exactly where the problem is (assuming it isn't something in Bevy that I missed after all) but this is a serious bug that needs an immediate fix.
> 
> For me, this is just more reason to migrate to cosmic_text (#7616). @tigregalis, can you do a quick review to help reassure me that we haven't missed the source of the bug in Bevy itself?

I think this is a bug in glyph_brush_layout, not introduced in Bevy.

For the text `"  H\nHH"`:

```
align Left:
" " @ 0,12
" " @ 4,12
"H" @ 0,28
"H" @ 0,43
"H" @ 10,43

align Center:
" " @ 0,12
" " @ 4,12
"H" @ -5,28
"H" @ -10,43
"H" @ 0,43

align Right:
" " @ 0,12
" " @ 4,12
"H" @ -10,28
"H" @ -20,43
"H" @ -10,43
```

<details>
<summary>
Reproduction:
</summary>

```rs
use glyph_brush_layout::{ab_glyph::*, *};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let dejavu = FontRef::try_from_slice(include_bytes!("../DejaVuSans.ttf"))?;

    let fonts = &[dejavu];

    let sections = ["  H\nHH"];

    for align in [
        HorizontalAlign::Left,
        HorizontalAlign::Center,
        HorizontalAlign::Right,
    ] {
        let glyphs = Layout::default().h_align(align).calculate_glyphs(
            fonts,
            &SectionGeometry {
                screen_position: (0.0, 0.0),
                bounds: (0.0, f32::MAX),
            },
            &[SectionText {
                text: &sections[0],
                scale: PxScale::from(15.5),
                font_id: FontId(0),
            }],
        );

        println!();
        println!("align {:?}: ", align);
        for glyph in glyphs {
            let character = &sections[glyph.section_index][glyph.byte_index..glyph.byte_index + 1];
            println!(
                "{:?} @ {},{}",
                character,
                glyph.glyph.position.x.round(),
                glyph.glyph.position.y.round(),
            );
        }
    }
    Ok(())
}

```
</details>

The spaces always advance from the left.

Mind you, cosmic text has its own issues with right alignment for the purposes of measuring "content size": https://github.com/pop-os/cosmic-text/issues/42#issuecomment-1607731931

**Comment by ickshonpe** [comment]
Yeah, soft line breaks don't work properly at all. Soft breaks on center- and right-aligned text are positioned after the white space characters, not at the end of the words, which results in an empty gap between the text and the node's right edge. 

I think it's probably pointless doing any more in Bevy than this and the trailing lines PR. My suspicion is it would take some ugly hacks to fix the remaining problems without changes to glyph_brush_layout. I'll make an issue at their repository but don't think it's worth our time to fix it ourselves, the effort is better put into the cosmic-text implementation and finding any remaining taffy measure func bugs.

**Comment by rparrett** [comment]
> The simplest solution may be to ignore spaces when calculating the text bounds' width.

This strategy does seem to fix the crash.

```rust
diff --git a/crates/bevy_text/src/glyph_brush.rs b/crates/bevy_text/src/glyph_brush.rs
index 9aab58ee9..1fbf93317 100644
--- a/crates/bevy_text/src/glyph_brush.rs
+++ b/crates/bevy_text/src/glyph_brush.rs
@@ -219,6 +219,9 @@ where
 
     for sg in section_glyphs {
         let scaled_font = get_scaled_font(sg.section_index);
+        if sg.glyph.id == scaled_font.glyph_id(' ') {
+            continue;
+        }
         let glyph = &sg.glyph;
         text_bounds = text_bounds.union(Rect {
             min: Vec2::new(glyph.position.x, 0.),
```

Can you think of any tricky scenarios to test / possible side effects?

I think it might not be unheard of to use a space to keep a text node from having its height collapsed or something like that. Users would be able to work around this, probably.

Maybe just the x bound should be ignored for spaces?

I'll do some more testing later.

**Comment by rparrett** [comment]
Do we have an upstream issue filed yet?

**Comment by tigregalis** [comment]
> Do we have an upstream issue filed yet?
> 
> edit: [alexheretic/glyph-brush#167](https://github.com/alexheretic/glyph-brush/issues/167)

On the assumption that we're replicating browser behaviour, and reading through that issue and comparing to browser behaviour I've changed my mind. The behaviour of glyph_brush_layout is correct... the problem is that min-content-width is in fact larger than max-content-width.

So the solution is not necessarily to ignore the space "glyphs" like I previously suggested, but I don't think special-casing on right-alignment is perfect either.

The assertion that max-content-width is greater than min-content-width that leads to the panic may not necessarily be correct. But I'm not sure what the solution should be since that seems like a logical assertion.

max-content-width:
image

min-content-width:
image
image

**Comment by alice-i-cecile** [comment]
> On the assumption that we're replicating browser behaviour
This seems like an non-goal, to be honest.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
On re-review, I'm less convinced by this fix, even if the bug is pretty severe.

> So the solution is not necessarily to ignore the space "glyphs" like I previously suggested, but I don't think special-casing on right-alignment is perfect either.

I agree with this comment, and I'm not fully sure how to best fix this other than "migrate to cosmic-text and try to reproduce". Removing from the milestone to avoid rushing in something half-baked :(

**Comment by rparrett** [comment]
Does something like
```diff
diff --git a/crates/bevy_ui/src/widget/text.rs b/crates/bevy_ui/src/widget/text.rs
index 5ff128ebb..f035b7fc8 100644
--- a/crates/bevy_ui/src/widget/text.rs
+++ b/crates/bevy_ui/src/widget/text.rs
@@ -52,8 +52,10 @@ impl Measure for TextMeasure {
         available_width: AvailableSpace,
         _available_height: AvailableSpace,
     ) -> Vec2 {
+        let min_x = self.info.min.x.min(self.info.max.x);
+        let max_x = self.info.min.x.max(self.info.max.x);
         let x = width.unwrap_or_else(|| match available_width {
-            AvailableSpace::Definite(x) => x.clamp(self.info.min.x, self.info.max.x),
+            AvailableSpace::Definite(x) => x.clamp(min_x, max_x),
             AvailableSpace::MinContent => self.info.min.x,
             AvailableSpace::MaxContent => self.info.max.x,
         });
```

Seem misguided? Might do some more thorough testing with that later if it doesn't seem obviously wrong.

**Comment by rparrett** [comment]
The patch above seems to at the very least not change the output any of the existing examples containing text.

**Comment by rparrett** [comment]
#10271 was merged.

**Pull request closed without merging**
