### PR TITLE
Add GitHub Stars Over Time Graph to README

### PR DESCRIPTION
**Pull request by zicklag**
This is an interesting metric that could be cool to have on your README. No problem if you don't want it there. :slightly_smiling_face:.

### CODE REVIEW

**Comment by cart** [comment]
Definitely a fun graph, but I don't think I want to give it "prime real-estate" in the main README

**Comment by zicklag** [comment]
A valid point. I was kind of on the fence with it. :smiley:

**Comment by cart** [comment]
I'll try to think of another place we can put this.

**Comment by cart** [comment]
(but yeah lets leave this closed for now)

**Pull request closed without merging**
