### PR TITLE
examples: add rng coloring to bevymark birds

### PR DESCRIPTION
**Pull request by Fishrock123**
This is something done by a lot of the "bunnymark" tests, and it makes it easier to really see how many you've added.

Idk it was fun.

I can probably make this more efficient by splitting the mouse handler in two but I figure it's probably not worth it.

### CODE REVIEW

**Comment by cart** [comment]
I agree that this is more fun. It changes the benchmark slightly because each click produces a new material (whereas previously they all shared the same material). But in practice it doesn't really affect performance, given that the amount of material sharing is still high (one new material per click).

I'm down to merge this. Just run resolve the cargo fmt errors and we're good to go!

**Comment by Fishrock123** [comment]
>  It changes the benchmark slightly because each click produces a new material (whereas previously they all shared the same material).

Correct, although I think in the long term that is probably more practical from perf testing overall.

Is `cargo fmt` run on all of the bevy repo? It causes some line ending issues on my machine, possibly from a faulty older checkout? (I am running Windows.)

**Comment by cart** [comment]
`cargo fmt --all` covers the whole workspace. We use `cargo +nightly fmt --all` because stable cargo fmt doesn't support merging imports yet.

**Comment by Fishrock123** [comment]
Sorry this has taken so long, I'm working with Bevy from windows and rustfmt was causing a line ending mess.

Turns out commenting out `newline_style = "Unix"` allows everything to work as expected - this is because my Git on Windows uses` CRLF` locally but syncs files as `LF`. (I forget how that is set up.)

However, after rebasing, something more mysterious has appeared:
```
error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> examples/tools/bevymark.rs:210:17
    |
210 |     let r = rng.gen_range(0.2, 1.0);
    |                 ^^^^^^^^^ ---  --- supplied 2 arguments
    |                 |
    |                 expected 1 argument

```

This error is bizarre, after all, `gen_range` is defined as:
```rust
    fn gen_range<T: SampleUniform, B1, B2>(&mut self, low: B1, high: B2) -> T
    where
        B1: SampleBorrow<T> + Sized,
        B2: SampleBorrow<T> + Sized,
    {
        T::Sampler::sample_single(low, high, self)
    }
    ```

**Comment by mockersf** [comment]
the `rand` dependency has been updated to 0.8, and now `gen_range` takes a range instead of taking its bounds:
https://docs.rs/rand/0.8.3/rand/trait.Rng.html#method.gen_range

tools like rust analyser sometimes fails to detect changes in dependencies after a rebase and will still check with the previous version...

**Comment by bjorn3** [comment]
> tools like rust analyser sometimes fails to detect changes in dependencies after a rebase and will still check with the previous version...

Saving a `Cargo.toml` even without any changes should cause rust-analyzer to call `cargo metadata` again to get the updated crate graph.

**Comment by Fishrock123** [comment]
Ah, that would do it. Updated again, hopefully I have addressed CI.

**Pull request merged**
