### PR TITLE
Wslg docs

### PR DESCRIPTION
**Pull request by jimmcnulty41**
# Objective

- WSL documentation was out-of-date and potentially misleading. The release of WSLg makes a lot of stuff easier

## Solution

- Just updating docs for now

## NB
I haven't been able to get a full end-to-end GPU on WSL test going yet, but plan to update this documentation again once I have more of a grasp on that

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by IceSentry** [comment]
This may have changed, but wslg was only available with windows 11 in the past.

**Review by IceSentry — APPROVED** [review]
Alright, I read the docs again. It seems they finally accepted that maybe supporting windows 10 too is a good idea. I remember originally they had no plans to do it.

**Comment by jimmcnulty41** [comment]
> This may have changed, but wslg was only available with windows 11 in the past.

I don't have a windows 10 instance to test on, but my understanding (from the [wslg release ](https://blogs.windows.com/windows-insider/2021/04/21/announcing-windows-10-insider-preview-build-21364/)and the[ wslg docs](https://github.com/microsoft/wslg)) is that it is available on up-to-date windows 10 installs

**Comment by Elabajaba** [comment]
I'd probably mention something about getting an up to date version of mesa (eg. through the kisak ppa for ubuntu) to run bevy on vulkan instead of gl (since bevy's GL targets GLES 3.0/webgl2 which is extremely limiting).

**Comment by inodentry** [comment]
I took this opportunity to do some research and try running Bevy from WSLg myself. I have now added detailed instructions for it in Bevy Cheatbook: https://bevy-cheatbook.github.io/platforms/windows.html#running-linux-builds-using-wslg

**Pull request merged**
