### PR TITLE
Add discord shield badge to README

### PR DESCRIPTION
**Pull request by TotalKrill**
This would highlight how active the community really is at just a glance, which is nice. It will however require an admin of the discord server to activate this under Server Settings->Widget-> enable server widget

### CODE REVIEW

**Comment by DJMcNab** [comment]
Rendered: [Discord](https://discord.gg/gMUk5Ph)

**Comment by TotalKrill** [comment]
Yes, it will render like that until the settings on the discord server has been activated. 

after that it should look something like this: 
image

**Comment by joshuajbouw** [comment]
The widget has to be turned on the discord too, does it not?

Also, alternatively, I use all shields from this personally. It unifies the design across everything and you can customise it: https://shields.io

Worth a consideration :)

**Comment by cart** [comment]
I dig it!

@joshuajbouw doesn't this pr already use shields.io?

**Comment by joshuajbouw** [comment]
Oh! So it does 😆

**Pull request merged**
