### PR TITLE
Add ability to panic to logs example

### PR DESCRIPTION
**Pull request by stepancheg**
# Objective

To debug issues like https://github.com/bevyengine/bevy/pull/11169.

## Solution

When P is pressed in logs example, call `panic!()`.

Screenshot 2024-01-02 at 01 10 16

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Might be simpler to just generate UI for the text, but I have no objection to using Text2D instead.

**Comment by stepancheg** [comment]
> UI for the text

How to do that, `TextBundle`?

**Comment by alice-i-cecile** [comment]
Yep, `TextBundle`. You probably don't need to spawn a camera that way.

**Comment by stepancheg** [comment]
Tried using `TextBundle`, 2D camera is still needed, and text by default gets into the top-left corner instead of center.

So I'm keeping as is for simplicity.

**Review by matiqo15 — APPROVED** [review]

**Comment by mockersf** [comment]
I would also prefer a `TextBundle` to keep consistency with other examples. Most examples have their instruction displayed on the top left corner.

**Comment by stepancheg** [comment]
Github does not see the updated in my branch in this PR: https://github.com/bevyengine/bevy/compare/main...stepancheg:bevy:logs-panic

**Pull request merged**
