### PR TITLE
remove gcd impl from bevy_render

### PR DESCRIPTION
**Pull request by atlv24**
# Objective

- bevy_render (poorly) implements gcd (which should be in bevy_math but theres not enough justification to have it there either anyways cus its just one usage)

## Solution

- hardcoded LUT replacement for the one usage

## Testing

- verified the alternative implementation of 4/gcd(4,x) agreed with original for 0..200

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by IQuick143 — APPROVED** [review]

**Comment by BenjaminBrienen** [comment]
Shouldn't this have a unit test for at least a few cases?

**Review by BenjaminBrienen — APPROVED** [review]

**Comment by BenjaminBrienen** [comment]
`assert_eq!` could've been used, but it doesn't matter at all for this.

**Comment by atlv24** [comment]
`assert_eq!` cant be used, it doesnt work in `const {}` context

**Comment by atlv24** [comment]
i can add tests, most of the renderer doesnt have any

**Comment by atlv24** [comment]
actually adding tests would require implementing gcd again, and if i hardcode values then the tests would literally be testing to check if an array equals itself. not much point here i think

**Comment by atlv24** [comment]
just leaving this here in case anyone wants to slap it into rust playground just to satisfy the itch
```rs
fn main() {
    for i in 0..200 {
        let a = (4 / gcd(i, 4)) as u32;
        let b = [1, 4, 2, 4][i as usize & 3];
        assert_eq!(a, b);
    }
    println!("done");
}

fn gcd(mut a: u64, mut b: u64) -> u64 {
    while b != 0 {
        let t = b;
        b = a % b;
        a = t;
    }
    a
}
```

**Pull request merged**
