### PR TITLE
Add Grid gizmos

### PR DESCRIPTION
**Pull request by solis-lumine-vorago**
# Objective

- Implement grid gizmos, suggestion of #9400 

## Solution

- Added `gizmos.grid(...) ` and `gizmos.grid_2d(...)`
- The grids may be configured using `.outer_edges(...)` to specify whether to draw the outer border/edges of the grid and `.skew(...)`to specify the skew of the grid along the x or y directions.

---

## Changelog

- Added a `grid` module to `bevy_gizmos` containing `gizmos.grid(...) ` and `gizmos.grid_2d(...)` as well as assorted items.
- Updated the `2d_gizmos` and `3d_gizmos` examples to use grids.

## Additional

The 2D and 3D examples now look like this:
Screenshot 2024-02-20 at 15 09 40
Screenshot 2024-02-20 at 15 10 07

### CODE REVIEW

**Review by afonsolage — CHANGES_REQUESTED** [review]
I ran the examples and they are fine and I'm not a math guy, but the implementation seems fine too, my only point is about `grid_2d` since to me both grids are `2d`, since a `grid_3d` would means, at least to me, a "cubic grid" not a "square grid".

IMO we should have only `grid` and showcase how to use them in `2d_gizmos` and `3d_gizmos`.

**Comment by afonsolage** [comment]
Sorry if I wasn't clear, but my point is I don't think we need a `gizmos_2d` just `gizmos` is enough.

**Comment by solis-lumine-vorago** [comment]
Yes, this would still provide all the functionality, but isn't approachable for new users. Imagine someone building a 2D game: they have only dealt with `Vec2` positions and `f32` rotations. If they want to draw a gizmo, they should continue to be fine with that and not be forced to learn about quaternions just for gizmos.

**Comment by pablo-lua** [comment]
In reality, would be good to have a cubic grid IMO. And one could fine good to be able to change the space between X lines and Y lines. (In the cubic grid example, we would have Z lines)

**Review by pablo-lua — CHANGES_REQUESTED** [review]
Can we maybe change the color of the grid lines in the example? It was a bit hard to me to see at first. Maybe we can use white?

**Comment by solis-lumine-vorago** [comment]
> And one could find good to be able to change the space between X lines and Y lines.

I'm not sure I understand this . You can have different spacings for x and y lines already. Simply pass something like `Vec2::new(2., 1.)` as the spacing argument. Am I missing something?

**Comment by pablo-lua** [comment]
> > And one could find good to be able to change the space between X lines and Y lines.
> 
> I'm not sure I understand this . You can have different spacings for x and y lines already. Simply pass something like `Vec2::new(2., 1.)` as the spacing argument. Am I missing something?

Not really, I'm saying thats good, sorry, wasn't clear.
The only thing that I think deserves to be there is the cubic grid in reality, as Users can find good use in it for debug purposes

**Comment by afonsolage** [comment]
> > > And one could find good to be able to change the space between X lines and Y lines.
> > 
> > I'm not sure I understand this . You can have different spacings for x and y lines already. Simply pass something like `Vec2::new(2., 1.)` as the spacing argument. Am I missing something?
> 
> Not really, I'm saying thats good, sorry, wasn't clear.
> The only thing that I think deserves to be there is the cubic grid in reality, as Users can find good use in it for debug purposes 
> 
> 

But as follow-up PR, right? Because I think a cubic-grid is out of scope of this PR, since this can be controversial, since the implementation can be trick IMO.

**Comment by solis-lumine-vorago** [comment]
> Can we maybe change the color of the grid lines in the example? It was a bit hard to me to see at first. Maybe we can use white?

White was a bit overwhelming, but it should be better now.

**Comment by pablo-lua** [comment]
> But as follow-up PR, right? Because I think a cubic-grid is out of scope of this PR, since this can be controversial, since the implementation can be trick IMO.

Yea, we can track this in #9400

**Comment by solis-lumine-vorago** [comment]
> But as follow-up PR, right? 

I think I could add this here, if that is ok. It would be just adding another axis to the existing implementation and something like `gizmos.cubic_grid(...)`

**Comment by pablo-lua** [comment]
> I think I could add this here, if that is ok. It would be just adding another axis to the existing implementation and something like `gizmos.cubic_grid(...)`

If we implement in the same way that is now, I think that's okay, but might be good keep this as uncontroversial as possible and do this in a follow-up? Not sure.
About the cubic_grid part, wouldn't be better call it "grid_3d" or only "grid" to keep the convention?

**Comment by solis-lumine-vorago** [comment]
> > I think I could add this here, if that is ok. It would be just adding another axis to the existing implementation and something like `gizmos.cubic_grid(...)`
> 
> If we implement in the same way that is now, I think that's okay, but might be good keep this as uncontroversial as possible and do this in a follow-up? Not sure. About the cubic_grid part, wouldn't be better call it "grid_3d" or only "grid" to keep the convention?

Ok, fair enough. As for the name, we already have `.grid` which we could just extend to include a third axis or we could do something like `.lattice`? I don't think `grid_3d` would be a good idea though, as it suggests (at least to me) that it is the same shape as `.grid` although it is different and more general.

**Comment by pablo-lua** [comment]
Keeping `.grid(...)` to do that function is better IMO.

**Comment by solis-lumine-vorago** [comment]
> Keeping `.grid(...)` to do that function is better IMO.

Ok, so we will add that functionality to `.grid` in a future PR, right?

**Review by pablo-lua — APPROVED** [review]
The math behind this looks fine to me, and nothing to say about the grid itself. All good

**Review by MiniaczQ — APPROVED** [review]
New to gizmos, so seeing `Drop` used for finalizing the builder was interesting

Looks good

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
The `Drop` pattern is a little too clever for my taste, and doesn't appear to be used elsewhere in gizmos. Can we find a simpler solution?

**Comment by solis-lumine-vorago** [comment]
> isn't the drop pattern used in multiple gizmos builders?

Yes, the `Drop` pattern is used for all primitives, ellipses and arcs.

**Comment by alice-i-cecile** [comment]
Ah my apologies, I did a search for `impl Drop`, which didn't reveal anything because of the intervening generics.

**Comment by alice-i-cecile** [comment]
@solis-lumine-vorago can you rebase (the examples got moved) and I'll give this a final pass before merging?

**Review by alice-i-cecile — APPROVED** [review]

**Comment by solis-lumine-vorago** [comment]
> @solis-lumine-vorago can you rebase (the examples got moved) and I'll give this a final pass before merging?

Yeah sure, it appears that `Color` was renamed but it should be all good now.

**Comment by solis-lumine-vorago** [comment]
@alice-i-cecile Could you enable Auto-merge again, please :)

**Comment by solis-lumine-vorago** [comment]
thx :D

**Pull request merged**
