### PR TITLE
Add `Transform::is_finite`

### PR DESCRIPTION
**Pull request by johanhelsing**
# Objective

- Sometimes it's very useful to know if a `Transform` contains any `NaN` or infinite values. It's a bit boiler-plate heavy to check translation, rotation and scale individually.

## Solution

- Add a new method `is_finite` that returns true if, and only if translation, rotation and scale all are finite.
- It's a natural extension of `Quat::is_finite`, and `Vec3::is_finite`, which return true if, and only if all their components' `is_finite()` returns true.

---

## Changelog

- Added `Transform::is_finite`

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by johanhelsing** [comment]
I wanted this when implementing a checksum function for `Transform`s with bevy_ggrs: https://johanhelsing.studio/posts/extreme-bevy-desync-detection#back-to-synctest-sessions

```rust
    let mut hasher = FixedState::build_hasher();

    assert!(
        transform.translation.is_finite() && transform.rotation.is_finite(),
        "Hashing is not stable for NaN f32 values."
    );

    transform.translation.x.to_bits().hash(&mut hasher);
    transform.translation.y.to_bits().hash(&mut hasher);
    transform.translation.z.to_bits().hash(&mut hasher);

    transform.rotation.x.to_bits().hash(&mut hasher);
    transform.rotation.y.to_bits().hash(&mut hasher);
    transform.rotation.z.to_bits().hash(&mut hasher);
    transform.rotation.w.to_bits().hash(&mut hasher);

    // skip transform.scale as it's not used for gameplay

    hasher.finish()
```

**Review by IQuick143 — APPROVED** [review]
Seems fine to me.

**Review by mockersf — CHANGES_REQUESTED** [review]
this function should probably be marked as inlined, I think the glam versions are already

**Comment by johanhelsing** [comment]
> this function should probably be marked as inlined, I think the glam versions are already

They are. Added it. I also added `must_use` even though glam doesn't (f32 has it though).

**Review by mockersf — APPROVED** [review]

**Pull request merged**
