### PR TITLE
Upgrade glam from 0.8.7 to 0.9.3

### PR DESCRIPTION
**Pull request by bitshifter**
There was a breaking change from glam 0.8 to 0.9 which made `Vec3` no longer use SIMD meaning its size and alignment changed. Because bevy is re-exporting glam's math types I think it would be good to get this change in so less users are affected by it further down the track. The `Vec3A` type was added to glam which has the SIMD implementation.

I see you commented on the glam issue tracking this change so hopefully the breaking change isn't a horrible surprise! (https://github.com/bitshifter/glam-rs/issues/36)

This PR could break some Vec3 GLSL uniform bindings although I didn't notice any `Vec3` uniforms when looking at the source.

glam 0.9.3 also added `Mat4::perspective_rh` removing the need for your own implementation.

I tried this change with a few of your examples and everything seemed to work. The `spawner` example seemed a little faster with this change.

### CODE REVIEW

**Comment by cart** [comment]
This is definitely a welcome change, but last time i checked there was a case where we relied on the old alignment in one of our shaders. Lemme take a look and make sure this doesn't break anything.

**Comment by cart** [comment]
(CI breakage was my fault)

**Comment by bitshifter** [comment]
I had a bit of a hunt around but didn't find anything, that said I am not familiar with bevy. While I couldn't find any vec3 uniforms if someone did use one bad things might happen. The Vertex format appeared to use arrays rather than glam types so they looked OK. bevy looks great btw!

**Comment by cart** [comment]
It looks like I removed the type I was worried about during a Bevy UI refactor. I'm gonna run some quick validations on my end, but this looks good to go.

**Comment by cart** [comment]
This is good to go, but I'm having issues getting CI to pass. Its failing on the bevy_ron crate. Earlier we pushed a fix to master, but retrying the github action appears to keep using the old version? Idk how to force it to test a merge with the latest master. (im not new to git or CI, but I _am_ new to Github Actions and github CI)

**Comment by bitshifter** [comment]
I can try update the PR with latest master, see if that helps

**Comment by cart** [comment]
brilliant. thanks!

**Pull request merged**
