### PR TITLE
Add clear coat standard material parameter

### PR DESCRIPTION
**Pull request by JMS55**
## Feature

Adds two new parameters to `StandardMaterial` (`clear_coat` and `clear_coat_perceptual_roughness`) in order to implement an additional clear coat layer over the base material.

Unfortunately, I cannot show a screenshot, as we currently don't have any form of indirect lighting to show off reflections with.

---

Implementation based on Filament: https://google.github.io/filament/Filament.html#materialsystem/clearcoatmodel.

Filament also notes that:

>  We should also modify the base layer's apparent roughness based on the IOR of the clear coat layer but this is something we have opted to leave out for now. 

But I am unsure what that would entail.

---

## Changelog

- Added two new fields to `StandardMaterial`: `clear_coat` and `clear_coat_perceptual_roughness`

### CODE REVIEW

**Comment by IceSentry** [comment]
You should probably add a note on the parameters that they won't do much until we have indirect lighting support.

**Comment by superdump** [comment]
Adding support for loading the values from glTF and testing with this would be good https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ClearCoatTest but I guess we would _really_ benefit from image-based lighting before clear coat becomes directly useful.

**Comment by alice-i-cecile** [comment]
This seems great, but I'm going to block merging this until we can test it with indirect lighting :)

**Comment by JMS55** [comment]
Ah, didn't mean to push this yet. Now that I added environment maps, I'm working on adapting clear coat to work with it. Also, I will look into adding support for glTF loading for clear coats.

**Comment by JMS55** [comment]
Status update: I've been reading about BRDF representations and material layering recently. Realtime, physically based material layers are kind of an unsolved problem at the moment. 

There's a couple of different systems we could adopt, ranging from linear mixes of a fixed set of layers, to much more physically accurate, but more expensive blending of arbitrary layers, and other systems in between. 

Currently, Bevy does not have a single brdf() function used for all lighting calculations, so we would also need a refactor (that I've mostly completed, but not yet pushed) to consolidate the brdf calculations.

The lack of a clear direction, and the dubious value of better materials when there's other rendering improvements that are more needed, has started to cause me to burn out on this. I will probably be taking a break from this for a bit.

**Comment by JMS55** [comment]
I have no motivation to continue this at the moment. However, if someone wants to pick this up, it should be fairly straightforward, and I would be happy to provide guidance.

It's just a bunch of boilerplate of adding the material properties and plugging them through the shaders in the correct way, and then a little bit of research and math needed for the actual lighting calculations and how the clear coat should be layered, and writing an example and documentation and stuff.

**Pull request closed without merging**
