### PR TITLE
Revert rendering-related associated type name changes

### PR DESCRIPTION
**Pull request by alice-i-cecile**
# Objective

>  Can anyone explain to me the reasoning of renaming all the types named Query to Data. I'm talking about this PR https://github.com/bevyengine/bevy/pull/10779 It doesn't make sense to me that a bunch of types that are used to run queries aren't named Query anymore. Like ViewQuery on the ViewNode is the type of the Query. I don't really understand the point of the rename, it just seems like it hides the fact that a query will run based on those types.

[@IceSentry](https://discord.com/channels/691052431525675048/692572690833473578/1184946251431694387)

## Solution

Revert several renames in #10779.

## Changelog

- `ViewNode::ViewData` is now `ViewNode::ViewQuery` again.

## Migration Guide

- This PR amends the migration guide in https://github.com/bevyengine/bevy/pull/10779

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Of the remaining changes, I could go either way on the renames. @IceSentry, I'll defer to your preferences here: just tell me which ones you'd like reverted.

**Comment by JMS55** [comment]
I prefer ViewNode::ViewQuery

**Comment by IceSentry** [comment]
Here's my opinion on all of these:

* Trait's ExtractComponent type Query has been renamed to Data.
	* Revert it to Query or QueryData
* Trait's GetBatchData types Query & QueryFilter has been renamed to Data & Filter, respectively.
	* QueryData and QueryFilter
* Trait's ExtractInstance type Query has been renamed to Data.
	* Revert it to Query or QueryData
* ~~Trait's ViewNode type ViewQuery has been renamed to ViewData.~~
* Trait's RenderCommand types ViewWorldQuery & ItemWorldQuery has been renamed to ViewData & ItemData, respectively.
	* I'd prefer ViewQuery and ItemQuery

Essentially, in the spirit of the original PR, drop the `World` where it isn't needed, but keep the `Query` terminology otherwise. I mostly don't like when types are just called `Data` because it doesn't really give any hints as to what it actually is.

**Review by JoJoJet — APPROVED** [review]
I agree with this. I think we should also implement the other renames IceSentry suggested.

**Review by rodolphito — APPROVED** [review]
looks good, also here's icesentry's rename suggestions implemented and tested
https://github.com/alice-i-cecile/bevy/pull/163

**Pull request merged**
