### PR TITLE
Explicitly run `+nightly` for `-Zcheck-cfg` pass in ci.

### PR DESCRIPTION
**Pull request by targrub**
# Objective

Getting this error running ci locally.

```
$ cargo check -Zcheck-cfg --workspace
error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
thread 'main' panicked at tools\ci\src\main.rs:166:14:
Please fix failing cfg checks in output above.: command exited with non-zero code `cargo check -Zcheck-cfg --workspace`: 101
```

## Solution

- Add `+nightly` flag to the `check-cfg` pass.

---

Obviously we shouldn't be running `nightly` Cargo, but at least now local running of `cargo run -p ci` will pass.

### CODE REVIEW

**Comment by rparrett** [comment]
I am seeing this output locally:
```
 cargo run -p ci cfg-check
    Blocking waiting for file lock on build directory
   Compiling ci v0.1.0 (/Users/robparrett/src/bevy/tools/ci)
    Finished dev [unoptimized + debuginfo] target(s) in 13.70s
     Running `target/debug/ci cfg-check`
$ cargo check +nightly -Zcheck-cfg --workspace
error: unexpected argument '+nightly' found
```

**Review by rparrett — APPROVED** [review]

**Review by doonv — APPROVED** [review]

**Comment by targrub** [comment]
Note: The PR for `cfg-check` was https://github.com/bevyengine/bevy/pull/12103.

**Review by mockersf — APPROVED** [review]

**Comment by BD103** [comment]
Perhaps in the future it would be nice to check whether CI is being compiled from a nightly toolchain or not (I'm thinking `build.rs` or `env!`?), to dynamically skip `check-cfg`.

**Comment by targrub** [comment]
```
... previous cargo run -p ci output
...
$ cargo +nightly check -Zcheck-cfg --workspace
error: no such command: `+nightly`

        Cargo does not handle `+toolchain` directives.
        Did you mean to invoke `cargo` through `rustup` instead?
thread 'main' panicked at tools\ci\src\main.rs:166:14:
Please fix failing cfg checks in output above.: command exited with non-zero code `cargo +nightly check -Zcheck-cfg --workspace`: 101
```
That's what I get from `cargo run -p ci`.  But if I run `cargo +nightly check -Zcheck-cfg --workspace` separately, it works.

**Pull request merged**
