### PR TITLE
[Merged by Bors] - Use T::Storage::STORAGE_TYPE to optimize out unused branches

### PR DESCRIPTION
**Pull request by james7132**
# Objective
`EntityRef::get` and friends all type erase calls to fetch the target components by using passing in the `TypeId` instead of using generics. This is forcing a lookup to `Components` to fetch the storage type. This adds an extra memory lookup and forces a runtime branch instead of allowing the compiler to optimize out the unused branch.

## Solution
Leverage `Component::Storage::STORAGE_TYPE` as a constant instead of fetching the metadata from `Components`.

## Performance
This has a near 2x speedup for all calls to `World::get`. Microbenchmark results from my local machine. `Query::get_component`, which uses `EntityRef::get` internally also show a slight speed up. This has closed the gap between `World::get` and `Query::get` for the same use case.

```
group                                                             entity-ref-generics                     main
-----                                                             -------------------                     ----
query_get_component/50000_entities_sparse                         1.00   890.6±40.42µs        ? ?/sec     1.10   980.6±28.22µs        ? ?/sec
query_get_component/50000_entities_table                          1.00   968.5±73.73µs        ? ?/sec     1.08  1048.8±31.76µs        ? ?/sec
query_get_component_simple/system                                 1.00    703.2±4.37µs        ? ?/sec     1.00    702.1±6.13µs        ? ?/sec
query_get_component_simple/unchecked                              1.02    855.8±8.98µs        ? ?/sec     1.00    843.1±8.19µs        ? ?/sec
world_get/50000_entities_sparse                                   1.00    202.3±3.15µs        ? ?/sec     1.85   374.0±20.96µs        ? ?/sec
world_get/50000_entities_table                                    1.00    193.0±1.78µs        ? ?/sec     2.02   389.2±26.55µs        ? ?/sec
world_query_get/50000_entities_sparse                             1.01    162.4±2.23µs        ? ?/sec     1.00    161.3±0.95µs        ? ?/sec
world_query_get/50000_entities_table                              1.00    199.9±0.63µs        ? ?/sec     1.00    200.2±0.74µs        ? ?/sec
```

This should also, by proxy, speed up the `ReflectComponent` APIs as most of those use `World::get` variants internally.

### CODE REVIEW

**Comment by BoxyUwU** [comment]
Did you try just passing `StorageType` in as an argument instead of making it generic

**Comment by james7132** [comment]
> Did you try just passing `StorageType` in as an argument instead of making it generic

That'd also work, but it'd add yet another safety invariant and force fetching `ComponentInfo` in untyped APIs onto the caller. Wanted to avoid that where possible. If it's more desirable that we keep code duplication low, I can do this if need be.

**Comment by james7132** [comment]
I've gone ahead and made the APIs not generic again, though the `_with_type` APIs are rather thin wrappers around the untyped APIs at this point. Very tempted to just remove them at this point.

**Review by BoxyUwU — APPROVED** [review]

**Comment by BoxyUwU** [comment]
assuming miri passes I think we should merge this, removing `with_type` can be done in a separate PR

**Review by alice-i-cecile — APPROVED** [review]

**Comment by hymm** [comment]
bors try

**Review by mockersf — APPROVED** [review]

**Review by cart — APPROVED** [review]
Looks good to me. Just resolve the merge conflict and we're good to go!

**Pull request closed without merging**
