### PR TITLE
Add Clone, PartialEq, Ser/De traits to Parent/Children

### PR DESCRIPTION
**Pull request by cBournhonesque**
# Objective

- Add missing traits to hierarchy components `Parent` and `Children`, which could be useful (it would be useful for me)

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
All of these other than PartialEq and Serialize could be abused to break the hierarchy. Not saying we shouldn't do this, but just pointing it out.

**Comment by james7132** [comment]
For the reasons listed above, I'm not too keen on deriving these. Serialize/Deserialize is definitely a maybe if this is being driven by an usability need like network serialization, but I've always been a bit skeptical those kinds of use cases for `Entity` as well.

**Review by james7132 — CHANGES_REQUESTED** [review]
For the reasons listed above, I'm not too keen on deriving these. Serialize/Deserialize is definitely a maybe if this is being driven by an usability need like network serialization, but I've always been a bit skeptical those kinds of use cases for Entity as well. However, Clone is definitely not OK given the possibility of breaking the hierarchy.

**Comment by cBournhonesque** [comment]
> For the reasons listed above, I'm not too keen on deriving these. Serialize/Deserialize is definitely a maybe if this is being driven by an usability need like network serialization, but I've always been a bit skeptical those kinds of use cases for Entity as well. However, Clone is definitely not OK given the possibility of breaking the hierarchy.

Yes exactly, the main use-case is network serialization; I guess I'll resort to making an internal wrapper component for network serialization then, similarly to what replicon does (https://github.com/projectharmonia/bevy_replicon/blob/master/src/parent_sync.rs#L80).

My hope was to avoid this by replicating `Parent` and `Children` directly, but maybe that's not even desirable (as replicating both Parent and Children would duplicate the information transmitted over the wire)

**Pull request closed without merging**
