### PR TITLE
Format ci

### PR DESCRIPTION
**Pull request by Vrixyz**
# Objective

Handling formatting in PR seems to be a pain point, see https://twitter.com/AliceICecile/status/1521107259119517696?s=20&t=UFBfiCQ82b8EhF-ci1QhCA for discussion

## Solution

- a CI task running cargo fmt, then pushing.
- Risks:
  - it will likely double the commits
  - it might add merge commits within pull requests, if an author forgets to pull an automated change from this task

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
😍 You rock, thank you!

**Comment by alice-i-cecile** [comment]
This looks good. IMO there are two paths forward here:

1. Remove the formatting check from the CI, and just do this instead.
2. Make this a manually triggered job with some sort of actions integration, like `bors`. If we went this route, I'm fine with handing out that permission to anyone who comments: formatting is not exactly an expensive or destruction action.

I think my preference is towards the former, but I'm open to being convinced. You can see that we already check as part of the `ci` script [here](https://github.com/bevyengine/bevy/blob/main/tools/ci/src/main.rs#L25), which *should* be run as part of the CI in [ci.yml](https://github.com/bevyengine/bevy/blob/main/.github/workflows/ci.yml).

I can't see where that's being done now though following the last round of changes from @mockersf 🤔

**Comment by mockersf** [comment]
Having CI automatically commit code change on a PR is a bad idea and way more painful that you would think. You can end up conflicting with your own PR between two commits, and then you ask someone to suddenly resolve merge conflicts when they don't even know how to run `cargo fmt`.

Every tool to format code has an option to do just check specifically to run in CI to avoid this issue.

I see two ways to fix that issue:
* a pre commit hook
  * they are not installed by default on a user local clone, but there are workaround that like https://github.com/rhysd/cargo-husky
  * they can be seen as user hostile
* a bot like bors that would react on a specific command to reformat a PR
  * would require some investment in dev/maintenance/trust to get it up

Maybe I'm wrong, but I don't see the problem of bad format in PRs that much of an issue that it needs to be fixed. When it happens, CI is red, and the user learns about `cargo fmt`. This approach is bad, and all the others have downsides...

**Comment by alice-i-cecile** [comment]
Thanks for the explanation, I'm on board. I think a bot is my favorite approach here.

> Maybe I'm wrong, but I don't see the problem of bad format in PRs that much of an issue that it needs to be fixed. When it happens, CI is red, and the user learns about cargo fmt.

The pain point I'm experiencing here is the inability to make trivial fixes to users PRs. Running `cargo fmt` is one of those (and occurs more often than you'd expect due to Github's suggestions bypassing format-on-save). 

Every round of trivial fixes is another context switch, with very variable latency on a volunteer-driven team. They can be helpful for teaching new contributors, but they're also somewhat exhausting, and can make the process feel nitpicky and unwelcoming.

Negotiating trivial fixes like "please run cargo fmt" also bloats the comments, slowing down reviews with noise.

**Comment by alice-i-cecile** [comment]
Going to close this out; we're going to be discussing this further in our retrospective and talking over the best way to handle this class of problems.

**Pull request closed without merging**
