### PR TITLE
Add cursor locking and grabbing API

### PR DESCRIPTION
**Pull request by WesterWest**
I've added a simple cursor grabbing and locking API that is tied to the window creation, that means you cannot hide and unhide cursor in one window, but that shouldn't be a big issue I don't think.

### CODE REVIEW

**Comment by WesterWest** [comment]
Issue waiting on #337, until then clippy test will fail

**Comment by WesterWest** [comment]
There is a bug, that when the Window tries to grab the cursor back on GNOME (cannot test on other platforms) the event is done earlier that GNOME ungrabs the cursor itself and this results in a X11 panic that cannot be caught by result.

**Comment by jamadazi** [comment]
Not being able to dynamically grab/ungrab the cursor *is* a big deal. Usually, you would want to grab the cursor while playing the game (when the mouse is used for controlling the camera) and un-grab it when in menus and such (when you need it to interact with UI).

The bevy cookbook already has an example of [how to do this using an event](https://github.com/jamadazi/bevy-cookbook/blob/master/bevy-cookbook.md#grabbing-the-mouse). It's pretty simple. I think that for it to be worth it to add a new API to bevy, it needs to provide an improvement to usability compared to what can be done without it.

I don't think that what this PR proposes is particularly useful.

**Comment by WesterWest** [comment]
yes, I agree @jamadazi . I don't think this is that useful either.

**Pull request closed without merging**
