### PR TITLE
Make the prepass shader compile when lightmaps are present.

### PR DESCRIPTION
**Pull request by pcwalton**
Commit 3f5a090b1bf6bb8b97972feb5504777f6b380559 added a reference to `STANDARD_MATERIAL_FLAGS_BASE_COLOR_UV_BIT`, a nonexistent identifier, in the alpha discard portion of the prepass shader. Moreover, the logic didn't make sense to me. I think the code was trying to choose between the two UV sets depending on which is present, so I made it do that.

I noticed this when trying Bistro with #13277. I'm not sure why this issue didn't manifest itself before, but it's clearly a bug, so here's a fix. We should probably merge this before 0.14.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
FYI @geckoxx <3 If you'd like to review this fix it would be much appreciated :)

**Review by alice-i-cecile — APPROVED** [review]

**Comment by robtfm** [comment]
it should be using shader def `STANDARD_MATERIAL_BASE_COLOR_UV_B` (which also needs to be defined for the prepass rust-side), similar to the main pass.

**Comment by pcwalton** [comment]
@robtfm OK, I made that change. I believe that the Rust side is already defining that.

**Comment by geckoxx** [comment]
This seems correct. Sorry, I missed this when moving from using material flags to shader defs.

**Review by IceSentry — APPROVED** [review]

**Review by robtfm — APPROVED** [review]

**Review by robtfm — COMMENTED** [review]
actually doesn't seem to work - `error: Too many '# endif' lines. Each endif should be preceded by an if statement.`

**Comment by pcwalton** [comment]
Marking as draft while I investigate.

**Comment by geckoxx** [comment]
The endif in line 27 should be removed.

**Comment by bugsweeper** [comment]
Looks like #13122 should be reopened at current codebase
image

**Pull request merged**
