### PR TITLE
Convenient way to add minimal plugins for a headless server

### PR DESCRIPTION
**Pull request by CleanCut**
It might be useful to make a way for folks to easily run a minimal bit of bevy (think headless server, CI job, etc.).

In that context, would this be a good approach? I based the actual minimal bit of plugins on https://github.com/bevyengine/bevy/issues/739#issuecomment-717390302  My biggest concern is that the loop duration is hard-coded.

Is there a more ideal way to solve this problem?  Maybe in a separate module+trait? Or just document how to do this? Something else?

### CODE REVIEW

**Comment by cart** [comment]
I definitely think something like this would be useful. I want to move off of the "configure plugins in the constructor" pattern as much as possible in favor of "configuration resources" (ex: [AssetServerSettings](https://github.com/bevyengine/bevy/blob/f81208adaaf4eb6d87ef053feef87b6cc6a7e11f/crates/bevy_asset/src/lib.rs#L42)) to solve problems like what we're seeing here with ScheduleRunnerPlugin.

I think the real fix here is to migrate ScheduleRunnerPlugin to the "configuration resource" pattern.

**Comment by cart** [comment]
I'm not super sold on adding another "helper method" like `add_minimal_plugins()`. I'm heavily considering deprecating `add_default_plugins()` in favor of `add_plugin_group(DefaultPlugins)` in future releases.

**Comment by CleanCut** [comment]
@cart -- ...and here I thought I was going to make a _tiny_ little contribution today 😝

- Removed the new helper method I had added in this PR
- Added `MinimalPlugins` to the prelude so it can be used as `add_plugin_group(MinimalPlugins)`
- Introduced a `ScheduleRunnerSettings` resource and refactored `ScheduleRunnerPlugin` to use it similar to the `AssetServerSettings` pattern.
- Moved the `run_once()` and `run_loop()` methods to `ScheduleRunnerSettings`.
- Removed the hard-coded 1/60s loop duration in favor of inheriting the `RunMode` enum's default of looping with no delay.
- Removed the _existing_ helper method `add_default_plugins()` and its trait in favor of `add_plugin_group(DefaultSettings)`.  ⚠️**Fair warning:** This will probably break every project / tutorial / guide ever created.  
- Updated all the examples to fix the breakage caused by ☝️

The current windows nightly seems to be unable to compile `rusty-xinput`. That seems unrelated to this PR.

**Comment by CleanCut** [comment]
Reported the ICE for windows nightly at https://github.com/rust-lang/rust/issues/78660

**Comment by cart** [comment]
thanks! we might need to disable windows nightly builds in the interim.

**Comment by CleanCut** [comment]
Upstream fix is out for review: https://github.com/rust-lang/rust/pull/78663

**Comment by cart** [comment]
Yeah I'm thinking we might as well make the hard `add_default_plugins` break now. Earlier is better

**Comment by zicklag** [comment]
@CleanCut I definitely have a use-case for this with the Bevy benchmark games. It was really annoying to take out the `add_default_plugins` and then have to figure out what plugins depended on each-other and that I needed to enable to get a basic headless game going. Thanks!

> Yeah I'm thinking we might as well make the hard add_default_plugins break now. Earlier is better

:+1: I'm a strong believer of breaking it early.

**Comment by cart** [comment]
Yeah the one thing im not super sold on is the `MinimalPlugins` name. "minimal" in what context? Like in this case its clearly a "headless context". But I'm also not sure I want to call this `HeadlessPlugins`. I think that should be probably be reserved for "headless version of full bevy game", which would include shims for rendering/audio/windowing etc.

**Comment by zicklag** [comment]
>  But I'm also not sure I want to call this HeadlessPlugins. I think that should be probably be reserved for "headless version of full bevy game", which would include shims for rendering/audio/windowing etc.

Yeah, I think that's a good idea for headless.

Maybe `CorePlugins`?

**Comment by cart** [comment]
Yeah I thought about that too. But ScheduleRunner isn't `core` (otherwise it would be a subset of default).

**Comment by cart** [comment]
On that note something like `default_plugins.extend(CorePlugins)` in PluginGroupBuilder might be useful ... although that probably doesn't give enough control over plugin order.

**Comment by cart** [comment]
BaseHeadlessPlugins
CoreHeadlessPlugins
ScheduleRunnerPlugins (probably too similar to ScheduleRunnerPlugin?)
CoreScheduleRunnerPlugins
BaseScheduleRunnerPlugins

Lol naming is hard. I'm also not super worried about needing the name MinimalPlugins for anything else, so we don't necessarily need to make the decision now. But if we can find a clearly better name today we might as well use it

**Comment by zicklag** [comment]
Maybe `HeadlessPlugins` and `ShimmedHeadlessPlugins` for the version with shims?

**Comment by cart** [comment]
Yeah thats not a bad train of thought. Or maybe `HeadlessPlugins` and `HeadlessDefaultPlugins`?

**Comment by zicklag** [comment]
> Or maybe HeadlessPlugins and HeadlessDefaultPlugins?

I'd be confused at what the difference is, though.

Maybe `HeadlessPlugins` and `VirtualizedHeadlessPlugins`? Virtualized sounds fancier than it is though.

Hmm, `MinimalPlugins` is actually sounding kind of good now. Maybe `DefaultSlim`?

**Comment by cart** [comment]
Haha yeah every alternative we've come up with has too many downsides. Lets just stick with MinimalPlugins for now. I guess @CleanCut was a step ahead of us :smile:

**Comment by CleanCut** [comment]
> Haha yeah every alternative we've come up with has too many downsides. Lets just stick with MinimalPlugins for now. I guess @CleanCut was a step ahead of us 😄

😆

**Pull request merged**
