### PR TITLE
[Merged by Bors] - Make events reuse buffers

### PR DESCRIPTION
**Pull request by TheRawMeatball**
I'm really curious why this wasn't the case already...

### CODE REVIEW

**Review by Sheepyhead — APPROVED** [review]

**Review by DJMcNab — APPROVED** [review]

**Review by Ratysz — APPROVED** [review]

**Comment by cart** [comment]
At the time the thought was "garbage collection". If we clear, that means events will always use the amount of memory equal to the number of events generated on the "most active" frame. `Vec::new()` is allocation-free, so we only allocate when there are events on a given frame. For "uncommon events" the current approach is way better, especially if they are "burst-ey and uncommon".

However for "high volume" regular events, clearing will be way faster. This new behavior is also consistent with the rest of bevy_ecs (which is also missing "garbage collection" for cases like this), so im inclined to merge.

But I think components, component tables, and events should have some sort of "shrink capacity by half if `USAGE < CAPACITY /   2` for X updates" approach. "just clearing" isn't good enough. And "reallocating per frame" is abysmal.

**Comment by TheRawMeatball** [comment]
While I could add some heuristic for garbage collection, or expose a method for manually shrinking the vecs as much as possible, I think these would be best done later with a more cohesive vision for how similar things are handled in the rest of the ECS.

**Comment by cart** [comment]
Yeah I do think garbage collection should be handled later (after much discussion). I'm going to merge this as  I do like the consistency with the rest of bevy_ecs.

**Pull request closed without merging**
