### PR TITLE
[Merged by Bors] - unused deps?

### PR DESCRIPTION
**Pull request by gilescope**
# Objective

- less deps.

## Solution

- delete button.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
bors try

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@mockersf, can we add an unused-deps step to our CI in some form?

**Comment by MinerSebas** [comment]
We are already using `cargo-udeps` in the [CI](https://github.com/bevyengine/bevy/blob/main/.github/workflows/ci.yml#L282-L304)

The reason these particular Crates were not found is a Bug in that Tool:
```
Some unused crates might not be detected. This includes crates used by std and its dependencies as well as crates that are already being used by dependencies of the studied crate.
```

**Review by IceSentry — APPROVED** [review]

**Comment by mockersf** [comment]
ci failures from bors are valid and where not noticed before because they were hidden behind other failures (fixed since in another PR)

**Comment by gilescope** [comment]
Ah yeah that's a fair point - alas cargo check doesn't check doc code (yet). Will fix.

**Review by mockersf — APPROVED** [review]

**Pull request closed without merging**
