### PR TITLE
[Merged by Bors] - Lighter no default features

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Even though it's marked as optional, it is no longer possible to not depend on `bevy_render` as it's a dependency of `bevy_scene`

## Solution

- Make `bevy_scene` optional
- For the minimalist among us, also make `bevy_asset` optional

### CODE REVIEW

**Comment by Nilirad** [comment]
What part of bevy_render is needed by bevy_scene? Wouldn't it be better to outsource the those parts in a more neutral crate such that bevy_scene depends on that instead of bevy_render?

**Comment by mockersf** [comment]
It's used for the visibility components. They could be pulled into their own crate like `Transform` was pulled into `bevy_transform`, but that's a bigger refactor.

For my use case I mostly want a very light default-featureless Bevy, so it makes sense to have `bevy_scene` as optional anyway.

**Comment by Nilirad** [comment]
We may consider having a `bevy_spatial` crate or something in the future, encompassing both transform and visibility.

I agree though that as a hot fix this should be merged to avoid pulling in `bevy_render` in a minimal build.

**Review by Nilirad — APPROVED** [review]

**Review by devil-ira — APPROVED** [review]

**Comment by Nilirad** [comment]
This introduces a breaking change.

## Migration guide

Assets and scenes are now behind a feature flag. So this migration is only needed if you are depending to the `bevy` crate with `default-features = false` in `Cargo.toml` and you are using assets or scenes. You will have to add the feature `bevy_asset` or `bevy_scene` to your `bevy` dependency (and also the dev-dependency if you have it).

**Pull request closed without merging**
