### PR TITLE
Update MSRV desc in README.md

### PR DESCRIPTION
**Pull request by lewiszlw**
# Objective

- Update MSRV desc in README.md

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by hymm** [comment]
Is this just being bumped so we're on latest or is there some new feature that someone wants to use?

**Comment by lewiszlw** [comment]
> Is this just being bumped so we're on latest or is there some new feature that someone wants to use?

Just keep MSRV latest as README said.

**Comment by mockersf** [comment]
The README says latest as a simplification, but the idea was to bump it when needed, not preemptively

**Review by james7132 — APPROVED** [review]

**Comment by cart** [comment]
> The README says latest as a simplification to avoid being out of date, but the idea was to bump it when needed, not preemptively.
> While everything will run/compile better on latest, this would break support for people on 1.67 or 1.68 without a good reason.

I agree with this. I don't see much of a reason to bump unless we have to. Maybe we should soften the language to

> As a result, the Minimum Supported Rust Version (MSRV) is generally close to "the latest stable release" of Rust.

**Comment by lewiszlw** [comment]
Understand, Updated README.md.

**Review by alice-i-cecile — APPROVED** [review]

**Review by hymm — APPROVED** [review]

**Pull request merged**
