### PR TITLE
Make get_short_name return Cow instead of String

### LINKED ISSUE #9496: `get_short_name` should return a `Cow` most likely
## What problem does this solve or what need does it fill?

`bevy_utils::get_short_name` returns a `String`. This results in unconditional allocation, even if the short name can be expressed as a slice of the full name. 

## What solution would you like?

Returning a `Cow` (similarly to how [`from_utf8_lossy`](https://doc.rust-lang.org/stable/std/string/struct.String.html#method.from_utf8_lossy) works) would reduce allocation.

## What alternative(s) have you considered?

Sometimes, `get_short_name` is used for debug/display purposes. We could also provide a wrapper type that specifically implements `Display` for `&str` with the `get_short_name` heuristic to remove all type prefixes.

## Additional context

I saw a "hand made" version of `get_short_name` in a `fmt::Debug` impl in asset_v2

### PR DESCRIPTION
**Pull request by nicopap**
# Objective

- Do not make allocation in `get_short_name` when not necessary. The `get_short_name` of a path without generics is strictly a subslice of the path itself, so we don't need to create a new buffer for it.
- Improve drastically parsing performance by working on ASCII (this allows skipping UTF8 checks (linear with string size) on every slice splits) It is still fully UTF8-complient, for the same reasons as #9371 
- Fixes #9496 

## Solution

- Rework `get_short_name` to work on `&[u8]` instead of `&str`, only returns an owned `String` when the path contains a special character.
- Added `DisplayShortName`. It stores any kind of string, but when displayed, it displays the `get_short_name` version.

## Future work

I think we could realistically replace the `GenericTypePathCell` with a streaming version of `get_short_name` that implements `Hash`, `Eq` etc. similarly to `DisplayShortName`. It would add the parsing cost on top of hashing/equality check, but now that the parser is a lot faster, it's questionable whether the cost is actually significant.

We could also replace the `CowStr` in the scheduling error type with `DisplayShortName`, to lazily parse the type path only when displaying it.

---

## Changelog

- `get_short_name` returns a `Cow<str>` instead of `String`, avoiding allocation when not strictly necessary. It is also significantly more performant
- Added `DisplayShortName`. It stores any kind of string, but when displayed, it displays the `get_short_name` version.

## Migration Guide

- `get_short_name` returns a `Cow<str>` instead of `String`, add `.to_string()` to the return value to get a `String`. However, we recommend that if you can, you store the `Cow` over the `String` to avoid allocations.

### CODE REVIEW

**Comment by nicopap** [comment]
On the performance-side of things. I'll assume it's more perfs because:
1. It's the same optimization as #9371, and it has been proven to be a 20% speedup on benchmarks
2. In the simple case, we completely skip allocation
3. We pre-allocate to a size known to be able to hold the return value. For a 33 chars string, that saves us 2 reallocations, for 65 chars: 3 etc.
4. We might elide bound checks (though they were probably mitigated by the optimizer already) by storing the `&[u8]` instead of storing an offset and getting the sub-slice.

**Comment by alice-i-cecile** [comment]
I like this change, and agree that it should improve performance without seriously hurting complexity. Can you add a test for a non-ASCII type name to verify that it works correctly (and continues to in the future)?

**Review by alice-i-cecile — APPROVED** [review]

**Comment by nicopap** [comment]
There is also the uppercase fix (#9587), which I'm not exactly sure how to integrate in this change.

**Comment by alice-i-cecile** [comment]
@nicopap want me to toss Adopt-Me on this?

**Comment by nicopap** [comment]
Sure. Should be easy to pick up.

**Comment by james7132** [comment]
Closing in favor of #12275.

**Pull request closed without merging**
