### PR TITLE
Fix missed `RenderDevice::configure_surface` call on window size change

### PR DESCRIPTION
**Pull request by HackerFoo**
# Objective

On iOS devices, the old code would sometimes miss changes and not call `RenderDevice::configure_surface` appropriately, leaving the screen at the wrong size when rotating.

## Solution

Change the `ExtractedWindow::size_changed` field to a `size_change_pending` flag that is only cleared after calling `configure_surface`.

## Changelog

Fixed: Windows may not be configured on size changes.

### CODE REVIEW

**Review by IceSentry — APPROVED** [review]
I tested it on my windows machine and resizing still worked as expected. I don't have any ios device so can't test that part unfortunately

**Comment by alice-i-cecile** [comment]
@HackerFoo this needs to be rebased following windows-as-entities.

**Comment by NthTensor** [comment]
Can anyone still reproduce this? It's quite old.

**Comment by richchurcher** [comment]
Backlog cleanup: closing due to inactivity. Probably best to wait for a further bug report if this is still an issue 2 years down the track.

**Pull request closed without merging**
