### PR TITLE
[Merged by Bors] - Make ktx2 and zstd default features

### PR DESCRIPTION
**Pull request by JMS55**
# Objective
- Environment maps use these formats, and in the future rendering LUTs will need textures loaded by default in the engine

## Solution

- Make ktx2 and zstd part of the default feature
- Let examples assume these features are enabled

---

## Changelog
- `ktx2` and `zstd` are now part of bevy's default enabled features

## Migration Guide

- If you used the `ktx2` or `zstd` features, you no longer need to explicitly enable them, as they are now part of bevy's default enabled features

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
@JMS55 should this be in the release milestone?

**Comment by JMS55** [comment]
Probably. I'll add both this and the tonemapping PR to the milestone. Unsure why the CI is failing for this, though...

**Comment by mockersf** [comment]
There is a test checking that all declared supported extensions are supported by the Image crate... which isn't the case for ktx2. I would be OK with that test being removed, it doesn't have enough value to start adding special cases to it...

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Pull request closed without merging**
