### PR TITLE
[Merged by Bors] - fix upsert_leaf not setting a MeasureFunc for new leaf nodes

### PR DESCRIPTION
**Pull request by ickshonpe**
# Problem

The `upsert_leaf` method creates a new `MeasureFunc` and, if required, a new leaf node, but then it only adds the new `MeasureFunc` to existing leaf nodes.

## Solution

Add the `MeasureFunc` to new leaf nodes as well.

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
This LGTM, but I agree that we should be able to do this more concisely.

**Comment by ickshonpe** [comment]
> Oops, this seems like a regression from #6743.

ah, I should have checked the history.

> I think this could be a one line diff with `new_leaf_with_measure`?

I think this version is probably better, even though it's more verbose. 
In the original, the two code paths confound the unused_variable lint.

**Comment by rparrett** [comment]
Hm. At a glance, `new_leaf_with_measure` seems to do less work than `new_leaf` + `set_measure`.

**Comment by rparrett** [comment]
> In the original, the two code paths confound the unused_variable lint.

I'm not seeing this on my end. CI runs without error locally with the minimal changeset.

**Review by alice-i-cecile — APPROVED** [review]

**Review by rparrett — APPROVED** [review]

**Comment by ickshonpe** [comment]
> > In the original, the two code paths confound the unused_variable lint.
> 
> I'm not seeing this on my end. CI runs without error locally with the minimal fix.

I meant that in the concise version, the linter didn't detect that the MeasureFunc variable was unused because it was still consumed on the other code path. The longer version is more robust in that we'd get an unused variable warning in that case. I agree that isn't clear if there is some performance cost though so I don't know. It's probably not worth worrying about, so I put things back as they were.

**Comment by rparrett** [comment]
Makes sense, agreed.

**Pull request closed without merging**
