### PR TITLE
Allow fog density texture to be scrolled over time with an offset

### PR DESCRIPTION
**Pull request by jirisvd**
# Objective

- The goal of this PR is to make it possible to move the density texture of a `FogVolume` over time in order to create dynamic effects like fog moving in the wind.
- You could theoretically move the `FogVolume` itself, but this is not ideal, because the `FogVolume` AABB would eventually leave the area. If you want an area to remain foggy while also creating the impression that the fog is moving in the wind, a scrolling density texture is a better solution.

## Solution

- The PR adds a `density_texture_offset` field to the `FogVolume` component. This offset is in the UVW coordinates of the density texture, meaning that a value of `(0.5, 0.0, 0.0)` moves the 3d texture by half along the x-axis.
- Values above 1.0 are wrapped, a 1.5 offset is the same as a 0.5 offset. This makes it so that the density texture wraps around on the other side, meaning that a repeating 3d noise texture can seamlessly scroll forever. It also makes it easy to move the density texture over time by simply increasing the offset every frame.

## Testing

- A `scrolling_fog` example has been added to demonstrate the feature. It uses the offset to scroll a repeating 3d noise density texture to create the impression of fog moving in the wind.
-  The camera is looking at a pillar with the sun peaking behind it. This highlights the effect the changing density has on the volumetric lighting interactions.
- Temporal anti-aliasing combined with the `jitter` option of `VolumetricFogSettings` is used to improve the quality of the effect.

---

## Showcase

https://github.com/user-attachments/assets/3aa50ebd-771c-4c99-ab5d-255c0c3be1a8

### CODE REVIEW

**Review by IceSentry — COMMENTED** [review]
So, the implementation looks fine to me, but why not just move the transform of the FogVolume entity? Is there a benefit to doing it like this compared to just moving the volume itself?

**Comment by jirisvd** [comment]
> So, the implementation looks fine to me, but why not just move the transform of the FogVolume entity? Is there a benefit to doing it like this compared to just moving the volume itself?

The motivation is that you might want an area of a level to be foggy, let's say a forest. If the transform of the fog was the thing that's being moved, then the FogVolume would eventually leave the forest.

I guess the best thing you could do is move the FogVolume back and forth with some kind of smoothing so that it never actually leaves the forest while still producing movement of the density texture. But if you want the wind to be consistently blowing the fog in a certain direction, then that's not possible.

Another thing you might want to have is a smaller localized bit of smoke, like a smoke grenade. In an FPS game you probably want the smoke to remain in place, but you still might want to produce the impression of movement by scrolling the density texture.

**Comment by jirisvd** [comment]
Generally speaking there are infinite possible things a tech artist might want to do with volumetric fog. An artist might for example want to have a hot spring with foggy vapors above it that consistently move upwards and dissipate while the actual fog volume remains in place.

I see the density texture offset as one small piece of the puzzle. Ideally, there would be a more customizable solution, like a node graph or some kind of a way to write a custom density function ([this has been recently discussed](https://discord.com/channels/691052431525675048/743663924229963868/1262331153814130709) on Discord). But this is probably a long way off, so until then, adding some basic properties like an offset can help.

**Comment by alice-i-cecile** [comment]
Thanks for the really nice explanation of why this is useful!

**Review by IceSentry — APPROVED** [review]
Cool, thank you, that all makes sense to me.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Thank you to everyone involved with the authoring or reviewing of this PR! This work is relatively important and needs release notes! Head over to https://github.com/bevyengine/bevy-website/issues/1677 if you'd like to help out.

**Pull request merged**
