### PR TITLE
[Merged by Bors] - Resolve most remaining execution-order ambiguities

### PR DESCRIPTION
**Pull request by JoJoJet**
# Objective

Bevy's internal plugins have lots of execution-order ambiguities, which makes the ambiguity detection tool very noisy for our users.

## Solution

Silence every last ambiguity that can currently be resolved.
Each time an ambiguity is silenced, it is accompanied by a comment describing why it is correct. This description should be based on the public API of the respective systems. Thus, I have added documentation to some systems describing how they use some resources.

# Future work

Some ambiguities remain, due to issues out of scope for this PR. 

* The ambiguity checker does not respect `Without<>` filters, leading to false positives.
* Ambiguities between `bevy_ui` and `bevy_animation` cannot be resolved, since neither crate knows that the other exists. We will need a general solution to this problem.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by hymm — APPROVED** [review]
Needing to suppress `Assets<Image>` so many times makes me worried about how ambiguity detection will work at a larger scale. Hopefully won't be too bad as most games won't need to get  mutable access to Assets too much. Either way not the concern of this PR.

**Comment by JoJoJet** [comment]
> Needing to suppress `Assets<Image>` so many times makes me worried about how ambiguity detection will work at a larger scale.

In the future, maybe we could have a `SystemParam` that only allows inserting new assets

**Comment by JoJoJet** [comment]
Misclick, my bad.

**Comment by alice-i-cecile** [comment]
Yeah the problem with Assets is that we need to have a pattern for "order independent writes".

**Pull request closed without merging**
