### PR TITLE
`Local` with required config as a const generic parameter

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- Alternative to #2440, but with a const generic parameter on `Local` instead of a new type

## Solution

Either:
- parameter should use the default value or a `FromWorld` impl, use `Local<T, true>`
- parameter must be configured using `config`, use `Local<T, false>`

If the parameter is `false`, the bound for T on `FromWorld` is lifted.

```rust
#[derive(Default)]
struct DefaultableStruct(u32);

struct NotDefaultableStruct(u32);

fn my_system(a: Local<DefaultableStruct, true>, b: Local<NotDefaultableStruct, false>) {}
```

Ideally, I would want the `Local` type to be:

```rust
enum LocalType {
    FromWorld,
    NeedConfig
}

pub struct Local<'a, T: Component, const LOCAL_TYPE: LocalType = LocalType::FromWorld>(&'a mut T);
```

Then my system would be:

```rust
fn my_system(a: Local<DefaultableStruct>, b: Local<NotDefaultableStruct, LocalType::NeedConfig>) {}
```

But this is not possible in Rust for now 😞 :
* we can't have our own type as a const generic: https://blog.rust-lang.org/2021/02/26/const-generics-mvp-beta.html#const-generics-for-custom-types
* we can't have a default value for const generics: https://blog.rust-lang.org/2021/02/26/const-generics-mvp-beta.html#const-generics-and-default-arguments

Those are the two top issues in "what's next", so hopefully they should come soonish...

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I prefer this solution in general, but would *like* to hold off for a prettier version. I suppose the churn isn't too bad; this is not a particularly prominent feature and the refactor would be easy.

**Comment by mockersf** [comment]
once we can use an enum, we could have more control on how it's initialized:
```rust
enum LocalType {
    FromWorld,
    FromDefault, // now separate from FromWorld
    NeedConfig
}
```

**Comment by cart** [comment]
Ooh this is a clever take / a pattern that wasn't on my radar. I'd also prefer to hold off until const generic defaults are an option (and ideally, enums).

**Comment by mockersf** [comment]
it seems feature `const_generics_defaults` is on a good way to stabilisation 🎉

**Comment by TheRawMeatball** [comment]
We could already use something like this design, if we substitute a module with 2 unit structs instead of an enum:
```rust
mod local_mode {
    struct FromWorld;
    struct NeedsConfig;
}
```

**Comment by NathanSWard** [comment]
> it seems feature const_generics_defaults is on a good way to stabilisation 🎉

Just upgrade the compiler we use to nightly and all our problems are solved :wink:

**Comment by DJMcNab** [comment]
As of https://github.com/bevyengine/bevy/pull/3633, this no longer makes sense.

**Pull request closed without merging**
