### PR TITLE
Use `Isometry` in `bevy_gizmos` wherever we can

### LINKED ISSUE #14319: Tracking issue: Isometry follow-ups
#14269 introduced isometry types to bevy_math. There are some places where it makes sense to integrate these that should probably be addressed in some fashion; the purpose of this issue is to track these.
- [x] Conversion methods relating `Transform`/`GlobalTransform` and `Isometry3d`. (#14478)
- [x] `Bounded2d`/`Bounded3d` could use isometry types in addition to raw translations/rotations. (#14485)
- [ ] Gizmos could use isometries to position figures in place of raw translation/rotations (requires investigation and some finesse to deal with 2d gizmos as well). (#14676)

These are all relatively similar in flavor, so it would be good if they blended harmoniously together (e.g. making it relatively easy to extract an `Isometry3d` from a `Transform` to position a sphere gizmo, for example).

### PR DESCRIPTION
**Pull request by RobWalt**
# Objective

- Solves the last bullet in and closes #14319
- Make better use of the `Isometry` types
- Prevent issues like #14655
- Probably simplify and clean up a lot of code through the use of Gizmos as well (i.e. the 3D gizmos for cylinders circles & lines don't connect well, probably due to wrong rotations)

## Solution

- go through the `bevy_gizmos` crate and give all methods a slight workover

## Testing

- For all the changed examples I run `git switch main && cargo rr --example <X> && git switch <BRANCH> && cargo rr --example <X>` and compare the visual results
- Check if all doc tests are still compiling
- Check the docs in general and update them !!! 

---

## Migration Guide

The gizmos methods function signature changes as follows:

- 2D
  - if it took `position` & `rotation_angle` before -> `Isometry2d::new(position, Rot2::radians(rotation_angle))`
  - if it just took `position` before -> `Isometry2d::from_translation(position)`
- 3D
  - if it took `position` & `rotation` before -> `Isometry3d::new(position, rotation)`
  - if it just took `position` before -> `Isometry3d::from_translation(position)`

### CODE REVIEW

**Comment by RobWalt** [comment]
Here are just some screenshots. This PR also fixes the capsule and cylinder primitive rendering which was broken in the mean time somehow. (The circles connecting points with the orthogonal lines aren't exact)

Before:

image

image

After:

image

image

---

Funnily enough I also didn't change any parameters and I don't know why it looks so "simple" in the before-version 🤔

**Review by alice-i-cecile — APPROVED** [review]

**Review by NiseVoid — APPROVED** [review]
Haven't reviewed everything in detail, but the changes overall look fine to me. The changes from a direction to the weird `Isometry::from_rotation(Quat::from_rotation_arc())` seems a but ugly, but I don't think we have a nicer solution for that currently.

**Comment by janhohenheim** [comment]
Wouldn't it be nicer to accept `impl Into<Isometry3d>` everywhere instead of `Isometry3d`?

**Comment by alice-i-cecile** [comment]
> Wouldn't it be nicer to accept `impl Into<Isometry3d>` everywhere instead of `Isometry3d`? That would make this API a bit more robust regarding future usability additions.

Possibly, but isometry is a really useful type, and that will increase complexity and compile times here.

**Comment by janhohenheim** [comment]
@alice-i-cecile given that Bevy uses `Transform` nearly everywhere, I'd argue that accepting an `impl` would *decrease* complexity for users, as they don't need to care about the mathematical concepts at play here and can have it "just work". I agree that `Isometry` is cool, but I don't think most users will care about the difference between it and `Transform`.
Since setting up gizmos is not an operation that happens in many places, I'd be surprised if accepting an `impl` had any measurable effect on compile times for an average plugin.
This is not a strong opinion, feel free to disregard if you disagree.

**Comment by alice-i-cecile** [comment]
Yeah I don't feel super strongly either, but I'd like to merge this as is and then refine later.

**Comment by janhohenheim** [comment]
@alice-i-cecile that's fair :)

**Pull request merged**
