### PR TITLE
Fix gizmos regression

### LINKED ISSUE #14142: Regression: gizmos panicking given bad output from `GlobalTransform::to_scale_rotation_translation`
## Bevy version

0.14

## What you did

Draw a big circle

## What went wrong

Bevy panicked.

```
Error: The vector given to `Dir3::new_unchecked` is not normalized. The length is 0.25.
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: bevy_math::direction::assert_is_normalized
   3: bevy_math::direction::Dir3::new_unchecked
   4: <bevy_gizmos::circles::SphereBuilder<Config,Clear> as core::ops::drop::Drop>::drop::{{closure}}
```

## Additional information

This is a regression not present in 0.13.

### PR DESCRIPTION
**Pull request by Lubba-64**
# Objective

- Fixes #14142

## Solution

- Make sure a regression test is written on this case that fails for the current code base but works with the suggested patch linked in the aforementioned issue. After this is confirmed to be working, apply the patch.

## Testing

- Run the regression test in both contexts, outputs were as expected.

### CODE REVIEW

**Comment by Lubba-64** [comment]
Feel free to nit this, wondering how the example based tests are set to run in CI...

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
So, these tests will get run when we attempt to merge, but I think that in this particular case we can use a standard unit test (without any rendering) to check for regressions. IMO just stick it in the `circles.rs` file.

That will be more straightforward, be run as part of our ordinary CI / local calls to `cargo test` and use less compute.

**Comment by Lubba-64** [comment]
> So, these tests will get run when we attempt to merge, but I think that in this particular case we can use a standard unit test (without any rendering) to check for regressions. IMO just stick it in the `circles.rs` file.
> 
> That will be more straightforward, be run as part of our ordinary CI / local calls to `cargo test` and use less compute.

Can gizmos be run headless? I tried to do this and could not get it to stop complaining about not having the shader asset present (i am probably missing something simple, i tried to look for other examples in the other unit tests and the best i found were those end to end tests

**Comment by alice-i-cecile** [comment]
I don't think we actually need to generate any gizmos to test this. Can we not just call `gizmos.sphere` without actually running the system?

I'd prefer to get this merged without a regression test over adding an integration test TBH.

**Comment by Lubba-64** [comment]
I just checked to see if I could run it headlessly and it appears as if spawning a gizmos struct requires access to create a ` Deferred<'s, GizmoBuffer<Config, Clear>>`, which seems can only be created through ECS means. This is not unexpected, but means that I will sadly have to remove the test or refactor a lot of code I am not yet qualified to touch.

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
