### PR TITLE
add `RunMode::Ticks` to use in test cases

### PR DESCRIPTION
**Pull request by JeanMertz**
As discussed on Discord, this adds a new `RunMode` that can be used in (but is not limited to) tests.

This allows one to run the loop `x` ticks, before validating the result. Technically, this makes `RunOnce` obsolete, but I left it in to not break any existing code, and to have a slightly nicer API when you only want to run the loop once.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I discussed this on Discord, and think this is valuable simple functionality to make unit testing ECS functionality more ergonomic. 

Incidentally, I wanted this for #68 tests anyways, so this would be nice to merge ASAP @cart.

**Comment by alice-i-cecile** [comment]
Another thought: it would actually be very useful to expose which iteration we're on as a Resource to make tests clearer and shorter. You can always just make one and then iterate it every pass, but it's a common enough pattern when using this RunMode that it feels like it should be baked in.

**Comment by JeanMertz** [comment]
> Another thought: it would actually be very useful to expose which iteration we're on as a Resource to make tests clearer and shorter.

@alice-i-cecile I added something that does what you mention. I'm unfamiliar with the project structure of Bevy, so I expect you want me to move some code around (or perhaps you had a completely different idea in mind), but at least the example validates that this works as expected.

**Comment by cart** [comment]
I'm a little hesitant to hard code this. "exit criteria" will likely be different across unit tests (and normal apps), so imo it makes sense to just add a system that sends the AppExit event at the appropriate time. This system isn't particularly complicated and could be reused across tests:

```rust
fn exit_on_tick(mut app_exit: ResMut<Events<AppExit>>, mut tick_counter: ResMut<i32>) {
    *tick_counter += 1;
    if *tick_counter == 10 {
        app_exit.send(AppExit);
    }
}
```

Some examples of actual unit tests that will use this might help sway me.

**Comment by cart** [comment]
I'm closing this, but feel free to continue discussing here and we can re-open if opposing viewpoints are expressed.

**Pull request closed without merging**
