### PR TITLE
Gate bevy_utils web-time re-export

### PR DESCRIPTION
**Pull request by AxiomaticSemantics**
# Objective

Reduce non-required dependencies

# Solution
Gate bevy_utils re-export of web-time behind wasm32 target and re-export from `std::time` on non wasm target

### CODE REVIEW

**Review by james7132 — APPROVED** [review]

**Comment by AxiomaticSemantics** [comment]
I'll probably move these cfg checks a line away from the rest, I don't like how it formatted that.

**Comment by rparrett** [comment]
Isn't "handling this for us" part of the point of `web-time`?

https://github.com/daxpedda/web-time/blob/main/src/lib.rs#L128

**Comment by mockersf** [comment]
Yup, the goal of `web-time` is to not need to do this. On native, it will just be a std re-export.

This should not change much the dependency tree or the compile time, not sure getting the complexity on Bevy side is worth it.

**Comment by AxiomaticSemantics** [comment]
> Yup, the goal of `web-time` is to not need to do this. On native, it will just be a std re-export.
> 
> This should not change much the dependency tree or the compile time, not sure getting the complexity on Bevy side is worth it.

I'm willing to close this as it's a lesser battle and I'll concentrate my efforts towards granular features in bevy_internal which is where most of the gains will be realized for those doing headless apps etc.

**Pull request closed without merging**
