### PR TITLE
[Merged by Bors] - Update concurrent-queue to 2.0

### PR DESCRIPTION
**Pull request by devil-ira**

### CODE REVIEW

**Comment by devil-ira** [comment]
I misinterpreted the other skip entries as I was thinking about it :V

This PR now updates our dependency on concurrent-queue to 2.0.

**Comment by yodaldevoid** [comment]
`async-channel` version 1.8.0 has been published using `concurrent-queue` 2.0.

**Comment by james7132** [comment]
The `async_task` version was specifically pinned in #6509, as we're reliant on one of the APIs exposed on it.

**Comment by mockersf** [comment]
@devil-ira could you read `async-task`? This should be good to merge after

**Review by mockersf — APPROVED** [review]

**Pull request closed without merging**
