### PR TITLE
Add `Annulus`-gizmos

### PR DESCRIPTION
**Pull request by solis-lumine-vorago**
# Objective

- Add support for drawing `Annulus`-gizmos using `gizmos.primitive_2d(...)`

## Changelog

- Updated the example `math/render_primitives`

### CODE REVIEW

**Review by Jondolf — APPROVED** [review]
Looks good, thanks!

I think it'd be good to make this return a builder similar to e.g. [`EllipseBuilder`](https://github.com/bevyengine/bevy/blob/3ec06c8d3362502aa7b3d5a03971c3e4bbbc26c3/crates/bevy_gizmos/src/circles.rs#L184), since that'd allow you to configure the resolution of the inner and outer circles. But I noticed that it's also missing for the primitive versions of the circle and ellipse gizmos, so I think it's fine to leave this to a follow-up.

**Review by pablo-lua — APPROVED** [review]

**Comment by solis-lumine-vorago** [comment]
> so I think it's fine to leave this to a follow-up.

I noticed that aswell, I think I will do that on monday

**Review by matiqo15 — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
let's merge this as it's ready, a followup PR with the builder will be very welcomed 🙂

**Comment by alice-i-cecile** [comment]
Thank you to everyone involved with the authoring or reviewing of this PR! This work is relatively important and needs release notes! Head over to https://github.com/bevyengine/bevy-website/issues/1311 if you'd like to help out.

**Pull request merged**
