### PR TITLE
Remove monkey.gltf

### LINKED ISSUE #9967: Bevy is in breach of the `monkey.gltf` license
Since #271, the bevy repo contains `Monkey.glb`, now `Monkey.gltf`, which is GPL3.0 licensed.

`Monkey.gltf` is the Blender Suzanne, always has been licensed under the GPL3.0

[The wikimedia page for Suzanne says this](https://commons.wikimedia.org/wiki/File:Suzanne.stl):

> Since this model is shipped as part of Blender, by extracting it we created very small subset of Blender (so to say a changed version of Blender) which we are free to distribute according to their own license statements

Of course, the author of that page is probably not a lawyer, but neither am I.

GPL3.0 requires crediting & sharing alike, or at least noticing users of their rights, none of which we've been doing since #271, three years ago.

## Solution

- Remove [Monkey.gltf](https://github.com/bevyengine/bevy/tree/main/assets/models/monkey) from the repository.
- Be very sorry.

### PR DESCRIPTION
**Pull request by OneFourth**
# Objective

- Fixes #9967

## Solution

- Remove `monkey.gltf`
- Added `torus.gltf`, which is two torus meshes joined together, to replace `monkey.gltf` in the examples

## Examples

I made `torus.gltf` mainly so that the multiple_windows example clearly shows the different camera angles

### asset_loading
image

### hot_asset_reloading
image

### multiple_windows:
image
image

### CODE REVIEW

**Review by IceSentry — APPROVED** [review]

**Review by hymm — APPROVED** [review]
We should probably find a better replacement in the future, but we should do this asap.

**Review by james7132 — APPROVED** [review]

**Comment by Lemonzyy** [comment]
> We should probably find a better replacement in the future, but we should do this asap.

I'm not sure the licence allows it but maybe we could add https://github.com/RayMarch/ferris3d

**Comment by Talon1024** [comment]
https://github.com/RayMarch/ferris3d/tree/main#license

**Comment by rlidwka** [comment]
> We should probably find a better replacement in the future.

https://en.wikipedia.org/wiki/List_of_common_3D_test_models

Newell's teapot is a very popular choice for this purpose.

**Pull request merged**
