### PR TITLE
[Merged by Bors] - Remove with bundle filter

### LINKED ISSUE #2620: Anti-feature request: remove `WithBundle`
## What problem does this solve or what need does it fill?

`WithBundle` promotes unidiomatic OOP-style code in Bevy that is hard to extend and maintain. It also doesn't behave the way many users would hope it does: it will detect any entities with the set of components within the bundle, rather than only entities spawned with the bundle.

It is also particularly odd to have the ability to filter on bundles but not request them (#2252), causing user confusion.

## What solution would you like?

Remove `WithBundle`. Existing users can use combined `With` filters (ideally with marker components), or even write their own query filter types if they desperately need this.

## What alternative(s) have you considered?

Complain about its usage in code reviews and discourage (or ignore it) in the docs.

## Additional context

We should attempt to remove this sooner rather than later to reduce the pain. If and when bundles are properly stored on the entity (perhaps for editor purposes?), we can consider adding this and #2252.

### PR DESCRIPTION
**Pull request by Hoidigan**
# Objective

Fixes #2620

## Solution

Remove WithBundle filter and temporarily remove example for query_bundle.

### CODE REVIEW

**Review by mockersf — CHANGES_REQUESTED** [review]
the example should be removed completely rather than commented out

**Comment by Hoidigan** [comment]
It's not very happy I deleted the example :(
Is there something you have to do to get it to delete it beyond just deleting the file?

**Comment by mockersf** [comment]
You also need to remove it:
https://github.com/bevyengine/bevy/blob/90586a4c461cde86b8a0e08f0770894e7cf30862/Cargo.toml#L321-L323

https://github.com/bevyengine/bevy/blob/90586a4c461cde86b8a0e08f0770894e7cf30862/examples/README.md#L165

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
unrelated ci failure

**Comment by Hoidigan** [comment]
So is there anything I need to do for this? I'm still kinda confused as to what I do at this point, if anything.

**Comment by mockersf** [comment]
nothing to do for now, you can wait for reviews/comments 🙂

**Review by NiklasEi — CHANGES_REQUESTED** [review]
The filter is mentioned in a doc comment l. 15 `bevy_ecs/src/bundle.rs`. Please remove that mention too.

**Comment by cart** [comment]
Looks good to me!

**Pull request closed without merging**
