### PR TITLE
[Merged by Bors] - CI - Check that examples are listed in README and Cargo

### LINKED ISSUE #1581: Add CI that checks whether new Examples are in readme
## What problem does this solve or what need does it fill?

Many Contributors don't realize that all examples are documented in the [README.md](https://github.com/bevyengine/bevy/blob/main/examples/README.md) inside the examples folder.
Because of this sometimes PR's are merged that forgot this, like #562 where a separate Example was a last-minute change.

## What solution would you like?

Add a CI task, that checks whether all examples are in the readme.

## What alternative(s) have you considered?

Do not automatically check for this and risk missing this Problem.

### PR DESCRIPTION
**Pull request by Weibye**
Closes #1581 

# Internal File/Link Consistency checker Action

This pull request adds an action to the CI that parses the [`./examples`](https://github.com/bevyengine/bevy/tree/main/examples) folder for files and cross references that with the links listed in [`README.md`](https://github.com/bevyengine/bevy/blob/main/examples/README.md) and [`Cargo.toml`](https://github.com/bevyengine/bevy/blob/main/Cargo.toml) to ensure the documentation actually reflects the examples currently in the repo. 

The primary reason for why we want this, is to prevent people from adding new examples but forgetting to also list them in the docs, or accidentally entering broken links (typos in docs).

For details on how the action is working: [Check out the README here](https://github.com/Weibye/action-internal-link-consistency/blob/main/README.md)

### CODE REVIEW

**Comment by Weibye** [comment]
@alice-i-cecile @mockersf @MinerSebas 
Continuing conversation from #1650 over here: 

This is a screenshot of the action currently in use on this pull request: https://github.com/bevyengine/bevy/pull/1650/checks?check_run_id=2209782326

I am mostly happy with the results but I'm currently trying to improve the clarity and directness of the output so that users immediately know what corrections need to take place. 

image

In this case the action has picked up 3 issues, which on closer inspection is really 2 distinct problems: 
1. `./examples/3d/pbr.rs` is currently missing from README and must be added
2. `./examples/3d/pbr_textures.rs` is missing from both README and Cargo and should be added to both targets.
3. `./examples/3d/[pbr].rs` is found in README, but there has not been found an accompanying file on disk. 

Now, 1 and 3 is the same issue: There is a typo in the README (brackets should not be there). 

Do you all have any insight into how I can improve the outputs given? Since this is potentially going to affect quite a few people, I want this to be as helpful and direct as possible and not cause unnecessary friction.

**Comment by Weibye** [comment]
Think I really messed up my git rebasing, will try to fix

**Comment by Weibye** [comment]
I'll nuke this one and create a fresh pull request once I'm confident the action does not pick up false-positives

**Comment by cart** [comment]
Just fixed the git history by squashing the commits, rebasing on main, and force pushing.

**Comment by Weibye** [comment]
Sorry for the delay everyone, this is almost complete. Will aim to have the pull request finished by the end of the day today.

**Comment by Weibye** [comment]
I had the action working properly, then #1714 came along and I realized I needed to support examples that does not lie within the examples folder.

**Comment by Weibye** [comment]
I think this is ready now and should be ready to go as #2263 gets merged.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
bors try

so it should fail now right?

**Comment by mockersf** [comment]
It works, it fails! https://github.com/bevyengine/bevy/runs/2697857713

Could you add it to bors? https://github.com/bevyengine/bevy/blob/main/.github/bors.toml

**Comment by MinerSebas** [comment]
Shouldn't this also currently Fail on the Tests category, as it isn't stored in the examples Folder? (See the `../`)
```md
## Tests

Example | File | Description
--- | --- | ---
`how_to_test_systems` | [`../tests/how_to_test_systems.rs`](../tests/how_to_test_systems.rs) | How to test systems with commands, queries or resources
```

But the CI config only sets this: `source: './examples/'`

**Comment by Weibye** [comment]
> Shouldn't this also currently Fail on the Tests category, as it isn't stored in the examples Folder? (See the `../`)
> 
> ```lisp
> ## Tests
> 
> Example | File | Description
> --- | --- | ---
> `how_to_test_systems` | [`../tests/how_to_test_systems.rs`](../tests/how_to_test_systems.rs) | How to test systems with commands, queries or resources
> ```
> 
> But the CI config only sets this: `source: './examples/'`

Hmm. Yes you are right. I'll fix this in the morning.

What is the desired approach here? Should we force test examples inside the examples folder? Or are test examples another thing that should be ignored?

**Comment by Weibye** [comment]
@mockersf Are there any specific reason why the examples on how to test systems (#1714) should live in the Test folder instead of the Examples folder?

**Comment by Weibye** [comment]
- The action should now work and _correctly_ fail on account of Test examples are not located within the scope of `examples/`
- iter_combinations should no longer be picked up as #2263 has been merged
- I also improved the output messages a bit to hopefully add some clarity

**Comment by alice-i-cecile** [comment]
bors try

**Comment by Weibye** [comment]
> Build failed:
> example-doc-validation

Should anyone have a suggestion for a better / clearer name, I'm all ears

**Comment by mockersf** [comment]
> @mockersf Are there any specific reason why the examples on how to test systems (#1714) should live in the Test folder instead of the Examples folder?

To be executed when running `cargo test`

**Comment by Weibye** [comment]
> > @mockersf Are there any specific reason why the examples on how to test systems (#1714) should live in the Test folder instead of the Examples folder?
> 
> To be executed when running `cargo test`

That makes sense, in which case I propose #2281 in order to unblock this PR

**Comment by mockersf** [comment]
I didn't check how your action works, but if it fails on that it may means it does things backwards: The goal of this PR is to check that examples are in the README.md and Cargo.toml files, not that the examples listed in those files are present in the examples folder.
The fact that those links are valid should already be checked by our link checker in CI

**Comment by Weibye** [comment]
> I didn't check how your action works, but if it fails on that it may means it does things backwards: The goal of this PR is to check that examples are in the README.md, not that the examples listed in this file are present in the examples folder.

Currently it does both.

> The fact that those links are valid should already be checked by our link checker in CI

The link-checker CI didn't exist at the time I started this work, so I reckoned checking for invalid links would be required to properly solve the problem. I'll remove that check from the action as it is redundant now.

This action will then only check that files within `./examples` are present in `./examples/README.md` and `Cargo.toml`, and _not_ the other way around.

**Comment by Weibye** [comment]
bors try

**Comment by Weibye** [comment]
I think this should now be complete and work properly this time. 
- Renamed the action, hopefully to be more clear.
- Re-versioned the action to get rid of the old non-working builds

This action should now run without picking up any issues and be ready to merge.

**Comment by NathanSWard** [comment]
bors try

**Review by NathanSWard — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by cart** [comment]
Great work! I feel so safe now :)

**Comment by DJMcNab** [comment]
@Weibye please respond in #2373 for the relicense to MIT/Apache 2.0. Thanks!

**Comment by Weibye** [comment]
> @Weibye please respond in #2373 for the relicense to MIT/Apache 2.0. Thanks!

Oof, thought I already had. Thanks for the reminder!

**Comment by DJMcNab** [comment]
Yay! Thanks! We missed you in the initial checks for users, but we're doing additional checks and found this PR from that.

**Pull request closed without merging**
