### PR TITLE
[Merged by Bors] - RemoveChildren command

### PR DESCRIPTION
**Pull request by jihiggins**

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
For posterity, this seems like a nice bit of functionality, and the code quality looks high.

However, parent-child designs in Bevy are due for a rewrite in general: see #1278 for some reasons why and #1627 for one of the most promising directions. I'm not sure if this is correct to merge in the meantime as a result.

**Review by alice-i-cecile — APPROVED** [review]
In the interim, I think this should be merged.

**Comment by cart** [comment]
Just resolved conflicts. Seems useful and the impl is safe.

**Comment by mockersf** [comment]
CI failed due to a nightly random ICE, restarting

**Pull request closed without merging**
