### PR TITLE
Automatic system discovery

### PR DESCRIPTION
**Pull request by TheRawMeatball**
After a very small bit of talking [on discord](https://discord.com/channels/691052431525675048/789987800014651412/793817819078721577), I went ahead and made a _very_ janky implementation which I will clean up significantly. I'm opening this PR mostly so there is a better place to discuss the benefits and downsides of the general concept.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I really like the idea of being able to do this: it would be very helpful for visualization, and could have some other engine-internal uses down the line. Could you give a small example of what the API looks like and what it does?

**Comment by TheRawMeatball** [comment]
```rust
use bevy::prelude::*;
fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_plugin(DiscPlugin)
        .run();
}

#[system]
fn discovered_system(mut state: ResMut<DiscoveredState>, time: Res<Time>) {
        println!("Woo, discovered system!");

}

#[derive(DiscoveryPlugin)]
#[root("/mnt/33CA263211FBF90F/bevy/examples/app/plugin.rs")]
struct DiscPlugin;
```

**Comment by TheRawMeatball** [comment]
The plugin example is butchered and contains this bit of code - it'll be moved to its own example soon, though.

**Comment by cart** [comment]
This is definitely a clever implementation, but I'm pretty opposed to it (as a default engine feature) for a number of reasons:

1. Extremely expensive: this requires opening X number of files, parsing them, extracting system info from the parsed results, then doing codegen for the plugin. I would want measured proof that this doesn't significantly affect compile times in projects (both small and large across clean and incremental builds) before considering it at all.
2. Super magical in an "arbitrary codegen across project structure" sort of way. This is way outside the bounds of normal rust coding. I'm shooting for Bevy to be relatively idiomatic / free of magic. Its one of the reasons I try to ignore macros in user-facing apis wherever possible (with reflection being a notable exception to the rule).

I think a similar api could be achieved using something like the [inventory](https://github.com/dtolnay/inventory) or [linkme](https://github.com/dtolnay/linkme) crates, but those have their own issues (they each have platform support issues and inventory breaks down on incremental builds). I was hoping I could use that sort of thing for the `bevy_reflect` crate, but I don't think its viable right now.

I'd rather focus efforts on somehow adding `linkme` support for all relevant platforms (namely WASM), which would then generically solve the type registry problem in a lower-compile-time overhead way.

On the largely orthogonal topic of "editor managed systems", I think it makes sense to do something like this:

```rust

struct DynamicStage { /* impl here */ }

impl Stage for DynamicStage { /* impl here */ }

// DynamicStage reads system configuration from something like Handle<DynamicStageConfig>

app
  .add_system_to_stage(stage::DYNAMIC, something.system())
  // maybe add shorthand for the above like this
  .add_dynamic_system(something.system())
```

The editor could then enumerate the systems added to the DYNAMIC stage and expose a gui to dynamically build an execution strategy.

**Comment by TheRawMeatball** [comment]
The compile time issue is a significant one, but I think I can optimize it through caching. The 2 mentioned crates look nice, but I think they're just as magic-y, if not more (especially inventory). I think "yeah, we add some code" is cleaner than the dark compiler magic used in those crates. 

On the topic of `DynamicStage` I personally feel like its fundementally flawed, as the code needs to run _before_ the editor can manage it.

**Comment by cart** [comment]
> The compile time issue is a significant one, but I think I can optimize it through caching.

Caching inside a macro seems like an easy way to introduce weird build bugs (especially once you take into account that rust-analyzer now executes macros too). Theres just so much added complexity here that makes me really uncomfortable.

> The 2 mentioned crates look nice, but I think they're just as magic-y, if not more (especially inventory). I think "yeah, we add some code" is cleaner than the dark compiler magic used in those crates.

I agree that they are also magical, but its a matter of scoping complexity (and overall compile time complexity). We don't need to add a bunch of file-io / parsing / cache layers with either of those two crates. The approach used is comparatively simple, both from a implementation size perspective and an "interface exposed" perspective. 

> On the topic of DynamicStage I personally feel like its fundementally flawed, as the code needs to run before the editor can manage it.

I'm not sure I follow that. The situation is:

* we have a bunch of systems compiled into a binary
* right now the order of execution is also compiled into the binary
* we want the editor to be able to control the order of execution of systems in the binary
* The editor cannot/should not directly modify the binary itself
* The editor should be able to modify the order of execution at runtime

I think the DynamicStage solution is a great solve to those constraints. Just let "execution strategy" be an asset modifiable at runtime by anything. And let the user decide at compile time what systems are governed by that strategy.

**Comment by TheRawMeatball** [comment]
> Caching inside a macro seems like an easy way to introduce weird build bugs (especially once you take into account that rust-analyzer now executes macros too). Theres just so much added complexity here that makes me really uncomfortable.

This is a valid concern, but the implementation is small and clear enough to be manageble (though the real test of that is coming back a week later). 

On the topic of the `DynamicStage`, I think the issue was that I misinterpreted it as a discovery system. To get on the same page, would the execution strategy asset be something like this?
```toml
[strategy]
stages = [
    "update",
    "fixed_update",
    "custom_stage"
]

[update]
stages = ["something", "something_else"]

[fixed_update]
stages = ["physics"]

[custom_stage]
stages = ["conditional"]
run-condition = "condition"
```

Driven by code looking like
```rust
app
    .add_dynamic_system(something.system())
    .add_dynamic_system(something_else.system())
    .add_dynamic_system(physics.system())
    .add_dynamic_system(conditional.system())
    .add_dynamic_condition(condition)
```

**Comment by cart** [comment]
> This is a valid concern, but the implementation is small and clear enough to be manageble (though the real test of that is coming back a week later).

I think we just have different opinions here. My gut reaction overall is negative, but its very possible that your assessment of the situation is correct. I'm not sure this is something we can resolve by just talking about it. I think it would be better to build this as a 3rd party plugin/crate first. Then we can consider adding it upstream if it works well in practice / doesn't regress builds / gets buy in from enough people. I'd rather take our time with this than commit to something potentially problematic and hope it works out.

> On the topic of the DynamicStage, I think the issue was that I misinterpreted it as a discovery system. To get on the same page, would the execution strategy asset be something like this?

Ahh gotcha. Yeah the design you laid out is what I was getting at.

**Comment by TheRawMeatball** [comment]
That sounds fair. I'll publish this implementation as bevy_discovery tomorrow and close this PR with a link and the benchmark results. Then I might get started on the DynamicStage with a seperate PR.

**Comment by cart** [comment]
Awesome. Thanks for being accommodating / putting up with me being heavy handed

 > Then I might get started on the DynamicStage with a seperate PR.

This is another one where I'm cool with taking our time / maybe it makes sense for it to be a separate plugin for a bit. I think it only really starts getting useful when we have an Editor UI for it, so it sort of makes sense to me to build them together / let the Editor UI inform the design. But my opinions are less strong here when it comes to order of operations / merge-ability.

**Comment by TheRawMeatball** [comment]
The crate is now published as [bevy_discovery](https://crates.io/crates/bevy_discovery)!

**Pull request closed without merging**
