### PR TITLE
Fix Update game_menu.rs

### PR DESCRIPTION
**Pull request by syapk**
multiple errors with: 
blahblahblah..   image: UiImage::new(icon)

fix with:
blahblahblah..   image: UiImage::from(icon)

# Objective

- Describe the objective or issue this PR addresses.
- If you're fixing a specific issue, say "Fixes #X".

## Solution

- Describe the solution used to achieve the objective above.

---

## Changelog

> This section is optional. If this was a trivial fix, or has no externally-visible impact, you can delete this section.

- What changed as a result of this PR?
- If applicable, organize changes under "Added", "Changed", or "Fixed" sub-headings
- Stick to one or two sentences. If more detail is needed for a particular change, consider adding it to the "Solution" section
  - If you can't summarize the work, your change may be unreasonably large / unrelated. Consider splitting your PR to make it easier to review and merge!

## Migration Guide

> This section is optional. If there are no breaking changes, you can delete this section.

- If this PR is a breaking change (relative to the last release of Bevy), describe how a user might need to migrate their code to support these changes
- Simply adding new functionality is not a breaking change.
- Fixing behavior that was definitely a bug, rather than a questionable design choice is not a breaking change.

### CODE REVIEW

**Comment by james7132** [comment]
It's unclear what this PR is trying to do. When running `game_menu` on `main`,  the example works exactly as intended, without any compile time or runtime errors. What went wrong to need the changes in this PR?

**Comment by syapk** [comment]
hi, i have this error with bevy 0.9.1:

cargo run    Compiling bevy v0.9.1

error[E0599]: no function or associated item named `new` found for struct `bevy::prelude::UiImage` in the current scope
   --> src\main.rs:104:37
    |
104 |                     image: UiImage::new(icon),
    |                                     ^^^ function or
associated item not found in `bevy::prelude::UiImage`

error[E0599]: no function or associated item named `new` found for struct `bevy::prelude::UiImage` in the current scope
   --> src\main.rs:496:53
    |
496 | ...                   image: UiImage::new(icon),
    |                                       ^^^ function or associated item not found in `bevy::prelude::UiImage`

error[E0599]: no function or associated item named `new` found for struct `bevy::prelude::UiImage` in the current scope
   --> src\main.rs:517:53
    |
517 | ...                   image: UiImage::new(icon),
    |                                       ^^^ function or associated item not found in `bevy::prelude::UiImage`

error[E0599]: no function or associated item named `new` found for struct `bevy::prelude::UiImage` in the current scope
   --> src\main.rs:538:53
    |
538 | ...                   image: UiImage::new(icon),
    |                                       ^^^ function or associated item not found in `bevy::prelude::UiImage`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `bevy` due to 4 previous errors
________________________________
De : James Liu ***@***.***>
Envoyé : lundi 12 décembre 2022 14:51
À : bevyengine/bevy ***@***.***>
Cc : syaPK ***@***.***>; Author ***@***.***>
Objet : Re: [bevyengine/bevy] Fix Update game_menu.rs (PR #6928)


It's unclear what this PR is trying to do. When running game_menu on main, the example works exactly as intended, without any compile time or runtime errors. What went wrong to need the changes in this PR?

**Comment by devil-ira** [comment]
The examples in the main branch are newer than 0.9 as it's for development.
The examples for the latest version can be found here: https://github.com/bevyengine/bevy/tree/latest/examples.

**Comment by james7132** [comment]
Closing this out as these changes are intended and was the result of user error.

**Comment by syapk** [comment]
ok thanks !!

**Pull request closed without merging**
