### PR TITLE
Add convenience method for polling Task<>

### PR DESCRIPTION
**Pull request by TheRawMeatball**
# Objective

Checking if a task is completed and retrieving the value is too convoluted

## Solution

Add a simple convenience method

### CODE REVIEW

**Comment by hymm** [comment]
Is this an alternative to https://github.com/bevyengine/bevy/pull/4102?

If it is what are the advantages/disadvantages vs that PR?

**Comment by TheRawMeatball** [comment]
Lower overhead, as this doesn't require adding an extra channel, instead using what's already built into `async_executor::Task`

**Comment by DJMcNab** [comment]
But if checking it is more expensive, then I would think that cost would dwarf the extra overhead of the channel.

That is, I can't just let the claim of 'lower overhead' meaning better go by without confirmation - `Task::poll` isn't a trivial function, and has more inherent overhead than a one-shot channel - because it must behave properly when an actual proper future is awaiting it. Maybe counting moves of the value changes that equation, but I don't find it as obviously clear cut as you.

**Review by alice-i-cecile — COMMENTED** [review]
Added the Controversial tag. I'd like to see perf testing here. The API is really simple and appealing, but I don't want that to turn into a footgun.

**Comment by hymm** [comment]
I added perf numbers here https://github.com/bevyengine/bevy/pull/4102#issuecomment-1116430517.

**Comment by richchurcher** [comment]
Backlog cleanup: closing (inactivity, no clear consensus). See #4102 also.

**Pull request closed without merging**
