### PR TITLE
Created crate bevy_net - provides TCP/UDP socket and listener functionality

### PR DESCRIPTION
**Pull request by 0x22fe**
This crate is optional and is enabled with the feature "bevy_net". It is an ECS-friendly wrapper for networking primitives. This pull request also has tested and working examples for a TCP client and server. This doesn't provide any high-level scene-related functionality, so it should be fine to merge into master without worrying about major design decisions. If not, any feedback is appreciated.

### CODE REVIEW

**Comment by MNTRA** [comment]
You might want to rename it to bevy_protoype_net.
Thats the naming convention for new crates according to the contibuting rules.

**Comment by cart** [comment]
This is awesome! For now, despite the fact that this is pretty low level, I still do think we should publish it as a separate crate. How events are generated, network primitives used, etc are all a pretty open design space that I think deserves time and experimentation before we commit to something.

**Comment by 0x22fe** [comment]
@cart Ok, that makes sense! I will move into my own repository, under the name `bevy_prototype_net` as @MNTRA suggested. Also, the [post on scaling Bevy](https://bevyengine.org/news/scaling-bevy/) says that there is/will be a centralized list of prototype crates. Where is that list (so that I may add this crate to it)?

**Comment by cart** [comment]
Currently for non-focus-area crates, https://github.com/bevyengine/awesome-bevy is the place.

For focus-area crates, we add links in the description of the relevant focus area issue

**Comment by 0x22fe** [comment]
Crate has been renamed to `bevy_prototype_simple_net` and is now located at [0x22fe/bevy_prototype_simple_net](https://github.com/0x22fe/bevy_prototype_simple_net).

**Pull request closed without merging**
