### PR TITLE
Example how to update state

### PR DESCRIPTION
**Pull request by stepancheg**
I'm adding `AppMock` again. This is not very nice looking code.

I'm thinking about this alternative: create a crate like `bevy_mocks`, which could be added as dev-dependency to most crates. AFAIU dev-dependencies are available in doctests.

`bevy_mocks` would contain interfaces of most frequently utilities like `App` or `Input<KeyCode>` and dummy implementations. That would be sufficient to write compile-only tests which would look concise in sources and illustrative in published rustdocs.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
> I'm thinking about this alternative: create a crate like bevy_mocks, which could be added as dev-dependency to most crates. AFAIU dev-dependencies are available in doctests.

This is a neat idea. Can you spin out an issue for it?

**Review by alice-i-cecile — APPROVED** [review]

**Comment by stepancheg** [comment]
https://github.com/bevyengine/bevy/pull/10726

**Review by TrialDragon — APPROVED** [review]
LGTM and the `AppMock` works as a solution for now until #3786 is resolved and hopefully removes the need. (Tho, this does have conflicts that needs to be resolved before merging).

**Comment by alice-i-cecile** [comment]
@stepancheg can you please resolve merge conflicts?

**Comment by TrialDragon** [comment]
This seems to not be importing necessary stuff; doc tests are failing.

**Pull request closed without merging**
