### PR TITLE
[Merged by Bors] - Expose command encoders

### PR DESCRIPTION
**Pull request by StarArawn**
# Objective
I'm exposing these command encoders so bevy user's can create their own command encoders. This is useful when you want to copy a texture to a texture or create a compute pass manually for example.

Note: I formatted this file which might of changed the order of some exports.

## Solution
Just re-export `CommandEncoder` and `CommandEncoderDescriptor`.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by jakobhellermann** [comment]
Maybe we should reexport `wgpu` entirely? `CommandEncoder` isn't exactly a `render_resource` anymore.

`rust-analyzer` probably prioritizes `bevy_render2::RenderPipelineDescriptor` over `bevy_render2::wgpu::RenderPipelineDescriptor` in its auto import so that should be no problem.

**Comment by cart** [comment]
> Maybe we should reexport wgpu entirely?

Its worth considering. But I do like having full control over our namespace. We already alias a number of wgpu types with our own (Texture, Buffer, RenderPiplineDescriptor, etc). Exporting wgpu wholesale makes talking about these types more difficult and introduces new (and possibly confusing and hard to debug) error cases for users of ide tooling like rust-analyzer. For now, I'd prefer to be selective here. If we miss something, users always have the escape hatch of pulling in wgpu directly. We should just do a thorough pass over the types wgpu exports and add everything we (I) missed. From there gaps should be few and far between.

**Comment by cart** [comment]
Definitely open to reconsidering how / where we export these types. `wgpu` just globs everything together at the root. `bevy_render` is a bit more organized, so we'll want to discuss ideal module names.

**Comment by cart** [comment]
(merging because this is useful now ... feel free to keep discussing)

**Pull request closed without merging**
