### PR TITLE
[Merged by Bors] - Public access for AnimationClip.duration

### PR DESCRIPTION
**Pull request by spooky-th-ghost**
# Objective

- Small change that better facilitates custom animation systems

## Solution

- Added a public access function to `bevy::animation::AnimationClip`, making duration publicly readable

---

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Thanks! Seems like a very simple, useful bit of the API.

**Review by mockersf — APPROVED** [review]

**Comment by cart** [comment]
Why are we returning a reference to an `f32` here? Thats a very irregular pattern. We should favor returning the value for copy types, especially primitives like floats.

**Comment by spooky-th-ghost** [comment]
my bad, that totally slipped my mind

**Pull request closed without merging**
