### PR TITLE
[Merged by Bors] - make `sub_app` return an `&App` and add `sub_app_mut() -> &mut App`

### PR DESCRIPTION
**Pull request by jakobhellermann**
It's sometimes useful to have a reference to an app a sub app at the same time, which is only possible with an immutable reference.

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
ci failed to download rust

**Comment by mockersf** [comment]
bors try

**Review by Ratysz — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by cart** [comment]
I chose to go against the grain with this api because the mutable variant will be _waaaaay_ more common than the immutable one (as in 99.999% of the time people want a mutable reference). Immutable access is an exception to the rule. I personally think its worth giving the terser / more ergonomic `sub_app` name to the mutable case.

**Comment by aloucks** [comment]
For what it's worth, I thought the old name was confusing. I was looking for something that ended with `_mut` for gaining mutable access. I consider `sub_app(..) -> &mut App` to be _less_ ergonomic as it doesn't follow conventions and established patterns.

**Comment by Ratysz** [comment]
Going against convention is a much greater affront to ergonomics than having to type 4 extra symbols (or less, if code completion is in a good mood).

**Comment by cart** [comment]
I still think something this central deserves a first class name. Immutable access to sub apps is pretty far off the happy path. With a few very exceptional cases, users shouldn't need to think about mutability at all here. Adding `_mut` increases the cognitive load of the common case to benefit the uncommon case. Conventions aren't hard and fast rules and I'm happy to break them when the cost / benefit of a situation makes sense. My preference is to add a new `sub_app_ref` api and leave `sub_app` as is. `_ref` is a convention [used in the std library](https://doc.rust-lang.org/std/io/struct.Chain.html#method.get_ref)  to indicate a method returns something immutable. That seems suitably clear for doc browsers.

Not putting my foot down here though. Feel free to weigh in / gather support for your preferred approach. Imo this is a pretty clear case of what an exception to the convention should look like (if we are going to allow exceptions). Its worth discussing it as a community and trying to establish consensus so we can quickly resolve these disagreements in the future. If this isn't an exception to the convention, I don't think anything is.

Vote here:
:rocket:  If you think we should leave this as-is. Exceptions to the `x` / `x_mut` convention (in favor of something like `x` / `x_ref`) are allowed when the mutable method is the overwhelmingly common use case, in the interest of ergonomics and/or reduction of cognitive load.
:tada:  If you think we should strictly follow `x`, `x_mut` in cases like this`, in the interest of following conventions and reducing surprises. 

(This is an "advisory vote" ... the results won't actually determine what we do, but I will give them weight)

**Comment by Ratysz** [comment]
`_ref()` only appears alongside `_mut()`, as much as I can remember right now.

I think we should follow convention as much as we can. I know it's not a rule, and that there are bound to be exceptions that make sense, but this doesn't feel like one.

I don't like the idea of having people learn Rust using libraries and small frameworks (most of which follow convention), then come to Bevy and find that the norms they've gotten used to don't apply.

**Comment by Ixentus** [comment]
The actual rule for the convention is here https://github.com/rust-lang/rfcs/blob/master/text/0199-ownership-variants.md

> 
> If foo uses/produces owned data by default, use:
> 
>     The _ref suffix (e.g. foo_ref) for the immutably borrowed variant.
>     The _mut suffix (e.g. foo_mut) for the mutably borrowed variant.
>

**Comment by aloucks** [comment]
That [example](https://doc.rust-lang.org/std/io/struct.Chain.html#method.get_ref) isn't really representative of what's happening here though.

Accessors in Rust almost always follow the `item(&self) -> &Item` and `item_mut(&mut self) -> &mut Item` pattern 

Or use `get(&self, id: Id) -> &Item` and `get_mut(&mut self, id: Id) -> &mut Item` for container-like objects.

**Comment by aevyrie** [comment]
I don't think the esthetics are worth breaking convention in this case. I definitely respect the argument, but as someone who relies on code completion or often times just guessing by following convention, this would trip me up without any _perceived_ gain. 

It's also nice to see mutability at a glance when reading someone else's code. I'm not good enough to infer it or remember these exceptions. 🙂

**Comment by cart** [comment]
Alrighty there is overwhelming support for `sub_app_mut`, so we will go with that. Thanks to everyone for weighing in!

**Pull request closed without merging**
