### PR TITLE
[Merged by Bors] - Remove leftover pbr_textures example

### PR DESCRIPTION
**Pull request by Grindv1k**
`examples/3d/pbr_textures.rs` was missing in both `Cargo.toml` and in the examples
`README.md`.

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Comment by adsick** [comment]
noticed it as well, wanted to add it)

**Comment by pkupper** [comment]
The pbr_textures and load_gltf examples were merged because the only difference was the rotating light. It looks like cart just forgot to remove the pbr_textures file. See commit [https://github.com/bevyengine/bevy/pull/1632/commits/00b03a7f09fa43cbb12102a60033dab14482762d](https://github.com/bevyengine/bevy/pull/1632/commits/00b03a7f09fa43cbb12102a60033dab14482762d) .

**Comment by Grindv1k** [comment]
@pkupper oh ok didn't know about that!

I did an overwrite of this branch to instead remove the leftover `pbr_textures.rs`.

**Review by alice-i-cecile — APPROVED** [review]

**Pull request closed without merging**
