### PR TITLE
Include bevy_text feature in bevy_ui

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Was this intentional? It seems pretty weird to keep them seperate.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by SUPERCILEX** [comment]
I maybe take this back? What's the story for people using `default-features=false`? `bevy_core_pipeline` is also not added when `bevy_render` is added (and maybe `bevy_winit` should be added too?). I can see the argument that everything should be chosen explicitly since most people won't use default-features=false anyway.

**Comment by alice-i-cecile** [comment]
`default-features=false` has two audiences:

1. People doing something unusual that want to improve their compile times in serious projects.
2. Library authors, since features are additive.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Changed my mind, I don't think we should do this.

**Comment by SUPERCILEX** [comment]
Makes sense!

**Comment by rparrett** [comment]
related: #7855

**Pull request closed without merging**
