### PR TITLE
[Merged by Bors] - Bump gilrs version to 0.10

### LINKED ISSUE #6555: Gamepad input not working for DualSense (PS5) controller
## Bevy version

Tested both v0.8.1 and commit c3c4088317f0ea09de8d96e22fa5beb28e486c30 of bevy

## What you did

Running the official gamepad input examples of bevy

`cargo run --example gamepad_input` and `cargo run --example gamepad_input_events`

plugging and unplugging my controller and pressing buttons.

## What went wrong

Controller doesn't log anything in the terminal when pressing buttons or connecting/disconnecting it.

## Additional information

Tested with the official example from gilrs repo and it works perfectly fine, outputs as expected when gilrs is standalone.

### PR DESCRIPTION
**Pull request by james7132**
# Objective
Fix #6555.

## Solution
Bump `gilrs` version to 0.10.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Duplicate dependencies are annoying, but I have a hard time arguing they're more important than supporting major controllers.

**Comment by mockersf** [comment]
girls 0.10 is breaking support for controllers on macOS. it has been fixed but not yet released

**Comment by paul-hansen** [comment]
> Duplicate dependencies are annoying, but I have a hard time arguing they're more important than supporting major controllers.

Opened a PR with Cpal to update their windows crate https://github.com/RustAudio/cpal/pull/726, I think that should solve the duplicate dependency. Will take a while to get downstream to us and I agree that it would be worth merging before then. (Once gilrs has the macOS fix out.)

**Comment by paul-hansen** [comment]
Gilrs 0.10.1 just dropped! Should have the MacOS fix.
https://crates.io/crates/gilrs/0.10.1
Also includes my fix to make wasm binary smaller and a fix for north and west buttons being flipped on Wasm too.

**Comment by james7132** [comment]
bors try

**Comment by mockersf** [comment]
could you update to `0.10.1` to ensure the 0.10.0 won't be used?

**Review by mockersf — APPROVED** [review]

**Pull request closed without merging**
