### PR TITLE
Add testing to Commands run_system functions

### PR DESCRIPTION
**Pull request by pablo-lua**
# Objective

- It was mentioned on #11019 the possibility to add a test to `Commands::run_system` and `Commands::run_system_with_input`, this is a follow up of the possibility
## Solution

- Adding the test to the common `Commands` tests

---

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@doonv can I get your review here?

**Comment by pablo-lua** [comment]
Just to be sure, the CI problem is related to that one problem mentioned in #11123? Never touched the file in question after all

**Comment by alice-i-cecile** [comment]
Yep, not your problem.

**Review by doonv — APPROVED** [review]
Looks good to me

**Comment by doonv** [comment]
btw i dont think there should be changelogs for this because there's no external changes. it's all internal tests

**Comment by pablo-lua** [comment]
Giving it a second look: in system_registry.rs there already two existent tests to this subject: nested_systems and nested_systems_with_inputs, so this PR doesn't really have a reason to exist, and therefore, I'm closing it

**Pull request closed without merging**
