### PR TITLE
Replace remaining uses of `&T, Changed<T>` with `Ref` in UI system queries

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Replace `Query<&T, Changed<T>>` style queries with the more efficient `Query<Ref<T>>` form in two of the UI systems.

---

## Changelog

Replaced use of  `Changed` with `Ref` in queries in the `ui_layout_system` and `calc_bounds` UI systems.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Much clearer!

**Review by mockersf — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
`Changed<T>` doesn't operate on an archetype level currently: only individual entities.

**Comment by inodentry** [comment]
@alice-i-cecile I have a question. Didn't we at some point talk about possibly tracking that information at the archetype level in the ECS in the future, to allow for more efficient change detection? So that query filters can actually result in an efficiency improvement by only accessing changed entities?

This PR seems counterproductive. If we ever do that, we would have to change it back.

Also, performance aside, I really disagree that using `Ref` is always necessarily clearer. If the intent is to only access changed entities, then the query filter makes that clear. If the intent is to access all entities, but be able to do different logic if entities were changed or not, then Ref is clearer.

I know this PR was merged long ago, and me expressing an opinion now probably doesn't matter much, but this really feels like the wrong direction to me.

**Comment by alice-i-cecile** [comment]
That's a valid position, and yeah, we should be able to have multiple layers of change detection for faster operation in the future.

**Pull request merged**
