### PR TITLE
[Merged by Bors] - Fix shader syntax

### PR DESCRIPTION
**Pull request by timokoesters**

### CODE REVIEW

**Review by Bobox214 — APPROVED** [review]

**Review by NiklasEi — APPROVED** [review]
Nice catch

**Review by devil-ira — CHANGES_REQUESTED** [review]
The struct definition is still using the old syntax :)

**Comment by timokoesters** [comment]
I fixed the struct syntax now @devil-ira

**Comment by cart** [comment]
> I fixed the struct syntax now @devil-ira

Not quite. Still needs to use `,` after each field instead of `;`

**Comment by timokoesters** [comment]
I fixed that and fixed the other Material file too

**Pull request closed without merging**
