### PR TITLE
fix changed meshes

### PR DESCRIPTION
**Pull request by cart**
#958 broke "updating" meshes. This fixes it (with no perf cost). I was over-complicating things :smile:

### CODE REVIEW

**Comment by cart** [comment]
Resolves #977

**Comment by cart** [comment]
(actually maybe it doesn't)

**Comment by rod-salazar** [comment]
I think it's a different issue for #977 (the Changed query doesn't catch the changes since the changes happened after this system ran, but it doesn't catch it on the next frame either of course, so it never sees it).

**Comment by cart** [comment]
Haha yeah i just noticed that. Take a look at the comment i just left there.

**Comment by msvbg** [comment]
This is the repro/issue I made that this is supposed to solve: #981. Unable to test it right now.

**Comment by msvbg** [comment]
Okay, I've confirmed that it closes #981. Nice!

**Pull request merged**
