### PR TITLE
Replace `map` + `unwrap_or(false)` with `is_some_and`

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

The `my_option.map(|inner| inner.is_whatever).unwrap_or(false)` pattern is fragile and ugly. 

Replace it with `is_some_and` everywhere.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by BenjaminBrienen — APPROVED** [review]

**Comment by Victoronz** [comment]
I think `map_or(true, ...)` also be done in this PR, as it is the same pattern.

**Comment by BenjaminBrienen** [comment]
> I think `map_or(true, ...)` also be replaced in this PR, as it is the same pattern.

That is already linted by clippy and I fixed that already in another PR.

**Comment by Victoronz** [comment]
> > I think `map_or(true, ...)` also be replaced in this PR, as it is the same pattern.
> 
> That is already linted by clippy and I fixed that already in another PR.

Does it capture everything? I had done a quick search in the engine and still found some `map_or(false/true, ...)`.
Not many, but still some.

**Comment by alice-i-cecile** [comment]
> I think map_or(true/false, ...) also be replaced in these PRs where applicable, as it is the same pattern.

I'm fine either way. I'll merge this on Monday if ickshonpe doesn't get to it, or doesn't want to bother.

**Pull request merged**
