### PR TITLE
Add char input

### PR DESCRIPTION
**Pull request by Jerald**
Based on the comments and information from #782, this is an alternative approach to providing a form of simple text input in bevy.

This adds the `CharInput` event to `bevy_input` and modifies `bevy_winit` to dispatch the event when the winit `ReceivedCharacter` event fires.

Only _one_ of either this PR or #805 should realistically be merged.

### CODE REVIEW

**Comment by Jerald** [comment]
I've now added #805 which is a more window-focused alternative to this approach. I'm leaving both open so the preferred one can be chosen, closing the other one.

**Comment by cart** [comment]
closed in favor of #805

**Comment by stanle-cs** [comment]
@cart I don't know if it's appropriate to ask here, but ran into this issue today. Is there a reason why #805 is favored over #804? I tried to use `<ReceivedCharacter>` and realized that it is part of the window plugin, so I can't use it with the minimal plugin group. Tried to find something similar to this at a lower level but doesn't look like we have an easy way to get the `char` from either `ScanCode` or `KeyCode` unless I'm mistaken.

**Comment by cart** [comment]
@stanle-cs Character input pretty much always happens within the context of a window (and on some platforms, _must_ happen in the context of a window). We might later add "windowless input" support for platforms that support it, but that is a corner case to a degree that I'm not sure we should be focusing on right now.

**Pull request closed without merging**
