### PR TITLE
Remove global vs local translation example

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

- Fix a source of contradictory advice relating to `GlobalTransform`

## Solution

- Remove global_vs_local_translation.rs

## Motivation

A user in discord asked:

> why do the docs say you shouldnt mutate global transform manually but global_vs_local_translation example does just that?

I don't believe that we actually do explicitly call that out in our docs, but similar language can be found in the Bevy Cheatbook. And maybe it **should** be spelled out more explicitly on our docs.

So this example seems to be promoting bad behavior, and apart from that, doesn't seem to be adding much that isn't covered by `parenting.rs`.

So I am proposing that we remove it.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
@aevyrie I know you've used this sort of direct manipulation of `GlobalTransform` before; do you think this example should be removed? Clarified?

**Comment by aevyrie** [comment]
If the goal is educating new users, then I agree with this PR. Mutating global transform is useful, but only after you understand the constraints of the propagation system. I think advice to beginners should be "don't mutate GlobalTransform unless you have a very good reason to"

**Review by alice-i-cecile — APPROVED** [review]
I'm on board with removing this. It's useful as a visualizer, but misleading due to its mutation of GlobalTransform.

**Review by ManevilleF — APPROVED** [review]

**Comment by cart** [comment]
> Some people found this example useful, maybe improving comments to explain what to do (and use the example to show why updating the global transform won't do what people may expect) would be better than removing it?

I agree with this sentiment. Providing more context in this example feels like the move.

**Pull request closed without merging**
