### PR TITLE
Rendertarget cmp (adopted)

### PR DESCRIPTION
**Pull request by richchurcher**
This is an adoption of #8300 (`aevyrie`). The only change I've made is removing `Ord` as [suggested](https://github.com/bevyengine/bevy/pull/8300#issuecomment-1498260941), and `PartialOrd` because I presumed that made sense.

Also took out `FromReflect`, because I see we get that for free now with `Reflect`.

> # Objective
> * The changes in Windows as Entities removed the ability to compare `RenderTargets` without bringing in additional query data. This should not be needed, as these types are directly comparable.
> 
> ## Solution
> * Reinstate derive macros.

### CODE REVIEW

**Comment by richchurcher** [comment]
Ah, yes I was possible a bit naiive here! Given the CI failure, I presume I would need to conduct some surgery on `sort_cameras` to make this work?

**Comment by tychedelia** [comment]
> Ah, yes I was possible a bit naiive here! Given the CI failure, I presume I would need to conduct some surgery on `sort_cameras` to make this work?

I'm not sure I totally understand the original justification for having different render targets in the same order. The implicit sort just feels li. I think we should change the ambiguity code to enforce an explicit total order (i.e. unique per camera). Curious what others think.

**Comment by richchurcher** [comment]
> > Ah, yes I was possible a bit naiive here! Given the CI failure, I presume I would need to conduct some surgery on `sort_cameras` to make this work?
> 
> I'm not sure I totally understand the original justification for having different render targets in the same order. The implicit sort just feels like a bug waiting to happen. I think we should change the ambiguity code to enforce an explicit total order (i.e. unique per camera). Curious what others think.

Awesome, I definitely am not qualified for that so I'll wait to hear the result!

**Comment by richchurcher** [comment]
Lack of clear consensus here in 2024, [Discord discussion](https://discord.com/channels/691052431525675048/692572690833473578/1287891927831678987) for further context.

**Pull request closed without merging**
