### PR TITLE
[Merged by Bors] - bevy_scene: Stabilize entity order in `DynamicSceneBuilder`

### PR DESCRIPTION
**Pull request by MrGVSV**
# Objective

Currently, `DynamicSceneBuilder` keeps track of entities via a `HashMap`. This has an unintended side-effect in that, when building the full `DynamicScene`, we aren't guaranteed any particular order. 

In other words, inserting Entity A then Entity B can result in either `[A, B]` or `[B, A]`. This can be rather annoying when running tests on scenes generated via the builder as it will work sometimes but not other times. There's also the potential that this might unnecessarily clutter up VCS diffs for scene files (assuming they had an intentional order).

## Solution

Store `DynamicSceneBuilder`'s entities in a `Vec` rather than a `HashMap`.

---

## Changelog

* Stablized entity order in `DynamicSceneBuilder` (0.9.0-dev)

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — COMMENTED** [review]
This feels like we should be using a `BTreeMap` (which relies on the ordered nature of the keys) instead of a `Vec` with a `HashSet`?

**Comment by MrGVSV** [comment]
> This feels like we should be using a `BTreeMap` (which relies on the ordered nature of the keys) instead of a `Vec` with a `HashSet`?

Good point! 

However, my one question with that is: do we want entities to be ordered by ID or by insertion? I feel like insertion might be nicer since you could give it two entities tied to particular data or relationship, and get the same result— regardless of which one happened to spawn first.

Although, for large groups of entities where order doesn't really matter, I suppose ordering by ID makes the output a little more readable (entity 1 always comes after entity 0)?

Any thoughts on this?

**Comment by alice-i-cecile** [comment]
My feeling is that by ID is simpler and more repeatable. It also serves as a nice little checksum.

**Comment by MrGVSV** [comment]
> My feeling is that by ID is simpler and more repeatable. It also serves as a nice little checksum.

Makes sense. I'll push the `BTreeMap` changes for now unless someone else feels strongly that it should be based on insertion order.

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Pull request closed without merging**
