### PR TITLE
[Merged by Bors] - Add const to methods and const defaults to bevy_ui

### LINKED ISSUE #5529: Add const builder methods to bevy_ui
## What problem does this solve or what need does it fill?

Constants are useful when manually defining UIs to get compile-time guarantees that your style / layout won't unexpectedly change at runtime.

However, many of the existing builder methods are not const, when they could be.

## What solution would you like?

1. Look through `bevy_ui`, and make any methods that you can `const`. This is particularly important for methods that return a new struct of the type that the impl block is for (a "builder method").
2. Ensure that all of the essential structs have a const equivalent to `Default::default()`. This should be a `DEFAULT` associated constant. Use these new constants in the `default` trait implementations where feasible.

## What alternative(s) have you considered?

Use a `const fn new()`. This is less clear, doesn't display the actual value in docs, and may have indirection overhead (IIRC this varies based on the optimization level). These are simple values, they should be represented as such.

### PR DESCRIPTION
**Pull request by james-j-obrien**
# Objective
- Fixes #5529 

## Solution
- Add assosciated constants named DEFAULT to as many types as possible
- Add const to as many methods in bevy_ui as possible

I have not applied the same treatment to the bundles in bevy_ui as it would require going into other bevy crates to implement const defaults for structs in bevy_text or relies on UiImage which calls HandleUntyped.typed() which isn't const safe.

Alternatively the defaults could relatively easily be turned into a macro to regain some of the readability and conciseness at the cost of explicitness.
Such a macro that partially implements this exists as a crate here: [const-default](https://docs.rs/const-default/latest/const_default/derive.ConstDefault.html) but does not support enums.

Let me know if there's anything I've missed or if I should push further into other crates.

### CODE REVIEW

**Review by Weibye — APPROVED** [review]
This looks good in my eyes 👍

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
I does seem like a pain to have all the default trait be manually implemented, not sure I like it...

**Comment by alice-i-cecile** [comment]
This is, in theory at least, only a temporary measure. I wouldn't bother with this for most of our types but IMO it's particularly useful for UI.

**Comment by cart** [comment]
Before opening the floodgates here on this pattern (which is non-standard / increases our code size), can we discuss specific motivating use cases?

And given that a solution to this problem [might be around the corner](https://github.com/rust-lang/rust/issues/67792), do we need solve this problem now or can we wait?

**Comment by alice-i-cecile** [comment]
The linked Rust feature would certainly be my favorite solution here, but it doesn't exist yet.

IMO there are 3 arguments for doing this:

1. The values of consts will show up automatically in hover tooltips, while they won't for macros.
2. This allows us to build additional helper methods / constants as seen in https://github.com/bevyengine/bevy/pull/5513/files#diff-e5ceeb8dc50a9a46e76e601d33134dd7601e606263264634c0c5736a7d12ff3bR87 using struct update syntax, rather than manually entering in the default values of fields (which is hard to read / impossible to update reliably / very error prone).
3. Similarly, this allows users to define their own custom UI styles / layout strategies using struct update syntax. This is particularly valuable in UI, where complex configurable global-ish constants are quite common and can improve clarity.

**Review by cart — APPROVED** [review]
Sorry for dragging my feet on this. Still not stoked that this is necessary, but its the best option we have if we want to unlock these scenarios.

**Pull request closed without merging**
