### PR TITLE
Add EventReaderMut - A way to iterate over Events with mutable references to them.

### PR DESCRIPTION
**Pull request by GGalizzi**
# Objective

Allows to iterate over events while obtaining a mutable reference to them.

I've been wanting to modify events while iterating over them to make "interceptor" systems over events so the final consumer will achieve a different result based of that event. I've noticed I'm not the only one looking for something like this based on Discord searches. 

Currently the only way to achieve something like this is to require `ResMut<Events<T>>` and use `drain`, which isn't ideal when the system only _may_ want to modify _some_ of the events, instead you have to drain them all, re-send accordingly, and manage the updates manually.

I don't know if this is the best solution, or if this is even something that would be wanted in the ECS, but here's the proposal, and it's easy to implement.

## Solution

Create a variation of the `EventReader` struct, called `EventReaderMut`, which contains a `ResMut` to these events, and does a mutable iteration over them.

## Example usage

```rust
fn intercept_attacks(
    //...
    booster: Query<(Entity, &Stats), With<Booster>>,
    mut attacks: EventReaderMut<Attack>,
) {
    attacks
        .iter_mut()
        // ...
        .for_each(|event| {
            // ..
            event.damage += boosted_by;
        });
}
```

## Unresolved questions / things left to consider

* Naming of struct & functions
* I don't know if there's a way to make a generic out of `internal_event_reader` so that code doesn't have to be repeated twice with the only thing changing is the calls to `iter` and `get` to `iter_mut` and `get_mut`.

### CODE REVIEW

**Comment by bjorn3** [comment]
> I've been wanting to modify events while iterating over them to make "interceptor" systems over events so the final consumer will achieve a different result based of that event. I've noticed I'm not the only one looking for something like this based on Discord searches.

I am curious why you did want this? Can you give some more details about what you exactly want to do?

**Comment by GGalizzi** [comment]
> > I've been wanting to modify events while iterating over them to make "interceptor" systems over events so the final consumer will achieve a different result based of that event. I've noticed I'm not the only one looking for something like this based on Discord searches.
> 
> I am curious why you did want this? Can you give some more details about what you exactly want to do?

Couple of examples:

1) Tile based collision detection, like in a roguelike. Yes, I could do it directly in the system that now fires the event. But it was making sense to me that there's a separate system that first checks if the movement is valid, and if it isn't then the event gets invalidated; further decoupling system concerns.

2) Attack Buff "totems", a system goes through active totems, and checks attack events, if the attacker is in range the event gets a buff on damage. Yes, it could be handled by giving a buff (insert buff component or modify existing component) on the buffed entity itself.


:shrug: I like events, and wanted more options with them.

**Comment by Nilirad** [comment]
I'm not particularly convinced to have mutable events. In my opinion, they should always be read-only.
An event, hence its name, shows a thing that happened. If you are able to modify it with arbitrary data it becomes conceptually invalid.

**Comment by GGalizzi** [comment]
Yes, I started thinking the same yesterday as I was trying some more stuff with this. An event should be better described as something that has happened, and you can't alter the past.
 
But could it also be a thing that is about to happen? 

In any case, I started wondering if I needed to make a separate resource to better describe what I need.

**Pull request closed without merging**
