### PR TITLE
Fix bloom wasm support

### LINKED ISSUE #7352: WASM does not work with HDR
Hi, I have an issue when enabling HDR running in the browser. Thanks for any help.

## Bevy version
Tried 0.9.1 and bleeding (cf612c8349068c2250dddf8190cd9cc5c24763d8)

## Relevant system information
Chrome Version 108.0.5359.71 (Official Build) (64-bit) on Ubuntu 22.10
```ignore
AdapterInfo { name: "ANGLE (Intel, Vulkan 1.3.224 (Intel(R) Xe Graphics (TGL GT2) (0x00009A49)), Intel open-source Mesa driver)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
```

## What you did
checkout https://github.com/rust-adventure/bevy-examples/blob/418afebf3f411625e149a23c2a360ffeee71b2b7/examples/bloom-2d/src/main.rs
and run using wasm-server-runner
```
cargo run --target wasm32-unknown-unknown
```

## What went wrong
```
wasm.js:371 panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
      note: label = `main_texture_sampled`
    Format Rgba16Float does not support multisampling

', /home/redspider/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.14.2/src/backend/direct.rs:2403:5

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:1334/api/wasm.js:359:13)
    at __wbg_new_abda76e883ba8a5f externref shim (http://localhost:1334/api/wasm.wasm:wasm-function[30763]:0xded455)
    at console_error_panic_hook::hook::h83df3a0af36e2bba (http://localhost:1334/api/wasm.wasm:wasm-function[9303]:0xa71ce7)
    at core::ops::function::Fn::call::h39797319ccfadbf4 (http://localhost:1334/api/wasm.wasm:wasm-function[43389]:0xe239e3)
    at std::panicking::rust_panic_with_hook::hb42d415afcc11f2f (http://localhost:1334/api/wasm.wasm:wasm-function[15757]:0xc76697)
    at std::panicking::begin_panic_handler::{{closure}}::h57dd84c078404aa2 (http://localhost:1334/api/wasm.wasm:wasm-function[18765]:0xd02df3)
    at std::sys_common::backtrace::__rust_end_short_backtrace::hef94dcc71d3b37f5 (http://localhost:1334/api/wasm.wasm:wasm-function[27153]:0xdd0e16)
    at rust_begin_unwind (http://localhost:1334/api/wasm.wasm:wasm-function[22878]:0xd84fb2)
    at core::panicking::panic_fmt::h32de9c76c9d5eb0c (http://localhost:1334/api/wasm.wasm:wasm-function[25650]:0xdbbce5)
    at core::ops::function::Fn::call::h811e23061157d904 (http://localhost:1334/api/wasm.wasm:wasm-function[16627]:0xca3fe2)
```

## Additional information
Works fine when HDR is disabled or without wasm

### PR DESCRIPTION
**Pull request by vallrand**
# Objective

- Fixes #7352 

## Solution

GLES doesn't support binding specific mip levels for sampling. Fallback to using separate textures instead.
- [wgpu-hal/src/gles/device.rs](https://github.com/gfx-rs/wgpu/blob/628a95cd1c27abce4d4ff2ffe4558cc4ef1e7fd3/wgpu-hal/src/gles/device.rs#L1038)

---

### CODE REVIEW

**Comment by mockersf** [comment]
Nice, thank you for doing this!

Could you set `wasm` to true in https://github.com/vallrand/bevy/blob/wasm-bloom/Cargo.toml#L277 and https://github.com/vallrand/bevy/blob/wasm-bloom/Cargo.toml#L538?

**Review by mockersf — APPROVED** [review]

**Comment by JMS55** [comment]
Needs a comment in the code explaining why we need a fallback for webgl2 and how the fallback is multiple textures instead of mips.

Also, did you test that this works ok in practice? Iirc there are problems with HDR on wasm (maybe only when used with MSAA?), regardless of bloom.

**Comment by mockersf** [comment]
works for me in WebGL2

**Comment by JMS55** [comment]
This shouldn't work? See https://docs.rs/bevy/latest/bevy/prelude/struct.Camera.html#structfield.hdr

Turning hdr on uses Rgba16Float textures for the ViewTarget, which shouldn't work with MSAA, and supposedly should outright crash with MSAA + WebGL2.

**Comment by JMS55** [comment]
https://github.com/bevyengine/bevy/pull/8634

**Review by JMS55 — APPROVED** [review]

**Review by devil-ira — APPROVED** [review]

**Review by cart — APPROVED** [review]

**Comment by MAG-AdrianMeredith** [comment]
just out of interest, does this workaround apply to webgpu version of wasm?

**Comment by mockersf** [comment]
No, bloom already works in WebGPU, you can check it here on a compatible browser: https://bevyengine.org/examples-webgpu/2D%20Rendering/bloom-2d/

**Pull request merged**
