### PR TITLE
Split the bevy_ecs reflect.rs module

### PR DESCRIPTION
**Pull request by nicopap**
# Objective

- Cleanup the `reflect.rs` file in `bevy_ecs`, it's very large and can get difficult to navigate

## Solution

- Split the file into 3 modules, re-export the types in the `reflect/mod.rs` to keep a perfectly identical API.
- Add **internal** architecture doc explaining how `ReflectComponent` works. Note that this doc is internal only, since `component.rs` is not exposed publicly.

### Tips to reviewers

To review this change properly, you need to compare it to the previous version of `reflect.rs`. The diff from this PR does not help at all! What you will need to do is compare `reflect.rs` individually with each newly created file.

Here is how I did it:

- Adding my fork as remote `git remote add nicopap https://github.com/nicopap/bevy.git`
- Checkout out the branch `git checkout nicopap/split_ecs_reflect`
- Checkout the old `reflect.rs` by running `git checkout HEAD~1 -- crates/bevy_ecs/src/reflect.rs`
- Compare the old with the new with `git diff --no-index  crates/bevy_ecs/src/reflect.rs crates/bevy_ecs/src/reflect/component.rs`

You could also concatenate everything into a single file and compare against it:

- `cat crates/bevy_ecs/src/reflect/{component,resource,map_entities,mod}.rs > new_reflect.rs`
- `git diff --no-index  crates/bevy_ecs/src/reflect.rs new_reflect.rs`

### CODE REVIEW

**Comment by NoahShomette** [comment]
Everything looks good to me and the divisions make sense.

The new documentation is really helpful to understand what the ReflectComponent stuff actually is, why its there, and what you use it for. I know these are intended for internal usage, however I think reflect is something where its really really helpful to the end user to understand more of how stuff works rather than less. These new docs in particular helped me a lot to understand what ReflectComponent actually is and why I'm using it. In that regard I think a portion of or a rewrite of these docs moved to the mod file so its public and hopefully in docs.rs would be really helpful for the end user who is trying to figure out how to use reflect. As it stands ReflectComponent doesn't really have any public documentation I believe. That can definitely be a follow up pr if its a good idea though.

**Review by alice-i-cecile — APPROVED** [review]
I like this change: cleaner and docs are good! I'm going to merge now in the interest of unblocking future work and avoiding merge conflicts.

**Comment by alice-i-cecile** [comment]
@NoahShomette thanks for the review :) In the future, feel free to actually use the `Approve` functionality in the Files Changed tab to make it easier to track. Bevy uses a system where PRs need two approvals to merge, but reviews from community members like yourself count!

**Comment by NoahShomette** [comment]
> @NoahShomette thanks for the review :) In the future, feel free to actually use the `Approve` functionality in the Files Changed tab to make it easier to track. Bevy uses a system where PRs need two approvals to merge, but reviews from community members like yourself count!

Of course, thank you! Wasn't sure exactly how to do it but I'll get it done right next time!

**Review by NoahShomette — APPROVED** [review]

**Pull request merged**
