### PR TITLE
Ahash constructor extensions and HashMap / HashSet

### PR DESCRIPTION
**Pull request by joshuajbouw**
The HashMap and HashSet should be renamed to add clarity that it isn't just a normal HashMap and HashSet and uses Ahash. This has been updated to reflect that. Further, it is very handy to add in the rest of the usual constructor API that one would use when constructing a HashMap or HashSet. This has been changed in these commits.

### CODE REVIEW

**Comment by cart** [comment]
I think I prefer the old approach of using `HashMap`, but importing from a different namespace. The actual type is still HashMap, its just the hashing algorithm is different. This change makes it seem like its a brand new type.

**Comment by joshuajbouw** [comment]
Sure, I can change it back and fix that formatting error.

**Comment by joshuajbouw** [comment]
PR name and code updated

**Comment by cart** [comment]
Awesome. if you rebase this should be good to go (i fixed the build break on master).

**Comment by joshuajbouw** [comment]
Should be good now.

**Pull request merged**
