### PR TITLE
Rename `trigger.entity()` to `trigger.target()`

### PR DESCRIPTION
**Pull request by aevyrie**
# Objective

- A `Trigger` has multiple associated `Entity`s - the entity observing the event, and the entity that was targeted by the event.
- The field `entity: Entity` encodes no semantic information about what the entity is used for, you can already tell that it's an `Entity` by the type signature!

## Solution

- Rename `trigger.entity()` to `trigger.target()`

---

## Changelog

- `Trigger`s are associated with multiple entities. `Trigger::entity()` has been renamed to `Trigger::target()` to reflect the semantics of the entity being returned.

## Migration Guide

- Rename `Trigger::entity()` to `Trigger::target()`.
- Rename `ObserverTrigger::entity` to `ObserverTrigger::target`

### CODE REVIEW

**Review by BenjaminBrienen — APPROVED** [review]
I like this and it lines up with how I'm used to this being called.

**Comment by BenjaminBrienen** [comment]
Obviously, the description needs to be updated lol

**Review by alice-i-cecile — APPROVED** [review]
This is much clearer to me, thanks for putting this together.

**Comment by alice-i-cecile** [comment]
CI caught a few more places where this needs to be renamed. Once that's fixed, ping me and I'll merge :)

**Comment by aevyrie** [comment]
@alice-i-cecile looks like I was missing some recent commits to main.

**Comment by aevyrie** [comment]
I'm not sure why CI is failing, the code it is pointing to doesn't exist on main or my branch.

**Pull request merged**
