### PR TITLE
Fix check that cursor position is within window bounds

### PR DESCRIPTION
**Pull request by mdickopp**
# Objective

The recently introduced check that the cursor position returned by `Window::cursor_position()` is within the bounds of the window (https://github.com/bevyengine/bevy/commit/3cf94e7c9d434a7fb21be1ff266c3fa43d13ea3d) has the following issue:

If *w* is the window width, points within the window satisfy the condition 0 ≤ *x* < *w*, but the code assumes the condition 0 ≤ *x* ≤ *w*. In other words, if *x* = *w*, the point is not within the window bounds. Likewise for the height. This program demonstrates the issue:

```rust
use bevy::{prelude::*, window::WindowResolution};

fn main() {
    let mut window = Window {
        resolution: WindowResolution::new(100.0, 100.0),
        ..default()
    };

    window.set_cursor_position(Some(Vec2::new(100.0, 0.0)));

    println!("{:?}", window.cursor_position());
}
```

It prints `Some(Vec2(100.0, 0.0))` instead of the expected `None`.

## Solution

- Exclude the upper bound, i.e., the window width for the *x* position and the window height for the *y* position.

### CODE REVIEW

**Comment by rparrett** [comment]
A fix was just merged: #9657

**Comment by mdickopp** [comment]
Should I open a new PR for the second issue (and close this one)?

**Comment by rparrett** [comment]
Feel free to modify this PR. Just making sure you know that the code just changed underneath you.

**Comment by mdickopp** [comment]
I modified the commit and the PR description accordingly.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
I'd like a quick regression test (or a handful of tests) for this :)

Good fix though.

**Comment by mdickopp** [comment]
Tests added.

**Review by alice-i-cecile — APPROVED** [review]

**Review by NoahShomette — APPROVED** [review]
LGTM

**Pull request merged**
