### PR TITLE
Align bevy_input::Touch API with other similar APIs 

### PR DESCRIPTION
**Pull request by amberkowalski**
With the recent changes to APIs in `Time` and `Timer`, I came across Touch which would benefit from the same change. Upon code approval I can add it to the changelog.

My last PR randomly killed itself when I was messing with the git history, odd.

### CODE REVIEW

**Review by CleanCut — APPROVED** [review]
Seems consistent with the Timer changes.

Should `delta` and `distance` also be marked `#[inline]` for consistency?

**Comment by amberkowalski** [comment]
> Seems consistent with the Timer changes.
> 
> Should `delta` and `distance` also be marked `#[inline]` for consistency?

I decided not to immediately since they're not simple getters and setters, but we'll see what @cart thinks.

**Comment by cart** [comment]
Yeah whether or not to inline is always an interesting question. I think we should only "always default" to inlining simple field accesses. Everything else should probably be informed by benchmarks (both perf and compile time).

**Comment by CleanCut** [comment]
> Yeah whether or not to inline is always an interesting question. I think we should only "always default" to inlining simple field accesses. Everything else should probably be informed by benchmarks (both perf and compile time).

Great, it's nice to have a guideline. 👍

**Pull request merged**
