### PR TITLE
Add Icospheres mesh generation

### PR DESCRIPTION
**Pull request by OptimisticPeach**
Additionally documents the shapes module.

Compile time differences (shouldn't affect iterative, however I'd be willing to test if given a test case).

| (Time is in ms) | Debug 1    | Debug 2    | Debug 3    | Release 1  | Release 2  |
|-----------------|-------------|-------------|-------------|-------------|-------------|
| With changes    | 139556.2935 | 135087.6362 | 135230.7311 | 333909.4623 | 336670.5693 |
| Without changes | 137795.5806 | 136931.7813 | 136264.8976 | 338061.5693 | 337324.0253 |

### CODE REVIEW

**Comment by OptimisticPeach** [comment]
Iterative build times:

| (Time is in ms) | Debug 1   | Debug 2   | Debug 3   | Release 1 | Release 2 | Release 3 |
|-----------------|-----------|-----------|-----------|-----------|-----------|-----------|
| With changes    | 5803.1103 | 4906.3747 | 4864.8367 | 4384.4085 | 4726.8643 | 4463.986  |
| Without changes | 4942.505  | 4942.2135 | 5134.3274 | 4416.553  | 4438.4845 | 4437.9489 |

**Comment by cart** [comment]
Brilliant. Thanks for the rigor here!

**Comment by cart** [comment]
Alrighty finally got around to testing this. Looking good!
image

**Comment by cart** [comment]
I do think i want 3d_scene to stay simple, so I'm thinking at some point we can add a "3d_shapes" example that showcases all of the current shapes bevy supports.

For now this is good!

**Pull request merged**
