### PR TITLE
Create `bevy_shape`

### PR DESCRIPTION
**Pull request by myreprise1**
# Objective

I'm going to start cleaning up the bloated `bevy_render`. This is the first part where I split the `mesh` module. At the moment the `mesh` module has to use `#[allow(clippy::module_inception)]`, for the inelegant `bevy::mesh::mesh` which really isn't ideal for something that could easily become `bevy_mesh` if I just move some files around. I decided to instead move `mesh::shape` for now.

## Solution

- Moved the `mesh::shape` module in `bevy_render` into a new crate called `bevy_shape`.
- Removed the unused `hexasphere` as a dependency of `bevy_render` and added it to `bevy_shape`.
- Removed the `mesh::shape` re-export from the `bevy_render` prelude.

Since I had to remove `shape` from `bevy_render`'s prelude, I:

- Added a feature called `bevy_shape` to `bevy` and added it as a default feature which can be optionally disabled.
- Added the `shape` module to `bevy` and added it to the `prelude`.

This means that when importing the bevy prelude like in the `examples` , `shape` does not have to be used manually, so you can still use `shape::Cube`, `shape::Cylinder`, etc. but `bevy::mesh::shape` is no longer used.

---

## Changelog

- Moved `bevy::mesh::shape` into `bevy::shape`.

## Migration Guide

Replace references to `bevy::mesh::shape` with `bevy::shape`.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Solidly in favor of this. Gets the controversial label because it's a new top-level crate though.

**Review by kurtkuehnert — APPROVED** [review]
I am also strongly in favor of this change. The diff is surprisingly small.
Especially when [RFC 12](https://github.com/bevyengine/rfcs/blob/main/rfcs/12-primitive-shapes.md) is going to be fully implemented this will be necessary IMO.
LGTM

**Review by alice-i-cecile — APPROVED** [review]
I agree with this change too. @aevyrie, opinions?

**Comment by aevyrie** [comment]
The fact that this diff is so small suggests to me that we don't gain anything from turning this module into a crate. It's not preventing compilation from parallelizing, nor is it ubiquitous enough that there is a need to import the module standalone. Even if it was, `bevy_shapes` depends on `bevy_render` which negates the reason for extracting it into a crate in the first place.

If this is being done to make iterative compiles of `bevy_render` itself faster, then we need to consider making crate subdirectories for crates that are actually modules extracted from single crate for compilation time reasons. The `/crates` dir is already quite large

As for RFC 12, those types belong in `bevy_math` with the other shape primitives. `bevy_shape` depending on `bevy_render` prevents us from using the crate for lightweight interop types.

**Comment by cart** [comment]
I appreciate @aevyrie's skepticism as this is taking `bevy_render` in a new direction and the actual "realized wins" are minimal at this point. Before merging, we should find some level of agreement on the direction being taken so we can make these decisions more effectively + consistently in the future.

The pros:
* `bevy_render` is smaller: crates that depend on `bevy_render`, but don't need shapes can now compile "earlier"
* The shape path is shorter `bevy::shape::Cube` vs `bevy::render::mesh::shape::Cube` 
* Shapes become optional. You can opt out if you don't want them. Note that we could do this with the current setup too.
* This _might_ make our docs a bit better. Right now the `shape` module is only searchable via the prelude.

The cons:
* In practice, this doesn't really affect UX meaningfully.
* This adds "crate bloat". Many small crates makes the project harder to navigate and increases boilerplate: more `Cargo.toml`s, longer publish.sh script, bigger `bevy/lib.rs`, etc.
* It also ticks our "dependency count" up by one, but in this specific case as the dependency is in our control the only downside there is "user perception". I don't think its something to worry about here.

Given that `bevy_render` can be a bottleneck (and will likely increasingly be so as we expand with higher level features), I think I'm inclined to go down the "slim down" path, within reason. I think in this case, shapes are not critical for building "render features", so we can break them out without too much thought. But I would _probably_ push back against something like moving the `view` module into its own crate, as that is required when building pretty much any render feature. Which means each render feature has one more crate to import / worry about.

**Comment by alice-i-cecile** [comment]
Primitive shapes have been added to bevy_math. Over time, the remaining shapes should probably end up there too.

**Pull request closed without merging**
