### PR TITLE
[Merged by Bors] - Remove unused code in game of life shader

### PR DESCRIPTION
**Pull request by NiklasEi**
# Objective

- Make `game_of_life.wgsl` easier to read and understand

## Solution

- Remove unused code in the shader
    - `location_f32` was unused in `init`
    - `color` was unused in `update`

### CODE REVIEW

**Review by superdump — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Comment by superdump** [comment]
bors retry

**Comment by superdump** [comment]
bors retry

**Comment by superdump** [comment]
bors retry

**Comment by superdump** [comment]
*sigh*

**Comment by superdump** [comment]
bors retry

**Pull request closed without merging**
