### PR TITLE
Add UV channel selection to StandardMaterial

### LINKED ISSUE #12496: Gltf texture not rendering properly
## Bevy version

Bevy main.

```
AdapterInfo { name: "NVIDIA GeForce 3060", device_type: DiscreteGpu, }
```

## What you did

Tried to use a glb scene exported from unreal.

## What went wrong
 I tried to use it in bevy and the textures looks odd.  Have tried in scene-viewer as well.
 But in GLTF viewer & blender it works well.

## Additional information

In bevy:

Screenshot 2024-03-15 220427

In GLTF viewer
Screenshot 2024-03-15 221437

[wall.glb.zip](https://github.com/bevyengine/bevy/files/14618811/wall.glb.zip)

### LINKED ISSUE #13086: Loading a glTF scene doesn't use the correct UV map for ambient occlusion
## Bevy version

0.13.2 and latest main (9592a40e1eb387f926b787cbb3a65d9db1dfb1a3)

## Relevant system information

```ignore
AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti Laptop GPU", vendor: 4318, device: 9440, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "546.33", backend: Vulkan }
```

## What you did

Load a gltf model with a ambient occlusion lightmap

## What went wrong

| Expected | Actual |
| --- | --- |
| https://gltf-viewer.donmccurdy.com/ | Bevy Scene Viewer Example |
| image | image |

In the example there is a cube mesh and a plane mesh, each with 2 UV maps. One UV map is used for the base colour and one is used for ambient occlusion. The gltf-viewer and three.js read and render the model correctly but not in bevy. The base texture can be seen properly rendered through the broken ambient occlusion texture so I suspect that the ambient occlusion is working but the 2nd UV map is not being used or being read incorrectly.

## Additional information

Model used to test: [gltf_model.zip](https://github.com/bevyengine/bevy/files/15097983/gltf_model.zip)

### LINKED ISSUE #13122: Incorrect UV map used when using Lightmap component
## Bevy version

0.13, main

## Relevant system information

```ignore
`AdapterInfo { name: "AMD Radeon RX 7900 XT", vendor: 4098, device: 29772, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "23.12.1 (LLPC)", backend: Vulkan }`
```

## What you did

See https://github.com/GitGhillie/bake_repro for code and blend files. Basically:
- Create plane and cube in Blender
- Add a simple texture to both (issue also occurs without textures)
- Bake lighting
- Export gltf

## What went wrong

The Bevy render looks awful, probably due to using the wrong UVs:
image

Using an online gltf viewer it looks correct, so I'm pretty sure it's something on the Bevy side:
image

## Additional information

Related Discord help thread: https://discord.com/channels/691052431525675048/1224462995875168426/1224462995875168426

### PR DESCRIPTION
**Pull request by geckoxx**
# Objective

- The StandardMaterial always uses ATTRIBUTE_UV_0 for each texture except lightmap. This is not flexible enough for a lot of gltf Files.
- Fixes #12496
- Fixes #13086
- Fixes #13122
- Closes #13153

## Solution

- The StandardMaterial gets extended for each texture by an UvChannel enum. It defaults to Uv0 but can also be set to Uv1.
- The gltf loader now handles the texcoord information. If the texcoord is not supported it creates a warning.
- It uses StandardMaterial shader defs to define which attribute to use.

## Testing

This fixes #12496 for example:
wall_fixed

For testing of all kind of textures I used the TextureTransformMultiTest from https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/TextureTransformMultiTest
Its purpose is to test multiple texture transfroms but it is also a good test for different texcoords.
It also shows the issue with emission #13133.

Before:
TextureTransformMultiTest_main

After:
TextureTransformMultiTest_texcoord

### CODE REVIEW

**Comment by geckoxx** [comment]
Added the same support for clearcoat textures and using shader defs instead of material flags.

**Comment by bugsweeper** [comment]
@geckoxx You should add "Closes #13153" to your description

**Comment by robtfm** [comment]
just a quick note about the shader defs - we could alternatively use indexes/bits in the material data to specify the uv indexes and avoid a proliferation of shader variants.

i think defs are probably better because 
- it will have no cost in the base case where only 1 set of texcoords are used
- if you do need to use multiple sets, you likely have them all in the same locations, so only one variant would be needed
- if they are not in the same locations, if you control the assets and you care enough, you can modify your assets to align them

whereas using data in the material would increase its size having a (marginal) effect on all uses of `StandardMaterial`, whether you want the flexibility or not.

**Review by mockersf — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Thank you to everyone involved with the authoring or reviewing of this PR! This work is relatively important and needs release notes! Head over to https://github.com/bevyengine/bevy-website/issues/1313 if you'd like to help out.

**Pull request merged**
