### PR TITLE
[Merged by Bors] - Fix end-of-animation index OOB

### LINKED ISSUE #6204: index out of bounds : for animation_player, irregular bug
## Bevy version

stable 0.8.0 release 

```ignore
AdapterInfo { name: "NVIDIA GeForce GTX 1080 Ti", vendor: 4318, device: 6918, device_type: DiscreteGpu, backend: Vulkan }
```

## What you did

Running a bunch of gltf animations. I change speed, animation clip very often.

## What went wrong

I get the panic error at random but after a while of running my game. 

One of my animations is 111 long but the error have occurred on other animations as well.

Error:

thread 'Compute Task Pool (4)' panicked at 'index out of bounds: the len is 111 but the index is 111', /home/pinkponk/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_animation-0.8.1/src/lib.rs:252:38
thread 'main' panicked at 'task has failed', /home/pinkponk/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/task.rs:426:45

## Additional information
Bevy code, animation_player
```
                        // Find the current keyframe
                        // PERF: finding the current keyframe can be optimised
                        let step_start = match curve
                            .keyframe_timestamps
                            .binary_search_by(|probe| probe.partial_cmp(&elapsed).unwrap())  <--- Problem probably here
                        {
                            Ok(i) => i, <-------------------------------------------------------------------------------- And here
                            Err(0) => continue, // this curve isn't started yet
                            Err(n) if n > curve.keyframe_timestamps.len() - 1 => continue, // this curve is finished
                            Err(i) => i - 1,
                        };
                        let ts_start = curve.keyframe_timestamps[step_start];
                        let ts_end = curve.keyframe_timestamps[step_start + 1]; <--------------------- Error here
                        let lerp = (elapsed - ts_start) / (ts_end - ts_start);
```

discord help thread: https://discord.com/channels/691052431525675048/1019697973933899910/threads/1026824382418522162

### PR DESCRIPTION
**Pull request by thebluefish**
# Objective

Fixes #6204

## Solution

Added another branch to handle end-of-animation special case

### CODE REVIEW

**Comment by thebluefish** [comment]
So I'm actually unsure if this was the best way to write that line as the binary search could only ever return *at most* the final index - same with the `Err(n)` check.

**Comment by alice-i-cecile** [comment]
> So I'm actually unsure if this was the best way to write that line as the binary search could only ever return at most the final index - same with the Err(n) check.

IMO it's better to code defensively; this behavior may change in the future, so we should be robust to being passed bad data here.

**Comment by mockersf** [comment]
> IMO it's better to code defensively

In this case it's defensive coding against Rust std...

Checking for equality could be faster

**Comment by alice-i-cecile** [comment]
Could we use more robust error handling than indexing downstream too? I try to avoid it, precisely because it subtly panics.

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Pull request closed without merging**
