### PR TITLE
Support optional far-plane culling

### LINKED ISSUE #4596: The `far` member of `PerspectiveProjection` is irrelevant
The `far` member of `PerspectiveProjection` is irrelevant, because the far plane is at negative infinite Z

https://github.com/bevyengine/bevy/blob/989fb8a78d2ca6e3fe6fb1ccd7d79ea88868b8c7/crates/bevy_render/src/camera/projection.rs#L25

### PR DESCRIPTION
**Pull request by superdump**
# Objective

- Support optional far-plane culling for perspective projections
- Fixes #4596 

## Solution

- Make the `PerspectiveProjection` `far` member into an `Option<f32>`
  - If it is set to `None`, do not frustum cull meshes against the far plane
  - If it is set to `Some(f32)`, frustum cull against that value
  - Default to `Some(1000.0)`

---

## Changelog

- Changed: `PerspectiveProjection` `far` became an `Option<f32>` to support optional far-plane frustum culling, with a default of `Some(1000.0)` and so far-plane culling is enabled.

## Migration Guide

In 0.7, this would not do far-plane frustum culling of meshes, only of lights:
```rust
PerspectiveProjection {
    far: 1000.0,
    ..default()
}
```

In 0.8, this will do far-plane frustum culling of meshes and lights (also this is the new default behavior):
```rust
PerspectiveProjection {
    far: Some(1000.0),
    ..default()
}
```

To disable far-plane frustum culling for meshes (still enabled for lights using a value of 1000.0):
```rust
PerspectiveProjection {
    far: None,
    ..default()
}
```

## Open questions

- Should there be separate optional far planes for lighting and meshes?

### CODE REVIEW

**Review by IceSentry — APPROVED** [review]

**Comment by IceSentry** [comment]
Not sure what the conflicts are, but the code looks good assuming the conflicts are fixed

**Comment by Rigidity** [comment]
This would be really nice to have so we can clip the far plane in games to hide world loading, for example chunks in voxel worlds.

**Comment by rodolphito** [comment]
I dont think having a far plane clip is desirable as it introduces visible view-dependent culling, because the corners of the screen are farther from the camera than the center. far culling should be done by distance to the camera to avoid objects popping in and out of view as you turn the camera.

ideally, this would be solved by an LOD system that cascaded detail proportional to screen area occupied by an object, and at a certain cutoff simply stopped rendering. if an entire mesh takes up less than a pixel it should probably be culled.

this also depends on fog: if theres a distance at which fog is 100% solid then everything past that should be culled regardless of size

**Comment by JMS55** [comment]
Superseded by #8205

**Pull request closed without merging**
