### PR TITLE
[Merged by Bors] - Release Checklist

### PR DESCRIPTION
**Pull request by alice-i-cecile**
To help make the process easier and more fool-proof, aid delegation and document institutional knowledge.

I'm not entirely sure where this belongs.

### CODE REVIEW

**Review by ZaMaZaN4iK — APPROVED** [review]

**Comment by cart** [comment]
Love this. I think this should probably go in the `docs` section. `.github` is for github config/automation. Also, can we rename it to `release_checklist.md`?

**Comment by NiklasEi** [comment]
At least the 0.5 update was also linked in "This Week in Rust"

**Comment by alice-i-cecile** [comment]
Done, done and done. Ready to merge!

**Pull request closed without merging**
