### PR TITLE
Added bevy_transform::component::local_space::LocalSpace

### LINKED ISSUE #1780: Allow specifying which transform components are relative to the parent, and which are global
## What problem does this solve or what need does it fill?

An example use case is a tank with a child turret entity.  The turret should inherit location and scale from the tank, but should rotate independently.

## What solution would you like?

I believe this can be implemented by adding a new optional component to the turret:

```rust
TransformDescriptor {
    translation: Local,
    rotation: Global,
    scale: Local
}
```

The `transform_propagate_system` could then look for this component and update the `GlobalTransform` accordingly.

_Note: I don't really like the name `TransformDescriptor` - can anyone think of better?_

## What alternative(s) have you considered?

There are two alternatives:
- Query for the parent's transform and subtract that from the turret's transform
- Parent both the tank and the turret to an empty, and use that for translation and scale.

Both of these are painful to use and don't take advantage of the ECS.

## Additional context

This is a feature that UE4 has

### LINKED ISSUE #3025: Lock values of transforms.
## What problem does this solve or what need does it fill?

Imagine adding a child entity to a parent, and you want the child to have the position updated but don't want it to update rotation. I would like a way to do, by locking certain parts of the transform.

## What solution would you like?

I propose a bitmask for disabling updates to translation, rotation and scale. Constants can be added to `Transform` like `MASK_TRANSLATION_X` to turn on/off flags. Whenever the system that updates transforms is called, it can check the mask before updating it. I'm not sure about the performance impact, how it would add up for large numbers of entities.

## What alternative(s) have you considered?

A byte is the smallest value we can use to store this. However, it can be given a generic name like `mask` and be used in the future for adding any other features. `if` statements aren't necessary for the update code, a simple AND statement and you can multiply the result by the updated field, effectively canceling it, like so: `transform.x = update.x * (transform.mask & MASK_TRANSLATION_X)` though, I don't actually know if this is what is happening.

## Additional context

I am using this for bevy_atmosphere. I wanted to attach a child entity for the skybox (to make it more flexible for cases such as local split-screen multiplayer) but since the rotation keeps moving, I would have to cancel it out with a system. This would improve performance in those cases.

### PR DESCRIPTION
**Pull request by JonahPlusPlus**
Relation describes the relationship between parent and child transforms.

# Objective

- Have a flexible way of describing how changes to a parent's `Transform` affect a child
- Fix #3025 
- Fix #1780 

## Solution

- `Relation` is a component that can be added to children, meaning different children can have different relationships to the parent
- It has three fields for translation, rotation and scale, which are optional, where `None` would mean there is no relationship
- `Some` can hold a `fn(_: &mut Vec3)` (in the case of translation and scale, rotation is a `Quat`), which allows assigning a closure that can modify a clone of the parent's field
- By default, fields aren't `None` but `Some(|_| ())`, which means to use the relationship that is already implemented, 1:1. This allows for users to set one part of the `Relation` and use `..Default::default()` for the rest

### Alternatives

- I had a hard time naming this, Relation might be too generic, IDK
- Instead of having separate fields for translation, rotation and scale, it's possible to just use one closure that takes a clone of the parent's transform, however, I felt that using separate `Option`s allowed for users to write less code, as they would have to set fields to 1.0 if it used a transform compared to just setting it to `None` in what I believe would be common cases like turning off rotation or scale. Could use some more insight/research.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
> I could change the name to `TransformMap`, as long as that's not too long.

Sounds good to me.

**Comment by JonahPlusPlus** [comment]
Actually changed the name to `LocalSpace`, since it better reflects the behavior you can get from using matrices, rather than function pointers.

**Comment by JonahPlusPlus** [comment]
I also removed `Option` since I couldn't figure out how to get the alternative behavior I was looking for without making complicated changes to the internals. For example: rotating the parent to change the position of the child but locking the orientation of the child isn't possible right now. Otherwise, I think this good for most use cases.

**Comment by HackerFoo** [comment]
@JonahPlusPlus could you please add some motivation to the PR description? What problem was this designed to address? If this is not a common problem, I think it would be better for the user to add a separate system and component to describe the relative movement (which should listed as an alternative.) I use something like this to manage a transform that only applies to one type of entity, so I can pretend to move the camera without affecting other meshes that are part of the interface. Using the hierarchy for this would have been a pain.

**Comment by HackerFoo** [comment]
I guess this is one, but it seems pretty specific:

> An example use case is a tank with a child turret entity. The turret should inherit location and scale from the tank, but should rotate independently.

**Comment by JonahPlusPlus** [comment]
@HackerFoo I'll admit it, it really is useful for more niche cases, but I think that's also why it's so useful, since it can be applied to a variety of niche cases. I think the main use cases though would be animation and constraints. [Example](https://discord.com/channels/691052431525675048/692648638823923732/903738219298967573)

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Relation can't be used here; it conflicts with the usage in #3742. I also think that this design space is highly controversial.

My feeling is that this needs to be addressed as part of an RFC tackling the hierarchy management.

**Pull request closed without merging**
