### PR TITLE
Rewrite WgpuRenderGraphExecutor::execute with iterators to allow rayon parallelization down the line

### PR DESCRIPTION
**Pull request by lachlansneff**
This pr rewrites `WgpuRenderGraphExecutor::execute` with iteration combinators to allow for parallelization with rayon. Currently, the render graph cannot be parallelized because of memory leaks (probably from wgpu), but when the leak is fixed, a few lines can be uncommented and the render graph will be executed in parallel.

### CODE REVIEW

**Comment by CleanCut** [comment]
@lachlansneff The async task system was included in [bevy 0.2](https://bevyengine.org/news/bevy-0-2/). Time to brush this off and update it?

**Comment by Moxinilian** [comment]
Hey @lachlansneff! Thank you for the PR. Do you think the PR can be updated to use bevy_tasks? If not, maybe we can close it.

**Comment by NathanSWard** [comment]
This PR is quite old and hasn't had any updates recently. 
If it's ok with others (ping @alice-i-cecile @mockersf) it's probably safe to close this PR.

**Comment by NathanSWard** [comment]
Closing this issue as discussed [here](https://discord.com/channels/691052431525675048/692572690833473578/858045924484055080).
This is mostly I'm favor of the new 0.6 renderer rework.

Please feel free to reopen if I'm incorrect or future development spawns from this PR :)

**Pull request closed without merging**
