### PR TITLE
Fix `alien_cake_addict` example

### LINKED ISSUE #15729: alien_cake_addict example lighting issues
## Bevy version

e7b83ac

## Relevant system information

```ignore
SystemInfo { os: "Linux 24.05 NixOS", kernel: "6.6.34", cpu: "AMD Ryzen 7 5800X 8-Core Processor", core_count: "8", memory: "31.2 GiB" }
AdapterInfo { name: "NVIDIA GeForce RTX 3060 Ti", vendor: 4318, device: 9353, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "550.78", backend: Vulkan }
```

## What you did

```ingore
cargo r --example alien_cake_addict
```

## What went wrong

At first the lighting is fine, but after losing the game and starting again by pressing space on the game over screen the lighting is messed up.

Here is a video showing it: https://youtu.be/dLpKSMGyS-M

### PR DESCRIPTION
**Pull request by BenjaminBrienen**
# Objective

Fixes #15729

## Solution

Use the state-scoped pattern.

## Testing

Tested manually. See the showcase.

---

## Showcase

https://github.com/user-attachments/assets/14ffefca-40c6-4c7e-b15b-f92466a2b0a5

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Much nicer, in addition to fixing the bug!

**Review by LiamGallagher737 — APPROVED** [review]
Worked locally for me and the code is also an improvement

**Comment by rparrett** [comment]
I am missing something. Could you help me understand the underlying bug and why these changes fix it?

**Comment by BenjaminBrienen** [comment]
> I am missing something. Could you help me understand the underlying bug and why these changes fix it?

The lighting bugs out due to too many entities being despawned. See the video in the issue.

**Review by rparrett — APPROVED** [review]

**Pull request merged**
