### PR TITLE
Fix Ci failing over dead code in tests

### LINKED ISSUE #12620: CI is failing on Rust 1.77
## Bevy version

`main` @ https://github.com/bevyengine/bevy/commit/7b842e373e990445ffb57d5f2fa97786d6d5acdb

## Problem

CI is failing on innocuous PRs: see https://github.com/bevyengine/bevy/commit/7b842e373e990445ffb57d5f2fa97786d6d5acdb for example.

```
error: field `0` is never read
   --> crates/bevy_asset/src/server/loaders.rs:311:14
    |
311 |     struct A(usize);
    |            - ^^^^^
    |            |
    |            field in this struct
    |
    = note: `A` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
    = note: `-D dead-code` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(dead_code)]`
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
    |
311 |     struct A(());
    |              ~~

error: field `0` is never read
```

Similarly, we're getting reports [on Discord](https://discord.com/channels/691052431525675048/692572690833473578/1220385676198019173) about lint failures elsewhere in `bevy_winit`.

These problems all look real (if trivial), this seems to just be the standard "new Rust version shipped lints that weren't caught earlier in CI".

### PR DESCRIPTION
**Pull request by Brezak**
# Objective

Fix Pr CI failing over dead code in tests and main branch CI failing over a missing semicolon. Fixes #12620.

## Solution

Add dead_code annotations and a semicolon.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by Brezak** [comment]
Should work now. I'll investigate a better solution when CI works again.

**Comment by alice-i-cecile** [comment]
Looks like we need to bless the new output of the compile-fail tests too.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Another compile-fail failure in https://github.com/bevyengine/bevy/actions/runs/8378534423/job/22943464592?pr=12623#step:6:261.

I've opened https://github.com/bevyengine/bevy/issues/12627 to see how we can make this less brittle.

**Comment by Brezak** [comment]
Either I'm doing something wrong or the errors rustc emits look different between Windows and Linux. Blessing the tests locally keeps failing so I've resorted to just copy pasting the expected output from the CI log.

**Comment by Brezak** [comment]
If this works now then the issue was that I forgot to add a newline to the end of the missing_deref.fail.stderr file when copying the CI output.

**Comment by Brezak** [comment]
It works!!!. I'm sorry it took so long.

**Review by matiqo15 — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
> It works!!!. I'm sorry it took so long.

No, this was very speedy! Much appreciated: it's a real chore to fix these failures and I love it when contributors tackle them.

**Comment by mockersf** [comment]
> Either I'm doing something wrong or the errors rustc emits look different between Windows and Linux. Blessing the tests locally keeps failing so I've resorted to just copy pasting the expected output from the CI log.

Yup it's https://github.com/bevyengine/bevy/issues/8962, somehow the output differs depending on your OS...

**Pull request merged**
