### PR TITLE
bevy_reflect incorrectly looks for bevy in dev-deps

### PR DESCRIPTION
**Pull request by Moxinilian**
When trying to determine how it should mention itself in derive macros, the crate finder incorrectly assumes it can use `bevy::reflect` if bevy is available as a dev dependency. This PR fixes this behavior by ignoring dev-dependencies.

### CODE REVIEW

**Comment by Moxinilian** [comment]
After giving it some thought I realized this means bevy_reflect will no longer work in situations in which examples need bevy_reflect only as a dev dependency. I need to change this.

**Comment by cart** [comment]
Hmm isn't this effectively a no-op change?

How is accepting both dev and normal deps different from first accepting normal, then falling back to dev?

**Comment by Moxinilian** [comment]
Consider the following:

```toml
[dependencies]
bevy_reflect = "*"

[dev-dependencies]
bevy = "*"
```
Originally, the first case will incorrectly use `bevy::reflect` in the main crate code, whereas here it will correctly pick up `bevy_reflect` in all cases (as it is always available).

Now consider the following:
```toml
[dependencies]
# nothing

[dev-dependencies]
bevy = "*"
```
Without the dev-deps fallback, bevy would not be located if the examples use bevy::reflect.

**Comment by cart** [comment]
Ah right. I wasn't considering the case where you have the full bevy crate _and_ a subcrate.

**Pull request merged**
