### PR TITLE
[Merged by Bors] - many_cubes: Add a cube pattern suitable for benchmarking culling changes

### PR DESCRIPTION
**Pull request by superdump**
# Objective

- Add a cube pattern to `many_cubes` suitable for benchmarking culling changes

## Solution

- Use a 'golden spiral' mapped to a sphere with the strategy of optimising for average nearest neighbour distance, as per: http://extremelearning.com.au/how-to-evenly-distribute-points-on-a-sphere-more-effectively-than-the-canonical-fibonacci-lattice/

### CODE REVIEW

**Comment by superdump** [comment]
While investigating:
* #3796
I wanted a 3D benchmark to test with. The recent changes to many_cubes seemed promising. However, the pattern of placing cubes on the surface of a large cube produce view-dependent number of visible meshes. This was intended to demonstrate frustum culling is working properly. I needed something more consistent so I found an algorithm for reasonably evenly distributing the cubes on the surface of a sphere. This does indeed maintain the number of visible meshes at fairly consistent numbers, making it more suitable for benchmarking changes to the culling and visibility systems.

**Comment by superdump** [comment]
Screenshot 2022-03-07 at 01 05 34

**Review by alice-i-cecile — APPROVED** [review]
Well-motivated, code quality is solid. This is also very pretty! 

Should we consider moving this and bevymark to their own folder? They're not exactly useful as learning material IMO.

**Comment by superdump** [comment]
> Should we consider moving this and bevymark to their own folder? They're not exactly useful as learning material IMO.

I think it could be useful to have a place for tests/benchmarks that exercise various aspects of the engine and enable developers to test/check things without having to (re)write the same things over and over. At least I find I’m very commonly using examples, possibly slightly modified, for testing various things during development. I also think we should make a gltf viewer out of load_gltf and a flying camera implementation like that in the shadow biases example. But that’s all off topic for the PR. :)

**Comment by alice-i-cecile** [comment]
Agreed; we should consider that in a separate PR I think.

**Comment by mockersf** [comment]
Could more people test this example to ensure it doesn't cause dizziness or discomfort?

> Should we consider moving this and bevymark to their own folder? They're not exactly useful as learning material IMO.

`bevy_mark`, `many_sprites`, `many_cubes`, `text_debug` and `font_atlas_debug` come to mind. But yes, another PR 🙂

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
@superdump could you also update the few `..Default::default()` that slipped through in the last PR on that example to the new `..default()`?

**Comment by superdump** [comment]
> @superdump could you also update the few `..Default::default()` that slipped through in the last PR on that example to the new `..default()`?

Done.

**Comment by alice-i-cecile** [comment]
bors try

**Comment by superdump** [comment]
bors try

**Comment by superdump** [comment]
Oh, I thought the test progress would be shown at the bottom and it had failed again. I see the status is elsewhere.

**Comment by alice-i-cecile** [comment]
We had a couple sets of eyes on this for nausea, and this is a very niche example. We can tweak it later if we get complaints.

**Pull request closed without merging**
