### PR TITLE
Fix ClearColor in 2d pipelines

### LINKED ISSUE #13377: Setting ClearColor doesn't work
## Bevy version

Tested on the main branch

## Relevant system information

Tested on

```ignore
`AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`
```

## What you did

I run the `clear_color` example, and it shows always black, without changing to purple when pressing space.

I did some bisect, and it appeared for the first time after [this](64e1a7835a7461924a94bda3e920596b7ce439d9).

### PR DESCRIPTION
**Pull request by pietrosophya**
# Objective

- Fixes #13377
- Fixes https://github.com/bevyengine/bevy/issues/13383

## Solution

- Even if the number of renderables is empty, the transparent phase need to run to set the clear color.

## Testing

- Tested on the `clear_color` example

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by IceSentry** [comment]
> Why transparent, and not opaque?

Because not enough people have reviewed my opaque 2d work yet https://github.com/bevyengine/bevy/pull/13069

**Comment by alice-i-cecile** [comment]
This appears to have the same root cause as #13383. @IceSentry is [working on a fix](https://discord.com/channels/691052431525675048/866787577687310356/1240395912598130769).

**Review by IceSentry — APPROVED** [review]

**Comment by IceSentry** [comment]
@alice-i-cecile this is the only fix needed, so this can be merged

**Comment by IceSentry** [comment]
The real fix will be to have an opaque pass, but that's a lot more work

**Comment by IceSentry** [comment]
Actually, @pietrosophya could you add the `if !transparent_phase.items.is_empty()` check around the `transparent_phase.render(&mut render_pass, world, view_entity);` line? That would be more correct.

Like this:

```rust
if !transparent_phase.items.is_empty() {
	transparent_phase.render(&mut render_pass, world, view_entity);
}
```

Realistically, it doesn't really matter because that means it's just running an empty scene anyway, but it still makes a bit more sense.

**Comment by pietrosophya** [comment]
Done! 😉

**Comment by alice-i-cecile** [comment]
Awesome, thank you all very much! Nice to clean up one of the larger open bugs in the milestone.

**Pull request merged**
