### PR TITLE
[Merged by Bors] - Add window resizing example

### PR DESCRIPTION
**Pull request by Weibye**
# Objective

- Adopted from #3836
- Example showcases how to request a new resolution
- Example showcases how to react to resolution changes

### CODE REVIEW

**Review by TimJentzsch — APPROVED** [review]
Would be nice to add a video/GIF/screenshot of the example to the PR description, but the code makes sense to me :)

**Comment by Weibye** [comment]
> Would be nice to add a video/GIF/screenshot of the example to the PR description, but the code makes sense to me :)

My screen-recorder _really_ does not like recording a window that changes in size. This is likely best tested if you check out the code 🙃

**Comment by TimJentzsch** [comment]
> > Would be nice to add a video/GIF/screenshot of the example to the PR description, but the code makes sense to me :)
> 
> My screen-recorder _really_ does not like recording a window that changes in size. This is likely best tested if you check out the code 🙃 

Hmm right, that would probably only work if you record the whole screen. But no worries, it's fine as long as it works locally :)

**Pull request closed without merging**
