### PR TITLE
remove bevy_utils::{default, prelude}

### LINKED ISSUE #15342: Remove `bevy_utils::default`
## What problem does this solve or what need does it fill?

Minimize `bevy_utils`. #11478

## What solution would you like?

Remove the `default` module.
The `prelude` module should also be removed because it will then be empty. The breaking change is practically the same breaking change.

## Additional context

There are some manual `impl Default`s that could probably be simplified to just the derive macro.

### PR DESCRIPTION
**Pull request by BenjaminBrienen**
# Objective

- End goal: #11478

## Solution

- Change references to `bevy_utils::default` to `Default::default`.
- Remove use statements.
- Remove empty prelude.

## Testing

- Local CI

## Migration Guide

- If using `bevy_utils::default`, stop. :)

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
@cart rather likes this style, and deliberately included it. IMO there's zero chance this is merged before the new `bsn!` macro drops, and little chance after it. I suspect that removing this will require a syntax improvement to Rust itself.

**Comment by BenjaminBrienen** [comment]
> @cart rather likes this style, and deliberately included it. IMO there's zero chance this is merged before the new `bsn!` macro drops, and little chance after it. I suspect that removing this will require a syntax improvement to Rust itself.

Would it not work to put `Default::default` in the bevy_internal prelude?

**Comment by alice-i-cecile** [comment]
> Would it not work to put Default::default in the bevy_internal prelude?

Hmm, this might work. I think that would be a lot more palatable, and still shrink bevy_utils.

**Comment by alice-i-cecile** [comment]
Closing per https://github.com/bevyengine/bevy/issues/11478#issuecomment-2364785282

**Pull request closed without merging**
