### PR TITLE
Make "fast builds" config 40% faster on mac

### PR DESCRIPTION
**Pull request by ashneverdawn**
This uses https://github.com/michaeleisel/zld which makes incremental builds roughly 40% faster on mac.

### CODE REVIEW

**Comment by lachlansneff** [comment]
Woot woot!

**Comment by ashneverdawn** [comment]
After doing the math properly, it was more like 58% faster. (34s -> 24s on 2014 mac with 2.6 GHz Dual-Core Intel Core i5) 😄

**Comment by cart** [comment]
This is a big win. Would you mind updating The Bevy Book setup guide too?

https://github.com/bevyengine/bevy-website/blob/master/content/learn/book/getting-started/setup/_index.md

**Comment by ashneverdawn** [comment]
https://github.com/bevyengine/bevy-website/pull/16

**Comment by CleanCut** [comment]
I must be doing something wrong. I tried replicating this exact config, but I see absolutely no difference in compile times: https://github.com/CleanCut/bevy_template/pull/1

**Comment by stefee** [comment]
We should put out some sort of announcement on Discord for people on macOS to update their `config` file from the latest template.

**Comment by CleanCut** [comment]
I still haven't been able to reproduce the speedup. 😢

**Comment by CleanCut** [comment]
Update: Thanks to @ashneverdawn's collaboration, I was able to confirm a 15% increase in build time. For more details see https://github.com/CleanCut/bevy_template/pull/1#issuecomment-679339965

**Pull request merged**
