### PR TITLE
[Merged by Bors] - `Query` filter types must be `ReadOnlyWorldQuery`

### PR DESCRIPTION
**Pull request by targrub**
# Objective

Fixes Issue #6005.

## Solution

Replaced WorldQuery with ReadOnlyWorldQuery on F generic in Query filters and QueryState to restrict its trait bound.

## Migration Guide

Query filter (`F`) generics are now bound by `ReadOnlyWorldQuery`, rather than `WorldQuery`. If for some reason you were requesting `Query<&A, &mut B>`, please use `Query<&A, With<B>>` instead.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Can you change your PR to description to something a bit more descriptive and add a quick migration guide section?

**Comment by alice-i-cecile** [comment]
Many of these changes seem unrelated; looks like a rebasing issue?

**Comment by alice-i-cecile** [comment]
Code changes LGTM now!

For the title, can you put "Query filter types must be `ReadOnlyWorldQuery`".

For the migration guide, how about:

## Migration Guide

Query filter (`F`) generics are now bound by `ReadOnlyWorldQuery`, rather than `WorldQuery`. If for some reason you were requesting `Query<&A, &mut B>`, please use `Query<&A, With<B>>` instead.

**Review by TheRawMeatball — APPROVED** [review]

**Review by inodentry — APPROVED** [review]

**Pull request closed without merging**
