### PR TITLE
Fix `CameraProjection` panic and improve `CameraProjectionPlugin`

### PR DESCRIPTION
**Pull request by doonv**
# Objective

Fix https://github.com/bevyengine/bevy/issues/11799 and improve `CameraProjectionPlugin`

## Solution

`CameraProjectionPlugin` is now an all-in-one plugin for adding a custom `CameraProjection`. I also added `PbrProjectionPlugin` which is like `CameraProjectionPlugin` but for PBR. 

P.S. I'd like to get this merged after https://github.com/bevyengine/bevy/pull/11766.

---

## Changelog

- Changed `CameraProjectionPlugin` to be an all-in-one plugin for adding a `CameraProjection`
- Removed `VisibilitySystems::{UpdateOrthographicFrusta, UpdatePerspectiveFrusta, UpdateProjectionFrusta}`, now replaced with `VisibilitySystems::UpdateFrusta`
- Added `PbrProjectionPlugin` for projection-specific PBR functionality.

## Migration Guide

`VisibilitySystems`'s `UpdateOrthographicFrusta`, `UpdatePerspectiveFrusta`, and `UpdateProjectionFrusta` variants were removed, they were replaced with `VisibilitySystems::UpdateFrusta`

### CODE REVIEW

**Comment by doonv** [comment]
This is now unblocked since #11766 has been merged.

**Review by NthTensor — COMMENTED** [review]
Code looks like a big improvement. Will approve later after I get the chance to evaluate this on examples.

**Comment by Zoomulator** [comment]
@doonv I did a rebase and fixed conflicts if you'd like to reset this PR to it.
https://github.com/ludospex/bevy/tree/fix-cameraprojection-crash

Notable conflicts:
- `CameraProjectionPlugin<T>` got new trait bounds `T: CameraProjection + Component + GetTypeRegistration`
- `CameraUpdateSystem` struct definition was moved to the line below `CameraProjectionPlugin`
- `check_visibility` is now generic `check_visibility::<WithMesh>` (`view/visibility/mod.rs`)

**Review by Zoomulator — APPROVED** [review]
Been running this in my own bevy fork for my game and it's been working well with my custom projection + pbr shadows. No complaints :)

**Review by Zoomulator — APPROVED** [review]
Looks good! Well spotted to not need the `check_visibility.after` given the recently added `.before(CheckVisibility)` above.

**Review by NthTensor — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Pull request merged**
