### PR TITLE
[Merged by Bors] - add an example using UI & states to create a game menu

### PR DESCRIPTION
**Pull request by mockersf**
adds an example using UI for something more related to a game than the current UI examples.

Example with a game menu:
* new game - will display settings for 5 seconds before returning to menu
* preferences - can modify the settings, with two sub menus
* quit - will quit the game

I wanted a more complex UI example before starting the UI rewrite to have ground for comparison

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
So, the other thing that you should consider adding is pulling in assets to use as images for the buttons. This is an important and non-trivial part of any UI, and I want to see how it works.

**Comment by mockersf** [comment]
> My only serious complaint is that the `despawn_scene::<T>` pattern is super high on boilerplate; I would like to eat some perf loss in order to avoid that by just filtering over the "where did this come from" components linearly.

In my own code, I actually name all the tag struct the same for each screen / scene, and scope it to a module so each is unique. I worried this would make it harder to read in a single file example

**Comment by mockersf** [comment]
> So, the other thing that you should consider adding is pulling in assets to use as images for the buttons. This is an important and non-trivial part of any UI, and I want to see how it works.

it depends what you mean by that:
- using an image directly as a button, or inside the button, very simple
- using an image as a button background that scales as the button needs, this gets complicated if the image has any kind of details that doesn't scale the same way horizontally / vertically, or some parts that should stay the same. One way to do that is called 9-patch files, and is not built in Bevy (yet) and why I wrote and use https://crates.io/crates/bevy_ninepatch. But has it adds more hierarchy to the UI, you can hit perf issues very quickly

**Comment by mockersf** [comment]
added 3 basic icons with a small trick on how to position them nicely (from my eye anyway)

**Comment by djeedai** [comment]
> I added some comments, but I guess there could still be some more.
> 
> I think it's probably best to open a PR once this one is merged, if you open a PR on this one it will be harder for other reviewer to take part in the process. Don't hesitate if you see other examples that could have more comments!

Will do, thanks for the comments already added!

**Pull request closed without merging**
