### PR TITLE
Update color and naming for consistency

### PR DESCRIPTION
**Pull request by aevyrie**
The `ClearColor` PR was merged before I was quite finished. This fixes a few errors, and addresses Cart's feedback about the pixel perfect example by updating the sprite colors to match the existing bevy bird branding colors.

image

### CODE REVIEW

**Comment by aevyrie** [comment]
02ce409 reverts the plane color change in #10339 to address some passive aggressive comments on discord.

image
image
image

**Review by cart — APPROVED** [review]

**Comment by cart** [comment]
Much appreciated!

**Review by alice-i-cecile — APPROVED** [review]
Sorry, thought you were done!

**Comment by aevyrie** [comment]
No worries, I didn't do a good job of communicating that. :)

**Pull request merged**
