### PR TITLE
[Merged by Bors] - Increase the `MAX_DIRECTIONAL_LIGHTS` from 1 to 10

### PR DESCRIPTION
**Pull request by kurtkuehnert**
# Objective

Currently we are limiting the amount of direction lights in a scene to one.

## Solution

Increase the amount of direction lights from 1 to 10. 
This still is not a perfect solution, but should unblock many use cases.
We could probably just store the directional lights similar to the point lights in an storage buffer, allowing for an variable amount of directional lights.

### CODE REVIEW

**Comment by cart** [comment]
Have you tested this in WebGL? I vaguely remember there being a restriction there, but maybe I'm mistaken.

**Comment by Ku95** [comment]
> Have you tested this in WebGL? I vaguely remember there being a restriction there, but maybe I'm mistaken.

No I have not, I am not sure how to compile and test on WebGL. Hopefully @superdump knows more. 
I do not think we are exceeding the uniform size limit, so I am not sure what the issue could be.
But I am wondering why this value was not set higher to begin with, all the code was already in place.

**Comment by mockersf** [comment]
doesn't work in wasm:
```
panicked at 'wgpu error: Validation Error

Caused by:
    In Texture::create_view
      note: label = `directional_light_shadow_map_texture_view`
    TextureView array layer count + base array layer 2 must be <= Texture depth/array layer count 1
```

#5900 would let us have a different const value in the shader 🥷

**Comment by robtfm** [comment]
this should work if you add a check to render\light.rs @ 1120 to make sure the number of shadow-enabled directional lights does not exceed `directional_shadow_maps_count` defined @ 811 (which is already capped at 1 for webgl).

you might also need to sort the directional lights to get the chosen shadow-caster to be stable.

**Comment by Ku95** [comment]
Thanks for your ideas. 

I have now added errors if spot/directional lights exceeds the maximum supported amount.
This should simply disable their shadows if the maximum is surpassed.

I think this is pretty much what @robtfm recommended. 

Do you think it would be a good idea to separate the directional lights into their own uniform/storage buffer in a follow up PR or are they simply to few to really matter?

**Comment by robtfm** [comment]
i don't think we should disable all the directional+spotlight shadow maps when the max is exceeded. i would prefer to leave the count calculations as they were and just add the `(index < directional_shadow_map_count)` condition to the flag set. that should work correctly and just render as many shadow maps as the platform supports.

the errors will be emitted every frame and are not really "errors"... i would suggest either silently ignoring them (that would be my pref for the shadow map count warning, it's the same treatment as point light shadows), or using a warning and a Local<bool> to check if the warning has already been emitted similar to in `assign_lights_to_clusters` (my pref for the directional light count warning).

**Comment by robtfm** [comment]
tested win32 and wasm, looks good to me

**Review by cart — APPROVED** [review]
Looks good to me!

**Pull request closed without merging**
