### PR TITLE
[Merged by Bors] - Add a way to toggle `AudioSink`

### PR DESCRIPTION
**Pull request by lovelymono**
# Objective

Currently toggling an `AudioSink` (for example from a game menu) requires writing

```rs
if sink.is_paused() {
    sink.play();
} else {
    sink.pause();
}
```

It would be nicer if we could reduce this down to a single line

```rs
sink.toggle();
```

## Solution

Add an `AudioSink::toggle` method which does exactly that.

---

## Changelog

- Added `AudioSink::toggle` which can be used to toggle state of a sink.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Code is correct, and docs are good. Unsure about adding non-idempotent methods, but users *will* want this.

Would you use this for e.g. "disable all dialogue" buttons in menus?

**Comment by lovelymono** [comment]
> Would you use this for e.g. "disable all dialogue" buttons in menus?

Right now in my game I have a persistent background music (similar to Stellaris' music player), and use this for a "Toggle music" button in options menu.

**Review by harudagondi — APPROVED** [review]

**Comment by harudagondi** [comment]
I am okay with this change, but note that `kira` and `oddio` doesn't have a toggle method, so does `bevy_kira_audio` and `bevy_oddio`.

**Review by Pietrek14 — APPROVED** [review]
Maybe the use case isn't broad, but it won't hurt to have this feature.

**Comment by alice-i-cecile** [comment]
Sure, why not. This *is* a common pattern.

bors r+

**Pull request closed without merging**
