### PR TITLE
[Merged by Bors] - Get rid of ChangedRes

### PR DESCRIPTION
**Pull request by TheRawMeatball**
This replaces `ChangedRes` with simple associated methods that return the same info, but don't block execution. Also, since ChangedRes was infectious and was the only reason `FetchSystemParam::get_params` and `System::run_unsafe` returned `Option`s, their implementation could be simplified after this PR is merged, or as part of it with a future commit.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
This was discussed further in #1186; particularly [this](https://github.com/bevyengine/bevy/discussions/1186#discussioncomment-256122) comment thread.

**Comment by cart** [comment]
Something we didn't discuss in the issue above (and that didn't occur to me until now) is that we're now retrieving resource change info on every Res fetch. We of course need to fetch "mutated" info for ResMut anyway, but with this approach we're adding a lot of extra fetches that will likely add up in a measurable way across all resources and all systems.

Its worth considering alternatives, such as a new `ResFlags<T>` SystemParam.

**Comment by alice-i-cecile** [comment]
Oh hmm, you're right. What if we borrowed the Query syntax to make it more approachable at the same time?

We were discussing moving in that direction already. Here's what I was thinking, for a before and after API:

`Res<T>`: `Res<&T>`
`ResMut<T>`: `Res<&mut T>`
`ChangedRes<T>`: `Res<Changed<&T>>`
(and so on)

I'm not sure I love the `&` references there, but they a) give us coherency with `Query` and b) allow us to differentiate between the pointer and the value for `Copy` resources (although that's kind of a weird pattern for anything other than a constant).

This would give us the ability to avoid fetching Resource change info right?

**Comment by alice-i-cecile** [comment]
So, this is coming back to our discussions about "system bodies should discuss what systems do when they run" vs. "run criteria / SystemSet / AppBuilder logic should discuss when they should run". This is valuable because it makes sure that the scheduler has access to all the relevant information, and it allows for systems to be clearer about what they do (and more reusable).

What if we cut ChangedRes entirely, and only access this information via a RunCriteria? That should avoid the issue @cart raises above, and keeps for a nice separation of concerns.

**Comment by TheRawMeatball** [comment]
>Its worth considering alternatives, such as a new ResFlags<T> SystemParam.

Sounds fair - I'll change things over to a `ResFlags<T>`.

>What if we cut ChangedRes entirely, and only access this information via a RunCriteria?

There are multiple problems with such an approach:
1) This kind of decision is usually done on a per-system basis, and potentially using a mix of other info such as events or queries.
2) These will rarely, if ever use the complex looping behavior in `RunCriteria`.
3) Run criteria have some additional cost, by virtue of being additional systems that do extra queries and force the scheduler to do more work. 

Overall, I don't think we should be bloating `RunCriteria` this much. A system should be able to easily specify if it should run, without having to write that in a different file. I don't think separating if a system should run from what is run is a very good idea, since a file specifying loads of unrelated run criteria is worse than lots of systems which specify their run criteria at their start, next to the necessary context.

**Comment by cart** [comment]
> Overall, I don't think we should be bloating RunCriteria this much

I agree with this generally. Encouraging people to move a simple "if changed" check to RunCriteria seems like a lot of added boilerplate / complexity for what should really be simple.

Imo encoding whether or not a system should run "inside" the system is preferable for cases where the filter is core to the logic of the system itself. splitting that type of logic out is a reduction in clarity (both by nature of the lines drawn and the boilerplate associated with drawing the lines). I expect this to be the "common" case.

**Comment by aevyrie** [comment]
I wanted to drop in to express a current use case in the hopes that it can help shape the API.

For bounding volume updates, there are three cases that need to be checked before recomputing the bounding volume:

1. Has the mesh handle been changed?
2. Has the mesh itself been changed?
3. Has the `GlobalTransform` changed?

We want to avoid recomputing bounding volumes, because it can be expensive, so using component change detection in queries is really useful! However, answering question (2) requires using `ChangedRes` in an entirely separate system.

Using something like `Flags` might work, but I'm worried that I now need to iterate over every single mesh to check which ones have changed, which could quickly become expensive. I'd prefer to have the power of component change detection, which could tell me if the underlying asset has changed. My ideal API would be something like:

```rust
query: Query<Handle<Mesh>, Or<(ChangedRes<Handle<Mesh>>, Changed<Handle<Mesh>>)>>
```

Maybe, even simpler, would be if asset mutations caused the `Handle` to be mutated - perhaps by keeping the handle UID the same, but bumping a rev counter (i.e. generational ID). Then `Changed<Handle<Mesh>>` would be triggered if the handle _or_ the underlying asset was changed, which seems to be the goal of change detection on a handle anyway. This would simplify the above example to:

```rust
query: Query<Handle<Mesh>, Changed<Handle<Mesh>>>
```

Having the ability to query asset changes through their handles would be incredibly useful, and seems much more Bevy-idiomatic than `ChangedRes`.

**Comment by Davier** [comment]
I just realized that `ChangedRes` can already be used to have event-triggered systems. It's far from perfect: you cannot use the event buffering system (it currently mutates the resource every frame) and there are some false positives (when looping), but it does prevent unused systems to run.
I'm not weighting against this PR though, since `ChangedRes` can be confusing to use, and run criteria may be a better solution for that feature.

**Comment by alice-i-cecile** [comment]
> Sounds fair - I'll change things over to a ResFlags<T>.

@TheRawMeatball I think with that change made this would be a good change to make in time for 0.5.

**Comment by TheRawMeatball** [comment]
Hmm, I split `ResFlags` out of `Res`, but we should still consider leaving the two unified since this split causes a bit of inconsistency between `Res` and `ResMut`

**Comment by cart** [comment]
Alrighty I think this is good to go. I like the `ResFlags<T>` impl as it provides parity with the `Flags<T>` component query.  I'm going to merge this so @TheRawMeatball gets proper credit, then I'll adapt #1525 to account for it.

**Comment by cart** [comment]
(cancelled because I want to think about ResMut + ResFlags conflicts a bit)

**Comment by cart** [comment]
I think @TheRawMeatball was right about Res/ResMut consistency. On paper I like ResFlags more, but it can't safely be used alongside ResMut, which means ResMut needs to include the "tracker status" methods on it. I can see people being very confused when ResMut::changed() exists but Res::changed() does not. ResFlags is also more code to compile / maintain. 

I ran some benchmarks. Adding ComponentFlags to Res pointers was completely in the noise. I did both a micro-benchmark (running a system that reads a Res and writes to a component) and I measured frame times on breakout.  The micro-benchmark is hard to trust because who knows whats being optimized out. But breakout has a larger number of systems/resources with a small number of entities, so if the cost was big i would expect it to register there.

If the benchmarks showed a measurable cost, I would be more inclined to just accept the ResFlags / ResMut / Res inconsistency, but now I'm inclined to roll with the simpler Res::changed() /ResMut::changed() impl.

Barring pushback here, I'll make the relevant changes in the ECS V2 pr. 

TheRawMeatball: if you want credit, just update this pr with your previous impl and I'll merge it prior to merging ECS v2.

**Comment by alice-i-cecile** [comment]
> but now I'm inclined to roll with the simpler Res::changed() /ResMut::changed() impl.

Yep, I like this, and think it's a much clearer API. Consistency is super valuable for being able to iterate quickly and safely, which means that your code base is easier to make faster in more concrete ways.

**Comment by TheRawMeatball** [comment]
I resetted back but the CI is borked.

**Comment by cart** [comment]
Looks like tinytemplate is in our `cargo test` build tree now (only on latest nightly after a cargo update)? 

I couldn't repro until a `rustup update` and a `cargo update`. Investigating now

**Comment by cart** [comment]
Alrighty its a criterion dependency (which explains why the ECS V2 PR isn't failing ... which removes the criterion dev-dependency from bevy-ecs)

**Comment by cart** [comment]
#1542

**Pull request closed without merging**
