### PR TITLE
Automatically add (and remove) S-Needs-Review to PRs

### LINKED ISSUE #5620: Add a workflow that adds a `S-Needs-Review` to all PRs meeting the "review" criteria
## What problem does this solve or what need does it fill?

Bevy's progress is currently bottlenecked by community reviews. [[*Citation needed*](https://c.tenor.com/Dp--4fYUHtgAAAAC/game-of-thrones-go-t.gif)]
Users can search PRs with the following filters and find issues that need their review:

https://github.com/bevyengine/bevy/pulls?q=is%3Aopen+is%3Apr+-label%3AS-Ready-For-Final-Review+-draft%3A%3Atrue+-label%3AS-Needs-RFC+-reviewed-by%3A%40me+-author%3A%40me

This is isn't a very visible approach and it is hard for users to find something that they don't necessarily know how to look for.

## What solution would you like?

Setup an automated workflow that adds the label `S-Needs-Review` to all pull requests that meets these criteria:

- is pull request
- is open
- is not draft
- without `S-Ready-For-Final-Review`
- without `S-Needs-RFC`
- without `S-Blocked`
- without `S-Adopt-Me`?
- Has less than 3 reviews (or less than 3 *approved* reviews?)

Open to discussion if these filters / criteria is the correct ones.

Either the same action or a separate one could also be responsible for removing the `S-Needs-Review` once the PR no longer fits the criteria.

## What alternative(s) have you considered?

- Doing it manually is unfeasible.
- Not adding the label will make it harder to find where to put review focus

### PR DESCRIPTION
**Pull request by x-52**
# Objective

- Fix #5620
- Make it easier for people to find PRs in need of a review

# Solution

- Create an actions workflow called "Pull Request Labeler"
- Runs every time a PR is created, marked as ready for review, or labeled
- For new PRs and PRs marked ready for review, it adds the label `S-Needs-Review`
- If certain labels are added, it will remove `S-Needs-Review`

### CODE REVIEW

**Comment by Weibye** [comment]
> * For review submissions, it checks if there have been 3 approvals, and will remove the label if that is true

Notably, our current guidelines state that something is ready for _final_ review if we have at _least_ 2 reviews. By having this setting to 3 we are going to label more PRs than strictly necessary by our process. 

However extra eyes on problems never hurt. 

I'm not sure which is the correct approach.

**Comment by mockersf** [comment]
I would prefer the "remove the label part" to not be conditioned by the number of reviews. The label should be removed when one of the incompatible labels are added (need rfc, adopt, ready, ...).

**Comment by Weibye** [comment]
> I would prefer the "remove the label part" to not be conditioned by the number of reviews. The label should be removed when one of the incompatible labels are added (need rfc, adopt, ready, ...).

That sounds much better. I agree!

**Comment by x-52** [comment]
> I would prefer the "remove the label part" to not be conditioned by the number of reviews. The label should be removed when one of the incompatible labels are added (need rfc, adopt, ready, ...).

Just implemented that!

**Review by Weibye — APPROVED** [review]
This looks good to me now :)

**Comment by Weibye** [comment]
This is now blocked on @cart adding a `S-Needs-Review` label :)

**Comment by mockersf** [comment]
this PR doesn't seem to work. https://github.com/bevyengine/bevy/runs/7818915107?check_suite_focus=true

**Comment by x-52** [comment]
@mockersf Sorry about that! I forgot to add a space in the if statement. Anyway, it seems to work now!

**Comment by mockersf** [comment]
(changing label to trigger workflow)

**Comment by Weibye** [comment]
> Run if [ $ACTION == "labeled" ]; then
gh: Not Found (HTTP 404)
jq: error (at <stdin>:0): Cannot iterate over null (null)
/home/runner/work/_temp/1a6669a8-882d-4ece-a911-e63c7ccf693d.sh: line 6: [: ==: unary operator expected

Is it unable to find the repository?

**Comment by alice-i-cecile** [comment]
Closing this out: we've moved away from this workflow.

**Pull request closed without merging**
