### PR TITLE
Updates default Text font size to 24px

### LINKED ISSUE #13587: Increase default font size
> Also, maybe 20px should just be the default font size. The default seems too tiny for any real use case anyway. Again, out of scope though.

_Originally posted by @IceSentry in https://github.com/bevyengine/bevy/issues/13583#issuecomment-2140906070_

### PR DESCRIPTION
**Pull request by mnmaita**
# Objective

- The default font size is too small to be useful in examples or for debug text.
- Fixes #13587

## Solution

- Updated the default font size value in `TextStyle` from 12px to 24px.
- Resorted to Text defaults in examples to use the default font size in most of them.

## Testing

- WIP

---

## Migration Guide

- The default font size has been increased to 24px from 12px. Make sure you set the font to the appropriate values in places you were using `Default` text style.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Much nicer for the examples! I've updated the PR description a bit to make it clearer and improve the migration guide.

**Review by rparrett — APPROVED** [review]
What a lovely diff.

(Non-blocking) There may be a few examples where `FiraMono-Medium` is manually specified and doesn't need to be.

There are a few that do need it because the help text uses glyphs beyond the limited set the default font contains. But I think a few may not.

**Comment by mnmaita** [comment]
> What a lovely diff.
> 
> (Non-blocking) There may be a few examples where `FiraMono-Medium` is manually specified and doesn't need to be.
> 
> There are a few that do need it because the help text uses glyphs beyond the limited set the default font contains. But I think a few may not.
> 
> In one case, I was able to use the default after swapping out unicode em-dashes for regular dashes. But some examples need "box drawing" glyphs.

I could split this up into several PRs but figured out that it was going to be too much work and then we'd be testing every single example on a different PR (or something like that). ETOOMANYEXAMPLES 😅 

I'll check those examples you mentioned and reduce code a bit more where possible, I like the idea.

**Comment by alice-i-cecile** [comment]
Ping me when you're done cleaning up and I'll validate it quick before merging :)

**Comment by mnmaita** [comment]
@alice-i-cecile finished with getting rid of the default font loading where appropriate. I did some extra cleanup in places where the default text color was used too.

**Pull request merged**
