### PR TITLE
[Merged by Bors] - Removed Mobile Touch event y-axis flip

### PR DESCRIPTION
**Pull request by slyedoc**
# Objective

Fix android touch events being flipped.  Only removed test for android, don't have ios device to test with.  Tested with emulator and physical device.

## Solution

Remove check, no longer needed with coordinate change in 0.9

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Can you remove it for iOS too? Even without testing this is virtually guaranteed to not be needed anymore.

**Comment by slyedoc** [comment]
Removed it for ios

**Review by alice-i-cecile — APPROVED** [review]

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
tested on iOS 👍

**Comment by mockersf** [comment]
Could you change the PR title to reflect it's also for iOS? The title will be used as the commit name in git history

**Comment by alice-i-cecile** [comment]
I'll merge this once the title is updated.

**Pull request closed without merging**
