### PR TITLE
Update config_fast_builds for windows

### PR DESCRIPTION
**Pull request by termhn**
Motivated by this comment thread from Discord https://discordapp.com/channels/691052431525675048/742884593551802431/749411745700773950

### CODE REVIEW

**Comment by CleanCut** [comment]
If this change is merged, let's make the corresponding change in https://github.com/CleanCut/bevy_template

**Comment by cart** [comment]
Unless I missed something in that conversation, it looks like we didn't really find a root cause for why rust-lld was missing. This PR reverts to the "old" manual config (albeit with more thorough docs :heart: ), which we moved off of because "rust-lld" seemed like a nicer, more automatic solution.

If rust-lld is not actually nicer + automatic then this seems reasonable. But are we sure this isn't a specific case of one person's computer/configuration not working? I'd like to be super sure that we aren't missing out on magic config that works without significant intervention like 3rd party package managers, downloading things from websites + modifying PATH, etc.

**Comment by termhn** [comment]
Hm, it does seem the original config (rust-lld.exe) is working for me. Guess I'll close this for now, and the person who was having trouble already followed to get it working for them with lld-link.exe

**Comment by cart** [comment]
Cool cool. I'll keep my eyes peeled for more cases like this. Its very possible that rust-lld isn't the panacea we think it is.

**Pull request closed without merging**
