### PR TITLE
Random sampling of directions and quaternions

### PR DESCRIPTION
**Pull request by mweatherley**
# Objective

Augment Bevy's random sampling capabilities by providing good tools for producing random directions and rotations.

## Solution

The `rand` crate has a natural tool for providing `Distribution`s whose output is a type that doesn't require any additional data to sample values — namely, [`Standard`](https://docs.rs/rand/latest/rand/distributions/struct.Standard.html). 

Here, our existing `ShapeSample` implementations have been put to good use in providing these, resulting in patterns like the following:
```rust
// Using thread-local rng
let random_direction1: Dir3 = random();

// Using an explicit rng
let random_direction2: Dir3 = rng.gen();

// Using an explicit rng coupled explicitly with Standard
let random_directions: Vec<Dir3> = rng.sample_iter(Standard).take(5).collect();
```

Furthermore, we have introduced a trait `FromRng` which provides sugar for `rng.gen()` that is more namespace-friendly (in this author's opinion):
```rust
let random_direction = Dir3::from_rng(rng);
```

The types this has been implemented for are `Dir2`, `Dir3`, `Dir3A`, and `Quat`. Notably, `Quat` uses `glam`'s implementation rather than an in-house one, and as a result, `bevy_math`'s "rand" feature now enables that of `glam`. 

---

## Changelog

- Created `standard` submodule in `sampling` to hold implementations and other items related to the `Standard` distribution.
- "rand" feature of `bevy_math` now enables that of `glam`.

---

## Discussion

From a quick glance at `Quat`'s distribution implementation in `glam`, I am a bit suspicious, since it is simple and doesn't match any algorithm that I came across in my research. I will do a little more digging as a follow-up to this and see if it's actually uniform (maybe even using those tools I wrote — what a thrill). 

As an aside, I'd also like to say that I think [`Distribution`](https://docs.rs/rand/latest/rand/distributions/trait.Distribution.html) is really, really good. It integrates with distributions provided externally (e.g. in `rand` itself and its extensions) along with doing a good job of isolating the source of randomness, so that output can be reliably reproduced if need be. Finally, `Distribution::sample_iter` is quite good for ergonomically acquiring lots of random values. At one point I found myself writing traits to describe random sampling and essentially reinvented this one. I just think it's good, and I think it's worth centralizing around to a significant extent.

### CODE REVIEW

**Comment by JMS55** [comment]
Small drive by comment, I think I'd prefer `Dir3::from_rng()` -> `Dir3::random()`.

**Comment by mweatherley** [comment]
> Small drive by comment, I think I'd prefer `Dir3::from_rng()` -> `Dir3::random()`.

Yeah I think that's reasonable; the only issue I really have with that is that `rand`'s `random()` doesn't take any additional parameters, which is why I chose `from_rng` as a name. I'm happy to change it if there's some consensus, obviously.

**Review by NthTensor — APPROVED** [review]
Second the name change on `from_rng`, though I don't care exactly to what. `from` usually implies pass by value and consumption, but this is pass by reference.

Love the docs, love the examples, we don't need tests because the primitives already have them, great all round.

Would prefer if you noted these are uniform in the doc for `FromRng` (I know, it should be obvious, but more docs are never bad).

**Comment by Bluefinger** [comment]
I'm going against the grain here and state that to me, `from_rng` was more correct than `random`, if going by convention from the `rand` docs: https://docs.rs/rand/latest/rand/trait.SeedableRng.html#method.from_rng

If anything, `from_rng` accepts a `<R: RngCore>` so that it can take an owned instance *or* reference (which is allowed by `RngCore`'s auto-traits), though in the case of `from_rng` from `SeedableRng`, it returns a `Result`.

Sorry if this is a bit bike-sheddy, but I feel more that we should abide more by the conventions set by `rand` here, as `random()` doesn't take any parameters, but `from_rng` does.

**Comment by NthTensor** [comment]
> If anything, from_rng accepts a <R: RngCore> so that it can take an owned instance or reference...

Oh neat, that choice makes a bit more sense then. I'm fine with either, open to additional bike shedding.

**Comment by NthTensor** [comment]
@alice-i-cecile would appreciate your input on this tiny naming bikeshed.

**Comment by alice-i-cecile** [comment]
I think `from_rng` is a bit clearer, and more consistent with the rest of the ecosystem.

Approving, but I'll wait until this is changed to merge :)

**Review by alice-i-cecile — APPROVED** [review]

**Pull request merged**
