### PR TITLE
[Merged by Bors] - `debug_checked_unwrap` should track its caller

### PR DESCRIPTION
**Pull request by JoJoJet**
# Objective

When an error causes `debug_checked_unreachable` to be called, the panic message unhelpfully points to the function definition instead of the place that caused the error.

## Solution

Add the `#[track_caller]` attribute in debug mode.

### CODE REVIEW

**Comment by james7132** [comment]
Another, probably more efficient, alternative is to replace it with a macro instead.  This also avoids us needing to screw around with the inlining of the function (see #5064).

**Comment by JoJoJet** [comment]
Fixed in #6461

**Comment by JoJoJet** [comment]
Turns out this actually was not fixed. The `track_caller` attribute still needs to be added to `debug_checked_unwrap`, which was added in the aforementioned PR.

**Review by CGMossa — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Pull request closed without merging**
