### PR TITLE
rename 'w and 's to 'world and 'state

### PR DESCRIPTION
**Pull request by LamequeFernandes**
Co-Authored-by: Peh099 <pedrohenriquec099@gmail.com>

# Objective

Rename ```'w``` and ```'s``` to ```'world``` and ```'state``` in [SystemParam](https://docs.rs/bevy/latest/bevy/ecs/system/trait.SystemParam.html#derive). As described in the first topic of issue #6953.

## Solution

Rename arguments in documentation.

---

## Changelog

Renamed ```'w``` and ```'s``` to ```'world``` and ```'state``` in documentation about SystemParam .

### CODE REVIEW

**Comment by LamequeFernandes** [comment]
We wondered if it was also necessary to rename the 'w and 's of the functions that were outside the comments in the documentation.

**Comment by MrGVSV** [comment]
I could be wrong, but isn't `'w` and `'s` required when using the `SystemParam` derive? If so, this change might be confusing. Maybe you could just give a call out to the the fact that they're for `'world` and `'state` (e.g. "...the `'w` lifetime (otherwise known as the _world_ lifetime)...")

**Comment by nicopap** [comment]
See also #6953

**Comment by inodentry** [comment]
Bikeshed: should it be `'system` instead of `'state`?

**Comment by alice-i-cecile** [comment]
> Bikeshed: should it be 'system instead of 'state?

No, this isn't only useful in systems.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
@LamequeFernandes it looks like you need to update the `SystemParam` macro for this to pass CI.

**Comment by alice-i-cecile** [comment]
Nice: can you resolve conflicts? Either merge `main` into this branch or rebase this PR.

**Comment by LamequeFernandes** [comment]
> Nice: can you resolve conflicts? Either merge `main` into this branch or rebase this PR.

Yes, I can, I'll do it with @Peh099 right now :)

**Comment by alice-i-cecile** [comment]
Rebase looks good, but looks like there's a couple places to touch up still :)

**Comment by CGMossa** [comment]
Was it done elsewhere?

**Pull request closed without merging**
