### PR TITLE
[Merged by Bors] - add ambient lighting hook

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

add a hook for ambient occlusion to the pbr shader

## Solution

add a hook for ambient occlusion to the pbr shader

### CODE REVIEW

**Comment by robtfm** [comment]
After discussing with robswain, I’ll change this to a more generically useful ambient lighting hook (that could allow custom control of eg fresnel effects etc as well)

**Comment by FraserLee** [comment]
@robtfm Do you know if this hook would be the right place to fetch the ambient environmental light colour from a procedural sky equation, or would that be somewhere else?

**Comment by robtfm** [comment]
> @robtfm Do you know if this hook would be the right place to fetch the ambient environmental light colour from a procedural sky equation, or would that be somewhere else?

it would be possible to do that here if it doesn't vary from material to material. with this pr you could accomplish it by replacing the shader stored at PBR_AMBIENT_HANDLE with your own shader containing an `ambient_lighting` function (with the same signature), and you would have to duplicate some/all of the original code. 

what might work even better for your use case (which is the skybox, i'm assuming) would be a separate hook for ambient color(s) so you could keep the original ambient lighting calculations, just using a color determined by your procedure. maybe i should add that too.

(note also if #5703 lands this would be cleaner to use - replacing handles is pretty hacky. but i would not advise trying to use that in the current state)

**Comment by FraserLee** [comment]
Thanks for the reply! That's good to know. I might experiment with it using this PR, but will hold off on anything final till there's a way with less duplicate code to maintain.

**Review by rodolphito — APPROVED** [review]
I like this change a lot, and the math is correct. Only concern is that since `NdotV` is being computed inside `ambient_light` now as well as outside, it may not be optimized out as a duplicate expression. Even if it is, the fact that they are in far apart places in the code can mean slight changes to one of the two lines can produce mysterious performance regressions.

I'd just pass in `NdotV` as well as N and V to avoid that

**Review by PROMETHIA-27 — APPROVED** [review]
LGTM

**Comment by alice-i-cecile** [comment]
@robtfm once you've rebased this I'm comfortable to merge this PR.

**Pull request closed without merging**
