### PR TITLE
check for all-features with cargo-deny

### LINKED ISSUE #9880: Cargo deny doesn't check for all features
## What went wrong

While I was checking the licenses of the bevy dependencies.
 I noticed that the 'cargo deny' in the 'dependencies.yaml' workflow doesn't check for all the features.

If you run in main: `cargo deny --all-features  check --hide-inclusion-graph`

It will give you a lot of errors: license errors, duplicate crates, unmaintained advisories, security vulnerabilities, and yanked versions.

## Additional information

<details>
  <summary>Output</summary>

```rust
error[rejected]: failed to satisfy license requirements
  ┌─ symphonia 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-bundle-flac 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-bundle-mp3 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-codec-aac 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-codec-adpcm 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-codec-pcm 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-codec-vorbis 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-core 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-format-isomp4 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-format-wav 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-metadata 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[rejected]: failed to satisfy license requirements
  ┌─ symphonia-utils-xiph 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft

error[duplicate]: found 2 duplicate entries for crate 'hermit-abi'
    ┌─ /Users/ameknite/code/rust/repos/bevy/Cargo.lock:204:1
    │
204 │ ╭ hermit-abi 0.2.6 registry+https://github.com/rust-lang/crates.io-index
205 │ │ hermit-abi 0.3.1 registry+https://github.com/rust-lang/crates.io-index
    │ ╰──────────────────────────────────────────────────────────────────────^ lock entries

error[duplicate]: found 3 duplicate entries for crate 'memoffset'
    ┌─ /Users/ameknite/code/rust/repos/bevy/Cargo.lock:248:1
    │
248 │ ╭ memoffset 0.6.5 registry+https://github.com/rust-lang/crates.io-index
249 │ │ memoffset 0.7.1 registry+https://github.com/rust-lang/crates.io-index
250 │ │ memoffset 0.9.0 registry+https://github.com/rust-lang/crates.io-index
    │ ╰─────────────────────────────────────────────────────────────────────^ lock entries

error[duplicate]: found 2 duplicate entries for crate 'nix'
    ┌─ /Users/ameknite/code/rust/repos/bevy/Cargo.lock:266:1
    │
266 │ ╭ nix 0.25.1 registry+https://github.com/rust-lang/crates.io-index
267 │ │ nix 0.26.2 registry+https://github.com/rust-lang/crates.io-index
    │ ╰────────────────────────────────────────────────────────────────^ lock entries

error[duplicate]: found 2 duplicate entries for crate 'num-traits'
    ┌─ /Users/ameknite/code/rust/repos/bevy/Cargo.lock:277:1
    │
277 │ ╭ num-traits 0.1.43 registry+https://github.com/rust-lang/crates.io-index
278 │ │ num-traits 0.2.15 registry+https://github.com/rust-lang/crates.io-index
    │ ╰───────────────────────────────────────────────────────────────────────^ lock entries

error[duplicate]: found 2 duplicate entries for crate 'tracy-client'
    ┌─ /Users/ameknite/code/rust/repos/bevy/Cargo.lock:410:1
    │
410 │ ╭ tracy-client 0.15.2 registry+https://github.com/rust-lang/crates.io-index
411 │ │ tracy-client 0.16.1 registry+https://github.com/rust-lang/crates.io-index
    │ ╰─────────────────────────────────────────────────────────────────────────^ lock entries

error[unmaintained]: slice-deque is unmaintained
    ┌─ /Users/ameknite/code/rust/repos/bevy/Cargo.lock:360:1
    │
360 │ slice-deque 0.3.0 registry+https://github.com/rust-lang/crates.io-index
    │ ----------------------------------------------------------------------- unmaintained advisory detected
    │
    = ID: RUSTSEC-2020-0158
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0158
    = The author of the `slice-deque` crate is unresponsive and is not receiving security patches.

      Maintained alternatives:

      - [`slice-ring-buffer`](https://crates.io/crates/slice-ring-buffer)
    = Announcement: https://github.com/gnzlbg/slice_deque/issues/94
    = Solution: No safe upgrade is available!

error[unmaintained]: mach is unmaintained
    ┌─ /Users/ameknite/code/rust/repos/bevy/Cargo.lock:241:1
    │
241 │ mach 0.3.2 registry+https://github.com/rust-lang/crates.io-index
    │ ---------------------------------------------------------------- unmaintained advisory detected
    │
    = ID: RUSTSEC-2020-0168
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0168
    = Last release was almost 4 years ago.

      Maintainer(s) seem to be completely unreachable.

      ## Possible Alternative(s)

      These may or may not be suitable alternatives and have not been vetted in any way;
      - [mach2](https://crates.io/crates/mach2) - direct fork
    = Announcement: https://github.com/fitzgen/mach/issues/63
    = Solution: No safe upgrade is available!

error[vulnerability]: SliceDeque::drain_filter can double drop an element if the predicate panics
    ┌─ /Users/ameknite/code/rust/repos/bevy/Cargo.lock:360:1
    │
360 │ slice-deque 0.3.0 registry+https://github.com/rust-lang/crates.io-index
    │ ----------------------------------------------------------------------- security vulnerability detected
    │
    = ID: RUSTSEC-2021-0047
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0047
    = Affected versions of the crate incremented the current index of the drain filter
      iterator *before* calling the predicate function `self.pred`.

      If the predicate function panics, it is possible for the last element in the
      iterator to be dropped twice.
    = Announcement: https://github.com/gnzlbg/slice_deque/issues/90
    = Solution: No safe upgrade is available!

error[yanked]: detected yanked crate (try `cargo update -p hermit-abi`)
    ┌─ /Users/ameknite/code/rust/repos/bevy/Cargo.lock:205:1
    │
205 │ hermit-abi 0.3.1 registry+https://github.com/rust-lang/crates.io-index
    │ ---------------------------------------------------------------------- yanked version
```

</details>

### PR DESCRIPTION
**Pull request by ameknite**
# Objective

Fix #9880

## Solution

- Add all-features flag 
- Allow "MPL-2.0" license for the [Symphonia](https://github.com/pdeljanov/Symphonia) crates
- Update dependencies unmaintained or with vulnerabilities: https://github.com/RustAudio/rodio/issues/517 , https://github.com/LiquidityC/slice_ring_buffer/pull/7

### CODE REVIEW

**Comment by ameknite** [comment]
@alice-i-cecile the MPL-2.0 license is only copyleft if you modify the source files, is not like LGPL. 

from https://www.mozilla.org/en-US/MPL/2.0/FAQ/

Q11: How 'viral' is the MPL? If I use MPL-licensed code in my proprietary application, will I have to give all the source code away?

> No. The license requires that Modifications (as defined in Section 1.10 of the license) must be licensed under the MPL and made available to anyone to whom you distribute the Source Code. However, new files containing no MPL-licensed code are not Modifications, and therefore do not need to be distributed under the terms of the MPL, even if you create a Larger Work (as defined in Section 1.7) by using, compiling, or distributing the non-MPL files together with MPL-licensed files. This allows, for example, programs using MPL-licensed code to be statically linked to and distributed as part of a larger proprietary piece of software, which would not generally be possible under the terms of stronger copyleft licenses.

**Comment by alice-i-cecile** [comment]
I agree with your analysis, but I'd like to keep this uncontroversial :) Was there a reason to add this in the current PR?

**Comment by ameknite** [comment]
Bevy uses Rodio, and Rodio uses [Symphonia](https://github.com/pdeljanov/Symphonia) which is MPL-2.0 licensed.

If bevy wants to avoid the MPL-20 license. It will need to stop using rodio.

Symphonia is used through these flags in bevy_audio:

symphonia-aac = ["rodio/symphonia-aac"]
symphonia-all = ["rodio/symphonia-all"]
symphonia-flac = ["rodio/symphonia-flac"]
symphonia-isomp4 = ["rodio/symphonia-isomp4"]
symphonia-vorbis = ["rodio/symphonia-vorbis"]
symphonia-wav = ["rodio/symphonia-wav"]

**Comment by ameknite** [comment]
The MPL-2.0 license is needed to fix #9880 

```error[rejected]: failed to satisfy license requirements
  ┌─ symphonia 0.5.3 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "MPL-2.0"
  │            ^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: license is considered copyleft
```

**Comment by devil-ira** [comment]
> If bevy wants to avoid the MPL-2.0 license. It will need to stop using rodio.

Not necessarily. symphonia is an optional dependency of rodio, which is why it's only caught in this PR.

IMO rather than allowing MPL-2.0 generally we should add and exception for `symphonia` similar to `unicode-ident` for now and discuss symphonia's license in another issue (If it wasn't already discussed?).

**Comment by ameknite** [comment]
yeah that could be a solution, but isn't this too verbose:

```toml
exceptions = [
    { name = "unicode-ident", allow = [
        "Unicode-DFS-2016",
    ] },
    { name = "symphonia", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-bundle-flac", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-bundle-mp3", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-codec-aac", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-codec-adpcm", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-codec-pcm", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-codec-vorbis", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-core", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-format-isomp4", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-format-wav", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-utils-xiph", allow = [
        "MPL-2.0",
    ] },
    { name = "symphonia-metadata", allow = [
        "MPL-2.0",
    ] },
]
```

**Comment by MinerSebas** [comment]
The potential problem is Console Support.
If that dependency requires changes for usage on a console, you may not share it due to an NDA, but that would conflict with the MPL License.
This is the reason that `wgpu` switched away from MPL.

So to be careful, it should be a case by case exception for dependencies that use MPL (When possible confirmed by a Dev with Console access).

**Comment by ameknite** [comment]
@MinerSebas you are right, I didn't think about that. It could be a problem if we added a crate too intertwined with bevy.
I really dislike how consoles force you to put everything under an NDA, but well it is what it .

**Review by alice-i-cecile — APPROVED** [review]

**Review by devil-ira — APPROVED** [review]

**Pull request merged**
