### PR TITLE
ecs: add #[bundle(default(..))] attribute

### PR DESCRIPTION
**Pull request by soqb**
# Objective

- Sometimes, when deriving `Bundle`, we would like to have some components that are initialized along with a bundle, but not part of the public API of the crate or initialized with a default value. Currently, users are required to create a constructor/builder API for this behaviour but classic constructors have clear ergonomic and clarity benefits in plenty of scenarios.

## Solution

- Introduce a `#[bundle(default(A, B = make_b, C))]` container-level attribute that lets us insert implicit components along with our bundles.

## Considerations / Alternatives

- With the `B = make_b` syntax, `make_b` must resolve to a function with the signature `fn() -> B`, but we could easily make this `fn(&BundleType) -> B`.

- Is `default` the best name? Perhaps something more explicit (ironic) like `implicit_components`.
 
- Is this necessary? I've found myself reaching for something like this a few times, but perhaps we should hint users towards the builder pattern instead. I think its very clear from the following definition which components are inserted, but it might not be so clear from the site where `EnemyBundle` is initialised.
```rust
#[derive(Bundle)]
#[bundle(default(NotExploding, Dry))]
struct EnemyBundle {
    max_health: MaxHealth,
}
```

---

## Changelog

- Introduced a new `#[bundle(default(A, B = make_b, C))]` container-level attribute that lets us insert implicit components along with our bundles.

### CODE REVIEW

**Comment by JoJoJet** [comment]
Couldn't you just use struct update syntax for default components?

```rust
#[derive(Bundle, Default)]
struct EnemyBundle {
    max_health: MaxHealth,
    marker1: NotExploding,
    marker2: Dry,
}

.spawn(EnemyBundle {
    max_health: MaxHealth(...),
    ..default()
})
```

**Comment by soqb** [comment]
not if any of your components are non-default, as it is in my case.

**Comment by JoJoJet** [comment]
How about 

```rust
#[derive(Bundle)]
struct EnemyBundle {
    max_health: MaxHealth,
    b: B,
}

impl Default for EnemyBundle {
    fn default() -> Self {
         Self {
            max_health: default(),
            b: make_b(),
        }
    }
}

.spawn(EnemyBundle {
    max_health: MaxHealth(...),
    ..default()
})
```

**Comment by alice-i-cecile** [comment]
Yeah, I'm not sold on this vs. a manual `Default` impl. I see the impulse, but this adds quite a bit of complexity and implicitness where I think that standard Rust idioms should do fine.

**Comment by soqb** [comment]
i think you both raise good points and i'm closing this PR, but might open a much more general issue if i get the time.

in my example, it was the equivalent of the `MaxHealth` component which couldn't be default and relied upon data specified by the user of my api, so struct update syntax was not an option.

**Pull request closed without merging**
