### PR TITLE
Add an attribute to automatically initialize some Resource types

### PR DESCRIPTION
**Pull request by JoJoJet**
# Objective

Having to call `.init_resource()` for every resource type can be annoying, especially if the resource is defined far from where  its containing plugin is built. Many resource types have a sensible default value and are expected to always be defined. For these types, calling `init_resource()` is not a meaningful operation, and can be done automatically with no loss in code clarity. Having to initialize many resource types can make `Plugin::build` cluttered, and can waste users' mental bandwidth by making them organize the init calls.

## Solution

Add an attribute to the derive macro that causes a resource type to be initialized automatically.

```rust
impl Plugin for MyPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(Update, show_images);
    }
}

#[derive(Resource, Default)]
#[resource(auto_init)]
struct Images(Vec<Image>);

// The `Images` resource will be given a default value when the system is initialized,
// which happens the first time the system or its containing schedule is run.
fn show_images(images: Res<Images>) {
    // ...
}
```

---

## Changelog

+ Added the `#[resource(auto_init)]` attribute, which makes it unnecessary to call `init_resource()` for a type.

### CODE REVIEW

**Review by killercup — COMMENTED** [review]
I like the idea of this -- but I think it needs more docs and updated examples to really sell it. E.g., how would I override the default value? By implementing `Default` or `FromWorld`?

**Comment by JoJoJet** [comment]
> I like the idea of this -- but I think it needs more docs and updated examples to really sell it. E.g., how would I override the default value? By implementing `Default` or `FromWorld`?

I mean the docs already say that it uses `FromWorld`. How would you like me to make it more clear?

**Comment by bushrat011899** [comment]
No necessarily a criticism, but this does invert the responsibility of registering types:

```rust
impl Plugin for MyPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(Update, show_images);
    }
}

#[derive(Resource, Default)]
#[resource(auto_init)]
struct Images(Vec<Image>);

fn show_images(images: Res<Images>) {
//                     ^---------^
//                     This function signature now controls what resources are
//                     registered in the app.
    // ...
}
```

Additionally, following this concept, should the same rules apply to `Event` as well?

```rust
// From the breakout example

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
//        .insert_resource(Scoreboard { score: 0 }) // No longer required
        .insert_resource(ClearColor(BACKGROUND_COLOR))
//        .add_event::<CollisionEvent>() // No longer required
        .add_systems(
            /* snip */
        )
        .run();
}

#[derive(Resource, Default)]
#[resource(auto_init)]
struct Scoreboard {
    score: usize,
}

#[derive(Event, Default)]
#[event(auto_init)]
struct CollisionEvent;
```

Even just in the breakout example, it's nice to see how clean the `App` setup becomes if events and resources were automatically initialised upon first request.

**Comment by JoJoJet** [comment]
Now that you mention it, `Events<T>` is like the perfect example of a resource with a reasonable default value, whose initialization doesn't do anything meaningful, and which doesn't make sense to be removed. It should probably be automatically initialized even without having to specify an attribute. Seems more controversial though so I'd be okay with leaving it for a follow-up.

**Comment by stargazing-dino** [comment]
> Not necessarily a criticism, but this does invert the responsibility of registering types:

Just random thought (not saying anything for this PR) but it'd be cool if a resource could also be auto dropped when it's no longer used. Possibly through reference counting the resource in use by all active systems. No idea how this would be implemented but it sounds cool haha

**Comment by JoJoJet** [comment]
On second thought, `App::add_event` also adds an instance of `event_update_system`, so we probably can't auto-initialize events in this way.

**Comment by JoJoJet** [comment]
Closing this because I think it makes resource initialization confusing, especially in places where resources are implicitly used like exclusive systems.

**Pull request closed without merging**
