### PR TITLE
Implement overloadable assignment operator traits for Mut

### PR DESCRIPTION
**Pull request by ickshonpe**
# objective

Implement the overloadable assignment operator traits for Mut.

# motivation

At the moment:

```rust
#[derive(Component, AddAssign, Deref, DerefMut)]
pub struct NewType(u32);

pub fn update(mut query: Query<&mut NewType>) {
    query.for_each_mut(|mut nt| {
        *nt += NewType(1);
        nt.0 += NewType(1);
        /* nt += NewType(1); // Error: cannot use `+=` on type `Mut<'_,NewType>` */
    });
}
```

After implementing AddAssign on Mut, like so:

```rust
impl<'a, T, U> AddAssign<U> for Mut<'a, T>
where
    T: AddAssign<U>,
{
    fn add_assign(&mut self, rhs: U) {
        *self.value += rhs;
    }
}
```

We can write:

```rust
#[derive(Component, AddAssign)]
pub struct NewType(u32);

pub fn update(mut query: Query<&mut NewType>) {
    query.for_each_mut(|mut nt| {
        nt += NewType(1);
    });
}
```

### CODE REVIEW

**Comment by IceSentry** [comment]
Couldn't you just implement `Deref` on the components where you need it? When using a crate like derive_more, you can derive Deref and you'll have pretty much the same result without any code added to bevy.

**Comment by Guvante** [comment]
I don't exactly what your code is doing as you don't provide definitions for the types included in your example but I played around with what I think it looks like.

1. Why the right had side changed? `velocity: &Velocity` so this PR shouldn't impact it.
2. Have you tried explicitly dereferencing the left hand side? It looks like your `.0` is already implicitly using `DerefMut` I wonder if an explicit usage would allow this to compile.

Given all that your example becomes `*position += velocity * time.delta_seconds()` which I think is just as good as the one without the dereference. Especially since `Mut` does not have a trivial `DerefMut` (it does change tracking).

Having at least one example of a tuple struct in a unit test would also help gauge the value add by explicitly showing how it simplifies things. Although to be fair when I tried to I ran into operator hell completely ignoring this PRs changes so might not be worth the effort.

**Comment by IceSentry** [comment]
The difference is that you would go from writing this
```rust
pub fn update(
    time: Res<Time>,
    mut query: Query<(&mut Position, &Velocity)>,
) {
    query.for_each_mut(|(mut position, velocity)| {
        position.0 += velocity.0 * time.delta_seconds();
    });
}
```

to this

```rust
pub fn update(
    time: Res<Time>,
    mut query: Query<(&mut Position, &Velocity)>,
) {
    query.for_each_mut(|(mut position, velocity)| {
        position += velocity * time.delta_seconds();
    });
}
```

It's just about not having to write .0 everywhere on a struct that is just a wrapper to a number.

**Comment by Guvante** [comment]
I understand the end goal, I was trying to unify comments about needing `Deref` and comments about how dropping `.0` worked with this PR. In my quick testing `Deref` was doing nothing.

```
pub fn update(
    time: Res<Time>,
    mut query: Query<(&mut Position, &Velocity)>,
) {
    query.for_each_mut(|(mut position, velocity)| {
        *position += velocity * time.delta_seconds();
    });
}
```

Works today assuming that the "no `.0`" version works.

**Comment by IceSentry** [comment]
> Works today assuming that the "no .0" version works.

I'm not sure what you mean here because this doesn't work today.

You can't do this without implementing the operators you are using on your tuple component. `Velocity` is a custom type and it doesn't implement any of that by default therefore you are forced to use `.0` to modify the data.

I asked about Deref/DerefMut because I thought it could be used in this context. Trying it out locally, it doesn't seem to work, but I remember cart mentioning using this for wrapper types when he was talking about adding the derive(Component) to bevy. Which is why I brought it up.

For the record since there seems to be confusion here. The PR is about using these kinds of types:
```rust
#[derive(Component)]
struct Velocity(f32);

#[derive(Component)]
struct Position(f32);
```

You can't use the containing value without either using `.0` or implementing something.

**Comment by Guvante** [comment]
> I'm not sure what you mean here because this doesn't work today.

Then why a PR that explicitly says "with this PR this code compiles"...

> For the record since there seems to be confusion here. 

The confusion was around what requirements on the end user would allow `Deref` to work but I don't think auto deref applies in this case as it doesn't seem to be triggering in my testing.

> You can't use the containing value without either using .0 or implementing something.

With the proper operators that would allow the given example to work with this PR the example I gave would compile without this PR.

#[derive(Component)]
    struct Time();

    impl Time {
        pub fn delta_seconds(&self) -> f32 {
            0.0
        }
    }

    #[derive(Clone, Copy)]
    struct Vec2(f32, f32);

    impl std::ops::AddAssign<Vec2> for Vec2 {
        fn add_assign(&mut self, rhs: Vec2) {
            self.0 += rhs.0;
            self.1 += rhs.1;
        }
    }

    impl std::ops::Mul<f32> for Vec2 {
        type Output = Vec2;
        fn mul(self, rhs: f32) -> Vec2 {
            Vec2(self.0 * rhs, self.1 * rhs)
        }
    }

    #[derive(Component, Clone, Copy)]
    struct Position(Vec2);
    #[derive(Component, Clone, Copy)]
    struct Velocity(Vec2);

    impl std::ops::AddAssign<Velocity> for Position {
        fn add_assign(&mut self, rhs: Velocity) {
            self.0 += rhs.0;
        }
    }

    impl std::ops::Mul<f32> for &Velocity {
        type Output = Velocity;
        fn mul(self, rhs: f32) -> Velocity {
            Velocity(self.0 * rhs)
        }
    }

    fn update(time: Res<Time>, mut query: Query<(&mut Position, &Velocity)>,) {
        query.for_each_mut(|(mut position, velocity)| {
            *position += velocity * time.delta_seconds();
        })
    }

Thus this PR isn't about remove `.0` but is instead about removing the dereference of `position`.

While I am all for the original plan this one seems less impactful to me, especially given that some consider non-trivial derefs to be something that should be explicit.

**Comment by ickshonpe** [comment]
> The difference is that you would go from writing this
> 
> ```rust
> pub fn update(
>     time: Res<Time>,
>     mut query: Query<(&mut Position, &Velocity)>,
> ) {
>     query.for_each_mut(|(mut position, velocity)| {
>         position.0 += velocity.0 * time.delta_seconds();
>     });
> }
> ```
> 
> to this
> 
> ```rust
> pub fn update(
>     time: Res<Time>,
>     mut query: Query<(&mut Position, &Velocity)>,
> ) {
>     query.for_each_mut(|(mut position, velocity)| {
>         position += velocity * time.delta_seconds();
>     });
> }
> ```
> 
> It's just about not having to write `.0` everywhere on a struct that is just a wrapper to a number.

Yes that's it.
Hadn't slept for two days and then spent hours learning git so I could work out how to send a second pull request and kept running out of harddrive space whenever I tried to compile anything and went on a completely dumb tangent implementing every operator even though they work already with deref / derefmut.
Updated my example to something clearer.

**Comment by ickshonpe** [comment]
> Thus this PR isn't about remove `.0` but is instead about removing the dereference of `position`.
> 
> While I am all for the original plan this one seems less impactful to me, especially given that some consider non-trivial derefs to be something that should be explicit.

Yes. I got this idea from a discussion on ergonomics in the Discord about Mut where they were complaining about writing .0 everywhere and not being to deconstruct Mut types in function parameters.
It seemed like it was a good idea at the time but you are right about it only removing the deference, and that not necessarily being a good thing when it also triggers change detection.

**Comment by richchurcher** [comment]
Closing due to inactivity and apparent lack of consensus. @ickshonpe please re-open an issue if this is still relevant in 2024.

**Pull request closed without merging**
