### PR TITLE
[Merged by Bors] - Add docstring comment to Style to reference CSS

### PR DESCRIPTION
**Pull request by djeedai**
Mention the fact that the UI layout system is based on the CSS layout
model through a docstring comment on the `Style` type.

# Objective

Explain to new users that the Bevy UI uses the CSS layout model, to lower the barrier to entry given the fact documentation (book and code) is fairly limited on the topic.

## Solution

Fix as discussed with @alice-i-cecile on #2918.

### CODE REVIEW

**Comment by mockersf** [comment]
there is one difference with CSS that should be mentioned: Bevy is upside down, with the vertical axis inverted

**Review by mockersf — APPROVED** [review]

**Comment by djeedai** [comment]
Who's doing the final review? Is that only @cart? If so, ping, this is very short to review and ready for merge, thanks! 🙏

**Comment by alice-i-cecile** [comment]
Generally only Cart. @mockersf has merge writes for "uncontroversial" PRs however, which I think this qualifies for.

**Comment by cart** [comment]
Yup this is uncontroversial. But I'll merge it because I'm here :)

**Pull request closed without merging**
