### PR TITLE
Allow `bevy_utils` in `no_std` Contexts

### PR DESCRIPTION
**Pull request by bushrat011899**
# Objective

- Adjust `bevy_utils` to make it `no_std` compatible
- Partially replaces #6581
- Contributes to #8161
- Contributes to #6370

## Solution

Added `alloc` and `std` features to `bevy_utils` (`std` is enabled by default), allowing the crate's use in `no_std` contexts.

## Testing

- CI passed locally.
- Used `bevy_utils` in a `no_std` crate as an experiment and compiled successfully.

## Migration Guide

If you were importing `bevy_utils` and setting `default_features` to `false`, but relying on elements which are now gated behind the `std` or `alloc` features, include the relevant feature in your `Cargo.toml`.

## Notes

 - Bevy already includes a single `no_std` crate, `bevy_ptr`, so there is precedent for this change.
 - As `bevy_utils` is widely used across the rest of Bevy, further work to make Bevy `no_std` compatible would be blocked on this crate, if such work was to be undertaken.
 - Most of the changes in this PR are just the removal of an unnecessary call to `to_string()` within unit tests.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Sure, this is useful enough. nostd support is part of being a good Rust citizen IMO.

For follow-up:
1. We should consider enabling the lint for using std rather than core globally, just to make this easier and reduce merge conflicts.
2. We should also consider setting up cargo-deny to enforce that our no-std crates/feature flag settings are actually std-free.

**Comment by alice-i-cecile** [comment]
Waiting on a second approval; this is contentious enough that I want at least a bit of discussion.

**Review by ItsDoot — APPROVED** [review]
If we continue to make more crates no-std compatible, we should add a no-std platform target to CI (probably non-blocking) to ensure they can actually work as no-std. Not required for this PR, though.

**Comment by bushrat011899** [comment]
> For follow-up:
>
> 1. We should consider enabling the lint for using std rather than core globally, just to make this easier and reduce merge conflicts.

That would be good!

>  2. We should also consider setting up cargo-deny to enforce that our no-std crates/feature flag settings are actually std-free.

> If we continue to make more crates no-std compatible, we should add a no-std platform target to CI (probably non-blocking) to ensure they can actually work as no-std. Not required for this PR, though.

I'm not very familiar with the CI-side of Bevy, but I do agree it would be nice to make some guarantees that can be checked by CI.

**Pull request merged**
