### PR TITLE
Fix the batching in `many_buttons` by giving each of the leaf nodes a global `ZIndex`

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Fix the batching in `many_buttons` by giving each of the leaf nodes a global `ZIndex`.

# Changelog

* Gave each of the text leaf nodes in the `many_buttons` a global `ZIndex` to improve batching.

### CODE REVIEW

**Review by nicoburns — CHANGES_REQUESTED** [review]
Hmm.... seems like it kinda defeats the point of a stress test if you're reducing the stress in a way which doesn't apply to most applications.

From what I've read the correct way to solve this is to use "z buffer" so that nodes with different z-indexes can still be batched together with proper occlusion being handled by the GPU.

**Comment by ickshonpe** [comment]
It is bit of a hack but a very simple one. Drawing a grid of labelled nodes is a common task and it's not great that the only example of that is really inefficient. 
I suppose maybe we could just add a comment to the example that says if are you doing this for real add a ZIndex,

**Comment by nicoburns** [comment]
> Drawing a grid of labelled nodes is a common task and it's not great that the only example of that is really inefficient

Oh, I thought that the point of the `many_buttons` example was more as benchmark than an actual example. I guess this makes more sense if it actually intended to be an example.

**Comment by ickshonpe** [comment]
No, I think you're probably right, I'll close this for now. It's an easy way to hack around the current UI perf problems but yeah it'd be better to fix them properly in the renderer. like you say.

**Pull request closed without merging**
