### PR TITLE
Resurrecting flappy_bevy (adopted, rewritten)

### PR DESCRIPTION
**Pull request by richchurcher**
# Objective

I mostly did this as an exercise, so I'm not sure if it really belongs in the examples or not. However, I thought it might be an interesting opportunity to introduce some of the ideas in `bevy_new_2d` to the examples.

My concern is that it's a lot to pack into a single-file structure. I'd like some takes on whether this is likely to be useful to new Bevy devs, and if it turns out the answer is "no" I'll happily move onto the next thing :sunglasses: 

The original PR is here: https://github.com/bevyengine/bevy/pull/4923 by `af-games`, and some of their original code survives. My implementation is still a little flaky (hence the WIP) but I thought I should get some quick takes on the idea before putting more time into it.

# Showcase

A hasty screenshot, as a reminder of what the idea was: lots of bevy icons with a little drift written in to separate 'em as they, er, flap.

image

### CODE REVIEW

**Comment by richchurcher** [comment]
@janhohenheim given your familiarity with the quickstart, perhaps you could weigh in when you have the time?

**Comment by richchurcher** [comment]
Other possibilities might include rewriting one of the existing examples to use an updated structure, or making this a "normal" flappy bird to keep the complexity down.

**Comment by janhohenheim** [comment]
Will review in detail later this week. 
Not your fault at all, but in general I heavily dislike the "example game in a single big file" pattern we have been cultivating so far.

**Comment by richchurcher** [comment]
> Will review in detail later this week. Not your fault at all, but in general I heavily dislike the "example game in a single big file" pattern we have been cultivating so far. Works great for generic examples, but I feel like this is the wrong way to go about showing newcomers how games are structured.

Don't review it in detail! That's not a good use of your time. I kinda agree, I just wasn't sure how to proceed. We may need some kind of separate repo for simple sample games, in the long run. Keeping them from getting bit rot is I guess the main issue. Maybe one 2D, one 3D, and one simple desktop application. But even that is quite a bit of maintenance scope.

**Comment by janhohenheim** [comment]
Can we not create a dir like `/examples/games/flappy/` and split up the files there?

**Comment by alice-i-cecile** [comment]
I think we should a) avoid adding new game examples to the repo in favor of more complex templates b) don't shove them all into a single file c) pick more compelling game examples that provide a more useful base to work off of.

Closing :)

**Pull request closed without merging**
