### PR TITLE
Update winit version 0.27.3

### PR DESCRIPTION
**Pull request by ar37-rs**
- Recent winit (version 0.27.3) also has compat for raw-window-handle 0.4.2
- Tested on desktop, native and wasm

### CODE REVIEW

**Comment by harudagondi** [comment]
There is already a previous PR (#5347) that updates winit (and other dependencies). Afaik this is blocked on wgpu.

**Comment by ar37-rs** [comment]
@harudagondi, it's winit 0.27.3 (not < than that), working fine i've tested both native including mouse_grab example and other on wasm as well.

**Comment by ar37-rs** [comment]
not sure for android though, since we are waiting winit 0.28.0 for more compact andorid support like: https://github.com/rib/android-activity

**Comment by harudagondi** [comment]
It's [`winit = 0.27`](https://github.com/bevyengine/bevy/pull/5347/files#diff-430ff15c09fecc41f366f88d7aac221cf60b43f87b36ed396673213aefa0ef16R25), which means `>=0.27.0, <0.28.0`, so it would pick `0.27.3`. Also as far as I understand, this PR have not updated ndk-glue to `0.7`.

**Comment by ar37-rs** [comment]
@harudagondi the problem wgpu blocked was on winit 0.27.2 which has raw-window-handle 4.2 compat problem, already fixed on 0.27.3

**Comment by harudagondi** [comment]
Hmm. I'll admit I have minimal knowledge on rendering, but in that PR [`raw-window-handle` is changed to 0.5](https://github.com/bevyengine/bevy/pull/5347/files#diff-826ca515bd860d3e5e5a035f6b47f4f2808925cc9f0f3df21d1988ead959bc36R19). Maybe we should ask why it is that case.

**Comment by mockersf** [comment]
Update for grab mode seems better in #5347. This update would also need to update `ndk-glue`. I don't know about `raw-window-handle` though.

wgpu update should be within the week, let's wait for it.

**Comment by ar37-rs** [comment]
@mockersf agree on that.

**Comment by alice-i-cecile** [comment]
Closing in favor of #6218, which is nearly ready to merge :) Thanks for scouting this out!

**Pull request closed without merging**
