### PR TITLE
[Merged by Bors] - Add license files to all published crates

### LINKED ISSUE #4719: Missing licenses in sub crates of bevy project
The published crates for bevy_macro_utils do not contain any license texts.
However, both the MIT and Apache-2.0 license terms require that redistributed sources contain a copy of the license text.

For example, choosealicense.com lists this under "Conditions" for both licenses:

- https://choosealicense.com/licenses/apache-2.0/
- https://choosealicense.com/licenses/mit/

The sources for this crate live [here](https://github.com/bevyengine/bevy/tree/main/crates/bevy_macro_utils
), and don't link any license files.

Looks like none of the crates that are published for the bevy project do, and the license files are only included in the [docs folder](https://github.com/bevyengine/bevy/tree/main/docs
).

Your own published crates are not in line with the licenses you chose.

### PR DESCRIPTION
**Pull request by NiklasEi**
# Objective

Add our licenses to every published crate

Fixes #4719

## Solution

- Copy licenses to every crate before publishing

### CODE REVIEW

**Comment by bjorn3** [comment]
Symlinks are not universally supported on Windows. I believe you need to enable developer mode on windows and enable symlink support when installing git. Otherwise git will represent symlinks as files containing the name of the target I believe.

**Comment by NiklasEi** [comment]
> Symlinks are not universally supported on Windows. I believe you need to enable developer mode on windows and enable symlink support when installing git. Otherwise git will represent symlinks as files containing the name of the target I believe.

Is that a problem here? I tested `cargo package` and it seems to put copies of the symlinked files into the package.

**Comment by mockersf** [comment]
if @cart is still using [this script](https://github.com/bevyengine/bevy/blob/main/tools/publish.sh) to publish, the script could just copy the license before publishing

**Comment by NiklasEi** [comment]
> if @cart is still using [this script](https://github.com/bevyengine/bevy/blob/main/tools/publish.sh) to publish, the script could just copy the license files before publishing

That's an alternative, but then we would have to use `--allow-dirty` for the publish command or check the copied files in. I wouldn't be really happy with any of those two options.

**Comment by mockersf** [comment]
Oh right, forgot about the dirty 🙁

**Comment by james7132** [comment]
Does [`license-file`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) allow relative paths outside of the crate directory? Or does this not work because we need two different licenses?

**Comment by cart** [comment]
Arg I _really_ don't want to duplicate our licenses a million times throughout the codebase. I'd like a single source of truth and as little "noise" as possible in the repo.

symlinks are better than duplication, but they still increase repo noise (and as mentioned, aren't great on windows), so I _think_ I prefer updating the publish script to do the copy. `--allow-dirty` is a bit regrettable, but it is "scoped" hackery. We could run git commands to the script to clear the working directory before publishing, which would protect against "dirt" (at the cost of potentially accidentally losing changes).

**Comment by alice-i-cecile** [comment]
It's so noisy, but I do want these licenses to show up properly on crates.io 🤔

**Review by alice-i-cecile — APPROVED** [review]

**Review by cart — APPROVED** [review]
TIL about pushd + popd. Looks good to me!

**Pull request closed without merging**
