### PR TITLE
[Merged by Bors] - add support for loading animations in `scene_viewer` example

### PR DESCRIPTION
**Pull request by jakobhellermann**
The `scene_viewer` example can be used to load and display glTF scenes. This PR also adds the ability to play animations in the file and cycle through them.

https://user-images.githubusercontent.com/22177966/161443011-0365c7de-c49e-44c4-b0f7-44330a015a4f.mp4

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Awesome!

**Comment by alice-i-cecile** [comment]
@cart, with this change merged in I think we should really showcase the scene_viewer example in the release notes for 0.7.

**Comment by HackerFoo** [comment]
Nice! One thing that would make this viewer more useful is handling the [`DroppedFile`](https://docs.rs/bevy/latest/bevy/prelude/enum.FileDragAndDrop.html#variant.DroppedFile) event.

Also, for anyone trying this to see the animation above:

```
cargo run --example scene_viewer assets/models/animated/Fox.glb
```

**Review by HackerFoo — APPROVED** [review]

**Pull request closed without merging**
