### PR TITLE
Implement `From<f32>` for `Val`

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Implement `From<f32>` for `Val`, returning a `Val:Px` value, and replace `Val` functions parameters with `impl Into<Val>`, so users can ellide the `Val::Px` variant specifier. 

Ergonomics aside, it's probably more robust too as it seems much easier to confuse `Val:Percent(100.)` with `Val::Px(100.)` than `100.`.

## Solution
Implement `From<f32>` for `Val`.
Change `Size` and `UiRect` to functions to non-const and replace the `Val` parameter with `impl Into<Val>`

# Changelog
* implemented `From<f32>` for `Val`
* replaced 'Val' function parameters with `impl Into<Val>` and made those functions non-const where necessary.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Hmm. I don't love it. At least for me, it seems hard to keep track of whether the From impl turns it into pixels or percents (or ems or mm or...)

**Comment by ickshonpe** [comment]
Well, it mirrors the CSS behaviour where `px` is the default if you don't specify a unit type.

**Comment by alice-i-cecile** [comment]
CSS is often full of these "clever" tricks and implicit behavior. I'm not convinced that's a model to emulate, although I do agree that specifying values is far too verbose for now.

My personal preference would be to include the `Val` enum variants in the bevy_ui prelude.

**Comment by IceSentry** [comment]
Another option could be to have short functions that would look like this:

```rust
pub fn px(v: f32) -> Val {
	Val::Px(v)
}
```

but don't make it part of the prelude because I think this would pollute the scope too much. This could probably be in a `bevy_ui::helpers` or something.

Essentially, do something similar to what glam does with `vec2(x, y)`/`vec3(x, y, z)`.

I don't really like the idea of adding more stuff to the prelude, especially when it's really short/generic stuff because it becomes really easy to clash with other things.

**Comment by ickshonpe** [comment]
The problem with helper functions I was thinking of about is that for some style properties, like border values, the `Auto` variant of `Val' is meaningless. Taffy has different `LengthPercentage` and `LengthPercentageAuto` types for this reason. And if there is a new type introduced then, as far I can tell, helper functions couldn't be made that would work with both types.

**Comment by ickshonpe** [comment]
The dissatisfaction with this pr for me is that it doesn't help when directly accessing fields. So it's probably not worth it.

**Comment by nicoburns** [comment]
> And if there is a new type introduced then, as far I can tell, helper functions couldn't be made that would work with both types.

This is possible. See Taffy's style_helpers module https://github.com/DioxusLabs/taffy/blob/main/src/style_helpers.rs The trick is to make the return type of the helper generic over a trait and implement that trait for each type you want the helper to work with. Bevy could potentially even use Taffy's traits and helper functions, and implement them for it's own types.

**Pull request closed without merging**
