### PR TITLE
Apply clippy::use_self

### PR DESCRIPTION
**Pull request by EdJoPaTo**
# Objective

When looking through the changes #14782 would produce I noticed another lint (`clippy::use_self`) that should be quite neat here (and solves some of `unused_qualifications` cases already which is why I don't want to supply a PR for both at the same time.)

In a bunch of cases `Self` is already used near the suggestion to use `Self` of `use_self`. So I assume this is accepted code which this lint enforces further in the future.

## Solution

Add `clippy::use_self` (and alphabetically sort its lints) and mostly `--fix` its way through the code. `cargo fmt` results in less lines for the same code afterwards. Also removed some empty lines here and there.

I also manually fixed the false-negative https://github.com/rust-lang/rust-clippy/issues/12381 in the cases I noticed.

`--fix` didn't work in `bevy_ecs` which turned out to be a clippy false-positive: https://github.com/rust-lang/rust-clippy/issues/13277

## Testing

`cargo clippy` still seems to be happy. `cargo run -p ci` seems to work too. (It produces some errors of this kind, but it doesn't seem relevant for this PR: `Could not set global logger and tracing subscriber as they are already set. Consider disabling LogPlugin.`)

Reviewing this is probably quite messy as this changes hundreds of files. This will likely also produce many merge conflicts. I am happy to integrate other merged branches for some time if interest in merging this is there. But similar to #10749 it shouldn't stay open for too long due to its amount of affected files.

### CODE REVIEW

**Review by janhohenheim — APPROVED** [review]
Way nicer for refactoring names. There are some cases where I wouldn't use `Self`, but the pros outweigh the cons imo

**Comment by BD103** [comment]
I'm in favor of this for its consistency, but I haven't looked through each file yet.

**Comment by EdJoPaTo** [comment]
> Way nicer for refactoring names.

Personally I think it's not only nicer for refactoring. It's also quite nice when reading code as its instantly clear something is exactly the given type. `fn some_magic(&self, whatever: &Self)` is easy to read even when the `impl Whatever` is further away or multiple quite similar structs like `Line` and `Lines` exist. So to me, it also reduces confusion when reading code.

**Comment by alice-i-cecile** [comment]
I don't think we should do this. This is a noisy change, and more importantly, I prefer the other style. When reviewing / reading code snippets, it's much harder to constantly keep track of what scope we're in, rather than just using the names. This has been attempted before in #4152 and was rejected by maintainers there. Closing this out as well, sorry.

**Pull request closed without merging**
