### PR TITLE
Link broken on AppTypeRegistry 

### LINKED ISSUE #6281: Link broken on `AppTypeRegistry`
## How can Bevy's documentation be improved?

https://dev-docs.bevyengine.org/bevy/app/struct.AppTypeRegistry.html

This should point to https://dev-docs.bevyengine.org/bevy/reflect/struct.TypeRegistryInternal.html.

Maybe we should make the internal type `pub`? I'll defer to @mockersf @MrGVSV @PROMETHIA-27 on that point.

### PR DESCRIPTION
**Pull request by ZarakiKanzaki**
# Objective

- The idea is to fix a dead link in the docs
- Fixes #6281

## Solution

- I replaced the link to the one suggested by the users in the  thread

---

### CODE REVIEW

**Comment by mockersf** [comment]
this is still a dead link for me when building doc locally

**Comment by ZarakiKanzaki** [comment]
> this is still a dead link for me when building doc locally

What's seems strange to me is that if we reference something inside the same namespace we have no problem, while if it's something related to another it seems to break, like in our case, there might be something I'm missing?

**Comment by mockersf** [comment]
I think I remember seeing a few issues in rustdoc about links between re-exported crates when the link wasn't available as is through the main crate... we have that issue in other parts of Bevy doc. But it may not be the same thing...

Sorry, I don't have better advice than "try different path for the type and build locally to check it works" 😞

**Comment by ZarakiKanzaki** [comment]
@mockersf Alrighty! I'll check some of this issues asap 😊

**Comment by mockersf** [comment]
no dead links for me anymore, this was probably fixed by rustdoc

**Pull request closed without merging**
