### PR TITLE
[Merged by Bors] - Decouple some dependencies

### PR DESCRIPTION
**Pull request by bjorn3**
# Objective

Reduce from scratch build time.

## Solution

Reduce the size of the critical path by removing dependencies between crates where not necessary. For `cargo check --no-default-features` this reduced build time from ~51s to ~45s. For some commits I am not completely sure if the tradeoff between build time reduction and convenience caused by the commit is acceptable. If not, I can drop them.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I'm unsure about:

- Removing thiserror usage in bevy_reflect

I agree with all other changes. I am particularly happy with the changes to `bevy_derive`; I was poking my nose into that code recently and this is a more sensible approach.

**Comment by alice-i-cecile** [comment]
bors try

**Comment by bjorn3** [comment]
I dropped "Remove the thiserror usage in bevy_reflect", enabled the full syn feature for bevy_reflect_derive too and removed another unused dependency.

**Comment by mockersf** [comment]
I would prefer to have less different crates depending on `uuid`, that's kind of a pain... but I guess that's part of the speedup

**Comment by bjorn3** [comment]
I dropped the uuid change. This reduces the savings for `cargo check --no-default-features` a bit, but this PR still gives a worthwhile improvement from 48s to 40s. Ready for review.

**Review by mockersf — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]
LGTM. That's a sizable win on build times.

**Comment by bjorn3** [comment]
Rebased

**Comment by alice-i-cecile** [comment]
bors retry

**Pull request closed without merging**
