### PR TITLE
[Merged by Bors] - Camera Output Modes, MSAA Writeback, and BlitPipeline

### LINKED ISSUE #5721: UI only shows if in last pass
## Bevy version

f1be89d45809c71c7d3f9f341f99e80780d69b20

## Relevant system information

Tested on MacOS and iOS, with 4x MSAA

## What you did

I used `UiCameraConfig` to enable `show_ui` on only one pass that was not the last pass (using camera priority.)

## What went wrong

The UI did not show, but I could see it was being rendered using the Metal debugger.

## Additional information

I suspected that the wrong color attachment was being used, so that the rendered UI was accidentally discarded.

So I made the following changes:

```diff
diff --git a/crates/bevy_ui/src/render/pipeline.rs b/crates/bevy_ui/src/render/pipeline.rs
index e199cef52..7914d3b8f 100644
--- a/crates/bevy_ui/src/render/pipeline.rs
+++ b/crates/bevy_ui/src/render/pipeline.rs
@@ -105,7 +105,7 @@ impl SpecializedRenderPipeline for UiPipeline {
             },
             depth_stencil: None,
             multisample: MultisampleState {
-                count: 1,
+                count: 4,
                 mask: !0,
                 alpha_to_coverage_enabled: false,
             },
diff --git a/crates/bevy_ui/src/render/render_pass.rs b/crates/bevy_ui/src/render/render_pass.rs
index 66445c92a..9308b7a26 100644
--- a/crates/bevy_ui/src/render/render_pass.rs
+++ b/crates/bevy_ui/src/render/render_pass.rs
@@ -81,14 +81,10 @@ impl Node for UiPassNode {
         };
         let pass_descriptor = RenderPassDescriptor {
             label: Some("ui_pass"),
-            color_attachments: &[Some(RenderPassColorAttachment {
-                view: &target.view,
-                resolve_target: None,
-                ops: Operations {
-                    load: LoadOp::Load,
-                    store: true,
-                },
-            })],
+            color_attachments: &[Some(target.get_color_attachment(Operations {
+                load: LoadOp::Load,
+                store: true,
+            }))],
             depth_stencil_attachment: None,
         };
```

and it works as expected now, but it's probably not necessary to use MSAA for the UI, so I'm not sure what the correct way to do this is. Obviously hardcoding the multisample count is a bad idea; it would have to be passed through the key if this is actually the correct solution.

### LINKED ISSUE #7361: Bloom not restricted to cameras with BloomSettings?
## Bevy version

- latest main
- bevy 0.9
- PR #6677 as of 1/27

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

I want bloom to be applied only to a subset of my scene, so I added a separate camera with `BloomSettings`.

```rust
use bevy::{
    core_pipeline::{bloom::BloomSettings, clear_color::ClearColorConfig},
    prelude::*,
    render::view::RenderLayers,
    sprite::MaterialMesh2dBundle,
};

fn main() {
    App::new()
        .insert_resource(ClearColor(Color::rgb(0.1, 0.1, 0.1)))
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup)
        .run();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    let no_bloom_layer = RenderLayers::layer(0);
    let bloom_layer = RenderLayers::layer(1);

    commands.spawn((
        Camera2dBundle {
            camera: Camera {
                hdr: true,
                ..default()
            },
            ..default()
        },
        no_bloom_layer,
    ));

    commands.spawn((
        Camera2dBundle {
            camera_2d: Camera2d {
                clear_color: ClearColorConfig::None,
                ..default()
            },
            camera: Camera {
                hdr: true,
                order: 1,
                ..default()
            },
            ..default()
        },
        bloom_layer,
        BloomSettings {
            threshold: 0.5,
            ..default()
        },
    ));

    let (saturation, lightness, alpha) = (0.8, 0.7, 1.0);

    // Circle
    commands.spawn((
        MaterialMesh2dBundle {
            mesh: meshes.add(shape::Circle::new(100.).into()).into(),
            material: materials.add(ColorMaterial::from(Color::Hsla {
                hue: 180.,
                saturation,
                lightness,
                alpha,
            })),
            transform: Transform::from_translation(Vec3::new(-125., 0., 0.)),
            ..default()
        },
        no_bloom_layer,
    ));

    // Hexagon
    commands.spawn((
        MaterialMesh2dBundle {
            mesh: meshes
                .add(shape::RegularPolygon::new(100., 6).into())
                .into(),
            material: materials.add(ColorMaterial::from(Color::Hsla {
                hue: 120.,
                saturation,
                lightness,
                alpha,
            })),
            transform: Transform::from_translation(Vec3::new(125., 0., 0.)),
            ..default()
        },
        bloom_layer,
    ));
}
```

## What went wrong

`BloomSettings` is only on the camera that renders the hexagon, so I expected only the hexagon to get bloom.

Instead, both shapes get bloom.

image

## Additional information

It's not clear if this is user error, a known limitation, or a bug.

### LINKED ISSUE #7435: Post processing doesn't work correctly when using multiple viewports
## Bevy version

0.9 and main

## What you did

In the split_screen example: 
- Enable hdr on both cameras (enabling hdr only on one also breaks bevy, but this is a separate issue).
- Add `BloomSettings::default()` to the left camera
- Use an emissive color for the plane

image

I would have expected the left viewport to have bloom applied to it.

## What went wrong

The bloom effect does not appear in the left viewport.

As you can see here, the bloom effect is indeed computed and generated correctly, but once it gets to the final upscaling pass, the texture modified by the post process is not used as an input.
image

image

I haven't investigated more than that, but it seems like the upscaling node is using the wrong texture when using multiple viewports combined with post processing.

### PR DESCRIPTION
**Pull request by cart**
# Objective

Alternative to #7490. I wrote all of the code in this PR, but I have added @robtfm as co-author on commits that build on ideas from #7490. I would not have been able to solve these problems on my own without much more time investment and I'm largely just rephrasing the ideas from that PR.

Fixes #7435
Fixes #7361
Fixes #5721

## Solution

This implements the solution I [outlined here](https://github.com/bevyengine/bevy/pull/7490#issuecomment-1426580633).

 * Adds "msaa writeback" as an explicit "msaa camera feature" and default to msaa_writeback: true for each camera. If this is true, a camera has MSAA enabled, and it isn't the first camera for the target, add a writeback before the main pass for that camera.
 * Adds a CameraOutputMode, which can be used to configure if (and how) the results of a camera's rendering will be written to the final RenderTarget output texture (via the upscaling node). The `blend_state` and `color_attachment_load_op` are now configurable, giving much more control over how a camera will write to the output texture.
 * Made cameras with the same target share the same main_texture tracker by using `Arc<AtomicUsize>`, which ensures continuity across cameras. This was previously broken / could produce weird results in some cases. `ViewTarget::main_texture()` is now correct in every context.
 * Added a new generic / specializable BlitPipeline, which the new MsaaWritebackNode uses internally. The UpscalingPipelineNode now uses BlitPipeline instead of its own pipeline. We might ultimately need to fork this back out if we choose to add more configurability to the upscaling, but for now this will save on binary size by not embedding the same shader twice.
 * Moved the "camera sorting" logic from the camera driver node to its own system. The results are now stored in the `SortedCameras` resource, which can be used anywhere in the renderer. MSAA writeback makes use of this.

---

## Changelog

- Added `Camera::msaa_writeback` which can enable and disable msaa writeback.
- Added specializable `BlitPipeline` and ported the upscaling node to use this.
- Added SortedCameras, exposing information that was previously internal to the camera driver node.
- Made cameras with the same target share the same main_texture tracker, which ensures continuity across cameras.

### CODE REVIEW

**Comment by IceSentry** [comment]
This might be a bit too advanced to have the example in the repo, but do you have a gist of how you would use this to fix https://github.com/bevyengine/bevy/issues/7435? I'm not entirely sure how I would need to use this to make it work correctly.

**Comment by cart** [comment]
@IceSentry the msaa writeback (which is enabled by default in this pr) should fix #7435 automatically. When I made the changes to split_screen mentioned in that issue, bloom showed up on the left side as expected.

**Comment by rparrett** [comment]
Ditto #7361

**Comment by cart** [comment]
@rparrett this also works as expected by default for me.

**Comment by rparrett** [comment]
> @rparrett this also works as expected by default for me.

With the example in #7361, I would expect the hexagon to get bloom, but with this PR, the circle does.

**Comment by cart** [comment]
@rparrett haha yup you're right.

First: I needed to re-add the bloom upsampling alpha blending from the other PR. (see latest commit).

From there, this camera setup works, which configures what amounts to the same setup from #7490:

```rust
    // No special config required here. This will write to the output texture by default 
    commands.spawn((
        Camera2dBundle {
            camera: Camera {
                hdr: true,
                ..default()
            },
            ..default()
        },
        no_bloom_layer,
    ));

    commands.spawn((
        Camera2dBundle {
            camera_2d: Camera2d {
                // Transparent clear color to ensure this layers on top of the output correctly
                clear_color: ClearColorConfig::Custom(Color::NONE),
                ..default()
            },
            camera: Camera {
                hdr: true,
                // Disable MSAA writeback as we don't want the last camera's outputs it in our
                // intermediate multisampled textures
                msaa_writeback: false,
                order: 1,
               // Write to the output texture, but load the previous state + blend 
                output_mode: CameraOutputMode::Write {
                    blend_state: Some(BlendState::ALPHA_BLENDING),
                    color_attachment_load_op: LoadOp::Load,
                },
                ..default()
            },
            ..default()
        },
        bloom_layer,
        BloomSettings {
            threshold: 0.5,
            intensity: 1.0,
            ..default()
        },
    ));
```

**Comment by cart** [comment]
Also for completeness I will confirm that #5721 works out of the box now.

**Review by robtfm — APPROVED** [review]
just one typo to prove i read it. 

i think personally i'd prefer having the more intelligent defaults, definitely for writeback and maybe for the clear color, but this does expose everything needed as it stands.

**Comment by cart** [comment]
> i think personally i'd prefer having the more intelligent defaults, definitely for writeback and maybe for the clear color, but this does expose everything needed as it stands.

I'm definitely down to explore something closer to the "smarts" of your previous impl for writeback (maybe in an opt-in, but enabled by default fashion). Feel free to follow this up if you're interested. (not for 0.10 though :smile: )

**Pull request closed without merging**
