### PR TITLE
Update to glam 0.28

### PR DESCRIPTION
**Pull request by superdump**
**NOTE: This depends on `encase` and `hexasphere` being updated to use glam 0.28 as well!**

# Objective

- Update `glam` to 0.28. Adds AArch64 NEON optimizations.

## Testing

I tested `many_cubes --benchmark` on an M1 Max. Frustum culling sees a 25% decrease in media frame time:

Screenshot 2024-06-10 at 13 06 59

Overall frame time when run through tracy didn't change much, oddly, as when running without tracy I saw about a 25% overall frame time reduction from eyeballing the frame times being printed to the terminal.

---

## Changelog

- For changes see: https://github.com/bitshifter/glam-rs/blob/0.28.0/CHANGELOG.md#0280---2024-06-10

## Migration Guide

- For migration see: - For changes see: https://github.com/bitshifter/glam-rs/blob/0.28.0/CHANGELOG.md#0280---2024-06-10

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
We're blocked on hexasphere and encase still, correct?

**Comment by superdump** [comment]
> We're blocked on hexasphere and encase still, correct?

Yup, added to the description now.

**Comment by waywardmonkeys** [comment]
https://github.com/teoxoy/encase/pull/73

**Comment by mnmaita** [comment]
Pushed https://github.com/OptimisticPeach/hexasphere/pull/20. Hopefully we also get a new tag on `hexasphere`.

**Comment by mnmaita** [comment]
`[hexasphere](https://crates.io/crates/hexasphere)` v13.0.0 is out now with the `glam` version bump (that was fast!).

**Comment by teoxoy** [comment]
encase v0.9 is up on crates.io

**Review by IQuick143 — APPROVED** [review]
Code changes all seem good.

**Comment by alice-i-cecile** [comment]
@superdump let me know when encase and hexasphere are bumped too and I'll merge this in :)

**Comment by alice-i-cecile** [comment]
Closing as adopted.

**Pull request closed without merging**
