### PR TITLE
Update hexasphere to 5.0.0

### PR DESCRIPTION
**Pull request by OptimisticPeach**
I made a mistake in creating the cubesphere api for other users. There should be no visible changes to the API on Bevy's end.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by OptimisticPeach** [comment]
I don't believe that the CI failure here is my fault... Any thoughts?

**Comment by cart** [comment]
Yup the unused-dependencies step is a network error. The check-advisories failure is a known issue. We should probably just disable it until we can fix it (which needs to wait for a wgpu upgrade ... which needs to wait on Rust 2021 releasing)

**Comment by cart** [comment]
Its already disabled on bors, so that won't block merging this.

**Comment by OptimisticPeach** [comment]
Cool! It's great to hear it.

**Comment by mockersf** [comment]
already merged in #2880

**Pull request closed without merging**
