### PR TITLE
Added new method remove to PluginGroup, also adds unit tests for PluginGroup

### PR DESCRIPTION
**Pull request by blaind**
As requested in #2166

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
why not use the `disable` method?

**Comment by blaind** [comment]
> why not use the `disable` method?

The root use case here is to reconfigure `RenderPlugin` with other config (needed, because some initialization is done in `build` method that depends on the configuration). `disable` won't work for that

```
pub fn add_plugins_fn(group: &mut PluginGroupBuilder) -> &mut PluginGroupBuilder {
    group.remove::<bevy_render::RenderPlugin>();
    group.add_after::<bevy_scene::ScenePlugin, _>(bevy_render::RenderPlugin {
        base_render_graph_config: Some(bevy_render::render_graph::base::BaseRenderGraphConfig {
            add_2d_camera: false,
            add_3d_camera: false,
            add_xr_camera: true,
            ..Default::default()
        }),
    });

    group
}
```

**Comment by mockersf** [comment]
the bug on disabling a plugin and reading it with another config is fixed in #2039 👍

**Comment by blaind** [comment]
That's great! I guess renders this PR as obsolete. Seems to contain tests as well

**Comment by alice-i-cecile** [comment]
Are we good to close this PR then? :)

**Comment by blaind** [comment]
> Are we good to close this PR then? :)

Ok for me, if there's no other use cases for the remove method

**Comment by alice-i-cecile** [comment]
I don't see any other immediate application of this functionality so I'm going to close this for now. This can be revived if a use case comes up :)

**Pull request closed without merging**
