### PR TITLE
support running bevy off the main thread

### PR DESCRIPTION
**Pull request by lee-orr**
# Objective

Adds support for running bevy off the main thread on Windows & Linux. This would be useful for embedding bevy (with it's built in winit plugin) in a non-bevy app while allowing sharing data using things like channels rather than inter-process communication. It's also needed by my hot-reload plugin, which currently forks bevy-winit.

## Solution

Set up a `window-off-main` feature for bevy-winit, and if so set the winit `with_any_thread` flag to true on supported systems.

---

## Changelog
- Added a `window-off-main` feature to bevy-winit, bevy-internal and bevy
- Added 3 feature & target gated sections - one for windows, one for wayland and one for x11 - each containing a single function call to set `with_any_thread`.
- Added a `window_off_main` example in the "window" section of the examples folder, and added the corresponding reference in the readme and in the root cargo.toml

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
For context, this PR is needed to enable https://crates.io/crates/dexterous_developer to work.

**Comment by lee-orr** [comment]
@alice-i-cecile - FYI, I was able to find another approach for dexterous_developer today, so it is not longer necessary for that. I still think this can be a useful option, but since I'm able to use bevy_winit as is now it's less urgent.

**Comment by mockersf** [comment]
what happens on linux if both `x11` and `wayland` features are enabled?

**Comment by lee-orr** [comment]
> what happens on linux if both `x11` and `wayland` features are enabled?

I have not been able to manually test on both, but based on my understanding from the winit docs I'd guess it'll set the flag for both of them, and then choose at runtime based on the existing mechanism (using WINIT_UNIX_BACKEND I believe).

**Pull request closed without merging**
