### PR TITLE
Add subgroup

### PR DESCRIPTION
**Pull request by BD103**
# Objective

Sometimes a `PluginGroup` requires another `PluginGroup`, like `DefaultPlugins`. The previous solution to this was:

```rust
use bevy::prelude::*;
use bevy::app::PluginGroupBuilder;

struct GamePlugins;

impl PluginGroup for GamePlugins {
    fn build(&mut self, group: &mut PluginGroupBuilder) {
        DefaultPlugins.build(group);

        // Add more plugins here...
    }
}
```

This feels backwards, even though it is correct.

## Solution

Add a quality-of-life function that merges another group into the current one.

```rust
use bevy::prelude::*;
use bevy::app::PluginGroupBuilder;

struct GamePlugins;

impl PluginGroup for GamePlugins {
    fn build(&mut self, group: &mut PluginGroupBuilder) {
        group.add_subgroup(DefaultPlugins);

        // Add more plugins here...
    }
}
```

---

## Changelog

Added `PlugingGroupBuilder::add_subgroup()`.

## Reasoning

My game is structured in a set of plugins. All you need to do is call `App::new().add_plugins(GamePlugins).run()`. This ensures that all the required plugins are registered. If `main.rs` has to also register `DefaultPlugins`, but doesn't, then my game would break. To fix this, I attach the default plugins as seen in the first example. I was dissatisfied with how that broke the flow of the code, so I wrote this function to fix it.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
I like this API; I think that this helps make the logic clearer when working with plugin groups.

Great work with the doc tests, and the PR writeup did a great job motivating this change.

I think this would be worth adding to the plugin group example, but I won't block on it.

**Comment by BD103** [comment]
Thanks for the feedback! I'll look into adding an example.

**Comment by BD103** [comment]
I have updated the example to show using `add_subgroup`. As long as that looks good, this PR is ready to merge.

**Review by alice-i-cecile — APPROVED** [review]
Example looks good. This needs one more review from the community before I can merge it; perhaps ask in #general-dev on Discord?

**Comment by alice-i-cecile** [comment]
I'll ask for you then :) No worries!

**Review by james7132 — COMMENTED** [review]
This current implementation rebuilds the entire plugin group it depends on. If done from multiple plugin groups declaring them as dependencies, you'll reregister everything under that dependency N times. This is clearly not desirable in the general case. We need explicit deduplication before this should be considered.

**Comment by alice-i-cecile** [comment]
Blocked on #69 then.

**Review by Sheepyhead — APPROVED** [review]

**Comment by BD103** [comment]
It's been a while since there's been activity here. Should I close the PR or leave it open?

**Comment by alice-i-cecile** [comment]
Let's close this out per the comment from James; we can always reopen in the future.

**Comment by BD103** [comment]
Ok, I won't delete my fork though until this gets resolved.

**Pull request closed without merging**
