### PR TITLE
[Merged by Bors] - unused dep references?

### PR DESCRIPTION
**Pull request by gilescope**
Got a hunch ( from undepend ) that these are not needed.

### CODE REVIEW

**Comment by NiklasEi** [comment]
At least the `bevy_reflect` dependency of `bevy_input` is needed (see the red CI build). Did Bevy build locally after making these changes?

**Comment by mockersf** [comment]
We are using https://crates.io/crates/cargo-udeps in CI to detect unused dependencies

**Comment by bjorn3** [comment]
cargo-udeps is not completely accurate. undepend works by actually compiling the source after removing candidate unused dependencies, which should be more accurate than cargo-udeps, but it seems not in this case.

**Review by mockersf — APPROVED** [review]

**Review by NiklasEi — APPROVED** [review]

**Pull request closed without merging**
