### PR TITLE
Add builder methods for `UiTextureAtlasImage`

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

Implement builder methods for `UiTextureAtlasImage`.

## Solution
 Copy the methods from `UiImage`  except with an index parameter for `new` instead of an image handle.

### CODE REVIEW

**Review by mwbryant — APPROVED** [review]
Looks like a simple straightforward usability plus!  I see no reason to not merge

**Review by IQuick143 — APPROVED** [review]
Seems good to me, I don't see a reason not to merge.

**Comment by ickshonpe** [comment]
I had forgotten about this PR, I thought that it had been merged ages ago. 
`UiImage` and `UiTextureAtlasImage` should have the same interface as far as possible, so it needs to be merged.

**Review by IQuick143 — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@ickshonpe once this is rebased / main is merged in I'll merge this PR. CI is failing because of a missing required check.

**Comment by TrialDragon** [comment]
`UiTextureAtlasImage` was removed in 135c724; this PR can be safely closed.

**Pull request closed without merging**
