### PR TITLE
Add gamepad_stick_input example 

### PR DESCRIPTION
**Pull request by targrub**
## Objective
(from https://github.com/bevyengine/bevy/pull/3721 writeup by mfdorst)
In pursuit of https://github.com/bevyengine/bevy/issues/3691 I felt that it would be handy to have a way to visualize the gamepad stick input.

## Solution
Add an example that shows gamepad stick input.

Rebase of https://github.com/bevyengine/bevy/pull/3721
See that for all comments.

### CODE REVIEW

**Comment by targrub** [comment]
I'm hoping someone will review this with an eye to recommended Bevy practices.  For example, the way ClearColor is used I believe may be outdated.

**Comment by rparrett** [comment]
Moving some feedback from the other PR here:

I would prefer that we use the default window size and rework this so that the zones are displayed in the middle of the screen. If we were to put this example as it is now onto https://bevyengine.org/examples/, it ends up very large size because it maintains the square aspect ratio.

**Comment by targrub** [comment]
> I would prefer that we use the default window size and rework this so that the zone squares are displayed in the middle of the screen. If we were to put this example as it is now onto https://bevyengine.org/examples/, it would up very large size because it maintains the square aspect ratio.

Since the bounds are -1.0 to 1.0 for both dimensions on the gamepad stick, I feel a square aspect ratio is most appropriate.  I'll set the window to a square size of the minimum dimension, keeping within the window's `WindowConstraints`.

> There's no issue with the way `ClearColor` is being used here.

 Thanks.

**Comment by rparrett** [comment]
> Since the bounds are -1.0 to 1.0 for both dimensions on the gamepad stick, I feel a square aspect ratio is most appropriate. I'll set the window to a square size of the minimum dimension, keeping within the window's `WindowConstraints`.

I am saying that the bounds can / possibly should be completely independent of the window size. Just show a 200x200 (or whatever) box in the middle of the window.

**Comment by targrub** [comment]
I left in setting the window title, but removed my other "window stuff."  Set input range box at 300x300 in middle of window.

**Comment by rparrett** [comment]
Another box below the others to visualize the full bounds would be helpful now.

**Comment by targrub** [comment]
I'm not equipped to make changes much beyond what I've done, since I don't have a gamepad.

**Comment by alice-i-cecile** [comment]
Closing in favor of #6074; I think they serve very similar purposes and we should refine the base in that PR <3

**Pull request closed without merging**
