### PR TITLE
Fix reflected serialization/deserialization on `Name` component

### PR DESCRIPTION
**Pull request by coreh**
# Objective

- This PR makes it so that `ReflectSerialize` and `ReflectDeserialize` traits are properly derived on `Name`. This avoids having the internal hash “leak” into the serialization when using reflection.

## Solution

- Added a conditional derive for `ReflectDeserialize` and `ReflectSerialize` via `#[cfg_attr()]`

---

## Changelog

- `Name` now implements `ReflectDeserialize` and `ReflectSerialize` whenever the `serialize` feature is enabled.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by MrGVSV — APPROVED** [review]

**Comment by MrGVSV** [comment]
Since this is technically a breaking change, could you add a migration guide?

**Review by matiqo15 — APPROVED** [review]

**Review by doonv — APPROVED** [review]

**Comment by coreh** [comment]
> Since this is technically a breaking change (i.e. existing scenes could now be invalid and/or expectations of what's included in the serialized output), could you add a migration guide?

Just saw this now, but the PR is already merged. 😕 Are we using the reflection (de)serialization for scenes? In this case I can add an entry to the migration guide, will the release script still pick it up even after the PR is merged? Will we need to include it manually later when writing the notes?

**Comment by MrGVSV** [comment]
> Are we using the reflection (de)serialization for scenes?

Yep! It's what powers the scene system essentially.

> In this case I can add an entry to the migration guide, will the release script still pick it up even after the PR is merged? Will we need to include it manually later when writing the notes?

I believe the script is only run towards the end of the cycle. So it should pick it up if you add it now.

**Comment by coreh** [comment]
@MrGVSV Ended up adding backwards compatibility to the old format: https://github.com/bevyengine/bevy/pull/11485

This should give people time to more easily migrate.

**Comment by Testare** [comment]
This doesn't seem to be working in 0.13?

**Pull request merged**
