### PR TITLE
[Merged by Bors] - Rename shapes examples for consistency

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

I was about to submit a PR to add these two examples to `bevy-website` and re-discovered the inconsistency.

Although it's not a major issue on the website where only the filenames are shown, this would help to visually distinguish the two examples in the list  because the names are very prominent.

This also helps out when fuzzy-searching the codebase for these files.

## Solution

Rename `shapes` to `2d_shapes`. Now the filename matches the example name, and the naming structure matches the 3d example.

## Notes

@Nilirad proposed this in https://github.com/bevyengine/bevy/pull/4613#discussion_r862455631 but it had slipped away from my brain at that time.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Merging as trivial :)

bors r+

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
example need to be renamed here too: https://github.com/bevyengine/bevy/blob/e7cd9c1b8629d0d851f74d4d129ec8832457e8f5/.github/workflows/validation-jobs.yml#L150

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Pull request closed without merging**
