### PR TITLE
Remove bitflags for ci

### PR DESCRIPTION
**Pull request by lewiszlw**
# Objective

-  Fixes https://github.com/bevyengine/bevy/issues/8421

## Solution

- Replace bitflags with a struct with a bunch of bool fields.

### CODE REVIEW

**Comment by CGMossa** [comment]
Can this not be an array?

**Comment by nicopap** [comment]
It could be a struct with a bunch of `bool` fields (which is what a bitfield is, just less compact). Given the diff, I doubt using a "more traditional" approach is much cleaner. The only difference is the `bitfields!` macro being replaced by an enum and a list of values. It's much harder to decipher intent in the later case than the former IMO.

bitfields are used to solve exactly the kind of problem it is used for: list of yes/no options.

enums are not used to model a list of options, they are in fact used to model several mutually exclusive options. The introduction of a `Vec<Check>` works around this limitation. But it muddies the meaning by adding complexity. It also introduces invalid states, for example: what does it mean to have two `Check::Test` in the `Vec`?

Maybe the structs with a lot of bool fields is cleaner? Since it models a list of options as well. I'd like to see it, like:

```rust
struct Check {
    format: bool,
    clippy: bool,
    compile_fail: bool,
    test: bool,
    doc_test: bool,
    doc_check: bool,
    bench_check: bool,
    example_check: bool,
    compile_check: bool,
}
```

It's not as optimized as the bitfields of course! But that is what #8421 was referring to when it said "it doesn't need optimization".

**Comment by mockersf** [comment]
I'm not sure I agree with the original issue, I find this PR increases complexity of the script. And it doesn't really remove a dependency anyway...

**Review by alice-i-cecile — APPROVED** [review]
I think that this is much simpler for contributors to understand and modify. Bitflags are quite complex for no good reason here IMO and it's hard to tell how we would extend this to more options in the future.

Not a huge fan of the `all` method, but I'm not convinced it's worth pulling in `strum` just for this.

**Comment by alice-i-cecile** [comment]
I would also be completely fine with the struct full of booleans instead.

**Comment by lewiszlw** [comment]
Refactored to a struct with a bunch of bool fields.

**Review by nicopap — COMMENTED** [review]
I don't think it's better than bitfields, but I think it is better than the enum. I entirely blame rustfmt for the longer diff, can't do much about it, it forces struct declarations to span multiple lines.

**Comment by lewiszlw** [comment]
I'm ok if we want to keep bitfields.

**Comment by JoJoJet** [comment]
Since the original PR was closed as not planned, I'm gonna close out this one too. Thanks for the PR, it's a shame it didn't end up being an improvement like we thought it would.

**Pull request closed without merging**
