### PR TITLE
Run the on enter schedule for states in startup instead of in StateTransitions

### LINKED ISSUE #7633: OnEnter schedule runs later than expected for default states
## Bevy version

main branch a1e4114ebee5b903a95dc1438b4f0d946ac3c8be

## What you did

I am trying to update a Plugin using States to the latest Bevy main. The plugin relies on "on enter" systems to prepare for certain user-configured states.

```rust
fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_state::<AppState>()
        .add_system_to_schedule(OnEnter(AppState::Start), prepare_state)
        .add_system(relies_on_prepare_state.in_base_Set(CoreSet::PreUpdate).run_if(in_state(AppState::Start)))
       .run();
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, States)]
enum AppState {
    #[default]
    Start,
    Next,
}
```
## What went wrong

If e.g. `prepare_state` initializes resources that the system `relies_on_prepare_state` asks for, the app will panic, because these resources will not be in the ECS. It works fine if we change the state to be `Next` and add a single system switching to the `Next` state.

The default states `onEnter` schedule is run in the first `CoreSet::StateTransitions`. But the `State` resource will already have the default value from the beginning. This means that systems running before`CoreSet::StateTransitions`, see an unexpected situation: The state resource says that we are currently in state "X" (so systems only running in that state will run), but the `OnEnter` schedule of state "X" has not been executed yet. 

The minimum here would be to very clearly document that any systems relying on states should only run after `CoreSet::StateTransitions`.

### PR DESCRIPTION
**Pull request by NiklasEi**
# Objective

- Currently, the `OnEnter` Schedule for default states (the states that an app is in from the beginning) run in `StateTransitions`. This has the unexpected effect, that systems running before `StateTransitions` already see the state resource with the default value, but the on enter systems have not run yet.
- resolves #7633

## Solution

- Run the `OnEnter` schedule for default states in start-up systems

~Alternatively, one could move the `StateTransitions` to before `PreUpdate`. Is there a reason it runs later? I would like to have a set for plugins to insert systems that should run before user logic, but do not have frame lag concerning state changes.~

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
> Alternatively, one could move the StateTransitions to before PreUpdate. Is there a reason it runs later? I would like to have a set for plugins to insert systems that should run before user logic, but do not have frame lag concerning state changes.

Generally the idea here was to allow users to do things like "read input and then apply a state transition" without getting any delay. Can you put your systems in `ApplyStateTransitions` before `apply_state_transition`? Or do they also want to run before `PreUpdate`?

**Review by alice-i-cecile — APPROVED** [review]

**Comment by hymm** [comment]
Not sure this is the right fix as now the OnEnter systems that run in Startup may behave differently than the ones in StateTransistions. Since there is a different system ordering to them. i.e. Startup runs before First and PreUpdate and StateTransitions runs after.

**Comment by NiklasEi** [comment]
Yes, I am also not completely happy with this. But my expectation would be: if the state resource says that I am in state "X", then the on enter systems for state "X" should have run already. That is currently not the case for early sets in the first frame and I don't see a different solution than moving the on enter systems to startup.

**Comment by NiklasEi** [comment]
I'll fix the build tomorrow. It's past midnight here 😴

**Comment by NiklasEi** [comment]
I'll fix the build tomorrow. It's past midnight here 😴

**Comment by alice-i-cecile** [comment]
> Not sure this is the right fix as now the OnEnter systems that run in Startup may behave differently than the ones in StateTransistions. Since there is a different system ordering to them. i.e. Startup runs before First and PreUpdate and StateTransitions runs after.

Yeah I'm unsure about this fix 🤔 It leads to some subtle failure cases, and the workarounds aren't bad.

**Comment by inodentry** [comment]
If you are writing a plugin that needs to add systems to run before user systems, why not just put them in a separate set and explicitly specify how you want to order them relative to state transitions?

PreUpdate is not the only place where you can put stuff to run before user systems.

With stageless, we no longer have stages. :) You are no longer limited by that design. Before, if you were to create a new stage, that could be considered invasive and bad for performance. Now you can just add systems and order them however you like.

**Comment by alice-i-cecile** [comment]
Ultimately I think this is not quite the right fix. I vote we close this for now, and see how the ecosystem handles things. Manually adding copies of `appy_state_transition<T>` in startup systems is quite easy, and a good fit for some plugins.

**Pull request closed without merging**
