### PR TITLE
[Merged by Bors] - Replace confusing links from CONTRIBUTING.md with short instruction

### PR DESCRIPTION
**Pull request by devil-ira**
# Objective
CONTRIBUTING.md contains links to pages that are restricted to Bevy Engine Org members.
First time contributors who read CONTRIBUTING.md will end up on a confusing 404 page if they try to follow the link.

Relevant discussion: #4365

## Solution

Replace links with directions to the Triage Team page.

### Note

I'm not sure if `assign themselves as a member` is accurate. I think that is what `automatically request membership` was referring to, but i can't check for myself :wink:

### CODE REVIEW

**Comment by devil-ira** [comment]
CI failure seems unrelated to my PR.
Surprisingly though it is failing on this file.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Thanks!

**Comment by cart** [comment]
Sorry one sec. Gonna make a quick change.

**Pull request closed without merging**
