### PR TITLE
texture atlas example: mark each loaded image as CPU persistent

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- After #10520, example `texture_atlas` crashes:
```
...
2024-01-03T17:58:18.478750Z  WARN texture_atlas: textures/rpg/tiles/generic-rpg-tile05.png did not resolve to an `Image` asset.
2024-01-03T17:58:18.478824Z  WARN texture_atlas: textures/rpg/tiles/generic-rpg-tile04.png did not resolve to an `Image` asset.
2024-01-03T17:58:18.478827Z  WARN texture_atlas: textures/rpg/tiles/generic-rpg-tile10.png did not resolve to an `Image` asset.
2024-01-03T17:58:18.478830Z  WARN texture_atlas: textures/rpg/tiles/generic-rpg-tile38.png did not resolve to an `Image` asset.
2024-01-03T17:58:18.478833Z  WARN texture_atlas: textures/rpg/tiles/generic-rpg-Slice.png did not resolve to an `Image` asset.
thread 'Compute Task Pool (0)' panicked at examples/2d/texture_atlas.rs:153:10:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `texture_atlas::setup`!
Encountered a panic in exclusive system `bevy_ecs::schedule::state::apply_state_transition<texture_atlas::AppState>`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

## Solution

- mark each image as CPU persistent as they are loaded

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by JMS55** [comment]
Hmm, this is kinda an unfortunate example. If we were loading sprites individually, we could use load_with_settings() and specify the persistence policy in the loader settings. Not really possible with the folder API...

We could configure meta files per sprite, but in this case I suppose this is the best way.

**Comment by alice-i-cecile** [comment]
Would a `load_folder_with_settings` API make sense here?

**Comment by JMS55** [comment]
> Would a `load_folder_with_settings` API make sense here?

Load folder is untyped, as it can load multiple different types of assets at once. I suppose we could restrict the with_settings variant to only load one type of asset, and skip the others.

**Comment by mockersf** [comment]
> Really though, we _should_ be able to still access the sprites the first frame they're loaded. So I'm not sure we need to Keep them anyways. Perhaps the asset event is getting sent a frame later?

frame 1
* trigger folder load

frame 2
* some files are loaded

frame 3
* previous images are unloaded
* new files are loaded

frame 4:
* previous images are unloaded
* new files are loaded
* folder is done loading
* trying to access all images, which fails

**Comment by JMS55** [comment]
Can you simply add each image as it finishes loading, instead of all at once at the end?

**Comment by hymm** [comment]
This fixes the example, but shouldn't we do something for texture atlases in general? Having the user manually mark all their images as persistent feels hacky.

**Comment by JMS55** [comment]
We could default to Keep for anything not loaded through the GLTF loader I suppose :thinking: .

**Comment by mockersf** [comment]
> We could default to Keep for anything not loaded through the GLTF loader I suppose 🤔 .

My personal opinion is that everything should be `Keep` by default: https://github.com/bevyengine/bevy/pull/11212

**Pull request closed without merging**
