### PR TITLE
[Merged by Bors] - Useful changes with relicensing benefits

### PR DESCRIPTION
**Pull request by DJMcNab**
This obsoletes #1111 and #2445, since @ColonisationCaptain and @temhotaokeaha haven't replied to #2373.

I believe that both of those PRs would be fine to keep, but they're even more fine to keep now :)

### CODE REVIEW

**Comment by cart** [comment]
I think you mentioned the wrong person. `@CleanCut` has replied (and isn't the author of #1111).

**Comment by DJMcNab** [comment]
Indeed, you're the second person to point that out. I've already edited it.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by cart** [comment]
Cool cool. I think we should delete cases like this from the list instead of checking them off (to avoid thinking they agreed to the relicense).

**Comment by cart** [comment]
Eh we should add a "changes obsoleted" category and move them there.

**Comment by cart** [comment]
Updated #2373

**Pull request closed without merging**
