### PR TITLE
[Merged by Bors] - Compute Pipeline Specialization

### LINKED ISSUE #3970: Compute Shader Integration
## What problem does this solve or what need does it fill?

For now Bevy does not have a dedicated compute pipeline abstraction, but only exposes the raw wgpu API for this use case.
The [game of life example](https://github.com/bevyengine/bevy/blob/main/examples/shader/compute_shader_game_of_life.rsl) shows how to implement your own compute pipelines.

Currently there is no way to use Bevy's shader abstraction(shader defs, shader imports and hot shader reloading) for compute, which makes writing those shaders quite cumbersome. 

## What solution would you like?

I would like to have a way of turning a `Handle<Shader>` into a `ShaderModule`, which can be use for creating the compute pipeline.
For the render pipelines we use a `RenderPipelineCache`, which intern stores a `ShaderCache`, for processing the shaders.
We probably need something similar for compute pipelines (`ComputePipelineCache`), or we decouple the `ShaderCache` entirely from the `RenderPipelineCache` to cache all shaders in a single place (resource).

### PR DESCRIPTION
**Pull request by Ku95**
# Objective

- Fixes #3970
- To support Bevy's shader abstraction(shader defs, shader imports and hot shader reloading) for compute shaders, I have followed carts advice and change the `PipelinenCache` to accommodate both compute and render pipelines.

## Solution

- renamed `RenderPipelineCache` to `PipelineCache`
- Cached Pipelines are now represented by an enum (render, compute)
- split the `SpecializedPipelines` into `SpecializedRenderPipelines` and `SpecializedComputePipelines`
- updated the game of life example

## Open Questions

- should `SpecializedRenderPipelines` and `SpecializedComputePipelines` be merged and how would we do that?
- should the `get_render_pipeline` and `get_compute_pipeline` methods be merged?
- is pipeline specialization for different entry points a good pattern

### CODE REVIEW

**Comment by Ku95** [comment]
Clippy complains, that the newly introduced `PipelineDescriptor` has two variants with a large size difference. https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
I think it is fine to just ignore it since there wont be too many pipelines for it to really matter, but what do you think?

**Comment by superdump** [comment]
So I guess we should try `Box`ing them and see if it has any negative impact on performance?

**Comment by Ku95** [comment]
> So I guess we should try `Box`ing them and see if it has any negative impact on performance?

Ok, will do that later. 😃

**Comment by Ku95** [comment]
I did something wrong while rebasing.   ...again

**Review by molikto — APPROVED** [review]

**Review by superdump — COMMENTED** [review]
This looks generally in the right ballpark. I wonder if there is a way to duplicate less of the code for render vs compute. I have a mild wonder about whether it impacts performance of render stuff in any way. Does it affect bevymark performance at all?

**Comment by cart** [comment]
Yup I like the general direction of a consolidated RenderPipeline type, although I think we might want to have separate CachedRenderPipelineId and CachedComputePipelineId (and internally remove and "switching" on compute and render pipelines). That would eliminate a class of user error where they pass a "render pipeline" CachedPipelineId into `get_compute_pipeline` (or vice versa). Likewise, it would eliminate all of the "internal switching" thats going on right now. It would mean duplicating some code, but I think its worth it.

**Comment by Ku95** [comment]
I will test performance and experiment with the distinct IDs tomorrow. 👍

**Comment by Ku95** [comment]
I have done some form of a split, but I don't really think it is much of an improvement. I still believe there is some way to make all of this pretty with some rust magic, but I am not experienced enough to see how.

**Comment by cart** [comment]
I think your changes made a good compromise between code reuse and "separate code paths". Splitting out the remaining enums would start bleeding in to the shader caching logic, which would make things pretty nasty.

I removed specialization from the game of life example as I think it hindered legibility. Imo specialization should only be used if you really need it. In this case it added over 30 lines of code / extra type complexity for no real benefit.

**Pull request closed without merging**
