### PR TITLE
Add AssetServer.load_inline to allow loading assets bundled into the binary.

### LINKED ISSUE #606: Support bundling assets
The code that loads a PNG file into a Texture seems to be tightly coupled with the AssetServer's system for loading from the filesystem. It would be good to be able to use `include_bytes!` to bundle the file content but still take advantage of Bevy's support for loading assets of various types. It would be sufficient to add a method such as:
```rust
fn read_asset<P: AsRef<Path>, R: Read>(path: P, reader: R) -> HandleId { ... }
```
or even:
```rust
fn load_in_memory_asset<P: AsRef<Path>>(path: P, data: &[u8]) -> HandleId { ... }
```

### PR DESCRIPTION
**Pull request by emosenkis**
Fixes #606. I implemented this before seeing the fix in #619 but it presents a smaller surface and makes no changes outside of the added function so I think it's worth considering which route is preferred.

### CODE REVIEW

**Comment by emosenkis** [comment]
Ping

**Comment by cart** [comment]
Hey sorry for the delay here. I've been punting Asset-related work because we're in the process of making some pretty massive asset system changes (either by adopting Atelier or using an experimental bevy_asset rework).

**Comment by cart** [comment]
This approach won't work now that asset loaders can produce multiple asset types. I think we can achieve similar results in atelier-assets, which plans on adding "asset pack-file" support. These packfiles could theoretically be embedded directly into the binary and would probably be a better general-purpose solution to the problem.

I think we should close this out, then re-visit the scenario when atelier-assets is integrated, but I'm curious to hear your thoughts.

**Comment by emosenkis** [comment]
Well, I just saw this now, but I published a little crate that implements this without changes to Bevy itself - see [#606](https://github.com/bevyengine/bevy/issues/606#issuecomment-720676530).

**Pull request closed without merging**
