### PR TITLE
Implement "in_any_state" and "in_all_states" functions

### LINKED ISSUE #11221: Add ```in_any_state``` and ```in_all_states``` run conditions
## What problem does this solve or what need does it fill?

As games get more complex, users may find themselves wanting to setup a chain of systems to run in multiple separate states or on specific variant overlaps of multiple state types. While this is currently possible with combinator operations, it can be verbose and these patterns may be common enough to have dedicated run conditions. Searching for "or_else" on the discord yields [quite](https://discord.com/channels/691052431525675048/691052431974465548/1192648431563460798) [a](https://discord.com/channels/691052431525675048/691052431974465548/1183247743616024636) [few](https://discord.com/channels/691052431525675048/1175640997867307119/1175645113075118180) [instances](https://discord.com/channels/691052431525675048/742569353878437978/1156299973210673192) [of](https://discord.com/channels/691052431525675048/691052431974465548/1147387587347099710) [people](https://discord.com/channels/691052431525675048/691052431974465548/1141269161247506563) [asking](https://discord.com/channels/691052431525675048/1121438610512683139/1121438610512683139) (👀) how to do an OR with states.

## What solution would you like?

Add two run conditions for handling multiple states: in_any_state for OR and in_all_states for AND. There's a good example to start from [here](https://discord.com/channels/691052431525675048/742569353878437978/1156320222739976262) for the OR version.

## What alternative(s) have you considered?

Using or_else or and_then will suffice but again, it can get verbose
```rust
.run_if(in_state(AppState::InGame).or_else(in_state(OtherState::PreGame)).or_else(in_state(AppState::TitleScreen)))
```
versus
```rust
.run_if(in_any_state([AppState::InGame, OtherState::PreGame, AppState::TitleScreen]))
```

## Additional context

The "in_any_state" may be a bit more useful than the "in_all_states" as the latter is only useful if you're using multiple types of States. Additionally, depending on changes like #9942 this might get more complicated or be handled differently anyway?

### PR DESCRIPTION
**Pull request by garychia**
# Objective

- Fixes #11221

## Solution

- Implement the `in_any_state` and `in_all_states` functions.

---

## Changelog

Added `in_any_state` and `in_all_states` functions.

### CODE REVIEW

**Review by doonv — APPROVED** [review]

**Comment by rparrett** [comment]
I'm not sure if `in_all_states` is useful as-is, restricted to a single state type.

**Comment by BD103** [comment]
Perhaps this could be implemented as a macro instead? That would allow for multiple state types, though I'm not sure how it would be optimized.

```rust
.run_if(in_any_state!(AppState::InGame, GameState::Level0))

macro_rules! in_any_state {
    ($first_state:expr, $($other_state:expr),*) => {
        in_state($first_state) $(.or_else(in_state($other_state)))*
    },
}
```

I haven't tested the code so it might be completely wrong, but it conveys the general idea.

**Comment by garychia** [comment]
It may be better to add `in_any_state` only for this time. Another PR can be created to implement `in_all_states` if necessary.
I like the macro approach as it reuses existing functions but I'm not sure which approach is better.

**Comment by BD103** [comment]
> It may be better to add `in_any_state` only for this time. [...]

I'm confused, what's your reasoning behind not implementing `in_all_states`? You already have the code for it.

**Comment by garychia** [comment]
> > It may be better to add `in_any_state` only for this time. [...]
> 
> I'm confused, what's your reasoning behind not implementing `in_all_states`? You already have the code for it.

I'm just wondering if we really need `in_all_states`. It seems that `in_all_states` is limited to special cases?

**Comment by BD103** [comment]
> I'm just wondering if we really need `in_all_states`. It seems that `in_all_states` is limited to special cases?

I would ask around on the Discord and see how much people would benefit from either of the functions. Macros can be... weird to maintain, since adding `#[macro_export]` to them exports them from the root of the crate. You can't really export them from a module, such as `schedule`, without `#[doc(hidden)]` and `pub use crate::my_macro`.

**Pull request closed without merging**
