### PR TITLE
[Merged by Bors] - Rename `headless_defaults` example to `no_renderer` for clarity

### PR DESCRIPTION
**Pull request by LegNeato**
# Objective

- Reduce confusion as the example opens a window and isn't truly "headless"
- Fixes https://github.com/bevyengine/bevy/issues/5260.

## Solution

- Rename the example and add to the docs that the window is expected.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Much clearer!

**Comment by LegNeato** [comment]
Will fix CI in a bit

**Comment by alice-i-cecile** [comment]
@Shatur @DJMcNab, please review when you get a chance :)

**Review by Shatur — APPROVED** [review]

**Review by DJMcNab — APPROVED** [review]

**Review by LoipesMas — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]

**Pull request closed without merging**
