### PR TITLE
Use previous ubuntu version in validation jobs

### PR DESCRIPTION
**Pull request by cart**
# Objective

xvfb is failing to start, likely due to a Mesa update. This has happened before: https://github.com/bevyengine/bevy/pull/6810

https://github.com/bevyengine/bevy/actions/runs/7359665469/job/20034758381

## Solution

Swap ubuntu-latest for ubuntu-20.04 (the previous ubuntu version) for the failing jobs. Lets hope this works!

We should revert this once ubuntu-latest is working again.

### CODE REVIEW

**Comment by cart** [comment]
I've cherry-picked the commit from this PR because clippy is also broken: https://github.com/bevyengine/bevy/pull/11123/commits

**Comment by stepancheg** [comment]
Seems like this change is no-op.

[ubuntu-latest was aliased to 22.04 for a year](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/).

Something different was changed (no idea).

**Comment by alice-i-cecile** [comment]
Adoption of https://github.com/bevyengine/bevy/pull/11123

**Comment by stepancheg** [comment]
I suspect we need something like this:

```sh
xvfb-run --error-file=$TMPDIR/xvfb-run.log ... || cat $TMPDIR/xvfb-run.log
```

**Comment by hymm** [comment]
could try pinning the mesa versions. Maybe something like this?
```text
sudo apt install -y xvfb libegl1-mesa=23.3.1~kisak1~f libgl1-mesa-dri=23.3.1~kisak1~f libxcb-xfixes0-dev mesa-vulkan-drivers=23.3.1~kisak1~f
```

**Comment by hymm** [comment]
Alternative https://github.com/bevyengine/bevy/pull/11143

**Pull request closed without merging**
