### PR TITLE
Rename Add to Queue for methods with deferred semantics

### LINKED ISSUE #15106: Rename `EntityCommands::add` to `EntityCommands::queue`
## What problem does this solve or what need does it fill?

The difference between these two is very hard to grasp from a naming point of view:

```rust
commands
  .entity(entity)
  .insert(Foo)
```

```rust
commands
  .entity(entity)
  .add(Foo)
```

## What solution would you like?

Rename `add` to `queue`. That also reflects that the changes happen *later*, not *now*.

## What alternative(s) have you considered?

Just leave it

## Additional context

@alice-i-cecile likes this as well :P

### PR DESCRIPTION
**Pull request by BenjaminBrienen**
# Objective

- Fixes #15106

## Solution

- Trivial refactor to rename the method. The duplicate method `push` was removed as well. This will simpify the API and make the semantics more clear. `Add` implies that the action happens immediately, whereas in reality, the command is queued to be run eventually.
- `ChildBuilder::add_command` has similarly been renamed to `queue_command`.

## Testing

Unit tests should suffice for this simple refactor.

---

## Migration Guide

- `Commands::add` and `Commands::push` have been replaced with `Commnads::queue`.
- `ChildBuilder::add_command` has been renamed to `ChildBuilder::queue_command`.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Can you replace https://docs.rs/bevy/latest/bevy/hierarchy/struct.ChildBuilder.html#method.add_command as part of this PR?

**Comment by BenjaminBrienen** [comment]
> Can you replace https://docs.rs/bevy/latest/bevy/hierarchy/struct.ChildBuilder.html#method.add_command as part of this PR?

I've already renamed it to `enqueue_command`. I guess I should mention that in the description as well! Let me know if I've misunderstood you and indeed forgot a refactor.

**Comment by alice-i-cecile** [comment]
Aha, I missed it! I've updated the migration guide in your PR.

**Review by alice-i-cecile — APPROVED** [review]

**Review by NthTensor — APPROVED** [review]
Surprised this isn't a larger change. I like this much better.

Do we want to do the same with `EntityCommands`?

**Comment by alice-i-cecile** [comment]
> Do we want to do the same with `EntityCommands`?

Yes please!

**Comment by BenjaminBrienen** [comment]
So instead of `insert_reflect` we have `enqueue_reflect`? All the ones that wrap around `commands.enqueue`, I assume.

**Review by janhohenheim — APPROVED** [review]
Happy to see this resolved so quickly, thanks :)

**Review by NiseVoid — APPROVED** [review]

**Comment by NiseVoid** [comment]
> So instead of `insert_reflect` we have `enqueue_reflect`? All the ones that wrap around `commands.enqueue`, I assume. If so, then we'd also be renaming `InsertReflectWithRegistry`.

I think @NthTensor was referring to `EntityCommands::add`

**Comment by janhohenheim** [comment]
@BenjaminBrienen yeah, looks like you missed [this one](https://docs.rs/bevy/latest/bevy/ecs/system/struct.EntityCommands.html#method.add). The reflect stuff doesn't need to be touched :)

**Comment by alice-i-cecile** [comment]
> So instead of `insert_reflect` we have `enqueue_reflect`? All the ones that wrap around `commands.enqueue`, I assume. If so, then we'd also be renaming `InsertReflectWithRegistry`.

`insert_reflect` is different: it adds a new component. The APIs we want to change are just those that are adding new commands directly. This semantic similarity between `add` and `insert` is a huge part of why we want this change in the first place!

**Comment by BenjaminBrienen** [comment]
> @BenjaminBrienen yeah, looks like you missed [this one](https://docs.rs/bevy/latest/bevy/ecs/system/struct.EntityCommands.html#method.add). The reflect stuff doesn't need to be touched :)

Weird. This file seems to escape VSCode's search feature. `fn add` doesn't show the file for me. Fixing now!

**Comment by alice-i-cecile** [comment]
Looks like a couple were missed in doc tests: https://github.com/bevyengine/bevy/actions/runs/10873672267/job/30170042797?pr=15234#step:5:1101

**Comment by iiYese** [comment]
Is there something better than `enqueue`? Cause if you do `.enqueue(A)` and then `.enqueue(B)` but `A` has the side effect of enqueueing `C` the effect order is `A, C, B` not `A, B, C`.

**Comment by alice-i-cecile** [comment]
> Is there something better than enqueue? Cause if you do .enqueue(A) and then .enqueue(B) but A has the side effect of enqueueing C the effect order is A, C, B not A, B, C.

I like `queue` better but I'm pretty sure I'm outvoted :p Doesn't solve the problem raised there though. IMO this is a very weird edge case: worth mentioning in the docs but not worth using a less clear name.

**Comment by atornity** [comment]
I prefer `queue` as well for what it's worth

**Comment by Shatur** [comment]
I personally liked "push" 😅 
But I also prefer "queue" to "enqueue".

**Comment by janhohenheim** [comment]
Big `queue` fan here, but also not a native speaker

**Comment by alice-i-cecile** [comment]
@BenjaminBrienen can you please swap all uses of `enqueue` to `queue`? I've heard enough!

**Comment by BenjaminBrienen** [comment]
> @BenjaminBrienen can you please swap all uses of `enqueue` to `queue`? I've heard enough!

Should I leave this "enqueue" alone?
https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/renderer/mod.rs#L152

**Comment by alice-i-cecile** [comment]
Yep, leave the rendering stuff alone for this PR. I'm also fine to leave the docs alone.

**Comment by alice-i-cecile** [comment]
Awesome. If you have a chance, please update the PR title and description to match. Otherwise I'll do it on merging tomorrow during my weekly merge train.

**Comment by alice-i-cecile** [comment]
@BenjaminBrienen doc links are broken due to the rename (scroll down the CI run...) and there's a simple merge conflict. Ping me when you've gotten to that and I'll merge it in.

**Comment by BenjaminBrienen** [comment]
@alice-i-cecile should be fixed now, just waiting on the CI :)

**Comment by BenjaminBrienen** [comment]
Sorry, now it should be good.

**Comment by BenjaminBrienen** [comment]
*now* it should be good... ?

**Pull request merged**
