### PR TITLE
[Merged by Bors] - wgpu has been moved from "wgpu-rs" to "wgpu"

### PR DESCRIPTION
**Pull request by temhotaokeaha**
Name and link update

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Review by NiklasEi — APPROVED** [review]

**Comment by NiklasEi** [comment]
@mockersf can you trigger the workflow? I don't think I can.

**Comment by mockersf** [comment]
@NiklasEi no one but Cart can trigger the workflow directly, but you should be able to run `bors try`

**Comment by DJMcNab** [comment]
@temhotaokeaha please respond in #2373 for the relicense to MIT/Apache 2.0. Thanks!

**Pull request closed without merging**
