### PR TITLE
Improve code quality of exit_on_esc_system

### PR DESCRIPTION
**Pull request by alice-i-cecile**
# Objective

- exit_on_esc system uses a less direct approach to check for inputs that's harder to read

## Solution

- Use Input resource, rather than iterating events

## Context

Alternative to #4259.

### CODE REVIEW

**Review by james7132 — APPROVED** [review]
There is a concern of having this delay by a tick given the way Input is updated. However, long term I don't think that's something we need to be concerned with for this kind of system.

**Review by KDecay — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
This seems to be breaking bors due to import duplication, so I'm going to remove it from the batch.

**Comment by alice-i-cecile** [comment]
Closing out. As @mockersf pointed out in private, I don't think the improvements here are worth it (and it's not clearer that the change is faster).

**Pull request closed without merging**
