### PR TITLE
Test entity labels, fixed corner cases, changed interface

### PR DESCRIPTION
**Pull request by payload**
* add tests for entity_labels_system
* fixed filling label_entities map
* fixed corner cases when removing entities, Labels component
* use Changed<Labels> query filter
* changed EntityLabels::get to return slice or empty slice instead of
  None or Some empty or non-empty slice

Changing the interface of EntityLabels::get is beneficial, since else
you would get different results in case there was an entity before that
with this missing label or not. You would either get None or Some(&[])
and need to handle both, which is actually not necessary.

### CODE REVIEW

**Comment by mockersf** [comment]
as mentioned [here](https://github.com/bevyengine/bevy/pull/1142#issuecomment-750725595), you shouldn't use `Changed` without changing first the stage the system runs on

goods to have more tests!

**Comment by cart** [comment]
Yup this seems good to me. We should be able to add Changed filters using this approach:

1. Add Changed filter to query
2. Move system to POST_UPDATE
3. Add a copy of the system to POST_STARTUP

Without Changed filters, the current implementation is expensive in a "very hard to justify" sort of way. (which isn't a critique of this pr. this is a critique of past @cart back when he was just building things for himself)

**Comment by cart** [comment]
Feel free to follow up with those changes (or I will if nobody else does). No harm in merging these fixes now.

**Comment by payload** [comment]
> Feel free to follow up with those changes (or I will if nobody else does). No harm in merging these fixes now.

I have a try :+1:

**Comment by payload** [comment]
> Feel free to follow up with those changes (or I will if nobody else does). No harm in merging these fixes now.

@mockersf followed up on that in #1155 :rocket:

**Pull request merged**
