### PR TITLE
Added shape::Cylinder

### PR DESCRIPTION
**Pull request by davidhof**
Added a cylinder shape to mesh.rs
image

### CODE REVIEW

**Comment by Philipp-M** [comment]
Shouldn't the top bottom planes be separate faces to preserve correct (vertex-)normals?

**Comment by davidhof** [comment]
> Shouldn't the top bottom planes be separate faces to preserve correct (vertex-)normals?

Not sure what you mean by planes? 
Its a triangle list so the order may be a bit weird (it alternates top and bottom triangles) but it should make no difference. 
And the normals are simply derived from the vertex positions.

**Comment by Philipp-M** [comment]
I mean, that the whole mesh should probably be 3 separate faces (a top/bottom face and the round face in between). For this the vertices have to be duplicated for the top and bottom part and separate normals have to be provided that show towards the up/down direction. This is necessary for e.g. correct lighting/ normal interpolation.

**Comment by davidhof** [comment]
Thanks @Philipp-M !
It definitely looks nicer now.

**Comment by cart** [comment]
Any reason for closing this other than my slow response time?

(Sorry about that by the way)

**Pull request closed without merging**
