### PR TITLE
Remove redundant math in tonemapping.

### PR DESCRIPTION
**Pull request by DGriffin91**
# Objective

- Tony McMapface has some math that cancels out.

## Solution

- Remove it.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
The math checks out.

**Comment by JMS55** [comment]
I'm not good enough at math to see this easily :sweat_smile:, @DGriffin91 do you mind writing out the derivation for me?

**Comment by DGriffin91** [comment]
> I'm not good enough at math to see this easily 😅, @DGriffin91 do you mind writing out the derivation for me?

This impl doesn't have the math: https://github.com/h3r2tic/tony-mc-mapface/blob/main/shader/tony_mc_mapface.hlsl
And I tested the output and it was the same either way.

**Review by JMS55 — APPROVED** [review]

**Comment by rparrett** [comment]
I have a feeling that the new version is more correct and the difference is too subtle for me to really make out, but the 3d examples are different before/after this PR.

Before:
bloom_3d

After:
bloom_3d

Output from `image-compare`'s "hybrid comparison" 
bloom_3d

**Pull request merged**
