### PR TITLE
Allow constraining Text in percent of window size

### LINKED ISSUE #1490: Text wrapping should work with a percent width
**Bevy version**

v0.4.0

**Operating system & version**

macOS 10.15.7

**What you did**

```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.system())
        .run();
}

fn setup(commands: &mut Commands, asset_server: Res<AssetServer>) {
    commands
        .spawn(CameraUiBundle::default())
        .spawn(TextBundle {
            text: Text {
                value: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor, nunc ac faucibus fringilla.".to_string(),
                font: asset_server.load("fonts/FiraSans-Bold.ttf"),
                style: TextStyle {
                    font_size: 60.0,
                    color: Color::WHITE,
                    ..Default::default()
                },
            },
            style: Style {
                position_type: PositionType::Absolute,
                position: Rect {
                    left: Val::Px(0.0),
                    top: Val::Px(0.0),
                    ..Default::default()
                },
                max_size: Size::new(Val::Percent(50.0), Val::Percent(100.0)),
                ..Default::default()
            },
            ..Default::default()
        });
}
```

**What you expected to happen**

I expected it to wrap the text at half the window width.

**What actually happened**

It doesn't wrap the text.  It runs right up to the right edge of the window.

**Additional information**

It seems that setting a `max_size` with `Val::Px()` works, but percent doesn't.

### PR DESCRIPTION
**Pull request by NiklasEi**
resolves #1490 

I based the extended constraint calculation on the previous code. But I find the previous and also the current implementation a bit confusing. It does not behave like I would expect it to. Could somebody explain to me why we take min and max constraints but only look at max if it is given? There doesn't seem to be any logic for the text box to be somewhere in between min and max based on e.g. screen size or other content on the screen.

That said, the corresponding issue should be fixed with this PR. If someone else would like to play around with it, I created a minimal Bevy App for testing based on the issue: https://github.com/NiklasEi/bevy_text_wrap_fix_1490

### CODE REVIEW

**Comment by tigregalis** [comment]
I think it's an oversight / incomplete implementation. I think the intent is that it works like width, min-width, max-width in css.

Also, Percent should be relative to its container, which may not necessarily be the window.

Now you could rename Percent to ViewPercent (similar to vh and vw) and it would be right.

The challenge is that Text can also be not a UI element though. So not all of these concepts would apply.

**Comment by NiklasEi** [comment]
I think Text is always UI. Text2D is a different story, but also not relevant for the code changes I did.

Good point with window not always being the container! I will look into that :)

**Comment by tigregalis** [comment]
Ah, sorry, you're right.

With respect to min_size, size and max_size, I believe the correct approach is to independently calculate each of these in terms of actual pixels. Then you take calculated_pixel_size, and clamp it between calculated_pixel_min_size and calculated_pixel_max_size:
```rust
/// Defines how min_size, size, and max_size affects the bounds of a text
/// block.
pub fn text_constraint(
    min_size: Val,
    size: Val,
    max_size: Val,
    scale_factor: f64,
    constraint: f32, // parent node's constraint
) -> f32 {
    // Needs support for percentages
    let calculated_min_size = match min_size {
        Val::Undefined | Val::Auto => 0.0,
        Val::Px(sz) => scale_value(sz, scale_factor),
        Val::Percent(sz) => scale_value((sz / 100.) * constraint, scale_factor),
    };
    let calculated_max_size = match max_size {
        Val::Undefined | Val::Auto => f32::MAX,
        Val::Px(sz) => scale_value(sz, scale_factor),
        Val::Percent(sz) => scale_value((sz / 100.) * constraint, scale_factor),
    };
    let mut calculated_size = match size {
        Val::Undefined | Val::Auto => f32::MAX,
        Val::Px(sz) => scale_value(sz, scale_factor),
        Val::Percent(sz) => scale_value((sz / 100.) * constraint, scale_factor),
    };
    // min-biased clamp (seems to be how css works)
    if calculated_size <= calculated_min_size {
        calculated_size = calculated_min_size
    } else if calculated_size >= calculated_max_size {
        calculated_size = calculated_max_size
    }
    calculated_size
}
```

**Comment by alice-i-cecile** [comment]
Closing in favor of #5502.

**Pull request closed without merging**
