### PR TITLE
[Merged by Bors] - Skinned extraction speedup

### PR DESCRIPTION
**Pull request by mockersf**
# Objective

- While animating 501 https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BrainStem, I noticed things were getting a little slow
- Looking in tracy, the system `extract_skinned_meshes` is taking a lot of time, with a mean duration of 15.17ms

## Solution

- ~~Use `Vec` instead of a `SmallVec`~~
- ~~Don't use an temporary variable~~
- Compute the affine matrix as an `Affine3A` instead
- Remove the `temp` vec

| |mean|
|---|---|
|base|15.17ms|
|~~vec~~|~~9.31ms~~|
|~~no temp variable~~|~~11.31ms~~|
|removing the temp vector|8.43ms|
|affine|13.21ms|
|all together|7.23ms|

### CODE REVIEW

**Comment by superdump** [comment]
I’d be interested to make. GlobalTransform just an Affine3A internally and not a separate representation at all, and see what impact that has on relevant systems… :)

**Comment by mockersf** [comment]
yup that would probably be faster, but also a much bigger bite to take...

**Comment by superdump** [comment]
Also, the title is incorrect. An almost 48% reduction in execution time is enormous.

**Comment by james7132** [comment]
Copying my comments from Discord:

>[2:12 PM] james7132: the temp buffer is only added in the case of a failure to fetch.
>[2:12 PM] james7132: if we can either remove the failure case
>[2:12 PM] james7132: or find another way to fail without breaking the state of the total joint buffer, we could probably save quite a bit of time

if we can avoid this double buffered copy, I think we could save quite a bit more time too.

**Comment by mockersf** [comment]
removed the need of the temp vec for 1ms extra gain 🎉

**Review by james7132 — APPROVED** [review]

**Review by cart — APPROVED** [review]
These are some tasty wins. Well done!

**Pull request closed without merging**
