### PR TITLE
Use logical coordinates for the UI layout

### PR DESCRIPTION
**Pull request by ickshonpe**
# Objective

It would be a lot more efficient and less complicated if the UI layout systems only used logical coordinates.

## Solution

Just use logical coordinates everywhere except where we can't.
Change `flex_node_system` and `FlexSurface` to use logical coordinates.

---

## Changelog

* Modified `flex_node_system` and `FlexSurface` to use logical coordinates.
* Changed the size paramter of `update_window` to a `Vec2` and renamed it to `logical_size`.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by ickshonpe** [comment]
cargo run --profile stress-test --features trace_tracy --example many_buttons -- no-text
logical_layout

**Comment by alice-i-cecile** [comment]
Yeah IMO the primary wins here are code quality. Can you fix up merge conflicts?

**Comment by ickshonpe** [comment]
> Yeah IMO the primary wins here are code quality. Can you fix up merge conflicts?

yes, will do.

**Comment by ickshonpe** [comment]
> Hmm... we ideally want to use physical coordinates in Taffy for rounding purposes (although this may not be critical for game UIs). I've been considering added a `scale_factor` configuration field to Taffy such that it takes logical units in and outputs physical units. Would that work with this approach?

Yeah, I've been looking for rounding issues but I haven't seen anything so far. If Taffy supported scale factor that would probably be ideal though. We'd just convert the physical coordinates back immediately when we update the node sizes and transforms etc.

**Comment by nicoburns** [comment]
I think this one probably ought to block on https://github.com/DioxusLabs/taffy/pull/478

**Comment by ickshonpe** [comment]
Yep, I'm not sure about this one at all now.

#8720 fixes a lot of the same problems, and doesn't have any of the possible negatives that this has.

**Comment by alice-i-cecile** [comment]
I'm going to close this in favor of #8720; we can revisit it later if y'all change your minds :)

**Pull request closed without merging**
