### PR TITLE
Added some missing dependencies for Linux

### PR DESCRIPTION
**Pull request by TCROC**
@jakobhellermann and I found that bevy on linux was missing some dependencies here: https://github.com/orhun/kmon/issues/2

Here is the part of the discussion that he found it: https://discord.com/channels/691052431525675048/789987800014651412/847858021907300352

And here is the entire discussion: https://discord.com/channels/691052431525675048/789987800014651412/847854179312468009

### CODE REVIEW

**Comment by cart** [comment]
Hmm these dependencies look really internal / nasty. Are we sure there isn't some "parent package" that should be installed instead?

**Comment by TCROC** [comment]
I'm not sure.  All I know is I couldn't compile or run the bevy program without those dependencies and I already had those ones that are currently in the Linux dependencies installed.

**Comment by TCROC** [comment]
Is there a way we can query the package database for a parent package containing this dependencies?

**Comment by TCROC** [comment]
@jakobhellermann Found a parent package that is much cleaner.  I updated the PR accordingly: ``libxcb-xfixes0-dev``

https://discord.com/channels/691052431525675048/789987800014651412/848988258721464401

**Comment by mockersf** [comment]
A little googling seems to indicate that libxcb (X c-binding) goal is to replace Xlib, that we're already adding as a dependency as libX11.

I don't know which is the way to go, but I don't think we should have both

**Comment by TCROC** [comment]
@mockersf How far away are they from that goal?  Currently it doesn't work and leaves things broken for Ubuntu users such as myself.  Once they reach the goal, then I agree that we should remove the package.

**Comment by mockersf** [comment]
> @mockersf How far away are they from that goal? 

No idea...

> Currently it doesn't work and leaves things broken for Ubuntu users such as myself.

I don't think it is... Our CI is using ubuntu and it works. The packages installed by default are listed [here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#installed-apt-packages) and we install a few additional: https://github.com/bevyengine/bevy/blob/22eddfcc55209264849339b9b32498bdec5c2c55/.github/workflows/ci.yml#L32

Could you check on a clean ubuntu?

**Comment by TCROC** [comment]
@mockersf I'll spin up a VM when I get a spare moment and see what happens.

**Comment by alice-i-cecile** [comment]
I'm going to close this out for now; the CI argument is compelling to me. If you can reproduce it feel free to open it back up or make a new PR.

**Pull request closed without merging**
