### PR TITLE
[Merged by Bors] - Fix post_processing and shader_prepass examples

### LINKED ISSUE #6799: Importing bevy_pbr::mesh_view_types imples defining MAX_DIRECTIONAL_LIGHTS
## Bevy version

Main @ `e954b8573`

## What you did

I did this in a shader:

```wgsl
#import bevy_pbr::mesh_view_types
```

Because I wanted the definition of the `Globals` struct to re-use in my own shader.

## What went wrong

```text
error: expected constant, found '#'
   ┌─ wgsl:59:49
   │
59 │     directional_lights: array<DirectionalLight, #{MAX_DIRECTIONAL_LIGHTS}u>,
   │                                                 ^ expected constant
```

### theories about what might be going wrong

Importing `bevy_pbr::mesh_view_types` implies that this value is defined.

### workarounds that you used

1. I could redefine the `Globals` struct, but I would like to not repeat that.
2. I currently add 
```rust
shader_defs: vec![ShaderDefVal::Int("MAX_DIRECTIONAL_LIGHTS".to_string(), 1)],
```
to my code and that works. But this feels like something I should not have to do.

### LINKED ISSUE #6996: Shaderdef values break shader imports
## Bevy version

All commits after d44e86507f66d2cbe2472557d2a2abb9c4f80a83

## What you did

Followed migration instructions in the PR.

## What went wrong

Shader error with:

```
2022-12-21T07:05:18.759671Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: expected constant, found '#'
   ┌─ wgsl:44:49
   │
44 │     directional_lights: array<DirectionalLight, #{MAX_DIRECTIONAL_LIGHTS}u>,
   │                                                 ^ expected constant
````

## Additional information

It appears that PR #5900 breaks imports, because those imports now depend on shaderdefs which users may not have available. In my case, I was attempting to import:

```
#import bevy_pbr::mesh_view_types
```

so I could use the `View` struct, which was giving me the error posted above. The problem was that the import was bringing `struct`s into scope that referred to the `MAX_DIRECTIONAL_LIGHTS` shaderdef, which my shader did not use. Specifically, it was erroring when it reached `struct Lights`:

```
struct Lights {
    // NOTE: this array size must be kept in sync with the constants defined in bevy_pbr/src/render/light.rs
    directional_lights: array<DirectionalLight, #{MAX_DIRECTIONAL_LIGHTS}u>,
```

### LINKED ISSUE #7375: shader_prepass example is broken
## Bevy version

first bad commit is c3a46822e14003970e2de0ea20ca09839a64d913

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

- `cargo run --example shader_prepass`
- press space bar

## What went wrong

Depth information in grayscale should be shown, but it's just a black screen.

There's some error output:

```
2023-01-26T21:15:17.623605Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: expected constant, found '#'
   ┌─ wgsl:38:41
   │
38 │     cascades: array<DirectionalCascade, #{MAX_CASCADES_PER_LIGHT}>,
   │                                         ^ expected constant


2023-01-26T21:15:17.842460Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: expected constant, found '#'
   ┌─ wgsl:38:41
   │
38 │     cascades: array<DirectionalCascade, #{MAX_CASCADES_PER_LIGHT}>,
   │                                         ^ expected constant

```

### PR DESCRIPTION
**Pull request by superdump**
# Objective

- Fix `post_processing` and `shader_prepass` examples as they fail when compiling shaders due to missing shader defs
- Fixes #6799
- Fixes #6996
- Fixes #7375 
- Supercedes #6997
- Supercedes #7380 

## Solution

- The prepass was broken due to a missing `MAX_CASCADES_PER_LIGHT` shader def. Add it.
- The shader used in the `post_processing` example is applied to a 2D mesh, so use the correct mesh2d_view_bindings shader import.

### CODE REVIEW

**Comment by superdump** [comment]
I feel we should make a separate view uniform shader import and use it everywhere as they're all constructed in the same way from the same struct. I also feel like I made a PR doing this a long time ago... maybe.

**Comment by IceSentry** [comment]
> I feel we should make a separate view uniform shader import 

Yeah, that does seem like a better fix. I originally tried reusing the MeshPipeline::specialize for the prepass, but it didn't work. I don't remember exactly why. It does seem possible to extract the common part to a separate function that could be used in both places.

**Review by IceSentry — APPROVED** [review]

**Review by robtfm — APPROVED** [review]
> I feel we should make a separate view uniform shader import and use it everywhere as they're all constructed in the same way from the same struct. I also feel like I made a PR doing this a long time ago... maybe.

i've done that at least once too, as part of #6738. also noting this fix would be covered by #5703

**Comment by rparrett** [comment]
Does this also close #7375?

**Comment by superdump** [comment]
Oh, I saw the markdown lint failure that seemed to just be an intermittent docker issue. I'll fix that.

**Review by superdump — COMMENTED** [review]
bors r+

**Pull request closed without merging**
