### PR TITLE
Expose Pipeline Compilation Zero Initialize Workgroup Memory Option

### PR DESCRIPTION
**Pull request by atlv24**
# Objective

- wgpu 0.20 made workgroup vars stop being zero-init by default. this broke some applications (cough foresight cough) and now we workaround it. wgpu exposes a compilation option that zero initializes workgroup memory by default, but bevy does not expose it.

## Solution

- expose the compilation option wgpu gives us

## Testing

- ran examples: 3d_scene, compute_shader_game_of_life, gpu_readback, lines, specialized_mesh_pipeline. they all work
- confirmed fix for our own problems

---

</details>

## Migration Guide

- add `zero_initialize_workgroup_memory: false,` to `ComputePipelineDescriptor` or `RenderPipelineDescriptor` structs to preserve 0.14 functionality, add `zero_initialize_workgroup_memory: true,` to restore bevy 0.13 functionality.

### CODE REVIEW

**Review by aevyrie — APPROVED** [review]
Can this be added to the default impl of `RenderPipelineDescriptor` so this doesn't break the next time someone adds it and decides to set it to false? Maybe a constructor even?

**Review by IceSentry — APPROVED** [review]

**Comment by IceSentry** [comment]
RenderPipelineDescritptor can't impl Default because of the VertexState. But the compute one could I guess.

**Comment by atlv24** [comment]
not sure if it makes sense to add a blanket Default impl, but per-field defaults would be nice. this is something that rust kinda lacks tbh

**Comment by atlv24** [comment]
i kinda like it
```rs
#[derive(Default)]
pub enum WorkgroupMemoryInitialization {
    #[default]
    Zeroed,
    Uninitialized,
}

impl From<WorkgroupMemoryInitialization> for bool {
    fn from(init: WorkgroupMemoryInitialization) -> bool {
        match init {
            WorkgroupMemoryInitialization::Zeroed => true,
            WorkgroupMemoryInitialization::Uninitialized => false,
        }
    }
}
```

**Comment by aevyrie** [comment]
> i kinda like it

Yeah, this feels like a much more idiomatic solution. You can also add some docs to the type!

**Comment by atlv24** [comment]
i'll do it monday

**Pull request merged**
