### PR TITLE
Implement `Spawn` trait

### PR DESCRIPTION
**Pull request by MiniaczQ**
# Objective

- Implement part of #14231 

## Solution

- Implement `Spawn` trait that provides `spawn_empty` and `spawn` API
- It's implemented for `World`, `Commands`, `WorldChildBuilder` and `ChildBuilder `

## Migration Guide

- `Spawn` was added to `bevy::prelude`, but will have to be included manually if prelude is not used.

### CODE REVIEW

**Comment by MiniaczQ** [comment]
After going through all the code for this, I think `Spawn` may be too specific,
we could include `entity(Entity) -> Self::SpawnOuyput` as well, since it shares the return type,
but we'd need a better name than `Spawn`

**Comment by MiniaczQ** [comment]
I'll fix docs after we agree on the code, it's a pain to maintain at all time

**Comment by benfrankel** [comment]
Not a full review yet but one note: Since `Spawn::SpawnOutput` is not given any bounds, generic contexts won't be able to do anything besides return it:

```rust
fn foo<C: Spawn>(commands: C) -> C::SpawnOutput {
    commands
        .spawn_empty()
        .insert(...) // Error
        .with_children(...) // Error
}
```

**Comment by MiniaczQ** [comment]
I'm getting the easy traits out first, hopefully we can get a few in 0.14.1

The trait for `EntityCommands` and `WorldMutEntity` is pretty controversial imo, since the mutation would be either deferred or immediate and that's something to consider

**Comment by benfrankel** [comment]
Deferred vs immediate is already the case for `Commands as Spawn` vs `Worlds as Spawn`, no?

**Review by benfrankel — CHANGES_REQUESTED** [review]

**Comment by benfrankel** [comment]
Naming proposition:
- `Spawn` -> `EntityContext`
- `Spawn::SpawnOutput` -> `EntityContext::EntityBuilder`

Or something along these lines.

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
I want to see a more cohesive overview of which traits would be used, and what they would be implemented for. I don't think this is wise to merge piecemeal, although I am in favor of the broad idea.

**Comment by MiniaczQ** [comment]
> I want to see a more cohesive overview of which traits would be used, and what they would be implemented for. I don't think this is wise to merge piecemeal, although I am in favor of the broad idea.

If we can't do it piecewise then this will turn into a large scale PR that will need to be for 0.15, in that case I'm closing the issue in favor of future discussion in #14231 with this as an example

**Pull request closed without merging**
