### PR TITLE
Re-export smallvec crate from bevy_utils

### LINKED ISSUE #10932: Re-export smallvec crate from bevy_utils
This is a useful type, and re-exporting it makes it easier for users (and other bevy sub-crates) to use, while ensuring the same version is used to prevent duplicate dependencies. 

Could also use arrayvec, which is what wgpu/taffy uses iirc.

### PR DESCRIPTION
**Pull request by DavJCosby**
Matches versioning & features from other Cargo.toml files in the project.

# Objective
Resolves #10932 

## Solution
Added smallvec to the bevy_utils cargo.toml and added a line to re-export the crate. Target version and features set to match what's used in the other bevy crates.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
For the crates that rely on bevy_utils already, we should use this re-export instead.

**Comment by DavJCosby** [comment]
Got a little tripped up with bevy_reflect's smallvec compiler feature, but I think I've got it now.

All bevy sub-crates that used smallvec were also using bevy_utils, so I was able to get them all moved over. If we'd like to upgrade from 1.6 to 1.11, this should make it easier.

**Comment by alice-i-cecile** [comment]
Yep, feel free to upgrade in this PR.

**Comment by DavJCosby** [comment]
This should be ready for review btw

**Review by alice-i-cecile — APPROVED** [review]

**Review by james7132 — APPROVED** [review]

**Pull request merged**
