### PR TITLE
[Merged by Bors] - Apply buffers in `ParamSet`

### PR DESCRIPTION
**Pull request by DJMcNab**
# Objective

- Fix https://github.com/bevyengine/bevy/issues/4676

## Solution

- Fixes https://github.com/bevyengine/bevy/issues/4676
- I have no reason to think this isn't sound, but `ParamSet` is a bit spooky

### CODE REVIEW

**Comment by BoxyUwU** [comment]
I wonder if we ought to make that a non defaulted function to avoid this kind of error in the future, it would be only a single line of "noise" on trait impls that dont need to apply anything, and manually implementing this trait to begin with is remarkably niche (tbh same line of thought for `new_archetype` given that is pretty important to not mess up overriding the default of...)

**Review by BoxyUwU — APPROVED** [review]

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
@DJMcNab Can you add a quick test for this? Once that's done, I'm happy to merge it.

**Comment by DJMcNab** [comment]
Presumably we can't merge it until CI resurrects itself?

**Comment by alice-i-cecile** [comment]
https://github.com/bevyengine/bevy/pull/4675 was r+'ed an entire 4 minutes before you posted that ;)

**Pull request closed without merging**
