### PR TITLE
[Merged by Bors] - Bevy derives handling generics in impl definitions.

### LINKED ISSUE #2037: Derives ignore const generics
## Bevy version

0.5

## Operating system & version

Windows 10 (not sure this matters)

## What you did

I tried deriving `RenderResources` and `TypeUuid` for a struct with const generics:

```rust
#[derive(Debug, RenderResources, TypeUuid)]
#[uuid = "d6cb24b8-4e4a-4bca-87c5-fa500618a8f0"]
struct Foo<const N: u32> {
    value: u32,
}
```

## What you expected to happen

It should have included the const type parameters in the implementation.

## What actually happened

It didn't include the const type parameters:

```rust
#[uuid = "d6cb24b8-4e4a-4bca-87c5-fa500618a8f0"]
struct Foo<const N: u32> {
    value: u32,
}
#[automatically_derived]
#[allow(unused_qualifications)]
impl<const N: u32> ::core::fmt::Debug for Foo<N> {
    /* <snip> */
}
static FOO_RENDER_RESOURCE_NAMES: &[&str] = &["Foo_value"];
static FOO_RENDER_RESOURCE_HINTS: &[Option<bevy_render::renderer::RenderResourceHints>] =
    &[None];
impl bevy_render::renderer::RenderResources for Foo {
    fn render_resources_len(&self) -> usize {
        1usize
    }
    fn get_render_resource(
        &self,
        index: usize,
    ) -> Option<&dyn bevy_render::renderer::RenderResource> {
        match index {
            0usize => Some(&self.value),
            _ => None,
        }
    }
    fn get_render_resource_name(&self, index: usize) -> Option<&str> {
        FOO_RENDER_RESOURCE_NAMES.get(index).copied()
    }
    fn get_render_resource_hints(
        &self,
        index: usize,
    ) -> Option<bevy_render::renderer::RenderResourceHints> {
        FOO_RENDER_RESOURCE_HINTS.get(index).and_then(|o| *o)
    }
    fn iter(&self) -> bevy_render::renderer::RenderResourceIterator {
        bevy_render::renderer::RenderResourceIterator::new(self)
    }
}
impl bevy_reflect::TypeUuid for Foo {
    const TYPE_UUID: bevy_reflect::Uuid = bevy_reflect::Uuid::from_bytes([
        0xD6, 0xCB, 0x24, 0xB8, 0x4E, 0x4A, 0x4B, 0xCA, 0x87, 0xC5, 0xFA, 0x50, 0x6, 0x18,
        0xA8, 0xF0,
    ]);
}
```

### PR DESCRIPTION
**Pull request by NathanSWard**
Fixes #2037 (and then some)

Problem:
- `TypeUuid`, `RenderResource`, and `Bytes` derive macros did not properly handle generic structs. 

Solution:
- Rework the derive macro implementations to handle the generics.

### CODE REVIEW

**Comment by NathanSWard** [comment]
A few comments to take into account!

1) There are a few more derive marcos that do not handle generics (e.g. `RenderResources` (plural)), which should probably get included in this PR.

2) There are currently no tests for the specific scenarios that would have prevented #2037 . I would propose adding some integration testing inside `tests/` for the derive macros to ensure the use cases are tested.

**Comment by MinerSebas** [comment]
Could you edit the PR description to change `Addresses #2037` `Fixes #2037`, so that the issue is linked and automatically closed once this is merged.

**Comment by alice-i-cecile** [comment]
> There are currently no tests for the specific scenarios that would have prevented #2037 . I would propose adding some integration testing inside tests/ for the derive macros to ensure the use cases are tested.

I would like to see this; I think it's a sensible place to put them.

**Comment by cart** [comment]
I dig it!

I personally think the tests should live in the crates where the macros are actually consumed/exported (ex: `RenderResources` should be tested in `bevy_render`) and be tested wherever their trait is defined.

`bevy_derive` really only exists because Rust forces a separate crate for proc macros and I don't want duplicate crates for everything that needs a proc macro (ex: bevy_render_dervie, bevy_asset_derive, etc). In general we should just pretend that proc macros originate from their "real" crates (and discourage users from pulling in bevy_derive directly).

**Comment by NathanSWard** [comment]
Tests are added for `RenderResource`, `RenderResources`, and `TypeUuid` 😸

**Review by mockersf — APPROVED** [review]

**Comment by SafariMonkey** [comment]
I might be missing something here, but doesn't this mean that different instantiations of a generic type deriving `TypeUuid` will have the same UUID? Is that not a problem if each `TypeUuid` is supposed to uniquely identify a type?

I'd love tools for making generics and reflection work better together, of course. Maybe add a generic bound to the impl that the child is `TypeUuid` and merge them? That could hopefully be const (PRNG merging UUIDs), but worst case it could be at runtime with `TypeUuidDynamic`. I'm currently making a different newtype struct for each collection that has to be `TypeUuid`, though I might be doing something wrong - I hope there's a better way.

**Comment by cart** [comment]
Hmm yeah supporting generics on TypeUuid derives does seem wrong. I think we should revert that change.

**Comment by NathanSWard** [comment]
>I might be missing something here, but doesn't this mean that different instantiations of a generic type deriving TypeUuid will have the same UUID? Is that not a problem if each TypeUuid is supposed to uniquely identify a type?

@SafariMonkey this was fixed in #2204, that you for finding this bug!

**Pull request closed without merging**
