### PR TITLE
Add fps overlay

### PR DESCRIPTION
**Pull request by matiqo15**
Adopted from #5084
Thanks to @mockersf for starting this, and @x3ro for updated shader.
# Objective
- Add overlay to display fps

## Solution
- Add an overlay node that is rendered after everything else
- Display the FPS from a shader (reusing number rendering from https://www.shadertoy.com/view/lt3GRj)
- add / remove the overlay camera when user press left control + left shift + tab

### CODE REVIEW

**Comment by mockersf** [comment]
not that useful for me now because it's a builtin feature on macOS, with this env variable: `MTL_HUD_ENABLED=1`

**Comment by matiqo15** [comment]
Currently overlay isn't displayed, though keybinds are triggering spawning/despawning camera

**Comment by stepancheg** [comment]
Why render FPS using shader instead of just adding a text panel? That would be simpler and look better.

**Comment by matiqo15** [comment]
> Why render FPS using shader instead of just adding a text panel? That would be simpler and look better.

see https://github.com/bevyengine/bevy/pull/5084#issuecomment-1165767621

**Comment by stepancheg** [comment]
So we don't want to depend on `bevy_text` (we do't actually need `bevy_ui` I think), so we reimplement subset of `bevy_text`, but in shaders instead of Rust. Not sure this is reasonable, but I'm not a project maintainer. Thank you for the link!

**Comment by robtfm** [comment]
sorry but i don't think 600loc is justified for this. from that comment:

> To not add UI nodes to the layout which may break the layout of the game

you can use absolute positioning to avoid impacting other ui elements
> To not need a font file (we don't have one by default in Bevy)

we do if `default_font` feature is enabled (enabled by default in `bevy` crate)
> To still work in case people disable bevy_ui
> To not depend on the UiCamera

yes ... i think it's pretty reasonable that if you want an overlay ui you need bevy_ui. 🤷 
> I would like to have something like https://github.com/IceSentry/bevy_prototype_frametime_display_plugin in that makes more sense than just a number (but I'm trusting @IceSentry to add it after 😄 )

that would be nice, but this isn't it ... i expect it could be done far more cleanly now with `UiMaterial` anyway.

putting that aside, from an impl point of view (if you're interested to use a render graph node just for learning) i would recommend looking at the ViewNode impl on e.g. `PostProcessNode`. we shouldn't need a separate camera bundle, just a marker added to an existing camera. i would speculate that the node is not running because some component is missing on the bundle that is required to thread the view all the way through to rendering.

**Pull request closed without merging**
