### PR TITLE
[Merged by Bors] - Fix some typos

### PR DESCRIPTION
**Pull request by rparrett**
# Objective

Stumbled on a typo and went on a typo hunt.

## Solution

Fix em

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Review by james7132 — APPROVED** [review]
Wonder if we should have a CI check for common typos.

bors r+

**Comment by rparrett** [comment]
My bad. I'll follow up in a separate PR if I find more.

**Comment by rparrett** [comment]
> Wonder if we should have a CI check for common typos.

That approach might work/help I guess. In general I think there are way too many false positives for automation to help with this sort of thing.

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Pull request closed without merging**
