### PR TITLE
[Merged by Bors] - remove Box from ExclusiveSystemFn

### PR DESCRIPTION
**Pull request by R3DP1XL**
Minor refactor to remove the boxing of the function pointer stored in ExclusiveSystemFn.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Interesting, thanks. So this increases monomorphization, but exclusive systems are relatively rare.

This should very slightly hurt compile times, but somewhat improve runtime performance? That seems like a fine tradeoff.

My main concern is that doing this means that runtime system insertion might become harder down the line. However, it [looks like](https://github.com/bevyengine/bevy/blob/a1cf3cd332234497df37cf16e0cae234b06670e9/crates/bevy_ecs/src/system/function_system.rs#L234) we already do the same thing for non-exclusive systems, so this has my approval.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by R3DP1XL** [comment]
Thanks for the quick review Alice!

**Review by DJMcNab — APPROVED** [review]
This looks correct, and I agree that this change makes sense. The double indirection would otherwise be very unfortunate.

(I don't like that I don't trust our testing infrastructure to know whether exclusive systems not working would be caught, but that's not this PR's problem)

**Pull request closed without merging**
