### PR TITLE
Allow `ambiguous_with` with multiple system-type set instances

### PR DESCRIPTION
**Pull request by devil-ira**
`ambiguous_with` is for indicating there's no dependency between systems. I don't think a system should fail when multiple instances exist of a system it explicitly is not ordering itself relative to.

This is currently preventing adding additional instances of the transform propagation systems, which blocks `bevy_rapier`.

### CODE REVIEW

**Comment by maniwani** [comment]
> I don't think a system should fail when multiple instances exist of a system it explicitly is not ordering itself relative to.

This is working as intended and I'm glad this was caught. I added this rule specifically to stop people from carelessly referencing unknowably large sets of systems like, i.e. `ambiguous_with(apply_system_buffers)`. 

So the true problem is that `bevy_transform` [does that][0], and that should be changed to resolve your issue, just like in #7636.

0: https://github.com/bevyengine/bevy/blob/d1a1f90902ad98115d6f19105bd8382a214377a2/crates/bevy_transform/src/lib.rs#L106-L117

**Comment by alice-i-cecile** [comment]
Seconding the comment from @maniwani. This still needs to be fixed by 0.10, but their suggestion is the right way to do it.

**Comment by maniwani** [comment]
We can remove that restriction in the future, but I want to be shown a situation that requires something to be ambiguous with every instance of a system that might exist.

**Comment by alice-i-cecile** [comment]
> I'm open to removing that restriction in the future, if it can be shown there's a situation that requires something to be ambiguous with every instance of a system that might exist.

This might be the case for true false positives: stuff that might be caught by archetype invariants, truly order-independent queue addition, async task initiation. Definitely a larger and more controversial decision though that I would like to put off until we know more.

**Comment by alice-i-cecile** [comment]
Yeah, let's close this out: we can easily redo this later if we decide it's the right approach.

**Pull request closed without merging**
