### PR TITLE
Interpolating hues should use rem_euclid.

### LINKED ISSUE #12631: Use `rem_euclid` consistently throughout `bevy_color`
## What problem does this solve or what need does it fill?

Some of the early code by @viridia that works with hues implements `rem_euclid` manually.

## What solution would you like?

Use the `rem_euclid` method on `f32` directly.

### LINKED ISSUE #12632: Add tests to `bevy_color` to ensure that hue blending goes through the shortest path
## What problem does this solve or what need does it fill?

When working with cylindrical color spaces (see #12617) for more context, the `Mix` trait should always follow the shortest path, moving from e.g. orange to purple through red, rather than looping through green.

## What solution would you like?

We should add tests to each of our cylindrical color spaces to ensure that this is (and continues to be) the case.

## Additional context

This may make sense to tackle in the same PR as #12618.

### PR DESCRIPTION
**Pull request by viridia**
Also, added additional tests for the hue interpolation.

Fixes #12632
Fixes #12631

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
A full fix is waiting on #12619 to get merged first.

**Comment by alice-i-cecile** [comment]
I'm merging #12619 with the old approach since it is otherwise ready: can you merge main in (in about 10 minutes) and then clean up that code here?

**Review by alice-i-cecile — APPROVED** [review]

**Review by pablo-lua — APPROVED** [review]
Looks good! And the new tests are tasty.

**Review by NthTensor — APPROVED** [review]

**Comment by viridia** [comment]
@alice-i-cecile Done.

**Pull request merged**
