### PR TITLE
allow DeferredPrepass to work without other prepass markers

### PR DESCRIPTION
**Pull request by robtfm**
# Objective

fix crash / misbehaviour when `DeferredPrepass` is used without `DepthPrepass`.

- Deferred lighting requires the depth prepass texture to be present, so that the depth texture is available for binding. without it the deferred lighting pass will use 0 for depth of all meshes.
- When `DeferredPrepass` is used without other prepass markers, and with any materials that use `OpaqueRenderMode::Forward`, those entities will try to queue to the `Opaque3dPrepass` render phase, which doesn't exist, causing a crash.

## Solution

- check if the prepass phases exist before queueing
- generate prepass textures if `Opaque3dDeferred` is present
- add a note to the DeferredPrepass marker to note that DepthPrepass is also required by the default deferred lighting pass
- also changed some `With<T>.is_some()`s to `Has<T>`s

### CODE REVIEW

**Review by IceSentry — APPROVED** [review]
Haven't tested it but code makes sense to me

**Review by Elabajaba — APPROVED** [review]
I also haven't tested it but the code makes sense.

**Comment by DGriffin91** [comment]
I think this definitely could make sense. Worth nothing though that this will create a discontinuity between the which prepass components the camera has in the main world vs the render world if the user only adds the deferred prepass.

**Comment by robtfm** [comment]
i've been on a bit of a journey with this...

forcing the depth prepass whenever deferred is present is not ideal: if a scene has forward materials and deferred materials it forces the depth prepass to run for the forward materials even if not requested/required.

i thought maybe it would be better to make a new marker `DepthPrepassTextureRequired` and add it when DepthPrepass or DeferredPrepass are present. but, maybe somebody will implement a deferred lighting plugin that doesn't require the depth texture, so adding/copying the depth texture unconditionally still doesn't make sense. 
also, dealing with shader defs gets a bit tricky: the prepass depth texture won't be populated for forward materials, so the def should not be present in the main pass for forward materials. but the view BindGroupLayout still needs to contain the corresponding entry to match the BindGroup, which will have the texture. currently both the layout and the def are based on `MeshPipelineKey::DEPTH_PREPASS`, and adding an extra key bit for "DEPTH_TEXTURE_IS_IN_THE_GROUP_BUT_SHOULDNT_BE_AVAILABLE_TO_THE_SHADER_BECAUSE_IT_WONT_BE_POPULATED" seemed like overkill. 

so instead i just fixed the crash (we now check if the `xxx3dPrepass` phase exists before trying to queue to it), and added a note to the DeferredPrepass comment that it requires `DepthPrepass` as well. I also changed the condition on `prepare_prepass_textures` so the deferred textures are still created if only `DeferredPrepass` is present. this means the original issue of running depth prepass for forward materials is still present, but at least it doesn't crash, and if somebody wants to make a custom deferred pass that doesn't use depth then the DepthPrepass doesn't need to be added.

**Comment by JMS55** [comment]
@robtfm I think this needs rebasing or something, the diff seems weird.

**Review by JMS55 — APPROVED** [review]

**Review by IceSentry — APPROVED** [review]

**Review by cart — APPROVED** [review]

**Pull request merged**
