### PR TITLE
Clonable `Events<T>` resource

### LINKED ISSUE #3816: `Events<T>` doesn't implement `Clone`
## What problem does this solve or what need does it fill?

`Events<T>` doesn't implement `Clone`.

## Why

Implementing `Clone` for `Events<T>` would allow for cross-world events,
the question is whether it's a footgun or not.

### PR DESCRIPTION
**Pull request by MiniaczQ**
# Objective

- Add `Clone` to `Events<T>` to share it to another `World`.
- Fixes #3816 

## Solution

I added `Clone` derives to necessary objects.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by mockersf** [comment]
Thinking more about the "footgun" side that wasn't discussed more in the original issue, I don't think this is a good idea.
* If you have a `ResMut<Events<T>>` that you clone, you end up with an `events` that has a `send` method that will lose events send through it unless you overwrite the original resource, in which case you probably don't need to clone it
* Looking at the original case mentioned (cross world events), I would be more confortable with something like `to_event_view` that would give a structure with only a read access to those events rather than a full clone

**Comment by alice-i-cecile** [comment]
> Looking at the original case mentioned (cross world events), I would be more confortable with something like to_event_view that would give a structure with only a read access to those events rather than a full clone

I agree, but this won't work for cross-world events across the networks.

**Comment by mockersf** [comment]
Cloning the whole struct doesn't feel like a good strategy for network. You'll end up serialising your events, and you're going to have a hard time if you need to clone everything before serialising.

**Comment by MiniaczQ** [comment]
I'll be closing the PR, please move to the issue for further discussion.

**Pull request closed without merging**
