### PR TITLE
Work around naga/wgpu WGSL instance_index -> GLSL gl_InstanceID bug on WebGL2

### LINKED ISSUE #9375: WebGL2 rendering broken: correct transform are not used
## Bevy version

`main` since https://github.com/bevyengine/bevy/pull/9254

## \[Optional\] Relevant system information

On WebGL2, all browsers

## What you did

Run one of the 3d examples, easily visible on the `pbr` example

## What went wrong

Screenshot 2023-08-05 at 12 53 14

### PR DESCRIPTION
**Pull request by superdump**
naga and wgpu should polyfill WGSL instance_index functionality where it is not available in GLSL. Until that is done, we can work around it in bevy using a push constant which is converted to a uniform by naga and wgpu.

# Objective

- Fixes #9375 

## Solution

- Use a push constant to pass in the base instance to the shader on WebGL2 so that base instance + gl_InstanceID is used to correctly represent the instance index.

## TODO

- [ ] Benchmark vs per-object dynamic offset MeshUniform as this will now push a uniform value per-draw as well as update the dynamic offset per-batch.
- [x] Test on DX12 AMD/NVIDIA to check that this PR does not regress any problems that were observed there. (@Elabajaba @robtfm were testing that last time - help appreciated. <3 )

---

## Changelog

- Added: `bevy_render::instance_index` shader import which includes a workaround for the lack of a WGSL `instance_index` polyfill for WebGL2 in naga and wgpu for the time being. It uses a push_constant which gets converted to a plain uniform by naga and wgpu.

## Migration Guide

Shader code before:

```
struct Vertex {
    @builtin(instance_index) instance_index: u32,
...
}

@vertex
fn vertex(vertex_no_morph: Vertex) -> VertexOutput {
...

    var model = mesh[vertex_no_morph.instance_index].model;
```

After:

```
#import bevy_render::instance_index

struct Vertex {
    @builtin(instance_index) instance_index: u32,
...
}

@vertex
fn vertex(vertex_no_morph: Vertex) -> VertexOutput {
...

    var model = mesh[bevy_render::instance_index::get_instance_index(vertex_no_morph.instance_index)].model;
```

### CODE REVIEW

**Review by robtfm — COMMENTED** [review]
code looks good to me.

works on win/nvidia with vulkan and dx12. i always forget how to best test wasm...

**Review by mockersf — APPROVED** [review]
OK for me on metal, webgl2 and webgpu

**Comment by superdump** [comment]
@robtfm I use the wasm-server-runner approach from https://bevy-cheatbook.github.io/platforms/wasm.html to test wasm builds

**Review by robtfm — APPROVED** [review]

**Comment by mockersf** [comment]
it has this error with webgl2 in CI:
```
ERROR    Handling wgpu errors as fatal by default log.target = "wgpu::backend::direct";
log.module_path = "wgpu::backend::direct";
log.file = "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs";
log.line = 3018;
panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 1, Gl)>`
    In a set_push_constant command
    Provided push constant is for stage(s) ShaderStages(VERTEX), however the pipeline layout has no push constant range for the stage(s) ShaderStages(VERTEX)
```

**Pull request merged**
