### PR TITLE
Storage Support in AsBindGroup

### LINKED ISSUE #5499: Storage Support in AsBindGroup
## What problem does this solve or what need does it fill?

Currently I use the `storage` binding to pass a vector of elements to a shader. Storage should be supported on the new `AsBindGroup` derive, otherwise it isn't really a replacement.

## What solution would you like?

Support writing`#[storage(0)]` the same way `#[uniform(0)]` is supported.

## What alternative(s) have you considered?

None, this is a pretty small change that fits in to the rest of the AsBindGroup macro, just seems like a strange missing piece.

### PR DESCRIPTION
**Pull request by blaind**
# Objective

Fixes #5499

## Solution

- Implement `#[storage(..)]` enum in AsBindGroup macro
- Have an example with both read and write storage buffers

---

### Added

- New `#[storage(..)]` enum in AsBindGroup macro

### CODE REVIEW

**Comment by james7132** [comment]
What's the difference between this PR and #6129?

**Comment by blaind** [comment]
> What's the difference between this PR and #6129?

Didn't know about that before, wasn't linked to the issue #5499. Same approach, this one has an example as well.

**Comment by IceSentry** [comment]
It wasn't linked because I didn't even know the issue existed 😅 I only created that PR because I was playing with storage buffers and didn't see a PR.

**Comment by IceSentry** [comment]
Also, it doesn't support any type, it only works for types that implement ShaderType.

**Comment by james7132** [comment]
With #6129 merged, I'm closing this PR. If the solution in that PR doesn't fit the needs here, either open a new PR or rebase this one to add the missing features required.

**Comment by IceSentry** [comment]
Having the example from this PR would still be worth it. @blaind let me know if you want to open a separate PR or change this one with the example. Otherwise I'll open one with only the example.

**Comment by blaind** [comment]
This pull request supports a `Buffer` type, which allows flexibility. E.g. user can have a multi-gigabyte buffer and update only a small slice of that in a frame.

#6129 seems to have bevy-internal conversion, where the whole type is converted into a buffer on each update, and transferred from CPU to GPU at once.

The example in this one is not usable for #6129 I think

**Comment by blaind** [comment]
Can this one be reopened (I can't do it)? I'll rebase later to main later.

**Comment by IceSentry** [comment]
For the example, I meant to have a similar example but updated to support #6129

If you see think both functionality can co-exist then that's even better

**Comment by alice-i-cecile** [comment]
Added via #14663.

**Pull request closed without merging**
