### PR TITLE
Add bevy_pbr as a dependency to bevy_gizmos

### LINKED ISSUE #10984: Using `bevy_gizmos` feature with `default-features=false` renders nothing (requires extra `bevy_pbr` feature)
## Bevy version

0.12

## What you did

Tried to use `bevy_gizmos` with the following `bevy` dependency configuration:

```toml
[dependencies.bevy]
version = "0.12"
default-features = false
features = ["bevy_gizmos"]
```

## What went wrong

Gizmos were not drawn.

## Additional information

The fix was to add the `bevy_pbr` feature:

```toml
[dependencies.bevy]
version = "0.12"
default-features = false
features = ["bevy_gizmos", "bevy_pbr"]
```

I think we just need to add an explicit dependency on `bevy_pbr` here:

https://github.com/bevyengine/bevy/blob/ca1874e6c612d73306173065242aaaa8733c9b20/Cargo.toml#L132

### PR DESCRIPTION
**Pull request by hecksmosis**
# Objective

- Fixes #10984 

## Solution

- Add bevy_pbr as a dependency for bevy_gizmos

### CODE REVIEW

**Review by matiqo15 — APPROVED** [review]

**Comment by IceSentry** [comment]
Like @irate-devil said in the comments of the original issue:

> Always adding bevy_pbr as a feature would prevent users that only need bevy_sprite from disabling it, and vice versa.

So I'm not sure this is the right solution.

**Comment by hecksmosis** [comment]
bevy _sprite doesn't require bevy_gizmos does it?

**Comment by mockersf** [comment]
it should be possible to draw gizmos without having to bring `bevy_pbr`
for example `cargo run --example 2d_gizmos --no-default-features --features "bevy_winit,bevy_ui,bevy_gizmos"` works and doesn't bring `bevy_pbr`

**Comment by mockersf** [comment]
fixed in #11296

**Pull request closed without merging**
