### PR TITLE
Align `Scene::write_to_world_with` to match `DynamicScene::write_to_world_with`

### PR DESCRIPTION
**Pull request by dmyyy**
# Objective

Fixes a regression in [previously merged but then reverted pr](https://github.com/bevyengine/bevy/pull/13714) that aligns lower-level `Scene` API with that in `DynamicScene`. Please look at the original pr for more details.

The problem was  `spawn_sync_internal` is used in `spawn_queued_scenes`. Since instance creation was moved up a level we need to make sure we add a specific instance to `SceneSpawner::spawned_instances` when using `spawn_sync_internal` (just like we do for `DynamicScene`). 

Please look at the last commit when reviewing.

## Testing

`alien_cake_addict` and `deferred_rendering` examples look as expected.

## Changelog

Changed `Scene::write_to_world_with` to take `entity_map` as an argument and no longer return an `InstanceInfo`

## Migration Guide

`Scene::write_to_world_with` no longer returns an `InstanceInfo`. 

Before
```rust
scene.write_to_world_with(world, &registry)
```
After
```rust
let mut entity_map = EntityHashMap::default();
scene.write_to_world_with(world, &mut entity_map, &registry)
```

### CODE REVIEW

**Comment by dmyyy** [comment]
@alice-i-cecile Anything I can do on my end to move this pr along?

**Comment by alice-i-cecile** [comment]
Can you swap this to a more descriptive title and then post about this in `#scenes-dev` please?

**Review by alice-i-cecile — APPROVED** [review]

**Comment by dmyyy** [comment]
@NthTensor You approved the last version - do you have a chance to take a look at this updated one?

**Review by MrGVSV — APPROVED** [review]
I'm not too familiar with this part of the scene stuff but I think the change makes sense. It also seems to be in line with the call to `Self::spawn_dynamic_internal` a few lines up.

**Comment by MrGVSV** [comment]
@dmyyy I'd also recommend updating your PR description as parts of it are from #13714 and don't really have to do with this fix

**Comment by dmyyy** [comment]
> ~@dmyyy I'd also recommend updating your PR description as parts of it are from #13714 and don't really have to do with this fix~
> 
> Never mind, I didn't realize that PR was reverted and this is re-applying those commits.

The description is a little bit confusing - I updated the wording a little

**Review by pcwalton — COMMENTED** [review]
I'll defer to the other reviewers because I don't know this code as well, but as long as it doesn't break test cases this is fine.

**Comment by alice-i-cecile** [comment]
I've double-checked the examples and no regressions this time :)

**Pull request merged**
